#+PROPERTY: header-args:latex :tangle ../../tex/ch1/revelacion.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros


* /Lectio/: 
:DESCRIPTION:

:END:
** Análisis
En este primer capítulo nos preguntamos \textquestiondown{}Cuál testimonio es
Revelación de Dios? \textquestiondown{}Qué papel juega el testimonio en la Dinámica de
la Revelación y su transmisión? Como referencia principal tendremos el artículo de
Latourelle sobre el Testimonio en el Diccionario de Teología Fundamental.


* /Propositum/:  
:DESCRIPTION: 

:END:

** Propositio: El testimonio en la dinámica de la Revelación
#+BEGIN_SRC latex
  % SECCIÓN 1: El testimonio en la dinámica de la revelación
\section{El testimonio en la dinámica de la Revelación}
#+END_SRC


* /////////////////////////////////////////////////////////
* /Quaestio/: Lo que hemos visto y oido 
:STATEMENT:

:END:
:DISCARDED:

:END:
:DESCRIPTION:

:END:
 
#+BEGIN_SRC latex
  Lo que existía desde el principio, lo que hemos oído, lo que hemos visto con
  nuestros ojos, lo que contemplamos y palparon nuestras manos acerca de la
  Palabra de vida –pues la Vida se manifestó, y nosotros la hemos visto y damos
  testimonio y os anunciamos la Vida eterna, que estaba junto al Padre y que se
  nos maifestó– lo que hemos visto y oído os lo anunciamos, para que también
  vosotros estéis en comunión con nosotros. Y nosotros estamos en comunión con el
  Padre y con su Hijo Jesucristo. Os escribimos esto para que nuestro gozo sea
  completo. (1Jn 1, 1–4)

#+END_SRC


* /Expositio/: What is truth?
:STATEMENT:

:END:


\subsection{Cristo Testigo}

\subsection{La transmisión de la revelación: el Testimonio apostólico}

\subsection{El testimonio de la fe en el martirio}




* /Disputatio/: 
:STATEMENT: 

:END:


* /Solutio/: 
:STATEMENT:

:END:

* /In Testimonium/: 
:STATEMENT:

:END:


* [Local Variables]
# Local Variables:
# mode: org
# mode: auto-fill
# word-wrap:t
# truncate-lines: t
# org-hide-emphasis-markers: t
# End:
