* Preamble

ALL settings handled here
settings files go to tex/style
including
bibsettings.tex
final.sty
csquote.cfg??
fonts folder
etc...

final.tex goes to /tex

!BASIC FUNCTIONAL STUFF in the preamble

STYLE TEMPLATE STUFF IN final.sty

CITATION AND BIBLIOGRAPHY STUFF IN bibsettings.tex

#+BEGIN_SRC latex :tangle ../tex/final.tex
%Base Document Class
\documentclass{scrbook}

%PACKAGES
%subfiles to include the chapters
\usepackage{subfiles}

%BIBLIOGRAPHY
%\input{../bibliography/style/bibsettings.tex}
\input{style/bibsettings.tex}

%The bibliography database
\addbibresource{../bibliography/bibliodb/primary.bib}
\addbibresource{../bibliography/bibliodb/secondary.bib}


%hyperref to handle cross-referencing commands
%\usepackage[hyperfootnotes=false]{hyperref}
%ifdraft for notes and todos activation
%\usepackage{ifdraft}
%verbatim for multiline comments
%\usepackage{verbatim}
%Easy Lists
%\usepackage[ampersand]{easylist}


\usepackage[main=spanish,english,greek]{babel}

% STYLE
%Load ./final.sty
\usepackage{style/final}

%\usepackage{graphicx}

% More Math Symbols (therefore)
%\usepackage{amsmath}
%\usepackage{amssymb}

%Mathspec for math and fontspec for the rest
%\usepackage{mathspec}
%\usepackage[no-math]{fontspec}
\usepackage{layouts}

\begin{document}
#+END_SRC

** Stuff to do
chequear los esto y este y solo, cuidado de no cambiar los textos citados

revisar también los enquotes....

términos o conceptos van entre comillas simples
expresiones o referencias a expresiones hechas ``''
citas de documentos <<>>

dentro de las citas no se usa enquote, sin las comillas como aparecen en el texto

revisar títulos y subtitulos... puntuación y  mayusculas/minusculas

buscar una traducción española de hume, lessing y las obras de W. no traducidas por anscombe

check escritura con mayúscula, tambien revelacion e iglesia

verificar guiones largos, añadir espacios pequeños

* SUBFILES
#+BEGIN_SRC latex :tangle ../tex/final.tex
%\input{./tester.tex}

\tableofcontents
\thispagestyle{empty}
\addtocontents{toc}{\protect\thispagestyle{empty}}

\setcounter{page}{0}

%INTRODUCCIÓN
%Introducción General al Problema del Testimonio
\subfile{./intro}
%CAPÍTULO 1:
%Introducción General al Problema del Testimonio
%\subfile{./ch1}
%CAPÍTULO 2:
%Vida y Pensamiento Propio de Elizabeth Anscombe
%\subfile{./ch2}
%CAPÍTULO 3:
%La concepción de Elizabeth Anscombe sobre el Testimonio
%\subfile{./ch3}
%CAPÍTULO 4:
%Conclusión General
\subfile{./ch4}

%Bibliography
%\clearpage
%\addcontentsline{toc}{chapter}{Bibliography}
\subfile{./bibliography}
#+END_SRC

#+BEGIN_SRC latex :tangle ../tex/final.tex
\end{document}
#+END_SRC

* Style
Setear csquotes para que ponga el numero de cita antes del punto. también para citar la biblia y magisterio en paréntesis en el texto
** Package name
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
\ProvidesPackage{style/final}
#+END_SRC
** Directrices
*** El Texto del cuerpo del documento, tamaño de letra 10pt.
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
\KOMAoptions{fontsize=10pt}
#+END_SRC
*** Tamaño de papel:  La tesina ha a de estar escrita en un formato de papel DIN‐A4,  “A4 (21 cm x 29,7 cm)” Debido a la encuadernación la tesina debe llevar una serie de márgenes muy concretos:
   - Superior: 6cm
   - Inferior: 6cm
   - Interior: 2,5cm
   - Exterior: 6,5cm
   - Encuadernación: 0cm
   - Posición del margen interno: Izquierda
   - Márgenes simétricos
   - Encabezado: 1,25cm (desde el borde)
   - Pie de página: 4cm (desde el borde)
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
\KOMAoptions{twoside=true}
%No header, page number at footer.
\pagestyle{plain}

\usepackage[
a4paper,
inner=2.5cm,
outer=6.1985cm,
top=5.887748cm,
bottom=5.887748cm,
bindingoffset=0cm,
footskip=1cm,
footnotesep=0.5cm,
%showframe,
%heightrounded,
nohead,
]{geometry}


#+END_SRC
*** La tipografía para a todo el texto es “Arial Unicode MS”.
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
%Extra math symbols
\usepackage{amsmath}
\usepackage{amssymb}

%Mathspec for math and fontspec for the rest.
\usepackage{mathspec}
\usepackage[no-math]{fontspec}
\usepackage{xltxtra,xunicode}

%Set sans font to Arial.
\setsansfont[
Path= ./font/arial/,
BoldFont=arialbd.ttf,
ItalicFont=ariali.ttf,
BoldItalicFont=arialbi.ttf,
]{arial.ttf}

%Set default font to sans.
\renewcommand{\familydefault}{\sfdefault}

%Set math font to arial.
\setmathsfont(Digits,Latin)[
Path= ./font/arial/,
ItalicFont=ariali.ttf,
Ligatures=TeX]{arial.ttf}

%Arial Unicode for greek text
\newfontfamily\greekfont[
Path= ./font/arial/,
Scale=MatchUppercase,
Ligatures=TeX]{arialuni.ttf}

\renewcommand{\textgreek}[1]{\bgroup\greekfont{#1}\egroup} % Greek text
#+END_SRC
*** Interlineado de 17 pt .
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
\usepackage{setspace}
\setstretch{1.41667}
#+END_SRC
*** La primera línea de cada párrafo tiene una sangría a de 1,25 cm
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
\KOMAoptions{parskip=off}
\setlength{\parindent}{1.25cm}

#+END_SRC
*** Los títulos de inicio del capítulo o sección irán centrados, en mayúsculas, negrita y a 12pt. NOTA IMPORTANTE: Los títulos de inicio del capítulo o sección deben quedar en página impar.
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
\renewcommand*\thechapter{\Roman{chapter}}
\renewcommand{\raggedchapter}{\centering}
\addtokomafont{chapter}{\sffamily\bfseries\fontsize{12pt}{12pt}\selectfont}

#+END_SRC
*** Los títulos  del primer nivel irán en negrita y sin sangría; los del segundo nivel en negrita y con sangría de 0,5 cm;  los de tercer y cuarto nivel, irán sin negrita y con sangría de 0,5 cm.
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
\setcounter{secnumdepth}{5}
\renewcommand*\thesection{\arabic{section}}
\addtokomafont{section}{\sffamily\bfseries\fontsize{10pt}{10pt}\selectfont}
\addtokomafont{subsection}{\sffamily\bfseries\fontsize{10pt}{10pt}\selectfont}
\addtokomafont{subsubsection}{\sffamily\mdseries\fontsize{10pt}{10pt}\selectfont}


\RedeclareSectionCommand[%
%expandtopt=true,%
beforeskip=-1em,%
]{section}

\RedeclareSectionCommand[%
beforeskip=-1em,%
indent=0.5cm,%
]{subsection}

\RedeclareSectionCommand[%
indent=0.5cm,%
]{subsubsection}

%\let\oldsection\section
%\def\section{\filbreak\oldsection}

#+END_SRC
*** Las notas al pie de página deben estar justificadas y sin sangría. La letra tendrá un tamaño de 8pt
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
% Defaults are sufficient.
\deffootnote[1.5em]{0em}{0em}{%
\textsuperscript{\thefootnotemark}\,%
}
#+END_SRC
*** Las citas literales de una obra, citadas en el cuerpo de el texto, irán entrecomilladas, excepto cuando tengan más de tres líneas, en cuyo caso será un párrafo independiente con una sangría de 1, 2 cm y opcionalmente en cursiva.
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
%csquotes for advanced facilities for inline and display quotations
\usepackage[autostyle,spanish=spanish,maxlevel=2]{csquotes}

\renewenvironment{quotation}
{\list{}{\listparindent=0cm%whatever you need
         \itemindent    \listparindent
         \leftmargin=1.2cm%  whatever you need
         \rightmargin=0cm%whatever you need
         \topsep=.25em%%%%%whatever you need
         \parsep        \z@ \@plus\p@}%
         \item\relax}
{\endlist}

\SetBlockEnvironment{quotation}

\renewcommand{\mkcitation}[1]{\footnote{#1}}
\renewcommand{\mktextquote}[6]{#1#2#3#6#4#5}
\renewcommand{\mkblockquote}[4]{#1#4#2#3}
#+END_SRC
*** URLs en citas
#+BEGIN_SRC latex :tangle ../tex/style/final.sty
% URL
\usepackage{url}
% By default the URLs are put in typewriter type in the body and the
% bibliography of the document when using the \url command.  If you are
% using many long URLs you may want to uncommennt the next line so they
% are typeset a little smaller.
% \renewcommand{\UrlFont}{\small\tt}
\renewcommand{\UrlFont}{\sffamily}
#+END_SRC

* Bibliografía

REPETICIÓN DE CITAS
Cuando se cita de nuevo la última obra citada, úsese:
Ibid. / ibid.
Cf. ibid., 34.
Ibid., 2-3.
Cuando se cita de nuevo el último autor/autora citado/a, úsese:
ID. / EAD.
C. Gil, “ley”, en: ID. (ed.), El Pentateuco (Madrid 2000) 23.

Cuando en el trabajo se señala la misma obra varias
veces, a partir de su segunda aparición se abrevia la
cita:
- No se ponen las iniciales de los nombres, ni la función de
editores/directores…
- se indican sólo las primeras palabras del título
- señálese el volumen de la obra cuando haya posibilidad de confusión
PACoMio et alii, “dios existe”, 235-240.
ColoMBo, Gli archivi imperfetti, 131-132.
Gil, El Antiguo Testamento iii, 282-283.
Cuando se cita por primera vez un artículo, pero de un
libro ya citado, éste se abrevia según lo ya dicho:
P. BAldelli, “Gli ospizi negli stati italiani”, en: renCkstorF –
MCQuAil, Novel evidence for Roman slavery, 121-146.
20
si por la naturaleza del trabajo conviene citar el año de
edición de la obra, puede hacerse:
ColoMBo, Gli archivi imperfetti, 1982, 131-132.


#+BEGIN_SRC latex :tangle ../tex/style/bibsettings.tex
\usepackage[
backend=biber,
%bibstyle=style/custom-authortitle,
%citestyle=../bibliography/style/verbose-ibid-custom,
%citestyle=style/custom-verbose-trad1,
bibstyle=authortitle,
citestyle=verbose-trad1,
opcittracker=false,
loccittracker=constrict,
%bibstyle=authortitle,
%citestyle=verbose-ibid,
%refsection=section,
%giveninits=true,
%autocite=footnote,
%block=none,
%useprefix=true,
%sorting=nyvt,
%isbn=false,
%url=false,
%autopunct=false,
pagetracker=spread,
ibidpage=true,
%hyperref=false,
]{biblatex}

\DefineBibliographyStrings{spanish}{%
    andothers = {et al.},
    in = {\lowercase{e}n:},
    editor = {(\lowercase{e}d.),},
    editors = {(\lowercase{e}ds.),},
}

#+END_SRC
