#+PROPERTY: header-args:latex :tangle ../../tex/ch3/3_2.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* /Lectio/: 
:DESCRIPTION:
Truth: Anselm or Thomnas?
Truth: Anselm and Wittgenstein/Verdad
'Making True'

:END:
** Análisis
Atender la razonabilidad de la tarea de dar testimonio del Hecho de Cristo como
anuncio de salvación supone:
<<recuperar la legitimidad de la pregunta filosófica y religiosa sobre la
verdad, en un tiempo que parece a priori que la rechaza.>>

En el contexto de la filosofía analítica la pregunta sobre la verdad (y la
falsedad) está entrelazada con la pregunta sobre el significado.

Wittgenstein, que "amó la verdad" ofreció más atención a la verdad que al
significado en el Tractatus, mientras que en las Investigaciones Filosóficas
parece ser al revés. ¿Anscombe atiende estos temas de la misma manera?

- En los escritos de Anscombe ambos temas se tratan por separado pero gozan
  aproximadamente del mismo status.
- El significado se ~

* /Propositum/:  
:DESCRIPTION: 

:END:

** Propositio: "Verdad y Significado"
#+BEGIN_SRC latex
  % SECCIÓN 1: La verdad
\section{Verdad y Significado}
#+END_SRC


* /////////////////////////////////////////////////////////
* /Quaestio/: What is to have truth? 
:STATEMENT:
The proposition has a sense which is independent of the facts.
:END:
:DISCARDED:

:END:
:DESCRIPTION:

:END:
 
#+BEGIN_SRC latex
Quaestio
#+END_SRC


* /Expositio/: What is truth?
:STATEMENT:

:END:


* /Disputatio/: 
:STATEMENT: 

:END:


* /Solutio/: 
:STATEMENT:

:END:

* /In Testimonium/: 
:STATEMENT:

:END:


* [Local Variables]
# Local Variables:
# mode: org
# mode: auto-fill
# word-wrap:t
# truncate-lines: t
# org-hide-emphasis-markers: t
# End:
