#+PROPERTY: header-args:latex :tangle ../../tex/ch1/intro_prob_test.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros
* "Testimonio"
** PARTE I
Situación de Nuestros Días

La crisis como síntoma:
Hipótiesis central.
El malestar es siempre síntoma indeleble del carácter en última instancia infinito del
conjunto de exigencias y evidencias que constituyen la experiencia elemental, común a
todo hombre, cuya realización se abre a la constitutiva religiosidad humana. (test
p.8>de lubac y giussianni)
Si eso es así, y la crisis económica y social remite a una dimensión antropológica y
religiosa, debemos entrar en ese orden de realidades para ofrecer una contribución
válida a la convivencia en las sociedades plurales de occidente.

Un mundo multicultural
Entre multiculturalismo y globalización
Como se ve, será de la mayor importancia delinear de modo adecuado la originalidad
irreductible del acontecimiento cristiano -hecho singular de relevancia universal- y su
modo propio de comunicación -el testimonio-, para asegurar con ello la permanencia
efectiva del anuncio de Cristo a los hombres de todas las culturas.

Por una parte se debe distinguir el cristianismo de las ideologías occidentales
(evangelización =/= occidentalización)

Por otra parte, sólo un cristianismo genuino podrá ayudar a los hombres de occidente a
afrontar sus propios dilemas no resuletos sobre el uso de la razón y su relación con la
religión, a la luz de aquella primera síntesis ejemplar de fe y razón que surgió del
diálogo entre el evangelio -nacido en el ambiente judío- y el mundo grecorromano(p. 11)



En el debate sobre multiculturalismo ofrecer una reflexión (in)acabada desde nuestro
enfoque propio: teología fundamental. indicamos algunas claves que puedan ayudar a
profundizar en este debate para precisar la comprensión de la fe cristiana en este
mundo plural como contexto en el que luego situar la doctrina cristiana sobre el
testimonio (p. 13)

1. El debate está siendo beneficioso para la cultura moral y jurídica occidental si
   tomamos como referencia el análisis de Alain Finkielkraut, de 'la' cultura a 'las'
   culturas y derechos de los ciudadanos como antídoto al relativismo de las
   identidades comunitarias
2. discusión sobre la importancia de los aspectos culturales de las comunidades tiene
   como contexto hoy una sociedad posindustrial y globalizada
   a. los factores que sostenian el modelo de separación público-privado: el estado
   moderno y el ciudadano individual, están sufriendo cambios
   b. la difusión de diferencias culturales lleva a replantear algunos temas clásicos
   de la teoría jurídica y social clásica como son la relación entre identidades y
   ciudadania o entre identidades y democracia
3. **discusiones acerca del tipo de racionalidad capaz de afrontar los retos sociales,
   culturales y políticos que conlleva. Sin lugar a dudas, la reelaboración adecuada de
   la racionalidaden el ámbito de las ciencias sociales y de la filosofía es una de las
   premisas necesarias para poder afrontar hasta el final los desafíos multiculturales
   den la perspectiva del testimonio cristiano como veremos.**
4. Debates acerca de la relación entre multiculturalidad y etnicidad. No todas las
   diferencias culturales son de tipo étnico. En este contexto llama la atención la
   estima que encuentra la categoría de mestizaje para superar los límites que todos
   advierten en ciertos planteamientos de la multiculturalidad

En resumen:
1. autores ofrecen crítica del relativismo cultural excluyente
2. desde perspectivas antropológicas y sociológicas e históricas se reinvindica un
   universalismo que permita la comunicación y comparación entre las culturas
3. remitida la necesidad de sentido de la experiencia humana sobre el que se puedan
   entablar intercambios q permitan construir la realidad de una sociedad común
4. se reconoce la necesidad de superar la división entre esfera pública y privada para
   afrontar convincentemente los desafíos que la sociedad ulticultural plantea
5. advertencia de oscilación entre el valor de una identidad comunitaria y valor
   universal del sujeto indiviudal
6. la categoría de mestizaje adquiere un protagonismo nuevo para describir la mezcla de
   hecho y expresar la indistición original y la igualdad plena entre los hombres.



Una sociedad multirreligiosa y (post)secular

Retorno a lo religioso
En una sociedad postsecular, retorno a lo religioso, pero el subjetivismo religioso y
el fundamentalismo violento tienen que ser purificados desde la razón. No actuar desde
la razón es contrario a la naturaleza de Dios.

El problema de la verdad en el contexto de las religiones
no es aceptable una solución para la compatibilidad entre religión, filosofía y cultura
que desde una postura relativista moderna diga adios a la verdad, como una promoción de
un cristianismo de la caridad sin referencia a la verdad. no hace justicia a la
exigencia filosófica de buscar y conocer la verdad, y tampoco hace justicia al Dios de
Jesucristo.

Frente a la tentación de una religión -o de una filosofía que se desentiende de la
pregunta por la verdad se debe reinvindicar que no hay religión humana que no atienda a
la exigencia racional, así como no hay itinerario humano de la razón que no consista en
la búsqueda de la verdad y del significado último de la vida.

la fe católica sostiene que Dios mismo se ha encarnado y, en consecuencia, es posible
que la libertad humana (situada siempre históricamente) lo encuentre en la historia
donde coexisten las religiones. las invitaciones de la iglesia al diálogo son una
dimensión intrínseca de la misión evangelizadora y no simple táctica para facilitar la
convivencia.

El cristianismo en la sociedad actual

I. No universalidad del hecho del cristianismo

A. pretensión cristiana en el mundo multicultural y post secular
Cita de introducción al cristianismo 117-127
el cristianismo al irrumpir en la escena cultural del mundo se orientó a interpelar mas
a la filosofía que a las religiones.

rtzinger argumenta que la fe cristiana carece de universalidad de facto (aunque tiene
pretensión universal)

Cuando decimos que la verdad de todo hombre se manifiesta en el acontecimiento de
Cristo, ¿podemos afirmar que esa manifestación es aquí y ahora tan real como lo fue
para los discípulos? y ¿se puede afirmar que la presencia de esa persona viva, Jesús,
fundamenta una salvación de carácter universal? Este desafío sigue presente en nustra
sociedad. De cómo la fe responda a esta objeción formulada, entre otros, por una
ilustración insatisfecha, depende la solución a la cuestión de la argumentación pública
de los cristianos en la sociedad democrática, a su credibilidad racional, como pedía
Habermas. ******<

B. Insuficiencia de un puro método de integración
No cabe legitimar la posición cristiana mediante una mera acumulación racional de
argumentos que integre las verdades que otros poseen. Hay que justificar el significado
de ese más del cristianismo evitando esto y también lo otro: el que se convierta en un
postulado puramente voluntarista, irracional

al plantear un metodo testimonial para el anuncio cristiano se pretende ofrecer un
método alternativo al de integración y se busca evitar los dos extremos indeseados: la
reducción racionalista y la reducción irracional


C. Autorelativización del cristianismo
disociasiones:
- afirmación hacia adentro del valor absoluto y relativización hacia afuera
- las tradiciones religiosas pueden ser estimadas al precio de verse reducidas a mera
  función referencial de una determinada realidad colectiva
- la verdad del cristianismo sería aceptable a condición de que aparezca sólo como una
  de las posibles razones subjetivas de compromiso social, fe en Dios sería un
  corolario opcional del compromiso ético o religioso
- disociacion fe-caridad, caridad separada de su raiz teologal
- ****dificultad desde el punto de vista linguístico. posturas que distinguen entre una
  relación inefable con el misterio y la insuficiencia de las expresiones linguísticas.
La posibilidad de un diálogo es que la experiencia cristiana sea completa en su
naturaleza y en su comunicación


II. Hacia una interpretación pública de la fe cristiana
síntesis de lo visto (p. 45)
A. Inevitable interpretacion cultural de la fe
dos posturas que no expresan la verdadera naturaleza del cristianismo y su modo de
presencia en la sociedad: cristianismo como religión civil (con una finalidad ética),
cristianismo como sólo anuncio de la cruz (desligado de las cuestiones éticas)
para superar los límites de ámbas necesitmos una interpretación cultural del
cristianismo den la cual, por una parte, el acontecimiento de Jesucristo se muestre en
toda su integridad teologal y por otra se perciba la peculiar razonabilidad propia de
un acontecimiento singular


B. La separación fe y vida en occidente
****La contribución de los cristianos sólo es decisiva si la inteligencia de la fe se
convierte en inteligencia de la realidad, clave de juicio y de transformación

- drama de la separación fe y razón - cristianismo dividido división inteligencia de la
  fe - inteligencia de la realidad se produce un creciente alejamiento, una extrañeza
  entre la mentalidad común y la fe cristiana
- debilitamiento del yo: urge mostrar una comprensión filosófica y teológica del acceso
  humano a la verdad que haga justicia, por una parte, a la verdadera condición del
  hombre en su plena unidad, y por otra, a la índole original del cirstianismo como
  acontecimiento.

III. La necesaria superación del carácter extrínseco de la relación entre fe y razón
síntesis de lo anterior***<(p.59)
A. Superar una concepcion racionalista de razón

B. Fe y saber

C. Fe no es extrínseca a la razón
entre la fe teologal y la visio beatifica hay una diferecnia que no es esencial, sino
de grado. En ese sentido quizá lo mas correcto sea considerar la fe como un
conocimiento indirecto a traves de signos visibles (sacramento, testigo), que remiten a
un fundamento invisible y a una plenitude definitiva en el cielo.

la fe es una forma de conocimiento de la verdad, singularísima por su origen, su medio
y su fin, y a la vez correspondiente con los dinamísmos humanos de razón y libertad que
no se ven mortificados o destruidos, sino exaltados en su índole propia.

en el hombre de fe no se superpone un don ajeno (alienante) al orden de la razón, sino
que por la gracia el creyente ejerce su propia razón del modo más pleno posible para
reconocer aquel Hecho singular que es la encarnación redentora (FR 13)

D. La manifestación del absoluto en la historia
El hombre concreto, al descubrir cada vez más el contenido filial y fraternal de su
exitencia, puede poner más en juego su capacidad de adhesión y de decisión
(autodominio), es decir, se convierte cada vez más en él mismo. LLega así en el tiempo
de la vida y por la gracia de Dios a realizar el ideal de conocimiento verdadero de sí
mismo y de plena libertad en la acción, por el que han suspirado los hombres
antiguos y modernos.



IV. Los ejes de la reflexión: la revelación y la fe; el conocimiento de la realidad; la
vida de la Iglesia y el diálogo con los hombres de hoy


** PARTE III
CAP III
Problema formulado contraponiendo la razón con la tradición/autoridad...

¿puede el hombre conocer el
* Analogía teológica
  :LOGBOOK:
  CLOCK: [2018-08-23 Thu 12:15]--[2018-08-23 Thu 16:32] =>  4:17
  :END:
!!Sin embargo -y esto es un dato de suma importancia-, detrás de todas estas crisis,
  está una noción de razón -y de libertad- que no es la genuinamente cristiana.
  Considero que la noción de logos cristiana no cae bajo la crisis post-moderna. Veamos
  este /novum/ que ha quedado intacto a la deconstrucción moderna.

-> El logos cristiano. Una cosmovisión análoga entre dos univocistas:

!!El logos cristiano emerge como una extraordinaria novedad ente los dos antedichos
  univocismos. Frente al logos estóico -fuerza pneumática divina e inmanente en la
  naturaleza-, y frente al logos neoplatónico, trascendente cuasi-divino y ajeno al
  mundo de lo material, el Logos divino del cristianismo -el Verbum- es, en efecto,
  trascendente: es una Persona de la Santísima Trinidad, que ha tenido -y tiene- una
  concreción histórica: se ha Encarnado,es Dios y hombre. p. 187

p. 190; Orígenes, contra celso 2, 31:

No son importantes para el cristiano 'palabra' o 'lenguaje' o 'razón' o 'ley' en sí
mismas, en un uso absoluto -todas son, de alguna manera, expresiones de la
autocomprensión humana-, sino sólo lo que Dios tiene que decir al hombre, el logos
theou, el hecho de que no es compoatible con el concepto griego de Dios, que Dios
interpele al hombre en el aquí y ahora de su vida.


Carácter veritativo del conocimiento teológico: p.194-195

Consistencia y valor de suplencia del lenguaje teológico p. 196-197
* La teología fundamental
** C2. Revelación cristiana: la palabra universal y definitiva de Dios

   :LOGBOOK:
   CLOCK: [2018-10-31 Wed 13:07]--[2018-10-31 Wed 13:32] =>  0:25
   CLOCK: [2018-10-30 Tue 16:55]--[2018-10-30 Tue 17:20] =>  0:25
   CLOCK: [2018-10-30 Tue 15:55]--[2018-10-30 Tue 16:20] =>  0:25
   :END:
TF tiene en la tractación de la Revelación su centro.

será a partir de la ilustración que aparecerá un tratado sobre la revelación...

primeros documentos eclesiásticos que trabajan el tema son ya de la primera mitad del
siglo xix

vat I será quien consagre el término: 8 veces en Dei filius y 1 en Pastor aeternus

el tratado de revelación se desarrolla, por tanto en ese contexto de ilustración

A partir del Vat II la tratación sobre la revelación encontrará un nuevo lugar en la
teología al convertirse en un tratado dogmático y sera R. Latourelle su más
significativo e influyente promotor... se elabora un nuevo tratado dogmático, un
tratado de la Revelación, llamado a ocupar un puesto junto con los grandes tratados
teológicos como son la fe y los sacramentos.

esta dogmática de la revelación aparece como un complemento al tratado apologético y al
tratado de la fe.

el tratado se presenta con una clara estructura dogmática la cual a partir de su
historia (Biblia, Padres, tradición teológica, Magisterio) propone una reflexión
teológica a partir de la triple vía que sugiere el Vaticano I para alcanzar una cierta
inteligencia de los misterios:
[***]vía de la analogía
    categoría de palabra
    [***]categoría de testimonio
    categoría de encuentro
vía de la unión de los misterios entre sí
revelación con creación, historia, encarnación, fe, milagro, Iglesia, visión de Dios
vía de la finalidad

p. 236

filosofía analítica (Cambridge-Oxford philosophy)

después del desafio sobre el criterio de falsificación defendido por A. Flew...
diversos especialistas han relanzado la dimensión analítico-realista del conocimiento y
han realizado propuestas significativas. Las más relevantes en
R. Swinburne:
The coherence of Theism
The existences of God
Revelation

se muestra la importancia y "necesidad" de la Revelación desde un punto de vista
filosófico-analítico y a partir del que llama "principio de credulidad", basado en el
"principio de probabilidad" -> en esta línea se situa el principio de Caridad propuesto
por Coady en Testimony (p. 21, 155-168,176).

B. Mitchell asume la argumentación cumulativa propuesta por J. H. Newman para mostrar
la racionabilidad de la religión y de la revelación, posteriormente ha encontrado
resonancia en el mundo alemán en Meyer-zu-Schlochtern y H.J. Pottmeyer

El hombre tiene capacidad de escuchar una palabra que sea definitiva (p.239)

[***] Qué es la Revelación y cómo se presenta como palabra última de Dios y "verdadera
estrella de orientación del hombre"? [FR 14ss]

Dios se conoce a través del mismo Dios, a este hecho se refiere en definitiva el
concepto de Revelación

** Categoría de Universal Concreto
Verbum Dei est ratio omnium rerum
Pater verbo su oquod ab ipso procedit dicit se et omnia

El concepto tiene origen idealista

-> universale ante res : idea previa a cualquier realización concreta
universale post res : concepto/nombre posteriormente atribuido a la cosa
universale in re : universal sólo presente en su realidad concreta

*universale concretum (idealismo alemán) : lo universal se une dialécticamente a lo
 particular aunque sin confundirse

el planteamiento inicial de la cuestión se encuentra en lessing en "sobre la
demostración en espíritu y fuerza" (1777)

El enfoque moderno del tema tiene su punto de partida en Hegel (1770-1831)

Schelling la desarrolla desde una línea mas positiva en Filosofía de la Revelación
(1858)

La continuada actualidad del tema de lessing se ve en la respuesta de la fides et ratio
al tema, sobre todo en el n. 95

En el siglo XX diversos autores,
H.U von Balthasar formula y desarrolla mas explícitamente la categoría

la expresión universale concretum aparece teológicamente válida si se la complementa
correctamente: en primer lugar con el adjetivo personale aplicado a Cristo, en segundo
lugar con el adjetivo sacramentale aplicado a la iglesia.

p.252 Qué analogías pueden ser útiles para describir el concepto de Revelación?
- Palabra
- Encuentro
-Presencia***
p.255 Toda Palabra supone alguien presente que la dirige, todo encuentro interpersonal
supone una presencia significativa de los que se encuentran. La presencia es fruto de
una alteridad, de una manifestación nueva e irreductible, de un testimonio
calificado...

p. 256: DV4: Dios envió a su Hijo... a fin de que viviera entre los hombres y
manifestara los secretos de Dios... Jesucristo, pues, con su total presencia y
manifestación personal, con palabras y obras..., con su muerte y resurrección
gloriosa... acaba y confirma que Dios vive con nosotros.

** perspectivas eclesiológicas de la tf
p. 474
"Si se quieren sintetizar las perspectivas eclesiológicas de la teología fundamental
reciente se pueden subrayar los siguientes puntos:
1. se constata una notable valoración de la Iglesia como "signo", pero de un
   "signo-que-se-hace-presente" lo que significa, dada su matriz "sacramental"
2. se constata la importancia de acentuar la contextualización de la Iglesia, dado que
   es una congregatio fidelium y, por tanto, enraizada en un mundo y en unas personas
   concretas, y por tanto, enraizada en un mundo y en unas personas concreta, y por
   tanto, no ajena a los avatares de este mundo y estas personas
3. aparece un nuevo talante fruto de la re-orientación de la teología fundamental: la
   apertura al diálogo, ya sea con las "otras realidades" eclesiales y con otras
   religiones y ya sea con la cultura y el pensamiento contemporáneo en clave auditus
   temporis et alterius"

^ esto sería la monstratio catholica

** [***]tratado Igl = marco englobante tf desde cat testimonio
el tratado sobre la Iglesia es el marco englobante y significativo de toda la
teología fundamental: y esto a partir de la categoría testimonio en su doble función:
fundacional hermenéutica (ad intra) y apologético-misionera (ad extra)
*** circularidad
la categoría del testimonio conlleva también una mutua circularidad entre
1. la dimensión externa del testimonio eclesial que es el testimonio revelador
   fundante -ecclesia mater congregans-
2. la dimensión interiorizada que es el testimonio creyente vivido -ecclesia
   fraternitas congregata-
3. dimensión interior e interiorizadora que es el testimonio constante del Espíritu
   -Spiritus in ecclesia-

^ de aquí emerge la función decisiva del testimonio eclesial de la Revelación y la
Fe como camino de credibilidad que no se reduce a una credibilidad meramente externa y
extrínseca, ni a a una credibilidad puramente interna y subjetiva, sino que centra su
atención en una comprensión de la credibilidad que es invitación externa e interna, a
la vez, a la fe, por razón se su carácter abierto e integrador, propio de la
perspectiva renovada de la eclesiología del Vaticano II

** Vat I -> Vat II
p. 484
El vaticano II, por un proceso de personalización que se extiende a toda la economía de
la revelación y de su transmisión, habla de testimonio personal y comunitario allí
dónde Vaticano I habla de atributos milagrosos de la Iglesia y reenfoca así toda la
eclesiología fundamental, tal como puede verse en un texto paradigmático del Vaticano
II donde se recuerda la fórmula clásica "signo levantado entre las naciones", sacada de
Is 11, 12, citada por el Vaticano I así: "sepan todos (los hijos de la Iglesia) que su
primera y principal obligación en pro de la difusión de la fe es vivir profundamente la
vida cristiana. Así, su fervor en el servicio de Dios y su caridad para con los demás
aportarán nuevo aliento espiritual a toda la Iglesia, que aprecerá como signo levantado
entre las naciones, luz del mundo y sal de la tierra."

La iglesia: credibilidad basada en el testimonio:

en la teología fundamental clásica, en su etapa apologética cláscia fue el referido a
la demonstratio catholica que tenía como objetivo demostrar la veracidad de la Iglesia
católica, de ahí su título clásico: De vera ecclesia.
En los manuales anteriores al Vaticano II los capítulos fundamentales de este tratado
eran: fundación de la Iglesia por Cristo con la institución del primado y la sucesión
apostólica, las notas de la verdadera Iglesia, el magisterio y la tradición y
eventualmente, su relación con la Escritura.


>*** Anscombe habla de la apologética que se hizo en una época relacionada con la
     razonabilidad de la fe y como estas discusiones desaparecen después de vat II y se
     queda un vacío donde estaban antes

** Notas

Siento que quisiera comenzar con la llamada de los primeros discípulos en Mt, donde se
da una interpretación a la llegada de Cristo a Cafarnaúm como cumplimiento y los
discípulos le siguen al momento, aparece Cristo como universal concreto para ellos, ahi
conectando con prades cuando dice ¿podemos afirmar que la presencia de esa persona
viva, Jesús, fundamenta una salvación de caracter universal.

Entendiendo la teología fundamental como disciplina que tiene la tractación de la
Revelación en su centro y la Revelación valorada desde su categoría fundamental:
Universal Concreto, planteamos la pregunta: ¿es razonable estimar el mensaje de Cristo
hoy como verdad universal en este contexto multireligioso y plural?

Entendiendo el tratado sobre la Iglesia como el marco englobante de toda la teología
fundamental y la Iglesia como universal concreto y signo de credibilidad basada en el
testimonio, planteamos la pregunta: ¿?
* William James
p. 27 ¿De qué modo este libro, que nace de la forma descrita, puede ser una guía para
nuestra vida y una revelación?
Para contestar a esta pregunta habríamos de poseer alguna teoría general que nos
mostrara con qué peculiaridades ha de contar una cosa para adquirir valor en lo que
concieren a la revelación... tal teoría sería lo que hemos denominado antes un juicio
espirirtual... Werthurtheil... proposición de valor...
esto como distinto de una proposición existencial.. que sería para contestar a una
pregunta sobre la naturaleza de un fenómeno.
El acercamiento a la religión que James realiza es de un punto de vista existencial,
atendiendo la pregunta sobre la naturaleza del comportamiento religioso desde nua
perspectiva psicológica.
Condiciones existenciales de la religión

Se puede reducir la experiencia de la conversión desde una perspectiva de materialismo
ético?

el análisis del conocer a Dios por medio del testimonio en esta investigación viene a
se respuesta a la pregunta acerca de la revelación, de qué manera esta experiencia
puede ser una guía para nuestra vida y una revelación? Cuenta con las peculiaridades
que le otorgan el valor de revelación?

la prueba definitiva de una creencia no estriba en su origen, sino según Maudsley, en
su funcionamiento en general.



* Esquema
- Introducción: la naturaleza de la pregunta sobre el testimonio

> La presencia del testimonio en la vida comunitaria
- El testimonio en la escritura
- El testimonio en vat ii y magisterio posterior
- El testimonio en la TF
> La pregunta teológica/filosófica sobre el testimonio

* //////

* Inicio
  :LOGBOOK:
  CLOCK: [2019-03-05 Tue 16:28]--[2019-03-05 Tue 16:53] =>  0:25
  CLOCK: [2019-03-05 Tue 15:52]--[2019-03-05 Tue 16:17] =>  0:25
  CLOCK: [2019-03-04 Mon 13:49]--[2019-03-04 Mon 14:14] =>  0:25
  CLOCK: [2019-03-04 Mon 12:48]--[2019-03-04 Mon 13:13] =>  0:25
  CLOCK: [2019-03-04 Mon 12:17]--[2019-03-04 Mon 12:42] =>  0:25
  :END:
* Introducción general al problema del Testimonio
** La naturaleza de la pregunta sobre el testimonio
*** notas
Este capítulo comienza planteando la quaestio que será investigada en el trabajo la
idea central es la descripción que hace Agustín de la pregunta sobre el tiempo: del
mismo modo en que el tiempo es una realidad presente en nuestro lenguaje cotidiano el
testimonio forma parte del lenguaje ordinario de nuestra vida eclesial. Así mismo,
preguntar o preguntarse qué es el tiempo... "explícalo"... nos deja sin palabras,
tambíen el testimonio, tan presente en nuestro lenguaje nos puede dejar en la misma
situación. Witt utiliza esta descripción para enmarcar la naturaleza de las preguntas
filosóficas.
Este primer capítulo estará organizado así, en un primer bloque la descripción del
testimonio como fenómeno familiar y presente en nuestro lenguaje y vida eclesial, en un
segundo bloque se plantea qué pasa cuando decímos: explícalo, cuando surge la
necesidad, como dice Witt de traer a la mente una explicación.
La motivación de enfocar de este modo la pregunta es introducir el tema dentro de su
language-game o como tal... el testimonio forma parte de nuestro language-game
eclesial. Otra motivación es enmarcar la pregunta desde el principio en la metodología
de W. y de Ans.
*** texto
#+BEGIN_SRC latex
  \section{Naturaleza de la pregunta sobre el testimonio}
    Es una experiencia familiar en nuestras comunidades reunirnos en torno a la
    Sagrada Escritura y compartir la Palabra buscando en ella luz para nuestro
    presente. Una escena evangélica en torno a la cual muchos se han reunido a
    escuchar al Señor es la narración de Mateo del comienzo de la misión pública de
    Jesús y la llamada de los primeros discípulos:

    \citalitlar{Al enterarse Jesús de que habían arrestado a Juan se retiró a
      Galilea. Dejando Nazaret se estableció en Cafarnaún, junto al mar, en el
      territorio de Zabulón y Neftalí, para que se cumpliera lo dicho por medio del
      profeta Isaías:\\
      <<Tierra de Zabulón y tierra de Neftalí, camino del mar, al otro lado del
      Jordán, Galilea de los gentiles. El pueblo que habitaba en tinieblas vio una
      luz grande; a los que habitaban en tierra y sombras de
      muerte, una luz les brilló>>.\\
      Desde entonces comenzó Jesús a predicar diciendo: <<Convertíos, porque está
      cerca el reino de los cielos>>.\\
      Paseando junto al mar de Galilea vio a dos hermanos, a Simón, llamado Pedro, y
      a Andrés, que estaban echando la red en el mar, pues eran pescadores. Les
      dijo: <<Venid en pos de mí y os haré pescadores de hombres>>. Inmediatamente
      dejaron las redes y lo siguieron. Y pasando adelante vio a otros dos hermanos,
      a Santiago, hijo de Zebedeo, y a Juan, su hermano, que estaban en la barca
      repasando las redes con Zebedeo, su padre, y los llamó. Inmediatamente dejaron
      la barca y a su padre y lo siguieron.\footnote{Mt~4,12--22}}

    No sería difícil ahora visualizar una variedad de escenarios en los que este
    texto pueda ser discutido en nuestro contexto eclesial. Es proclamado, por
    ejemplo, en el ciclo A el III Domingo del Tiempo Ordinario. Es así que puede
    escucharse en las reflexiones del Papa Francisco en el Ángelus en la Plaza de
    San Pedro, donde destaca el hecho de que la misión de Jesús comience en una zona
    periférica:
    \citalitlar{Es una tierra de frontera, una zona de tránsito donde se encuentran
      personas diversas por raza, cultura y religión. La Galilea se convierte así en
      el lugar simbólico para la apertura del Evangelio a todos los pueblos. Desde
      este punto de vista, Galilea se asemeja al mundo de hoy: presencia simultánea
      de diversas culturas, necesidad de confrontación y necesidad de encuentro.
      También nosotros estamos inmersos cada día en una <<Galilea de los gentiles>>,
      y en este tipo de contexto podemos asustarnos y ceder a la tentación de
      construir recintos para estar más seguros, más protegidos. Pero Jesús nos
      enseña que la Buena Noticia, que Él trae, no está reservada a una parte de la
      humanidad, sino que se ha de comunicar a todos. Es un feliz anuncio destinado
      a quienes lo esperan, pero también a quienes tal vez ya no esperan nada y no
      tienen ni siquiera la fuerza de buscar y pedir.\footnote{PAPA FRANCISCO
        ÁNGELUS Plaza de San Pedro Domingo 26 de enero de 2014}}

    Tambíen el Papa Benedicto XVI ofreció su comentario y se fijó en la fuerza de esa
    noticia que Cristo comenzaba a anunciar:
    \citalitlar{El término ``evangelio'', en tiempos de Jesús, lo usaban los
      emperadores romanos para sus proclamas. Independientemente de su contenido, se
      definían ``buenas nuevas'', es decir, anuncios de salvación, porque el
      emperador era considerado el señor del mundo, y sus edictos, buenos presagios.
      Por eso, aplicar esta palabra a la predicación de Jesús asumió un sentido
      fuertemente crítico, como para decir: Dios, no el emperador, es el Señor del
      mundo, y el
      verdadero Evangelio es el de Jesucristo.\\
      La ``buena nueva'' que Jesús proclama se resume en estas palabras: ``El reino
      de Dios —-o reino de los cielos-— está cerca''. ¿Qué significa esta expresión?
      Ciertamente, no indica un reino terreno, delimitado en el espacio y en el
      tiempo; anuncia que Dios es quien reina, que Dios es el Señor,
      y que su señorío está presente, es actual, se está realizando.\\
      Por tanto, la novedad del mensaje de Cristo es que en él Dios se ha hecho
      cercano, que ya reina en medio de nosotros, como lo demuestran los milagros y
      las curaciones que realiza.\footnote{BENEDICTO XVI ÁNGELUS Plaza de San Pedro
        Domingo 27 de enero de 2008}}

    No sólo en San Pedro, sino que también podría encontrarse este texto en la
    celebración de la eucaristía domincal resonando en las comunidades y parroquias;
    en las homilias, oraciones, reflexiones o cánticos, invitando a la conversión y
    haciendo nueva la invitación de Jesús: <<Convertíos, porque está cerca el reino
    de los cielos>>. Quizás tambíen se le oiga entre algún grupo juvenil donde
    Simón, Andrés, Santiago y Juan sean tratados como modelos de vocación a la vida
    consagrada o al apostolado, atendiendo con entusiasmo cómo lo dejaron todo en el
    momento para seguir a Jesús. Seguramente algún joven reconociendo aquella
    llamada: <<Venid en pos de mí y os haré pescadores de hombres>> sonando como voz
    dentro de sí.

    El texto de la Escritura es tratado en estos contextos como testimonio de la
    vida de Jesucristo y de la vida de aquellos que le llaman maestro y que
    participan de su misión. No son, sin embargo, tratados como historias del
    pasado, sino como palabras para el presente. Es hoy que la Buena Noticia no está
    reservada a una parte de la humanidad, sino que ha de comunicarse a todos como
    insiste el Papa Francisco. Es hoy que Dios se hace cercano en Cristo para reinar
    en medio de nosotros como enseñó Benedicto XVI. Es hoy que Jesús nos invita a la
    conversión y a ir en pos de él.

    Es sobre esta costumbre de la Iglesia que ha de formularse ahora una pregunta.
    Resultará apropiado apelar aquí a otra costumbre de la Iglesia y buscar luz para
    esto en las Confesiones de San Agustín. Pensando en Dios y pensando en el
    tiempo, Agustín queda inquieto por una serie de preguntas: \citalitlar{¿Qué es,
      pues, el tiempo? ¿Quién podrá explicar esto fácil y brevemente? ¿Quién podrá
      comprenderlo con el pensamiento, para hablar luego de él? Y, sin embargo, ¿qué
      cosa más familiar y conocida mentamos en nuestras conversaciones que el
      tiempo? Y cuando hablamos de él, sabemos sin duda qué es, como sabemos o
      entendemos lo que es cuando lo oímos pronunciar a otro. ¿Qué es, pues, el
      tiempo? Si nadie me lo pregunta, lo sé; pero si quiero explicárselo al que me
      lo pregunta, no lo sé.\footnote{De las confesiones xi.14 (n. 17)}}

    Agustín expresa su extrañeza de que un concepto empleado ordinariamente se
    torne tan desconocido cuando llega la hora de explicarlo. ``¿Qué es el
    tiempo?'' o ``¿qué es conocer?'', ``¿la libertad?'' y ``¿qué es la fe?'' son
    preguntas de este tipo; distintas, por ejemplo, a ``¿cuál es el peso exacto de
    este objeto?'' o ``¿quién será la próxima persona en entrar por esa
    puerta?''.\footnote{cf. Wittgenstein BT. p.304} Preguntar ``¿qué es conocer una
    verdad para la vida por el testimonio de la Escritura?'' sería, como la pregunta
    agustiniana sobre el tiempo, una pregunta sobre la naturaleza o esencia de
    este fenómeno. Un concepto familiar en la vida de la Iglesia como el
    testimonio queda enmarcado como problema cuando nos acercamos a él queriendo
    comprender su esencia.

    Para continuar explorando la naturaleza de la pregunta sobre el testimonio
    resultará útil recurrir aquí al modo en que el psicólogo William James formula
    algunas preguntas sobre la Escritura al comienzo de sus conferencias sobre la
    \emph{religion natural}. Apelando a la literatura de lógica de su época a
    comienzos del siglo XX distingue dos niveles de investigación sobre cualquier
    tema: aquellas preguntas que se resuelven por medio de prposiciones
    \emph{existenciales}, como ``¿qué constitución, qué origen, qué historia tiene
    esto?'' o ``¿cómo se ha realizado esto?''; en segundo lugar las preguntas que se
    responden con proposiciones de \emph{valor} como ``¿cuál es la importancia,
    sentido o significado actual de esto?''. A este segundo juicio James lo denomina
    \emph{juicio espiritual}. Aplicando esta distinción a la Biblia se cuestiona:

    \citalitlar{ <<¿Bajo qué condiciones biográficas los escritores sagrados aportan
      sus diferentes contribuciones al volumen sacro?>>, <<¿Cúal era exactamente el
      contenido intelectual de sus declaraciones en cada caso particular?>>. Por
      supuesto, éstas son preguntas sobre hechos históricos y no vemos cómo las
      respuestas pueden resolver, de súbito, la última pregunta: <<¿De qué modo este
      libro, que nace de la forma descrita, puede ser una guía para nuestra vida y
      una revelación?>>. Para contestar habríamos de poseer alguna teoría general
      que nos mostrara con qué peculiaridades ha de contar una cosa para adquirir
      valor en lo que concierne a la revelación; y, en ella misma, tal teoría sería
      lo que antes hemos denominado un juicio espiritual.\footnote{William James
        Variedades de la Experiencia Religiosa p. 27} }

    Desde esta perspectiva la pregunta sobre cómo el testimonio de la escritura
    puede ser una guía para nuestra vida es una investigación sobre la importancia,
    sentido o significado que ésta tiene actualmente. La respuesta emitida en
    conclusión sería un juicio de valor sobre el fenómeno del testimonio. James
    propone que sería necesaria una teoría general que explicara qué características
    ha de tener alguna cosa para que merezca ser valorada como revelación. Así
    planteado, la pregunta sobre el testimonio sería atendida adecuadamente por
    medio de una investigación que indagara dentro de este fenómeno para descubrir
    los elementos que le otorgan el valor adecuado como para ser considerado guía
    para nuestra vida o una revelación. La explicación de dichos elementos
    configurarían una teoría que nos permitiría juzgar un testimonio concreto como
    valioso, o no, como guía o revelación para nuestras vidas.

    La ruta sugerida por este modo de conducir esta investigación, sin embargo, nos
    dejaría lejos del modo en que Elizabeth Anscombe se plantea un problema
    filosófico. En el trasfondo de su metodología filosófica está la propuesta por
    Ludwig Wittgenstein. Aunque se verá con más detalle qué implica esto, es
    necesario anticipar ahora algo acerca del modo en que ambos se encaminan a la
    hora de atender una investigación filosófica.

    En \emph{Investigaciones Filosóficas} \S89 Wittgenstein hace referencia al
    texto antes citado de las Confesiones para describir la peculiaridad de las
    preguntas filosóficas:
    \citalitlar{ Augustine says in \emph{Confessions} XI. 14, ``quid est ergo
      tempus? si nemo ex me quaerat scio; si quaerenti explicare velim nescio''.
      --This could not be said about a question of natural science (``What is the
      specific gravity of hydrogen'', for instance). Something that one knows when
      nobody asks one but no longer knows when one is asked to explain it, is
      something that has to be \emph{called to mind}. (And it is obviously
      something which, for some reason, it is difficult to call to mind.)}

    Para Wittgenstein es de gran importancia atender el paso que damos para
    resolver la perplejidad causada por el reclamo de explicar un fenómeno. El
    deseo de aclararlo nos puede impulsar a buscar una explicación dentro del
    fenómeno mismo, o cómo él diría: \citalitinterlin{We feel as if we had to see
      right into phenomena}.\footnote{\S90} Esta predisposición nos puede conducir
    a ignorar la amplitud del modo en que el lenguaje sobre esto es empleado en la
    actividad humana y a enfocarnos sólo en un elemento particular del lenguaje
    sobre este fenómeno y tomarlo como un ejemplo paradigmático para construir un
    modelo abstrayendo explicaciones y generalizaciones sobre él. Esta manera de
    indagar, le parece a Wittgenstein, nos hunde cada vez más profundamente en un
    estado de frustración y confusión filosófica de modo que llegamos a imaginar
    que para alcanzar claridad \citalitinterlin{we have to describe extreme
      subtleties, which again we are quite unable to describe with the means at
      our disposal. We feel as if we had to repair a torn spider's web with our
      fingers.}\footnote{\S106}

    La alternativa que Wittgenstein propone es una investigación que no esté
    dirigida hacia dentro del fenómeno, sino \citalitinterlin{as one might say,
      towards the \emph{`possibilities'} of phenomena. What that means is that we
      call to mind the \emph{kinds of statement} that we make about phenomena}. A
    este esfuerzo le denomina ``investigación gramática''. La describe de este modo:
    \citalitlar{ Our inquiry is therefore a grammatical one. And this inquiry sheds
      light on our problem by clearing misunderstandings away. Misunderstandings
      concerning the use of words, brought about, among other things, by certain
      analogies between the forms of expression in different regions of our
      language. -- Some of them can be removed by substituting one form of
      expression for another; this may be called `analysing' our forms of
      expression, for sometimes this procedure resembles taking things
      apart.\footnote{\S90}} El modo de salir de nuestra perplejidad, por tanto,
    consiste en prestar cuidadosa atención al uso que hacemos de hecho con las
    palabras y la aplicación que empleamos de las expresiones. Esto está al
    descubierto en nuestro uso del lenguaje de modo que la dificultad para
    \emph{traer a la mente} aquello que aclare un fenómeno no está en descubrir algo
    oculto en éste, sino en aprender a valorar lo que tenemos ante nuestra vista:
    \citalitinterlin{The aspects of things that are most important for us are hidden
      because of their simplicity and familiarity. (One is unable to notice
      something -- because it is always before one's eyes.)}\footnote{\S129} La
    descripción de los hechos concernientes al uso del lenguaje en nuestra actividad
    humana ordinaria componen los pasos del tipo de investigación sugerido por
    Wittgenstein. Hay cierta insatisfacción en este modo de proceder, como él mismo
    afirma: \citalitlar{Where does this investigation get its importance from, given
      that it seems only to destroy everything interesting: that is, all that is
      great and important? (As it were, all the buildings, leaving behind only bits
      of stone and rubble.) But what we are destroying are only houses of cards, and
      we are
      clearing up the ground of language on which they stood.\\
      The results of philosophy are the discovery of some piece of plain nonsense
      and the bumps that the understanding has got running up against the limit of
      language. They -- these bumps -- make us see the value of that discovery.}

    Anscombe, al igual que Wittgenstein, no se limita a emplear un sólo método para
    hacer filosofía, como afirma el mismo Wittgenstein: \citalitinterlin{There is
      not a single philosophical method, though there are indeed methods, different
      therapies as it were}.\footnote{\S133} Sin embargo si atendemos a su modo de
    hacer filosofía podemos encontrarla empleando lenguajes o juegos de lenguaje
    imaginarios para arrojar luz sobre modos actuales de usar el lenguaje o esquemas
    conceptuales; del mismo modo su trabajo esta lleno de ejemplos donde la
    encontramos examinando con detenimiento el uso que de hecho hacemos del
    lenguaje.\footnote{cf. teichmann p. 228-229} Es visible en ella ese
    \citalitinterlin{modo característicamente Wittgensteniano de rebatir la
      tendencia del filósofo de explicar alguna cuestión filosóficamente enigmática
      inventando una entidad o evento que la causa, así como los físicos inventan
      partículas como el gravitón}.\footnote{There is however a somehow
      chracteristically Wittgenstenian way of countering the philosopher's tendency
      to explain a philosophically puzzling thing by inventing an entity or event
      which causes it, as physicists invent particles like the graviton. From plato
      to witt intro xix}

    Según el título de este trabajo ha prometido, el análisis sobre el testimonio
    que será expuesto es el que se encuentra desarrollado en el pensamiento de
    Elizabeth Anscombe. La pregunta planteada al inicio: ¿qué es conocer una verdad
    para la vida por el testimonio de la Escritura?, entendida como investigación
    filosófica, será examinada en las descripiciones que Anscombe realiza sobre el
    modo de usar el lenguaje sobre el creer, la confianza, la verdad, la fe y otros
    fenómenos relacionados con el conocer por testimonio. Nuestro título adiverte
    además que ésta es una investigación en perspectiva teólogica, cabe
    inmendiatamente añadir algo breve al respecto.

    ¿Qué es teología?, se preguntaba Joseph Ratzinger en su alocución en el 75
    aniversario del nacimiento del cardenal Hermann Volk en 1978, e introducía
    suscintamente su respuesta a esa pregunta tan grande diciendo:

    \citalitlar{Cuando se intenta decir algo sobre esta materia, precisamente como
      tributo al cardenal Volk y a su pensamiento, se asocian, poco menos que
      automáticamente, dos ideas. Me viene a las mientes, por un lado, su divisa (y
      título de uno de sus libros): \emph{Dios todo en todos}, y el programa
      espiritual contenido en ella; por otra parte, se aviva el recuerdo de lo que
      ya antes se ha insinuado: un modo de interrogar total y absolutamente
      filosófico, que no se detiene en reales o supuestas comprobaciones históricas,
      en diagnósticos sociológicos o en técnicas pastorales, sino que se lanza
      implacablemente a la busqueda de los fundamentos.\\
      Según esto, cabría formular ya dos tesis que pueden servirnos de hilo
      conductor para nuestro interrogante sobre la esencia de la teología:\\
      1. La teología se refiere a Dios.\\
      2. El pensamiento teológico está vinculado al modo de cuestionar filosófico
      como a su método fundamental.\footnote{teoría de los principios teológicos, p
        380}}
    Esta investigación sobre el testimonio como parte de la vida de la Iglesia será
    realizada atendiendo al modo de cuestionar filosófico realizado por Elizabeth
    Anscombe como método, examinando esta experiencia en referencia a Dios, es
    decir, como vivencia de su ser y de su obrar.

    Hasta aquí simplemente se ha descrito un modo de andar a través de la discusión
    acerca de la categoría del testimonio atendiendo el hecho de que tanto la
    temática como la figura de Anscombe otorgan a este camino peculiaridades que hay
    que tener en cuenta. Siendo concientes de estas particularidades podríamos ahora
    ampliar más el horizonte respecto de dos cuestiones brevemente expuestas
    anteriormente. En primer lugar es necesario ampliar la descripción hecha hasta
    aquí del fenómeno del testimonio en la vida de la Iglesia, ya que aunque nos
    resulte familiar relacionarlo con el testimonio de la Sagrada Escritura, tanto
    en el Magisterio de la Iglesia como en la propia Escritura se haya presente la
    categoría del testimonio con una riqueza que merece la pena explorar. En segundo
    lugar habría que detallar todavía mejor lo problemático del testimonio, sobre
    todo cuando se considera su importancia en la transmisión de la fe y el anuncio
    del Evangelio en el mundo.
#+END_SRC
*** notas
!!Es pregunta filosófica como la describe Witt desde Agustín
!!Es pregunta teológica como la describe Ratzinger

^Sigue presente en nuestra sociedad el desafío de responder a una objeción formulada
entre otros por una ``ilustración insatisfecha'', en palabras de Angelo Scola; una
corriente de pensamiento que ha tenido la capacidad de plantear preguntas pero no ha
sabido encontrarle respuestas adecuadas. De ésta forman parte Kant, Lessing o Jaspers
(p. 35-36)

No es un escenario extraño encontrarnos en una misa escuchando esta palabra y llevar
esto a nuestra experiencia presente y encontrar en ellas una descripción de una
experiencia con la que sentimos que podemos identificarnos.

No sólo en la parroquia, sino también en ámbitos diversos en donde nuestras acciones o
palabras son genuino deseo de seguir a Cristo, su obra, su enseñanza. Actuar como él.
Actuar con él. En la oficina, en la calle, en la familia, quisieramos elegir en ese
instante, sobre cualquier otro modo de actuar esa ruta que implica seguir a Cristo.
Peeero.

De las confesiones xi.14 (n. 17) ¿Qué es, pues, el tiempo? ¿Quién podrá explicar esto
fácil y brevemente? ¿Quién podrá comprenderlo con el pensamiento, para hablar luego de
él? Y, sin embargo, ¿qué cosa más familiar y conocida mentamos en nuestras
conversaciones que el tiempo? Y cuando hablamos de él, sabemos sin duda qué es, como
sabemos o entendemos lo que es cuando lo oímos pronunciar a otro. ¿Qué es, pues, el
tiempo? Si nadie me lo pregunta, lo sé; pero si quiero explicárselo al que me lo
pregunta, no lo sé.

Prades en dar testimonio p. 37 plantea Cuando decimos que la verdad de todo hombre se
manifiesta en el acontecimiento de Cristo, ¿podemos afirmar que esa manifestación es
aquí y ahora tan real como lo fue para los discípulos? y se puede afirmar que la
presencia de esa persona viva, Jesús, fundamenta una salvación de carácter universal?
Ese desafío sigue presente en nuestra sociedad.


Fides et ratio 13

ratio sacramentalis de la revelación.... a esta se le puede unir una ratio
testimonialis (dar testimonio 449)

13. De todos modos no hay que olvidar que la Revelación está llena de
misterio. Es verdad que con toda su vida, Jesús revela el rostro del Padre, ya que ha
venido para explicar los secretos de Dios; 13 sin embargo, el conocimiento que nosotros
tenemos de ese rostro se caracteriza por el aspecto fragmentario y por el límite de
nuestro entendimiento. Sólo la fe permite penetrar en el misterio, favoreciendo su
comprensión coherente.

El Concilio enseña que « cuando Dios revela, el hombre tiene que someterse con la fe
».14 Con esta afirmación breve pero densa, se indica una verdad fundamental del
cristianismo. Se dice, ante todo, que la fe es la respuesta de obediencia a Dios. Ello
conlleva reconocerle en su divinidad, trascendencia y libertad suprema. El Dios, que se
da a conocer desde la autoridad de su absoluta trascendencia, lleva consigo la
credibilidad de aquello que revela. Desde la fe el hombre da su asentimiento a ese
testimonio divino. Ello quiere decir que reconoce plena e integralmente la verdad de lo
revelado, porque Dios mismo es su garante. Esta verdad, ofrecida al hombre y que él no
puede exigir, se inserta en el horizonte de la comunicación interpersonal e impulsa a
la razón a abrirse a la misma y a acoger su sentido profundo. Por esto el acto con el
que uno confía en Dios siempre ha sido considerado por la Iglesia como un momento de
elección fundamental, en la cual está implicada toda la persona. Inteligencia y
voluntad desarrollan al máximo su naturaleza espiritual para permitir que el sujeto
cumpla un acto en el cual la libertad personal se vive de modo pleno.15 En la fe, pues,
la libertad no sólo está presente, sino que es necesaria. Más aún, la fe es la que
permite a cada uno expresar mejor la propia libertad. Dicho con otras palabras, la
libertad no se realiza en las opciones contra Dios. En efecto, ¿cómo podría
considerarse un uso auténtico de la libertad la negación a abrirse hacia lo que permite
la realización de sí mismo? La persona al creer lleva a cabo el acto más significativo
de la propia existencia; en él, en efecto, la libertad alcanza la certeza de la verdad
y decide vivir en la misma.

Para ayudar a la razón, que busca la comprensión del misterio, están también los signos
contenidos en la Revelación. Estos sirven para profundizar más la búsqueda de la verdad
y permitir que la mente pueda indagar de forma autónoma incluso dentro del misterio.
Estos signos si por una parte dan mayor fuerza a la razón, porque le permiten
investigar en el misterio con sus propios medios, de los cuales está justamente celosa,
por otra parte la empujan a ir más allá de su misma realidad de signos, para descubrir
el significado ulterior del cual son portadores. En ellos, por lo tanto, está presente
una verdad escondida a la que la mente debe dirigirse y de la cual no puede prescindir
sin destruir el signo mismo que se le propone.

Podemos fijarnos, en cierto modo, en el horizonte sacramental de la Revelación y, en
particular, en el signo eucarístico donde la unidad inseparable entre la realidad y su
significado permite captar la profundidad del misterio. Cristo en la Eucaristía está
verdaderamente presente y vivo, y actúa con su Espíritu, pero como acertadamente decía
Santo Tomás, « lo que no comprendes y no ves, lo atestigua una fe viva, fuera de todo
el orden de la naturaleza. Lo que aparece es un signo: esconde en el misterio
realidades sublimes ».16 A este respecto escribe el filósofo Pascal: « Como Jesucristo
permaneció desconocido entre los hombres, del mismo modo su verdad permanece, entre las
opiniones comunes, sin diferencia exterior. Así queda la Eucaristía entre el pan común
».17

El conocimiento de fe, en definitiva, no anula el misterio; sólo lo hace más evidente y
lo manifiesta como hecho esencial para la vida del hombre: Cristo, el Señor, « en la
misma revelación del misterio del Padre y de su amor, manifiesta plenamente el hombre
al propio hombre y le descubre la grandeza de su vocación »,18 que es participar en el
misterio de la vida trinitaria de Dios.19


William James plantea temprano en sus lectures el tipo de pregunta: ¿De qué modo este
libro, que nace de la forma descrita, puede ser una guía para nuestra vida y una
revelación? p. 27 y plantea, para contestar a esta pregunta habríamos de poseer una
teoría general que nos mostrara con qué peculiaridades ha de contar una cosa para
adquirir valor en lo que concierne a la revelación; y, en ella misma, tal teoría sería
lo que antes hemos denominado un juicio espiritual, éste distinto de un juicio
existencial, sería una proposición de valor como respuesta a cuestionamiento sobre el
sentido, importancia o significado actual de algo. La pregunta ¿qué son las tendencias
religiosas? esta relacionada con un nivel de investigación, ¿cuál es su signifcado
filosófico? con otro. El primero se atiende con un juicio existencial del tipo: cuál es
su naturaleza, cómo se ha realizado? ¿Qué constitución, qué origen, qué historia tiene?
El segundo se atendería con un juicio de valor del tipo: cuál es su importancia, su
sentido, su significado actual?

En sus lectures William adopta un punto de vista puramente existencial, cosa que
advierte dado que causa sorpresa entre personas religiosas. Considera los fenómenos de
la experiencia religiosa biológica y psicológicamente como si fuesen simpres hechos
curiosos de la historia individual, algunos pensaran que se degrada un tema tan
sublime, pero su intención no es desacreditar el aspecto religioso de la vida.


** El testimonio en la Sagrada Escritura
*** Texto
#+BEGIN_SRC latex
  \section{La categoría del Testimonio en la Sagrada Escritura}
  La Iglesia de hoy, como María, conserva el Evangelio meditándolo en su
  corazón.\footnote{Lc 2,19} Así está presente en el centro de la comunidad
  creyente el anuncio de Cristo vivo como fundamento de su esperanza en cada etapa
  de la historia. Este motivo de esperanza conservado es también compartido y
  expresado, según la enseñanza del apóstol:\citalitinterlin{glorificad a Cristo
    en vuestros corazones, dispuestos siempre a dar explicación a todo el que os
    pida una razón de vuestra esperanza}.\footnote{1Pe 3, 15} Este Evangelio
  atesorado como fundamento en el centro de la vida de la comunidad eclesial, así
  como Buena Nueva proclamada y transmitida en el tiempo y en el mundo puede ser
  comprendido como tres testimonios que son uno:<<palabra vivida en el
  Espíritu>>\footnote{cf. Porque es el Espíritu el que impulsa a la Iglesia a
    perseguir son obras de evangelización; es el Espíritu quien santifica y
    fecunda el testimonio de su vida; y es el Espíritu el que inspira la fe, la
    nutre y la profundiza. Es el Espíritu quien alivia entre estos tres
    testimonios que son uno: el de la palabra vivida en el Espíritu. A través del
    testimonio, el Espíritu internaliza el testimonio externo de la Buena Nueva de
    la salvación en Jesucristo y lo lleva al cumplimiento de la fe, que es la
    respuesta del amor del verdadero amor de la humanidad a través del Padre.
    Cristo; Latourelle Evangelisation et temoignage ninot 582}.

  La Evangelización puede ser entendida en este sentido como testimonio de la
  <<palabra de vida>>\footnote{1Jn 1,1} que los apóstoles anuncian como testigos
  de lo que han contemplado y palpado\footnote{1Jn 1,1}. Es también el testimonio
  del modo de vivir de los cristianos que, acogiendo esta palabra, la viven,
  poniendo por obra lo que ella enseña. Es además testimonio del Espíritu Santo
  que internaliza el testimonio externo de la Buena Noticia y lo lleva al
  cumplimiento de la fe en cada persona.\footnote{cf. latourelle, ninot 582} Es el
  Espíritu el que santifica y fecunda la acción de los cristianos, es tambíen el
  que impulsa y sostiene la acción de la Iglesia; es el Espíritu el que inspira la
  fe, la nutre y la profundiza.\footnote{latourelle evangelisation et temoignage}

  Este dinamísmo fundamental que puede encontrarse vivo hoy en la comunidad de la
  Iglesia ha actuado en ella desde su origen y le ha acompañado en cada época.
  Según esto es posible valorar lo que se transmite en la tradición eclesial como
  la perpetuación de la actividad de Cristo y los apóstoles, que es a su vez
  proyección del testimonio divino.\footnote{ el testimonio divino se proyecta
    luego en el apostólico y se perpetúa en el testimonio eclesial. Por eso, el
    testimonio es revelación en la actividad de Cristo y de los apóstoles y es
    transmisión de la revelación en la tradición eclesial. ninot 573}

  En la actividad de Cristo el testimonio divino queda proyectado como
  interpelación a la libertad realizada por la identidad propia de Jesús:
  \citalitinterlin{Si conocieras el don de Dios y quién es el que te dice ``dame
    de beber'' le pedirías tu, y él te daría agua viva}\footnote{Jn 4, 10};
  \citalitinterlin{``¿Crees tú en el Hijo del hombre?''\ldots ``¿Y quién es,
    Señor, para que crea en él?''\ldots ``Lo estás viendo: el que te está
    hablando, ese es''}\footnote{Jn 9, 35--37}. En la actividad apostólica, el
  testimonio divino sigue interpelando la libertad humana como manifestación de
  Jesús Resucitado. Los apóstoles actuan como testigos de los acontecimientos de
  la Pascua de Jesús y su valor salvífico\footnote{cf. ninot 576} y este
  testimonio es descrito como acción del Espíritu que impulsa la tarea apostólica
  y que da nueva vida a los que acogen el anuncio de la Buena Noticia.

  Puede encontrarse un ejemplo de esto en el testimonio de Felipe. El apóstol sale
  más allá de Jerusalén hacia Samaria, y todavía llega más lejos, al compartir la
  Buena Noticia de Jesús con un extranjero Etíope: \citalitlar{El Espíritu dijo a
    Felipe: <<Acércate y pégate a la carroza>>. Felipe se acercó corriendo, le oyó
    leer el profeta Isaías, y le preguntó: <<¿Entiendes lo que estás leyendo?>>.
    Contestó: <<¿Y cómo voy a entenderlo si nadie me guía?>>. E invitó a Felipe a
    subir y a sentarse con él. El pasaje de la Escritura que estaba leyendo era
    este: \emph{Como cordero fue llevado al matadero, como oveja muda ante el
      esquilador, así no abre su boca. En su humillación no se le hizo justicia.
      ¿Quién podrá contar su descendencia? Pues su vida ha sido arrancada de la
      tierra.} El eunuco preguntó a Felipe: <<Por favor, ¿de quién dice esto el
    profeta?; ¿de él mismo o de otro?>>. Felipe se puso a hablarle y, tomando pie
    de este pasaje, le anunció la Buena Nueva de Jesús. Continuando el camino,
    llegaron a un sitio donde había agua, y dijo el eunuco: «Mira, agua. ¿Qué
    dificultad hay en que me bautice?». Mandó parar la carroza, bajaron los dos al
    agua, Felipe y el eunuco, y lo bautizó. Cuando salieron del agua, el Espíritu
    del Señor arrebató a Felipe. El eunuco no volvió a verlo, y siguió su camino
    lleno de alegría. \footnote{Hch 8, 29--39}} Además de ser ejemplo de la
  actividad apostólica, este relato puede servir como síntesis del modo en que la
  categoría del testimonio está presente en la Escritura.

  El testimonio comienza con la iniciativa de Dios mismo que impulsa tanto la
  palabra profética del Antiguo Testamento como el anuncio apostólico del Nuevo
  Testamento. Esta iniciativa de Dios tiende hacia el testimonio de la Palabra
  definitiva del Padre que es Cristo resucitado. En aquellos que creen en el
  testimonio de Dios se engendra alegría y vida nueva. En palabras de R.
  Latourelle:
  \citalitlar{En el trato de las tres personas divinas con los hombres existe un
    intercambio de testimonios que tiene la finalidad de proponer la revelación y
    de alimentar la fe. Son tres los que revelan o dan testimonio, y esos tres son
    más que uno. Cristo da testimonio del Padre, mientras que el Padre y el
    Espíritu dan testimonio del Hijo. Los apóstoles a su vez dan testimonio de lo
    que han visto y oído del verbo de la vida. Pero su testimonio no es la
    comunicación de una ideología, de un descubrimiento científico, de una técnica
    inédita, sino la proclamación de la salvación prometida y finalmente
    realizada.\footnote{diccion testimonio p.1531}}
  De este modo el anuncio del apóstol Felipe sirve aquí como un ejemplo específico
  del testimonio, que ilustra sin embargo, una noción
  que\citalitinterlin{atraviesa toda la Escritura y se corresponde con la
    estructura misma de la revelación.}\footnote{la noción de testimonio atraviesa
    la Escritura y se coresponde con la estructura misma de la Revelación: <<la
    Escritura describe la revelación como una economía del testimonio>>. prades
    109} El testimonio está presente a lo largo de la Escritura junto a otras
  categorías como pueden ser la de `alianza', `palabra', `paternidad' o
  `filiación', como parte del \citalitinterlin{grupo de analogías empleadas por la
    Escritura para introducir al hombre en las riquezas del misterio
    divino}.\footnote{latourelle p. 1523}

  Esta clave servirá para dar enfoque a un examen sobre la categoría del
  testimonio en la Escritura. ¿Qué nos dice el Antiguo y el Nuevo Testamento de la
  revelación como acto testimonial de Dios? Esta pregunta supone que la revelación
  comparte los rasgos de la actividad humana que es el testimonio, sin embargo,
  como Latourelle adiverte: \citalitinterlin{globalmente se puede decir que el
    testimonio bíblico asume pero al mismo tiempo exalta hasta sublimarlos, los
    rasgos del testimonio humano.}\footnote{cf. latourelle 1526 Globalmente se
    puede decir que el testimonio bíblico asume pero al mismo tiempo exalta hasta
    sublimarlos, los rasgos del testimonio humano. latourelle 1526}

  Cabe añadir una última consideración. La revelación de Dios entendida como acto
  testimonial suyo tiene como expresión definitiva el misterio pascual de
  Cristo.\footnote{cf. el misterio pascual al cual tiende toda la existencia
    terrena de Cristo, constituye el acto testimonial por excelencia de Dios
    prades 128} Este misterio ocupa el lugar principal en el testimonio bíblico:
  \citalitlar{la Resurrección como ``final'' de la unicidad del acontecimiento de
    Jesucristo, encarnado, muerto y resucitado, subraya específicamente la
    definitividad de la existencia humana salvada por Dios en la carne de Jesús de
    Nazaret, ya que la autocomunicación de Dios ha alcanzado su palabra última en
    la Resurrección de Jesucristo, y por eso es prenda de la resurrección de todos
    los hombres.\footnote{ninot 404}}
  Como tal, parece justo tratar el testimonio que es el misterio pascual en su
  propio apartado. Y será éste precisamente el punto de partida para esta
  descripción de la categoría del testimonio en la Escritura.
  #+END_SRC
*** Notas
El testimonio en la escritura

intro: la igl no olvida el motivo de su esperanza

si partimos desde la vivencia de la igle hoy nos encontramos una igl q guarda y
transmite el motivo de su esperanza esta acción evangelizadora la podemos recoger en la
exp: palabra vivida en el esp

esto implica un triple test

esta acción de la iglesa y su tradición es también perpetuación de la accion de cristo/
apostoles

así como cristo interpela: si supieras... confias... soy yo
también los apóstoles orientan... es él
a modo de síntesis felipe

hacia donde refiere en definitiva el testimonio de Cristo y los apóstoles es a alguien,
al Dios salvador

de modo que podemos decir que
en la escritura la categoría del testimonio está presente como estructura de la propia
revelación

es así que nos encontramos al test como una de las analogías empleadas...

si entendemos la revelación desde su estructura testimonial
podemos decir que es acto testimonial de Dios por excelencia en la resu
acto testimonial de Dios en el AT
acto testimonial de Dios en el NT

*** El testimonio en el anuncio pascual
  Lo que se quiere decir es que

  - el misterio pascual (en sí) es el acto testimonial por excelencia de Dios
  - creer en este misterio implica dar asentimiento a la manifestación más plena y
  al motivo de credibilidad más cierto

  Este misterio es anunciado por los apóstoles y
  la categoría del testimonio está presente en el
  anuncio pascual en el sentido de que los apóstoles son testigos:
  de un hecho enraizado en la historia
  del valor salvífico de este hecho
  de la interpretación basada en la autenticidad de los dichos y obras de Jesús

  Cristo mismo es testigo veraz y acreditado, verdadero profeta porque realiza lo
  que ha prometido.

  Enunciados:
  Dios lo resucitó de entre los muertos
  Relatos del sepulcro vacío y apariciones


  el testimonio en sí del suceso pascual
  el testimonio que Cristo da de éste como revelación/promesa/anuncio
  el testimonio apostólico de éste
  el testimonio de Cristo como resucitado y glorificado

#+BEGIN_SRC latex
  \subsection{El testimonio en el misterio y anuncio pascual}
#+END_SRC
**** El hecho en sí de la Pascua constituye el acto testimonial por excelencia de Dios
***** estatuto epistemológico especial
#+BEGIN_SRC latex
  \ifdraft{\subsubsection{Estatuto espistemológico especial}}{}
  <<Cristo ha resucitado>>\footnote{Cf. 1 Tes 4,15; 1Cor 15,12--20; Rom 6,4} es la
  confesión que está en el núcleo del más primitivo anuncio del
  evangelio.\footnote{ninot 403} Creer en esta noticia conlleva acoger la
  manifestación más plena de la Revelación y la motivación más definitiva para
  creer. En este sentido:
  \citalitlar{La Resurrección de Jesús mirada desde la perspectiva de la teología
    fundamental presupone un estatuto epistemológico peculiar, puesto que es el
    punto culminante y objeto de la Revelación y, a su vez, es su acreditación
    suprema y máximo motivo de credibilidad, tal como recuerda el texto citado de
    Pablo ``si Cristo no ha resucitado, nuestra predicación es vana y vana es
    nuestra fe'' (1 Cor 15,14).\footnote{ninot 405}}

  Este misterio pascual no aparece como hecho desconectado del conjunto de la vida
  y misión de Jesús, sino que hacia él tienden sus obras y palabras desde el
  comienzo. Cristo pasó por el mundo haciendo el bien, como testimonio de la
  bondad de Dios, y esta acción va orientada a ese punto culminante que es su
  pasión, muerte y resurrección; \citalitinterlin{el testimonio que Jesús va
    ofreciendo durante su vida pública le va a reclamar una entrega definitiva a
    favor de los que o han acogido y frente a la resistencia que ha generado en
    quienes le rechazan.}\footnote{prades 127}
#+END_SRC
***** Lc 22,42 testimonio de confianza absoluta en el Padre
#+BEGIN_SRC latex
  \ifdraft{\subsubsection{Es testimonio y motivo de credibilidad definitvo de
      confianza absoluta en el Padre}}{}

  A lo largo de este camino Jesús manifiesta su confianza en el Padre:
  \citalitinterlin{Padre, te doy gracias porque me has escuchado; yo sé que tu me
    escuchas siempre}\footnote{Jn 11, 41b-42a}; esta relación queda afirmada
  plenamente ante la pasión como confianza puesta en la voluntad del Padre:
  \citalitinterlin{Padre\ldots que no se haga mi voluntad, sino la
    tuya}\footnote{Lc 22,42}. De este modo en el misterio pascual queda
  atestiguada la plena unidad de Cristo con el Padre, en la mayor confianza
  imaginable.\footnote{prades 127}
#+END_SRC
***** Jn 3 16 testimonio de Amor
#+BEGIN_SRC latex
  \ifdraft{\subsubsection{Es testimonio y motivo de credibilidad definitvo del
      Amor de Dios}}{}
#+END_SRC
***** Lc 24,27.45-48 Hch 2,23;3,18 testimonio libertad de Dios en proyecto necesario
#+BEGIN_SRC latex
  \ifdraft{\subsubsection{Es testimonio y motivo de credibilidad definitvo del
      proyecto de salvación deseado libremente por Dios}}{}
#+END_SRC

**** El testimonio de Jesús en su vida pública tiende hacia su entrega definitiva
Para esto he venido
verdadero/falso profeta
**** El testimonio apostólico de la Pascua anuncia hecho y su valor e interpreta
si no hay resurrección tampoco cristo y nuestra predicación es vana
testimonio de pentecostés hch 2
testimonio cornelio hch 10
#+BEGIN_SRC latex
Si Cristo no ha resucitado
sería vana cualquier argumentación, sin embargo, Jesús es <<el Viviente>>,
estuvo muerto, pero vive por los siglos de los siglos.\footnote{Ap 1, 17--18}
Así Pedro da testimonio de ésto el día de Pentecostés: \citalitinterlin{A este
  Jesús lo resucitó Dios, de lo cual todos nosotros somos
  testigos}.\footnote{Hch 2, 32} El apóstol es testigo en la fe sobre un
acontecimiento enraizado en la historia.\footnote{ninot 402 y 406 enraizado}

Así mismo es presentado el testimonio de Pedro en casa de Cornelio donde el
centurión y todos lo que lo acompañaban esperaban reunidos para escuchar lo que
el Señor quisiera comunicarles por medio del apóstol. Pedro, comprendiendo que
la verdad de Dios no hace acepción de personas, narra los hechos que él bien
conoce: \citalitlar{<<Vosotros conocéis lo que sucedió en toda Judea, comenzando
  por Galilea, después del bautismo que predicó Juan. Me refiero a Jesús de
  Nazaret, ungido por Dios con la fuerza del Espíritu Santo, que pasó haciendo
  el bien y curando a todos los oprimidos por el diablo, porque Dios estaba con
  él. Nosotros somos testigos de todo lo que hizo en la tierra de los judíos y
  en Jerusalén. A este lo mataron, colgándolo de un madero. Pero Dios lo
  resucitó al tercer día y le concedió la gracia de manifestarse, no a todo el
  pueblo, sino a los testigos designados por Dios: a nosotros, que hemos comido
  y bebido con él después de su resurrección de entre los
  muertos.>>\footnote{Hch 10, 37--41}} Este testimonio de los hechos queda
enlazado con un testimonio de fe sobre el sentido profundo de lo que Pedro
conoce, Jesús, a quien los apóstoles y el pueblo vieron y escucharon es ahora
juez de vivos y muertos:
\citalitlar{<<Nos encargó predicar al pueblo, dando solemne testimonio de que
  Dios lo ha constituido juez de vivos y muertos. De él dan testimonio todos los
  profetas: que todos los que creen en él reciben, por su nombre, el perdón de
  los pecados.>>\footnote{Hch 10, 42-43}}

El apóstol entiende estos hechos y su alcance religioso y salvífico
interpretándolos en continuidad con la voluntad de Dios manifestada en su acción
en favor del pueblo judío a quién habló por medio de los profetas; voluntad
hecha manifiesta en definitva en \citalitinterlin{Jesús el Nazareno, varón
  acreditado por Dios ante vosotros con los milagros, prodigios y signos que
  Dios realizó por medio de él, como vosotros mismos sabéis}.\footnote{Hch 2,22}

La categoría del testimonio en el anuncio pascual es sobre un hecho enraizado en
la historia, que tiene un alcance religioso y salvífico y que es interpretado
desde la voluntad de Dios manifestada en los hechos y palabras de Cristo. Sin
las obras que Jesús realizó, el testimonio apostólico se derrumba, no
existe.\footnote{Latourelle 1529} Sin la vida y obra, muerte y resurrección de
Jesús \citalitinterlin{resultamos unos falsos testigos de Dios, porque hemos dado
  testimonio contra él, diciendo que ha resucitado a Cristo, a quien no ha
  resucitado}.\footnote{1 Cor 15, 15} Sin embargo, Jesús es testigo verdadero y
acreditado, en su resurreción se realiza en acto lo que ha
prometido\footnote{prades 128}, de modo que el testimonio apostólico queda
acreditado.
#+END_SRC

**** El testimono de Cristo se prolonga en la historia como Resucitado
enunciados:
Dios lo resucitó
Relatos sepulcro vacío...
*** El testimonio en el Antiguo Testamento
#+BEGIN_SRC latex
  \subsection{El testimonio en el Antiguo Testamento}

  I. en el AT se nos describe la revelación como acto testimonial de Dios en estos términos:
  prades 114-115:

  Yahvé da testimonio de sí
  en las obras de la creación
  en la ley que son testimonio
  hombres escogidos como moisés

  II. en el AT la revelación es acto testimonial de Dios ante todo a través de los
  profetas

  latourelle: en el AT el testigo es ante todo el profeta

  el testigo es también el pueblo de Israel

Is 43, 8--12

  la autoridad del testigo no viene de él, sino de su vocación privilegiada y de
  su envío. prades 117

  lo que escinde este nuevo sentido del testimonio de todos sus usos en el
  lenguaje ordinario es que el testimonio no pertenece al testigo. Este procede de
  una iniciativa absoluta, en cuanto a su origen y en cuanto a su contenido.
  prades 118 - ricoeur

  en el AT el testimonio en su sentido más denso y sublime, es el de Dios mismo a
  través de personas escogidas por Él, que reminten continuamente a hechos
  acontecidos en la historia y a la interpretación que los acompaña, para
  reconocer con ello la presencia y actuación de Dios en la historia humana.

  Hay peligro de falsos profetas y también de corazones sordos. El pueblo es
  infiel y testarudo y actua irracionalmente rechazando las múltiples pruebas de
  la predilección divina.



#+END_SRC

*** El testimonio en el Nuevo Testamento
#+BEGIN_SRC latex
\subsection{El testimonio en el Nuevo Testamento}
  El testimonio exterior va acompañado de un testimonio interior del Espíritu que
  hace al hombre capaz de abrirse al evangelio y de adherirse a él por la fe. 1530


!!!Aquí terminar otra vez con mateo y hablando de el universal concreto

#+END_SRC

** El testimonio en el Magisterio
Decálogo sobre el testimonio AG 11 (572 tf ninot)
Evangelii Nuntiandi n21
** El problema de la categoría del testimonio
Si la
revelación misma se apoya en la experiencia humana del testimonio para expresar
una de las relaciones fundamentales que unen al hombre con Dios, la reflexión
teológica se encuentra entonces autorizada a explorar los datos de esta
experiencia.'' Latourelle 1523

El testimonio como manifestación significativa --hagiofánica-- de la misión de la
Iglesia en su realidad histórica es, pues, el punto final, pero también puede ser el
punto inicial, de toda nuestra Teología Fundamental, ya que de él surge el signo
eclesial de creidibilidad que es la mediación próxima para conocer la Revelación. ninot
p. 572

  Sentidos
  empírico-histórico
  jurídico
  ético-antropológico
  teológico
