#+PROPERTY: header-args:latex :tangle ../../tex/ch1/intro_prob_test.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros
* "Testimonio"
** PARTE I
Situación de Nuestros Días

La crisis como síntoma:
Hipótiesis central.
El malestar es siempre síntoma indeleble del carácter en última instancia infinito del
conjunto de exigencias y evidencias que constituyen la experiencia elemental, común a
todo hombre, cuya realización se abre a la constitutiva religiosidad humana. (test
p.8>de lubac y giussianni)
Si eso es así, y la crisis económica y social remite a una dimensión antropológica y
religiosa, debemos entrar en ese orden de realidades para ofrecer una contribución
válida a la convivencia en las sociedades plurales de occidente.

Un mundo multicultural
Entre multiculturalismo y globalización
Como se ve, será de la mayor importancia delinear de modo adecuado la originalidad
irreductible del acontecimiento cristiano -hecho singular de relevancia universal- y su
modo propio de comunicación -el testimonio-, para asegurar con ello la permanencia
efectiva del anuncio de Cristo a los hombres de todas las culturas.

Por una parte se debe distinguir el cristianismo de las ideologías occidentales
(evangelización =/= occidentalización)

Por otra parte, sólo un cristianismo genuino podrá ayudar a los hombres de occidente a
afrontar sus propios dilemas no resuletos sobre el uso de la razón y su relación con la
religión, a la luz de aquella primera síntesis ejemplar de fe y razón que surgió del
diálogo entre el evangelio -nacido en el ambiente judío- y el mundo grecorromano(p. 11)



En el debate sobre multiculturalismo ofrecer una reflexión (in)acabada desde nuestro
enfoque propio: teología fundamental. indicamos algunas claves que puedan ayudar a
profundizar en este debate para precisar la comprensión de la fe cristiana en este
mundo plural como contexto en el que luego situar la doctrina cristiana sobre el
testimonio (p. 13)

1. El debate está siendo beneficioso para la cultura moral y jurídica occidental si
   tomamos como referencia el análisis de Alain Finkielkraut, de 'la' cultura a 'las'
   culturas y derechos de los ciudadanos como antídoto al relativismo de las
   identidades comunitarias
2. discusión sobre la importancia de los aspectos culturales de las comunidades tiene
   como contexto hoy una sociedad posindustrial y globalizada
   a. los factores que sostenian el modelo de separación público-privado: el estado
   moderno y el ciudadano individual, están sufriendo cambios
   b. la difusión de diferencias culturales lleva a replantear algunos temas clásicos
   de la teoría jurídica y social clásica como son la relación entre identidades y
   ciudadania o entre identidades y democracia
3. **discusiones acerca del tipo de racionalidad capaz de afrontar los retos sociales,
   culturales y políticos que conlleva. Sin lugar a dudas, la reelaboración adecuada de
   la racionalidaden el ámbito de las ciencias sociales y de la filosofía es una de las
   premisas necesarias para poder afrontar hasta el final los desafíos multiculturales
   den la perspectiva del testimonio cristiano como veremos.**
4. Debates acerca de la relación entre multiculturalidad y etnicidad. No todas las
   diferencias culturales son de tipo étnico. En este contexto llama la atención la
   estima que encuentra la categoría de mestizaje para superar los límites que todos
   advierten en ciertos planteamientos de la multiculturalidad

En resumen:
1. autores ofrecen crítica del relativismo cultural excluyente
2. desde perspectivas antropológicas y sociológicas e históricas se reinvindica un
   universalismo que permita la comunicación y comparación entre las culturas
3. remitida la necesidad de sentido de la experiencia humana sobre el que se puedan
   entablar intercambios q permitan construir la realidad de una sociedad común
4. se reconoce la necesidad de superar la división entre esfera pública y privada para
   afrontar convincentemente los desafíos que la sociedad ulticultural plantea
5. advertencia de oscilación entre el valor de una identidad comunitaria y valor
   universal del sujeto indiviudal
6. la categoría de mestizaje adquiere un protagonismo nuevo para describir la mezcla de
   hecho y expresar la indistición original y la igualdad plena entre los hombres.



Una sociedad multirreligiosa y (post)secular

Retorno a lo religioso
En una sociedad postsecular, retorno a lo religioso, pero el subjetivismo religioso y
el fundamentalismo violento tienen que ser purificados desde la razón. No actuar desde
la razón es contrario a la naturaleza de Dios.

El problema de la verdad en el contexto de las religiones
no es aceptable una solución para la compatibilidad entre religión, filosofía y cultura
que desde una postura relativista moderna diga adios a la verdad, como una promoción de
un cristianismo de la caridad sin referencia a la verdad. no hace justicia a la
exigencia filosófica de buscar y conocer la verdad, y tampoco hace justicia al Dios de
Jesucristo.

Frente a la tentación de una religión -o de una filosofía que se desentiende de la
pregunta por la verdad se debe reinvindicar que no hay religión humana que no atienda a
la exigencia racional, así como no hay itinerario humano de la razón que no consista en
la búsqueda de la verdad y del significado último de la vida.

la fe católica sostiene que Dios mismo se ha encarnado y, en consecuencia, es posible
que la libertad humana (situada siempre históricamente) lo encuentre en la historia
donde coexisten las religiones. las invitaciones de la iglesia al diálogo son una
dimensión intrínseca de la misión evangelizadora y no simple táctica para facilitar la
convivencia.

El cristianismo en la sociedad actual

I. No universalidad del hecho del cristianismo

A. pretensión cristiana en el mundo multicultural y post secular
Cita de introducción al cristianismo 117-127
el cristianismo al irrumpir en la escena cultural del mundo se orientó a interpelar mas
a la filosofía que a las religiones.

rtzinger argumenta que la fe cristiana carece de universalidad de facto (aunque tiene
pretensión universal)

Cuando decimos que la verdad de todo hombre se manifiesta en el acontecimiento de
Cristo, ¿podemos afirmar que esa manifestación es aquí y ahora tan real como lo fue
para los discípulos? y ¿se puede afirmar que la presencia de esa persona viva, Jesús,
fundamenta una salvación de carácter universal? Este desafío sigue presente en nustra
sociedad. De cómo la fe responda a esta objeción formulada, entre otros, por una
ilustración insatisfecha, depende la solución a la cuestión de la argumentación pública
de los cristianos en la sociedad democrática, a su credibilidad racional, como pedía
Habermas. ******<

B. Insuficiencia de un puro método de integración
No cabe legitimar la posición cristiana mediante una mera acumulación racional de
argumentos que integre las verdades que otros poseen. Hay que justificar el significado
de ese más del cristianismo evitando esto y también lo otro: el que se convierta en un
postulado puramente voluntarista, irracional

al plantear un metodo testimonial para el anuncio cristiano se pretende ofrecer un
método alternativo al de integración y se busca evitar los dos extremos indeseados: la
reducción racionalista y la reducción irracional


C. Autorelativización del cristianismo
disociasiones:
- afirmación hacia adentro del valor absoluto y relativización hacia afuera
- las tradiciones religiosas pueden ser estimadas al precio de verse reducidas a mera
  función referencial de una determinada realidad colectiva
- la verdad del cristianismo sería aceptable a condición de que aparezca sólo como una
  de las posibles razones subjetivas de compromiso social, fe en Dios sería un
  corolario opcional del compromiso ético o religioso
- disociacion fe-caridad, caridad separada de su raiz teologal
- ****dificultad desde el punto de vista linguístico. posturas que distinguen entre una
  relación inefable con el misterio y la insuficiencia de las expresiones linguísticas.
La posibilidad de un diálogo es que la experiencia cristiana sea completa en su
naturaleza y en su comunicación


II. Hacia una interpretación pública de la fe cristiana
síntesis de lo visto (p. 45)
A. Inevitable interpretacion cultural de la fe
dos posturas que no expresan la verdadera naturaleza del cristianismo y su modo de
presencia en la sociedad: cristianismo como religión civil (con una finalidad ética),
cristianismo como sólo anuncio de la cruz (desligado de las cuestiones éticas)
para superar los límites de ámbas necesitmos una interpretación cultural del
cristianismo den la cual, por una parte, el acontecimiento de Jesucristo se muestre en
toda su integridad teologal y por otra se perciba la peculiar razonabilidad propia de
un acontecimiento singular


B. La separación fe y vida en occidente
****La contribución de los cristianos sólo es decisiva si la inteligencia de la fe se
convierte en inteligencia de la realidad, clave de juicio y de transformación

- drama de la separación fe y razón - cristianismo dividido división inteligencia de la
  fe - inteligencia de la realidad se produce un creciente alejamiento, una extrañeza
  entre la mentalidad común y la fe cristiana
- debilitamiento del yo: urge mostrar una comprensión filosófica y teológica del acceso
  humano a la verdad que haga justicia, por una parte, a la verdadera condición del
  hombre en su plena unidad, y por otra, a la índole original del cirstianismo como
  acontecimiento.

III. La necesaria superación del carácter extrínseco de la relación entre fe y razón
síntesis de lo anterior***<(p.59)
A. Superar una concepcion racionalista de razón

B. Fe y saber

C. Fe no es extrínseca a la razón
entre la fe teologal y la visio beatifica hay una diferecnia que no es esencial, sino
de grado. En ese sentido quizá lo mas correcto sea considerar la fe como un
conocimiento indirecto a traves de signos visibles (sacramento, testigo), que remiten a
un fundamento invisible y a una plenitude definitiva en el cielo.

la fe es una forma de conocimiento de la verdad, singularísima por su origen, su medio
y su fin, y a la vez correspondiente con los dinamísmos humanos de razón y libertad que
no se ven mortificados o destruidos, sino exaltados en su índole propia.

en el hombre de fe no se superpone un don ajeno (alienante) al orden de la razón, sino
que por la gracia el creyente ejerce su propia razón del modo más pleno posible para
reconocer aquel Hecho singular que es la encarnación redentora (FR 13)

D. La manifestación del absoluto en la historia
El hombre concreto, al descubrir cada vez más el contenido filial y fraternal de su
exitencia, puede poner más en juego su capacidad de adhesión y de decisión
(autodominio), es decir, se convierte cada vez más en él mismo. LLega así en el tiempo
de la vida y por la gracia de Dios a realizar el ideal de conocimiento verdadero de sí
mismo y de plena libertad en la acción, por el que han suspirado los hombres
antiguos y modernos.



IV. Los ejes de la reflexión: la revelación y la fe; el conocimiento de la realidad; la
vida de la Iglesia y el diálogo con los hombres de hoy


** PARTE III
CAP III
Problema formulado contraponiendo la razón con la tradición/autoridad...

¿puede el hombre conocer el
* Analogía teológica
  :LOGBOOK:
  CLOCK: [2018-08-23 Thu 12:15]--[2018-08-23 Thu 16:32] =>  4:17
  :END:
!!Sin embargo -y esto es un dato de suma importancia-, detrás de todas estas crisis,
  está una noción de razón -y de libertad- que no es la genuinamente cristiana.
  Considero que la noción de logos cristiana no cae bajo la crisis post-moderna. Veamos
  este /novum/ que ha quedado intacto a la deconstrucción moderna.

-> El logos cristiano. Una cosmovisión análoga entre dos univocistas:

!!El logos cristiano emerge como una extraordinaria novedad ente los dos antedichos
  univocismos. Frente al logos estóico -fuerza pneumática divina e inmanente en la
  naturaleza-, y frente al logos neoplatónico, trascendente cuasi-divino y ajeno al
  mundo de lo material, el Logos divino del cristianismo -el Verbum- es, en efecto,
  trascendente: es una Persona de la Santísima Trinidad, que ha tenido -y tiene- una
  concreción histórica: se ha Encarnado,es Dios y hombre. p. 187

p. 190; Orígenes, contra celso 2, 31:

No son importantes para el cristiano 'palabra' o 'lenguaje' o 'razón' o 'ley' en sí
mismas, en un uso absoluto -todas son, de alguna manera, expresiones de la
autocomprensión humana-, sino sólo lo que Dios tiene que decir al hombre, el logos
theou, el hecho de que no es compoatible con el concepto griego de Dios, que Dios
interpele al hombre en el aquí y ahora de su vida.


Carácter veritativo del conocimiento teológico: p.194-195

Consistencia y valor de suplencia del lenguaje teológico p. 196-197
* La teología fundamental
** C2. Revelación cristiana: la palabra universal y definitiva de Dios

   :LOGBOOK:
   CLOCK: [2018-10-31 Wed 13:07]--[2018-10-31 Wed 13:32] =>  0:25
   CLOCK: [2018-10-30 Tue 16:55]--[2018-10-30 Tue 17:20] =>  0:25
   CLOCK: [2018-10-30 Tue 15:55]--[2018-10-30 Tue 16:20] =>  0:25
   :END:
TF tiene en la tractación de la Revelación su centro.

será a partir de la ilustración que aparecerá un tratado sobre la revelación...

primeros documentos eclesiásticos que trabajan el tema son ya de la primera mitad del
siglo xix

vat I será quien consagre el término: 8 veces en Dei filius y 1 en Pastor aeternus

el tratado de revelación se desarrolla, por tanto en ese contexto de ilustración

A partir del Vat II la tratación sobre la revelación encontrará un nuevo lugar en la
teología al convertirse en un tratado dogmático y sera R. Latourelle su más
significativo e influyente promotor... se elabora un nuevo tratado dogmático, un
tratado de la Revelación, llamado a ocupar un puesto junto con los grandes tratados
teológicos como son la fe y los sacramentos.

esta dogmática de la revelación aparece como un complemento al tratado apologético y al
tratado de la fe.

el tratado se presenta con una clara estructura dogmática la cual a partir de su
historia (Biblia, Padres, tradición teológica, Magisterio) propone una reflexión
teológica a partir de la triple vía que sugiere el Vaticano I para alcanzar una cierta
inteligencia de los misterios:
[***]vía de la analogía
    categoría de palabra
    [***]categoría de testimonio
    categoría de encuentro
vía de la unión de los misterios entre sí
revelación con creación, historia, encarnación, fe, milagro, Iglesia, visión de Dios
vía de la finalidad

p. 236

filosofía analítica (Cambridge-Oxford philosophy)

después del desafio sobre el criterio de falsificación defendido por A. Flew...
diversos especialistas han relanzado la dimensión analítico-realista del conocimiento y
han realizado propuestas significativas. Las más relevantes en
R. Swinburne:
The coherence of Theism
The existences of God
Revelation

se muestra la importancia y "necesidad" de la Revelación desde un punto de vista
filosófico-analítico y a partir del que llama "principio de credulidad", basado en el
"principio de probabilidad" -> en esta línea se situa el principio de Caridad propuesto
por Coady en Testimony (p. 21, 155-168,176).

B. Mitchell asume la argumentación cumulativa propuesta por J. H. Newman para mostrar
la racionabilidad de la religión y de la revelación, posteriormente ha encontrado
resonancia en el mundo alemán en Meyer-zu-Schlochtern y H.J. Pottmeyer

El hombre tiene capacidad de escuchar una palabra que sea definitiva (p.239)

[***] Qué es la Revelación y cómo se presenta como palabra última de Dios y "verdadera
estrella de orientación del hombre"? [FR 14ss]

Dios se conoce a través del mismo Dios, a este hecho se refiere en definitiva el
concepto de Revelación

** Categoría de Universal Concreto
Verbum Dei est ratio omnium rerum
Pater verbo su oquod ab ipso procedit dicit se et omnia

El concepto tiene origen idealista

-> universale ante res : idea previa a cualquier realización concreta
universale post res : concepto/nombre posteriormente atribuido a la cosa
universale in re : universal sólo presente en su realidad concreta

*universale concretum (idealismo alemán) : lo universal se une dialécticamente a lo
 particular aunque sin confundirse

el planteamiento inicial de la cuestión se encuentra en lessing en "sobre la
demostración en espíritu y fuerza" (1777)

El enfoque moderno del tema tiene su punto de partida en Hegel (1770-1831)

Schelling la desarrolla desde una línea mas positiva en Filosofía de la Revelación
(1858)

La continuada actualidad del tema de lessing se ve en la respuesta de la fides et ratio
al tema, sobre todo en el n. 95

En el siglo XX diversos autores,
H.U von Balthasar formula y desarrolla mas explícitamente la categoría

la expresión universale concretum aparece teológicamente válida si se la complementa
correctamente: en primer lugar con el adjetivo personale aplicado a Cristo, en segundo
lugar con el adjetivo sacramentale aplicado a la iglesia.

p.252 Qué analogías pueden ser útiles para describir el concepto de Revelación?
- Palabra
- Encuentro
-Presencia***
p.255 Toda Palabra supone alguien presente que la dirige, todo encuentro interpersonal
supone una presencia significativa de los que se encuentran. La presencia es fruto de
una alteridad, de una manifestación nueva e irreductible, de un testimonio
calificado...

p. 256: DV4: Dios envió a su Hijo... a fin de que viviera entre los hombres y
manifestara los secretos de Dios... Jesucristo, pues, con su total presencia y
manifestación personal, con palabras y obras..., con su muerte y resurrección
gloriosa... acaba y confirma que Dios vive con nosotros.

** perspectivas eclesiológicas de la tf
p. 474
"Si se quieren sintetizar las perspectivas eclesiológicas de la teología fundamental
reciente se pueden subrayar los siguientes puntos:
1. se constata una notable valoración de la Iglesia como "signo", pero de un
   "signo-que-se-hace-presente" lo que significa, dada su matriz "sacramental"
2. se constata la importancia de acentuar la contextualización de la Iglesia, dado que
   es una congregatio fidelium y, por tanto, enraizada en un mundo y en unas personas
   concretas, y por tanto, enraizada en un mundo y en unas personas concreta, y por
   tanto, no ajena a los avatares de este mundo y estas personas
3. aparece un nuevo talante fruto de la re-orientación de la teología fundamental: la
   apertura al diálogo, ya sea con las "otras realidades" eclesiales y con otras
   religiones y ya sea con la cultura y el pensamiento contemporáneo en clave auditus
   temporis et alterius"

^ esto sería la monstratio catholica

** [***]tratado Igl = marco englobante tf desde cat testimonio
el tratado sobre la Iglesia es el marco englobante y significativo de toda la
teología fundamental: y esto a partir de la categoría testimonio en su doble función:
fundacional hermenéutica (ad intra) y apologético-misionera (ad extra)
*** circularidad
la categoría del testimonio conlleva también una mutua circularidad entre
1. la dimensión externa del testimonio eclesial que es el testimonio revelador
   fundante -ecclesia mater congregans-
2. la dimensión interiorizada que es el testimonio creyente vivido -ecclesia
   fraternitas congregata-
3. dimensión interior e interiorizadora que es el testimonio constante del Espíritu
   -Spiritus in ecclesia-

^ de aquí emerge la función decisiva del testimonio eclesial de la Revelación y la
Fe como camino de credibilidad que no se reduce a una credibilidad meramente externa y
extrínseca, ni a a una credibilidad puramente interna y subjetiva, sino que centra su
atención en una comprensión de la credibilidad que es invitación externa e interna, a
la vez, a la fe, por razón se su carácter abierto e integrador, propio de la
perspectiva renovada de la eclesiología del Vaticano II

** Vat I -> Vat II
p. 484
El vaticano II, por un proceso de personalización que se extiende a toda la economía de
la revelación y de su transmisión, habla de testimonio personal y comunitario allí
dónde Vaticano I habla de atributos milagrosos de la Iglesia y reenfoca así toda la
eclesiología fundamental, tal como puede verse en un texto paradigmático del Vaticano
II donde se recuerda la fórmula clásica "signo levantado entre las naciones", sacada de
Is 11, 12, citada por el Vaticano I así: "sepan todos (los hijos de la Iglesia) que su
primera y principal obligación en pro de la difusión de la fe es vivir profundamente la
vida cristiana. Así, su fervor en el servicio de Dios y su caridad para con los demás
aportarán nuevo aliento espiritual a toda la Iglesia, que aprecerá como signo levantado
entre las naciones, luz del mundo y sal de la tierra."

La iglesia: credibilidad basada en el testimonio:

en la teología fundamental clásica, en su etapa apologética cláscia fue el referido a
la demonstratio catholica que tenía como objetivo demostrar la veracidad de la Iglesia
católica, de ahí su título clásico: De vera ecclesia.
En los manuales anteriores al Vaticano II los capítulos fundamentales de este tratado
eran: fundación de la Iglesia por Cristo con la institución del primado y la sucesión
apostólica, las notas de la verdadera Iglesia, el magisterio y la tradición y
eventualmente, su relación con la Escritura.


>*** Anscombe habla de la apologética que se hizo en una época relacionada con la
     razonabilidad de la fe y como estas discusiones desaparecen después de vat II y se
     queda un vacío donde estaban antes

** Notas

Siento que quisiera comenzar con la llamada de los primeros discípulos en Mt, donde se
da una interpretación a la llegada de Cristo a Cafarnaúm como cumplimiento y los
discípulos le siguen al momento, aparece Cristo como universal concreto para ellos, ahi
conectando con prades cuando dice ¿podemos afirmar que la presencia de esa persona
viva, Jesús, fundamenta una salvación de caracter universal.

Entendiendo la teología fundamental como disciplina que tiene la tractación de la
Revelación en su centro y la Revelación valorada desde su categoría fundamental:
Universal Concreto, planteamos la pregunta: ¿es razonable estimar el mensaje de Cristo
hoy como verdad universal en este contexto multireligioso y plural?

Entendiendo el tratado sobre la Iglesia como el marco englobante de toda la teología
fundamental y la Iglesia como universal concreto y signo de credibilidad basada en el
testimonio, planteamos la pregunta: ¿?
* William James
p. 27 ¿De qué modo este libro, que nace de la forma descrita, puede ser una guía para
nuestra vida y una revelación?
Para contestar a esta pregunta habríamos de poseer alguna teoría general que nos
mostrara con qué peculiaridades ha de contar una cosa para adquirir valor en lo que
concieren a la revelación... tal teoría sería lo que hemos denominado antes un juicio
espirirtual... Werthurtheil... proposición de valor...
esto como distinto de una proposición existencial.. que sería para contestar a una
pregunta sobre la naturaleza de un fenómeno.
El acercamiento a la religión que James realiza es de un punto de vista existencial,
atendiendo la pregunta sobre la naturaleza del comportamiento religioso desde nua
perspectiva psicológica.
Condiciones existenciales de la religión

Se puede reducir la experiencia de la conversión desde una perspectiva de materialismo
ético?

el análisis del conocer a Dios por medio del testimonio en esta investigación viene a
se respuesta a la pregunta acerca de la revelación, de qué manera esta experiencia
puede ser una guía para nuestra vida y una revelación? Cuenta con las peculiaridades
que le otorgan el valor de revelación?

la prueba definitiva de una creencia no estriba en su origen, sino según Maudsley, en
su funcionamiento en general.



* Esquema
- Introducción: la naturaleza de la pregunta sobre el testimonio

> La presencia del testimonio en la vida comunitaria
- El testimonio en la escritura
- El testimonio en vat ii y magisterio posterior
- El testimonio en la TF
> La pregunta teológica/filosófica sobre el testimonio

* //////

* Inicio
  :LOGBOOK:
  CLOCK: [2019-03-05 Tue 16:28]--[2019-03-05 Tue 16:53] =>  0:25
  CLOCK: [2019-03-05 Tue 15:52]--[2019-03-05 Tue 16:17] =>  0:25
  CLOCK: [2019-03-04 Mon 13:49]--[2019-03-04 Mon 14:14] =>  0:25
  CLOCK: [2019-03-04 Mon 12:48]--[2019-03-04 Mon 13:13] =>  0:25
  CLOCK: [2019-03-04 Mon 12:17]--[2019-03-04 Mon 12:42] =>  0:25
  :END:
* Introducción general al problema del Testimonio
** La naturaleza de la pregunta sobre el testimonio
*** notas
Este capítulo comienza planteando la quaestio que será investigada en el trabajo la
idea central es la descripción que hace Agustín de la pregunta sobre el tiempo: del
mismo modo en que el tiempo es una realidad presente en nuestro lenguaje cotidiano el
testimonio forma parte del lenguaje ordinario de nuestra vida eclesial. Así mismo,
preguntar o preguntarse qué es el tiempo... "explícalo"... nos deja sin palabras,
tambíen el testimonio, tan presente en nuestro lenguaje nos puede dejar en la misma
situación. Witt utiliza esta descripción para enmarcar la naturaleza de las preguntas
filosóficas.
Este primer capítulo estará organizado así, en un primer bloque la descripción del
testimonio como fenómeno familiar y presente en nuestro lenguaje y vida eclesial, en un
segundo bloque se plantea qué pasa cuando decímos: explícalo, cuando surge la
necesidad, como dice Witt de traer a la mente una explicación.
La motivación de enfocar de este modo la pregunta es introducir el tema dentro de su
language-game o como tal... el testimonio forma parte de nuestro language-game
eclesial. Otra motivación es enmarcar la pregunta desde el principio en la metodología
de W. y de Ans.
*** texto
#+BEGIN_SRC latex
  \section{Naturaleza de la pregunta sobre el testimonio}
    Es una experiencia familiar en nuestras comunidades reunirnos en torno a la
    Sagrada Escritura y compartir la Palabra buscando en ella luz para nuestro
    presente. Una escena evangélica en torno a la cual muchos se han reunido a
    escuchar al Señor es la narración de Mateo del comienzo de la misión pública de
    Jesús y la llamada de los primeros discípulos:

    \citalitlar{Al enterarse Jesús de que habían arrestado a Juan se retiró a
      Galilea. Dejando Nazaret se estableció en Cafarnaún, junto al mar, en el
      territorio de Zabulón y Neftalí, para que se cumpliera lo dicho por medio del
      profeta Isaías:\\
      <<Tierra de Zabulón y tierra de Neftalí, camino del mar, al otro lado del
      Jordán, Galilea de los gentiles. El pueblo que habitaba en tinieblas vio una
      luz grande; a los que habitaban en tierra y sombras de
      muerte, una luz les brilló>>.\\
      Desde entonces comenzó Jesús a predicar diciendo: <<Convertíos, porque está
      cerca el reino de los cielos>>.\\
      Paseando junto al mar de Galilea vio a dos hermanos, a Simón, llamado Pedro, y
      a Andrés, que estaban echando la red en el mar, pues eran pescadores. Les
      dijo: <<Venid en pos de mí y os haré pescadores de hombres>>. Inmediatamente
      dejaron las redes y lo siguieron. Y pasando adelante vio a otros dos hermanos,
      a Santiago, hijo de Zebedeo, y a Juan, su hermano, que estaban en la barca
      repasando las redes con Zebedeo, su padre, y los llamó. Inmediatamente dejaron
      la barca y a su padre y lo siguieron.\footnote{Mt~4,12--22}}

    No sería difícil ahora visualizar una variedad de escenarios en los que este
    texto pueda ser discutido en nuestro contexto eclesial. Es proclamado, por
    ejemplo, en el ciclo A el III Domingo del Tiempo Ordinario. Es así que puede
    escucharse en las reflexiones del Papa Francisco en el Ángelus en la Plaza de
    San Pedro, donde destaca el hecho de que la misión de Jesús comience en una zona
    periférica:
    \citalitlar{Es una tierra de frontera, una zona de tránsito donde se
      encuentran personas diversas por raza, cultura y religión. La Galilea se
      convierte así en el lugar simbólico para la apertura del Evangelio a todos
      los pueblos. Desde este punto de vista, Galilea se asemeja al mundo de hoy:
      presencia simultánea de diversas culturas, necesidad de confrontación y
      necesidad de encuentro. También nosotros estamos inmersos cada día en una
      <<Galilea de los gentiles>>, y en este tipo de contexto podemos asustarnos y
      ceder a la tentación de construir recintos para estar más seguros, más
      protegidos. Pero Jesús nos enseña que la Buena Noticia, que Él trae, no está
      reservada a una parte de la humanidad, sino que se ha de comunicar a todos.
      Es un feliz anuncio destinado a quienes lo esperan, pero también a quienes
      tal vez ya no esperan nada y no tienen ni siquiera la fuerza de buscar y
      pedir.\autocite{francisco2014angelus}}

    Tambíen el Papa Benedicto XVI ofreció su comentario y se fijó en la fuerza de esa
    noticia que Cristo comenzaba a anunciar:
    \citalitlar{El término ``evangelio'', en tiempos de Jesús, lo usaban los
      emperadores romanos para sus proclamas. Independientemente de su contenido, se
      definían ``buenas nuevas'', es decir, anuncios de salvación, porque el
      emperador era considerado el señor del mundo, y sus edictos, buenos presagios.
      Por eso, aplicar esta palabra a la predicación de Jesús asumió un sentido
      fuertemente crítico, como para decir: Dios, no el emperador, es el Señor del
      mundo, y el
      verdadero Evangelio es el de Jesucristo.\\
      La ``buena nueva'' que Jesús proclama se resume en estas palabras: ``El reino
      de Dios —--o reino de los cielos-—- está cerca''. ¿Qué significa esta expresión?
      Ciertamente, no indica un reino terreno, delimitado en el espacio y en el
      tiempo; anuncia que Dios es quien reina, que Dios es el Señor,
      y que su señorío está presente, es actual, se está realizando.\\
      Por tanto, la novedad del mensaje de Cristo es que en él Dios se ha hecho
      cercano, que ya reina en medio de nosotros, como lo demuestran los milagros y
      las curaciones que realiza.\autocite{benedicto2008angelus}}

    No sólo en San Pedro, sino que también podría encontrarse este texto en la
    celebración de la eucaristía domincal resonando en las comunidades y parroquias;
    en las homilias, oraciones, reflexiones o cánticos, invitando a la conversión y
    haciendo nueva la invitación de Jesús: <<Convertíos, porque está cerca el reino
    de los cielos>>. Quizás tambíen se le oiga entre algún grupo juvenil donde
    Simón, Andrés, Santiago y Juan sean tratados como modelos de vocación a la vida
    consagrada o al apostolado, atendiendo con entusiasmo cómo lo dejaron todo en el
    momento para seguir a Jesús. Seguramente algún joven reconociendo aquella
    llamada: <<Venid en pos de mí y os haré pescadores de hombres>> sonando como voz
    dentro de sí.

    El texto de la Escritura es tratado en estos contextos como testimonio de la
    vida de Jesucristo y de la vida de aquellos que le llaman maestro y que
    participan de su misión. No son, sin embargo, tratados como historias del
    pasado, sino como palabras para el presente. Es hoy que la Buena Noticia no está
    reservada a una parte de la humanidad, sino que ha de comunicarse a todos como
    insiste el Papa Francisco. Es hoy que Dios se hace cercano en Cristo para reinar
    en medio de nosotros como enseñó Benedicto XVI. Es hoy que Jesús nos invita a la
    conversión y a ir en pos de él.

    Es sobre esta costumbre de la Iglesia que ha de formularse ahora una pregunta.
    Resultará apropiado apelar aquí a otra costumbre de la Iglesia y buscar luz para
    esto en las Confesiones de San Agustín. Pensando en Dios y pensando en el
    tiempo, Agustín queda inquieto por una serie de preguntas: \citalitlar{¿Qué es,
      pues, el tiempo? ¿Quién podrá explicar esto fácil y brevemente? ¿Quién podrá
      comprenderlo con el pensamiento, para hablar luego de él? Y, sin embargo, ¿qué
      cosa más familiar y conocida mentamos en nuestras conversaciones que el
      tiempo? Y cuando hablamos de él, sabemos sin duda qué es, como sabemos o
      entendemos lo que es cuando lo oímos pronunciar a otro. ¿Qué es, pues, el
      tiempo? Si nadie me lo pregunta, lo sé; pero si quiero explicárselo al que me
      lo pregunta, no lo sé.\footnote{De las confesiones xi.14 (n. 17)}}

    Agustín expresa su extrañeza de que un concepto empleado ordinariamente se
    torne tan desconocido cuando llega la hora de explicarlo. ``¿Qué es el
    tiempo?'' o ``¿qué es conocer?'', ``¿la libertad?'' y ``¿qué es la fe?'' son
    preguntas de este tipo; distintas, por ejemplo, a ``¿cuál es el peso exacto de
    este objeto?'' o ``¿quién será la próxima persona en entrar por esa
    puerta?''.\footnote{cf. Wittgenstein BT. p.304} Preguntar ``¿qué es conocer una
    verdad para la vida por el testimonio de la Escritura?'' sería, como la pregunta
    agustiniana sobre el tiempo, una pregunta sobre la naturaleza o esencia de
    este fenómeno. Un concepto familiar en la vida de la Iglesia como el
    testimonio queda enmarcado como problema cuando nos acercamos a él queriendo
    comprender su esencia.

    Para continuar explorando la naturaleza de la pregunta sobre el testimonio
    resultará útil recurrir aquí al modo en que el psicólogo William James formula
    algunas preguntas sobre la Escritura al comienzo de sus conferencias sobre la
    \emph{religion natural}. Apelando a la literatura de lógica de su época a
    comienzos del siglo XX distingue dos niveles de investigación sobre cualquier
    tema: aquellas preguntas que se resuelven por medio de prposiciones
    \emph{existenciales}, como ``¿qué constitución, qué origen, qué historia tiene
    esto?'' o ``¿cómo se ha realizado esto?''; en segundo lugar las preguntas que se
    responden con proposiciones de \emph{valor} como ``¿cuál es la importancia,
    sentido o significado actual de esto?''. A este segundo juicio James lo denomina
    \emph{juicio espiritual}. Aplicando esta distinción a la Biblia se cuestiona:

    \citalitlar{ <<¿Bajo qué condiciones biográficas los escritores sagrados aportan
      sus diferentes contribuciones al volumen sacro?>>, <<¿Cúal era exactamente el
      contenido intelectual de sus declaraciones en cada caso particular?>>. Por
      supuesto, éstas son preguntas sobre hechos históricos y no vemos cómo las
      respuestas pueden resolver, de súbito, la última pregunta: <<¿De qué modo este
      libro, que nace de la forma descrita, puede ser una guía para nuestra vida y
      una revelación?>>. Para contestar habríamos de poseer alguna teoría general
      que nos mostrara con qué peculiaridades ha de contar una cosa para adquirir
      valor en lo que concierne a la revelación; y, en ella misma, tal teoría sería
      lo que antes hemos denominado un juicio espiritual.\footnote{William James
        Variedades de la Experiencia Religiosa p. 27} }

    Desde esta perspectiva la pregunta sobre cómo el testimonio de la escritura
    puede ser una guía para nuestra vida es una investigación sobre la importancia,
    sentido o significado que ésta tiene actualmente. La respuesta emitida en
    conclusión sería un juicio de valor sobre el fenómeno del testimonio. James
    propone que sería necesaria una teoría general que explicara qué características
    ha de tener alguna cosa para que merezca ser valorada como revelación. Así
    planteado, la pregunta sobre el testimonio sería atendida adecuadamente por
    medio de una investigación que indagara dentro de este fenómeno para descubrir
    los elementos que le otorgan el valor adecuado como para ser considerado guía
    para nuestra vida o una revelación. La explicación de dichos elementos
    configurarían una teoría que nos permitiría juzgar un testimonio concreto como
    valioso, o no, como guía o revelación para nuestras vidas.

    La ruta sugerida por este modo de conducir la investigación, sin embargo, nos
    dejaría apartados de la manera en que Elizabeth Anscombe se plantea un problema
    filosófico. En el trasfondo de su metodología filosófica está la propuesta por
    Ludwig Wittgenstein. Aunque se verá con más detalle qué implica esto, es
    necesario anticipar ahora algo acerca del modo en que ambos se encaminan a la
    hora de atender una investigación filosófica.

    En \emph{Investigaciones Filosóficas} \S89 Wittgenstein hace referencia al
    texto antes citado de las Confesiones para describir la peculiaridad de las
    preguntas filosóficas:
    \citalitlar{ Augustine says in \emph{Confessions} XI. 14, ``quid est ergo
      tempus? si nemo ex me quaerat scio; si quaerenti explicare velim nescio''.
      --This could not be said about a question of natural science (``What is the
      specific gravity of hydrogen'', for instance). Something that one knows when
      nobody asks one but no longer knows when one is asked to explain it, is
      something that has to be \emph{called to mind}. (And it is obviously
      something which, for some reason, it is difficult to call to mind.)}

    Para Wittgenstein es de gran importancia atender el paso que damos para
    resolver la perplejidad causada por el reclamo de explicar un fenómeno. El
    deseo de aclararlo nos puede impulsar a buscar una explicación dentro del
    fenómeno mismo, o como él diría: \citalitinterlin{We feel as if we had to see
      right into phenomena}.\footnote{\S90} Esta predisposición nos puede conducir
    a ignorar la amplitud del modo en que el lenguaje sobre esto es empleado en la
    actividad humana y a enfocarnos sólo en un elemento particular del lenguaje
    sobre este fenómeno y tomarlo como un ejemplo paradigmático para construir un
    modelo abstrayendo explicaciones y generalizaciones sobre él. Esta manera de
    indagar, le parece a Wittgenstein, nos hunde cada vez más profundamente en un
    estado de frustración y confusión filosófica de modo que llegamos a imaginar
    que para alcanzar claridad \citalitinterlin{we have to describe extreme
      subtleties, which again we are quite unable to describe with the means at
      our disposal. We feel as if we had to repair a torn spider's web with our
      fingers.}\footnote{\S106}

    La alternativa que Wittgenstein propone es una investigación que no esté
    dirigida hacia dentro del fenómeno, sino \citalitinterlin{as one might say,
      towards the \emph{`possibilities'} of phenomena. What that means is that we
      call to mind the \emph{kinds of statement} that we make about phenomena}. A
    este esfuerzo le denomina ``investigación gramática''. La describe de este modo:
    \citalitlar{ Our inquiry is therefore a grammatical one. And this inquiry sheds
      light on our problem by clearing misunderstandings away. Misunderstandings
      concerning the use of words, brought about, among other things, by certain
      analogies between the forms of expression in different regions of our
      language. -- Some of them can be removed by substituting one form of
      expression for another; this may be called `analysing' our forms of
      expression, for sometimes this procedure resembles taking things
      apart.\footnote{\S90}} El modo de salir de nuestra perplejidad, por tanto,
    consiste en prestar cuidadosa atención al uso que hacemos de hecho con las
    palabras y la aplicación que empleamos de las expresiones. Esto está al
    descubierto en nuestro uso del lenguaje de modo que la dificultad para
    \emph{traer a la mente} aquello que aclare un fenómeno no está en descubrir algo
    oculto en éste, sino en aprender a valorar lo que tenemos ante nuestra vista:
    \citalitinterlin{The aspects of things that are most important for us are hidden
      because of their simplicity and familiarity. (One is unable to notice
      something -- because it is always before one's eyes.)}\footnote{\S129} La
    descripción de los hechos concernientes al uso del lenguaje en nuestra actividad
    humana ordinaria componen los pasos del tipo de investigación sugerido por
    Wittgenstein. Hay cierta insatisfacción en este modo de proceder, como él mismo
    afirma: \citalitlar{Where does this investigation get its importance from, given
      that it seems only to destroy everything interesting: that is, all that is
      great and important? (As it were, all the buildings, leaving behind only bits
      of stone and rubble.) But what we are destroying are only houses of cards, and
      we are
      clearing up the ground of language on which they stood.\\
      The results of philosophy are the discovery of some piece of plain nonsense
      and the bumps that the understanding has got running up against the limit of
      language. They -- these bumps -- make us see the value of that discovery.}

    Anscombe, al igual que Wittgenstein, no se limita a emplear un sólo método para
    hacer filosofía, como afirma el mismo Wittgenstein: \citalitinterlin{There is
      not a single philosophical method, though there are indeed methods, different
      therapies as it were}.\footnote{\S133} Sin embargo si atendemos a su modo de
    hacer filosofía podemos encontrarla empleando lenguajes o juegos de lenguaje
    imaginarios para arrojar luz sobre modos actuales de usar el lenguaje o esquemas
    conceptuales; del mismo modo su trabajo esta lleno de ejemplos donde la
    encontramos examinando con detenimiento el uso que de hecho hacemos del
    lenguaje.\footnote{cf. teichmann p. 228-229} Es visible en ella ese
    \citalitinterlin{modo característicamente Wittgensteniano de rebatir la
      tendencia del filósofo de explicar alguna cuestión filosóficamente enigmática
      inventando una entidad o evento que la causa, así como los físicos inventan
      partículas como el gravitón}.\footnote{There is however a somehow
      chracteristically Wittgenstenian way of countering the philosopher's tendency
      to explain a philosophically puzzling thing by inventing an entity or event
      which causes it, as physicists invent particles like the graviton. From plato
      to witt intro xix}

    Según el título de este trabajo ha prometido, el análisis sobre el testimonio
    que será expuesto es el que se encuentra desarrollado en el pensamiento de
    Elizabeth Anscombe. La pregunta planteada al inicio: ¿qué es conocer una verdad
    para la vida por el testimonio de la Escritura?, entendida como investigación
    filosófica, será examinada en las descripiciones que Anscombe realiza sobre el
    modo de usar el lenguaje sobre el creer, la confianza, la verdad, la fe y otros
    fenómenos relacionados con el conocer por testimonio. Nuestro título adiverte
    además que ésta es una investigación en perspectiva teólogica, cabe
    inmendiatamente añadir algo breve al respecto.

    ¿Qué es teología?, se preguntaba Joseph Ratzinger en su alocución en el 75
    aniversario del nacimiento del cardenal Hermann Volk en 1978, e introducía
    suscintamente su respuesta a esa pregunta tan grande diciendo:

    \citalitlar{Cuando se intenta decir algo sobre esta materia, precisamente como
      tributo al cardenal Volk y a su pensamiento, se asocian, poco menos que
      automáticamente, dos ideas. Me viene a las mientes, por un lado, su divisa (y
      título de uno de sus libros): \emph{Dios todo en todos}, y el programa
      espiritual contenido en ella; por otra parte, se aviva el recuerdo de lo que
      ya antes se ha insinuado: un modo de interrogar total y absolutamente
      filosófico, que no se detiene en reales o supuestas comprobaciones históricas,
      en diagnósticos sociológicos o en técnicas pastorales, sino que se lanza
      implacablemente a la busqueda de los fundamentos.\\
      Según esto, cabría formular ya dos tesis que pueden servirnos de hilo
      conductor para nuestro interrogante sobre la esencia de la teología:\\
      1. La teología se refiere a Dios.\\
      2. El pensamiento teológico está vinculado al modo de cuestionar filosófico
      como a su método fundamental.\footnote{teoría de los principios teológicos, p
        380}}
    Esta investigación sobre el testimonio como parte de la vida de la Iglesia será
    realizada atendiendo al modo de cuestionar filosófico realizado por Elizabeth
    Anscombe como método, examinando esta experiencia en referencia a Dios, es
    decir, como vivencia de su ser y de su obrar.

    Hasta aquí simplemente se ha descrito un modo de andar a través de la discusión
    acerca de la categoría del testimonio atendiendo el hecho de que tanto la
    temática como la figura de Anscombe otorgan a este camino peculiaridades que hay
    que tener en cuenta. Siendo concientes de estas particularidades podríamos ahora
    ampliar más el horizonte respecto de dos cuestiones brevemente expuestas
    anteriormente. En primer lugar es necesario ampliar la descripción hecha hasta
    aquí del fenómeno del testimonio en la vida de la Iglesia, ya que aunque nos
    resulte familiar relacionarlo con el testimonio de la Sagrada Escritura, tanto
    en el Magisterio de la Iglesia como en la propia Escritura se haya presente la
    categoría del testimonio con una riqueza que merece la pena explorar. En segundo
    lugar habría que detallar todavía mejor lo problemático del testimonio, sobre
    todo cuando se considera su importancia en la transmisión de la fe y el anuncio
    del Evangelio en el mundo.
#+END_SRC
*** notas
!!Es pregunta filosófica como la describe Witt desde Agustín
!!Es pregunta teológica como la describe Ratzinger

^Sigue presente en nuestra sociedad el desafío de responder a una objeción formulada
entre otros por una ``ilustración insatisfecha'', en palabras de Angelo Scola; una
corriente de pensamiento que ha tenido la capacidad de plantear preguntas pero no ha
sabido encontrarle respuestas adecuadas. De ésta forman parte Kant, Lessing o Jaspers
(p. 35-36)

No es un escenario extraño encontrarnos en una misa escuchando esta palabra y llevar
esto a nuestra experiencia presente y encontrar en ellas una descripción de una
experiencia con la que sentimos que podemos identificarnos.

No sólo en la parroquia, sino también en ámbitos diversos en donde nuestras acciones o
palabras son genuino deseo de seguir a Cristo, su obra, su enseñanza. Actuar como él.
Actuar con él. En la oficina, en la calle, en la familia, quisieramos elegir en ese
instante, sobre cualquier otro modo de actuar esa ruta que implica seguir a Cristo.
Peeero.

De las confesiones xi.14 (n. 17) ¿Qué es, pues, el tiempo? ¿Quién podrá explicar esto
fácil y brevemente? ¿Quién podrá comprenderlo con el pensamiento, para hablar luego de
él? Y, sin embargo, ¿qué cosa más familiar y conocida mentamos en nuestras
conversaciones que el tiempo? Y cuando hablamos de él, sabemos sin duda qué es, como
sabemos o entendemos lo que es cuando lo oímos pronunciar a otro. ¿Qué es, pues, el
tiempo? Si nadie me lo pregunta, lo sé; pero si quiero explicárselo al que me lo
pregunta, no lo sé.

Prades en dar testimonio p. 37 plantea Cuando decimos que la verdad de todo hombre se
manifiesta en el acontecimiento de Cristo, ¿podemos afirmar que esa manifestación es
aquí y ahora tan real como lo fue para los discípulos? y se puede afirmar que la
presencia de esa persona viva, Jesús, fundamenta una salvación de carácter universal?
Ese desafío sigue presente en nuestra sociedad.


Fides et ratio 13

ratio sacramentalis de la revelación.... a esta se le puede unir una ratio
testimonialis (dar testimonio 449)

13. De todos modos no hay que olvidar que la Revelación está llena de
misterio. Es verdad que con toda su vida, Jesús revela el rostro del Padre, ya que ha
venido para explicar los secretos de Dios; 13 sin embargo, el conocimiento que nosotros
tenemos de ese rostro se caracteriza por el aspecto fragmentario y por el límite de
nuestro entendimiento. Sólo la fe permite penetrar en el misterio, favoreciendo su
comprensión coherente.

El Concilio enseña que « cuando Dios revela, el hombre tiene que someterse con la fe
».14 Con esta afirmación breve pero densa, se indica una verdad fundamental del
cristianismo. Se dice, ante todo, que la fe es la respuesta de obediencia a Dios. Ello
conlleva reconocerle en su divinidad, trascendencia y libertad suprema. El Dios, que se
da a conocer desde la autoridad de su absoluta trascendencia, lleva consigo la
credibilidad de aquello que revela. Desde la fe el hombre da su asentimiento a ese
testimonio divino. Ello quiere decir que reconoce plena e integralmente la verdad de lo
revelado, porque Dios mismo es su garante. Esta verdad, ofrecida al hombre y que él no
puede exigir, se inserta en el horizonte de la comunicación interpersonal e impulsa a
la razón a abrirse a la misma y a acoger su sentido profundo. Por esto el acto con el
que uno confía en Dios siempre ha sido considerado por la Iglesia como un momento de
elección fundamental, en la cual está implicada toda la persona. Inteligencia y
voluntad desarrollan al máximo su naturaleza espiritual para permitir que el sujeto
cumpla un acto en el cual la libertad personal se vive de modo pleno.15 En la fe, pues,
la libertad no sólo está presente, sino que es necesaria. Más aún, la fe es la que
permite a cada uno expresar mejor la propia libertad. Dicho con otras palabras, la
libertad no se realiza en las opciones contra Dios. En efecto, ¿cómo podría
considerarse un uso auténtico de la libertad la negación a abrirse hacia lo que permite
la realización de sí mismo? La persona al creer lleva a cabo el acto más significativo
de la propia existencia; en él, en efecto, la libertad alcanza la certeza de la verdad
y decide vivir en la misma.

Para ayudar a la razón, que busca la comprensión del misterio, están también los signos
contenidos en la Revelación. Estos sirven para profundizar más la búsqueda de la verdad
y permitir que la mente pueda indagar de forma autónoma incluso dentro del misterio.
Estos signos si por una parte dan mayor fuerza a la razón, porque le permiten
investigar en el misterio con sus propios medios, de los cuales está justamente celosa,
por otra parte la empujan a ir más allá de su misma realidad de signos, para descubrir
el significado ulterior del cual son portadores. En ellos, por lo tanto, está presente
una verdad escondida a la que la mente debe dirigirse y de la cual no puede prescindir
sin destruir el signo mismo que se le propone.

Podemos fijarnos, en cierto modo, en el horizonte sacramental de la Revelación y, en
particular, en el signo eucarístico donde la unidad inseparable entre la realidad y su
significado permite captar la profundidad del misterio. Cristo en la Eucaristía está
verdaderamente presente y vivo, y actúa con su Espíritu, pero como acertadamente decía
Santo Tomás, « lo que no comprendes y no ves, lo atestigua una fe viva, fuera de todo
el orden de la naturaleza. Lo que aparece es un signo: esconde en el misterio
realidades sublimes ».16 A este respecto escribe el filósofo Pascal: « Como Jesucristo
permaneció desconocido entre los hombres, del mismo modo su verdad permanece, entre las
opiniones comunes, sin diferencia exterior. Así queda la Eucaristía entre el pan común
».17

El conocimiento de fe, en definitiva, no anula el misterio; sólo lo hace más evidente y
lo manifiesta como hecho esencial para la vida del hombre: Cristo, el Señor, « en la
misma revelación del misterio del Padre y de su amor, manifiesta plenamente el hombre
al propio hombre y le descubre la grandeza de su vocación »,18 que es participar en el
misterio de la vida trinitaria de Dios.19


William James plantea temprano en sus lectures el tipo de pregunta: ¿De qué modo este
libro, que nace de la forma descrita, puede ser una guía para nuestra vida y una
revelación? p. 27 y plantea, para contestar a esta pregunta habríamos de poseer una
teoría general que nos mostrara con qué peculiaridades ha de contar una cosa para
adquirir valor en lo que concierne a la revelación; y, en ella misma, tal teoría sería
lo que antes hemos denominado un juicio espiritual, éste distinto de un juicio
existencial, sería una proposición de valor como respuesta a cuestionamiento sobre el
sentido, importancia o significado actual de algo. La pregunta ¿qué son las tendencias
religiosas? esta relacionada con un nivel de investigación, ¿cuál es su signifcado
filosófico? con otro. El primero se atiende con un juicio existencial del tipo: cuál es
su naturaleza, cómo se ha realizado? ¿Qué constitución, qué origen, qué historia tiene?
El segundo se atendería con un juicio de valor del tipo: cuál es su importancia, su
sentido, su significado actual?

En sus lectures William adopta un punto de vista puramente existencial, cosa que
advierte dado que causa sorpresa entre personas religiosas. Considera los fenómenos de
la experiencia religiosa biológica y psicológicamente como si fuesen simpres hechos
curiosos de la historia individual, algunos pensaran que se degrada un tema tan
sublime, pero su intención no es desacreditar el aspecto religioso de la vida.


** El testimonio en la Sagrada Escritura
*** Texto
#+BEGIN_SRC latex
  \section{La Categoría del Testimonio en la Sagrada Escritura}
  La Iglesia de hoy, como María, conserva el Evangelio meditándolo en su
  corazón.\footnote{Lc 2,19} Así está presente en el centro de la comunidad
  creyente el anuncio de Cristo vivo como fundamento de su esperanza en cada etapa
  de la historia. Este motivo de esperanza conservado es también compartido y
  expresado, según la enseñanza del apóstol:\citalitinterlin{glorificad a Cristo
    en vuestros corazones, dispuestos siempre a dar explicación a todo el que os
    pida una razón de vuestra esperanza}.\footnote{1Pe 3, 15} Este Evangelio
  atesorado como fundamento en el centro de la vida de la comunidad eclesial, así
  como Buena Nueva proclamada y transmitida en el tiempo y en el mundo puede ser
  comprendido como tres testimonios que son uno:<<palabra vivida en el
  Espíritu>>\footnote{cf. Porque es el Espíritu el que impulsa a la Iglesia a
    perseguir son obras de evangelización; es el Espíritu quien santifica y
    fecunda el testimonio de su vida; y es el Espíritu el que inspira la fe, la
    nutre y la profundiza. Es el Espíritu quien alivia entre estos tres
    testimonios que son uno: el de la palabra vivida en el Espíritu. A través del
    testimonio, el Espíritu internaliza el testimonio externo de la Buena Nueva de
    la salvación en Jesucristo y lo lleva al cumplimiento de la fe, que es la
    respuesta del amor del verdadero amor de la humanidad a través del Padre.
    Cristo; Latourelle Evangelisation et temoignage ninot 582}.

  La Evangelización puede ser entendida en este sentido como testimonio de la
  <<palabra de vida>>\footnote{1Jn 1,1} que los apóstoles anuncian como testigos
  de lo que han contemplado y palpado\footnote{1Jn 1,1}. Es también el testimonio
  de los cristianos que, acogiendo esta palabra, la viven,
  poniendo por obra lo que ella enseña. Es además testimonio del Espíritu Santo
  que internaliza el testimonio externo de la Buena Noticia y lo lleva al
  cumplimiento de la fe en cada persona.\footnote{cf. latourelle, ninot 582} Es el
  Espíritu el que santifica y fecunda la acción de los cristianos, es tambíen el
  que impulsa y sostiene la acción de la Iglesia; es el Espíritu el que inspira la
  fe, la nutre y la profundiza.\footnote{latourelle evangelisation et temoignage}

  Este dinamísmo fundamental que puede encontrarse vivo hoy en la comunidad de la
  Iglesia ha actuado en ella desde su origen y le ha acompañado en cada época.
  Según esto es posible valorar lo que se transmite en la tradición eclesial como
  la perpetuación de la actividad de Cristo y los apóstoles, que es a su vez
  proyección del testimonio divino.\footnote{ el testimonio divino se proyecta
    luego en el apostólico y se perpetúa en el testimonio eclesial. Por eso, el
    testimonio es revelación en la actividad de Cristo y de los apóstoles y es
    transmisión de la revelación en la tradición eclesial. ninot 573}

  En la actividad de Cristo el testimonio divino queda proyectado como
  interpelación a la libertad realizada por la identidad propia de Jesús:
  \citalitinterlin{Si conocieras el don de Dios y quién es el que te dice ``dame
    de beber'' le pedirías tu, y él te daría agua viva}\footnote{Jn 4, 10};
  \citalitinterlin{``¿Crees tú en el Hijo del hombre?''\ldots ``¿Y quién es,
    Señor, para que crea en él?''\ldots ``Lo estás viendo: el que te está
    hablando, ese es''}\footnote{Jn 9, 35--37}. En la actividad apostólica, el
  testimonio divino sigue interpelando la libertad humana como manifestación de
  Jesús Resucitado. Los apóstoles actuan como testigos de los acontecimientos de
  la Pascua de Jesús y su valor salvífico\autocite[Cf.][576]{ninot2009tf} y este
  testimonio es descrito como acción del Espíritu que impulsa la tarea apostólica
  y que da nueva vida a los que acogen el anuncio de la Buena Noticia.

  Puede encontrarse un ejemplo de esto en el testimonio de Felipe. El apóstol sale
  más allá de Jerusalén hacia Samaria, y todavía llega más lejos, al compartir la
  Buena Noticia de Jesús con un extranjero Etíope: \citalitlar{El Espíritu dijo a
    Felipe: <<Acércate y pégate a la carroza>>. Felipe se acercó corriendo, le oyó
    leer el profeta Isaías, y le preguntó: <<¿Entiendes lo que estás leyendo?>>.
    Contestó: <<¿Y cómo voy a entenderlo si nadie me guía?>>. E invitó a Felipe a
    subir y a sentarse con él. El pasaje de la Escritura que estaba leyendo era
    este: \emph{Como cordero fue llevado al matadero, como oveja muda ante el
      esquilador, así no abre su boca. En su humillación no se le hizo justicia.
      ¿Quién podrá contar su descendencia? Pues su vida ha sido arrancada de la
      tierra.} El eunuco preguntó a Felipe: <<Por favor, ¿de quién dice esto el
    profeta?; ¿de él mismo o de otro?>>. Felipe se puso a hablarle y, tomando pie
    de este pasaje, le anunció la Buena Nueva de Jesús. Continuando el camino,
    llegaron a un sitio donde había agua, y dijo el eunuco: «Mira, agua. ¿Qué
    dificultad hay en que me bautice?». Mandó parar la carroza, bajaron los dos al
    agua, Felipe y el eunuco, y lo bautizó. Cuando salieron del agua, el Espíritu
    del Señor arrebató a Felipe. El eunuco no volvió a verlo, y siguió su camino
    lleno de alegría. \footnote{Hch 8, 29--39}} Además de ser ejemplo de la
  actividad apostólica, este relato puede servir como síntesis del modo en que la
  categoría del testimonio está presente en la Escritura.

  El testimonio comienza con la iniciativa de Dios mismo que impulsa tanto la
  palabra profética del Antiguo Testamento como el anuncio apostólico del Nuevo
  Testamento. Esta iniciativa de Dios tiende hacia el testimonio de la Palabra
  definitiva del Padre que es Cristo resucitado. En aquellos que creen en el
  testimonio de Dios se engendra alegría y vida nueva. En palabras de R.
  Latourelle:
  \citalitlar{En el trato de las tres personas divinas con los hombres existe un
    intercambio de testimonios que tiene la finalidad de proponer la revelación y
    de alimentar la fe. Son tres los que revelan o dan testimonio, y esos tres son
    más que uno. Cristo da testimonio del Padre, mientras que el Padre y el
    Espíritu dan testimonio del Hijo. Los apóstoles a su vez dan testimonio de lo
    que han visto y oído del verbo de la vida. Pero su testimonio no es la
    comunicación de una ideología, de un descubrimiento científico, de una técnica
    inédita, sino la proclamación de la salvación prometida y finalmente
    realizada.\autocite[1531]{latourelle2000testimonio}}
  De este modo el anuncio del apóstol Felipe sirve aquí como un ejemplo específico
  del testimonio, que ilustra sin embargo, una noción
  que\citalitinterlin{atraviesa toda la Escritura y se corresponde con la
    estructura misma de la revelación.}\footnote{la noción de testimonio atraviesa
    la Escritura y se coresponde con la estructura misma de la Revelación: <<la
    Escritura describe la revelación como una economía del testimonio>>.
    \autocite[109]{prades2015testimonio}} El testimonio está presente a lo largo
  de la Escritura junto a otras categorías como pueden ser la de `alianza',
  `palabra', `paternidad' o `filiación', como parte del \citalitinterlin{grupo de
    analogías empleadas por la Escritura para introducir al hombre en las riquezas
    del misterio divino}.\footnote{latourelle p. 1523}

  Esta clave servirá para dar enfoque a un examen sobre la categoría del
  testimonio en la Escritura. ¿Qué nos dice el Antiguo y el Nuevo Testamento de la
  revelación como acto testimonial de Dios? Esta pregunta supone que la revelación
  comparte los rasgos de la actividad humana que es el testimonio, sin embargo,
  como Latourelle adiverte: \citalitinterlin{globalmente se puede decir que el
    testimonio bíblico asume pero al mismo tiempo exalta hasta sublimarlos, los
    rasgos del testimonio humano.}\footnote{cf. latourelle 1526 Globalmente se
    puede decir que el testimonio bíblico asume pero al mismo tiempo exalta hasta
    sublimarlos, los rasgos del testimonio humano. latourelle 1526}

  Cabe añadir una última consideración. La revelación de Dios entendida como acto
  testimonial suyo tiene como expresión definitiva el misterio pascual de
  Cristo.\footnote{cf. el misterio pascual al cual tiende toda la existencia
    terrena de Cristo, constituye el acto testimonial por excelencia de Dios
    prades 128} Este misterio ocupa el lugar principal en el testimonio bíblico:
  \citalitlar{la Resurrección como ``final'' de la unicidad del acontecimiento de
    Jesucristo, encarnado, muerto y resucitado, subraya específicamente la
    definitividad de la existencia humana salvada por Dios en la carne de Jesús de
    Nazaret, ya que la autocomunicación de Dios ha alcanzado su palabra última en
    la Resurrección de Jesucristo, y por eso es prenda de la resurrección de todos
    los hombres.\footnote{ninot 404}}
  Como tal, parece justo tratar el testimonio que es el misterio pascual en su
  propio apartado. Y será éste precisamente el punto de partida para esta
  descripción de la categoría del testimonio en la Escritura.
  #+END_SRC
*** Notas
El testimonio en la escritura

intro: la igl no olvida el motivo de su esperanza

si partimos desde la vivencia de la igle hoy nos encontramos una igl q guarda y
transmite el motivo de su esperanza esta acción evangelizadora la podemos recoger en la
exp: palabra vivida en el esp

esto implica un triple test

esta acción de la iglesa y su tradición es también perpetuación de la accion de cristo/
apostoles

así como cristo interpela: si supieras... confias... soy yo
también los apóstoles orientan... es él
a modo de síntesis felipe

hacia donde refiere en definitiva el testimonio de Cristo y los apóstoles es a alguien,
al Dios salvador

de modo que podemos decir que
en la escritura la categoría del testimonio está presente como estructura de la propia
revelación

es así que nos encontramos al test como una de las analogías empleadas...

si entendemos la revelación desde su estructura testimonial
podemos decir que es acto testimonial de Dios por excelencia en la resu
acto testimonial de Dios en el AT
acto testimonial de Dios en el NT

*** El testimonio en el anuncio pascual
  Lo que se quiere decir es que

  - el misterio pascual (en sí) es el acto testimonial por excelencia de Dios
  - creer en este misterio implica dar asentimiento a la manifestación más plena y
  al motivo de credibilidad más cierto

  Este misterio es anunciado por los apóstoles y
  la categoría del testimonio está presente en el
  anuncio pascual en el sentido de que los apóstoles son testigos:
  de un hecho enraizado en la historia
  del valor salvífico de este hecho
  de la interpretación basada en la autenticidad de los dichos y obras de Jesús

  Cristo mismo es testigo veraz y acreditado, verdadero profeta porque realiza lo
  que ha prometido.

  Enunciados:
  Dios lo resucitó de entre los muertos
  Relatos del sepulcro vacío y apariciones


  el testimonio en sí del suceso pascual
  el testimonio que Cristo da de éste como revelación/promesa/anuncio
  el testimonio apostólico de éste
  el testimonio de Cristo como resucitado y glorificado

#+BEGIN_SRC latex
  \subsection{El testimonio en el misterio y anuncio pascual}
#+END_SRC
**** El hecho en sí de la Pascua constituye el acto testimonial por excelencia de Dios
***** estatuto epistemológico especial
#+BEGIN_SRC latex
  <<Cristo ha resucitado>>\footnote{Cf.~1Tes 4,15; 1Cor 15,12--20; Rom 6,4} es la
  confesión que está en el núcleo del más primitivo anuncio del
  evangelio.\autocite[Cf.][403]{ninot2009tf} Creer en esta noticia conlleva acoger la
  manifestación más plena de la Revelación y la motivación más definitiva para
  creer. En este sentido:
  \citalitlar{La Resurrección de Jesús mirada desde la perspectiva de la teología
    fundamental presupone un estatuto epistemológico peculiar, puesto que es el
    punto culminante y objeto de la Revelación y, a su vez, es su acreditación
    suprema y máximo motivo de credibilidad, tal como recuerda el texto citado de
    Pablo ``si Cristo no ha resucitado, nuestra predicación es vana y vana es
    nuestra fe'' (1 Cor 15,14).\autocite[405]{ninot2009tf}}

  Este misterio pascual no aparece como hecho desconectado del conjunto de la vida
  y misión de Jesús, sino que hacia él tienden sus obras y palabras desde el
  comienzo. Cristo pasó por el mundo haciendo el bien, como testimonio de la
  bondad de Dios, y esta acción va orientada a ese punto culminante que es su
  pasión, muerte y resurrección; \citalitinterlin{el testimonio que Jesús va
    ofreciendo durante su vida pública le va a reclamar una entrega definitiva a
    favor de los que lo han acogido y frente a la resistencia que ha generado en
    quienes le rechazan.}\autocite[127]{prades2015testimonio}
#+END_SRC
***** Lc 22,42 testimonio de confianza absoluta en el Padre
#+BEGIN_SRC latex
  A lo largo de este camino Jesús manifiesta su confianza en el Padre:
  \citalitinterlin{Padre, te doy gracias porque me has escuchado; yo sé que tu me
    escuchas siempre}\footnote{Jn 11, 41b-42a}; esta relación queda afirmada
  plenamente ante la pasión como confianza puesta en su voluntad:
  \citalitinterlin{Padre\ldots que no se haga mi voluntad, sino la
    tuya}\footnote{Lc 22,42}. De este modo en el misterio pascual queda
  atestiguada la plena unidad de Cristo con el Padre, en la mayor confianza
  imaginable.\footnote{prades 127}
#+END_SRC
***** Jn 3 16 testimonio de Amor
#+BEGIN_SRC latex
  A lo largo de su misión, Cristo dió testimonio del amor del Padre
  \citalitinterlin{habiendo amado a los suyos que estaban en el
    mundo\ldots}\footnote{Jn 13,1}. En el misterio pascual, donde
  \citalitinterlin{los amó hasta el extremo}\footnote{Jn 13, 1}, queda confirmado
  definitivamente como testigo del Padre. Con su entrega ofrece el testimonio
  pleno del amor salvador del Padre: \citalitinterlin{Porque tanto amó Dios al
    mundo, que entregó a su Unigénito, para que todo el que cree en él no perezca,
    sino que tenga vida eterna.}\footnote{Jn 3,16}
#+END_SRC
***** Lc 24,27.45-48 Hch 2,23;3,18 testimonio libertad de Dios en proyecto necesario
#+BEGIN_SRC latex
  A lo largo de su vida, Cristo también es testigo de la necesidad del camino
  salvífico que es libre e irrevocable decisión trinitaria de redimir a los
  hombres\footnote{prades 128}: \citalitinterlin{¿No sabíais que yo debía estar en
    las cosas de mi Padre?}\footnote{Lc 2, 49}; \citalitinterlin{El hijo del
    hombre tiene que padecer mucho, ser reprobado por los ancianos, sumos
    sacerdotes y escribas, ser ejecutado y resucitar a los tres días.}\footnote{Mc
    8, 31} Este testimonio de la voluntad divina es comprendido por los discípulos
  por la luz del Resucitado; \citalitinterlin{les abrió el entendimiento para
    comprender las Escrituras\ldots ``así está escrito: el Mesías padecerá,
    resucitaráde entre los muertos al tercer día y en su nombre se proclamará la
    conversión''}.\footnote{Lc 24, 45-47a}
#+END_SRC
**** El testimonio de Jesús en su vida pública tiende hacia su entrega definitiva
Para esto he venido
verdadero/falso profeta
#+BEGIN_SRC latex
  La intencionalidad de este testimonio que Jesús ofrece a lo largo de su vida
  hasta llegar al acto testimonial definitivo de Dios al mundo que es el misterio
  pascual aparece con claridad en la respuesta de Cristo a Pilato antes de la
  Pasión: \citalitinterlin{Yo para esto he nacido y para esto he venido al mundo:
    para dar testimonio de la verdad. Todo el que es de la verdad escucha mi
    voz.}\footnote{Jn 18,37} En su vida pública y en su misión Cristo ha actuado
  como profeta que anuncia la verdad; da a conocer al Padre, a quien nadie ha
  visto nunca, pero que el Hijo sí conoce.\footnote{cf. Jn 1,18 vease también
    Jesús de Nazaret 24} En el misterio pascual Jesús se manifiesta como verdadero
  profeta, acreditado por el hecho mismo de la Resurrección donde se ha realizado
  en él mismo lo que ha revelado y prometido. \footnote{prades 128}
#+END_SRC
**** El testimonio apostólico de la Pascua anuncia hecho y su valor e interpreta
si no hay resurrección tampoco cristo y nuestra predicación es vana
testimonio de pentecostés hch 2
testimonio cornelio hch 10
#+BEGIN_SRC latex
  La resurrección de Cristo no sólo acredita su propio testimonio, sino que
  sostiene el testimonio apostólico. Si Cristo no ha resucitado sería vana
  cualquier argumentación, sin embargo, Jesús es <<el Viviente>>, estuvo muerto,
  pero vive por los siglos de los siglos.\footnote{Ap 1, 17--18}

  Los apóstoles son testigos de la vida de Cristo, de sus palabras y acciones,
  muerte y resurrección. De tal modo, son testigos en continuidad con el testimonio
  de Cristo. El testimonio apostólico es un anuncio de estos hechos que ellos
  conocen y cuyo valor han reconocido por la fe. Así Pedro proclama estas cosas el
  día de Pentecostés: \citalitinterlin{A este Jesús lo resucitó Dios, de lo cual
    todos nosotros somos testigos}.\footnote{Hch 2, 32} El apóstol es testigo en
  la fe sobre un acontecimiento enraizado en la historia.\footnote{ninot 402 y 406
    enraizado}

  Así mismo es presentado el testimonio de Pedro en casa de Cornelio donde el
  centurión y todos lo que lo acompañaban esperaban reunidos para escuchar lo que
  el Señor quisiera comunicarles por medio del apóstol. Pedro, comprendiendo que
  la verdad de Dios no hace acepción de personas, narra los hechos que él bien
  conoce: \citalitlar{<<Vosotros conocéis lo que sucedió en toda Judea, comenzando
    por Galilea, después del bautismo que predicó Juan. Me refiero a Jesús de
    Nazaret, ungido por Dios con la fuerza del Espíritu Santo, que pasó haciendo
    el bien y curando a todos los oprimidos por el diablo, porque Dios estaba con
    él. Nosotros somos testigos de todo lo que hizo en la tierra de los judíos y
    en Jerusalén. A este lo mataron, colgándolo de un madero. Pero Dios lo
    resucitó al tercer día y le concedió la gracia de manifestarse, no a todo el
    pueblo, sino a los testigos designados por Dios: a nosotros, que hemos comido
    y bebido con él después de su resurrección de entre los
    muertos.>>\footnote{Hch 10,37--41}} Este testimonio de los hechos queda
  enlazado con un testimonio de fe sobre el sentido profundo de lo que Pedro
  conoce, Jesús, a quien los apóstoles y el pueblo vieron y escucharon, es ahora
  juez de vivos y muertos:
  \citalitlar{<<Nos encargó predicar al pueblo, dando solemne testimonio de que
    Dios lo ha constituido juez de vivos y muertos. De él dan testimonio todos los
    profetas: que todos los que creen en él reciben, por su nombre, el perdón de
    los pecados.>>\footnote{Hch 10,42--43}}

  El apóstol entiende estos hechos y su alcance religioso y salvífico
  interpretándolos en continuidad con la voluntad de Dios manifestada en su acción
  en favor del pueblo judío a quién habló por medio de los profetas; voluntad
  hecha manifiesta en definitva en \citalitinterlin{Jesús el Nazareno, varón
    acreditado por Dios ante vosotros con los milagros, prodigios y signos que
    Dios realizó por medio de él, como vosotros mismos sabéis}.\footnote{Hch 2,22}

  Este anuncio es experiencia del Resucitado que comió y bebió con ellos;
  él mismo se apareció a los que él quiso dando testimonio de su
  resurrección. \citalitinterlin{Cristo glorificado manifiesta su verdad a los que
    él quiere y esta manifestación es simultaneamente testimonio de su identidad y
    testimonio de que él es la Vida (1Jn 5,11)}\autocite[129]{prades2015testimonio}

  El misterio divino que se manifiesta en la Pascua de Jesús no deja de expresarse
  en el anuncio pascual realizado por los apóstoles. Ellos son testigos de un
  hecho enraizado en la historia, que tiene un alcance religioso y salvífico y que
  es interpretado desde la voluntad de Dios manifestada en los hechos y palabras
  de Cristo. Sin las obras que Jesús realizó, el testimonio apostólico se
  derrumba, no existe.\autocite[Cf.][1529]{latourelle2000testimonio} Sin la vida y
  obra, muerte y resurrección de Jesús \citalitinterlin{resultamos unos falsos
    testigos de Dios, porque hemos dado testimonio contra él, diciendo que ha
    resucitado a Cristo, a quien no ha resucitado}.\footnote{1Cor 15,15}

  En Cristo, testigo acreditado por su Resurrección, encuentra su cumplimiento
  la promesa hecha al pueblo de Israel: \citalitinterlin{El Señor, tu Dios, te
    suscitará de entre los tuyos, de entre tus hermanos, un profeta como yo. A
    él lo escucharéis}.\footnote{Dt 18, 15 véase intro Jesús de Nazaret} Así
  como el misterio pascual y su anuncio no están desconectados de la vida de
  Cristo, tampoco lo están de la acción salvadora de Dios en el AT. Como veremos,
  el misterio divino se manifiesta a un pueblo que también está llamado a dar
  testimonio, reconociendo desde la confianza en Dios el valor salvífico de los
  sucesos de su historia.
#+END_SRC

**** El testimono de Cristo se prolonga en la historia como Resucitado
     enunciados:
Dios lo resucitó
Relatos sepulcro vacío...
#+BEGIN_SRC latex

#+END_SRC
*** El testimonio en el Antiguo Testamento
#+BEGIN_SRC latex
  \subsection{La acción testimonial de Dios en el Antiguo Testamento}
#+END_SRC
*** Notas
  I. en el AT se nos describe la revelación como acto testimonial de Dios en estos términos:
  prades 114-115:

  Yahvé da testimonio de sí
  en las obras de la creación
  en la ley que son testimonio
  hombres escogidos como moisés

  II. en el AT la revelación es acto testimonial de Dios ante todo a través de los
  profetas

  latourelle: en el AT el testigo es ante todo el profeta

  el testigo es también el pueblo de Israel

Is 43, 8--12


  su envío. prades 117

  lo que escinde este nuevo sentido del testimonio de todos sus usos en el
  lenguaje ordinario es que el testimonio no pertenece al testigo. Este procede de
  una iniciativa absoluta, en cuanto a su origen y en cuanto a su contenido.
  prades 118 - ricoeur

  en el AT el testimonio en su sentido más denso y sublime, es el de Dios mismo a
  través de personas escogidas por Él, que reminten continuamente a hechos
  acontecidos en la historia y a la interpretación que los acompaña, para
  reconocer con ello la presencia y actuación de Dios en la historia humana.

  Hay peligro de falsos profetas y también de corazones sordos. El pueblo es
  infiel y testarudo y actua irracionalmente rechazando las múltiples pruebas de
  la predilección divina.

El pueblo, sin embargo, es un pueblo ciego y sordo. \citalitinterlin{YHWH se
  enfrenta a un pueblo infiel y testarudo (Jer 2; Os 2; Ez 16) que demuestra la
  irracionalidad de su obrar al rechazar las múltiples pruebas de la
  predilección divina}.\footnote{prades 119}


*** Texto
#+BEGIN_SRC latex
  En el AT encontramos ese <<intercambio de testimonios>> que existe en el trato
  de las tres personas divinas con los
  hombres.\autocite[Cf.][1531]{latourelle2000testimonio} También aquí la acción
  testimonial divina se despliega de diversos modos. En la vida del pueblo de la
  alianza YHWH da testimonio de sí a través de la creación, la ley y, de modo
  eminente, en personas elegidas y enviadas por
  él.\autocite[Cf.][114s]{prades2015testimonio} Esta manifestiación divina implica
  como testigo al mismo pueblo, hacia quien ha sido dirigida la voz del Señor.

  La literatura sapiencial recoge la profundización en la experiencia de
  Dios que ha tenido el pueblo de Israel. En ella se describe el acceso posible al
  conocimiento de Dios a partir de los bienes visibles o de sus obras:
  \citalitlar{Son necios por naturaleza todos los hombres que han ignorado a Dios
    y no han sido capaces de conocer al que es a partir de los bienes visibles, ni
    de reconocer al artífice fijándose en sus obras, sino que tuvieron por dioses
    al fuego, al viento, al aire ligero, a la bóveda estrellada, al agua impetuosa
    y a los luceros del cielo, regidores del mundo. Si, cautivados por su
    hermosura, los creyeron dioses, sepan cuánto los aventaja su Señor, pues los
    creó el mismo autor de la belleza. Y si los asombró su poder y energía,
    calculen cuánto más poderoso es quien los hizo, pues por la grandeza y
    hermosura de las criaturas se descubre por analogía a su creador.\footnote{Sab
      13,1--5}}
  El Dios que puede ser reconocido por analogía en el asombro y belleza de las
  ciraturas es un Dios personal que concede sabiduría al
  piadoso:\citalitinterlin{Aún quedan misterios mucho más grandes: tan solo hemos
    visto algo de sus obras. Porque el Señor lo ha hecho todo y a los piadosos les
    ha dado la sabiduría.}\footnote{Eclo 43,32--33} Esta sabiduria es justicia y
  raíz de inmortalidad:
  \citalitlar{Pero tú, Dios nuestro, eres bueno y fiel, eres paciente y todo lo
    gobiernas con misericordia. Aunque pequemos, somos tuyos y reconocemos tu
    poder, pero no pecaremos, sabiendo que te pertenecemos. Conocerte a ti es
    justicia perfecta y reconocer tu poder es la raíz de la
    inmortalidad.\footnote{Sab 15,1--3}}
  En este sentido la misma creación es acto testimonial de Dios donde se comunica
  su misterio y la vida que Él ofrece.

  YHWH también aparece en el AT como testigo de los mandamientos contenidos en la
  Ley.\autocite[Cf.][115]{prades2015testimonio} Ésta queda grabada en las ``tablas
  del testimonio'' y confiadas a Moisés:\citalitinterlin{Cuando acabó de hablar
    con Moisés en la montaña del Sinaí, le dio las dos tablas del Testimonio,
    tablas de piedra escritas por el dedo de Dios.}\footnote{Ex 31,18} Este
  testimonio se enfrenta a un pueblo con el corazón extraviado:\citalitinterlin{Al
    acercarse al campamento y ver el becerro y las danzas, Moisés, encendido en
    ira, tiró las tablas y las rompió al pie de la montaña.}\footnote{Ex 32,19}
  Sin embargo Dios no se detiene ante la dureza del pueblo. Las tablas del
  testimonio son reconstruidas:
  \citalitlar{El Señor dijo a Moisés: <<Labra dos tablas de piedra como las
    primeras y yo escribiré en ellas las palabras que había en las primeras tablas
    que tú rompiste.>>\ldots~<<Escribe estas palabras: de acuerdo con estas
    palabras concierto alianza contigo y con Israel>>.\footnote{Ex 34,1.27}}
  Moisés, que conoció el nombre del Señor (Ex 3,13s), y habló con Él como un amigo
  (Ex 33,11), aparece ante el pueblo como testigo del único Dios, y de su lealtad
  con el pueblo. Pertenece a
  aquellos que el Señor elige como testigos suyos en cada etapa de la historia del
  pueblo de Israel como testimonio suyo y de su fidelidad.

  Este es el modo eminente en que el AT describe el testimonio que Dios dirige al
  pueblo. Los profetas y ungidos por YHWH son testigos del Señor y de su
  compromiso con el pueblo. La vida totalmente comprometida del profeta expresa
  tanto a Dios, absoluto que comunica, como su lealtad:
  \citalitlar{es Dios quien da testimonio de sí mismo y de sus obras y designios a
    través de las personas elegidas, que se comprometen en su integridad como
    testigos de YHWH incluso hasta la muerte si el testimonio les lleva a ello.
    Por eso, la autoridad del testimonio no descansa en los testigos, sino en el
    mismo YHWH, que es quien los escoge y
    envía.\autocite[116s]{prades2015testimonio}}
  En tanto que testigos, la acción de estos escogidos puede ser descrita según los
  rasgos que tiene la actividad humana de dar testimonio, sin embargo la noción de
  testigo que aplica a estos elegidos de Dios va más allá de la que encontraríamos
  en el lenguaje ordinario. La vida del profeta queda comprometida con un
  testimonio que no le pertenece, sino que \citalitinterlin{procede de una
    iniciativa absoluta, en cuanto a su origen y en cuanto a su
    contenido}\autocite[118]{prades2015testimonio} puesto que viene de Dios y es
  testimonio de sí. Aquí la categoría de testimonio significa mas allá de su uso
  ordinario en la actividad humana y adquiere un sentido religioso como dimensión
  totalmente nueva\autocite[Cf.][118]{prades2015testimonio}.

  El testimonio de YHWH que el profeta proclama con su actividad y el compromiso
  de su vida implica al pueblo y le hace testigo:
  \citalitlar{Saca afuera a un pueblo que tiene ojos, pero está ciego, que tiene
    oídos, pero está sordo. Que todas las naciones se congreguen y todos los
    pueblos se reúnan. ¿Quién de entre ellos podría anunciar esto, o proclamar los
    hechos antiguos? Que presenten sus testigos para justificarse, que los oigan y
    digan: es verdad. Vosotros sois mis testigos --—oráculo del Señor--—, y
    también mi siervo, al que yo escogí, para que sepáis y creáis y comprendáis
    que yo soy Dios. Antes de mí no había sido formado ningún dios, ni lo habrá
    después. Yo, yo soy el Señor, fuera de mí no hay salvador. Yo lo anuncié y os
    salvé; lo anuncié y no hubo entre vosotros dios extranjero. Vosotros sois mis
    testigos --—oráculo del Señor--—: yo soy Dios.\footnote{Is 43,8--12}}
  El siervo es testigo que el Señor ha escogido para que el pueblo sepa, crea y
  comprenda que YHWH es el único Dios verdadero. Al compartir este saber de Dios
  con el pueblo, éstos también están llamados a ser testigos. Ninguna otra nación
  podría anunciar como ellos lo que YHWH ha hecho para proveer, liberar, salvar.

  Así como el profeta, el pueblo es escogido y enviado por YHWH y por medio de él
  el Señor da testimonio de sí mismo y se propone como quien da sentido y
  consistencia a toda la realidad humana. Este testimonio tiene importancia social
  puesto que está llamado a ser proclamado, y esta proclamación implica el
  compromiso de los actos y la vida del testigo, es decir, del profeta y todo el
  pueblo.\autocite[Cf.][1526s]{latourelle2000testimonio}

  El testimonio de Dios a través de personas escogidas por Él en el AT queda
  constituido por la narración de hechos que acontecen en la historia, estos
  hechos son interpretados en su valor absoluto y carácter redentor, y son
  confesados como actuación de Dios en la vida
  humana.\autocite[Cf.][119]{prades2015testimonio} Esto vuelve a ponernos en
  conexión con la figura de Cristo como profeta acreditado por su Resurrección y
  los apóstoles como verdaderos testigos de un hecho enraizado en la historia,
  confesado desde la fe e interpretado desde la acción de Dios en Jesús. Esta
  sintonía anticipa lo que se verá a continuación sobre el testimonio en el Nuevo
  Testamento. En él la acción testimonial de Dios se describe en continuidad con
  la tradición veterotestamentaria y llegará a su manifestación plena en el
  misterio pascual.
#+END_SRC

*** El testimonio en el Nuevo Testamento
Ninot Lucas y Juan
Latourelle Testimonio Apostólico y Juan
Prades Testimonio de Cristo, del E. S. y de los apóstoles
  El testimonio exterior va acompañado de un testimonio interior del Espíritu que
  hace al hombre capaz de abrirse al evangelio y de adherirse a él por la fe. 1530


!!!Aquí terminar otra vez con mateo y hablando de el universal concreto

-> Jesús Universal Concreto: testigo singular y testimonio absoluto del absoluto
Su acción historica, su persona e identidad tienen valor absoluto, esto es singular

    -Su testimonio tiene caracter público y jurídico, es sometido a juicio
     jn 15 22-24: testimonio con caracter performativo, no es acogido
    -es testimonio de la Luz
    -es testimonio del Hijo
    -cricularidad entre testimonio y su credibilidad
Juan mismo anuncia lo que ha visto y oído del verbo de la vida para que por la fe en su
testimonio los hombres entren en comunión de vida con el Padre y con su Hijo.


- Espiritu Santo: testigo de la verdad plena
    Jn 15, 26 el dará testimonio de mi
    Jn 16, 13 guiará hasta lverdad plena

latou: El hombre, sin embargo, no sería capaz de acoger por la fe este testimonio del
absoluto, manifestado en la carne y el lenguaje de Jesús, sin una atracción interior
(Jn 6,44), que es un don del Padre y un testimonio del Espíritu (1Jn 5,9--10).

En este momento, el testimonio se interioriza casi por completo, ya que se dice que el
que cree en Cristo tiene dentro de sí el testimonio de Dios. El testimonio que el
creyente posee en sí mismo es el testimonio que el Espíritu da del Hijo.

-> los apostoles son testigos: martires
lc 24,48 los apósotles serán testigos de estas cosas

su testimonio es anuncio de un acontecimiento presente y abierto al futuro, que sigue
aconteciendo en el tiempo... prades 146

la cadena de transmisión viva del testimonio cristiano tiene dos aspectos históricos
inseparables. como dos momentos históricos de un único testimonio pospascual prades 148

-> su finalidad es el bautismo prades 150

-> en conclusión:
testimonio es estructura de la revelación. el que la revelación tenga esta forma nos
dice que la revelación es una forma suprema de amor y libertad que tiene su raiz en el
Don de Dios. El hecho de ser una comunicción libre y amorosa nos muestra su aspecto
profundamente humano; el hecho de que es don de Dios nos muestra su aspecto no
solamente humano. prades 152

lo que se quiere decir aquí es que
en el nuevo testamento la acción testimonial de Dios mas eminente en el AT que es
hablar por medio de un elegido adquiere todavía una dimensión más sublime porque Jesús
es manifestación concreta del absoluto. Este testimonio absoluto no puede ser acogido
sin una atracción interior que es testimonio del Espíritu. El único testimonio
pospascual se realiza en el tiempo en los testigos oculares y los martires, testigos de
compromiso. la finalidad del testimonio es el bautismo.

decir que dios se revela al modo de un testimonio es decir que su revelación es acto de
libertad y amor, que interpela la libertad nuestra.

la revelación es testimonio del hijo, del padre y del espíritu como acción libre suya
que es el motivo de credibilidad, es don de Dios

la revelación es testimonio de una comunicación que interpela nuestra libertad que ha
de acoger la verdad comunicada que es Dios mismo.

#+BEGIN_SRC latex
  \subsection{La acción testimonial de Dios en el Nuevo Testamento}
  El Evangelio de Mateo enseña que el día que Jesús llegó a Cafarnaún a comenzar
  su predicación se cumplieron las promesas que Dios había hecho por medio de los
  profetas. Ese día el Reino de los cielos quedó desvelado en su cercanía. Allí la
  vida de los primeros discípulos cambió al punto y definitivamente. El testimonio
  de Cristo no es cualquier anuncio o cualquier hecho, sino que tiene un valor
  absoluto. Jesús de Nazaret \citalitinterlin{no se limita a proponer una cierta
    inspiración espiritual o un cierto sentido ético para el obrar de la persona o
    del pueblo, sino que pretende ser radicalmente ``testimonio de la verdad'' (Jn
    18,37) de alcance universal.}\autocite[126]{prades2015testimonio} Jesús es
  testimonio de carácter singular,\autocite[Cf.][279]{ninot2009tf} en quien se da
  a conocer el momento de la plenitud de la
  salvación,\autocite[Cf.][290]{ninot2009tf} presencia del hombre nuevo y
  ``paradigma universal de humanidad''\autocite[Cf.][291]{ninot2009tf}. Este valor
  universal de la verdad que se comunica en Jesús se desarrolla y se manifiesta en
  sus acciones concretas: comiendo con los pecadores o sanando a los enfermos es
  donde se muestra \citalitinterlin{el camino, la verdad y la
    vida}\footnote{Cf.~Jn 14,6} para todos.

  Este testimonio de Cristo, su vida, actos y palabras, fue sometido al juicio de
  sus contemporaneos. Asombrados porque no enseña como los demás y por las signos
  que realiza, se cuestionan sobre su autoridad y poder. Entonces Jesús también
  tiene que ofrecer testimonio de su credibilidad. La respuesta a este juicio del
  pueblo se halla en su ministerio en sintonía con las Escrituras:
  \citalitinterlin{Hoy se ha cumplido esta Escritura que acabáis de
    oir}\footnote{Lc 4,21}; donde el pueblo puede encontrar la vida y el sentido
  que buscan: \citalitinterlin{estudiáis las Escrituras pensando encontrar en
    ellas vida eterna; pues ellas están dando testimonio de mi, ¡y no queréis
    venir a mí para tener vida!}\footnote{Jn 5, 39--40}. El testimonio de
  credibilidad de Jesús ante el pueblo se encuentra también en sus obras, que son
  las obras del Padre y son confirmación y realización de sus enseñanzas:
  \citalitinterlin{Si no hago las obras de mi Padre, no me creáis, pero si las
    hago, aunque no me creáis a mí, creed a las obras, para que comprendáis y
    sepáis que el Padre está en mí y yo en el Padre}\footnote{Jn 10,38}.

  El singular testimonio de Cristo es comunicación de la verdad con valor
  universal. El testimonio de Cristo es también su actividad e identidad que hacen
  creíble lo que comunica. De este modo entre lo que Jesús testimonia y la
  credibilidad que suscita su testimonio hay una circularidad constante:
  \citalitlar{La pretensión única que encerraba su testimonio resultaba tan
    exorbitante que hubiera sido inaceptable para los hombres si no fuera porque
    sus obras, sus palabras y, en rigor, su presencia misma, lo hacían
    profundamente razonable en su
    singularidad.\autocite[124]{prades2015testimonio}}

  Acoger el testimonio de Jesús es escuchar la Escritura y creer en las obras del
  Padre. Sin embargo la palabra de Cristo choca con el odio de aquellos que son
  hostiles a la verdad y que, rechazando su testimonio, se juzgan a sí
  mismos.\footnote{Pero la palabra de Cristo choca con la contestación y el odio.
    Enfrentados con Cristo, los judíos, que representan al conjunto del mundo
    hostil a la verdad, rechazan su testimonio y se juzgan a sí
    mismos.\autocite[1530]{latourelle2000testimonio}} \citalitlar{Si yo no hubiera
    venido y no les hubiera hablado, no tendrían pecado, pero ahora no tienen
    excusas de su pecado. El que me odia a mí, odia también a mi Padre. Si yo no
    hubiera hecho en medio de ellos obras que ningún otro ha hecho, no tendrían
    pecado, pero ahora las han visto y me han odiado a mí y a mi Padre\footnote{Jn
      15,22--24}}

  Jesús es \citalitinterlin{la luz que brilla en la tiniebla y la tiniebla no la
    recibió}\footnote{Jn 1,5}. Jesús es el \citalitinterlin{unigénito, que está en
    el seno del Padre, es quien lo ha dado a conocer}\footnote{Jn 1,18}. Este
  testimonio es manifestación de la comunión trinitaria. Cristo revela al Padre y
  comunica al Espíritu, y su identidad de Hijo es manifestada como acción del
  Padre y del Espíritu: \citalitinterlin{Apenas se bautizó Jesús, salió del agua;
    se abrieron los cielos y vio que el Espíritu de Dios bajaba como una paloma y
    se posaba sobre él. Y vino una voz de los cielos que decía: <<Este es mi Hijo
    amado, en quien me complazco>>.}\footnote{Mt 4,16--17}

  La acción testimonial de Dios que se describe en el Nuevo Testamento está
  concentrada en la persona de Cristo y en su relación manifiesta con el Padre y
  el Espíritu se expresa el testimonio de la Trinidad misma:
  \citalitlar{la Escritura describe la actividad reveladora de la trinidad en
    forma de testimonios mutuos. El Hijo es el testigo del padre, y como tal se da
    a conocer a los apóstoles. A su vez, el Padre da también testimonio de que
    Cristo es el Hijo, por la atracción que produce en las almas, por las obras
    que da al Hijo para que las realice y sobre todo por la resurrección,
    testimonio decisivo del Padre en favor del Hijo. El Hijo da testimonio del
    Espíritu porque promete enviarlo como educador, consolador, santificador. Y el
    Espíritu viene y da testimonio del hijo porque le recuerda, le da a conocer,
    descubre la plenitud de sentido de sus palabras, lo insinua en las
    almas.\footnote{de Latourelle, Teología de la Revelación 410
      en\autocite[131]{prades2015testimonio}}}
  Esta actividad reveladora de la trinidad introduce al ser humano en la comunión
  trinitaria. Dios trino se comunica al ser humano actuando en su interior,
  atrayendo, inspirando; también se comunica externamente por las obras que
  realiza. Esta participación en la comunión divina viene bien expresada en la
  finalidad del testimonio apostólico: \citalitinterlin{Eso que hemos visto y oído
    os lo anunciamos, para que estéis en comunión con nosotros y nuestra comunión
    es con el Padre y con su Hijo Jesucristo.}\footnote{1Jn 1,3}

  Jesús es el fundamento, testigo fiel y veraz para todo tiempo y
  lugar.\autocite[Cf.][132]{prades2015testimonio} Creer su testimonio es acoger al
  absoluto en la historia, esta confianza la hace posible el Espíritu:
  \citalitlar{Cristo es, por tanto, el testigo absoluto, el que lleva en sí mismo
    la garantía de su testimonio. El hombre, sin embargo, no sería capaz de acoger
    por la fe este testimonio del absoluto, manifestado en la carne y el lenguaje
    de Jesús, sin una atracción interior (Jn 6,44), que es un don del Padre y un
    testimonio del Espíritu (1Jn 5,9--10).\autocite{latourelle2000testimonio}}
  Aquellos que creen en Cristo no sólo encuentran una respuesta a su busqueda de
  vida y sentido, sino que \citalitinterlin{de sus entrañas manarán ríos de agua
    viva}.\footnote{Jn 7,38} Y esto Jesús lo dice \citalitinterlin{refiriéndose al
    Espíritu que habían de recibir los que creyeran en él}.\footnote{Jn 7,39} Esta
  promesa del Espíritu acontece en Pentecostés y sin ese testimonio postpascual
  del Espíritu quedaría incompleta la comunicación de Dios en el misterio
  Pascual.\autocite[Cf.][135]{prades2015testimonio} El envío y la acción del
  Espíritu prometido completa la acción testimonial de Dios:
  \citalitlar{Al haber ``acompañado'' al Hijo en la tierra de una manera singular
    desde el momento de su unción en el Jordán, que dispone al Hijo ---concebido
    por obra del Espíritu Santo--- para la misión en la carne, el Espíritu Santo
    vueve al Padre portando en sí todo el misterio redentor del Hijo. De este
    modo, cuando el Resucitado lo envía a la Iglesia, el Espíritu vuelve como
    Testigo de la verdad completa, que incluye la perfecta glorificación de la
    carne del Hijo como plenitud de lo
    humano.\autocite[134s]{prades2015testimonio}}

  El Espíritu enviado por Cristo lleva a la verdad plena a los apóstoles:
  \citalitinterlin{cuando venga él, el Espíritu de la verdad, os guiará hasta la
    verdad plena. Pues no hablará por cuenta propia, sino que hablará de lo que
    oye y os comunicará lo que está por venir}.\footnote{Jn 16,13} Este testimonio
  del Espíritu completa tambíen el testimonio de los apóstoles:
  \citalitinterlin{Cuando venga el Paráclito, que os enviaré desde el Padre, el
    Espíritu de la verdad, que procede del Padre, él dará testimonio de mí; y
    también vosotros daréis testimonio, porque desde el principio estáis
    conmigo}.\footnote{Jn 15,26--27} Ellos han estado desde el principio con
  Cristo, así son testigos que pueden narrar lo que han visto y oído; su testimono
  queda perfeccionado por el Espíritu que les introduce en el misterio del Hijo
  encarnado y les permite interpretar y comprender la verdad del Hijo, y por éste,
  la del Padre.\autocite[Cf.][139]{prades2015testimonio}

  Los que han compartido con Jesús desde el principio son testigos del Evangelio,
  pero el Resucitado sigue eligiendo apóstoles y en virtud de la acción del
  Espíritu éstos son testigos del mismo misterio.\autocite[Cf.][576]{ninot2009tf}
  Así Matías no sólo es \citalitinterlin{uno de los que nos acompañaron todo el
    tiempo que convivió con nosotros el Señor Jesús}\footnote{Hch 1,21}, sino que
  es elegido por el Resucitado.\footnote{Cf.~Hch 1,24--26} Igualmente Pablo es
  constituido testigo por la llamada del Resucitado, asi puede decir
  \citalitinterlin{Yo mismo hermanos cuando vine a vosotros anunciaros el
    testimonio de Dios\ldots}\footnote{1\,Cor 2,1}. De este modo la transmisión
  viva del testimonio cristiano esta constituida por un momento fundacional en la
  convivencia con Jesús y un momento continuante como dos aspectos históricos
  inseparables.\autocite[Cf.][148]{prades2015testimonio} Este momento continuante
  esta compuesto por los que han sido testigos oculares, como por los que no:
  \citalitinterlin{unos y otrs son elegidos, llamados y enviados por Cristo, el
    Cristo histórico los primeros y el Cristo glorioso los
    segundos}.\autocite[148]{prades2015testimonio}

  Aquel que recibe este testimonio y cree en él encuentra la vida nueva. <<¿Qué
  dificultad hay en que me bautice?>>, decide aquel hombre que recibió el
  testimonio de Felipe y <<siguió su camino lleno de alegría>> después de haber
  encontrado a Dios. Considerar la revelación divina como acción testimonial de
  Dios conduce en definitiva a estimar la revelación misma como forma de amor y
  libertad de Dios que interpela el amor y libertad humano. En tanto que
  comunicación libre y amorosa, el testimonio de Dios atiende la naturaleza humana
  de su beneficiario; en tanto que don divino queda desvelado su origen y meta más
  allá de lo humano.\autocite[Cf.][152]{prades2015testimonio}
#+END_SRC

** El testimonio en el Magisterio
   :LOGBOOK:
   CLOCK: [2019-03-20 Wed 16:16]--[2019-03-20 Wed 16:41] =>  0:25
   CLOCK: [2019-03-20 Wed 15:46]--[2019-03-20 Wed 16:11] =>  0:25
   CLOCK: [2019-03-20 Wed 11:48]--[2019-03-20 Wed 12:13] =>  0:25
   CLOCK: [2019-03-20 Wed 11:15]--[2019-03-20 Wed 11:40] =>  0:25
   CLOCK: [2019-03-20 Wed 10:40]--[2019-03-20 Wed 11:05] =>  0:25
   CLOCK: [2019-03-20 Wed 10:05]--[2019-03-20 Wed 10:30] =>  0:25
   :END:

Decálogo sobre el testimonio AG 11 (572 tf ninot)
Evangelii Nuntiandi n21

#+BEGIN_SRC latex
  \section{Iglesia como signo sacramental el Testimonio en el Magisterio Reciente}
  Nuestro recorrido comenzó al inicio de este capítulo tomando como punto de
  partida a la Iglesia como signo visibile. La vida de la comunidad eclesial, sus
  costumbres y actitudes, son presencia histórica y realidad perceptible. La
  Iglesia puede ser reconocida hoy actuando según su costumbre de reunirse en
  torno a la Palabra de Dios para celebrarla y conocer la verdad para su vida. Lo
  que se vive hoy y se ha transmitido en la tradición eclesial lo hemos valorado
  como perpetuación de la actividad de Cristo y de los apóstoles y, por tanto,
  como proyección del testimonio divino. En este sentido hemos considerado la
  presencia de la Revelación divina en el corazón y anuncio de la Iglesia como
  triple testimonio usando la expresión de Latourelle: <<palabra vivida en el
  Espíritu>>. Esta reflexión ha querido servir para describir la naturaleza de la
  Revelación como experiencia familiar en la vida de la Iglesia. La noción de la
  categoría del testimonio que atraviesa la escritura ha servido para valorar la
  naturaleza de la Revelación según su estructura testimonial.

  Así como la categoría del testimonio ha servido para decir algo sobre la
  Revelación en la Escritura, ahora se pretende decir algo sobre lo que la
  categoría del testimonio puede aportar para comprender la identidad de la
  Iglesia y su misión en el mundo y cómo ésta forma parte del dinamismo de la
  Revelación divina.

  Con Latourelle se ha dicho que el testimonio es una de esas categorías que la
  escritura emplea como analogía para introducirnos al misterio divino. El
  Concilio nos regala otra analogía que va de la mano con la categoría del
  testimonio en la comprensión de la Iglesia y su misión:
  \citalitlar{la sociedad provista de sus órganos jerárquicos y el Cuerpo místico de
  Cristo, la asamblea visible y la comunidad espiritual, la Iglesia terrestre y la
  Iglesia enriquecida con los bienes celestiales, no deben ser consideradas como
  dos cosas distintas, sino que más bien forman una realidad compleja que está
  integrada de un elemento humano y otro divino. Por eso se la compara, por una
  notable analogía, al misterio del Verbo encarnado, pues así como la naturaleza
  asumida sirve al Verbo divino como de instrumento vivo de salvación unido
  indisolublemente a Él, de modo semejante la articulación social de la Iglesia
  sirve al Espíritu Santo\footnote{LG 8}}

  La visibilidad de la Iglesia está al servicio del Espíritu Santo de modo que su
  naturaleza humana sirve a la presencia divina como instrumento vivo de
  salvación. La presencia de la articulación social de la Iglesia actua de manera
  análoga a la presencia de Cristo. Según esto se puede decir que
  \citalitinterlin{la eclesiología se resuelve en la Cristología y por eso el
    ``lugar'' de la Iglesia en el acto de creer será ``análogo'' al de
    Cristo}.\autocite[566]{ninot2009tf} Esta relación con Cristo y el Espíritu
  otorgan a la Iglesia valor sacramental:
  \citalitlar{Porque Cristo, levantado sobre la tierra, atrajo hacia sí a todos
    (cf. Jn 12, 32 gr.); habiendo resucitado de entre los muertos (Rm 6, 9), envió
    sobre los discípulos a su Espíritu vivificador, y por El hizo a su Cuerpo, que
    es la Iglesia, sacramento universal de salvación; estando sentado a la derecha
    del Padre, actúa sin cesar en el mundo para conducir a los hombres a la
    Iglesia y, por medio de ella, unirlos a sí más estrechamente y para hacerlos
    partícipes de su vida gloriosa alimentándolos con su cuerpo y sangre. Así que
    la restauración prometida que esperamos, ya comenzó en Cristo, es impulsada
    con la misión del Espíritu Santo y por Él continúa en la Iglesia, en la cual
    por la fe somos instruidos también acerca del sentido de nuestra vida
    temporal, mientras que con la esperanza de los bienes futuros llevamos a cabo
    la obra que el Padre nos encomendó en el mundo y labramos nuestra salvación
    (cf. Flp 2, 12).\footnote{LG 48}}
  Esta Iglesia que es sacramento es mediación de acción salvadora de Dios;
  comunica los dones de la gracia y manifiesta el misterio de Dios:
  \citalitlar{Todo el bien que el Pueblo de Dios puede dar a la familia humana al
    tiempo de su peregrinación en la tierra, deriva del hecho de que la Iglesia es
    "sacramento universal de salvación", que manifiesta y al mismo tiempo realiza
    el misterio del amor de Dios al hombre.\footnote{GS 45}}

  La Iglesia en el mundo es así uno de los signos contenidos en la Revelación que
  ayudan a la razón que busca la comprensión del misterio. El signo sacramental
  que es la Iglesia permite atestiguar desde la fe el misterio de Dios que en ella
  se expresa del mismo modo que ocurre con la Eucaristía o la presencia de Cristo
  encarnado:
  \citalitlar{Podemos fijarnos, en cierto modo, en el horizonte sacramental de la
    Revelación y, en particular, en el signo eucarístico donde la unidad
    inseparable entre la realidad y su significado permite captar la profundidad
    del misterio. Cristo en la Eucaristía está verdaderamente presente y vivo, y
    actúa con su Espíritu, pero como acertadamente decía Santo Tomás, <<lo que no
    comprendes y no ves, lo atestigua una fe viva, fuera de todo el orden de la
    naturaleza. Lo que aparece es un signo: esconde en el misterio realidades
    sublimes>>. A este respecto escribe el filósofo Pascal: <<Como Jesucristo
    permaneció desconocido entre los hombres, del mismo modo su verdad permanece,
    entre las opiniones comunes, sin diferencia exterior. Así queda la Eucaristía
    entre el pan común>>.\footnote{FR 13}}
  El misterio sublime que aparece en un signo puede ser atestiguado por la fe
  viva. El asentimiento al signo sacramental por la fe supone el reconocimiento de
  que viene de Dios y por tanto es creer a quien es garante de su propia verdad.
  Este asentimiento implica a la persona por completo:
  \citalitlar{Desde la fe el hombre da su asentimiento a ese testimonio divino.
    Ello quiere decir que reconoce plena e integralmente la verdad de lo revelado,
    porque Dios mismo es su garante. Esta verdad, ofrecida al hombre y que él no
    puede exigir, se inserta en el horizonte de la comunicación interpersonal e
    impulsa a la razón a abrirse a la misma y a acoger su sentido profundo. Por
    esto el acto con el que uno confía en Dios siempre ha sido considerado por la
    Iglesia como un momento de elección fundamental, en la cual está implicada
    toda la persona. Inteligencia y voluntad desarrollan al máximo su naturaleza
    espiritual para permitir que el sujeto cumpla un acto en el cual la libertad
    personal se vive de modo pleno.\footnote{FR 13}}
  La acogida del misterio divino comunicado en el signo sacramental es así un acto
  de libertad plena que no sólo permite reconocer el misterio de Dios, sino que
  nos desvela nuestra vocación de comunión con Él, que es nuestro sentido más
  auténtico:
  \citalitlar{El conocimiento de fe, en definitiva, no anula el misterio; sólo lo
    hace más evidente y lo manifiesta como hecho esencial para la vida del hombre:
    Cristo, el Señor, <<en la misma revelación del misterio del Padre y de su
    amor, manifiesta plenamente el hombre al propio hombre y le descubre la
    grandeza de su vocación>>, que es participar en el misterio de la vida
    trinitaria de Dios.\footnote{FR 13}}

  La Iglesia es signo sacramental unido inseparablemente al misterio divino que
  comunica, de modo análogo a la unión del Verbo divino y la naturaleza asumida
  por Él. El conocimiento de la fe abre la razón humana a la verdad revelada como
  comunicación interpersonal de Dios realizada por medio de este signo sacramental
  que es la Iglesia. Este acto de confianza es movimiento de la libertad como
  asentimiento y elección de Dios que se revela y acogida de su llamada a
  participar de la comunión trinitaria. Aquí sacramento y testimonio son
  categorías que interactuan para describir el acceso al misterio divino que se
  comunica a través de signos. Esta Iglesia que es signo sacramental es signo
  creíble por el testimonio de la vida comprometida con el misterio de amor que
  significa: \citalitlar{La misión primera y fundamental que recibimos de los
    santos Misterios que celebramos es la de dar testimonio con nuestra vida. El
    asombro por el don que Dios nos ha hecho en Cristo infunde en nuestra vida un
    dinamismo nuevo, comprometiéndonos a ser testigos de su amor. Nos convertimos
    en testigos cuando, por nuestras acciones, palabras y modo de ser, aparece
    Otro y se comunica. Se puede decir que el testimonio es el medio con el que la
    verdad del amor de Dios llega al hombre en la historia, invitándolo a acoger
    libremente esta novedad radical. En el testimonio Dios, por así decir, se
    expone al riesgo de la libertad del hombre. Jesús mismo es el testigo fiel y
    veraz (cf. Ap 1,5; 3,14); vino para dar testimonio de la verdad (cf. Jn
    18,37). Con estas reflexiones deseo recordar un concepto muy querido por los
    primeros cristianos, pero que también nos afecta a nosotros, cristianos de
    hoy: el testimonio hasta el don de sí mismos, hasta el martirio, ha sido
    considerado siempre en la historia de la Iglesia como la cumbre del nuevo
    culto espiritual: <<Ofreced vuestros cuerpos>> (Rm 12,1). Se puede recordar,
    por ejemplo, el relato del martirio de san Policarpo de Esmirna, discípulo de
    san Juan: todo el acontecimiento dramático es descrito como una liturgia, más
    aún como si el mártir mismo se convirtiera en Eucaristía. Pensemos también en
    la conciencia eucarística que san Ignacio de Antioquía expresa ante su
    martirio: él se considera <<trigo de Dios>> y desea llegar a ser en el
    martirio <<pan puro de Cristo>>. El cristiano que ofrece su vida en el
    martirio entra en plena comunión con la Pascua de Jesucristo y así se
    convierte con Él en Eucaristía. Tampoco faltan hoy en la Iglesia mártires en
    los que se manifiesta de modo supremo el amor de Dios. Sin embargo, aun cuando
    no se requiera la prueba del martirio, sabemos que el culto agradable a Dios
    implica también interiormente esta disponibilidad, y se manifiesta en el
    testimonio alegre y convencido ante el mundo de una vida cristiana coherente
    allí donde el Señor nos llama a anunciarlo.\footnote{SCa 85}}
  El testimonio hasta el don de nosotros mismos se convierte en signo sacramental,
  el cristiano que ofrece su vida por completo como testigo entra en comunión con
  la Pascua y se convierte con Cristo en Eucaristía. La vida entregada, este signo
  sacramental, es el medio adecuado para comunicar la comunión con Dios:
  \citalitlar{En efecto, la fe necesita un ámbito en el que se pueda testimoniar y
    comunicar, un ámbito adecuado y proporcionado a lo que se comunica. Para
    transmitir un contenido meramente doctrinal, una idea, quizás sería suficiente
    un libro, o la reproducción de un mensaje oral. Pero lo que se comunica en la
    Iglesia, lo que se transmite en su Tradición viva, es la luz nueva que nace
    del encuentro con el Dios vivo, una luz que toca la persona en su centro, en
    el corazón, implicando su mente, su voluntad y su afectividad, abriéndola a
    relaciones vivas en la comunión con Dios y con los otros. Para transmitir esta
    riqueza hay un medio particular, que pone en juego a toda la persona, cuerpo,
    espíritu, interioridad y relaciones. Este medio son los sacramentos,
    celebrados en la liturgia de la Iglesia. En ellos se comunica una memoria
    encarnada, ligada a los tiempos y lugares de la vida, asociada a todos los
    sentidos; implican a la persona, como miembro de un sujeto vivo, de un tejido
    de relaciones comunitarias. Por eso, si bien, por una parte, los sacramentos
    son sacramentos de la fe, también se debe decir que la fe tiene una estructura
    sacramental. El despertar de la fe pasa por el despertar de un nuevo sentido
    sacramental de la vida del hombre y de la existencia cristiana, en el que lo
    visible y material está abierto al misterio de lo eterno. \footnote{LF 40}}
  Al celebrar los sacramentos con fe viva, la comunidad eclesial se deja implicar
  por completo por la luz del Dios vivo que se comunica y el memorial que se
  encarna. Despertar a la fe en los sacramentos es también despertar al sentido
  sacramental que tiene la propia vida cristiana. Así como en los sacramentos los
  signos visibles comunican la luz de Dios, también la propia existencia del
  cristiano puede arrojar esa luz.

  Este valor sacramental de la vida del cristiano y de la comunidad eclesial hace
  de su propia existencia un testimonio kerygmático:
  \citalitlar{La Buena Nueva debe ser proclamada en primer lugar, mediante el
    testimonio. Supongamos un cristiano o un grupo de cristianos que, dentro de la
    comunidad humana donde viven, manifiestan su capacidad de comprensión y de
    aceptación, su comunión de vida y de destino con los demás, su solidaridad en
    los esfuerzos de todos en cuanto existe de noble y bueno. Supongamos además
    que irradian de manera sencilla y espontánea su fe en los valores que van más
    allá de los valores corrientes, y su esperanza en algo que no se ve ni osarían
    soñar. A través de este testimonio sin palabras, estos cristianos hacen
    plantearse, a quienes contemplan su vida, interrogantes irresistibles: ¿Por
    qué son así? ¿Por qué viven de esa manera? ¿Qué es o quién es el que los
    inspira? ¿Por qué están con nosotros? Pues bien, este testimonio constituye ya
    de por sí una proclamación silenciosa, pero también muy clara y eficaz, de la
    Buena Nueva. Hay en ello un gesto inicial de evangelización. Son posiblemente
    las primeras preguntas que se plantearán muchos no cristianos, bien se trate
    de personas a las que Cristo no había sido nunca anunciado, de bautizados no
    practicantes, de gentes que viven en una sociedad cristiana pero según
    principios no cristianos, bien se trate de gentes que buscan, no sin
    sufrimiento, algo o a Alguien que ellos adivinan pero sin poder darle un
    nombre. Surgirán otros interrogantes, más profundos y más comprometedores,
    provocados por este testimonio que comporta presencia, participación,
    solidaridad y que es un elemento esencial, en general al primero absolutamente
    en la evangelización.\footnote{EN 21}}
  La acción testimonial de Dios que se manifiesta en Cristo y en los sacramentos
  instituidos por Él está analogamente presente en la vida comprometida del
  cirstiano. El testimonio humano es respuesta de fe de aquellos que han
  reconocido a Dios en los signos que le encarnan y que corresponden con palabras
  y obras que quieren significar la vida nueva que viene del Señor. En esta
  correspondencia se unden las raíces de la misión de proclamar la Buena Nueva.

  El testimonio es así acción propia de todo bautizado que ha quedado unido a
  Cristo y a la Iglesia.\autocite[Cf.][188]{prades2015testimonio} Toda la Iglesia
  tiene la misión de dar testimonio; los obispos ofrecen al mundo el rostro de la
  Iglesia con su trato y trabajo pastoral\footnote{GS 43}, los presbíteros,
  creciendo en el amor por el desempeño de su oficio, han de ser un vivo
  testimonio de Dios\footnote{LG 41}, los fieles han de dar testimonio de verdad
  como testigos de la resurrección\footnote{LG 28 y LG 38}, los religiosos deben
  ofrecer un testimonio sostenido por la integridad de la fe, por la caridad y el
  amor a la cruz y la esperanza de la gloria futura\footnote{PC 25}, los
  profesores han de dar testimonio tanto con su vida como con su
  doctrina\footnote{GE 8}, los misioneros han de ofrecer testimonio con una vida
  enteramente evangélica, con paciencia, longanimidad, suavidad, caridad sincera,
  y si es necesario hasta con la propia sangre.\footnote{AG 24}

  El signo que es la vida de los cristianos y, por tanto la Iglesia, esta llamado
  a purificarse y crecer. La contradicción entre la fe y la vida de los cristianos
  puede constituir un motivo de tropiezo, en lugar de dar a conocer la luz de
  Dios. El testimonio de la vida entregada, aún cuando ha sido estimado según su
  valor sacramental, es un signo imperfecto que debe ser madurado con una actitud
  vigilante:
  \citalitlar{Aunque la Iglesia, por la virtud del Espíritu Santo, se ha mantenido
    como esposa fiel de su Señor y nunca ha cesado de ser signo de salvación en el
    mundo, sabe, sin embargo, muy bien que no siempre, a lo largo de su prolongada
    historia, fueron todos sus miembros, clérigos o laicos, fieles al espíritu de
    Dios. Sabe también la Iglesia que aún hoy día es mucha la distancia que se da
    entre el mensaje que ella anuncia y la fragilidad humana de los mensajeros a
    quienes está confiado el Evangelio. Dejando a un lado el juicio de la historia
    sobre estas deficiencias, debemos, sin embargo, tener conciencia de ellas y
    combatirlas con máxima energía para que no dañen a la difusión del Evangelio.
    De igual manera comprende la Iglesia cuánto le queda aún por madurar, por su
    experiencia de siglos, en la relación que debe mantener con el mundo. Dirigida
    por el Espíritu Santo, la Iglesia, como madre, no cesa de ``exhortar a sus
    hijos a la purificación y a la renovación para que brille con mayor claridad
    la señal de Cristo en el rostro de la Iglesia''\footnote{GS 34}}
  La vida de la Iglesia está marcada por esa llamada a este enriquecimiento
  constante. Como afirma DV 8: \citalitinterlin{la Iglesia, en el decurso de los
    siglos, tiende constantemente a la plenitud de la verdad divina, hasta que en
    ella se cumplan las palabras de Dios.}

  La categoría del testimonio ha servido para acercarnos a algunos textos
  magisteriales y describir la vida de la Iglesia como signo sacramental. A modo
  de conclusión son luminosas las palabras de K. Wojtyła:
  \citalitlar{El significado del testimonio en la doctrina del Vaticano II es
    explícitamente analógico, puesto que el Concilio habla del testimonio de Dios
    y del hombre, que, de diversa manera, corresponde al divino, y a una respuesta
    multiforme a la revelación. En todo caso, sin embargo, la respuesta es
    testimonio y el testimonio, respuesta. \footnote{Para una discusión más amplia
      de la lectura de Wojtyła véase \cite[194--197]{prades2015testimonio}}}

  Este recorrido a través de algunos modos de emplear la categoría del testimonio
  en la Escritura y la doctrina magisterial ha servido para describir los
  dinamísmos de la Revelación como acción libre y amorosa del Padre encarnada en
  en la naturaleza humana asumida por el Verbo y sostenida por la acción interior
  del Espíritu. Esta acción de la libertad divina ha encontrado la correspondencia
  de la libertad humana que acoge la invitación al amor y se compromete por
  completo a la comunión con Dios. Este intercambio testimonial comunica el amor
  divino.


#+END_SRC


** El problema de la categoría del testimonio
#+BEGIN_SRC latex
  \section{La Categoría del Testimonio como problema}

  Hasta ahora se ha empleado la categoría del testimonio sin problematizarla. Es
  decir, hemos tratado el testimonio como <<cosa familiar y conocida>> empleada
  ordinariamente en nuestras conversaciones. Es aquí donde nos permitimos tratar
  al testimonio como algo que hay que esclarecer, algo sobre lo que se plantean
  preguntas, de modo que hay que traer a la mente una explicación adecuada. En
  palabras de Latourelle:
  \citalitlar{Si la revelación misma se apoya en la experiencia humana del
    testimonio para expresar una de las relaciones fundamentales que unen al
    hombre con Dios, la reflexión teológica se encuentra entonces autorizada a
    explorar los datos de esta
    experiencia.\autocite[1523]{latourelle2000testimonio}}
  Hasta el momento sólo hemos formulado una pregunta, que si ampliamos un poco
  queda: ``¿qué es conocer una verdad para la vida por el testimonio de la
  revelación divina?''. Esta formulación puede servir como punto de partida y, si
  tenemos en cuenta la reflexión filosófica en torno al testimonio, podemos
  expandirla más.

  Aún cuando el testimonio ocupa un lugar vital en nuestro contacto con el mundo,
  no siempre ha gozado del interés de la investigación filosófica. Más
  recientemente, sin embargo, su importancia ha sido mejor apreciada y así lo
  refleja la variedad literatura que puede encontrarse en la filosofía
  contemporanea.\footnote{Cf. Jennifer Lackey Despite the vital role that
    testimony occupies in our epistemic lives, traditional epistemological
    theories focused primarily on other sources, such as sense perception, memory,
    and reason, with relatively little attention devoted specifically to
    testimony. In recent years, however, the epistemic significance of testimony
    has been more fully appreciated, and the current literature has benefited from
    the publication of a considerable amount of interesting and innovative work in
    this area.}
  Esta época mas prolija en discusiones no es, sin embargo, el origen de algunas
  posturas propuestas en torno al testimonio, éste lo encontramos más bien en la
  época moderna. Recurriremos, por tanto, a algunas aportaciones y desafíos
  ofrecidos por la filosofía moderna y contemporánea para expandir nuestra
  anterior pregunta y formular las cuestiones principales que serviran luego para
  navegar en el pensamiento de Elizabeth Anscombe.

  \subsection{¿Cuál es el valor epistemológico del testimonio?}
  Corresponde a la epistemología la tarea de estudiar la naturaleza del conocer y
  su justificación. ¿Cuáles son los componentes del conocimiento? ¿sus fuentes o
  condiciones? ¿sus límites?\footnote{Cf. Oxford Epistemology, characterized
    broadly, is an account of knowledge. Within the discipline of philosophy,
    epistemology is the study of the nature of knowledge and justification: in
    particular, the study of (a) the defining components, (b) the substantive
    conditions or sources, and (c) the limits of knowledge and justification.} La
  pregunta sobre el valor epistemológico del testimonio consiste en juzgar el
  lugar que éste ocupa en una descripición del conocimiento; ¿qué se puede decir
  del testimonio como estrategia para adquirir la verdad y evitar el
  error?\footnote{Cf. Any standard or strategy worthy of the title ``epistemic''
    must have as its fundamental goal the acquisition of truth and the avoidance
    of error.}

  Podemos recurrir al análisis tradicional empleado para hablar del conocimiento
  proposicional y entenderlo como `creencia verdadera justificada'.\footnote{Ever
    since Plato's Theaetetus, epipstemologists have tried to identify the
    essential, defining components of propositional knowledge. These components
    will yield an analysis of propositional knowledge. An influential traditional
    view, inspired by Plato and Kant among others, is that propositional knowledge
    has three individually necessary and jointly sufficient components:
    justification, truth, and belief. On this view, propositional knowledge is, by
    definition, justified true belief. This tripartite definition has come to be
    called ``the standard analysis''.} Según esta composición tripartita la
  pregunta sobre el valor epistemológico del testimonio se puede plantear
  diciendo: dada una comunicación que cualifique como testimonio y que sea al caso
  que la creencia formada desde esta comunicación está basada enteramente en el
  testimonio recibido,\footnote{Even if an expression of thought qualifies as
    testimony and the resulting belief formed is entirely testimonially based for
    the hearer, however, there is the further question of how precisely such a
    belief successfully counts as justified belief or an instance of knowledge.}
  ¿cómo adquirimos efectivamente una creencia verdadera justificada sobre la base
  de lo que alguien nos ha dicho?\footnote{how we successfully acquire justified
    belief or knowledge on the basis of what other people tell us. This, rather
    than what testimony is, is often taken to be the issue of central import from
    an epistemological point of view.}, es decir, ¿cómo, precisamente, una
  creencia como esta puede ser contada satisfactoriamente como creencia
  justificada o una instancia de conocimiento? \footnote{how precisely such a
    belief successfully counts as justified belief or an instance of knowledge}

  Las respuestas a esta pregunta central sobre la epistemología del testimonio se
  han situado en dos posturas que se han denominado `reduccionista' y
  `no-reduccionista'.\footnote{Indeed, this is the question at the center of the
    epistemology of testimony, and the current philosophical literature contains
    two central options for answering it: non-reductionism and reductionism.} Las
  raices históricas de la primera postura se le suelen atribuir a Hume y de la
  segunda a Thomas Reid.

  De acuerdo a los no-reduccionistas el testimonio es simplemente una fuente de
  justificación como lo sería la percepción de los sentidos, la memoria o la
  inferencia. Según esto, siempre que no haya una justificación contraria
  suficientemente relevante, el que escucha tiene justificación verdadera para
  creer las proposiciones del testimonio del que habla.\footnote{According to
    non-reductionists ---whose historical roots are standardly traced back to
    Reid--- testimony is just as basic a source of justification (warrant,
    entitlement, knowledge, etc.) as sense perception, memory, inference, and the
    like. Accordingly, so long as there are no relevant defeaters, hearers can
    justifiedly accept the assertions of speakers merely on the basis of a
    speaker's testimony.}

  Hume, por su parte, \citalitinterlin{es uno de los pocos filósofos que ha
    ofrecido algo así como una descripción sostenida acerca del testimonio y si
    alguna perspectiva puede reclamar el título de `el punto de vista adoptado' es
    la suya}.\footnote{is one of the few philosophers who has offered anything
    like a sustained account of testimony and if any view has a claim to the title
    of `the received view' it is his testimony p 79} En la base de su valoración
  del testimonio está su estima de la relación de causa y efecto como fundamento
  de cualquier razonamiento conciernente a cuestiones de hecho.

  Distinto a las relaciones de ideas, la evidencia de la veracidad de una cuestión
  de hecho no se demuestra a priori, sino que ha de ser descubierta en la
  experiencia. Ahora bien, ¿cuál es la naturaleza de la evidencia de aquellas
  cuestiones de hecho que están más allá de la percepción de nuestros sentidos o
  de las impresiones de nuestra memoria?\footnote{Matters of fact, which are the
    second objects of human reason, are not ascertained in the same manner; nor is
    our evidence of their truth, however great, of a like nature with the
    foregoing (relations of ideas) [\ldots] The contrary of every matter of fact
    is still possible [\ldots] We should, in vain, therefore attempt to
    demonstrate its falsehood. Were it demonstratively false, it would imply a
    contradiction, and could never be distinctly conceived by the mind [\ldots]
    what is the nature of that evidence which assures us of any real existence and
    matter of fact, beyond the present testimony of our senses, or the records of
    our memory. enquiry ch IV part I} Nuestros razonamientos relacionados con
  algún hecho se componen de inferencias realizadas a partir del conocimiento que
  tenemos de que a una causa se sigue su efecto.\footnote{All our reasonings
    concerning fact are of the same nature; and here it is constantly supposed
    that there is a connection between the present fact and that which is inferred
    from it. Were there nothing to bind them together, the inference would be
    entirely precarious.} Este conocimiento de la relación causa y efecto, a su
  vez, no consiste en un razonamiento a priori, \citalitinterlin{sino que surge
    completamente de la experiencia, cuando descubrimos que cualesquiera objetos
    particulares están constantemente unidos entre sí}.\footnote{that the
    knowledge of this relation is not, in any instance, attained by reasonings a
    priori, but arises entirely from experience, when we find that any particular
    objects are constantly conjoined with each other. enquiry ch IV part I} Es así
  que \citalitinterlin{por medio de esta relación solamente, podemos ir más allá
    de nuestra memoria y sentidos}. \footnote{By means of that relation alone, we
    can go beyond the evidence of our memory and senses.}

  Esta misma línea de razonamiento es la que se sigue en la descripción acerca del
  testimonio y su valor: \citalitlar{there is no species of reasoning more common,
    more useful, and even necessary to human life, than that which is derived from
    the testimony of men, and the reports of eye witnesses and spectators. This
    species of reasoning, perhaps, one may deny to be founded on the relation of
    cause and effect. I shall not dispute about a word. It will be sufficient to
    observe, that our assurance in any argument of this kind, is derived from no
    other principle than our observation of the veracity of human testimony, and
    of the usual conformity of facts to the reports of witnesses. It being a
    general maxim, that no objects have any discoverable connection together, and
    that all the inferences which we can draw from one to another, are founded
    merely on our experience of their constant and regular conjunction; it is
    evident, that we ought not to make an exception to this maxim in favour of
    human testimony, whose connection with any event seems, in itself, as little
    necessary as any other. Were not the memory tenacious to a certain degree; had
    not men commonly an inclination to truth and a principle of probity; were they
    not sensible to shame, when detected in a falsehood; were not these, I say,
    discovered by experience to be qualities inherent in human nature, we should
    never repose the least confidence in human testimony. A man delirious, or
    noted for falsehood and villany, has no manner of authority with
    us.\footnote{enquiry ch X part I}} Así como nuestra habitual experiencia de la
  relación de causa y efecto nos permite hacer inferencias acerca de las
  cuestiones de hecho que están más allá de nuestros sentidos, la conformidad que
  usualmente experimentamos entre los hechos y el informe que un testigo nos da de
  ellos nos permite inferir su veracidad. Según el análasis ofrecido por
  C.\,A.\,J.~Coady, la teoría de Hume: \citalitlar{constitutes a reduction of
    testimony as a form of evidence or support to the status of a species (one
    might almost say, a mutation) of inductive inference. And, again, in so far as
    inductive inference is reduced by Hume to a species of observation and
    consequences attendant upon observations, then in a like fashion testimony
    meets the same fate.\footnote{testimony p. 79}}

  La valoración epistemológica del testimonio y la perspectiva ofrecida por Hume
  nos deja así con un primer desafío: \citalitlar{en la vida social cabe aceptar
    un conocimiento por testimonio a condición de que su grado de certeza se
    limite a la probabilidad, y a condición de que pueda ser siempre reconducido a
    una verificación por conocimiento
    directo}.\autocite[294]{prades2015testimonio} Estas consideraciones añaden
  algunos elementos a nuestro cuestionamiento original. Conocer una verdad para la
  vida desde el testimonio implica que pueda obtenerse una creencia verdadera
  justificada basada en lo que una persona ha comunicado. La visión de Hume es que
  la evidencia que puede ofrecer un testimonio para justificar una creencia no es
  mayor que la probabilidad y esta evidencia está basada en la inferencia que nos
  permite la habitual experiencia de que el testimonio comunicado y la verdad de
  los hechos suelen ir unidos. Más adelante veremos qué tiene que decir Anscombe
  ante este desafío. Todavía podemos plantear una segunda cuestión esta vez
  relacionada con la segunda parte de nuestra pregunta original.

  \subsection{¿Tiene fuerza un testimonio histórico del absoluto?}
  El contexto de la reflexión de Hume sobre el testimonio es precisamente el de la
  creencia en los milagros. La preocupación de Hume es que el `hombre sabio' pueda
  verificar sus creencias de modo que no sea víctima de `engaños supersticiosos'.
  Para esto, estima, que ha encontrado un argumento que servirá para distinguir
  superstición de verdad.\footnote{I flatter myself, that I have discovered an
    argument of a like nature, which, if just, will, with the wise and learned, be
    an everlasting check to all kinds of superstitious delusion, and consequently
    will be useful as long as the world endures.} Dice: \citalitinterlin{in our
    reasonings concerning matter of fact, there are all imaginable degrees of
    assurance, from the highest certainty to the lowest species of moral evidence.
    A wise man, therefore, proportions his belief to the evidence}. Entonces
  sugiere un criterio que permite ajustar las creencias a la evidencia:
  \citalitlar{“That no testimony is sufficient to establish a miracle, unless the
    testimony be of such a kind, that its falsehood would be more miraculous than
    the fact which it endeavours to establish; and, even in that case, there is a
    mutual destruction of arguments; and the superior only gives us an assurance
    suitable to that degree of force which remains after deducting the inferior.”}
  Esto tiene como consecuencia que lo razonable sea abandonar la razonabilidad de
  las verdades cristianas, comprendiendo que solo pueden ser contempladas desde la
  fe. Empleando su criterio ofrece una valoración de la revelación de la escritura
  como sigue:
  \citalitlar{I am the better pleased with the method of reasoning here delivered,
    as I think it may serve to confound those dangerous friends, or disguised
    enemies to the Christian religion, who have undertaken to defend it by the
    principles of human reason. Our most holy religion is founded on faith, not on
    reason; and it is a sure method of exposing it, to put it to such a trial as
    it is by no means fitted to endure. To make this more evident, let us examine
    those miracles related in Scripture; and, not to lose ourselves in too wide a
    field, let us confine ourselves to such as we find in the Pentateuch, which we
    shall examine according to the principles of these pretended Christians, not
    as the word or testimony of God himself, but as the production of a mere human
    writer and historian. Here then we are first to consider a book, presented to
    us by a barbarous and ignorant people, written in an age when they were still
    more barbarous, and in all probability long after the facts which it relates,
    corroborated by no concurring testimony, and resembling those fabulous
    accounts which every nation gives of its origin. Upon reading this book, we
    find it full of prodigies and miracles. It gives an account of a state of the
    world and of human nature entirely different from the present: of our fall
    from that state; of the age of man extended to near a thousand years; of the
    destruction of the world by a deluge; of the arbitrary choice of one people,
    as the favourites of heaven, and that people the countrymen of the author; of
    their deliverance from
    bondage by prodigies the most astonishing imaginable.\\
    I desire any one to lay his hand upon his heart, and, after a serious
    consideration, declare, whether he thinks that the falsehood of such a book,
    supported by such a testimony, would be more extraordinary and miraculous than
    all the miracles it relates; which is, however, necessary to make it be
    received according to the measures of probability above established.}
  ¿Se puede afirmar que sería más ``milagrosa'' la falsedad de los milagros que
  atestigua la escritura? La posibilidad de recibir este testimonio como evidencia
  de alguna verdad descansaría sobre esta condición y una persona razonable
  debería medir la probabilidad de veracidad de estos relatos teniendo en cuenta
  que el estado de las cosas que describe es distinto al que experimentamos en el
  presente.

  En una línea similar de pensamiento encontramos las reflexiones de
  G.\,E.~Lessing. Dos cuestiones expresadas en ``On the proof of the spirit and
  power'' merecen ser destacadas:
  \citalitlar{The problem is that reports of fulfilled prophecies are not
    fullfiled prophecies; that reports of miracles are not miracles. These, the
    prophecies fulfilled before my eyes, the miracles that occur before my eyes,
    are immediate in their effect. But those---the reports of fulfilled prophecies
    and miracles, have to work through a medium which takes away all their force}
  Lo que debería tener la fuerza para justificar la credibilidad queda debilitado
  por su medio de transmisión, entonces \citalitinterlin{the problem is that this
    proof of the spirit and of power no longer has any spirit or power, but has
    sunk to the level of human testimonies of spirit and power}. Tal como lo
  plantea Lessing y teniendo en cuenta el criterio propuesto por Hume, el
  testimonio, en tanto que dinamismo humano, no tiene fuerza suficiente para
  justificar razonablemente creencias sobre Dios como verdadero conocimiento.

  Esta objeción nos lleva a la siguiente:
  \citalitlar{the reports which we have of these prophecies and miracles are as
    reliable as historical truths can ever be [\ldots] But if they are as reliable
    as this, why are they treated as if they were infinitely more reliable?
    [\ldots] If no historical truth can be demonstrated, then nothing can be
    demonstrated by means of historical truths. That is: \emph{accidental truths
      of history can never become proof of necessary truths of reason.}}
  El punto que Lessing señala es infranqueable para su propio intento de
  comprometerse con la verdad que la creencia cristiana pretende comunicar. La
  singularidad de la persona y obra de Jesús como manifestación de la realidad de
  Dios pierde para él toda su fuerza, puesto que no puede estimar estas verdades
  históricas como fundamento para una verdad necesaria como lo es la verdad de
  Dios.

  Esto nos deja con una segunda problemática: \citalitinterlin{no se puede tener
    conocimiento directo de milagros y profecias [\ldots] no se puede aceptar una
    comunicación divina que no sea inmediatamente dirigida al
    individuo}\autocite[294]{prades2015testimonio}. Este desafío viene a poner en
  cuestión que un hecho histórico de la vida personal o colectiva pueda ser
  estimado como testimonio del absoluto. La revelación de Dios por medio de
  testigos no es un fenómeno que tenga justificación razonable para su veracidad,
  y por tanto sólo puede ser acogida por una fe desconectada de la razón.

  \subsection{¿El lenguaje religioso es capaz de transmitir alguna verdad?}

  Ciruclo de viena, falsabilidad como cuarto atributo de el conocimiento
  proposicional. cita de analogía teológica.

#+END_SRC
*** TODO notas
tres objeciones (Prades 294) no se puede tener conocimiento directo de milagros
o profecías

en la vida social cabe aceptar un conocimiento por testimonio a condición de que
su grado de certeza se limite a la probabilidad

no se puede aceptar una comunicación divina que no sea inmediatamente dirigida
al individuo



Hasta el momento sólo nos hemos
planteado una pregunta que ahora podemos ampliar: ¿qué es conocer una
verdad para la vida por el testimonio de la revelación divina?


Qué otros cuestionamientos se pueden formular relacionados con este fenómeno?


Es posible agrupar algunos desafíos y aportaciones de la filosofía moderna y
contemporánea en varías preguntas principales. Éstas serán útiles a la hora de
indagar en el pensamiento de Elizabeth Anscombe.


Cuál es el valor epistemologico del testimonio?


how we successfully acquire justified belief or knowledge on the basis of what
other people tell us. This, rather than what testimony is, is often taken to be
the issue of central import from an epistemological point of view.




Because of this, those who are interested in the epistemic status of testimonial
beliefs often embrace a very broad notion of what it is to testify, one that
properly leaves the distinction between reliable and unreliable (or otherwise
epistemically good and bad) testimony for epistemology to delineate.

An adequate account of testimony, therefore, should recognize the distinction
between entirely non-informational expressions of thought and testimony.
Moreover, let us use the general term act of communication to include both
verbal and written assertions as well as communicative physical gestures, such
as nods, points, and so on. Given this, a rough characterization of testimony
may be expressed in something like the following way: T: S testifies that p by
making an act of communication a if and only if (in part) in virtue of a's
communicable content, (1) S reasonably intends to convey the information that p,
or4 (2) a is reasonably taken as conveying the information thatp.5

However, even if a speaker's assertion is properly connected with the conveying
of information, not everything we learn from the testimony of others qualifies
as testimonially based knowledge.

Even if an expression of thought qualifies as testimony and the resulting belief
formed is entirely testimonially based for the hearer, however, there is the
further question of how precisely such a belief successfully counts as justified
belief or an instance of knowledge. Indeed, this is the question at the center
of the epistemology ology of testimony, and the current philosophical literature
contains two central options for answering it: non-reductionism and
reductionism.


According to non-reductionists-whose historical roots are standardly traced back
to Reid-testimony is just as basic a source of justification (warrant,
entitlement, knowledge, etc.) as sense perception, memory, inference, and the
like. Accordingly, so long as there are no relevant defeaters, hearers can
justifiedly accept the assertions of speakers merely on the basis of a speaker's
testimony.10


In contrast to non-reductionism, reductionists-whose historical roots are typically
traced back to Hume-maintain that in order to justifiedly accept the testimony of
speakers, more is needed than the mere absence of undefeated defeaters. In particular,
proponents of reductionism argue that hearers must have sufficiently good positive
reasons for accepting a given report, reasons that are not themselves ineliminably
based on the testimony of others. Typically, these reasons are the result of induction:
for instance, we observe a general conformity between facts and reports and, with the
aid of memory and reason, we inductively infer that certain speakers, contexts, or
types of


reports are reliable sources of information. In this way, the justification of
testimony is reduced to the justification we have for sense perception, memory,
and inductive 16


Puede haber un hecho histórico que signifique una realidad absoluta?


Lessing es lo mismo relatos de milagros etc...

I flatter myself, that I have discovered an argument of a like nature, which, if just,
will, with the wise and learned, be an everlasting check to all kinds of superstitious
delusion, and consequently, will be useful as long as the world endures. For so long, I
presume, will the accounts of miracles and prodigies be found in all history, sacred
and profane.


Cita de Lackey
our dependence....


en la filosofía moder


cómo suena una descripción del conocer que tenga en cuenta el testimonio?


hume diría:


It may, therefore, be a subject worthy of curiosity, to enquire what is the nature of
that evidence which assures us of any real existence and matter of fact, beyond the
present testimony of our senses, or the records of our memory. This part of philosophy,
it is observable, has been little cultivated, either by the ancients or moderns ; and
therefore our doubts and errors, in the prosecution of so important an enquiry, may be
the more excusable ; while we march through such difficult paths without any guide or
direction. They may even prove useful, by exciting curiosity, and destroying that
implicit faith and security, which is the bane of all reasoning and free enquiry. The
dis covery of defects in the common philosophy, if any such there be, will not, I
presume, be a discourage ment, but rather an incitement, as is usual, to attempt
something more full and satisfactory than has yet been proposed to the public. All
reasonings concerning matter of fact seem to be founded on the relation of Cause and
Effect


We learn the events of former ages from history; but then we must peruse the vol umes
in which this instruction is contained, and thence carry up our inferences from one
testimony to another, till we arrive at the eyewitnesses and spectators of these
distant events. In a word, if we proceed not upon some fact, present to the memory or
senses, our reasonings would be merely hypothetical ; and how ever the particular links
might be connected with each other, the whole chain of inferences would have noth ing
to support it, nor could we ever, by its means, ar rive at the knowledge of any real
existence. If I ask why you believe any particular matter of fact, which you relate,
you must tell me some reason ; and this reason will be some other fact, connected with
it. But as you cannot proceed after this manner, in infini tum, you must at last
terminate in some fact, which is present to your memory or senses ; or must allow that
your belief is entirely without foundation.


All belief of matter of fact or real existence is derived merely from some object,
present to the memory or senses, and a customary conjunction between that and some
other object. Or in other words ; having found in many instances, that any two kinds of
objects— flame and heat, snow and cold—have always been con joined together ; if flame
or snow be presented anew to the senses, the mind is carried by custom to expect heat
or cold, and to believe that such a quality does exist, and will discover itself upon a
nearer approach.


The sceptic, therefore, had better keep within his proper sphere, and display those
philosophical objec tions, which arise from more profound researches. Here he seems to
have ample matter of triumph; while he justly insists, that all our evidence for any
matter of fact, which lies beyond the testimony of sense or memory, is derived entirely
from the relation of cause and effect ; that we have no other idea of this relation
than that of two objects, which have been frequently conjoined together ; that we have
no argu ment to convince us, that objects, which have, in our experience, been
frequently conjoined, will likewise, in other instances, be conjoined in the same
manner ; and that nothing leads us to this inference but custom or a certain instinct
of our nature ; which it is indeed difficult to resist, but which, like other
instincts, may be fallacious and deceitfuh While the sceptic insists upon these topics,
he shows his force, or rather, in deed, his own and our weakness ; and seems, for the
time at least, to destroy all assurance and conviction. These arguments might be
displayed at greater length, if any durable good, or benefit to society could ever be
expected to result from them.


Hume
anota un par de cosas
no se ha estudiado mucho
no se puede ser tan escéptico q no se valore
su valor no puede ser exagerado, la confianza q merece descansa en la experiencia q
tenemos de inferir efectos de causas

todo conocimiento descansará al final en un contacto con la experiencia o la memoria

la filosofía contemporánea aporta otras ideas,
lackey:

y qué pasa cuando se trata de un testimonio sobre algún hecho extraordinario, como un
milagro?


-----

An account of knowledge
which takes testimony into account, how does it look?

study of nature of knowledge and justification

Si se hace un estudio de la naturaleza del conocer y su justificación
y entonces se hace una descripición del conocimiento

Si entendemos la epistemología como una descripción del conocer

¿Qué papel juega el testimonio

Una descripción del conocimiento que tenga en cuenta el testimonio cómo
quedaría?



Epistemology, characterized broadly, is an account of knowledge. Within the
discipline of philosophy, epistemology is the study of the nature of knowledge
and justification: in particular, the study of (a) the defining components, (b)
the substantive conditions or sources, and (c) the limits of knowledge and
justification. Categories (a)--(c) have prompted traditional philosophical
controversy over the analysis of knowledge and justification, the sources of
knowledge and justification (in the case, for instance of rationalism vs
empiricism), and the status of skepticism about knowledge and justification.

Epistemologists have distinguished some species of knowledge, including:
propositional knowledge (that something is so), nonpropositional knowledge of
something (for instance, knowledge by acquaintance, or by direct awareness),
empirical (a posteriori) propositional knowledge, nonempirical (a priori)
propositional knowledge, and knowledge how to do something.

Ever since Plato's Theaetetus, epipstemologists have tried to identify the
essential, defining components of propositional knowledge. These components will
yield an analysis of propositional knowledge. An influential traditional view,
inspired by Plato and Kant among others, is that propositional knowledge has
three individually necessary and jointly sufficient components: justification,
truth, and belief. On this view, propositional knowledge is, by definition,
justified true belief. This tripartite definition has come to be called ``the
standard analysis''.

Knowledge is not just true belief. Knowledge requires that the satisfaction of
its belief condition be ``appropriately related'' to the satisfaction of its
truth condition. This is one broad way of understanding the justification
condition of the standard analysis. Controversy arises over the meaning of
``justification'' as well as over the substantive conditions for a belief's
being justified in a way appropriate to knowledge.

Any standard or strategy worthy of the title ``epistemic'' must have as its
fundamental goal the acquisition of truth and the avoidance of error. This
follows from the fact that genuine knowledge has truth as an essential condition
and excludes error. Of course, contemporary epistemology offers numerous
strategies for acquiring truth and avoiding erros, including contextualist,
coherentist, foundationalist, internalist, and externalist strategies.

Ideally, we would be able to say convingcingly that a particular strategy is
more effective at acquiring truth and avoiding error than all the others, and
then be done with the provlem o f final epistemological authority. Whatever
strategy has maximal effectiveness in getting truth and blocking error would
then have final epistemological authority for us. Unfortunately for us, the
problem resists such quick resolution.

Skeptics can help us appreciate the problem we face. Thay raise general
questions about the reliability of our cognitive sources; that is, they ask
about our cognitive sources altogether, as a whole. In doing so, they wonder
what convincing reason we have to regard those sources as reliable for aquiring
truth and avoiding error.

Our offering any kind of support for the reliability of our cognitive source
will depend on our use of such cognitive sources as perception, introspection,
belief, memory, testimony, intuition, and common sense. Since all such sources
are under question by skeptics, with regard to reliability, our use of them
cannot deliver the kind of evidence of reliability sought by skeptics.

Unfortunately, we cannot assume a position independent of our own cognitive
sources to deliver a test of their reliability of the sort demanded by skeptics.
This is the human cognitive predicament, and no one has shown how we can escape
it.



--------

Hume: Treatise
SECTION IV. Of the component parts of our reasonings concerning cause and
effect.

Tho’ the mind in its reasonings from causes or effects carries its view
beyond those objects, which it sees or remembers, it must never lose sight of
them entirely, nor reason merely upon its own ideas, without some mixture of
impressions, or at least of ideas of the memory, which are equivalent to
impressions.


When we infer effects from causes, we must establish the existence
of these causes; which we have only two ways of doing, either by an immediate
perception of our memory or senses, or by an inference from other causes; which
causes again we must ascertain in the same manner, either by a present
impression, or by an inference from their causes, and so on, till we arrive at
some object, which we see or remember. ’Tis impossible for us to carry on our
inferences in infinitum; and the only thing, that can stop them, is an
impression of the memory or senses, beyond which there is no room for doubt or
enquiry.



Enquiries

37. But here it may be proper to remark, that though our conclusions from
experience carry us beyond our memory and senses, and assure us of matters of
fact which happened in the most distant places and most remote ages, yet some
fact must always be present to the senses or memory, from which we may first
proceed in drawing these conclusions. A man, who should find in a desert country
the remains of pompous buildings, would conclude that the country had, in
ancient times, been cultivated by civilized inhabitants; but did nothing of this
nature occur to him, he could never form such an inference. We learn the events
of former ages from history; but then we must peruse the volumes in which this
instruction is contained, and thence carry up our inferences from one testimony
to another, till we arrive at the eyewitnesses and spectators of these distant
events. In a word, if we proceed not upon some fact, present to the memory or
senses, our reasonings would be merely hypothetical; and however the particular
links might be connected with each other, the whole chain of inferences would
have nothing to support it, nor could we ever, by its means, arrive at the
knowledge of any real existence. If I ask why you believe any particular matter
of fact, which you relate, you must tell me some reason; and this reason will be
some other fact, connected with it. But as you cannot proceed after this manner,
in infinitum, you must at last terminate in some fact, which is present to your
memory or senses; or must allow that your belief is entirely without foundation.



38. What, then, is the conclusion of the whole matter? A simple one; though, it
must be confessed, pretty remote from the common theories of philosophy. All
belief of matter of fact or real existence is derived merely from some object,
present to the memory or senses, and a customary conjunction between that and
some other object. Or in other words; having found, in many instances, that any
two kinds of objectsflame and heat, snow and cold- have always been conjoined
together; if flame or snow be presented anew to the senses, the mind is carried
by custom to expect heat or cold, and to believe that such a quality does exist,
and will discover itself upon a nearer approach. This belief is the necessary
result of placing the mind in such circumstances. It is an operation of the
soul, when we are so situated, as unavoidable as to feel the passion of love,
when we receive benefits; or hatred, when we meet with injuries. All these
operations are a species of natural instincts, which no reasoning or process of
the thought and understanding is able either to produce or to prevent. At this
point, it would be very allowable for us to stop our philosophical researches.
In most questions we can never make a single step further; and in all questions
we must terminate here at last, after our most restless and curious enquiries.
But still our curiosity will be pardonable, perhaps commendable, if it carry us
on to still farther researches, and make us examine more accurately the nature
of this belief, and of the customary conjunction, whence it is derived. By this
means we may meet with some explications and analogies that will give
satisfaction; at least to such as love the abstract sciences, and can be
entertained with speculations, which, however accurate, may still retain a
degree of doubt and uncertainty. As to readers of a different taste; the
remaining part of this section is not calculated for them, and the following
enquiries may well be understood, though it be neglected.



86. There is, in Dr. Tillotson’s writings, an argument against the real
presence, which is as concise, and elegant, and strong as any argument can
possibly be supposed against a doctrine, so little worthy of a serious 76/David
Hume refutation. It is acknowledged on all hands, says that learned prelate,
that the authority, either of the scripture or of tradition, is founded merely
in the testimony of the apostles, who were eye-witnesses to those miracles of
our Saviour, by which he proved his divine mission. Our evidence, then, for the
truth of the Christian religion is less than the evidence for the truth of our
senses; because, even in the first authors of our religion, it was no greater;
and it is evident it must diminish in passing from them to their disciples; nor
can any one rest such confidence in their testimony, as in the immediate object
of his senses. But a weaker evidence can never destroy a stronger; and
therefore, were the doctrine of the real presence ever so clearly revealed in
scripture, it were directly contrary to the rules of just reasoning to give our
assent to it. It contradicts sense, though both the scripture and tradition, on
which it is supposed to be built, carry not such evidence with them as sense;
when they are considered merely as external evidences, and are not brought home
to every one’s breast, by the immediate operation of the Holy Spirit. Nothing is
so convenient as a decisive argument of this kind, which must at least silence
the most arrogant bigotry and superstition, and free us from their impertinent
solicitations. I flatter myself, that I have discovered an argument of a like
nature, which, if just, will, with the wise and learned, be an everlasting check
to all kinds of superstitious delusion, and consequently, will be useful as long
as the world endures. For so long, I presume, will the accounts of miracles and
prodigies be found in all history, sacred and profane.


89. This contrariety of evidence, in the present case, may be derived from
several different causes; from the opposition of contrary testimony; from the
character or number of the witnesses; from the manner of their delivering their
testimony; or from the union of all these circumstances. We entertain a
suspicion concerning any matter of fact, when the witnesses contradict each
other; when they are but few, or of a doubtful character; when they have an
interest in what they affirm; when they deliver their testimony with hesitation,
or on the contrary, with too violent asseverations. There are many other
particulars of the same kind, which may diminish or destroy the force of any
argument, derived from human testimony. Suppose, for instance, that the fact,
which the testimony endeavours to establish, partakes of the extraordinary and
the marvellous; in that case, the evidence, resulting from the testimony, admits
of a diminution, greater or less, in proportion as the fact is more or less
unusual. The reason why we place any credit in witnesses and historians, is not
derived from any connexion, which we perceive a priori, between testimony and
reality, but because we are accustomed to find a conformity between them. But
when the fact attested is such a one as has seldom fallen under our observation,
here is a contest of two opposite experiences; of which the one destroys the
other, as far as its force goes, and the superior can only operate on the mind
by the force, which remains. Enquiry Concerning Human Understanding/79 The very
same principle of experience, which gives us a certain degree of assurance in
the testimony of witnesses, gives us also, in this case, another degree of
assurance against the fact, which they endeavour to establish; from which
contradiction there necessarily arises a counterpoize, and mutual destruction of
belief and authority. I should not believe such a story were it told me by Cato,
was a proverbial saying in Rome, even during the lifetime of that philosophical
patriot.20 The incredibility of a fact, it was allowed, might invalidate so
great an authority. The Indian prince, who refused to believe the first
relations concerning the effects of frost, reasoned justly; and it naturally
required very strong testimony to engage his assent to facts, that arose from a
state of nature, with which he was unacquainted, and which bore so little
analogy to those events, of which he had had constant and uniform experience.
Though they were not contrary to his experience, they were not conformable to
it.21




*** de la pres
\subsection{Wittgenstein y la filosofía analítica}

La tesina está centrada en el pensamiento de Elizabeth Anscombe, sin embargo, su
relación con Wittgenstein y la filosofía analítica requiere que esta
investigación tenga en cuenta algunas consideraciones básicas tanto del Profesor
como de la escuela. Este será el contexto filosófico de la investigación.

Para el concepto de filosofía analítica nos adscribimos por el momento a la
definición que ofrece Conesa:

\emph{ ``Por filosofía analítica entiendo aquel enfoque de los problemas
  filosóficos que pone un énfasis en el análisis lógico y conceptual como método
  privilegiado \mbox{---aunque} no \mbox{exclusivo---} para resolver estos
  problemas''}\footcite[16]{cyc}

La filosofía analítica nos ofrece un ámbito adecuado para el estudio del
testimonio, como afirma el mismo Conesa:

\emph{ ``En el ámbito de la filosofía analítica ---y especialmente por la
  influencia de Thomas Reid y Ludwig Wittgenstein--- asistimos a una
  revalorización del testimonio como forma de saber. Formulado en su forma más
  simple, se viene a decir que <<si alguien sabe que `p' y dice que `p',
  entonces quien lo escucha también sabe que
  `p'>>.''}\footcite[487]{feylogicaconesa}

Esta revalorización del testimonio en la filosofía analítica explica el interés
de realizar esta investigación dentro de esta escuela.

Las aportaciones de Wittgenstein en el campo de la filosofía analítica con el
Tractatus y más tarde con las Investigaciones Filosóficas son fundamentales. Su
influencia en el pensamiento de Anscombe es importante, así afirma Teichmann:

\emph{ ``Elizabeth Anscombe's name will be known to many as that of the English
  translator of a good number of Wittgenstein's Writings, in particular of the
  summation of his later philosophy, the Philosophical
  Investigations.[\ldots]And it is probably the influence of Wittgenstein's
  later philosophy that most readers of Anscombe will detect, rather than of his
  early philosophy. But her most sustained direct discussion of Wittgenstein is
  of course to be found in An Introduction to Wittgenstein's Tractatus; and it
  is interesting how themes from the Tractatus crop up in various guises in her
  articles, troughout her career.''}\footcite[191]{teichmann}

Aunque la relación entre Anscombe y Wittgenstein era muy estrecha, sus
pensamientos y actitudes eran distintos en diversos temas. Una cuestión en la
que ambos filósofos difieren y que será interesante para nuestro estudio es el
tema de la razonabilidad de la fe. Al recorrer la biografía de Anscombe y su
relación con Wittgenstein abordaré esta cuestión como punto de partida en el
estudio de Anscombe. Tambíen nos servira de marco el pensamiento de Wittgenstein
al tratar el tema del misterio y el sinsentido al final del recorrido por el
pensamiento de Elizabeth.

\subsection{G. E. M. Anscombe}

Francisco Conesa ubica a Anscombe dentro de ``aquellos autores que entienden la
fe primordialmente como un saber por testimonio''\footcite[84]{cyc}, esto la
sitúa en el centro de nuestra investigación.

Anscombe se convirtió a la fe católica en su juventud temprana y esta fe juega
un papel importantísimo en su vida, pensamiento y filosofía. Este dato es
llamativo cuando se considera su estrecha relación con Wittgenstein y la
filosofía analítica, ella misma, sin embargo explica:

\emph{ ``Analytical philosophy is more characterized by styles of argument and
  investigation than by doctrinal content. It is thus possible for people of
  widely different beliefs to be practitioners of this sort of philosophy. It
  ought not to surprise anyone that a seriously beleiving Catholic Christian
  should also be an analytical philosopher.''}\footcite[66]{opinionsanscombe}

Una escena de su vida puede resumir el interés por su pensamiento en este
estudio. Su hija, Mary Geach, nos narra:

\emph{ ``She told me how one day ---I think it was as an undergraduate--- she
  had come across a passage in Russell to the effect that an argument from the
  facts about the world to the existence of God could not be valid, as one could
  not deduce a necessary conclusion from a contingent premiss. She had not at
  the time been able to see what was wrong with the notion that necessities can
  only be deduced from necessities, but she had known that to deny the
  possibility of moving by reason from the facts about the world to a knowledge
  of existence of God was to deny a doctrine defined as of faith by an
  ecumenical council. She went then to church and made an act of faith [\ldots].
  She realized later that of course one can derive necessary conclusions from
  contingent premises. If she had relied on her own understanding, she would
  have lost her faith for a falsehood.''}

La actitud de Anscombe hacia la Iglesia y el misterio de la Revelación tanto
como su lugar dentro de la filosofía analítica son muy relevantes para el tipo
de reflexión teológica que quisiéramos desarrollar. Más aún son relevantes para
una reflexión sobre el testimonio en nuestro contexto contemporáneo.

\subsection{Perspectiva Teológico-Fundamental}

En el primer punto resaltaba la relación entre testimonio y Revelación, en el
examen de esta relación anticipaba ya la perspectiva teológico-fundamental del
trabajo. A esto quisiera añadir algunas consideraciones más.

La reflexión ``La Identidad de la Teología Fundamental'' de Salvador Pié-Ninot
nos da una buena pauta sobre la misión de la Teología Fundamental y, en
consecuencia, sobre la perspectiva que ha de tener esta investigación.

Al exponer la nueva imagen de la teología fundamental que se va desarrollando en
la etapa entre 1980 y 1998 observa que \emph{``esta nueva imagen se puede
  tipificar en torno a dos grandes modelos con sus aspectos decisivos: el
  epistemológico, que proviene de la concepción subyacente de la credibilidad, y
  el sistemático, que manifiesta la estructuración y contenido de la Teología
  Fundamental en esta etapa''}\footcite[29]{ninotTF}.

Sobre la epistemología comenta:

\emph{ ``La renovación de la TF va muy ligada a las componentes epistemológicas
  ``humanas'' del acto de fe: en definitiva la función de la credibilidad y la
  de los signos de ella.''}\footcite[31]{ninotTF}

En cuanto al modelo sistemático (monstratio religiosa, christiana y catholica)
al abordar la monstratio catholica aporta su propia reflexión:

\emph{ ``el tratado sobre la Iglesia, ni es sólo la tercera monstratio teológico
  fundamental, ni es sólo el máximo signo de revelación como
  Cristo-en-la-Iglesia, sino que además es el marco englobante y significativo
  de toda la Teología Fundamental. Y esto a partir de la categoría testimonio en
  su doble función: la fundacional-hermenéutica `ad-intra' y la
  apologética-misionera `ad-extra'.''}

Añade que esta categoría conlleva una mutua circularidad entre la dimensión
externa del testimonio eclesial, la dimensión interiorizada que es el testimonio
creyente vivido y la dimensión interior e interiorizada que es el testimonio
constante del Espíritu. De esta circularidad emerge la función del testimonio
eclesial como camino de credibilidad que es invitación externa e interna a la
vez. \footnote{\cite[40]{ninotTF}}

Al llegar a la propuesta para la teología fundamental que se encuentra en la
Fides et Ratio distingue tres ejes importantes planteados para esta disciplina
en el n. 67\footcite[49]{ninotTF}:
1. Disciplina que da razón de la fe (cf. 1 Pe 3, 15).\\
2. Justifica y explicita la relación entre la fe y la reflexión filosófica.\\
3. Estudia la Revelación y su credibilidad, con el acto de fe.

Finalmente ofrece su propuesta:

\emph{ ``La teología fundamental, ``como disciplina del Dar razón de la fe'',
  tiene como identidad: fundar y justificar la pretensión de verdad de la
  revelación cristiana como propuesta sensata de
  credibilidad.''}\footcite[72]{ninotTF}

Desde esta doble identidad identifica una doble tarea: la tarea de fundar y
justificar la denomina ``tarea dogmático-fundacional'' y la pretensión de la
verdad como propuesta sensata de credibilidad la llama ``tarea
apologético-misionera''. De este modo ofrece una concepción de la Teología
Fundamental que integra una doble tarea y se orienta por un lado hacia una
`martiría' como expresión de su dimensión apologética y por otro lado se muestra
inteligente como manifestación de su dimensión fundante en la perspectiva de la
esperanza cristiana.\footnote{\cite[72]{ninotTF}}

Esta doble tarea es la que que asume esta investigación al pretender orientarse
desde una perspectiva teológico-fundamental. La valoración de la categoría del
testimonio en el pensamiento de Elizabeth Anscombe se realizará en clave de
``teología fundante'' que busca arrojar luz sobre el testimonio que es
componente epistemológico en la experiencia humana y categoría teológica con una
función fundacional-hermenéutica. Es también una valoración en clave de
``teología apologética'' que busca describir la categoría del testimonio en su
función apologética-misionera y estudiar su valor como elemento de credibilidad
de la Revelación.



*** notas
  Si la
  revelación misma se apoya en la experiencia humana del testimonio para expresar
  una de las relaciones fundamentales que unen al hombre con Dios, la reflexión
  teológica se encuentra entonces autorizada a explorar los datos de esta
  experiencia.'' Latourelle 1523

  El testimonio como manifestación significativa --hagiofánica-- de la misión de la
  Iglesia en su realidad histórica es, pues, el punto final, pero también puede ser el
  punto inicial, de toda nuestra Teología Fundamental, ya que de él surge el signo
  eclesial de creidibilidad que es la mediación próxima para conocer la Revelación. ninot
  p. 572

    Sentidos
    empírico-histórico
    jurídico
    ético-antropológico
    teológico
** El problema del testimonio
texto de rosseau Prades 243
lessing
Hume
tres objeciones (Prades 294)
no se puede tener conocimiento directo de milagros o profecías
en la vida social cabe aceptar un conocimiento por testimonio a condición de que su
grado de certeza se limite a la probabilidad
no se puede aceptar una comunicación divina que no sea inmediatamente dirigida al
individuo

Prades 295

racionalismo y empirismo convergen en su visión negativa del testimonio al poner en
cuestión la validez de una autoridad externa en orden al conocimiento verdadero

tengamos en cuenta que la Revelación remite a acontecimientos históricos que la razón
moderna no está dispuesta a tomar en consideración porque no le reconoce valor
universal.

divorcio entre mediación testimonial y razón universal

refutado el testimonio como transmisión histórica del saber revelado, dicho saber es
sustituido por el saber ético y religioso accesible a la razón natural y capaz de ser
atestiguado fundamentalmente por medio del buen ejemplo ético.

desafío lanzado por la filosofía moderna

Prades 297
puede el hombre conocer el absoluto en la historia?

hume y la tesis reduccionista


Prades 298 el conocimiento de la verdad mediante testigos
el conocimiento testimonial de la verdad de Dios en la historia 329
