* General
* Naturaleza de la pregunta sobre el testimonio
* El testimonio en la Escritura: la Revelación como acción testimonial de Dios
* El testimonio en el Magisterio: la Iglesia como signo sacramental
* La categoría del testimonio como problema
- Vamos a recuperar la pregunta inicial porque en este apartado la vamos a desgranar un
poco
- para desgranarla vamos a tener en cuenta las aportaciones y desafios de la filosofia
moderna y contemporanea
- implicitamente vamos a decir algo sobre por qué hablar del testimonio hoy
- las preguntas que vamos a hacer son así
  - luego una primera más basada en qué es conocer una verdad para la vida por el
    testimonio
  - luego otra que tiene que ver con la posibilidad de la experiencia de un testimonio
    de la revelación divina
  - finalmente una cuestión relacionada con la posibilidad de que el lenguaje teológico
    tenga valor proposicional

Coady se interesa por el testimonio...

Coady i first began tinking about the epistemological status of testimony in the 1960s
when writing a thesis at Oxford on issues in the theory of perception.
... i recall being intirgued by some remarks of elizabeth anscombe on the topic during
her lectures on the empiricists

when i began reading papers on the subject, my audiences mostly reacted with
incomprehension, or the sort of disbelief evoked by denials of the merest common sense.

Gradually, the climate of thought has changed and there is now more sympathy for the
view that testimony is a prominent and underexplored epistemological landscape,
although what sort of feature it is and how largely it looms are still naturally
matters for disagreement testimony vii

Lackey también

Prades
Latourelle
y ninot
y sagan

lo que quiero hacer es como tres cosas
quiero decir que mira mientras hemos hablado del testimonio en la escritura y en
el magisterio lo hemos descrito dentro de un contexto específico.

en ese contexto es empleado como analogía para describir la acción divina en la
revelación.

dado que es empleado en este contexto de esta manera queremos explorar los datos
de esta experiencia

esto conllevaría pasar de emplear el testimonio como analogía a explorar los
datos de esa experiencia

una cosa que quiero hacer es eso....
decir ok ahora vamos a pasar de describir el testimonio usado en este contexto
como analogía a explorar los datos de esta experiencia

otra cosa que quiero hacer es decir que la categoría del testimonio no siempre
ha sido estimada en el ámbito teológico y filosófico

Coady piensa que tiene que ver con la visión individualista
lackey reconoce que no siempre pero ahora goza de más

pero junto a eso quiero decir que Anscombe pertenece a una epoca contenmporanea
dond


Siguiendo a Latourelle describimos el testimonio que es empleado como analogía
para hablar de la acción divina en la revelación

el testimonio empleado en un contexto específico como es la escritura y el
magisterio

ahí se usa con ese valor analógico

como actividad humana que puede usarse para describir la divina

si es hablamos del testimonio como actividad humana tendríamos que decir que el
testimonio se emplea de ordinario en la actividad humana como... (cuatro tipos)

latourelle sugiere que hay que explorar los datos de esta experiencia

Anscombe explora los datos de esta experiencia en sus lecciones sobre los
empiristas


Aquí lo que se quiere es decir
ok, ya se describió el testimonio dentro de su contexto en el lenguaje de la
escritura y en los escritos del magisterio,

ahora vamos a ver lo problemático.

Cómo se articula la pregunta sobre el testimonio? que pistas se pueden usar?


Ciertamente en el ámbito teológico


Tambien en el magisterio, latourelle: categoria casi omnipresente en vat ii
Latourelle 1532:
se constata que el tema del testimonio es uno de los temas principales y
privilegiados del Vaticano II. Como un \emph{leitmotiv}, aparece en todas las
constituciones y en todos los decretos. A los ojos del concilio, atestiguar
significa acreditar el evangelio como verdad y salvación del hombre mediante una
vida conforme con el evangelio.

Ninot diria.... p. 572
Desde hace aproximadamente un siglo, la categoría testimonio se ha introducido
de forma progresiva en el vocabulario eclesial. La concentración y
personalización operada por el Concilio Vaticano II conlleva la potenciación de
un término nuevo como es el testimonio. \textelp{} lo que el Vaticano I
pretendía al tratar el signo de la Iglesia, que también era visto como ``un
testimonio'' [DH 3013], se encuentra en la categoría testimonio, que con el
Vaticano II irrumpe masivamente.

Prades 81
La teología ha ido revalorizando el testimonio, que había quedado relegado a un
segundo plano en otros momentos de la historia de la teología, hasta alcanzar
una difusión realmente masiva en los años posteriores al Concilio.

83
Después de una fase de ascenso luminoso, la estrella del testimonio ha ido
palideciendo. Algunos textos magisteriales avisaron pronto del posible riesgo de
ambigüedad. Además, en los últimos años se han levantado voces que denuncian un
cierto abuso de esta categoría.

84
se ha hecho notar que el testimonio podía verse limitado a la manifestación de
una especie de seriedad con lo humano...
pero sin llegar a remitir a la verdad de Cristo.

Se trataría del riesgo de una reducción experiencialista del testimonio, donde
lo más importante sería su carácter social-existencial y no tanto la efectiva
verdad teologal transmitida. Se ha criticado consecuentemente la reducción del
testimonio ---y de la misma teología--- a puro relato autobiográfico.

Si se recupera la profundidad implicada en el testimonio se contribuirá a salir
del subjetivismo ---antiguo y moderno---, con su carga correspondiente de
individualismo, tan contrario a la verdadera naturaleza social del hombre y al
carácter a la vez personal y comunitario de la salvación cristiana.

Desde
en el ambito de la teologia hubo boom despues de vat ii
despues bajo
y ahora de nuevo

y es que es la iglesia

y hoy en el mundo hay una situación

y la gilesia tambien tiene que responder

prades dice

en la filosofía ocurre que
como dice lackey

coady por su parte

y anscombe pertenece a esta reflexión contemporanea

en su caso también sus reflexiones responden a los desafios modernos,
específicamente a las propuestas del empirismo


latourelle: niveles informar - compromiso - profesión pública


**** La Categoría del testimonio como problema
***** En contexto de Esc y magis categoría del test usada como analogía
***** Ahora vamos a explorar los datos de esta experiencia
****** Los contextos del testimonio son estos y estos son sus niveles
***** Ahora vamos a tratar al testimonio como cuestión problemática
***** Para plantear problema del testimonio vemos cómo se ha estudiado
***** No siempre se ha tratado
***** en la teología se recupera
***** el contexto actual reclama el testimonio
***** el contexto filosófico
***** Anscombe lo trabaja en su discusión de los empiristas
***** no se ha tratado por visión individualista
***** Vamos a coger la pregunta inicial y la vamos a expandir
***** ¿Cuál es el valor espistemológico del testimonio?
***** ¿Tiene fuerza un testimonio histórico del Absoluto?
***** ¿Tiene carácter veritativo el lenguaje teológico?


Such dependence on testimony was largely glossed over by ancient philosophers, but has
been emphasized by C. A. J. Coady, Elizabeth Fricker, Jennifer Lackey, and many other
recent philosophers, who often trace the historical roots of their discussion back to
an eighteenth-century debate between the Scottish philosophers David Hume and Thomas
Reid.

Hume took what I will call an “inferentialist” view of belief on testimony. “No kind of
reasoning,” he said, is more common or more useful—even necessary—to human life than
the kind derived from the testimony of men. . . . [O]ur confidence in any argument of
this kind is derived wholly from our observation of the truthfulness of human testimony
and of how facts usually conform to the reports witnesses give of them.1

Reid, by contrast, took what I will call a “defaultist” view: It is evident that, in
the matter of testimony, the balance of human judgment is by nature inclined to the
side of belief; and turns to that side of itself when there is nothing put into the
opposite scale. If it was not so, no proposition that is uttered in discourse would be
believed, until it was examined and tried by reason; and most men would be unable to
find reasons for believing the thousandth part of what is told them. Such distrust and
incredulity would . . . place us in a worse condition than that of savages.2

Sadly, accounts of testimonial justification from before Hume and Reid remain largely
unexamined.3 As C. A. J. Coady notes in his pioneering work Testimony: A Philosophical
Study, medieval Christian philosophers were especially disposed to see the value of
testimonial belief, for which Aquinas had an “interesting and subtle theory.”4


* Cómo porceder....

** Coady:
The Problematic > The tradition > the solution > the puzzles > The applications

problematic:
3 chapters of expository and definitional character

1- to which extent our normal cognitive practices are underpinned by our reliance upon
what others tell us
2- analytical clarification of what is involved in talk of testimony and defines a
concept of testimony suited to our purposes in our investigation
3- examines some consquences of this definition an defends it against misgivings
arising from intuition and theory

tradition:
exploration of the work of those few philosophers who have written extensively upon
epistemology of testimony... most attention is given to 
Hume, Price, Russel and Reid

this serves to expose the individualist emphases (already sketched in chapter 1)

all of this discussion is done from a critical standpoint

focus in first part is on the standing or reliability of testimony at large (as an
institutional fact) 
focus in second part is on issues of a more specifically methodological and 'applied'
kind.

** Lackey
Chapter 1
discussion of various views of the nature of testimony found in the philosophical
literature

diagnosis of why the disagreement over the nature of testimony is so deep

argue that our concept of testimony has two distinct and often independent aspects to
it
-it is often thought of as an intentional act on the part of the speaker 
-is often thought of as simply a source of belief or knowledge for the hearer

->inadequate views result either from collapsing these two aspects into a single
account or from a failure to recognize one of them

offer disjunctive view of the nature of testimony that adequately captures these two
independent aspects, and provides the basis for an iluminatign theory of testimony's
epistemological significance

ends with a definition of testimony

Chapter 2
the epistemic status of testimony

belief view of testimony: a testimonial exchange involves a speaker's belief, along
with the epistemic properties it possesses, being transmitted to a hearer 

two dimensions

-necessity claim: a hearer knows (believes with justification/warrant) that p on the
basis of a speaker's testimony that p only if the speaker itself knows (believes with
justification/warrant) that p.

-sufficiency claim: if a speaker knows (believes with justification/warrant) that p,
and a hearer comes to believe that p on the basis of the content of this speaker's
testimony that p without possessing any relevant defeaters, then the hearer also knows
(believes with justification/warrant) that p
support for this view derives from a purported analogy between testimony and memory

in this chapter it is argued that this view is wrong unreliable believers can be
reliable testifiers and reliable believers can be unreliable testifiers, so both claims
are wrong

Chapter 3
development of an alternative picture of epistemology of testimony: statement view of
testimony
focusing on the epistemic status of the statements of speakers, not their beliefs:
this new conception of testimonial knowledge shows that we don't learn from one
another's beliefs, we learn from one another's words

defending this view from thre objections

Chapter 4 
One further objection related to the knowledge norm of assertion and proposal of the
reasonable to believe norm of assertion as a replacement

Chapter 5 
on the topic of testimonial justification or warrant 
critique of the two central views:
reductionism and non reductionism

testimony is neither just as basic, nor ultimately reducible to, other epistemic
sources, such as sense perception, memory, and reason. Thus, both are false.

Chapter 6 
diagnosis on the problem afflicting both reduct and non-reduct: attempting to place all
of the epistemic work on only one or the other of the participants

argue that that we need to look toward a view of testimonial justification or warrant -
dualism

requiring both 
the truthconduciveness of the speaker's testimony 
the possession of appropriate positive reasons by the hearer

Chapter 7
defend dualism against infant/child objection

Chapter 8
family of theories which share three central theses:
1-interpersonal relationship between parties should be the central focus of epistemology
2-features of the interpersonal relationship are responsible for conferring epistemic value
3-epistemic justification or warrant provded by testimony is nonevidential in nature



chapter 6




** Prades:
-Primera parte
teología que se sitúa desde el presente para discernir los signos de los tiempos:
es una introducción que presenta situaciones reales de la sociedad plural de occidente
y de la Iglesia católica que vive en ella

-Segunda Parte
primera comprensión básica del fenómeno linguístico y humano del testimonio, 

entra in medias res a partir de la presentación del testimonio en el AT y NT -> la
originalidad de la comprensión planteada en la revelación del testimonio es la que
gobierna el esfuerzo teológico del libro

se sigue un análisis detallado de la doctrina magisterial sobre el testimonio en el
periodo post conciliar

-Tercera Parte
diálogo con la cultura: recorrido histórico por el pensamiento occidental

habiendo estudiado la índole propia del testimonio revelado a partir de sus fuentes, se
ahonda entonces en la "credibilidad" del hecho testimonial de Cristo y de la Iglesia

el recorrido filosófico sirve para ahondar en la credibilidad de la concepcion original
planteada en las fuentes 

-Cuarta Parte
se hace cargo de lo adquirido

ofrece el punto de vista del autor en clave filosófico-teológica y en sus consecuencias
pastorales 





