* Primary Sources
:DEFINITION:
A primary source provides direct or firsthand evidence about an event, object, person,
or work of art.

Primary sources are first-hand, authoritative accounts of an event, topic, or
historical time period. They are typically produced at the time of the event by a
person who experienced it, but can also be made later on in the form of personal
memoirs or oral histories.

Anything that contains original information on a topic is considered a primary source.
Usually, primary sources are the object discussed in your paper. For instance, if you
are writing an analysis on Upton Sinclair’s The Jungle, the book would be a primary
source. But, just because a source is old does not mean it is a primary source.
:END:
** By Wittgenstein
*** Tractatus Logico-Philosophicus
#+BEGIN_SRC bibtex :tangle primary.bib
@book{wittgenstein1922tractatus,
author = "Ludwig Wittgenstein",
title = "Tractatus Logico-Philosophicus",
publisher = "Dover Publications, Mineola, New York",
year = "1999",
keywords = "primary, wittgenstein",
}
#+END_SRC

** By Wittgenstein translated by G.E.M. Anscombe 
*** Philosophical Investigations (1953)
#+BEGIN_SRC bibtex :tangle primary.bib
@book{wittgenstein1953phiinv,
author = "Ludwig Wittgenstein",
title = "Philosophical Investigations",
publisher = "Wiley Blackwell",
year = "2009",
edition = "4",
keywords = "primary, wittgenstein",
}
#+END_SRC
*** Remarks on the Foundation of Mathematics (1956)
#+BEGIN_SRC bibtex :tangle primary.bib
@book{wittgenstein1956remmath,
author = "Ludwig Wittgenstein",
title = "Remarks on the Foundations of Mathematics",
publisher = "Basil Blackwell",
year = "1956",
%edition = "4",
keywords = "primary, wittgenstein",
}
#+END_SRC

*** Notebooks 1914-1916 (1961)
*** Zettel (1967)
*** Philosophical Remarks 
*** On Certainty (with Denis Paul) (1969)
*** Remarks on the Philosophy of Psicology
*** Remarks on Colour (1977)

** By G.E.M. Anscombe
*** Intention (1957)
*** An Introduction to Wittgenstein's Tractatus (1959)
#+BEGIN_SRC bibtex :tangle primary.bib
@book{IWT, 
author={Gertrude Elizabeth Margaret Anscombe}, 
title={An Introduction to Wittgenstein's Tractatus},
publisher={St. Augustine's Press, Indiana}, 
year={1971},
keywords={primary, anscombe}
}
#+END_SRC
*** Three Philosopers (with Peter Geach) (1961)
*** Collected Philosophical Papers (1981)
**** From Parmenides to Wittgenstein
:worldcat:
http://www.worldcat.org/oclc/299374922
:end:
#+BEGIN_SRC bibtex :tangle primary.bib
  @mvcollection{anscombe1981parmenides,
  title={From Parmenides to Wittgenstein},
  author={Gertrude Elizabeth Margaret Anscombe},
  editor={Gertrude Elizabeth Margaret Anscombe},
  isbn={9780631129226},
  lccn={81004317},
  series={The collected philosophical papers of G.E.M. Anscombe},
  volume={1},
  publisher={Basil Blackwell, Oxford},
  year={1981},
  keywords={Anscombe Elizabeth; Wittgenstein; Logic; Parmenides; Primary Source},
  abstract={Writing on philosophy of mind, philosophy of action, philosophy of
                    language, and philosophical logic, Anscombe is known as one of
                    analytical Thomisms's most prominent figures. This collection
                    includes her writing on the work of her teacher, Ludwig
                    Wittgenstein, with whom she worked closely as co-editor and
                    translator.}
  }
#+END_SRC
***** Introduction
#+BEGIN_SRC bibtex :tangle primary.bib
  @incollection{anscombe1981parmenidesintro,
  booktitle={From Parmenides to Wittgenstein},
  title={Introduction},
  author={Gertrude Elizabeth Margaret Anscombe},
  series={The collected philosophical papers of G.E.M. Anscombe},
  volume={1},
  publisher={Basil Blackwell, Oxford},
  year={1981},
  keywords={Anscombe Elizabeth; Wittgenstein; Logic; Parmenides; Primary Source},
  abstract={}
  }
#+END_SRC
***** Parmenides, Mystery and Contradiction
#+BEGIN_SRC bibtex :tangle primary.bib
  @incollection{anscombe1981parmenidespmc,
  booktitle={From Parmenides to Wittgenstein},
  title={Parmenides, Mystery and Contradiction},
  author={Gertrude Elizabeth Margaret Anscombe},
  series={The collected philosophical papers of G.E.M. Anscombe},
  volume={1},
  publisher={Basil Blackwell, Oxford},
  year={1981},
  keywords={Anscombe Elizabeth; Wittgenstein; Logic; Parmenides; Primary Source},
  abstract={}
  }
#+END_SRC
***** The Early Theory of Forms
#+BEGIN_SRC bibtex :tangle primary.bib
  @incollection{anscombe1981parmenidesetof,
  booktitle={From Parmenides to Wittgenstein},
  title={The Early Theory of Forms},
  author={Gertrude Elizabeth Margaret Anscombe},
  series={The collected philosophical papers of G.E.M. Anscombe},
  volume={1},
  publisher={Basil Blackwell, Oxford},
  year={1981},
  keywords={Anscombe Elizabeth; Wittgenstein; Logic; Parmenides; Primary Source},
  abstract={}
  }
#+END_SRC
**** Metaphysics and the Philosophy of the Mind
:worldcat:
 http://www.worldcat.org/oclc/10430565
:end:
#+BEGIN_SRC bibtex :tangle primary.bib
  @mvcollection{anscombe1981metaphysics,
  title={Metaphysics and the Philosophy of the Mind},
  author={Gertrude Elizabeth Margaret Anscombe},
  editor={Gertrude Elizabeth Margaret Anscombe},
  isbn={9780816610808},
  series={The collected philosophical papers of G.E.M. Anscombe},
  volume={2},
  publisher={Basil Blackwell, Oxford},
  year={1981},
  keywords={Anscombe Elizabeth; Perception; Sensation; Primary Source},
  abstract={Metaphysics and the Philosophy of Mind: The collected Philosophical
                    Papers of G.E.M. Anscombe, Volume 2, is part of a multivolume
                    compilation of her life's work, providing insight into the
                    mind of a groundbreaking 20th century philosopher. This
                    volume's work explores memory, intentionality, causality and
                    time, delving into the language, actions, and logic of
                    perception, sensation, and more.}
  }
#+END_SRC
***** Introduction
#+BEGIN_SRC bibtex :tangle primary.bib
  @incollection{anscombe1981metaphysicsintro,
  booktitle={Metaphysics and the Philosophy of the Mind},
  title={Introduction},
  author={Gertrude Elizabeth Margaret Anscombe},
  series={The collected philosophical papers of G.E.M. Anscombe},
  volume={2},
  publisher={Basil Blackwell, Oxford},
  year={1981},
  keywords={Anscombe Elizabeth; Wittgenstein; Logic; Parmenides; Primary Source},
  abstract={}
  }
#+END_SRC
**** Ethics, Religion and Politics
:worldcat:
http://www.worldcat.org/oclc/873936079
:end:
#+BEGIN_SRC bibtex :tangle primary.bib
  @mvcollection{anscombe1981ethics,
  title={From Parmenides to Wittgenstein},
  author={Gertrude Elizabeth Margaret Anscombe},
  editor={Gertrude Elizabeth Margaret Anscombe},
  isbn={9780631129226},
  lccn={81004317},
  series={The collected philosophical papers of G.E.M. Anscombe},
  volume={3},
  publisher={Basil Blackwell, Oxford},
  year={1981},
  keywords = {Anscombe Elizabeth; Ethics; Religion; Politics; Primary Source},
  abstract = {Gertrude Elizabeth Margaret Anscombe is considered one of analytical
                    philosophy's most prominent figures and a leader in the field
                    of virtue ethics. Ethics, Religion, and Politics: Collected
                    Philosophical Papers, Volume 3, is part of a multi-volume
                    compilation of her work surrounding the philosophy of mind,
                    philosophy of action, philosophy of language, philosophical
                    logic, and ethics. This volume includes selected works
                    relating to consequentialism, intention, and more, providing
                    Ascombe scholars with a high-level view of her evolution of
                    thought.}
  }
#+END_SRC
***** Faith 
#+BEGIN_SRC bibtex :tangle primary.bib
 @incollection{faith,
 author = "Gertrude Elizabeth Margaret Anscombe",
 booktitle = "Ethics, Religion and Politics",
 title = "Faith",
 publisher = "Blasil Blackwell, Oxford",
 year = "1981",
 keywords = "primary, anscombe, standrews",
 }
#+END_SRC

*** St. Andrews Studies Collection (2005-2011)
**** From Plato to Wittgenstein
#+BEGIN_SRC bibtex :tangle primary.bib
@mvcollection{anscombe2011plato,
title={From Plato to Wittgenstein},
author={Gertrude Elizabeth Margaret Anscombe},
editora={Mary Geach},
editorb={Luke Gormally},
isbn={9781845402334},
series={St. Andrews Studies in Philosophy and Public Affairs},
publisher={Imprint Academic},
year={2011},
keywords={Anscombe Elizabeth; Primary Source; St Andrews}
}
 #+END_SRC

*****  Wittgenstein's 'two cuts' in the history of philosophy
#+BEGIN_SRC bibtex :tangle primary.bib
 @incollection{anscombe2011plato:twocuts,
 author = "Gertrude Elizabeth Margaret Anscombe",
 booktitle = "From Plato to Wittgenstein",
 title = "Wittgenstein's 'two cuts' in the history of philosophy",
 publisher = "Imprint Academic",
 year = "2011",
 keywords = "primary, anscombe, standrews",
 }
#+END_SRC

***** The Simplicity of the Tractatus
#+BEGIN_SRC bibtex :tangle primary.bib
 @incollection{anscombe2011plato:simplicity,
 author = "Gertrude Elizabeth Margaret Anscombe",
 booktitle = "From Plato to Wittgenstein",
 title = "The Simplicity of the Tractatus",
 publisher = "Imprint Academic",
 year = "2011",
 keywords = "primary, anscombe, standrews",
 }
#+END_SRC

***** Wittgenstein on Rules and Private Language
#+BEGIN_SRC bibtex :tangle primary.bib
 @incollection{anscombe2011plato:rnpl,
 author = "Gertrude Elizabeth Margaret Anscombe",
 booktitle = "From Plato to Wittgenstein",
 title = "Wittgenstein on Rules and Private Language",
 publisher = "Imprint Academic",
 year = "2011",
 keywords = "primary, anscombe, standrews",
 }
#+END_SRC



* Secondary Sources 
:DEFINITION:
Secondary sources describe, discuss, interpret, comment upon, analyze, evaluate,
summarize, and process primary sources.

Secondary sources interpret or critique primary sources. They often include an analysis
of the event that was discussed or featured in the primary source.

They are second-hand accounts that interpret or draw conclusions from one or more
primary sources.
:END:

** José María Torralba
*** Acción intencional y razonamiento práctico según G.E.M. Anscombe
#+BEGIN_SRC bibtex :tangle secondary.bib
@book{torralba2005accion,
author = "José María Torralba",
title = "Acción Intencional y Razonamiento Práctico Según G.E.M. Anscombe",
publisher = "Ediciones Universidad de Navarra, S.A., Pamplona",
year = "2005",
series = "Colección Filosófica",
volume = "189",
keywords = "anscombe, torralba",
}
#+END_SRC
** Roger Teichmann
*** The Philosophy of Elizabeth Anscombe
#+BEGIN_SRC bibtex :tangle secondary.bib
%Books on Anscombe
@book{teichmann,
author = "Roger Teichmann",
title = "The Philosophy of Elizabeth Anscombe",
publisher = "Oxford University Press",
year = "2008",
keywords = "primary, anscombe, teichmann",
}
#+END_SRC
** Jenny Teichmann
*** Biographical Memoirs of Fellows of The British Academy
:worldcat:
http://www.worldcat.org/oclc/61430741
:end:
#+BEGIN_SRC bibtex :tangle secondary.bib
@incollection{teichman2002fellows,
author = "Jenny Teichman",
editor = "F. M. L. Thompson",
booktitle = "Biographical Memoirs of Fellows I",
title = "Gertrude Elizabeth Margaret Anscombe, 1919-2001",
publisher = "Oxford University Press, Oxford",
year = "2002",
series= "Proceedings of the British Academy",
volume = "115",
isbn="0197262783",
keywords = "bio, anscombe",
}
#+END_SRC

** Biografías de Wittgenstein
*** Ray Monk
#+BEGIN_SRC bibtex :tangle secondary.bib
  @book{monk1991duty,
  author = "Ray Monk",
  title = "Ludwig Wittgenstein: the duty of genius",
  publisher = "Vintage, London",
  year = "1991",
  keywords = "primary, wittgenstein, biography",
  }
#+END_SRC
*** Brian McGuinness
#+BEGIN_SRC bibtex :tangle secondary.bib
  @book{mcguinness1988alife,
  author = "Brian McGuinness",
  title = "Wittgenstein: A Life",
  subtitle = "Young Ludwig 1889-1921",
  publisher = "University of California Press",
  year = "1988",
  keywords = "primary, wittgenstein, biography",
  }
#+END_SRC 

   %Primary Sources 

  %Anscombe 


  %%url = "https://www.britac.ac.uk/sites/default/files/09\%20Geach\%201820.pdf"
  @incollection{biofellowsxiv,
  author = "Anthony Kenny",
  booktitle = "Biographical Memoirs of Fellows XIV",
  title = "Peter Thomas Geach 1916–2013",
  publisher = "Oxford University Press, Oxford",
  year = "2016",
  series= "Biographical Memoirs of Fellows",
  volume = "14",
  isbn = "9780197265918",
  keywords = "bio, anscombe, geach",
  }


  @incollection{phiaut,
  editor = "H. A. Lewis",
  booktitle = "Peter Geach: Philosophical Encounters",
  title = "A Philosophical Autobiography",
  publisher = "Springer Science \& Business Media",
  series = "Synthese Library",
  year = "2013",
  volume = "213",
  pages = "1-25",
  keywords = "bio, anscombe, geach",
  }

  @book{fa&esphom,
  editor = "J.~M.~Torralba and J.~Nubiola",
  title = "La Filosofía Analítica y la Espiritualidad del Hombre",
  publisher = "Ediciones Universidad de Navarra, S.A., Pamplona",
  year = "2005",
  keywords = "primary, anscombe",
  }




  %Secondary Sources


  %Wittgenstein's Diaries
  @book{cnv,
  author = "Ludwig Wittgenstein",
  editor = "Georg Henrik von Wright and Heikki Nyman and Alois Pichler",
  title = "Culture and Value",
  publisher = "Blackwell Publishing, Oxford",
  year = "1998",
  edition = {2 Rev.},
  keywords = "primary, wittgenstein, biography",
  }

  %Wittgenstein's Letters
  @book{cambridgeletters,
  editor = "Brian McGuinness",
  title = "Wittgenstein in Cambridge",
  subtitle = "Letters and Documents 1911-1951",
  publisher = "Wiley-Blackwell",
  year = "2012",
  keywords = "primary, wittgenstein, biography",
  }


  %Russell
  @book{introtomathphi,
  author = "Bertrand Russell",
  title = "Introduction to Mathematical Philosophy",
  publisher = "Nottingham, Spokesman.",
  year = "2008",
  note = "Reprint, Originally published in London in Allen and Unwin, 1919.",
  keywords = "primary, wittgenstein, biography",
  }


  %The Tablet, for news and testimonies
  @article{wisemanlects,
      author  = "",
      title   = "From Our Notebook",
      day     = "13",
      month   = "11",
      year    = "1971",
      journal = "Tablet",
      volume  = "225",
      number  = "6858"
  }

  %Public and Private Occasions
  @book{pubnpriv,
  editor = "James C. Klagge and Alfred Nordman",
  title = "Ludwig Wittgenstein",
  subtitle = "Public and Private Occasions",
  publisher = "{Rowman \& Littlefield Publishers Inc.}, Maryland",
  year = "2003",
  keywords = "secondary, wittgenstein, biography",
  }

  @article{NWR,
	  author = {Christian Eric Erbacher and Sophia Krebs},
	  title = {The First Nine Months of Editing Wittgenstein - Letters from G.E.M.
                    Anscombe and Rush Rhees to G.H. von Wright},
	  journal = {Nordic Wittgenstein Review},
	  year = {2015},
	  keywords = {Wittgenstein Ludwig; Wittgenstein's Nachlass; scholarly editing;
                    history of analytical philosophy; Philosophical
                    Investigations; Anscombe Elizabeth; Rhees Rush; Wright G.H.
                    von},
	  abstract = {The National Library of Finland (NLF) and the Von Wright and
                    Wittgenstein Archives at the University of Helsinki (WWA) keep
                    the collected correspondence of Georg Henrik von Wright,
                    Wittgenstein’s friend and successor at Cambridge and one of
                    the three literary executors of Wittgenstein’s Nachlass. Among
                    von Wright’s correspondence partners, Elizabeth Anscombe and
                    Rush Rhees are of special interest to Wittgenstein scholars as
                    the two other trustees of the Wittgenstein papers. Thus, von
                    Wright’s collections held in Finland promise to shed light on
                    the context of decades of editorial work that made
                    Wittgenstein’s later philosophy available to all interested
                    readers. In this text, we present the letters which von Wright
                    received from Anscombe and Rhees during the first nine months
                    after Wittgenstein’s death. This correspondence provides a
                    vivid picture of the literary executors as persons and of
                    their developing relationships. The presented letters are
                    beautiful examples of what the correspondence as a whole has
                    to offer; it depicts – besides facts of editing – the story of
                    three philosophers, whose conversing voices unfold the human
                    aspects of inheriting Wittgenstein’s Nachlass. Their story
                    does not only deal with editing the papers of an eminent
                    philosopher, but with the attempt to do justice to the man
                    they knew, to his philosophy and to his wishes for
                    publication.},
	  issn = {2242-248X},
	  pages = {195--231},
	  url = {https://www.nordicwittgensteinreview.com/article/view/3288}
  }
