* Motivación Personal
** Categoría del Testimonio 
*** Dimensión de la Vida Cristiana 
**** Creer y conocer
**** Latourelle
*** Vaticano II
**** Biblio
*** Categoría adecuada para el diálogo interreligioso // intercultural
*** Teología de Juan
**** Valor Cognoscitivo y epistemológico propio de la revelación
**** Dinámica de la revelación
** G. E. M. Anscombe
*** Wittgenstein y la filosofía analítica
*** Perspectiva filosófica y creyente
*** Pensamiento contemporaneo
*** Actitud vocal
** Perspectiva Teológico-Fundamental
*** Doble tarea
**** Apologética como diálogo
**** Fundamentación de las categorías teológicas
*** Epistemología de la teología (Cesar Izq)
**** Desde qué teoría del conocimiento se le dota de estatuto epistemológico a la teología? Desde qué ciencia ejemplar se está cuestionando que la teología tenga carácter de ciencia? ¿Es la fe con su dinámica cognoscitiva propia, que excede todo humano conocer, la que justifica suficientemente el valor cognoscitivo de la teología?

* Objetivo de la Tesina
- Presentar la categoría del testimonio dentro de la concepción de la revelación cristiana.

- Indagar en la problemática epistemológica que plantea el testimonio como experiencia del conocimiento de la verdad.

- Exponer una valoración crítica sobre el valor epistemológico del testimonio según se presenta en el ámbito de la filosofía analítica, específicamente en el pensamiento de Elizabeth Anscombe.


* Fuentes Básicas y bibliografía elemental que se va aconsultar
** Fuentes relacionadas a la categoría del testimonio
** Fuentes relacionadas a G. E. M. Anscombe
** Fuentes relacionadas a la filosofía analítica y el valor cognoscitivo de la fe
** Fuentes relacionadas a la teología fundamental
