* La Naturaleza del Testimonio Cristiano
** El testimonio en la dinámica de la revelación

-¿El martir afirma algo más que la autenticidad de su creencia?


* El Valor Cognoscitivo de la Fe y el problema del lenguaje religioso en la filosofía analítica.

* Anscombe y Wittgenstein
- Ludwig Wittgenstein
- Wittgenstein on Rules and Private Language
- Wittgenstein, Frege and Ramsey
- Wittgenstein: Whose Philosopher?
- Wittgenstein's 'two cuts' in the history of philosophy
- Consequences of the Picture Theory
- On the form of Wittgsenstein's writing
- Was Wittgenstein a conventionalist?
- The Simplicity of the Tractatus
- An Introduction to Wittgenstein's Tractatus

* La Categoría del Testimonio en el Pensamiento de Anscombe
** Cuestiones generales
*** Estatuto epistemológico del testimonio

**** puritan response (Plato and Collingwood)
Humans are reliant on testimony for a large amount of what they think they know, so knowledge is rarer than is usually believed

**** reductive response(Hume, Russell, Clifford)
We know when we rely on testimony, but our dependence on testimony is justified by more fundamental forms of evidence (like our own experience or inference). {We trust testimony because it has been our experience that it's usually reliable}.

**** fundamentalist response(Reid, Coady is close to this)
Our reliance upon testimony should be regarded as fundamental to the justification of belief in the same way as perception, memory and inference.

**** end-of-epistemology response(Quine, Popper)
Our reliance on testimony is one of different objections presented as an objection to foundationist epistemology

*** Planteamiento del problema

**** Approach de Coady:
***** the problem
- Coady:
Concept of testimony[to be defined]:
A certain Speech Act(Searle)
Illocutionary Act(J. L. Austin)
may be and standardly is 
performed 
under certain conditions
and
with certain intentions
such that we might naturally think of 
the definition 
as giving us
conventions governing
the existence of the act of testifying.

Cuáles son las convenciones que gobiernan la existencia del acto de testificar?

El testimonio formal como la elevación en dignidad del testimonio natural por el contexto más ceremonial.
a) it is a form of evidence
b) it is constitued by persons A offering hteir remarks as evidence so that we are invited to accept p because A says that p.
c) the person offering the remarks is in a position to do so, ie. has the relevant authority, competence or credentials
d) the testifier has been given a certain status in the inquiry by being formally aknowledged as a witness and by giving his evidence with due ceremony
e)As a specification o (c) within english la and proceedings influenced by it, the testimony is normally required to be first-hand
f)as a corollary of (a) the testifier's remarks should be relevant to a disputed or unresolved question and should be directed to those who are in need of evidence on the matter

El testimonio natural como cotidiana operación social de la mente
Las convenciones que gobiernan el 'speech act' de testificar son:
A speaker S testifies by making some statement p if and only if:
a)His stating that p is evidence that p and is offered as evidence that p 
b)S has the relevant competence, authority, or credentials to state truly that p
c)S's statement that p is relevant to some disputed or unresolved question (which may or may not be, p?) and is directed to those who are in need of evidence on the matter

It's illocutionary point (mode of achievement) is: to inform an audience that something is the case.(Same as assertions and objections)
The way to achieve this point (different to assertions) is through the speaker's status as one having a particular kind of authority to speak to the matter in question, a matter where evidence is required. 
This is not the same as presenting the information that p for acceptance on the basis of its following from certain other propositions presented, independent of the status of the witness. 
One who testifies gives a specific type of assertion.

***** The solution
[Relevancia del testimonio en el uso ordianrio -> porque está tan desatendido en la discusión filosófica?
¿Tiene el testimonio alguna relevancia en nuestro conocimiento?  ¿Cuál?
¿Es razonable la confianza que ponemos ordinariamente en el testimonio?
Cual es el lugar del testimonio en la epistemología? cuál es la tradición sobre ese lugar?
Qué se puede decir para defender la confianza que ponemos en el testimonio en nuestro conocimiento?
La solución: 
el status del testimonio:
1. Similitudes y diferencias entre el testimonio y las otras fuentes de información como estas se manifiestan a sí mismas en la gramática de nuestros conceptos y en nuestros modos naturales de pensamiento e investigación.
1.a. Escrutinio del comportamiento de ciertos verbos relativos a la percepción.
----->¿Cuál es el verbo perceptivo relativo al testimonio? ¿Cual es el verbo propio de recibir testimonio?
]

**** Approach de Prades:
¿Es razonable la empresa cristiana de ofrecer el testimonio de cristo como anuncio de salvación verdadero y creible?

**** Approach de Conesa (Filosofía analítica)
¿Se pueden aplicar los conceptos de verdad y falsedad a las proposiciones religiosas?
Respuesta de Anscombe según Conesa
-> Sí, fe es la creencia puesta en aquello que se cree que es palabra de Dios. El valor cognoscitivo de la fe es el valor de aquel conocimiento que se adquiere por testimonio.

**** Antiseri:
Fe es el asentimiento a verdades que no se demuestran y que aceptamos como verdades sobre la base de la confianza en alguien que testifique esas verdades. ¿en virtud de qué testimonio se acepta una específica visión del mundo, se creen las verdades expresada en el símbolo, se toman como indiscutibles unos dogmas que desconciertan nuestra razón y se impone una determinada moral?
->La lógica del testimonio ofrece a estas verdades su justificación. 


*** Recorrido por el pensamiento de Anscombe

**** Verdad y Falsedad
***** La Pregunta Filosófica sobre la Verdad:
[Language and Thought ]
[Truth]
- Truth: Anselm and Wittgenstein
- Truth: Anselm or Thomas?
- Anselm and the Unity of Truth
- A theory of Language?
- Necessity and Truth
- Thought and Action in Aristotle: What is Practical Truth?
- Practical Truth

[Bedrock]

**** Analisis del Lenguaje Epistémico
- On Wisdom
- Knowledge and Certainty
- Knowledge and Reverence for Human Life
- 'The General Form of Proposition'
- Comments on Professor R. L. Gregory's Paper on Perception
- On Brute Facts
- Will and Emotion
- Memory, 'Experience' and Causation
- Understanding Proofs: Meno, 85d9 – 86c2
- Subjunctive Conditionals
- What is it to Believe Someone?
- The Intentionality of Sensation
- Substance
- The Subjectivity of Sensation
- Events in the mind
- On Sensations of Position
- Intention
- Pretending
- Practical Inference

**** Proposiciones de fe y lenguaje religioso
- Faith
- A Reply to Mr. C. S. Lewis's Argument that “Naturalism” is Self- Refuting
- Has Mankind One Soul: An Angel Distributed among many Bodies?
- Human Essence
- La esencia Humana
- Plato, Soul and 'the Unity of Apperception'
- Why Anselm's Proof in the Proslogion in not an onthological argument
- On the Hatred of God
- On Attachment to Things and Obedience to God
- On being on Good Faith
- On Humanae Vitae
- Philosophers and Economists: Two Philosphers' Objections to Usury
- Retractation
- Sin: the McGivney Lectures
- The Inmortality of the Soul
- Two Moral Theologians
- You Can Have Sex without Children: Christianity and the New Offer
- Morality
- Modern Moral Philosophy

**** Hume y la Tradición sobre el Valor espistemológico del testimonio:

***** ("Tradition" in Coady)
****** [Testimony and Observation: The reductive approach 
If any view [about testimony] has claim to the title of the 'received view' it's Hume's

****** Deciding for testimony (Price)
Price's and Russell's attempts to vindicate our extensive reliance upon testimony

****** The analogical approach
Rusell's discussion

****** Scottish fundamentalism
Thomas Reid]

***** Tradición Sobre el lugar espistemológico: Hume y la Causalidad, Conocimiento de la Historia <- On Certainty [Tradición: Hume, Russell, Reid & Price] Coady y Lackey
- Hume and Julius Caesar
- Hume on causality: introductory
- The Reality of the Past
- Causality and Determination
- Causality and Extensionality
- “Whatever has a beginning of existence must have a cause”: Hume's Argument Exposed
- Times, Beginnings and Causes
- Before and After
- The Causation of Action
- Chisolm on Action
- Action, Intention and 'Double Effect'
- Part Three: Causality and time
- On Russell's Theory of Descriptions

**** Verbos epistémicos
¿Cuál es el verbo para recibir testimonio?
"learn"?

**** Lógica del Testimonio:
- Authority in Morals
- On the Source of the Authority of the State
- The Moral Enviroment of the Child
- On Promising and its justice, and Whether it Need be Respected in Foro Interno
- Rules, Rights and Promises
- The Two Kinds of error in action

**** Sentido, sinsentido y misterio
***** [Sense, Nonsense and Mystery]
****** Misterio
- 'Mysticism' and Solipsism
- Analytical Philosophy and the Sipirituality of Man
- On Transubstantiation
- Parmenides, Mystery and Contradiction
- The Question of Linguistic Idealism
- Paganism, Superstition and Philosophy
- On Piety, or: Plato's Euthyphro


** Cuestiones específicas (puzzles)
Credibilidad de algunos tipos de testimonio
¿Son creibles las narraciones lo extraordinario e inesperado?
¿Es posible conocer el hecho histórico por medio de la tradición?
¿Conozco una proposición que creo por la autoridad de otro pero yo no puedo probar?
**** Narraciones Extraordinarias
- Aristotle and the Sea Battle: De Interpretatione, Chapter IX
- Prophecy and Miracles
- Hume on Miracles
- Modern Moral Philosophy
- Good and Bad Human Action

* Valoración y Crítica




