#+PROPERTY: header-args:latex :tangle ../../tex/ch4/critic.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

https://w2.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20131124_evangelii-gaudium.html#_ftnref3

7. La tentación aparece frecuentemente bajo forma de excusas y reclamos, como si debieran darse innumerables condiciones para que sea posible la alegría. Esto suele suceder porque «la sociedad tecnológica ha logrado multiplicar las ocasiones de placer, pero encuentra muy difícil engendrar la alegría»[2]. Puedo decir que los gozos más bellos y espontáneos que he visto en mis años de vida son los de personas muy pobres que tienen poco a qué aferrarse. También recuerdo la genuina alegría de aquellos que, aun en medio de grandes compromisos profesionales, han sabido conservar un corazón creyente, desprendido y sencillo. De maneras variadas, esas alegrías beben en la fuente del amor siempre más grande de Dios que se nos manifestó en Jesucristo. No me cansaré de repetir aquellas palabras de Benedicto XVI que nos llevan al centro del Evangelio: «No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva»[3].

https://w2.vatican.va/content/benedict-xvi/es/encyclicals/documents/hf_ben-xvi_enc_20051225_deus-caritas-est.html

1. Hemos creído en el amor de Dios: así puede expresar el cristiano la opción fundamental de su vida. No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva. En su Evangelio, Juan había expresado este acontecimiento con las siguientes palabras: « Tanto amó Dios al mundo, que entregó a su Hijo único, para que todos los que creen en él tengan vida eterna » (cf. 3, 16). La fe cristiana, poniendo el amor en el centro, ha asumido lo que era el núcleo de la fe de Israel, dándole al mismo tiempo una nueva profundidad y amplitud. En efecto, el israelita creyente reza cada día con las palabras del Libro del Deuteronomio que, como bien sabe, compendian el núcleo de su existencia: « Escucha, Israel: El Señor nuestro Dios es solamente uno. Amarás al Señor con todo el corazón, con toda el alma, con todas las fuerzas » (6, 4-5). Jesús, haciendo de ambos un único precepto, ha unido este mandamiento del amor a Dios con el del amor al prójimo, contenido en el Libro del Levítico: « Amarás a tu prójimo como a ti mismo » (19, 18; cf. Mc 12, 29- 31). Y, puesto que es Dios quien nos ha amado primero (cf. 1 Jn 4, 10), ahora el amor ya no es sólo un « mandamiento », sino la respuesta al don del amor, con el cual viene a nuestro encuentro.

https://www.commonwealmagazine.org/unflinching:
In her 1957 book Intention, now regarded as the foundational text in analytic philosophy of action, Anscombe attempted a Wittgensteinian defense of the understanding of intention that philosophers like Sidgwick and Hare had ruled out. She was also arguing there against a view of intention that had become popular among Catholic moral theologians. Her 1961 paper “War and Murder” described this view as resting on a form of “Cartesian psychology”:

According to this psychology, an intention was an interior act of the mind which could be produced at will. Now if intention is all important—as it is—in determining the goodness or badness of an action, then, on this theory of what intention is, a marvelous way offered itself of making any action lawful. You only had to “direct your intention” in a suitable way. In practice, this means making a little speech to yourself: “What I mean to be doing is…”

LA ÚLTIMA LINEA DEL TRABAJO SERÁ ESTA:

#+BEGIN_SRC latex
\blockquote[{\Cite[\S505]{wittgenstein1969oncertes}}]{Es ist immer von Gnaden der Natur, wenn man etwas weiß}. Para Wittgenstein, el juego de lenguaje, que es esencial en nuestra experiencia de conocer, es posible por una especie de providencia de la naturaleza. Con esto se refiere al hecho de que nuestras aseveraciones son posibles porque no ocurre constantemente que neguemos los fundamentos o justificaciones de afirmaciones que hemos llegado a considerar un juicio cierto y sólido. Añade que el \blockquote[{\Cite[\S509]{wittgenstein1969oncertes}}]{juego de lenguaje sólo es posible si se confía en algo}. Y con esto no quiere decir \enquote*{si es posible confiar}, sino si se confía de hecho, si se actúa en confianza.

Elizabeth Anscombe añadiría que este juego de lenguaje, y por tanto el conocer, es posible por la Gracia de Dios\footnote{\Cite[Cf.][224]{teichmann2008ans}: \enquote{It is `by favour of Nature' that assertion and knowledge are posible (cf. \emph{On Certainty, para. 505}); for Anselm and for Anscombe, it is (also) by the grace of God.}}. Con esto no estaríamos diciendo que ella simplemente cambiaría `Naturaleza' por `Dios' en la afirmación de Wittgenstein sobre la certeza, se refiere a otras cosas más.

Por un lado `Verdad' \blockquote[{\Cite[47]{torralbaynubiola2005fayeh:verdad}}]{es uno de los nombres de Dios} y \blockquote[{\Cite[47]{torralbaynubiola2005fayeh:verdad}}]{Hay verdad en muchas cosas}. Aquí ella también es `hermana intelectual' de San Anselmo, ambos comparten una noción trascendental de la verdad como rectitud que va a través de muchas cosas: proposiciones, el pensamiento, la voluntad, la acción y el ser de las cosas\footnote{\Cite[Cf.][197]{teichmann2008ans}: \enquote{In Anselm's account of how truth serves as the goal of assertion, he describes truth as `rightness perceptible to the intellect alone' \textelp{} a rightness that is to be found no only in propositions, but also in thought, will, action, and the being of things.}}. Y aquí podríamos atribuir a la Gracia Divina nuestra capacidad de reconocer y apreciar esta rectitud.

Esta idea nos conduce a otra en la que las reflexiones de Anscombe aluden a la Providencia Divina como fundamento del lenguaje. Ella se pregunta: \enquote*{¿es la humanidad la que produce las esencias experesadas en la gramática?}\footnote{\Cite[Cf.][72]{torralbaynubiola2005fayeh:esencia}} y propone que la respuesta a esto, según su parecer, no se encuentra en la humanidad misma, sino en \enquote{quien produjo la humanidad}; y añade: \blockquote[{\Cite[73]{torralbaynubiola2005fayeh:esencia}}]{Para mucha gente hoy día, esta respuesta equivale a ``la evolución''. Pero esto no es otra cosa que decir ``bueno, ocurrió y ya está''. Una respuesta más racional sería: la Inteligencia, que creó al hombre y que creó otras cosas por medio del \emph{logos} de su sabiduría. Aquel \emph{logos} constituye una infinidad de \emph{logos} de cosas posibles y reales, y también de las invenciones humanas}. Para ella la pregunta \enquote*{¿qué ha producido las esencias expresadas en el lenguaje humano?} es equivalente a \enquote*{¿qué es lo que ha producido el ser humano, capaz de aprender un lenguaje?}. Termina diciendo: \blockquote[{\Cite[74]{torralbaynubiola2005fayeh:esencia}}]{aquello que produce las inteligencias que producen tales cosas, y el resto del lenguaje también, es a su vez una inteligencia o unas inteligencias. Pero tendrá que ser una inteligencia de tipo distinto de la humana: porque si no, tendríamos un regreso al infinito. Es necesario que esta inteligencia (o estas inteligencias) sea capaz de inventar el lenguaje, incluso aunque tenga la habilidad de usar el lenguaje como lo hacemos los seres humanos}. Y según esto podríamos atribuir a la Gracia el que la humanidad posea el lenguaje del todo.

Pero, ¿Anscombe está hablando de Dios aquí? Es posible hacer esa conexión; habla de la `Intelgiencia' ``distinta de la humana'' que crea ``por medio del \emph{logos} de su sabiduria'', que es capaz de ``inventar el lenguaje'' y de ``usar el lenguaje como lo hacemos'' nosotros. Esto evoca ya el modo en que Elizabeth hablaba de la fe. Aquí estamos en la misma situación en la que nos dejan muchas de las expresiones de Anscombe presentes en este estudio. ¿Son nociones valiosas para la teología?, ¿nos dan ocasión para hablar de Dios y de su actuar? La respuesta a esto se encuentra, en las conexiones que nos permiten establecer.

Podríamos caracterizar el enfoque de la teología fundamental en clave `dogmático-fundacional' y `apologético-misionera'\footnote{\Cite[Cf.][80-85]{ninot2009tf}}. Desde esta perspectiva, el testimonio puede ser analizado según el primer aspecto como un modo de describir y comprender la Revelación y según el segundo como un modo de ``dar razón de nuestra esperanza'' en diálogo con la sociedad plural de la que formamos parte. Desde de este enfoque, ¿qué oportunidades ofrecen las reflexiones de Anscombe que hemos estudiado al análisis del testimonio? Una buena clave para situar su aportación es esta: \blockquote[{\Cite[451]{prades2015testimonio}}]{Ninguna esfera del saber humano puede prescindir <<absolutamente>> de la confianza en los propios sentidos, en la memoria, en la percepción sensible, en el otro, en la sociedad. El hombre vive de creencias, que no son contrarias al ejercicio crítico del saber, sino que se entrelazan inevitablemente con el mismo. Por este motivo la razón del hombre es una razón creyente. La plena estatura de esta razón creyente requiere llegar a distinguir la confianza de la mera credulidad}.

Las discusiones de Anscombe sobre el saber, la verdad, el lenguaje, nuestras creencias y sus fundamentos describen una visión del lenguaje vivo en la actividad humana y del ser humano activo en el uso del lenguaje en el contexto de sus relaciones.

En el centro
la creencia de que Dios está involucrado en la actividad humana del lenguaje.



El recorrido por el sector de la obra de Anscombe que hemos hecho para indagar sobre el testimonio nos deja con una impresión sobre el lenguaje y sobre la naturaleza de distintos tipos de creencias nuestras y cómo estas quedan fundamentadas o justificadas. En estas descripciones se encuentran muchas oportunidades para establecer conexiones con

Entender la revelación de Dios como testimonio
Valor apologético del testimonio

La verdad práctica raz pract 189
Anscombe explica que la verdad práctica...

EG 7-8
No me cansaré de repetir aquellas palabras de Benedicto XVI que nos llevan al centro del Evangelio: «No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva»[3].

8. Sólo gracias a ese encuentro —o reencuentro— con el amor de Dios, que se convierte en feliz amistad, somos rescatados de nuestra conciencia aislada y de la autorreferencialidad. Llegamos a ser plenamente humanos cuando somos más que humanos, cuando le permitimos a Dios que nos lleve más allá de nosotros mismos para alcanzar nuestro ser más verdadero. Allí está el manantial de la acción evangelizadora. Porque, si alguien ha acogido ese amor que le devuelve el sentido de la vida, ¿cómo puede contener el deseo de comunicarlo a otros?


\blockquote[][\,(St 1, 22-25)]{\emph{Poned en práctica la palabra y no os contentéis con oírla, engañándoos a vosotros mismos. Porque quien oye la palabra y no la pone en práctica, ese se parece al hombre que se miraba la cara en un espejo y, apenas se miraba, daba media vuelta y se olvidaba de cómo era. Pero el que se concentra en una ley perfecta, la de la libertad, y permanece en ella, no como oyente olvidadizo, sino poniéndola en práctica, ese será dichoso al practicarla}}.
#+END_SRC
