#+PROPERTY: header-args:latex :tangle ../../tex/ch4/critic.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

https://w2.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20131124_evangelii-gaudium.html#_ftnref3

7. La tentación aparece frecuentemente bajo forma de excusas y reclamos, como si debieran darse innumerables condiciones para que sea posible la alegría. Esto suele suceder porque «la sociedad tecnológica ha logrado multiplicar las ocasiones de placer, pero encuentra muy difícil engendrar la alegría»[2]. Puedo decir que los gozos más bellos y espontáneos que he visto en mis años de vida son los de personas muy pobres que tienen poco a qué aferrarse. También recuerdo la genuina alegría de aquellos que, aun en medio de grandes compromisos profesionales, han sabido conservar un corazón creyente, desprendido y sencillo. De maneras variadas, esas alegrías beben en la fuente del amor siempre más grande de Dios que se nos manifestó en Jesucristo. No me cansaré de repetir aquellas palabras de Benedicto XVI que nos llevan al centro del Evangelio: «No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva»[3].

https://w2.vatican.va/content/benedict-xvi/es/encyclicals/documents/hf_ben-xvi_enc_20051225_deus-caritas-est.html

1. Hemos creído en el amor de Dios: así puede expresar el cristiano la opción fundamental de su vida. No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva. En su Evangelio, Juan había expresado este acontecimiento con las siguientes palabras: « Tanto amó Dios al mundo, que entregó a su Hijo único, para que todos los que creen en él tengan vida eterna » (cf. 3, 16). La fe cristiana, poniendo el amor en el centro, ha asumido lo que era el núcleo de la fe de Israel, dándole al mismo tiempo una nueva profundidad y amplitud. En efecto, el israelita creyente reza cada día con las palabras del Libro del Deuteronomio que, como bien sabe, compendian el núcleo de su existencia: « Escucha, Israel: El Señor nuestro Dios es solamente uno. Amarás al Señor con todo el corazón, con toda el alma, con todas las fuerzas » (6, 4-5). Jesús, haciendo de ambos un único precepto, ha unido este mandamiento del amor a Dios con el del amor al prójimo, contenido en el Libro del Levítico: « Amarás a tu prójimo como a ti mismo » (19, 18; cf. Mc 12, 29- 31). Y, puesto que es Dios quien nos ha amado primero (cf. 1 Jn 4, 10), ahora el amor ya no es sólo un « mandamiento », sino la respuesta al don del amor, con el cual viene a nuestro encuentro.

https://www.commonwealmagazine.org/unflinching:
In her 1957 book Intention, now regarded as the foundational text in analytic philosophy of action, Anscombe attempted a Wittgensteinian defense of the understanding of intention that philosophers like Sidgwick and Hare had ruled out. She was also arguing there against a view of intention that had become popular among Catholic moral theologians. Her 1961 paper “War and Murder” described this view as resting on a form of “Cartesian psychology”:

According to this psychology, an intention was an interior act of the mind which could be produced at will. Now if intention is all important—as it is—in determining the goodness or badness of an action, then, on this theory of what intention is, a marvelous way offered itself of making any action lawful. You only had to “direct your intention” in a suitable way. In practice, this means making a little speech to yourself: “What I mean to be doing is…”

LA ÚLTIMA LINEA DEL TRABAJO SERÁ ESTA:

Santiago 1,22-25
22
Poned en práctica la palabra y no os contentéis con oírla, engañándoos a vosotros mismos. 23 Porque quien oye la palabra y no la pone en práctica, ese se parece al hombre que se miraba la cara en un espejo 24 y, apenas se miraba, daba media vuelta y se olvidaba de cómo era. 25 Pero el que se concentra en una ley perfecta, la de la libertad, y permanece en ella, no como oyente olvidadizo, sino poniéndola en práctica, ese será dichoso al practicarla.

* /Lectio/:
:DESCRIPTION:
Truth: Anselm or Thomnas?
Truth: Anselm and Wittgenstein/Verdad
'Making True'

:END:
** Análisis
Atender la razonabilidad de la tarea de dar testimonio del Hecho de Cristo como
anuncio de salvación supone:
<<recuperar la legitimidad de la pregunta filosófica y religiosa sobre la
verdad, en un tiempo que parece a priori que la rechaza.>>

En el contexto de la filosofía analítica la pregunta sobre la verdad (y la
falsedad) está entrelazada con la pregunta sobre el significado.

Wittgenstein, que "amó la verdad" ofreció más atención a la verdad que al
significado en el Tractatus, mientras que en las Investigaciones Filosóficas
parece ser al revés. ¿Anscombe atiende estos temas de la misma manera?

- En los escritos de Anscombe ambos temas se tratan por separado pero gozan
  aproximadamente del mismo status.
- El significado se

* /Propositum/:
:DESCRIPTION:

:END:

** Propositio: "Verdad y Significado"
#+BEGIN_SRC latex
  % SECCIÓN 1: La verdad
\section{Verdad y Significado}
#+END_SRC


* /////////////////////////////////////////////////////////
* /Quaestio/: What is to have truth?
:STATEMENT:
The proposition has a sense which is independent of the facts.
:END:
:DISCARDED:

:END:
:DESCRIPTION:

:END:

#+BEGIN_SRC latex
  \subsection{Qué es tener la verdad}
  Elizabeth Anscombe visitó muchas veces la Universidad de Navarra junto con Peter
  Geach y allí impartió algunos seminarios y participó de las Reuniones
  Filosóficas.\footcite[cf.~][p.~15]{fa&esphom}

  En una de sus visitas, en octubre de 1983, ofreció dos lecciones tituladas:
  ``Verdad'' y ``La unidad de la verdad''. En la primera lección planteó la
  cuestión de este modo:

  \citalitlar{Hay verdad en muchas cosas. Mirando a mi título `Truth' me quedo
    algo sobrecogida por él, pues lo que salta de la página hacia mi es uno de los
    nombres de Dios. `He amado la verdad' me dijo una vez un profesor moribundo,
    después de hablarme de la dificultad que sentía sobre la idea de amar a Dios.
    Sin embargo: `He amado la verdad'. Y luego, temiendo que yo no malentendiera
    su afirmación: `No me refiero, cuando digo eso, que \emph{tenga} la verdad'}
  \citalitlar{Tener la verdad, estar en la verdad--¿qué es esto? Y qué quiso decir
    Nuestro Señor al llamarse a \emph{sí mismo} la verdad? `No hay tal cosa como
    la verdad, sólo hay verdades', dijo mi suegro a la primera esposa de Bertrand
    Russell. Russell fue su maestro; la influencia se ve con facilidad.}
  \citalitlar{¿Pero cuáles son las cosas que tienen verdad en ellas? ¿Tiene la
    creación? ¿tienen las acciones? A qué se refería Aristóteles cuando dijo que
    el bien de la razón práctica era `verdad de acuerdo con el recto deseo'? ¿Las
    cosas hechas por los hombres tienen verdad en ellas? ¿Qué, de nuevo, quiso
    decir Aristóteles cuando afirmó que el arte o la habilidad es una disposición
    productiva con un logos verdadero? Mas allá todavía: Qué fuerza tiene contar
    la verdad entre los `trascendentales', esas cosas que `atraviesan' todas las
    categorías y todas las formas especiales de las cosas; y que no pertenecen
    cada uno a una categoría, como el color: amarillo; o el area: un acre; o el
    animal: un caballo.\footcite[p.~71]{FPW}}

#+END_SRC


* /Expositio/: What is truth?
:STATEMENT:

:END:
Verdad
Unidad de la Verdad
Truth: Anselm or Thomas
Making True
Necessity of Truth
On Brute Facts

#+BEGIN_SRC latex
  La cuestión que Anscombe trae en esta lección tiene que ver con la primacia de
  la verdad sobre la falsedad.\footcite[195]{teichmann}

  Anscombe no se traga toda la teoría de la imagen de las proposiciones. Pero ella
  ve lo que es probablemente la cosa mas iluminadora de la comparación de
  Wittgenstein de imagenes y proposiciones; es decir, este `Janus-faced aspect' de
  las proposiciones, un aspecto que puede ser expresado de diversos modos--como el
  que `No' no se corresponde con nada en la realidad, o que P y no-P (los
  símbolos) pueden ser sistematicamente inercambiados, cada uno asumiendo la
  función del otro..

#+END_SRC

* /Disputatio/:
:STATEMENT:

:END:


* /Solutio/:
:STATEMENT:

:END:

* /In Testimonium/:
:STATEMENT:

:END:


* [Local Variables]
# Local Variables:
# mode: org
# mode: auto-fill
# word-wrap:t
# truncate-lines: t
# org-hide-emphasis-markers: t
# End:
