#+PROPERTY: header-args:latex :tangle ../../tex/ch4/critic.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

https://w2.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20131124_evangelii-gaudium.html#_ftnref3

7. La tentación aparece frecuentemente bajo forma de excusas y reclamos, como si debieran darse innumerables condiciones para que sea posible la alegría. Esto suele suceder porque «la sociedad tecnológica ha logrado multiplicar las ocasiones de placer, pero encuentra muy difícil engendrar la alegría»[2]. Puedo decir que los gozos más bellos y espontáneos que he visto en mis años de vida son los de personas muy pobres que tienen poco a qué aferrarse. También recuerdo la genuina alegría de aquellos que, aun en medio de grandes compromisos profesionales, han sabido conservar un corazón creyente, desprendido y sencillo. De maneras variadas, esas alegrías beben en la fuente del amor siempre más grande de Dios que se nos manifestó en Jesucristo. No me cansaré de repetir aquellas palabras de Benedicto XVI que nos llevan al centro del Evangelio: «No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva»[3].

https://w2.vatican.va/content/benedict-xvi/es/encyclicals/documents/hf_ben-xvi_enc_20051225_deus-caritas-est.html

1. Hemos creído en el amor de Dios: así puede expresar el cristiano la opción fundamental de su vida. No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva. En su Evangelio, Juan había expresado este acontecimiento con las siguientes palabras: « Tanto amó Dios al mundo, que entregó a su Hijo único, para que todos los que creen en él tengan vida eterna » (cf. 3, 16). La fe cristiana, poniendo el amor en el centro, ha asumido lo que era el núcleo de la fe de Israel, dándole al mismo tiempo una nueva profundidad y amplitud. En efecto, el israelita creyente reza cada día con las palabras del Libro del Deuteronomio que, como bien sabe, compendian el núcleo de su existencia: « Escucha, Israel: El Señor nuestro Dios es solamente uno. Amarás al Señor con todo el corazón, con toda el alma, con todas las fuerzas » (6, 4-5). Jesús, haciendo de ambos un único precepto, ha unido este mandamiento del amor a Dios con el del amor al prójimo, contenido en el Libro del Levítico: « Amarás a tu prójimo como a ti mismo » (19, 18; cf. Mc 12, 29- 31). Y, puesto que es Dios quien nos ha amado primero (cf. 1 Jn 4, 10), ahora el amor ya no es sólo un « mandamiento », sino la respuesta al don del amor, con el cual viene a nuestro encuentro.

https://www.commonwealmagazine.org/unflinching:
In her 1957 book Intention, now regarded as the foundational text in analytic philosophy of action, Anscombe attempted a Wittgensteinian defense of the understanding of intention that philosophers like Sidgwick and Hare had ruled out. She was also arguing there against a view of intention that had become popular among Catholic moral theologians. Her 1961 paper “War and Murder” described this view as resting on a form of “Cartesian psychology”:

According to this psychology, an intention was an interior act of the mind which could be produced at will. Now if intention is all important—as it is—in determining the goodness or badness of an action, then, on this theory of what intention is, a marvelous way offered itself of making any action lawful. You only had to “direct your intention” in a suitable way. In practice, this means making a little speech to yourself: “What I mean to be doing is…”

LA ÚLTIMA LINEA DEL TRABAJO SERÁ ESTA:

#+BEGIN_SRC latex
451 testimonio prades

Entender la revelación de Dios como testimonio
Valor apologético del testimonio

Lo que hemos visto es Descripción de la naturaleza de nuestras creencias y sus fundamentos o justificaciones.

verdad es uno de los nombres de Dios que va atraves de las cosas, es rectitud

La verdad práctica raz pract 189
Anscombe explica que la verdad práctica...

esp del hom 74: sea capaz de inventar el lenguaje

EG 7-8
No me cansaré de repetir aquellas palabras de Benedicto XVI que nos llevan al centro del Evangelio: «No se comienza a ser cristiano por una decisión ética o una gran idea, sino por el encuentro con un acontecimiento, con una Persona, que da un nuevo horizonte a la vida y, con ello, una orientación decisiva»[3].

8. Sólo gracias a ese encuentro —o reencuentro— con el amor de Dios, que se convierte en feliz amistad, somos rescatados de nuestra conciencia aislada y de la autorreferencialidad. Llegamos a ser plenamente humanos cuando somos más que humanos, cuando le permitimos a Dios que nos lleve más allá de nosotros mismos para alcanzar nuestro ser más verdadero. Allí está el manantial de la acción evangelizadora. Porque, si alguien ha acogido ese amor que le devuelve el sentido de la vida, ¿cómo puede contener el deseo de comunicarlo a otros?

That assertion can have the function or purpose ascribed to it by Anselm (see above, p.
196)—i.e. that there can be such a thing as assertion—depends on the empirical fact,
among others, that people don’t generally reject their earlier assertions as unfounded.
It is ‘by favour of Nature’ that assertion and knowledge are possible (On Certainty,
para. 505); for Anselm and for Anscombe, it is (also) by the grace of God.



Poned en práctica la palabra y no os contentéis con oírla, engañándoos a vosotros mismos. Porque quien oye la palabra y no la pone en práctica, ese se parece al hombre que se miraba la cara en un espejo y, apenas se miraba, daba media vuelta y se olvidaba de cómo era. Pero el que se concentra en una ley perfecta, la de la libertad, y permanece en ella, no como oyente olvidadizo, sino poniéndola en práctica, ese será dichoso al practicarla. (St 1, 22--25)
#+END_SRC
