#+PROPERTY: header-args:latex :tangle ../../tex/intro/presentacion.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

#+BEGIN_SRC latex
\blockquote[][\,(1 Jn 1-4)]{\emph{Lo que existía desde el principio, lo que hemos oído, lo que hemos visto con nuestros propios ojos, lo que contemplamos y palparon nuestras manos acerca del Verbo de la vida; pues la Vida se hizo visible, y nosotros hemos visto, damos testimonio y os anunciamos la vida eterna que estaba junto al Padre y se nos manifestó. Eso que hemos visto y oído os lo anunciamos, para que estéis en comunión con nosotros y nuestra comunión es con el Padre y con su Hijo Jesucristo. Os escribimos esto, para que nuestro gozo sea completo}}. ¿Quién se comunica en el testimonio al que se refieren estas palabras? Es un anuncio que invita a la comunión, pero nace y se transmite también en comunión. Es así que este testimonio es comunicación que nace en la comunión Trinitaria, es comunicación del Verbo en quien la Vida se hizo visible y es comunicación de \enquote*{los que han contemplado y palpado}: los apóstoles y la Iglesia apostólica.

Esta relación entre participación en la comunión y comunicación de la Verdad es un aspecto de la Revelación que se expresa con fuerza cuando la entendemos como `testimonio'. Igualmente, entender la misión evangelizadora de la Iglesia como `testimonio' de la Verdad y de la Vida, nos deja situados, no solo ante el amor de Dios que se comunica, sino ante sus destinatarios. De este modo, comprender el testimonio de fe que es misión evangelizadora implica considerar al ser humano, su realidad, su lenguaje y actividad, su libertad y su deseo de la verdad. Esta investigación pretende ofrecer una descripción de algunos aspectos de nuestra vida ---del ser humano como destinatario de la Revelación--- desde la filosofía de G.E.M. Anscombe.

Merece la pena conocer la obra de Elizabeth Anscombe. Hay una interesante audacia en su temperamento, método y pensamiento. Su esposo, Peter Geach, decía: \blockquote[{\Cite[11]{geach1991philaut}}: \enquote{As a mature philosopher, Elizabeth strikes me as a more adventurous thinker than I am: it is she who gets bold and at first sight merely zany ideas, to which I sometimes reacted with initial outrage. (Cfr. her papers `The Intentionality of Sensation' and `The First Person') Usually I come to think these bold ideas are more defensible than I had originally supposed}.]{Como una filósofa madura, Elizabeth me parece ser una pensadora más intrépida que yo: es ella quien tiene ideas audaces y que a primera vista resultan meramente alocadas, a lo que en ocasiones he reaccionado con inicial indignación. (Cfr. sus escritos \emph{The Intentionality of Sensation} y \emph{The First Person}) Usualmente llego a pensar que estas audaces ideas son más justificables de lo que originalmente suponía}. Una gran parte de este estudio esta dedicada a presentar el modo en que Anscombe se enfrenta a preguntas particulares y explorar las conexiones que ofrecen sus respuestas a cuestiones que están relacionadas entre sí. Esto con el deseo de conocer un panorama de su pensamiento. El objetivo es dejar vetas abiertas donde su pensamiento pueda representar una aportación al estudio teológico.

El primer capítulo, presenta algunas motivaciones para este estudio y presenta la categoría de testimonio como objeto de estudio teológico sobre la cual se plantean tres cuestiones. El tercer capítulo, expone varias discusiones de la obra de Anscombe en las que se encuentran las premisas fundamentales para argumentar sobre las tres cuestiones planteadas en el primer capítulo. El capítulo segundo presenta a grandes rasgos el perfil biográfico y filosófico de Anscombe, destacando la filosofía de Wittgenstein como trasfondo del método y pensamiento de Elizabeth, además del interés que puede haber en estudiar el testimonio dentro de la filosofía analítica. El último capítulo ofrece valoraciones finales sobre lo que las reflexiones de Elizabeth estudiadas en la investigación pueden aportar en relación con algunas cuestiones dentro del campo de la teología fundamental.
#+END_SRC

The approach:
- From Teichmann
Part of the difficulty on reading Anscombe is her eschewal of system.
A system or theory often makes things easier for the reader. Once you have grasped N's theory, you can frequently infer what N would have to say on some point by simply 'applying' the theory. But it can often be hard to predict in advance what Anscombe will say about some given thing. She is infuriatingly prone to take each case on its merits.

...as such this investigation cannot rely on applying 'Anscombe's Theory' on the category of testimony.

Another reason for the apparent lack of systemacity in Anscombe's writings is due to her purpose of getting somewhere in her own thoughts on some topic; she usually spends little or no time in providing a background, or in justifying her main 'assumptions', prefering to begin in media res These same assumptions may be justified or addressed elsewhere in her ouvre. There are manifold connections between her thoughts on different topics. Such connections do bind Anscombe's thoughts together into a sort of system, but this is not a system concocted so as to be applied to particular problems. Rather it is a system itself constituted by a mature overview of those problems, the result of one mind's having tackled many particular and interrelated questions.

...as such this investigation purports to expose Anscombe's mind tackling particular and interrelated questions regarding topics related to getting to know by testimony.
How do I go by testimony about God? <- what is it to be in front of testimony about
God?

engaging with what Anscombe says, as opposed to merely expounding on it entails putting forward possible objections and counter-arguments, and developing or applying her ideas beyond the limits of her original discussions.

...as such this investigation is an engagement with Anscombe's writings. Developing and applying her ideas on the topic of testimony

- From my own expreience.

Stuff related to knowledge, perception, belief, mystery, etc. relies upon
wittgenstenian notions, practices and propositions.

... as such this investigation has to show Wittgenstein's way of soing philosophy as a
backdrop to what Anscombe does.
