#+PROPERTY: header-args:latex :tangle ../../tex/intro/presentacion.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

#+BEGIN_SRC latex
Lo que existía desde el principio, lo que hemos oído, lo que hemos visto con nuestros propios ojos, lo que contemplamos y palparon nuestras manos acerca del Verbo de la vida; pues la Vida se hizo visible, y nosotros hemos visto, damos testimonio y os anunciamos la vida eterna que estaba junto al Padre y se nos manifestó. 3 Eso que hemos visto y oído os lo anunciamos, para que estéis en comunión con nosotros y nuestra comunión es con el Padre y con su Hijo Jesucristo. Os escribimos esto, para que nuestro gozo sea completo. (1 Jn 1--4)
#+END_SRC

The approach:

- From Teichmann
Part of the difficulty on reading Anscombe is her eschewal of system.
A system or theory often makes things easier for the reader. Once you have grasped N's
theory, you can frequently infer what N would have to say on some point by simply
'applying' the theory. But it can often be hard to predict in advance what Anscombe
will say about some given thing. She is infuriatingly prone to take each case on its
merits.

...as such this investigation cannot rely on applying 'Anscombe's Theory' on the
category of testimony.

Another reason for the apparent lack of systemacity in Anscombe's writings is due to
her purpose of getting somewhere in her own thoughts on some topic; she usually spends
little or no time in providing a background, or in justifying her main 'assumptions',
prefering to begin in media res
These same assumptions may be justified or addressed elsewhere in her ouvre. There are
manifold connections between her thoughts on different topics. Such connections do bind
Anscombe's thoughts together into a sort of system, but this is not a system concocted
so as to be applied to particular problems. Rather it is a system itself constituted by
a mature overview of those problems, the result of one mind's having tackled many
particular and interrelated questions.

...as such this investigation purports to expose Anscombe's mind tackling particular
and interrelated questions regarding topics related to getting to know by testimony.
How do I go by testimony about God? <- what is it to be in front of testimony about
God?

engaging with what Anscombe says, as opposed to merely expounding on it entails putting
forward possible objections and counter-arguments, and developing or applying her ideas
beyond the limits of her original discussions.

...as such this investigation is an engagement with Anscombe's writings. Developing
and applying her ideas on the topic of testimony

- From my own expreience.

Stuff related to knowledge, perception, belief, mystery, etc. relies upon
wittgenstenian notions, practices and propositions.

... as such this investigation has to show Wittgenstein's way of soing philosophy as a
backdrop to what Anscombe does.
