* By Collections
** Collected Philosophical Papers
***   I: From Parmenides to Wittgenstein
**** _Parmenides, Mystery and Contradiction_ (1969) :testimony:mystery:
**** +The Early Theory of Forms (1981)+
**** +The New Theory of Forms (1966)+
**** +Understanding Proofs (1979)+
**** Aristotle and the Sea Battle (1956) :testimony:prophecy_miracles:
    - It is necessary: given an antiphasis about the present or the past, the
      affirmative proposition must be true or false; and similarly for the negative.
      + antiphasis :: a pair of propositions in which the same predicate is in one
                      affirmed, in the other denied, on the same subject
    - Aristotle's point is that "Either p or not p" is always necessary; *this
      necessity we are familiar with*.
    - What is a *novelty* is that when p describes a present or past situation, then
      either p is necessarily true, or ~p is necessarily true; and here "necessarily
      true" has a sense which is unfamiliar to us:
      + "necessarily true" is not simply the same as "true"
      + about something that would happen tomorrow, everyone would say: "there may be
        or may not"
      + we also say this about things which we don't know about the past and the
        present
      + does "may" express mere ignorance on our part in both cases?
      + logical necessity
**** +The Principle of Individuation (1953)+
**** Thought and Action in Aristotle: What is practical truth? (1965) :practical_truth:
     - The notion of truth or flasehood in action would quite generally be countered by
       the objection that "true" and "false" are senseles predicates as applied to what
       is done. If I am right there is philosophy to the contrary in Aristotle. And if,
       as I should maintain, the idea of descriptions under which what is done is
       voluntary is integral to his notion of action, then these predicates apply to
       actions stictly and properly, and not merely by an extension and in a way that
       ought to be explained away.
**** Necessity and Truth (1965) :necessarily_true:
     - The sorting out by Aquinas of the de re and the de dicto necessities confounded
       in 'what is known is necessarily true' is something a present-day English
       philosopher can appreciate.
**** _Hume and Julius Caesar_ (1973) :testimony:causality:reality_past:
     - But here it seems that she is arguing that the standard Humean
       foundationalist-evidentialist epistemology won't work, and also that coherentism
       won't work (at least if coherentism is supposed to imply that absolutely any
       belief we have can, in principle, be doubted and examined without threatening
       the whole structure of our web of beliefs). This is, at least for its time, a
       rather radical claim, since for a while it seemed that one must either be a
       foundationalist or a coherentist about epistemic justification. What is this
       third way that is needed to account for our knowledge of history (or
       justification of our beliefs regarding historical matters of fact)?
**** Whatever has a beginning... must have a cause (1974) :causality:
     - Hume gives an argument to show that a beginning of existence without a cause is
       not demonstrably absurd
       - It's an argument from imagination
       - we may grant the Parmenidean principle that "It is the same thing that can be
         thought and can be"
       - Hume's extension of it is certainly wrong
**** Will and Emotion (1978) :belief:practical_truth:
     - Will and emotion don't 'take' propositional objects, but involve desires which
       do; this Brentano got right in assimilating will and emotion
     - Anscombe opposes the assimilation
     - Belief is as it's objects are (p.103)
     - Is an error to assimilate will and emotion, a confusion of radically diferent
       kinds of thing, of elements in a flow of feelings with the voluntariness of an
       act. It's like identifying hunger with the voluntariness of eating.
     - There is an element of 'what for' present in the description of a voluntary act
       (will) that belongs to the intelligence of the agent.
     - It takes human intelligence to be an akolastos in Aristotle's sense and take an
       appetite and make it one's goal.
**** +Retractation (1965)+
**** _The Question of Linguistic Idealism (1976)_  :mystery:
     - This can be disproved but I still believe it is not an attitude of faith at all
***  II: Metaphysics and the Philosophy of the Mind
**** The Intentionality of Sensation, A Grammatical Feature :intentional_object:
     - Intentionality has been defined as a feature of certain verbs
     - An intentional object is the direct object of an intentional verb acting as an
       intentional verb
     - worship is an intentional verb
     - Just as 'direct object' is not the name of a kind of thing, neither is
       'intentional object' (since intentional objects are a species of direct objects)
     - An intentional object is given by a word or phrase which gives a description
       under which
**** +The First Person+
**** +Substance+
**** +The Subjectivity of Sensation+
**** +Events in the Mind+
**** +Comments on Gregory's on Perception+
**** +On Sensations of Position+
**** Intention ??
**** Pretending ??
     - Contrast between mock performances, plain pretence, hypocrytical pretence
**** On the Grammar of Enjoy
     - Here she is interested in the characterization of predicative connection
     - non-predicative connection of words
     - what does the verb to enjoy take?
     - belief takes a proposition
     - I am saying that a predicative connection of expressions is just the sort of
       connection into which we introduce negative signs and quantifying applicatives,
       and which we combine with others by truth-connectives
     - Is she reevaluating predicative connection?
**** The Reality of the Past
**** Memory, 'Experience' and Causation
**** +Causality and Determination+
**** +Time, Beginnings and Causes+
**** +Soft Determinism+
**** +Causality and Extensionality+
**** +Before and After+
**** +Subjunctive Conditionals+
**** "Under a Description"
     - theory of event identity
**** +Analysis Competition - Tenth Problem+
**** +A Reply to Mr C. S. Lewis's Argument+
*** III: Ethics, Religion and Politics
**** +The two kinds of error in action+
**** On promising and its justice
     - language game descrption p. 16-17
     - Those whose reactions show that for them the principle operates as an axiom
       appear either
       - to be making morality itself their substantive aim
       - testifying that there is a substantive good **
**** +On Brute facts+
     - Certain facts besides relations of ideas or statements of matter of fact
**** +Modern Moral Philosophy+
     - [Hume's] considerations constantly open up very deep and important problems
**** Authority in Morals
     - Be doers of the word and not hearers only
     - analogy: teaching morals like teaching mathematics
     - some truths about what is the case are revealed
**** War and Murder
     - It is not a vague faith in the triumph of the spirit over force, but a definite
       faith in the divine promises, that makes us believe that the church cannot fail.
**** +Mr Truman's Degree+
**** +The Justice of the present war examined+
**** +You can have sex without children+
**** Rules, Rights and promises
     - God himself can make no promises to man except in human language
     - Hume: Promises are naturally unintelligible, Anscombe: musts and cant's (as
       expressions of rules) are not naturally unintelligible, they can be understood
       by those of normal intelligence as they are trained in the practices of reason
**** _On Transubstantiation_
**** _Faith_
**** +On Frustration of the majority+
**** +On the source of authority of the state+
** St. Andrews Collection
*** Logic Truth and Meaning
**** Belief and Thought
**** Grounds of Belief
**** Motives for beliefs of all sorts
**** Thought and existent objects
**** Knowledge and Essence
**** Grammar, Structure and Essence
**** Private Ostensive Definition
**** Kripke on Rules and Private Language
**** Truth, sense and assertion
**** 'Making True'
**** Existence and truth
**** Existence and the existencial quantfier
**** On a queer pattern of argument
* análisis diacrónico
** [1973] Hume an Julius Caesar
** [1979] What is it to believe someone?
** [] The reality of the past
*** cpp II: p. 118:
so far i have spoken only of that use of the past tense in which a witness reports what
he has witnessed.
we also receive and use testimony, tell and hear stories, make deductions and guesses,
use unfullfilable past conditional sentences, express wishes about the past, make
historical statements and investigations.

If we were to describe the uses of words made in these cases, our descriptions would
all lack one particular feature. The descriptions would not in these cases include any
mention of actual events corresponding to the
* análisis sincrónico
Hume and Julius Caesar 73 > Faith 75 > What is it to Believe Someone 79

Parmenides Mystery and Contradiction 69 > On transubstantiation 74 > The Question of
linguistic Idealism 76
* Points
** Common Knowledge
semantic justification = justification that attaches to a correct use of language
epistemic justification = justifiaction that attaches as such to telling the truth

That these two kinds of justification are more closely related than might be thought is
a theme that appears in some of Wittgenstein’s most searching and radical later
writings, notably in Remarks on the Foundations of Mathematics and On Certainty.
Wittgenstein invites us to view the rules governing the correct use of words as
comparable to the rules governing the acceptance or rejection of beliefs (which are
themselves of course paradigmatically expressed in words); a ‘world view’ is determined
as much by our language and its attendant conceptual scheme as by what we would
ordinarily term our knowledge of things.

immovable foundations
world-picture

hinge propositions

in a world-view to believe is not to surmise
in a religious belief to believe is not to surmise
a world-view and a religious belief are not the same

In grounds of belief she makes a distintion between tradition or common knowledge and
testimony, arguing that things justified on being thaught are justified on something
thicker than testimony. Tradition or common knowledge is described by her as being
thaught to join in doing something, not to believe something. But because everyone is
taught to do such things, an object of belief is generated. The belief is so certainly
correct (for it follows the practice) that it is knowledge.
_Here knowledge is no other than certainly correct belief in pursuit of a practice. But
the connection with testimony is remote and indirect._


What is it to believe someone ends with the problem about the priority of rightness and
truthfulness, this connects with the idea of anselm and anscombe that a true
proposition is doing what it ought

teichmann touches this in p 223

That assertion can have the function or purpose ascribed to it by Anselm (see above, p.
196)—i.e. that there can be such a thing as assertion—depends on the empirical fact,
among others, that people don’t generally reject their earlier assertions as unfounded.
It is ‘by favour of Nature’ that assertion and knowledge are possible (On Certainty,
para. 505); for Anselm and for Anscombe, it is (also) by the grace of God.

it is not experiencing pain that gives you the meaning of the word 'pain'. How could an
experience dictate the grammar of a word? ... The word is not just a response to that
experience at that time: what else is the word to apply to? The experience can't
dictate what is to be put together with it. qli 114

The question of what the inner life is, Wittgenstein insists, is no to be settled by
ostensive definition, or by description of any interior qoings-on, neither for the
subject nor for the observer. The answer lies in attending to the kind of things that
we are permittted to say about these matters, by the rules of the conversation. The
kind of object that a thing is comes out in the kinds of things that it is appropriate
to say about it. This evidently goes for God as much as for imagination. Theology after
Witt 146

** Divine attestation
En prophecy and miracles Anscombe destaca la propuesta de Vaticano I acerca de los
argumentos externos.
Al tener esto en cuenta, lanza la pregunta: Esto podría ser tomado como materia de fe,
¿Pero si aquello que constituye atestación divina puede ser conocido solo por la fe, en
que queda lo que dice el concilio?

lo primero es que un "historiador apático" no podría aceptar el rol de los milagros
como hechos ciertamente verdaderos, no sería razonable pedir al historiador apático que
resuelva el problema de cómo han llegado a quedar escritos estos relatos.

Una persona que haya tomado como maestro el AT, para alguien así sí que tendría peso
las profecías cumplidas o los milagros

Para Anscombe debe haber una tesis de teología natural que afirme qué implica que una
persona está divinamente atestada

Esta tesis no tiene que ser materia de fe

El argumento puede ser que si no queda probado presuntuoso entonces no podriamos no
obedecerle

pero no basta un motivo negativo

puede uno creer porque no tiene signos de que este hombre sea presuntuoso?
y entonces hay que considerar que una de dos o es presuntuoso o lo que dice viene de
Dios? y entonces como no hay signos de que sea presuntuoso, pues viene de Dios?

Seguramente querríamos razones positivas para creer, y no meramente ausencia de razón
positiva para descreer?

Esto, me parece, es correcto, y va con la tesis de que en cierto sentido no puede haber
un profeta con una nueva doctrina.

Con estas cosas y lo que dice en 'faith' se podría construir una descripción de lo que
Anscombe considera como atestación divina




* Hume on miracles
el hecho que el testimonio intenta establecer, si tiene que ver con algo
extraordinario, en ese caso la evidencia, resultante del testimonio, admite una
disminución, mayor o menor, en proporción a si el dato más o menos inusual

concluye, en consecusión con este principio, que ha de rechazarse todo testimonio de
milagros, ya que ninguno es suficiente para establecer un milagro, excepto si su
falsedad fuera más milagrosa que el hecho que se esfuerza por establecer

Está de acuerdo con teoria de probabilidad y es intuitivamente aceptable que
si, por ejemplo, según nuestra información de trasfondo, la probabilidad de un
terremoto en españa es menor que la probabilidad de un informe mentiroso en el
periódico el próximo día, entonces la probabilidad de que haya ocurrido, incluso si lo
leemos en el periódico de hoy, es menor que 1/2

El argumento de que mientras más improbable el evento, menos peso tiene el testimonio
es consono.
Pero no necesitábamos este argumento si un evento es de un tipo que no tiene
probabilidad finita, es decir, es imposible. Entonces el testimonio no tiene ningún
peso. No añade a la probabilidad nada.

comenzando con:
un hombre sabio ajusta sus creencias a las evidencias
y termina diciendo:
un hombre sabio no necesita considerar para nada este tipo de evidencia
El curso del argumento de Hume sólo puede ser razonable si
se considera que el testimonio no puede añadir nada a la probabilidad del hecho

el no-ocurrir del evento más testimonio es más probable que
el sí-ocurrir del evento más testimonio
si
el testimonio falso sobre el hecho es más probable que el hecho

la falsedad del testimonio tiene que ser más improbable que el milagro, si ha de ser
considerado el testimonio.

Un argumento de este tipo, para mostrar que ningún testimonio puede tener algún peso,
tiene que ser falaz si se concede la probabilidad finita;

pues la proporción de la probabilidad de que el evento será narrado si ha ocurrido

(casi cierto para algunos eventos de naturaleza extraordinaria, si han ocurrido
públicamente)

a la probabilidad de que, si no ha ocurrido, que se invente esa mentira particular
puede ser alta.

Es en esta proporción que
las probabilidades consecuentes (despúes del testimonio)
exceden las las probabilidades antecedentes en favor del evento.

* Hume and Julius Caesar
**** sofisma
**** cuestión interesante
 ¿por qué las cosas que se nos dicen y los escritos que vemos son puntos de partida
 para nuestro creer en eventos distantes y así también en la cadena del relato
 intermedia?

Es bien difícil caracterizar la solidez peculiar [relacionada con un conocimiento que
cuenta con este grado de certeza] o sus límites
conocemos sobre César por el testimonio de los antiguos historiadores y hasta tenemos
sus propios escritos
y cómo sabes *eso*, que esos son historiadores antiguos y estos escritos de Julio
Cesar?
te lo dijeron.
y como lo saben tus maestros?
se lo dijeron

Lo sabemos porque nos han enseñado
no solo por enseñanza explícita,
sino por estar implicito en mucho que se nos ha enseñado explicitamente.
Pero es bien dificil ...
es dificil caracterizar la solidez peculiar o los limites que pueda tener
una enseñanza transmitida con el status logico tan  particular
con un particular status lógico de un tipo de certeza
