* Fase 1: Presentación Inicial [50%]
- [X] Un título preciso.
  - La Categoría del Testimonio en el pensamiento de Elizabeth Anscombe. Un estudio en perspectiva teológico-fundamental.
- [ ] Una Introducción con tres apartados:
  - [ ] Motivación personal.
  - [ ] Objetivo de la tesina.
  - [ ] Fuentes básicas y bibliografía elemental que se van a consultar.
- [ ]Un índice elemental.
(Aquí debe haber una segunda entrevista con el Director, para aprobar el plan).

* Fase 2: Fuentes Primarias [%]
- [ ] Recopilar las fuentes primarias escritas, si es posible, en su idioma original.

* Fase 3: Fuentes Secundarias [%]
- [ ] Recopilar fuentes secundarias: escritos y comentarios sobre las fuentes primarias, hechos por otros autores.

* Fase 4: Precisión de la Introducción y esquema de los capítulos [%]
- [ ] Tras una primera lectura, deberá elaborar de manera más precisa la introducción y un esquema de los capítulos previstos (presentar al Director).

* Fase 5: Lectura y desarrollo de esquema detallado, notas y bibliografía [%]
- [ ] Lectura ordenada, orientada a cada capítulo, sobre un esquema detallado del mismo: notas y bibliografía 
(presentar al Director).

* Fase 6: Redacción y correcciones [%]
- [ ] Redacción y presentación del trabajo realizado al Director para su corrección y aprobación.

* Fase 7: Redacción Definitiva [%]
- [ ] Redacción definitiva.
