* Belief and thought 
** assertion
 | decision  | Act of Assent |
 | Intention | Belief        |

 I suddenly believed would mean I suddenly inwardly assented


 at this point we seem to have 2 candidates for the role of initiation act of a
 disposition which is a belief that p

 1. an /occurrent thought/ that /p/ or that /'p'/ is true
 2. an inward assent 

 if both these exist there is no difficulty: sometimes one, sometimes the other might
 perform this role.


 Let's address the question of assent

 assent from one person to a proposition formulated by another gives us the picture of 2
 procedures: 
 a. the formulation of something assertible --what frege calls judgeable content
 b. the assent to, or inward assertion of, that content

 with this picture in mind it would seem natural to take a view as follows:

 to think has 2 broadly distinct senses:
 1. think is roughly equivalent to 'believe' (or, in appropiate contexts, 'intend')
 2. to have intelligible content before one's mind

 an often dispositional application
 being used in the first sense:
 when a report of thinking implies that the thinker believes what he is thinking

 refers to an episode
 being used in the second sense:
 I suddenly believed him
 or
 just for a moment i thought that...

 the definition of belief as thought plus assent does have some application, but only to
 a restricted range of cases

 it has to be rejected as a general definition because one doesn't have to be thniking
 what one believes

** 'Voicers'
Let's use a new term for 
all these first person present indicatives 
which form 
such 'sustaining frameworks' in our utterances

i will call them 'voicers' for they stand in a special relation to the voicings of our
beliefs and our -various- thoughts.

a voicer is not a performative, though it does share some of the peculiarities of a
performative.

In particular, no voicer is an assertion 
* Grounds of belief

** 
*Belief on grounds which can be considered as premises for arguments presupposes belief
without grounds, or at any rate without grounds that can be so considered*

Hume's philosophical opinion was that these ultimate groundless grounds were sense
impressions. 

But I say that they are such beliefs as those of which one will say 'Everyones knows
that!' <- 
there are grounds, premises for arguments, which are not sense impressions, but 
traditional knowledge or common knowledge or pieces of traditional knowledge


** 

I can obtain an experience which, in view of what I have learned, I shall with
certainty call seeing the present Pope;

i can not optain any experience which I can call seeing Alexander Borgia

BUT
that will not make me any better placed for the rationality
of my belief that there is such a person 
as the present pope, than for the rationality of my belief that there was such a person
as Alexander Borgia

MY KNOWLEDGE OF THE THINGS AMONG WHICH AND THE PLACES IN WHICH I LIVE IS NOT SO MUCH
THEORY LADEN, AS COMMON-KNOWLEDGE LADEN

** 
 it's a falsification here to speak of testimony:
 to say that it is by testimony that i know that i was born

 there is something else, not testimony, though acquired by education from human beings,
 which is, so to speak, /thicker/ than testimony.


 The work of determining England and fixing the meaning of the name /would/ depend on
 testimony 
 -the testimony of many different people for different parts of it

 the work done, people could be taught what England was (no doubt still disputing some
 regions).

 Now those who learned thereafter can hardly be said to have knowledge by testimony.

 They were taught to call something England.

 Something indeed which could in large part only be defined for them by hearsay;
 and they so taught those who came after them 

 i am an heir of this tradition 

 i would be queer to say i know this by testimony

 it is rather as if i had been taught to join in doing something, than to believe
 something 

 -but because everyone is taught to do such things, an object of belief is generated

 the belief is so certainly correct (for it follows the practice)
 that it is knowledge; for here knowledge is no other than certainly correct belief in
 pursuit of a practice

 but the connection with testimony is remote and indirect


* Hume and Julius Caesar (1973)
Section IV part III of Book I of the treatise

Topic: belief in matters falling outside our own experience and memory

when infering effects from causes
we must establish the existence of these causes
either by:
 
inmediate perception of our memory or senses

or by

 an inference from other causes

these other causes must be ascertained in the same manner

it is impossible to carry on our inferences in infinitum

Hume tries to ilustrate this by an example of historical belief 

we believe that caesar was killed....

it is obvious all this chain of argument or connexion of causes and effects is at first
founded on those characters or letters which are seen or remembered 

But this is not infering effects from causes, it is infering causes from effects.

As such, fo an historical belief we must have to saying
when we infer effects fromo causes or causes from effects...

when we infer causes from effects we must establish the existence of those effects
either by perception or by inference from other effects which effects we must ascertain
in the same manner by a present impression or by an inference from their effects and so
on, until we arrive at an object which we see or remember



For Hume the relation of cause and effect is the one bridge by which to reach belief in
matters beyond our present impressions or memories

and also cause and effect are inferentially symmetrical

are they?

what is the starting point? (the start of inference or the start of the justification
chain) 



The historical example is an inference of the original cause, the killing of Caesar,
from its remote effect, the present perception of certain characters or letters.

The starting-point is the present perception, and from it we can run through a chain of
effects of causes which are effects of causes to the original cause: the killing of
Caesar

the end of the chain is thus not our perception and so it doesn't serve as an
impression of our memory or senses beyond which there is no room for doubt or enquiry
as to stop us going infinitely

"tis impossible for us to carry on our inference in infinitum" means: *the
justification of the grounds of our inferences cannot go on in infinitum* *we must come
to belief which we do not base on grounds*

What Hume is arguing is that we not only have a perception starting point but that we
must reach a starting point in the justification of these inferences

for him tracing back (from effects to causes) is taken to be symmetrical to inferences
from causes to effects

it must be purely hypothetical inference

we reason (purely hypothetically) if Caesar was killed, then there were witnesses , if
there were witnesses then there was testimonies, then there were records made from
them, if there were records made then there are characters and letters to be seen which
say that Caesar was Killed

Four parts of Hume's thesis:

1. a chain of reasons for a belief must terminate in something that is believed without
   being founded on anything else
2. the ultimate belief must be of a quite different character from derived beliefs: it
   must be perceptual belief, belief in something perceived, or presently remembered
3. the immediate justification for a belief p, if the belief is not a perception, will
   be another belief q, which follows from, just as much as it implies, p.
4. we believe by inference through the links in a chain of record

implicit corollary: when we believe in historical information belonging to the remote
past, we believe that there has been a chain of record

Hume must believe all this

*But it is not like that!*


If the written records that we now see are grounds of our belief, they are first and
foremost 

*grounds for belief*
in Caesar's killing,
belief that the assasination is a solid bit of history

THEN

our belief in that original event IS A GROUND FOR BELIEF in 

much of the intermediate transmission <-



belief in recorded history is on the whole a belief that there has been a chain of
tradition of reports and records going back to contemporary knowledge;

IT IS NOT A BELIEF IN THE HISTORICAL FACTS BY AN INFERENCE THAT PASSES THROUGH THE
LINKS OF SUCH A CHAIN. AT MOST, THAT CAN VERY SELDOM BE THE CASE.

Casting a doubt about Caesar's existence would put us in a vacuum in which there is
nothing by which to judge anything else

What would I be allowed to count as evidence then?

PEOPLE IN HISTORY ARE NOT IN ANY CASE HYPOTHESES WHICH WE HAVE ARRIVED AT TO EXPLAIN
CERTAIN PHENOMENA

A general epistemological reason for duobting one will be a reason for doubting all,
and then none of them would have anythin to test it by

* Motives for beliefs of all sorts

What is a motive?

It wouldn't ordinarily be called a motive; 

the term motive seems to be restricted to passions or objects

but if

by motive we mean what prompts one 

what is one's ground for doing or omitting anything, then "Someone told me" may well be 
said to give me a motive

wether or not it gives a ground for the belief, or gives my ground for the belief, it
does give my ground for doing something -namely believing

this should be called a motive

grounds for believing, this is motive (what prompts me)

grounds for a belief  is not the same as grounds for believing


* Knowledge and Essence (1989)

My objetivo principal es señalar la gran importancia del pensamiento del Tractatus de
que la teoría del conocimiento es filosofía de la psicología.

La importancia es para la historia de la filosofía en el sentido de la historia del
pensamiento filosófico.

No se cuanto ha sido notado, pero aquí, en esta afirmación, 'La teoría del conocimiento
es filosofía de la psicología' un corte queda hecho. 

Durante varios siglos la teoríá del conocimiento había sido lo que la metafísica había
sido antes de ellas. Había llegado a ser la teoría de la esencia del mundo, de los
componentes definitivos del universo. Esta corriente empezo a venir con Descartes, si
él se ganó el título 'el padre de la filosofía moderna'. Las olas llegaron a su máxima
altitud con declaración de Kant de haber hecho una revolución Copernicana. 

La posición suprema de la teoría del conocimiento estaba garantizada mucho antes que
Kant y se mantuvo incluso entre filósofos como Bertrand Russell que abobinaba  a Kant.

Todavía estaba operativa en Wittgenstein a pesar de su afirmación en el Tractatus.
En "Philosophical Remarks" encontramos la observación: Una proposición es borrador
sobre una verificación.

Se le podría dar una interpretación inocente a esta observación si se le asocia con
Tractatus 4.063:
para ser capaz de decir: '"p" es verdadero (o falso)', debo haber determinado en qué
circunstancias llamo a 'p' verdadero, y haciendo esto determino el sentido de la
proposición

Pero aquí también nos recordamos que la explicación llega a su fin y nos preguntamos si
el determinar del que habla es un determinar por proposiciones adicionales que
describan las circunstancias en las que llamo a una proposición verdadera.

Ciertamente hemos de pensar que no, pues de otro modo la explicación no llegará a su
fin o habrá una invocación de la experiencia con la que si se llega al fin. 

Esta última puede estar bien pero no consistirá en una descripción de las
circunstancias en las que llamo 'p' verdadero -- no si esa descripción misma tiene que
tener su sentido indicado por una ulterior descripción del mismo tipo. 

A la luz del pensamiento más tardío, podriamos hablar de la experiencia en cuestión
como la de aprender un lenguaje.
...


Las indagaciones interesantes sobre el conocimiento, 

una vez que se ha abandonado el
intento de caracterizarlo como un tipo de creer que satisface ciertas condiciones,

conciernen lo que todos, o todos en ciertas culturas, puede ser asumido que conocen una
vez que han crecido y son razonablemente competentes; 

y la relación de algunas afirmaciones de conocer con preguntas como ¿cómo lo sabes
(know)?





---
a grammatical imposibility describes the bounds of sense
an epistemic imposibility defines the bounds of knowledge

I am in pain is the expression of a sensation

not a description based on internal or external criteria

