#+PROPERTY: header-args:latex :tangle ../../tex/ch3/beliefanditsstructure.tex

+BEGIN_SRC latex
\section{Acerca del creer y su estructura}
+END_SRC
* Qué es creer a alguien?
** Quaestio: Acerca de un Peculiar Patrón de Argumento
 #+BEGIN_SRC latex
   \subsection{Un Peculiar Patrón de Argumento.}
   Peter Geach dedica un breve apartado a Anscombe en su ``Autobiografía
   Filosófica''. Ambos se dedicaban a la filosofía y era común que cuestionaran a
   uno sobre el pensamiento del otro, sin embargo no era raro que no supieran cómo
   contestar. Los dos tenían distintos intereses en sus investigaciones y tambíen
   un estilo diferente al acercarse a los problemas filosóficos. Geach lo describe
   así: \citalitlar{Como una filósofa madura, Elizabeth me parece ser una pensadora
     más intrépida que yo: es ella quien tiene ideas audaces y que a primera vista
     resultan meramente alocadas, a lo que en ocasiones he reaccionado con inicial
     indignación. (Cfr. sus escritos \emph{The Intentionality of Sensation} y
     \emph{The First Person}) Usualmente llego a pensar que estas audaces ideas son
     más justificables de lo que originalmente
     suponía\footnote{\cite[11]{geach1991philaut}: <<As a mature philosopher,
       Elizabeth strikes me as a more adventurous thinker than I am: it is she who
       gets bold and at first sight merely zany ideas, to which I sometimes reacted
       with initial outrage. (Cfr. her papers `The Intentionality of Sensation' and
       `The First Person') Usually I come to think these bold ideas are more
       defensible than I had originally supposed.>>}.} El mismo libro que recoge
   estas memorias de Geach contiene un breve artículo de Elizabeth titulado
   \emph{On a Queer Pattern of Argument}\footnote{\cite{anscombe1991aqp} En
     adelante la referencia al artículo será como aparece en:
     \cite{anscombe2015logic:qpa}} que ejemplifica adecudamente las palabras antes
   referidas sobre su esposa.

   En esta ocasión la consideración intrépida consitirá en indagar sobre la validez
   de principios lógicos familiares aplicándolos a diversos ejemplos de
   argumentaciones. El extraño patrón de argumento que da título a la investigación
   queda expresado de este modo:
     \begin{adjustwidth}{1.2cm}{}
       1.\hspace{.459cm}Si $p$, entonces $q$.\\
       2.\hspace{.459cm}Si $r$, entonces no (si $p$ entonces $q$).\\
       3.\hspace{.459cm}Si no $p$ entonces $r$.\\
       $\therefore$\hspace{.459cm}$p$ y $q$.
     \end{adjustwidth}

     Se obtiene `no $r$' de las primeras dos premisas y entonces `$p$' de `no $r$'
     y la tercera premisa; con la primera premisa nuevamente y `$p$' obtenemos la
     conclusión.{\footnote{\cite[299]{anscombe2015logic:qpa} <<We get `not $r$'
         from the first two premises and then `$p$' from `not $r$' and the third;
         with the first one again this gives us the conclusion>>.}} Hecha esta
     descripción, Anscombe entonces invita a considerar el siguiente argumento
     construido según el patrón anterior:
     \begin{adjustwidth}{1.2cm}{}
       1.\hspace{.459cm}Si ese árbol cae, entonces interrumpirá el paso por el camino
       durante mucho tiempo.\\
       2.\hspace{.459cm}Eso no es verdad si hay una máquina para remover árboles
       funcionando.\\
       3.\hspace{.459cm}Si el árbol no cae, habrá una máquina para remover árboles
       funcionando.\\
       $\therefore$\hspace{.459cm}El árbol caerá e interrumpirá el paso por el camino
       durante mucho tiempo.
     \end{adjustwidth}

     ¿Qué resultado se obtiene si se intenta formar un juicio razonable o
     conocimiento desde este argumento? <<Si ese árbol cae entonces interrumpirá el
     camino y si hay una maquina para remover árboles funcionando entonces no será
     verdad que si el árbol cae entonces interrumpira el camino.>> (`Si $p$
     entonces $q$ y si $r$ entonces no [si $p$ entonces $q$]'). De esta conjunción
     se sigue `no habrá una maquina para remover árboles funcionando' (`no $r$'),
     pero ¿se podría considerar esta deducción un juicio razonable?. La segunda
     premisa se lee como arrojando duda sobre la primera, y la tercera premisa
     expresa la pertinencia de la segunda. Descartar la duda y afirmar la primera
     sugiere que ya se cree la primera premisa antes de evaluar la segunda. Pero en
     ese caso el argumento mismo no explicaría los fundamentos para la conclusión.
     Aún cuando se estuviera asintiendo a las otras dos premisas porque ya se cree
     la primera, estas trabajan junto a un hipotético para sostener la
     creencia\autocite[Cf.~][300]{anscombe2015logic:qpa}.

     Anscombe entonces propone: \citalitinterlin{Si todo esto es correcto, tenemos
       aquí un caso bastante interesante de una serie de proposiciones que implican
       una conclusión pero no son fundamentos posibles para llegar a esa
       conclusión}\footnote{\cite[300]{anscombe2015logic:qpa} <<If all this is
       right, we have here a rather interesting case of a set of propositions which
       entail a conclusion but are impossible grounds for coming to that
       conclusion>>}. El argumento no necesita que se juzgue como verdadera la
     conclusión o parte de ella para considerar verdadera alguna de las premisas,
     pero sí reclama que parte de la conclusión sea fundamento para aceptar la
     combinación de las premisas de modo que se pueda formar conocimiento o un
     juicio razonable\footnote{\cite[Cf.~][301]{anscombe2015logic:qpa}}.

     En este caso `$q$' no se sigue necesariamente de `$p$' y así, al no ser una
     verdad necesaria, sólo se puede aceptar la conjunción de las primeras dos
     premisas si se está independientemente seguro de que `no $r$'. No es común que
     estemos en la situación de pensar que `si $p$ entonces $q$' y que sólo por eso
     esté claro que `si $r$ entonces no (si $p$ entonces $q$)' y entonces poder
     deducir razonablemente de esto que `no $r$'. Es más común que al juzgar la
     conjunción de las primeras dos premisas, el antecedente de la segunda pierda
     fuerza. El punto de la segunda premisa es arrojar duda sobre la primera; la
     conjunción de la segunda premisa y la tercera refuerzan la pertinencia de la
     segunda. Sin embargo la segunda premisa sólo tendrá la fuerza de poner en duda
     la primera premisa ---y no al revés--- si, además de ser verdadera y
     pertinente, resulta imposible de descartar porque resulta necesario tomar en
     serio su antecedente `si $r$'\autocite[Cf.~][301]{anscombe2015logic:qpa}.

     Anscombe acuña la expresión `revocabilidad
     esencial'\footnote{\cite[Cf.~][301]{anscombe2015logic:qpa}: <<Then we have
       perhaps discovered the special character of (theoretical) hypotheticals
       whose consquents don't follow logically from their antecedents. We might
       call this character `essential defeasibility'>>.} para denominar al carácter
     especial de hipotéticos teoréticos cuyos consecuentes no se siguen lógicamente
     de sus antecedentes. En este caso esta característica es la que hace que
     incluso cuando `no $r$' se sigue de `si $p$ entonces $q$ y si $r$, entonces no
     (si $p$ entonces $q$)', no sería razonable deducir `no $r$' de esa conjunción.
     Elizabeth además observa que hay un gran número de juicios que son así. Al
     hacer una afirmación categórica con la seguridad apropiada, frecuentemente se
     descarta inmediatamente lo que la falsificaría sólo porque se sabe que ésta es
     verdadera. Sin embargo existe toda una clase de juicios como el que se ha
     analizado que al ser hechos no se descarta implicitamente como falso todo lo
     que los falsificaría\autocite[Cf.~][302]{anscombe2015logic:qpa}.
 #+END_SRC
*** ramble bramble mumble
 que puedas sacar esta conclusion de estas tres premisas es fundamento para
  dudar de la conjunción de las tres

  la razón no es que la conclusion sea falsa o absurda
  es una proposición perfectamente posible
  y
  es objetada solo como una conclusión de proposiciones perfectamente posibles,
  que son mutuamente compatibles y de las que si se sigue

  se puede objetar la conclusión, no porque sea falsa o absurda, sino
  que se objeta como la conclusion de estas proposiciones que sí son posibles y
  compatibles y de las cuales si se sigue.

  de donde sacas esa conclusión?
  se sigue de las premisas
  no lo creo
  por qué?

  q no se sigue de p, no es una verdad necesaria
  entonces si q no se sigue necesariamente de p
  sólo puedo aceptar la conjunción de 1 y 2 si estoy independientemente seguro
  de que no r

 las circunstancias son raras en las que puedo decir que si p entonces q y sólo
 por eso que sea claro que si r, entonces no (si p entonces q) y uno puede
 deducir que no r

 Por lo regular cuando se juzga si p entonces q es fácil aceptar cualquier
 antecedente en la segunda premisa sin que este perturbe realmente la creencia
 de que si p entonces q

 sin embargo el punto de que exista la segunda premisa es exactamente arrojar
 duda sobre la primera

 la pertinencia de esa duda parece depender de las circunstancias

 se puede pensar en una manera de discutir el asunto fuera de la influencia de algún contexto
 específico?

 Pero tenemos una tercera premisa que es perfectamente posible y hace pertinente
 la segunda

 entonces el punto es que la verdad y también la pertinencia de la segunda
 proposición
 tiene que necesariamente arrojar duda sobre la primera excepto para alguien que
 tenga especial información de que sin duda no r (no habrá una maquina)

 si juzgamos que si p entonces q
 y se nos lanza una premisa segunda verdadera si r entonces no (si p entonces q)
 esta segunda sólo será capaz de arrojar duda sobre la segunda no sólo si es
 verdadera, sino también si es imposible que sea simplemente descartada porque
 no tenemos que tomar en serio su antecedente

 hay un gran numero de juicios hipoteticos que son como esto

 hay toda una clase de juicios tales que cuando los hacemos
 no estamos implicitamente descartando como falso
 todo lo que los falsificaría

 en contraste cuando hacemos una afirmación categórica con la seguridad
 apropiada
 es con frecuencia el caso que
 puedo descartar inmediatamente como falso
 lo que lo falsificaría
 sólo por que sé que es verdad

 cuando hago una afirmación categórica con la seguridad apropiada
 sólo porque sé que es verdad
 puedo descartar inmediatamente como falso todo lo que
 falsificaría esta afirmación

 en esta ocasión estoy haciendo un juicio en el que afirmo como verdadero algo
 sin poder descartar inmediatamente todo lo que falsificaría esta afirmación

 quizás aquí hemos descubierto
 el caracter especial
 de los
 hipotéticos (teoreticos) cuyos consecuentes no se siguen lógicamente de sus
 antecedentes
 podemos llamar a esta característica revocabilidad (inviabilidad) esencial

 (no r) se sigue
 pero no es razonable deducirlo de esa conjunción

 sino que reclama otro fundamento (como creer que x cree)

 parece que llegar a la conclusión reclama dudar del antecedente de la segunda
 premisa si r

 si p entonces q
 si r entonces no (si p entonces q)
 por lo tanto no r
 bueno, si no p entonces r
 por lo tanto no r
 si p entonces no r
 por lo tanto p y q

Cuando la primera premisa no expresa una verdad necesaria, cuando q no se sigue
de p el car

  p y q es una afirmación categórica?
  p y q es un tipo de juicio que cuando lo hacemos no estamos descartando
  implicitamente como falso cualquier cosa que lo falsificaría

*** thoughts
 Cuestiona la aplicabilidad de principios lógicos que ya son familiares usando
 ejemplos de argumentación actual


   Este argumento es formálmente válido y sus premisas son mutuamente compatibles.
   Todas pueden ser verdad juntas sólo en el caso en el que el árbol caiga y el
   camino quede interrumpido. ¿Cómo es que hay algo obviamente chiflado sobre este
   argumento?

   La peculiaridad de este caso es que no parece haber ninguna dificultad para
   juzgar ninguna de las tres premisas como verdaderas sin haber juzgado ya la
   conclusión o parte de ella como verdadera.

   La dificultad está en combinarlas en conocimiento, o en un juicio razonable,
   a no ser que parte de la conclusión sea parte del fundamento para aceptar la
   combinación. Uno quiere decir: que puedas sacar esta conclusión desde estas tres
   proposiciones es fundamento para dudar la conjunción de éstas. Pero la razón no
   es que la conclusión sea ella misma falsa, tampoco absurda. Es una proposición
   perfectamente posible, y es objetada sólo como una conclusión de proposiciones
   perfectamente posibles, que son mutuamente compatibles y desde las cuales esto
   si se sigue.


   La razón para objetar parece no ser nada peculiar con el ejemplo, sino que
   reside en el caracter bastante general de las primeras dos premisas cuando la
   primera no expresa ninguna verdad necesaria es decir, cuando q no se sigue de p.
   El carácter general parece ser esto: uno usualmente puede aceptar las instancias
   1 y 2 juntas, cuando q no se sigue de p, sólo cuando uno está
   independientemenete seguro de que no r

   Las circunstancias son raras en las que uno piense que p entonces q, y sólo por
   eso, que esté claro de que si r, entonces no (si p entonces q), y uno pueda
   deducir que no r.

   Lo que despierta la duda no es simplemente la verdad de la segunda proposición,
   sino su verdad combinada con la imposibilidad de simplemente descartarla porque
   no tenemos que tomar su */antecedente seriamente/*

   Es una observación interesante e importante que hay toda una clase de juicio
   tales que cuando los hacemos no estamos implícitamente descartando como falso
   todo lo que los falsificaría.

   En contraste, cuando hago una afirmación categórica con la seguridad apropiada,
   es con frecuencia el caso que puedo de inmediato eliminar como falso lo que lo
   falsificaría --sólo porque sé que este es verdadero.

   Entonces quizas hemos descubierto el caracter especial de (teoreticos)
   hipotéticos cuyos consecuentes no se siguen lógicamente de sus antecedentes.
   Podríamos llamar a esta característica `inviabilidad (anulabilidad,
   revocabilidad) esencial'. Esto será la razón por la cual, incluso cuando no r se
   sigue de si p entonces q y si re, entonces no(si p entonces r), todavía puede
   ser altamente irracional deducir no r de esa conjunción.

   El análisis terminará por levantar más problemas
   que clarificaciones. Con frecuencia los argumentos terminan sonando como
   locuras. Pero acaso no son validos? Y acaso no son ambas premisas y conclusiones
   bastante posibles --dado, para cada caso, una historia apropiada?
   La tercera premisa usualmente reclama una historia. Pero las historias son
   suplidas con facilidad.

   Podría haber un tipo de si p entonces q que sea irrevocable?
   Si es posible podemos tener un caso donde llegamos a la conclusion p y q
   desde las 3 premisas hipotéticas 1,2 y 3

   \begin{adjustwidth}{1.2cm}{}
     1. Si Dios ha prometido a mi padre que será el padre de una gran nación por
     medio de mi, entonces mi padre lo será\\
     2. Si mi Padre me mata, no es cierto que si Dios le ha prometido que él sera
     el Padre de una gran nación por medio de mi, entonces el lo será.
     (Por lo tanto no me matará.)\\
     3. Si Dios no ha prometido a mi padre que el será el padre de una gran nación
     por medio de mí, mi padre va a matarme.\\
     $\therefore$ Dios ha prometido a mi padre y esto será cumplido\\
   \end{adjustwidth}
** What is it to believe someone?
#+BEGIN_SRC latex
  \subsection{¿Qué es creer a alguien?}
#+END_SRC
*** Cuestión peliminar
#+BEGIN_SRC latex
  \subsubsection{Cuestión preliminar}
  En el análisis anterior Anscombe ha descrito un escenario en el que combinar
  varias premisas como conocimiento o juicio razonable resulta problemático a la
  hora de justificar el fundamento de la conclusión apoyándose sólo en las
  premisas y su relación lógica.

  En su investigación titulada \emph{What is it to believe someone?} Anscombe
  comienza describiendo otro escenario basado en el mismo argumento, situándose así
  en una situación que plantea la misma dificultad; también en el creer a alguien
  el fundamento para la combinación de las premisas en un juicio razonable parece
  estar más allá de las mismas premisas y sus relaciones. En esta ocasión cada
  premisa aparece atribuida a una persona distinta y la conclusión a un cuarto
  personaje. El pequeño relato aparece como sigue: \citalitlar{Había tres hombres,
    $A$, $B$ y $C$, hablando en cierta aldea. $A$ dijo: ``Si ese árbol cae,
    interrumpirá el paso por el camino durante mucho tiempo.'' ``No será así si
    hay alguna máquina para remover árboles funcionando'', dijo $B$. $C$ destacó:
    ``\emph{Habrá} una, si el árbol no cae.'' El famoso sofista Eutidemo, un
    extraño en el lugar, estaba escuchando. Inmediatamente dijo: ``Les creo a
    todos. Así que infiero que el árbol caerá e interrumpirá el paso por el
    camino.'' \footnote{\cite[1]{anscombe2008faith:tobelieve} <<There were three
      men, $A$, $B$ and $C$, talking in a certain village. $A$ said ``If that tree
      falls down, it'll block the road for a long time.'' ``That's not so if
      there's a tree-clearing machine working'', said $B$. $C$ remarked ``There
      \emph{will} be one, if the tree doesn't fall down.'' The famous sophist
      Euthydemus, a stranger in the place, was listening. He immediately said ``I
      believe you all. So I infer that the tree will fall and the road will be
      blocked.''>>}}

  ¿En qué está mal Eutidemo? Si se evalúa la lógica del argumento antes expuesto
  no aparece ninguna contradicción, sin embargo hay algo extraño en la afirmación
  ``les creo a todos''. Si la lógica del argumento parece permitir que la
  inferencia de Eutidemo sea posible, ¿por qué suena tan extraña la posibilidad de
  que les crea a todos y juzgue esa conclusión?
#+END_SRC
*** Naturaleza de la Investigación
#+BEGIN_SRC latex
   \subsubsection{Naturaleza de la Investigación}
   Es útil recordar aquí en términos generales el modo en el que Anscombe actua en
   una investigación filosófica. Wittgenstein inicialmente describió el análisis
   del lenguaje bajo la concepción de que la lógica conforma el orden que está
   debajo y que sostiene todo lenguaje posible. El trabajo del filósofo es analizar
   el lenguaje para sacar al descubierto el orden lógico que está debajo del
   lenguaje ordinario y que es la forma de la realidad. Wittgenstein abandonó esta
   concepción; en Investigaciones Filosóficas exclama: \citalitlar{Cuanto más de
     cerca examinamos el lenguaje actual, más crece el conflicto entre éste y
     nuestro requisito. (Pues la pureza cristalina de la lógica no era, por
     supuesto, algo que yo hubiera \emph{descubierto}: era un requisito.) El
     conflicto se hace intolerable; el requisito llega ahora a estar en peligro de
     tornarse vacuo. --- Nos hemos situado en hielo resbaladizo donde no hay
     fricción, y así, en cierto sentido, las condiciones son ideales; pero también,
     justo por eso, no somos capaces de caminar. Queremos caminar: así que
     necesitamos \emph{fricción}. ¡De vuelta al terreno
     escarpado!\footnote{\cite[\S107]{wittgenstein1953phiinv}: <<The more closely
       we examine actual language, the greater becomes the conflict between it and
       our requirement. (For the crystalline purity of logic was, of course, not
       something I had \emph{discovered}: it was a requirement.) The conflict
       becomes intolerable; the requirement is in danger of becoming vacuous. ---
       We have got on to slippery ice where there is no friction, and so, in a
       certain sense, the conditions are ideal; but also, just because of that, we
       are unable to walk. We want to walk: so we need \emph{friction}. Back to the
       rough ground!>>}.}

   Los nombres, las proposiciones, el lenguaje, no tienen una forma esencial para
   ser puesta al descubierto por el análisis, sino que son familias de estructuras
   que están a plena vista y que pueden ser clarificadas por medio de la
   descripción\autocite[Cf.~][12]{bakerhacker2009understanding}. Wittgenstein le
   \citalitinterlin{da la vuelta a la
     busqueda}\autocite[\S108]{wittgenstein1953phiinv}, y trata a la lógica no como
   lo que está debajo del lenguaje para ser descubierto, sino como
   \citalitinterlin{una cuadrícula que imponemos sobre los argumentos para probar y
     demostrar su validez}\footnote{\cite[12]{bakerhacker2009understanding}: <<a
     grid we impose upon arguments to test and demonstrate their validity>>}.

   Descartada la concepción sublime de la tarea filosófica, Wittgenstein describe
   los problemas filosóficos como formas de malentendidos o falta de entendimiento
   que pueden ser disueltos por medio de descripciones de los usos de las palabras.
   La tarea de la filosofía es la \citalitinterlin{clarificación gramatical que
     disuelve la perplejidad conceptual y ofrece una visión amplia o representación
     estudiable de un segmento de la gramática de nuestro
     lenguaje}\footnote{\cite[12]{bakerhacker2009understanding}: <<grammatical
     clarification that dissolves conceptual puzzlement and gives an overview of or
     surveyable representation of a segment of the grammar of our language>>}. Esta
   metodología, por tanto, no pretende ofrecer teorías explicativas fruto de la
   deducción o la hipótesis; tampoco pretende ofrecer tesis dogmáticas o
   esencialistas. Más bien busca describir usos familiares de las palabras y
   ordenarlas de tal manera que los patrones de su uso sean
   estudiables\autocite[Cf.~][12]{bakerhacker2009understanding}. La metodología de
   Elizabeth está basada en esto.
 #+END_SRC
*** Investigación en la gramática de creer
#+BEGIN_SRC latex
   \subsubsection{Investigación Gramática de `creer a $x$ que $p$'.}
   Anscombe pone el interés de su investigación en la forma de la expresión `creer
   a $x$ que $p$'\autocite[Cf.~][2]{anscombe2008faith:tobelieve}. Su análisis se va
   desenvolviendo a lo largo de la descripción de los usos de la expresión.

   \citalitinterlin{Si me dijeras `Napoleón perdió la batalla de Waterloo' y te
     digo `te creo' sería una
     broma}\footnote{\cite[4]{anscombe2008faith:tobelieve}: <<If you tell me
     `Napoleon lost the battle of Waterloo' and I say `I believe you' that is a
     joke.>>}. A primer golpe `creer a $x$ que $p$' parece que significa
   simplemente creer lo que alguien me dice, o creer que lo que me dice es
   verdadero. Sin embargo esto no es suficiente. Puede ser que ya crea lo que
   alguien me venga a decir. Puede ser que la comunicación suscite que forme mi
   propio juicio acerca de la verdad comunicada, pero aquí no podría decir que
   estoy creyendo al que comunica o que estoy contando con él para mi creer que
   $p$.

   ¿Entonces creer a alguien es creer algo apoyado en el hecho de que lo ha dicho?
   \citalitinterlin{Puede que se le pregunte a un testigo `¿Por qué pensó que aquel
     hombre se estaba muriendo?' y que éste responda `Porque el doctor me lo dijo'
     [\ldots] `no me hice ninguna opinión propia --- yo sólo creí al
     doctor'}\footnote{\cite[4]{anscombe2008faith:tobelieve}: <<A witness might be
     asked `Why did you think the man was dying?' and reply `Because the doctor
     told me'. If asked further what his own judgement was, he may reply `I had no
     opinion of my own --- I just believed the doctor'.>>}. Éste puede ser un
   ejemplo de contar con $x$ para la verdad de $p$. Esto, sin embargo, tampoco
   parece ser suficiente. Puedo imaginar el caso en el que esté convencido de que
   alguien a la vez cree lo opuesto a la verdad de $p$ y quiera mentirme. Según
   este cálculo podría decir que creo en lo que ha dicho por el hecho de que me lo
   ha dicho, pero no estaría diciendo que le creo a él.

   ¿Qué se puede decir del <<les creo a todos>> de Eutidemo en la cuestión
   preliminar? Anscombe juzga que la exclamación no expresa simplemente una opinión
   apresurada o excesiva credulidad, sino más bien suena a
   locura\autocite[5]{anscombe2008faith:tobelieve}. Eutidemo no puede estar
   diciendo la verdad cuando dice que les cree a todos. La expresión de $C$ da
   pertinencia a lo que dice $B$, y la manera natural de entender lo que dice $B$
   es como arrojando duda sobre lo que $A$ ha dicho. ¿Se puede pensar que $A$
   todavía cree lo que ha dicho inicialmente? ¿Eutidemo puede creer a $A$ sin saber
   cuál es su reacción a lo que $B$ y $C$ han dicho? Entonces Anscombe concluye,
   \citalitinterlin{Para creer a $N$ uno debe creer que $N$ mismo cree lo que está
     diciendo}\footnote{\cite[5]{anscombe2008faith:tobelieve}: <<To believe $N$ one
     must believe that $N$ himself believes what he is saying>>.} Creer a $N$ sin
   saber si $N$ cree lo que dice le suena a Elizabeth como una locura.

   En este punto queda expuesta a la luz una segunda creencia involucrada en el
   creer a $x$ que $p$. Anscombe fija su atención en esto. Creer a $x$ que $p$
   conlleva otras creencias, éstas son presuposiciones implicadas en llegar a
   plantearse si creer o no. En primer lugar, si se cree a alguien, tiene que ser
   el caso que se cree que una comunicación es de
   alguien\autocite[Cf.~][6]{anscombe2008faith:tobelieve}. Esta presuposición no
   parece tan problemática si se piensa en las ocasiones en las que creemos a
   alguien que es percibido. Sin embargo tiene más profundidad si se considera que
   con frecuencia recibimos la comunicación sin que esté presente el que habla,
   como cuando leemos un libro\autocite[Cf.~][5]{anscombe2008faith:tobelieve}.

   Se puede imaginar aquí una situación problemática. Supongamos que alguien recibe
   una carta en la que el autor no es el comunicador ostensible o aparente, es
   decir, quien firma la carta no es quien la ha escrito. ¿Se puede decir que el
   que recibe la carta cree o descree al autor o al comunicador ostensible? Creer
   al autor, afirma Anscombe, conlleva un tipo de juicio y especulación que no son
   mediaciones ordinarias en el creer a
   alguien\autocite[Cf.~][7]{anscombe2008faith:tobelieve}. Para decir que creo al
   autor tendría que discernir que la comunicación que viene bajo otro nombre es
   realmente de esta otra persona que además me quiere decir esto.

   Respecto de la posibilidad de decir que se cree al comunicador ostensible
   Anscombe distingue entre un comunicador ostensible que exista o no. Ante una
   comunicación que viene de parte de un comunicador aparente que no existe,
   alguien puede responder diciendo que cree o descree al comunicador aparente,
   pero la decisión de decir esto ---dice Anscombe--- \citalitinterlin{es una
     decisión de dar a estos verbos un uso `intencional', como el verbo `ir
     tras'}\footnote{\cite[7]{anscombe2008faith:tobelieve}: <<is a decision to give
     those verbs an `intentional' use like the verb `to look for'>> Ver:
     \cite{anscombe1981metaphysics:intsens}. Anscombe propone que un verbo es usado
     intencionalmente cuando tiene como objeto directo un `objeto intencional'
     (`objeto' no en el sentido material, sino de finalidad).}. Esto lo ilustra
   añadiendo: \citalitlar{Y así uno podría hablar de alguien como creyendo al dios
     (Apolo, digamos), cuando consultó el oráculo del dios -- sin que por esto uno
     estuviera implicando que uno mismo cree en la existencia del dios. Todo lo que
     queremos es que necesitamos saber lo que es llamado que el dios le diga
     algo\footnote{\cite[7]{anscombe2008faith:tobelieve}: <<And so we might speak
       of someone as believing the god (Apollo, say), when he consulted the oracle
       of the god -- without thereby implying that one believed in the existence of
       the gos oneself. All we want is that we should know what is called the god's
       telling him something>>}.} `Creer' usado aquí intencionalmente viene a decir
   que se busca o se desea creer a $x$ (Apolo en este caso) cuando se recibe
   aquello que alguien entiende como una comunicación suya.

   En el caso de que el comunicador ostensivo sí exista, la noción de creerle
   manifiesta una cierta oscilación. Una tercera persona podría decir que `aquel,
   pensando que $N$ dijo esto, le creyó', o el comunicador aparente puede decir
   `veo que pensaste que fui yo quien dijo esto y me creiste', sin embargo, si el
   que ha recibido la comunicación dijera `naturalmente te creí', el comunicador
   aparente podría contestar `ya que no lo he dicho yo, no me estabas creyendo a
   mi'\autocite[Cf.~][8]{anscombe2008faith:tobelieve}.

   Estas consideraciones llevan a Anscombe a distinguir entre el que habla en una
   comunicación y el productor inmediato de la
   comunicación\autocite[Cf.~][8]{anscombe2008faith:tobelieve}. Éste puede ser
   cualquiera que pase hacia adelante alguna comunicación, un maestro o mensajero,
   o un interprete o traductor; éste es \citalitinterlin{el productor inmediato de
     aquello que se entiende, o incluye una reclamación interna de ser entendido
     como una comunicación de $NN$}\footnote{\cite[8]{anscombe2008faith:tobelieve}:
     <<we can speak of the immediate producer of what is taken, or makes an
     internal claim to be taken, as a communication from $NN$>>}. Si digo que creo
   a un intérprete estoy afirmando que creo lo que ha dicho su principal, y mi
   contar con el intérprete consiste en la creencia de que ha reproducido lo que
   aquel ha dicho. En este sentido el intérprete no le falta rectitud si dice algo
   que no es verdadero pero no ha representado falsamente lo que ha dicho su
   principal. Por el contrario, al maestro sí le faltaría rectitud si lo que dice
   no es verdadero. Cuando se cree al maestro, aún en el caso que no sea de ninguna
   manera autoridad original de lo que comunica, se le cree a él sobre lo que
   transmite. Para Anscombe no es necesario que cuando se cree a alguien se le
   trate como una autoridad
   original\autocite[Cf.~][5]{anscombe2008faith:tobelieve}. En esto el ejemplo del
   maestro como distinto del intérprete es ilustrativo. Un maestro puede conocer lo
   que enseña porque lo ha recibido de alguna tradición de información y al
   transmitir lo que enseña se le está creyendo a él.

   Asoma aquí otro aspecto relacionado con esta presuposición. Al creer que una
   comunicación es de alguien se cree a una persona que puede tener distintos
   grados de autoridad sobre lo que dice. El maestro del que se ha hablado antes
   podría afirmar <<Leonardo da Vinci dibujó diseños para una máquina voladora>> y
   en esto no es para nada una autoridad
   original\autocite[Cf.~][6]{anscombe2008faith:tobelieve}. Conoce esto porque lo
   ha escuchado, incluso si ha visto los diseños. Aún cuando los hubiera
   descubierto él mismo, tendría que haber contado con alguna información recibida
   de que esos diseños que ve son de Leonardo. En este caso sí seria una autoridad
   original en notar que estos diseños que ha escuchado que son de Leonardo son de
   máquinas voladoras. Anscombe explica la distinción diciendo:
   \citalitlar{[Alguien] es \emph{una} autoridad original en aquello que él mismo
     ha hecho y visto y oido: digo \emph{una} autoridad original porque sólo quiero
     decir que él mismo sí contribuye algo, es algún tipo de testigo por ejemplo,
     en lugar de alguien que sólo transmite información recibida. Pero su informe
     de aquello de lo que es testigo es con frecuencia [\ldots] fuertemente
     influenciado o más bien casi del todo formado por la información que \emph{él}
     ha recibido\footnote{\cite[5]{anscombe2008faith:tobelieve}: <<He is \emph{an}
       original authority on what he himself has done and seen and heard: I say
       \emph{an} original authority because I only mean that he does himself
       contribute something, e.g. is in some sort a witness, as oposed to one who
       only transmits information received. But his account of what he is a witness
       to is very often [\ldots] heavily affected or ratherl all but completely
       formed by what information \emph{he} had received.>>}.} Además de ser
   \emph{una} autoridad original sobre algún hecho, una persona puede ser una
   autoridad \emph{totalmente} original. Si la distinción entre alguien que no es
   una autoridad original y alguien que sí lo es ha sido descrita como la
   contribución de algo propio que junto con la información recibida permite
   construir un informe, lo particular de una autoridad totalmente original es que
   no se apoya en ninguna información recibida para construir su informe de los
   hechos. Anscombe no entiende el lenguaje como información recibida. Pone como
   ejemplo de informe de una autoridad totalmente original a alguien que dice `esta
   mañana comí una manzana' y dice: \citalitlar{si él está en la situación usual
     entre nosotros, sabe lo que una manzana es --- es decir, puede reconocer
     una. Así que aún cuando se le ha `enseñado el concepto' al aprender a usar el
     lenguaje en la vida ordinaria, no cuento esto como un caso de depender en
     información recibida.\footnote{\cite[6]{anscombe2008faith:tobelieve}: <<if he
       is in the situation usual among us, he knows what an apple is --- i.e. can
       recognise one. So though he was `taught the concept' in learning to use
       language in everyday life, I do not count that as a case of reliance on
       information received.>>}}

   Hasta aquí se ha visto que el creer a $x$ que $p$ implica otras creencias que
   son presuposiciones a la pregunta sobre si se cree o se descree a alguien y se
   ha descrito lo que tiene que ver con la creencia de que una comunicación viene
   de alguien. Anscombe examina otras presuposiciones más. También tiene que ser el
   caso que creamos que por la comunicación, la persona que habla quiere decir
   \emph{esto}. En situaciones ordinarias no es difícil distinguir si alguien está
   diciendo o escribiendo algún lenguaje. Sin embargo, aún cuando el que habla use
   palabras que puedo `hacer mías' y creer simplemente las palabras que dice, aquí
   queda espacio para decir que hay una creencia adicional de que se ha dicho `tal
   cosa' en la comunicación. Elaboramos en aquello que hemos creido y usamos otras
   palabras distintas, nuestras creencias no están atadas a palabras específicas.
   También podríamos pensar que alguien diga que cree \emph{esto} porque cree a $x$
   y que se le cuestione su creencia preguntando `¿qué tomaste como $x$ dicicéndote
   eso?'\autocite[Cf.~][8]{anscombe2008faith:tobelieve}.

   Otra presuposición más sería que se cree que la comunicación está
   \emph{dirigida} a alguien, aunque sea `a quien lea esto' o `a quien pueda
   interesar'. Esta creencia se podría problematizar pensando en algún caso que
   alguien reciba una comunicación con otro destinatario, ¿estaría creyendo al que
   se comunica?. Asncombe opina que en un sentido extendido o reducido y considera
   que el tema parece de poca
   importancia\autocite[Cf.~][7]{anscombe2008faith:tobelieve}.

   Una persona a quien se dirige una comunicación puede \emph{fallar en creerla} si
   no nota la comunicación, o si notándola no la interpreta como lenguaje, o si
   notándola como lenguaje no la toma como dirigida hacia ella; o puede que crea
   todo esto, pero lo interprete incorrectamente, o puede que lo interprete bien
   pero no crea que viene realmente de $N$. En este tipo de casos la persona no ha
   descreido, sino que no ha llegado a estar en la situación de plantearse esa
   pregunta. Para poder llegar a preguntar si alguien cree a $x$ que $p$ habría que
   excluir o asumir como excluidos todos los casos en los que estas otras
   presuposiciones no se han cumplido. Es así que Anscombe concluye:
   \citalitlar{Supongamos que todas la presuposiciones están dadas. $A$ está
     entonces en la situación ---una muy común--- donde surge la pregunta sobre si
     creer o dudar (suspender el juicio ante) $NN$. Sin confusión por todas las
     preguntas que surgen por las presuposiciones, podemos ver que creer a alguien
     (en el caso particular) es confiar en él para la verdad -- en el caso
     particular. \footnote{\cite[9]{anscombe2008faith:tobelieve}: <<Let us suppose
       that all the presuppositions are in. $A$ is then in the situation ---a very
       normal one--- where the question arises of believing or doubting (suspending
       judgement in face of) $NN$. Unconfused by all the questions that arise
       because of the presuppositions, we can see that believing someone (in the
       particular case) is trusting him for the truth -- in the particular
       case.>>}.}
   Que $A$ crea a $N$ que $p$ implica que $A$ cree que en una comunicación, que puede
   venir de un productor inmediato, $N$ es el que habla y lo que dice es $p$ y esta
   comunicación está dirigida hacia $A$; entonces $A$, creyendo que $N$ cree que
   $p$, confia en $N$ sobre la verdad de $p$.
#+END_SRC
** Valoraciones Preliminares
#+BEGIN_SRC latex
  \subsection{Valoraciones Preliminares}
  Hasta aquí hemos recorrido con Elizabeth una descripción de un tipo de juicio
  cuyo fundamento se encuentra más allá de la relación lógica de sus premisas.
  Formar un juicio razonable a partir de la creencia depositada en el informe de
  alguien acerca de algún hecho no sólo tiene como fundamento una valoración de la
  lógica de su argumentación, sino que implica, dadas las presuposiciones, confiar
  en el que habla, creyendo además que cree lo que dice.

  El análisis de Anscombe también ofrece la posibilidad de hacer una descripción
  general de lo que significa `creer a un testigo que $p$'. Anscombe ha hecho la
  distinción entre alguien que simplemente transmite información y alguien que
  puede ser considerado algún tipo de testigo. Un testigo es un ejemplo de
  autoridad original y alguien es una autoridad original acerca de lo que él mismo
  ha hecho y visto y oído. Un testigo que es una autoridad original aporta algo de
  lo que él mismo ha hecho y visto y oído y lo considera junto a información que
  ha recibido para comunicar su informe de algún hecho. Cuando el testigo no
  cuenta con información recibida, sino que habla sólo de lo que aporta él mismo,
  es una autoridad totalmente original. Aunque esta descripción del testigo es muy
  amplia, permite afirmar que cuando $A$ cree a un testigo que $p$, $A$ cree que
  en una comunicación, que puede venir de un productor inmediato, es esta
  autoridad original el que habla y que dice $p$ y tiene a $A$ como destinatario;
  entonces $A$, creyendo que esta autoridad original cree lo que dice, confia en
  el testigo sobre la verdad de $p$.

  La investigación sobre el creer abre además varias rutas de análisis en torno al
  tema del testimonio. Dos de estas conexiones aparecen en la investigación de
  Anscombe a modo de preámbulo y la tercera queda planteada como una cuestión
  abierta al final.
#+END_SRC
*** Acceso al mundo más allá de la experiencia
#+BEGIN_SRC latex
   \subsubsection{Acceso al mundo más allá de la experiencia}
   ¿Cómo accedemos a una idea del mundo más allá de nuestra experiencia personal?
   Una de las cuestiones que Anscombe plantea como preámbulo a su análisis sobre el
   `creer a alguien' tiene que ver con esta pregunta.

   Hume diría que el puente que permite nuestro contacto con la realidad más allá
   de nuestra experiencia es la relación
   causa-y-efecto\autocite[Cf.~][3]{anscombe2008faith:tobelieve}. Inferimos las
   causas desde sus efectos porque estamos acostumbrados a ver que causa y efecto
   van juntas. Estas causas inferidas las verificamos en la percepción inmediata de
   nuestra memoria o nuestros sentidos, o por medio de la inferencia de otras
   causas verificadas del mismo
   modo\autocite[Cf.~][88]{anscombe1981parmenides:humeandjulius}. Hume entonces
   propone que la relación entre el testimonio y la verdad es de la misma clase,
   inferimos la verdad del testimonio porque estamos acostumbrados a que vayan
   juntas\autocite[Cf.~][3]{anscombe2008faith:tobelieve}.

   Anscombe tacha de absurda esta visión del rol del testimonio en el conocimiento
   humano\autocite[Cf.~][3]{anscombe2008faith:tobelieve} y le parece que
   \citalitinterlin{el misterio es cómo Hume la pudo haber llegado a
     sostener}\footnote{\cite[Cf.~][3]{anscombe2008faith:tobelieve}: <<the mystery
     is how Hume could ever have entertained it.>>}. Entonces explica:
   \citalitlar{Hemos de reconocer al testimonio como el que nos da nuestro mundo
     más grande en no menor grado, o incluso en un grado mayor, que la relación de
     causa y efecto; y creerlo es bastante distinto en estructura que el creer en
     causas y efectos. Tampoco es lo que el testimonio nos da una parte
     completamente desprendible, como el borde de grasa en un pedazo de filete. Es
     más bien como las manchas y rayas de grasa que están distribuidas a través
     de la buena carne; aunque hay nudos de pura grasa
     también\footnote{\cite[3]{anscombe2008faith:tobelieve}:<<We must acknowledge
       testimony as giving us our larger world in no smaller degree, or even in a
       greater degree, than the relation of cause and effect; and believing it is
       quite dissimilar in structure from belief in causes and effects. Nor is what
       testimony gives us entirely a detachable part, like the thick fringe of fat
       on a chunk of steak. It is more like the flecks and streaks of fat that are
       distributed through good meat; though there are lumps of pure fat as
       well>>}.} Elizabeth considera que la mayor parte de nuestro conocimiento de
   la realidad está apoyado en la creencia que tenemos en las cosas que se nos han
   enseñado o dicho\autocite[Cf.~][3]{anscombe2008faith:tobelieve}. Para ella, la
   investigación acerca de `creer a alguien' no sólo es del interés de la teología
   o de la filosofía de la religión, sino de enorme importancia para la teoría del
   conocimiento\autocite[Cf.~][3]{anscombe2008faith:tobelieve}.

   La ruta de análisis que Anscombe abre con esta propuesta consiste en una
   descripción más adecuada de la `estructura del creer en el testimonio' como una
   estructura distinta de la relación causa y efecto. Aquí la descripción vista
   sobre el `creer a algiuen' ha ofrecido ya pistas valiosas. Sin embargo, Anscombe
   aborda el tema en otras discusiones y es necesario tenerlas en cuenta para hacer
   una descripción más completa.
#+END_SRC
*** `Creer a alguien' como `Fe'
#+BEGIN_SRC latex
   \subsubsection{`Creer a alguien' como `Fe'}
   Una segunda cuestión que aparece como preámbulo en la investigación de Anscombe
   es planteada así: \citalitinterlin{Si las palabras siempre guardaran sus
     antiguos valores, podría haber llamado mi tema `Fe'. Este corto término ha
     sido usado en el pasado justo con este significado, el de creer a
     alguien}\footnote{\cite{anscombe2008faith:tobelieve}: <<If words always kept
     their old values, I might have called my subject `Faith'. That short term has
     in the past been used in just this meaning, of believing someone.>>}. Este uso
   de la expresión sera útil para Anscombe en su análisis del uso de la palabra
   `fe'. Su descripción estará enfocada en `fe' como `creer a Dios que $p$'. Esta
   segunda ruta será explorada más adelante.
#+END_SRC
*** Creer a quien habla rectamente
#+BEGIN_SRC latex
   \subsubsection{Creer a quien habla rectamente}
   Al final de la investigación, Anscombe propone una cuestión que se queda
   abierta. Tiene que ver con uno de los ejemplos relacionados a creer que la
   comunicación viene de alguien. Allí proponia imaginar el caso en el que
   estuvieramos convencidos de que alguien viene a decirnos lo que cree que es
   falso, pero a la misma vez sabemos que lo que cree es lo contrario a la verdad.
   Al decir lo que cree que es falso estaría afirmando la verdad. En ese caso,
   afirmaba Anscombe, podría decir que creo en lo que dice y además creo porque lo
   dice, pero no le creo a él. Se podría preguntar ¿cuál es la diferencia entre
   llegar a la creencia de $p$ porque alguien que está en lo correcto y es veraz me
   lo ha dicho, y llegar a la misma creencia porque me lo ha dicho alguien que está
   equivocado y miente? Ambos casos parecen implicar un cálculo, en uno se calcula
   que está en lo correcto y es veraz y en el otro se calcula que está equivocado y
   miente. ¿Por qué estamos dispuestos a decir que creemos al que habla sólo en el
   caso en que esté en lo correcto y sea veraz? ¿Acaso no llevan ambos casos a la
   misma creencia que $p$?

   Aquí Anscombe percibe que hay más que decir sobre la prioridad que damos a la
   rectitud y la veracidad en el creer lo que se nos dice sobre la realidad. De las
   tres rutas descritas, recorreremos ésta primero.
 #+END_SRC

* Rambling
Varios puntos para tratar aquí

no es lo mismo inferir la verdad desde el análisis lógico que creer a x que p

la gramática de la palabra fe tiene que ver con la gramática del creer a x que p

la estructura de creer a x que p es la estructura de conocer el mundo más alla
de mis percepciones o relaciones de percepciones.

creer a x que p

creencia depositada en p enseñado

la creencia depositada en el testimonio de x
me permite acceder a la idea del mundo más allá de mi experiencia personal

creer en el testimonio de x
es creer a x que p

p = testimonio

creer a x que p
es
una parte importante para la teoría del conocimiento

la mayor parte de nuestro conocimiento de la realidad descansa en la creencia
que depositamos en las cosas que se nos han enseñado y dicho.

Tenemos que reconocer al testimonio como dándonos nuestro mundo más grande en no
menor grado, e incluso en mayor grado que la relación de causa y efecto
y creerlo es bastante disimilar en estructura que el creer en causas y efectos.


lo que el testimonio nos da no es una parte desprendible

Para Anscombe `p' en creer a x que p es el testimonio.

Testimonio es lo que se cree cuando se confia en x

no> Testimonio es lo que se conoce cuando se cree a x que p
la realidad es lo que se conoce cuando se cree a x que p
creer a x que p
es creer el testimonio de x


la creencia puesta en lo que se nos ha dicho
sotiene la gran parte de
nuestro conocimiento

 Hasta aquí, se podría decir que un testigo es una autoridad original o totalmente
  original. Un testigo aporta algo suyo. Cuando digo que creo a un testigo que x

  estoy diciendo que
  Creo a alguien que cuenta con algo suyo que ha oído, o hecho o visto y que
  uniendo eso a información recibida ofrece un informe de algún hecho



  del análisis podemos sacar que creer a alguien que p incluye otras creencias



  El analisis nos deja una impresión general de lo que decimos cuando decimos que
  creemos a alguien


  Esta investigación de Anscombe establece varios nexos importantes. La gramática
  de `creer a $X$ que $p$' está relacionada en puntos importantes con la gramática
  de la fe. El testimonio es descrito como el complemento (in)directo en la
  expresión `Creer a $X$ que $p$'. Adicionalmente, el análisis de Anscombe
  presenta una descripción de la estructura de creer que es útil para la
  descripción del testimonio.

  El primer vínculo que establece es entre `creer a' y la fe. \citalitinterlin{Si
    las palabras mantuvieran sus viejos significados habría llamado a mi tópico
    fe}. Hoy la palabra se usa para significar lo mismo que religión, o
  posiblemente creencia religiosa. Según este uso, creer en Dios --creer que Dios
  es, no que pueda ayudarnos, por ejemplo-- se llamaría fe. Esto ha tenido un
  efecto dañino para el pensamiento sobre la religión. En el pasado, sin embargo,
  el término ha sido usado justo con el sentido de `creer a alguien'. Cuando se
  usaba de este modo, fe se distinguía como humana y divina, según se usara para
  hablar de creer a un ser humano o creer a Dios.

  El segundo vínculo queda establecido cuando Anscombe describe la importancia de
  creer con un objeto personal para la teoría del conocimiento. `Creer a $X$ que
  $p$' es un tema importante, no sólo para la teología y para la filosofía de la
  religión, sino también para la teoría del conocimiento. Una descripción o teoría
  sobre cómo conocemos que no tenga en cuenta lo que conocemos por testimonio
  ignora una gran parte de nuestro modo de conocer el mundo. \citalitinterlin{La
    mayor parte de nuestro conocimiento de la realidad descansa sobre la creencia
    que depositamos en las cosas que se nos han dicho y enseñado.}

  En tercer lugar Anscombe rechaza la teoría de Hume sobre nuestro acceso a la
  realidad más allá de nuestra experiencia o relación de ideas y su descripción de
  la estructura del creer en el testimonio. La descripción de Hume consiste en
  subsumir el creer en el testimonio bajo nuestra creencia en causas y efectos. Su
  pensamiento era que creemos en las causas porque percibimos sus efectos y causa
  y efecto siempre se han encontrado yendo juntos. Similarmente creemos en el
  testimonio porque percibimos el testimonio y hemos encontrado que siempre (¡al
  menos con frecuencia!) testimonio y verdad van juntos. Es así que la idea de
  causa y efecto es nuestro puente para llegar a cualquier idea del mundo más allá
  de nuestra experiencia personal. Anscombe tacha la propuesta de absurda y
  plantea: \citalitlar{Hemos de reconocer al testimonio como el que nos da nuestro
    mundo más grande en no menor grado, o incluso en un grado mayor, que la
    relación de causa y efecto; y creerlo es bastante distinto en estructura que
    el creer en causas y efectos. Tampoco es lo que el testimonio nos da una parte
    completamente desprendible, como el fleco de grasa en un pedazo de filete. Es
    más bien como los flequillos y rayas de grasa que están distribuidos a través
    de la buena carne; aunque hay grumos de pura grasa también.}


* Notes on section structure:
En lugar de presentar el preámbulo primero vamos a ir directo a la investigación
gramática del creer

después hablaremos de los temas tratados en el preámbulo:

esto lo llamaríamos fe
esto es un tema importante para la teoría del conocimiento
hume describe la estructura del testimonio así...

*después de la investigación
se plantean los próximos tres apartados en orden inverso

la estructura del testimonio

la fe

la primacía de la verdad

la conexión puede ser: "creer a x que p" es nuestro puente para acceder a una idea
del mundo más allá de nuestra percepción.

La mayor parte de nuestro conocimiento de la realidad descansa en las cosas que se nos
han dicho y enseñado


* What is it to Believe Someone
** Preamble
*** Question: what is wrong with euthydemus?
A says if p then q
B says that's not so if r [if r then not (if p then q)]
C says if not p then r
D says i belive you all, so I infer that p and q

this is crazy because in absence of any indication from A, he should not be assumed to
believe what he said at first, although it can't be ruled out that he still does think
that way

it is crazy because D can't be telling the true when he says i beleve you all
A shows no sign to still believe what b has cast doubt on

to believe N one must beleve that N himself believes what he is saying
*** does this deserve the attention of philosophic enquiry?
i hope to show that it does.

it is of great importance in philosophy and in life and it's itself problematic enough
to need philosophical investiagtion
*** Believe someone used to be called faith

Hubo una época en la que había el siguiente modo de hablar: fe se distinguía como
humana y divina. Fe humana era creer a un mero ser humano; fe divina era creer a Dios.

Perder esta manera de hablar e igualar fe a religión o creencia religiosa en el sentido
de creer que Dios existe, por ejemplo, ha tenido un efecto repugnante en el pensamiento
sobre la religión

Abrahám creyo a Dios y esto le contó como justificación...
incluso en este contexto bien conocido, donde las palabras aparecen llanamente, la
expresión no es atendida.

Esta historia de Abraham es conocida incluso por intelectuales ignorantes gracias a
Temor y temblor de Kiekergaard. En esta el autor entra en el territorio que le interesa
evadiendo astutamente la primer punto de la historia, que Abrahám creyó a Dios.
Sabe que está ahí, pero no lo afronta.

Esto ha tenido su efecto pues en asunto s de moda intelectual solemos actuar como
borregos.
**** creer a x que p
 Incluso aunque las palabras aparecen llanamente somos atiborrados con basura sobre
 creer en como opuesto a creer a, insistiendo en creer en bueno y creer a malo.

 Naturalmente uno que esté pensando en esa linea no tomaría interes en creer con un
 objeto personal, dado que este será siempre creer que (no creer en)

 Para mis intenciones es necesario adoptar la expresión creer a x que p.

*** Topic important for the theory of knowledge
    La mayor parte de nuestro conocimiento de la realidad descansa sobre la creencia
    que depositamos en las cosas que se nos han enseñado y dicho.

    Hume pensaba que la idea de causa y efecto era el puente que nos permite alcanzar
    alguna idea de un mundo más allá de la experiencia personal.

    Creer en el testimonio pertenece a la misma clase de creencia que el creer en
    causas y efectos.

    Creemos en una causa, pensaba, porque percibimos el efecto y se ha encontrando que
    causa y efecto siempre van juntas.

    Similarmente creemos en la verdad del testimonio porque percibimos el testimonio y
    hemos encontrado (bueno! con frecuencia) que el testimonio y la verdad van juntos.

    La propuesta es absurda.

    Hemos de reconocer al testimonio el darnos nuestro mundo más grande en no menor
    grado, o incluso en un grado mayor, que la relación de causa y efecto; y creer en
    él es bastante distinto en estructura que el creer en causa y efectos

    Tampoco es lo que el testimonio nos da como una parte enteramente desprendible como
    un fleco grueso de grasa de un pedazo de filete. Es más como los flecos rayos de
    grasa que están distribuida a través de la buena carne; aunque hay nudos de pura
    grasa también.

Los ejemplos de las ocasiones en las que lo que se nos ha enseñado sirve como
herramienta para adquirir nuevo conocimiento pueden ser multipicados indefinidamente.

Incluso saber dónde estoy tiene que ver con una complicada red de información recibida.
** Investigation (what's the grammar)
*** Believe with a personal object cannot be reflexive
- To believe someone one must believe that someone himself believes what he is saying

I can say I believe in myself
I can't say I believe myself that x because I wouldn't be believing that I believe what
I'm saying

*** believing someone isn't just believing what he says
I can believe something that another believes, and not because I believe him
This is as what happens when a philosophy teacher expects the student not to believe
him but to come to see.
*** believing someone isn't just believing something on his saying that it is so
he may be lying to me and also believe what is not so
i couldn't say to be beliving him

*** believing someone is believing NN believes what he is saying
this would be the reason why
it cannot be reflexive
euthydemus remark sounds crazy
believing someone isn't just believing what he says based on his saying so


*** Cases when the person believed is not perceived
Often all we have is the communication without the speaker

*** finding something out by a book
  this is so almost any time we find something because it is told us in a book
**** it may be a case:
a communication with a perceived person communicating about another communication where
the communicator is unperceived
**** usually it goes:
the idea of the author is not much brought to our attention at first
**** in any case:
we come to receive communications in books and are apto to believe what a book says
abut itself

*** believing a person is not necessarily taking him as an original authority
he can be a total authority
an original authority
or not an orginal authority at all

believing someone who isn't an original authority is still believing him

an interpreter may be saying something untrue, but he is not wrong if he is not falsely
representing his principal

if you believe an interpreter you believ his principal


a teacher, even though not an original authority is wrong when he says something untrue
and that hangs together with with the fact that his pupils believe him

*** the further beliefs in believing someone
**** it must be tha case that you believe something is a communication (from someone)
**** you have to believe tha by it he is telling you this (is language)
**** the communication is addressed to someone
       1. can someone be supposed to be believing someone when he believes what he says
          while addressing somebody else?

       2. Can someone be supposed to be believing someone when he believes a
          communication that isn't really frome the ostensible communicator, even
          though it is addressed to him?

          can he be said to be believing (or disbelieving) the real or the
          ostensible communicator?

           a. to say in this case that he could be beliving the real communicator would
           be saying that when we believe someone judgement and speculation intervenes

           when we say we believe someone we don't say belief in the sense of forming a
           judgement

           if we learned a communication wasn't really from NN. we would simply case to
           say that we beleve NN.

           b. could we say we believe the ostensible communicator
               - in the case the ostensible communicator exists

                  a third party may be less likely to use the verb believe
                 intentionally "so, thinking that NN said this, he believed him"

               nn himself from his perspective
               "I see, you thought I said this, and you believed me"

               the recepeint from his perspective Naturally i believed you... NN might
               reject this saying: "Since I didn't say it, you weren't believing me"

               there is an oscillation here on the notion of believing

               - in the case teh ostensible communicator doesn't exist

               the decision to speak of believing him is a decision to give that ver an
               intentional use like the verb to look for

               it wouldn't be needed to imply the existence of the inexistent
               communicator, all is needed is to know what it's called the communicator
               telling something

       3. This comes out another way where the recipient does not believe that the
          communication is form NN

          NN may call it a refusal to believe him
       4. If X is to believe NN, something must be being taken as a communication, and
          since X must be believing something on NN say-so there is also involved the
          belief that this communication says such-and-such

i may simply believ your words and

I ought to be able to elaborate upon anything that i believe

** Definition
 Only when we have excluded all the cases
 or
 simply assumed their exclusion

 then we come to the situation in which the question simply is: Does X believe NN or
 not?

 Let us suppose that all the presuppositions are in. A is the in the situation --a very
 normal one--
 where the question arises of believing or doubting (suspending judgemente in face of)
 NN.

 Unconfused by all the questions that arise because of the presuppositions, we can see
 that believing someone (in the particular case) is

 trusting him for the truth - in the particular case.

** Expositio
 ¿Qué es creer a alguien? - Hay muchos presupuestos a la pregunta: ¿X cree a NN o no?
 Creer a alguien (en un asunto particular) es confiar en él acerca de la verdad -- de
 ese asunto particular.

 Llegar a estar en la situación en la que surge para 'A' la pregunta de creer o dudar
 (suspender el juicio ante) NN supone que todos los presupuestos están ahí, es decir que
 han quedado excluidos o se asume que que están excluidos todos estos casos.

 Estos casos son:
 podriamos hablar de un
 productor inmediato de lo que es tomado
 o
 hace una declaración interna de ser tomado

 como una comunicación de NN

 este productor puede ser un mensajero, o un interprete

 el receptor puede fallar en creer (opuesto a dudar o negar creer)
 por una serie de actitudes

 A puede no notar la comunicación del todo
 A puede notar la comunicación y entenderla como lenguaje y hacer algo de ella, pero no
 tomarla como dirigida a el

 u puede notarla y tomarla como lenguaje y sin embargo, sea que la tome como dirigida a
 el o no, puede hacer de ella incorrectamente

 y podría tomarla como dirigida a él y no hacer de ell a incorrectamente pero no creer
 que viene de NN.

** Síntesis:
Un productor inmediato, que puede ser un mensajero o un interprete, ofrece lo que puede
entenderse o declara poder ser entendido como una comunicación de NN.

El receptor de esta comunicación estará en la situación de preguntarse si creer o dudar
de NN si:
Nota la comunicación
Toma la comunicación como lenguaje
Toma la comunicación como dirigda a él
Interpreta la comunicación correctamente
Cree que viene de NN


Presuponiendo que X notó la comunicación, la tomó como lenguaje y como dirigida a él,
la interpretó correctamente y cree que viene de NN; afirmar que X cree a NN es decir
que X confia en NN acerca de la verdad de este asunto particular.

Presuponiendo que X notó la comunicación, la tomó como lenguaje y como dirigida a él,
la interpretó correctamente y cree que viene de NN; afirmar que X duda de NN es decir
que X duda (suspende el juicio ante) de NN acerca de la verdad de este asunto
particular.

Si los presupuestos no se dan, no se puede decir que X cree o duda de NN, sino que
falló en creer, o no llego a estar en la situación de preguntarse si creer a NN o dudar
de él.


** cuestión de la primacia de la verdad sobre la falsedad



* Belief and thought
** assertion
 | decision  | Act of Assent |
 | Intention | Belief        |

 I suddenly believed would mean I suddenly inwardly assented


 at this point we seem to have 2 candidates for the role of initiation act of a
 disposition which is a belief that p

 1. an /occurrent thought/ that /p/ or that /'p'/ is true
 2. an inward assent

 if both these exist there is no difficulty: sometimes one, sometimes the other might
 perform this role.


 Let's address the question of assent

 assent from one person to a proposition formulated by another gives us the picture of 2
 procedures:
 a. the formulation of something assertible --what frege calls judgeable content
 b. the assent to, or inward assertion of, that content

 with this picture in mind it would seem natural to take a view as follows:

 to think has 2 broadly distinct senses:
 1. think is roughly equivalent to 'believe' (or, in appropiate contexts, 'intend')
 2. to have intelligible content before one's mind

 an often dispositional application
 being used in the first sense:
 when a report of thinking implies that the thinker believes what he is thinking

 refers to an episode
 being used in the second sense:
 I suddenly believed him
 or
 just for a moment i thought that...

 the definition of belief as thought plus assent does have some application, but only to
 a restricted range of cases

 it has to be rejected as a general definition because one doesn't have to be thniking
 what one believes

** 'Voicers'
Let's use a new term for
all these first person present indicatives
which form
such 'sustaining frameworks' in our utterances

i will call them 'voicers' for they stand in a special relation to the voicings of our
beliefs and our -various- thoughts.

a voicer is not a performative, though it does share some of the peculiarities of a
performative.

In particular, no voicer is an assertion
* Grounds of belief

**
*Belief on grounds which can be considered as premises for arguments presupposes belief
without grounds, or at any rate without grounds that can be so considered*

Hume's philosophical opinion was that these ultimate groundless grounds were sense
impressions.

But I say that they are such beliefs as those of which one will say 'Everyones knows
that!' <-
there are grounds, premises for arguments, which are not sense impressions, but
traditional knowledge or common knowledge or pieces of traditional knowledge


**

I can obtain an experience which, in view of what I have learned, I shall with
certainty call seeing the present Pope;

i can not optain any experience which I can call seeing Alexander Borgia

BUT
that will not make me any better placed for the rationality
of my belief that there is such a person
as the present pope, than for the rationality of my belief that there was such a person
as Alexander Borgia

MY KNOWLEDGE OF THE THINGS AMONG WHICH AND THE PLACES IN WHICH I LIVE IS NOT SO MUCH
THEORY LADEN, AS COMMON-KNOWLEDGE LADEN

**
 it's a falsification here to speak of testimony:
 to say that it is by testimony that i know that i was born

 there is something else, not testimony, though acquired by education from human beings,
 which is, so to speak, /thicker/ than testimony.


 The work of determining England and fixing the meaning of the name /would/ depend on
 testimony
 -the testimony of many different people for different parts of it

 the work done, people could be taught what England was (no doubt still disputing some
 regions).

 Now those who learned thereafter can hardly be said to have knowledge by testimony.

 They were taught to call something England.

 Something indeed which could in large part only be defined for them by hearsay;
 and they so taught those who came after them

 i am an heir of this tradition

 i would be queer to say i know this by testimony

 it is rather as if i had been taught to join in doing something, than to believe
 something

 -but because everyone is taught to do such things, an object of belief is generated

 the belief is so certainly correct (for it follows the practice)
 that it is knowledge; for here knowledge is no other than certainly correct belief in
 pursuit of a practice

 but the connection with testimony is remote and indirect


* Hume and Julius Caesar (1973)
Section IV part III of Book I of the treatise

Topic: belief in matters falling outside our own experience and memory

when infering effects from causes
we must establish the existence of these causes
either by:

inmediate perception of our memory or senses

or by

 an inference from other causes

these other causes must be ascertained in the same manner

it is impossible to carry on our inferences in infinitum

Hume tries to ilustrate this by an example of historical belief

we believe that caesar was killed....

it is obvious all this chain of argument or connexion of causes and effects is at first
founded on those characters or letters which are seen or remembered

But this is not infering effects from causes, it is infering causes from effects.

As such, fo an historical belief we must have to saying
when we infer effects fromo causes or causes from effects...

when we infer causes from effects we must establish the existence of those effects
either by perception or by inference from other effects which effects we must ascertain
in the same manner by a present impression or by an inference from their effects and so
on, until we arrive at an object which we see or remember



For Hume the relation of cause and effect is the one bridge by which to reach belief in
matters beyond our present impressions or memories

and also cause and effect are inferentially symmetrical

are they?

what is the starting point? (the start of inference or the start of the justification
chain)



The historical example is an inference of the original cause, the killing of Caesar,
from its remote effect, the present perception of certain characters or letters.

The starting-point is the present perception, and from it we can run through a chain of
effects of causes which are effects of causes to the original cause: the killing of
Caesar

the end of the chain is thus not our perception and so it doesn't serve as an
impression of our memory or senses beyond which there is no room for doubt or enquiry
as to stop us going infinitely

"tis impossible for us to carry on our inference in infinitum" means: *the
justification of the grounds of our inferences cannot go on in infinitum* *we must come
to belief which we do not base on grounds*

What Hume is arguing is that we not only have a perception starting point but that we
must reach a starting point in the justification of these inferences

for him tracing back (from effects to causes) is taken to be symmetrical to inferences
from causes to effects

it must be purely hypothetical inference

we reason (purely hypothetically) if Caesar was killed, then there were witnesses , if
there were witnesses then there was testimonies, then there were records made from
them, if there were records made then there are characters and letters to be seen which
say that Caesar was Killed

Four parts of Hume's thesis:

1. a chain of reasons for a belief must terminate in something that is believed without
   being founded on anything else
2. the ultimate belief must be of a quite different character from derived beliefs: it
   must be perceptual belief, belief in something perceived, or presently remembered
3. the immediate justification for a belief p, if the belief is not a perception, will
   be another belief q, which follows from, just as much as it implies, p.
4. we believe by inference through the links in a chain of record

implicit corollary: when we believe in historical information belonging to the remote
past, we believe that there has been a chain of record

Hume must believe all this

*But it is not like that!*


If the written records that we now see are grounds of our belief, they are first and
foremost

*grounds for belief*
in Caesar's killing,
belief that the assasination is a solid bit of history

THEN

our belief in that original event IS A GROUND FOR BELIEF in

much of the intermediate transmission <-



belief in recorded history is on the whole a belief that there has been a chain of
tradition of reports and records going back to contemporary knowledge;

IT IS NOT A BELIEF IN THE HISTORICAL FACTS BY AN INFERENCE THAT PASSES THROUGH THE
LINKS OF SUCH A CHAIN. AT MOST, THAT CAN VERY SELDOM BE THE CASE.

Casting a doubt about Caesar's existence would put us in a vacuum in which there is
nothing by which to judge anything else

What would I be allowed to count as evidence then?

PEOPLE IN HISTORY ARE NOT IN ANY CASE HYPOTHESES WHICH WE HAVE ARRIVED AT TO EXPLAIN
CERTAIN PHENOMENA

A general epistemological reason for duobting one will be a reason for doubting all,
and then none of them would have anythin to test it by

* Motives for beliefs of all sorts

What is a motive?

It wouldn't ordinarily be called a motive;

the term motive seems to be restricted to passions or objects

but if

by motive we mean what prompts one

what is one's ground for doing or omitting anything, then "Someone told me" may well be
said to give me a motive

wether or not it gives a ground for the belief, or gives my ground for the belief, it
does give my ground for doing something -namely believing

this should be called a motive

grounds for believing, this is motive (what prompts me)

grounds for a belief  is not the same as grounds for believing


* Knowledge and Essence (1989)

My objetivo principal es señalar la gran importancia del pensamiento del Tractatus de
que la teoría del conocimiento es filosofía de la psicología.

La importancia es para la historia de la filosofía en el sentido de la historia del
pensamiento filosófico.

No se cuanto ha sido notado, pero aquí, en esta afirmación, 'La teoría del conocimiento
es filosofía de la psicología' un corte queda hecho.

Durante varios siglos la teoríá del conocimiento había sido lo que la metafísica había
sido antes de ellas. Había llegado a ser la teoría de la esencia del mundo, de los
componentes definitivos del universo. Esta corriente empezo a venir con Descartes, si
él se ganó el título 'el padre de la filosofía moderna'. Las olas llegaron a su máxima
altitud con declaración de Kant de haber hecho una revolución Copernicana.

La posición suprema de la teoría del conocimiento estaba garantizada mucho antes que
Kant y se mantuvo incluso entre filósofos como Bertrand Russell que abobinaba  a Kant.

Todavía estaba operativa en Wittgenstein a pesar de su afirmación en el Tractatus.
En "Philosophical Remarks" encontramos la observación: Una proposición es borrador
sobre una verificación.

Se le podría dar una interpretación inocente a esta observación si se le asocia con
Tractatus 4.063:
para ser capaz de decir: '"p" es verdadero (o falso)', debo haber determinado en qué
circunstancias llamo a 'p' verdadero, y haciendo esto determino el sentido de la
proposición

Pero aquí también nos recordamos que la explicación llega a su fin y nos preguntamos si
el determinar del que habla es un determinar por proposiciones adicionales que
describan las circunstancias en las que llamo a una proposición verdadera.

Ciertamente hemos de pensar que no, pues de otro modo la explicación no llegará a su
fin o habrá una invocación de la experiencia con la que si se llega al fin.

Esta última puede estar bien pero no consistirá en una descripción de las
circunstancias en las que llamo 'p' verdadero -- no si esa descripción misma tiene que
tener su sentido indicado por una ulterior descripción del mismo tipo.

A la luz del pensamiento más tardío, podriamos hablar de la experiencia en cuestión
como la de aprender un lenguaje.
...


Las indagaciones interesantes sobre el conocimiento,

una vez que se ha abandonado el
intento de caracterizarlo como un tipo de creer que satisface ciertas condiciones,

conciernen lo que todos, o todos en ciertas culturas, puede ser asumido que conocen una
vez que han crecido y son razonablemente competentes;

y la relación de algunas afirmaciones de conocer con preguntas como ¿cómo lo sabes
(know)?





---
a grammatical imposibility describes the bounds of sense
an epistemic imposibility defines the bounds of knowledge

I am in pain is the expression of a sensation

not a description based on internal or external criteria


* Cual es la estructura del creer en el testimonio?

Anscombe dice que creer en el testimonio es un creer bastante distinto en estructura
que creer en causas y efectos.

Parece que habla de esto en hume and julius caesar y en grounds for belief

puede decirse lo siguiente?

la estructura de creer en el testimonio es la estructura de creer en alguien
la estructura de creer en alguien es

dados los presupuestos
A Nota la comunicación
A Toma la comunicación como lenguaje
A Toma la comunicación como dirigda a él
A Interpreta la comunicación correctamente
A Cree que viene de NN

confiar en NN acerca de la verdad de x cuando una comunicación de NN llega a A por
medio de un productor inmediato.


La estructura de creer en el testimonio de alguien
si entendemos creer en el testimonio de alguien como
creer a x que p

es la estructura de la fe tambien

cual es esa estructura?
dados ciertos presupuestos
x confia en NN acerca de la verdad de p

podemos sacar una descripción de
la categoría del testimonio

de las interconexiones que Anscombe describe
en el "arco" de la verdad, el sentido y la aserción
enunciar y significar son distintos
la rectitud propia de lo que la verdad es aplica tanto a la persona que enuncia como al
enunciado

la persona puede mentir
el enunciado falso cuando es creido significa algo pero no enuncia nada.

la paradoja, distinto de el enunciado falso no significa nada.

el enunciado verdadero hace rectamente aquello para lo que se creó
la persona que dice una proposición verdadera actua rectamente

creer a alguien que dice una proposición verdadera es reconocer la rectitud de la
aserción y reconocer la rectitud de la persona que habla

hay, por tanto un modo de conocer la verdad que se puede describir como

dados los presupuestos
confiar en NN acerca de la verdad de una proposición
cuando la proposición es verdadera tiene rectitud perceptible a la mente
NN actua con rectitud
cuando la proposición es falsa aunque signifique algo no dice nada
cuando la proposición es una paradoja no significa ni comunica nada

la rectitud es perceptible a la mente sin tener que acudir a la experiencia




* Valoraciones finales

En un argumento que tiene caracter de revocabilidad esencial la razonabilidad de un
juicio o conocimiento formado a partir de éste reclama un apoyo externo a sus premisas.
En el caso del creer a alguien que p el que alguien crea lo que dice es este apoyo

Anscombe habla del testigo como una autoridad original, `que él mismo contribuye algo'
en oposición a simplemente transmitir una información recibida sin embargo se puede
decir que se cree a x que p sin que este sea una autoridad original



Se abren tres rutas desde aquí sobre la primacia de la verdad la fe como creer a Dios
que p sobre la estructura del testimonio de la estructura del testimonio se pasa a Hume
on Miracles, de ahí a Prophecy and Miracles



| 1 | 2 |
|   |   |



* [Local Variables]
# Local Variables:
# mode: org
# mode: auto-fill
# word-wrap:t
# truncate-lines: t
# org-hide-emphasis-markers: t
# End:
