#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico/dia_intro.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

  Breve introducción explicando los artículos y orden de presentación, su naturaleza, etc...
  Se presentan en orden cronológico para ver la evolución del pensamiento, aunque más bien es para entablar las relaciones entre los distintos documentos.

  Los Artículos
  Parmenides, Mystery and Contradiction, Hume and Julius Caesar y The Question for Linguistic Idealism se encuentran en From Parmenides to Wittgenstein

  Verdad, sentido y certeza.
  El interés de estos artículos es doble: la noción del lenguaje y de la justificación que tenemos para lo que podemos llamar conocimiento.

  Los Artículos
  On Transubstantiation
  Faith
  En Ethics, Religion and Politics

  Se encuentran junto a What is it to believe someone? y Prophecy and Miracles
  en Faith in a Hard Ground

  En Hume and Juluis Caesar

#+BEGIN_SRC latex
R. Teichmann destaca un reto que podemos encontrar al investigar sobre algún tema específico dentro de la obra de Anscombe:
\blockquote[{\Cite[1]{teichmann2008ans}}: Part of the difficulty in reading Anscombe is in finding your bearings, and this has to do with her eschewal of System. A system or theory often makes things easier for the reader. Once you have grasped N's theory, you can frequently infer what N would have to say on some point by simply `applying' the theory. But it can often be hard to predict in advance what Anscombe will say about some given thing. She is infuriatingly prone to take each case on its merits.]
{Parte de la dificultad en leer a Anscombe está en encontrar nuestro rumbo, y esto tiene que ver con su evasión de Sistema. Un sistema o teoría a menudo hace las cosas más fáciles para el lector. Una vez que haz captado la teoría de $N$, con frecuencia puedes inferir qué tendría que decir $N$ sobre algún punto al simplemente \enquote*{aplicar} la teoría. Pero frecuentemente puede ser difícil predecir de antemano qué dirá Anscombe acerca de alguna cosa dada. Tiene la exasperante tendencia a tomar cada caso en sus propios méritos}. 
Esto no quiere decir que Anscombe carezca de rigor o sistematicidad en sus escritos, sin embargo suele adentrarse \enquote*{in medias res} en sus discusiones con la intención de llegar a algún sitio por la fuerza de sus propias reflexiones sin detenerse a dar mucha explicación de sus presupuestos o del trasfondo de su discusión\footnote{\Cite[Cf.][1]{teichmann2008ans}: \textelp{} there is another reason for the lack of apparent systematicity in Anscombe's writings, and that is that her purpose in writing was typically to get somewhere in her own thoughts on some topic; she usually spends little or no time in providing a background, or in justifying her main `assumptions', preferring to begin \emph{in medias res}.}.
En este apartado se presentan algunos artículos que pueden parecer inconexos puesto que, aunque hay entre ellos temáticas y argumentaciones comunes, Anscombe discurre en cada discusión como un esfuerzo aislado, sin hacer referencia en cada artículo a discusiones previas donde haya desarrollado temas similares o donde haya argumentado las premisas que sirven como presupuestos en otras discusiones. Un ejemplo de esto puede encontrarse en el artículo \emph{What is it to believe someone?} que, aún cuando cuenta con premisas argumentadas en \emph{Faith}, no hace referencia explícita de esta discusión. Aún cuando las reflexiones más tardías no establecen esta referencia explicita a argumentaciones previas, hemos elegido presentar los artículos que se discuten en este apartado en orden cronológico con el fin de visualizar el desarrollo de las ideas de Anscombe a lo largo de su quehacer filosófico. 

Un marco de referencia que sirve para sistematizar de algún modo estos artículos se encuentra en la ubicación de estos ensayos en las colecciones publicadas por Anscombe en 1981 y por M. Geach y L. Gormally entre 2005-2016. Los Artículos \emph{Parmenides, Mystery and Contradiction}, \emph{Hume and Julius Caesar} y \emph{The Question for Linguistic Idealism} se encuentran en el volumen \emph{From Parmenides to Wittgenstein} (1981) que recoge artículos que estudian la relación entre lo posible y lo concebible. Los Artículos \emph{On Transubstantiation} y \emph{Faith} se encuentran en el volumen \emph{Ethics, Religion and Politics} (1981) y \emph{What is it to believe someone?} y \emph{Prophecy and Miracles} en \emph{Faith in a Hard Ground} (2008) donde están recogidas discusiones en las que Elizabeth escribe expresamente desde la enseñanza católica. Teniendo esto en cuenta podemos destacar dos líneas principales de argumentación presentes en estas discusiones. Por un lado nos ofrecen una descripción de lo que constituye `lenguaje significativo', asunto importante para argumentar la capacidad del lenguaje religioso de comunicar la verdad; y por otra parte describen la naturaleza especial de la creencia que llamamos `fe', cuestión relevante para caracterizar los fundamentos de la credibilidad de la revelación.
#+END_SRC
