#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

#+BEGIN_SRC latex
\section{Análisis Diacrónico}
#+END_SRC

* Hume and Julius Caesar 1973                    :published:
:PUBLICATION_INFO:
Originally published in october 1973 vol 34 Issue 1 of Analysis Journal Reprinted in
CPP I in 1981 p. 86-92
:END:
#+BEGIN_SRC latex
\subsection{Hume and Julius Caesar}
#+END_SRC
** Intro 1: este ensayo y los otros
:TEXT:
In the present volume the lengthy paper ‘Hume on causality: introductory’ is the matrix
from which Anscombe extracted ‘Hume and Julius Caesar’ and ‘“Whatever has a beginning
of existence must have a cause”: Hume’s Argument Exposed’.[2] It is published here as
an example of the scrupulous and attentive study she devoted to major philosophers
which is abundantly evident in her unpublished papers.
:END:
#+BEGIN_SRC latex
  Los artículos \emph{Hume and Julius Caesar} y \emph{``Whatever has a beginning
    of existence must have a cause'': Hume’s Argument Exposed} de Anscombe, fueron
  publicados en la revista académica \emph{Analysis} en octubre de 1973 y abril de
  1974 respectivamente. Ambos están relacionados por el tema de la causalidad en
  Hume. En el trasfondo de los dos artículos está otro documento no publicado
  hasta 2011 con el título \emph{Hume on causality: introductory}.
#+END_SRC
** Intro 2: Hume es interesante porque abre buenas cuestiones
#+BEGIN_SRC latex
  Una de las actitudes características de Anscombe es su tendencia a quedar
  atraída por preguntas que representan cuestiones profundas, incluso en
  discusiones cuyos argumentos, método o conclusiones no le parecen tan
  interesantes.

  Un autor que suele tener este efecto en ella es Hume. En \emph{Modern Moral
    Philosophy} dice:

  \blockquote[{\cite[172]{anscombe1981mmph}}: The features of Hume’s philosophy
  which I have mentioned, like many other features of it, would incline me to
  think that Hume was a mere ---brilliant--— sophist; and his procedures are
  certainly sophistical. But I am forced, not to reverse, but to add to this
  judgement by a peculiarity of Hume’s philosophizing: namely that, although he
  reaches his conclusions --—with which he is in love--— by sophistical methods,
  his considerations constantly open up very deep and important problems. It is
  often the case that in the act of exhibiting the sophistry one finds oneself
  noticing matters which deserve a lot of exploring: the obvious stands in need of
  investigation as a result of the points that Hume pretends to have made.]{Las
    características de la filosofía de Hume que he mencionado, como muchas otras
    de sus características, me hacen inclinarme a pensar que Hume era un simple
    ---brillante--- sofista; y sus procedimientos son ciertamente sofísticos. Sin
    embargo me veo forzada, no a retractarme, sino a añadir a este juicio por la
    peculiaridad del filosofar de Hume: a saber, que aunque llega a sus
    conclusiones ---con las que está enamorado--- por métodos sofísticos, sus
    consideraciones constantemente abren problemas bien profundos e importantes.
    Frecuentemente es el caso que en el acto de exhibir la sofística uno se
    encuentra a sí mismo notando temas que merecen mucha exploración: lo obvio
    queda necesitado de investigación como resultado de los puntos que Hume
    pretende haber hecho.}
#+END_SRC
** Fundamento de creencias más allá impresiones es una buena cuestión
#+BEGIN_SRC latex
  En el artículo \emph{Hume and Julius Caesar} la discusión que capta el interés
  de Anscombe se encuentra en la sección IV de la tercera parte del \emph{Treatise
    of Human Nature} sobre el tema de la justificación de nuestro creer en
  cuestiones que están más allá de nuestra experiencia y memoria. Anscombe cita el
  texto de Hume como sigue:

  \blockquote[{\cite[86]{anscombe1981hjc}}When we infer effects from causes, we
  must establish the existence of these causes\ldots either by an immediate
  perception of our memory or senses, or by an inference from other causes; which
  causes we must ascertain in the same manner either by a present impression, or
  by an inference from their causes and so on, until we arrive at some object
  which we see or remember. 'Tis impossible for us to carry on our inferences
  \emph{in infinitum}, and the only thing that can stop them, is an impression of
  the memory or senses, beyond which there is no room for doubt or enquiry.
  (Selby-Bigge's edition, pp. 82--3)]{Cuando inferimos efectos partiendo de causas
    debemos establecer la existencia de estas causas\ldots ya sea por la
    percepción inmediata de nuestra memoria o sentidos, o por la inferencia
    partiendo de otras causas; causas que debemos explicar de la misma manera por
    una impresión presente, o por una inferencia partiendo de sus causas, y así
    sucesivamente hasta que lleguemos a un objeto que vemos o recordamos. Es
    imposible para nosotros proseguir en nuestras inferencias al infinito, y lo
    único que puede detenerlas es una impresión de la memoria o los sentidos más
    allá de la cual no existe espacio para la duda o indagación.}
#+END_SRC
** un presupuesto y dos argumentos:
*** relación causa-efecto puente hacia cuestiones más allá de impresiones
:TEXT:
When we infer effects from causes, we must establish the existence of these causes;
which we have only two ways of doing, either by an immediate perception of our memory
or senses, or by an inference from other causes; which causes again we must ascertain
in the same manner, either by a present impression, or by an inference from their
causes, and so on, till we arrive at some object, which we see or remember.
:END:
#+BEGIN_SRC latex
  Ya en la sección II de esta misma parte del \emph{Treatise}, Hume ha planteado
  cómo es la causalidad la conexión que nos asegura la existencia o acción de un
  objeto que es seguido o precedido por la existencia o acción de
  otro.\footnote{Cf. Treatise Sección II Parte III: ’Tis only causation, which
    produces such a connexion, as to give us assurance from the existence or
    action of one object, that ’twas follow’d or preceded by any other existence
    or action; nor can the other two relations be ever made use of in reasoning,
    except so far as they either affect or are affected by it. }
  Ahora en la sección IV esta relación de causa y efecto será tomada como un
  principio de asociación de ideas según el cual es posible inferir desde la
  impresión de alguna cosa, una idea sobre otra cosa.

  Desde esta noción de causalidad se explica la posibilidad de acceder a hechos
  más allá de nuestra experiencia; estos son inferencias de efectos desde sus
  causas. De este modo: \blockquote[{\cite[87]{anscombe1981hjc}}: For Hume, the
  relation of cause and effect is the one bridge by which to reach belief in
  matters beyond our present impressions or memories.]{Para Hume, la relación de
    causa y efecto es el único puente por el que se puede alcanzar creer en
    cuestiones más allá de nuestras impresiones presentes o memorias.}
#+END_SRC
** Ilustración: punto histórico, por qué razón lo creemos o rechazamos
*** we believe that Caesar was killed
:TEXT:
  To give an instance of this, we may chuse any point of history, and consider for what
  reason we either believe or reject it. Thus we believe that Cæsar was kill’d in the
  senate-house on the ides of March; and that because this fact is establish’d on the
  unanimous testimony of historians, who agree to assign this precise time and place to
  that event. Here are certain characters and letters present either to our memory or
  senses; which characters we likewise remember to have been us’d as the signs of
  certain ideas; and these ideas were either in the minds of such as were immediately
  present at that action, and receiv’d the ideas directly from its existence; or they
  were deriv’d from the testimony of others, and that again from another testimony, by
  a visible gradation, ’till we arrive at those who were eye-witnesses and spectators
  of the event. ’Tis obvious all this chain of argument or connexion of causes and
  effects, is at first founded on those characters or letters, which are seen or
  remember’d, and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain wou’d
  in that case hang upon another; but there wou’d not be any thing fix’d to one end of
  it, capable of sustaining the whole; and consequently there wou’d be no belief nor
  evidence. And this actually is the case with all hypothetical arguments, or
  reasonings upon a supposition; there being in them, neither any present impression,
  nor belief of a real existence.
:END:
#+BEGIN_SRC latex
  El paso adicional que Hume propone en esta sección es que al realizar estas
  inferencias es necesario establecer la existencia de las causas por medio de la
  percepción inmediata de los sentidos o por medio de una ulterior inferencia. Sin
  embargo, el establecimiento de la existencia de estas causas por medio de
  inferencias no puede continuar infinitamente, sino que tiene que llegar a una
  impresión de la memoria o los sentidos que sirva de justificación o fundamento
  definitivo.

  Para ilustrar este paso, Hume hace una invitación interesante:
    \blockquote[{\cite[?]{humetreatise}}: chuse any point of history, and consider
    for what reason we either believe or reject it.]{elegir cualquier punto en la
      historia, y considerar por qué razón lo creemos o rechazamos.} Acerca de una
    creencia histórica se nos invita a considerar sobre qué se sostiene su
    justificación. ¿Cuál es su fundamento?:
    \blockquote[{\cite[?]{humetratise}}: Thus we believe that Cæsar was kill’d in
    the senate-house on the ides of March; and that because this fact is establish’d
    on the unanimous testimony of historians, who agree to assign this precise time
    and place to that event. Here are certain characters and letters present either
    to our memory or senses; which characters we likewise remember to have been us’d
    as the signs of certain ideas; and these ideas were either in the minds of such
    as were immediately present at that action, and receiv’d the ideas directly from
    its existence; or they were deriv’d from the testimony of others, and that again
    from another testimony, by a visible gradation, ’till we arrive at those who
    were eye-witnesses and spectators of the event. ’Tis obvious all this chain of
    argument or connexion of causes and effects, is at first founded on those
    characters or letters, which are seen or remember’d, and that without the
    authority either of the memory or senses our whole reasoning wou’d be chimerical
    and without foundation.]{Así, creemos que César fue asesinado en el Senado en
      los idus de Marzo; y esto porque el hecho está establecido basándose en el
      testimonio unánime de los historiadores, que concuerdan en asignar a este
      evento este tiempo y lugar precisos. Aquí ciertos caracteres y letras se
      hallan presentes a nuestra memoria o sentidos; caracteres que recordamos
      igualmente que han sido usados como signos de ciertas ideas; y estas ideas
      estuvieron ya en las mentes de los que se hallaron inmediatamente presentes a
      esta acción y que obtuvieron las ideas directamente de su existencia; o fueron
      derivadas del testimonio de otros, y éstas a su vez de otro testimonio, por
      una graduación visible, hasta llegar a los que fueron testigos oculares y
      espectadores del suceso. Es manifiesto que toda esta cadena de argumentos o
      conexión de causas y efectos se halla fundada en un principio en los
      caracteres o letras que son vistos o recordados y que sin la autoridad de la
      memoria o los sentidos nuestro razonamiento entero sería quimérico o carecería
      de fundamento.}
#+END_SRC
** Catching Hume on his mistake
*** it must be purely hypothetical inference
#+BEGIN_SRC latex
  Anscombe comienza por reaccionar afirmando:
  \blockquote[{\cite[86]{anscombe1981hjc}}: This is not to infer effects from
  causes, but rather causes from effects.]{Esto no es inferir efectos partiendo de
    sus causas, sino más bien causas desde los efectos.} Es decir, el ejemplo
  histórico de Hume consiste en una inferencia de la causa original, el asesinato
  de Julio César, desde su efecto remoto que es nuestra percepción en el presente.
  Creemos en el asesinato de César porque lo inferimos como la causa última en una
  cadena causal que llega hasta nuestra percepción de ciertas oraciones que
  leemos. El hecho de que estemos leyendo esta información es la percepción que
  justifica la creencia de que hay una cadena de causas y efectos que tiene como
  efecto esta experiencia. Esta inferencia pasa a través de una cadena de efectos
  de causas, que son efectos de causas\ldots ¿Dónde empieza la cadena? La
  respuesta parece ser nuestra percepción presente. ¿Cómo hemos de entender,
  entonces, el argumento de que la cadena no puede continuar infinitamente? La
  propuesta de Hume es que la cadena ha de terminar en una impresión que no deje
  lugar a dudas o busqueda mas allá, sin embargo, la cadena termina en el
  asesinato de Julio César, no en nuestra percepción. La imagen que Hume pretende
  ofrecer es la de una cadena fijada en sus dos extremos por algo distinto a los
  eslabones que la componen, sin embargo, no lo logra, más bien parece describir
  un voladizo, una estructura apoyada en un punto, pero sin apoyo en el otro
  extremo.

  La afirmación \blockquote['Tis impossible for us to carry on our inference in
  infinitum]{Es imposible para nosotros proseguir en nuestras inferencias al
    infinito} viene a significar, según la interpretación de Anscombe, que
  \blockquote[the justification of the grounds of our inferences cannot go on in
  infinitum]{la justificación de los fundamentos de nuestras inferencias no pueden
    continuar al infinito}. El argumento aquí mas bien es que tiene que haber un
  punto de partida para la inferencia de la causa original. La relación de
  inferencias propuesta por Hume en su ilustración acabaría siendo una inferencia
  hipotética según su propia definición. Anscombe explica diciendo:

  \blockquote[hume in causality: We must suppose ourselves to start with the
  familiar idea, merely as idea, of Caesar having been killed. Now if we ask why
  we believe it we shall, as Hume does, point to historical testimony (the
  ‘characters and letters’), which doesn’t at this point figure as what stops
  inference going on ad infinitum. However, if we want to explain the connection
  we shall form the idea of Caesar’s death being recorded by eyewitnesses; and
  these records having been received by others, who transmitted an account ...
  etc. Here we really are arguing from the idea of an original cause to the idea
  of an effect; we are ‘inferring effects from causes’, though only in the sense
  of passing from the idea of the cause to the idea of the effect.]{Tendríamos que
    suponer que comenzamos con la idea familiar, meramente como una idea, de que
    César fue asesinado. Ahora si preguntamos por qué lo creemos hemos de, como
    hace Hume, señalar al testimonio histórico (los `caracteres y letras'), lo
    cual en este punto no figura como lo que detiene que la inferencia siga al
    infinito. Sin embargo, si queremos explicar la conexión tenemos que formular
    la idea de la muerte del Cesar siendo recordada por testigos; y esos recuentos
    siendo recibidos por otros, quienes transmitieron un informe\ldots etc. Aquí
    estamos realmente razonando desde la idea de una causa original a la idea de
    un efecto; estamos `infiriendo efectos de causas', pero solo en el sentido de
    pasar de la idea de la causa a la idea del efecto.}

  Desde este análisis, Anscombe resume lo argumentado por Hume en cuatro partes:

  \blockquote[humeandjulius 88: First, a chain of reasons for a belief must
  terminate in something that is believed without being founded on anything else.
  Second, the ultimate belief must be of a quite different character from derived
  beliefs: it must be perceptual belief, belief in something perceived, or
  presently remembered. Third, the immediate justification for a belief p, if the
  belief is not a perception, will be another belief q, which follows from, just
  as much as it implies, p. Fourth, we believe by inference through the links in a
  chain of record

  There is an implicit corollary: when we believe in historical information
  belonging to the remote past, we believe that there has been a chain of record]{
    Primero, una cadena de razones para una creencia debe terminar en algo que se
    cree sin estar fundado en alguna otra cosa. Segundo, la creencia última debe
    ser de una naturaleza distinta a las creencias derivadas: Tiene que ser
    creencia perceptual, creer en algo percibido, or recordado en el presente.
    Tercero, la justificación inmediata de una creencia $p$, si la creencia no es
    una percepción, será otra creencia $q$, la cual se sigue, en la misma medida
    que implica, a $p$. Cuarto, creemos por inferencia a través de los eslabones
    en una cadena de relato.

    Hay un corolario implicito: cuando creemos en información histórica
    perteneciente a un pasado remoto, creemos que ha habido una cadena de relato.}

  Sin embargo, Anscombe considera que esta no es la manera adecuada de establecer
  esta relación. Mas bien: \blockquote[hjc 88: \emph{If} the written records that
  we now see are grounds of our belief, they are first and foremost grounds for
  belief in Caesar's killing, belief that the assassination is a solid bit of
  history. Then our belief in that original event is a ground for belief in much
  of the intermediate transmision.]{\emph{Si} los relatos escritos que vemos ahora
    son fundamento para nuestro creer, estos son primero y ante todo fundamento
    para la creencia en el asesinato de Cesar, creencia en que el asesinato es un
    pedazo sólido de historia. Entonces nuestra creencia en ese evento original es
    fundamento para el creer en mucha de la transimisión intermedia.}
  ¿Por qué creemos que hubo testigos del asesinato? Ciertamente porque creemos que
  hubo un asesinato. La creencia de que hubo testigos es inferida de la creencia
  en el hecho.

  Anscombe compara este modo de entender la cadena de transmisión de información
  histórica a nuestra creencia en la continuidad espacio-temporal. Si reconocemos
  en una ocasión a una persona conocida como alguien que vimos la semana pasada,
  nuestra creencia en que es la misma persona no es una inferencia de otra
  creencia acerca de la continuidad espacio-temporal de un patrón humano desde
  ahora hasta entonces, sino que más bien nuestra creencia en la continudad
  espacio-temporal esta inferida del reconocimiento de la identidad de la persona.
  Sin embargo, una evidencia sobre una interrupción en la continuidad sí alteraría
  nuestra creencia en la identidad.

  Elizabeth entonces concluye que: \blockquote[hjc 89: Belief in recorded history is
  on the whole a belief that there has been a chain of tradition of reports and
  records going back to contemporary knowledge; it is not a belief in the
  historical facts by an inference that passes through the links of such a chain.
  At most, that can very seldom be the case.]{La creencia en los registros de la
    historia consiste en general la creencia de que ha habido una cadena de
    tradición de informes y registros que van hacia el conocimiento contemporaneo;
    no es una creencia en hechos históricos por una inferencia que pasa por los
    eslabones de una cadena como esta. Como mucho, esto seria muy raramente el
    caso.}

  Ahora bien, como se ha dicho antes, el interés de Anscombe no esta simplemente
  en mostrar en que se equivoca Hume, sino que considera que la cuestión toca el
  nervio de un problema con cierta profundidad:
  \blockquote[causality in hume 2855: The interesting problem that arises, then,
  is why the things we are told and the writings that we see are the starting
  points for our belief in the far distant events and so in the intermediate chain
  of record.]{El problema interesante que surge, entonces, es por qué las cosas
    que se nos dicen y los escritos que vemos son puntos de partida para nuestro
    creer en eventos distantes y así también en la cadena del relato intermedia.}
#+END_SRC
*** no es posible continuar infinitamente una cadena de inferencias
:TEXT:
’Tis impossible for us to carry on our inferences in infinitum; and the only thing,
that can stop them, is an impression of the memory or senses, beyond which there is no
room for doubt or enquiry.
:END:
+BEGIN_SRC latex
  El argumento de Hume, entonces, se compone de dos partes.
  En primer lugar, una cadena de inferencia en la cual "ya que p, q, etc..."
  en la que p da una causa creida (no percibida) y q un efecto inferido, no puede continuar
para siempre, sino que tiene que terminar n

  Determina que estas inferencias no pueden continuar infinitamente. Si se tratara
  de mera relación especulativa de conceptos no representaría dificultad, pero se
  trata de creer, y la cadena no podría ofrecer una creencia si no tiene término.
  \blockquote[{\cite[2762]{anscombe2011hoc}}: Now there really is no difficulty
  about going on ad infinitum, or at any rate about saying ‘and so on ad
  infinitum’, if the ‘inferring’ is simply deriving the idea of the effect from
  that of the cause. But the inferring is more than that ---it is believing. It is
  in connection with this that Hume is saying ‘this chain can’t go on for
  ever’.]{Ahora realmente no hay dificultad en ir infinitamente, o en cualquier
    caso decir `así sucesivamente infinitamente', si el `inferir' es simplemente
    derivar la idea del efecto partiendo de su causa. Pero el inferir es más que
    eso ---es creer. Es en conexión con esto que Hume dice `esta cadena no puede
    seguir para siempre'}

  First, a chain ‘Since p, q, etc’ in which p gives a believed-in (not perceived)
  cause and q an inferred effect, cannot go on for ever but must terminate in a
  proposition that is believed without inferring any consequences from it; and
  from this proposition we then work back in reverse order to p.

  This is a particular form of a familiar argument that not everything can be
  argued from something else, that is: that it cannot be the case that everything
  is argued from something else. I believe p because I believe q because I believe
  r because I believe s ---this cannot go on for ever; it must end in something
  which I believe, not because I believe something else. This argument appears to
  be correct.

#+END_SRC
*** el término de la cadena de inferencias no puede ser otra inferencia
+BEGIN_SRC latex
Hume’s second point is that not merely must the chain that he is concerned with
come to an end somewhere, but its terminus must be of a different kind from the
other members. ... without the authority either of the memory or the senses our
whole reasonings wou’d be chimerical and without foundation. Every link of the
chain wou’d in that case hang upon another; but there wou’d not be anything
fix’d to one end of it, capable of sustaining the whole; and consequently there
wou’d be no belief or evidence.[27]


The second part of his argument, which says that the terminus must be of a
different character from the links of the chain, is more doubtful than the first
part which only says there must be a terminus. Hume does not think that I have
to have a present perception (of memory or sense) in connection with my belief
that Caesar was killed in the Senate House: we can ‘reason upon our past
conclusions and principles, without having recourse to those impressions from
which they first arose.’ The convictions, however, must have been produced by
impressions, and ‘all reasonings concerning causes and effects are originally
deriv’d from some impression’.
#+END_SRC

*** hume's thesis falls into four parts
*** two comparisons: identity and proper names
#+BEGIN_SRC latex

#+END_SRC

** Conclusion:perception of records>belief distant event>chain of record

** Not just catching the mistake, but seeing what to say about this
The interesting problem that arises, then, is why the things we are told and the
writings that we see are the starting points for our belief in the far distant events
and so in the intermediate chain of record. This is a question of vast importance. But
the consideration of it would take us far away from that investigation of Hume on cause
which has been our present business. I take it as sufficiently demonstrated that Hume’s
account is wrong. (One may be convinced of that without thinking that one has an
alternative account.)
** Wittgenstein: On Certainty


So it turns out when I say things like “Here is a hand” I’m not really making a claim
about the world, I’m laying down some rules for discussion. If you doubt there’s a hand
here, then fuck you and that’s all there is to it. We can’t really talk about anything
now, because we can’t even agree on something as simple as a goddamn hand. When we all
agree here is a hand, then we can go about discussing our world in meaningful ways.
Skepticism just undermines a foundation and replaces it with nothing; its paralyzing.
The grounds for such radical skepticism don’t exist; it presupposes and relies on the
very certainty it tries to undermine.

The hypothesis that Julius Caesar might turn out never to have existed can be rejected,
once the details of that hypothesis have been demanded.

#+BEGIN_SRC latex
  Para discutir esta cuestión Anscombe recurre a las reflexiones de Wittgenstein
  en \emph{On Certainty}



  8. The ditference between the concept of 'knowing' and the concept of 'being
  certain' isn't of any great importance at all, except where "I know" is meant to
  mean: I can't be wrong. In a law-court, for example, "I am certain" could
  replace "I know" in every piece of testimony. We might even imagine its being
  forbidden to say "I know" there. [A passage in WiZheZm Meister, where "You know"
  or "You knew" is used in the sense "You were certain", the facts being different
  from what he knew.]

  12. -For "I know" seems to describe a state of affairs which guarantees what is
  known, guarantees it as a fact. One always forgets the expression "I thought I
  knew".

  13. For it is not as though the proposition "It is so" could be inferred from
  someone else's utterance: "I know it is so". Nor from the utterance together
  with its not being a lie.-But can't I infer "It is so" from my own utterance "I
  know etc."? Yes; and also "There is a hand there" follows from the proposition
  "He knows that there's a hand there". But from his utterance "I know . . ." it
  does not follow that he does know it.

  14- That he does know takes some shewing. I j. It needs to be shewtz that no
  mistake was possible. Giving the assurance "I know" doesn't suffice. For it is
  after all only an assurance that I can't be making a mistake, and it needs to be
  objectiueb established that I am not making a mistake about that.

  2 1. Moore's view really comes down to this: the concept 'know' C is analogous
  to the concepts 'believe', surmise', 'doubt', 'be convinced' in that the
  statement "I know . .. ." can't be a mistake. And if that is so, then there can
  be an inference from such an utterance to the truth of an assertion. And here
  the form "I thought I knew" is being overlooked.-But if this latter is
  inadmissible, then a mistake in the assertion must be logically impossible too.
  And anyone who is acquainted with the language-game must realize thisan
  assurance from a reliable man that he hows cannot contribute anything. 22. It
  would surely be remarkable if we had to believe the reliable person who says "I
  can't be wrong"; or who says "I am not wrong".

  94. But I did not get my picture of the world by satisfying
  myself of its correctness: nor do I have it because I am satisfied
  of its correctness. No: it is the inherited background against
  which I distinguish between true and false.



  204. Giving grounds, however, justifying the evidence, comes
  to an end;-but the end is not certain propositions' striking us
  immediately as true, i.e. it is not a kind of seeing on our part;
  it is our acting, which lies at the bottom of the language-game.
  205. If the true is what is grounded, then the ground is not
  true, nor yet false.
  206. If someone asked us 'but is that true?" we might say "yes"
  to him; and if he demanded grounds we might say "I can't give
  you any grounds, but if you learn more you too will think the
  same".
  If this didn't come about, that would mean that he couldn't
  for example learn history.
  207. "Strange coincidence, that every man whose skull has
  been opened had a brain!"


  3 I I. Or imagine that the boy questioned the truth of history
  (and everything that connects up with it)--and even whether the
  earth had existed at all a hundred years before.
  3 I 2. Here it strikes me as if this doubt were hollow. But in that
  case-isn't belief in history hollow too ? No; there is so much that
  this connects up with.


  167. It is clear that our empirical propositions do not all have
  the same status, since one can lay down such a proposition and
  turn it from an empirical proposition into a norm of description.
  Think of chemical investigations. Lavoisier makes experiments
  with substances in his laboratory and now he concludes that this
  and that takes place when there is burning. He does not say that
  it might happen otherwise another time. He has got hold of a
  definite world-picture-not of course one that he invented:
  he learned it as a child. I say world-picture and not hypothesis,
  because it is the matter-of-course foundation for his research and
  as such also goes unmentioned.


  24j To whom does anyone say that he knows something? To
  himself, or to someone else. If he says it to himself, how is it
  distinguished from the assertion that he is sure that things are like
  that? There is no subjective sureness that I know something. The


  certainty is subjective, but not the knowledge. So if I say "I
  know that I have two hands", and that is not supposed to express
  just my subjective certainty, I must be able to satisfy myself that
  I am right. But I can't do that, for my having two hands is not
  less certain before I have looked at them than afterwards. But I
  could say: 'That I have two hands is an irreversible belief." That
  would express the fact that I am not ready to let anything count
  as a disproof of this proposition.
  246. "Here I have arrived at a foundation of all my beliefs."
  "This position I will holdl" But isn't that, precisely, ody because
  I am completely convinced of it ?-What is 'being. completely convinced' like ?
  247. What would it be like to doubt now whether I have two
  hands ? Why can't I imagine it at all? What would I believe if I
  didn't believe that? So far I have no system at all within which -
  this doubt might exist.
  248. I have arrived at the rock bottom of my convictions.
  -~nd one might almost say that these fhdation-walls are
  carried by the whole house.
  249. One gives oneself a false picture of doubt.
  2 j O. My having two hands is, in normal circumstances, as certain
  as anything that I could produce in evidence for it.
  That is why I am not in a position to take the sight of my hand
  as evidence for it.
  2 j I. Doesn't this mean: I shall proceed according to this belief
  unconditionally, and not let anything confuse me ?
  2~2. But it isn't just that I believe in this way tha.t I have two
  hands, but that every reasonable person does.
  25 3. At the foundation of well-founded belief lies belief that is
  not founded.
  2 j4. Any 'reasonable' person behaves like this
#+END_SRC

* Prophecy and Miracles

p. 37 Now what does this rest on? It might rest on faith. In Deuteronomy, when the Jews were
forbidden to consult soothsayers and necromancers, and omens, they were promised
prophets ‘like Moses’ whom they were to attend to instead.
