#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* Hume and Julius Caesar 1973                    :published:
:PUBLICATION_INFO:
Originally published in october 1973 vol 34 Issue 1 of Analysis Journal Reprinted in
CPP I in 1981 p. 86-92
:END:
** Intro 1: este esnayo y los otros
** Intro 2: Hume es interesante porque abre buenas cuestiones
** Fundamento de creencias más allá impresiones es una buena cuestión
** Dos argumentos:
*** relación causa-efecto puente hacia cuestiones más allá de impresiones
When we infer effects from causes, we must establish the existence of these causes;
which we have only two ways of doing, either by an immediate perception of our memory
or senses, or by an inference from other causes; which causes again we must ascertain
in the same manner, either by a present impression, or by an inference from their
causes, and so on, till we arrive at some object, which we see or remember.
*** no es posible continuar infinitamente una cadena de inferencias
’Tis impossible for us to carry on our inferences in infinitum; and the only thing,
that can stop them, is an impression of the memory or senses, beyond which there is no
room for doubt or enquiry.
** Ilustración: punto histórico, por qué razón lo creemos o rechazamos
*** we believe that Caesar was killed
  To give an instance of this, we may chuse any point of history, and consider for what
  reason we either believe or reject it. Thus we believe that Cæsar was kill’d in the
  senate-house on the ides of March; and that because this fact is establish’d on the
  unanimous testimony of historians, who agree to assign this precise time and place to
  that event. Here are certain characters and letters present either to our memory or
  senses; which characters we likewise remember to have been us’d as the signs of
  certain ideas; and these ideas were either in the minds of such as were immediately
  present at that action, and receiv’d the ideas directly from its existence; or they
  were deriv’d from the testimony of others, and that again from another testimony, by
  a visible gradation, ’till we arrive at those who were eye-witnesses and spectators
  of the event. ’Tis obvious all this chain of argument or connexion of causes and
  effects, is at first founded on those characters or letters, which are seen or
  remember’d, and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain wou’d
  in that case hang upon another; but there wou’d not be any thing fix’d to one end of
  it, capable of sustaining the whole; and consequently there wou’d be no belief nor
  evidence. And this actually is the case with all hypothetical arguments, or
  reasonings upon a supposition; there being in them, neither any present impression,
  nor belief of a real existence.
** Catching Hume on his mistake
***
** Conclusion:perception of records>belief distant event>chain of record
** Not just catching the mistake, but seeing what to say about this
** Wittgenstein: On Certainty


So it turns out when I say things like “Here is a hand” I’m not really making a claim
about the world, I’m laying down some rules for discussion. If you doubt there’s a hand
here, then fuck you and that’s all there is to it. We can’t really talk about anything
now, because we can’t even agree on something as simple as a goddamn hand. When we all
agree here is a hand, then we can go about discussing our world in meaningful ways.
Skepticism just undermines a foundation and replaces it with nothing; its paralyzing.
The grounds for such radical skepticism don’t exist; it presupposes and relies on the
very certainty it tries to undermine.

The hypothesis that Julius Caesar might turn out never to have existed can be rejected,
once the details of that hypothesis have been demanded.
