#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

#+BEGIN_SRC latex
\section{Análisis Diacrónico}
#+END_SRC

* Prophecy and Miracles 1957
#+BEGIN_SRC latex
\subsection{Prophecy and Miracles}
#+END_SRC

#+BEGIN_SRC latex
  El texto de \emph{Prophecy and Miracles} ha sido publicado en \emph{Faith in a
    Hard Ground} de la colección de St. Andrew's. Con mucha probabilidad es el
  texto de una ponencia ofrecida en 1957 en el \emph{Philosophical Enquiry Group}
  que solía reunirse en el Centro de Conferencias de los Dominicos en \emph{Spode
    House, Staffordshire}.
#+END_SRC
#+BEGIN_SRC latex
  Anscombe especifica las coordenadas de su discusión en torno a tres documentos:
  \begin{enumerate}
  \item La constitución dogmática \enquote{Dei Filius}, específicamente el
    capítulo tercero donde afirma: \blockquote[Ut nihilominus fidei nostrae
    obsequium rationi consentaneum esset, voluit Deus cum internis Spiritus Sancti
    auxiliis externa iungi revelationis suae argumenta, facta scilicet divina,
    atque imprimis miracula et prophetias, quae cum Dei omnipotentiarn et
    infinitam scientiam luculenter commonstrent, divinae revelationis signa sunt
    certissima et omnium intelligentiae accommodata. Quare tum Moyses et
    Prophetae, tum ipse maxime Christus Dominus multa et manifestissima miracula
    et prophetias ediderunt; et de Apostolis legimus: Illi autem profecti
    praedicaverunt ubique, domino cooperante, et sermonem confirmante, sequentibus
    signis (Mare. XVI, 20). Et rursum scriptum est: Habemus firmiorem propheticum
    sermonem, cui bene facitis attendentes quasi lucernae lucenti in caliginoso
    loco (2 Petr. I, 19).]{Sin embargo, para que el obsequio de nuestra fe sea de
      acuerdo a la razón, quiso Dios que a la asistencia interna del Espíritu
      Santo estén unidas indicaciones externas de su revelación, esto es, hechos
      divinos y, ante todo, milagros y profecías, que, mostrando claramente la
      omnipotencia y conocimiento infinito de Dios, son signos ciertísimos de la
      revelación y son adecuados al entendimiento de todos. Por eso Moisés y los
      profetas, y especialmente el mismo Cristo Nuestro Señor, obraron muchos
      milagros absolutamente claros y pronunciaron profecías; y de los apóstoles
      leemos: <<Salieron a predicar por todas partes, colaborando el Señor con
      ellos y confirmando la Palabra con las señales que la acompañaban>>. Y
      nuevamente está escrito: <<Tenemos una palabra profética más firme, a la
      cual hacéis bien en prestar atención, como a lámparas que iluminan en lugar
      oscuro>>.}
  \item La advertencia del Deuteronomio: \blockquote{Todo lo que yo os mando, lo
      debéis observar y cumplir; no añadirás ni suprimirás nada. Si surge en medio
      de ti un profeta o un visionario soñador y te propone: \enquote{Vamos en pos
        de otros dioses ---que no conoces--- y sirvámoslos}, aunque te anuncie una
      señal o un prodigio y se cumpla la señal o el prodigio, no has de escuchar
      las palabras de ese profeta o visionario soñador. (Dt 13, 1--4a)}
  \item \emph{On the proof of the spirit and of Power} de Lessing. Del cual
    considera varios puntos, pero se enfoca en su argumento central:
    \blockquote[Who denies it ---I do not--- that the reports of those miracles
    and prophecies are just as trustworthy as any historical truth can be? ---But
    now: if they are only so trustworthy, why are they so used as suddenly to make
    them infinitely more trustworthy? How? By building quite different things, and
    more things, on them, than one is entitled to build on historically evidenced
    truths. If no historical truth can be demonstrated, then neither can anything
    be demonstrated by historical truths. That is: accidental historical truths
    can never become the proof of necessary truths of reason.]{}
  \end{enumerate}

  En éste documento afirma: \enquote{It is one thing to experience the fulfilment
    of prophecy; fulfilled prophecies of which I know only as a matter of history
    that others are supposed to have experienced them, are quite another thing.}
  Junto a esto añade: \enquote{Those that take place before my own eyes have their
    effect in an immediate way; the others are supposed to have their effect
    through a medium that deprives them of all power.}

  We all believe that there was such a person as Alexander, who conquered almost
  all Asia in a short time. But who would stake something of great and permanent
  importance, whose loss was irreplaceable, on this belief? Who, in consequence of
  this belief, would forswear for ever all knowledge that should concflict with
  it? Certainly I should not. I have at present nothing to object against
  Alexander and his conquests; but it would after all be possible that they were
  founded on a mere poem of Choerilus who accompanied Alexander, just as the ten
  year siege of Troy is founded on nothing but Homer.

  That Christ, against whose resurrection I have no significant historical
  objection, gave himself out as the son of God on account of it; that his
  disciples believed he was that on account of it; this I readily believe. For
  these truths, as truths of one and the same class, follow quite naturally one
  from the other.
  But now, leap from that historical truth to a quite different class of truths,
  and to demand of me that I should transform all my metaphysical and moral
  concepts accordingly; to expect me, because I can set no trustworthy evidence
  against the resurrection of Christ, to alter all my fundamental ideas of the
  deity---if that is not metabasis eis allo genos then I don't know what Aristotle
  meant by that term.
  Of course, you say: this Christ, who rose from the dead---which you admit as an
  historical fact---this Christ said that God had a son of the same nature as
  himself and that he was that son.---Splendid! If only the fact Christ said this
  were not equally merely historically certain.

  The most central part of his argument comes in the following passage:

  El argumento de Lessing en este ensayo es más complicado de lo que parece.
  Anscombe distingue varios puntos.

  1. Puede parecer extraño que emplee el dato de que podríamos haber sabido de
  Alejandro Magno solo por el poema de Coerilio para justificar que no podemos
  basar nada con certeza perfecta en la existencia de Alejandro, pero hay dos
  razónes para esta afirmación.

  a) Puede que aquí haya una alusión al hecho de que
  sabemos de las palabras y obras de Cristo por medio de una única fuente, el
  Nuevo Testamento. Cierto es que son múltiples libros, pero se sostiene su punto
  dado que está escrito por miembros de un grupo específico.

  b) El motivo principal se hace claro cuando habla de las accidentales verdades
  históricas como no pudiendo ser justificación para verdades necesarias de razón

  el piensa que una verdad necesaria de razón, una verdad metafísica, y una verdad
  tal, como una verdad matemática no puede seguirse de un hecho histórico, si esto
  fuera así, la verdad histórica debería ser tant cierta como se supone que sea
  una verdad metafísica, pero una verdad histórica puede tener muy poca certeza,
  como lo sería alexander, si solo conocieramos de él por el poema de Coerilio


  Pienso que no merece nuestra atención, puesto que el supuesto de que cualquier
  cosa creíble sobre Dios tiene que ser \enquote{una verdad de razón en tanto que
    necesaria} es peor que dudoso; es incoherente. Esto posiblemente deriva de
  nociones Leibnizianas de \enquote{ser necesario}, lo que espero que podamos
  considerar como hecho explosión: y esto va con la idea de Lessing, que se ha
  tornado tan difundida, que las verdades de la religión tienen todas que ser
  tales que la raza humana podría al final haberlas pensado por sí misma.

  2. Desde la perspectiva de la Constitución de Vaticano I, la insistencia de
  Lessing de que las verdades históricas nunca pueden ser suficientemente certeras
  puede se poco importante.

  No hay nada en él acerca de una demostración de la verdad del cristianismo; solo
  sobre argumentos externos solidos

  estos solidos argumentos externos no pretenden demostrar,

  por tanto, alta probabilidad, que Lessing está dispuesto a conceder, puede ser
  suficiente para constituir solidos argumentos externos

  desde luego que Lessing no estaría de acuerdo con un argumento meramente
  probable para verdades necesarias

  sin embargo sí sería un problema respecto de la fe, que debería de ser cierta,
  si sus fundamentos son como mucho probables, qué excusa podría tener entonces?
  Esto haría de los fundamentos probables algo irrelevante

  Podriamos entenderlo así,
  una persona puede tener lo que le resultan fundamentos probables, y abrazar la
  fe cristiana, y luego descubrir que sus fundamentos no eran más que argumentos
  débiles y errores históricos, sin embargo, se supone que se abrace a la fe
  igualmente, así sus fundamentos solo fueron la escalera que pateó al subir,
  importante solo psicologicamente....
  seria un error pensar que una escalera como esta conduce correctamente a la fe,
  excepto si cualquier escalera bastara.
  parece que sí hay algo en la afirmación de lessing de sobre construir cosas
  sobre verdades históricas sobre las cuales uno no tiene el derecho de construir,
  y esto permanece, incluso cuando se descarte su visión de que cualquier cosa
  creida sobre Dios debe ser una verdad necesaria.

  3. Su posición es ciertamente incompatible con el creer cristiano
  parece estar yendo en contra de cierto argumento, no contra las creencia
  crisitanas
  como diciendo, si las sostienes es por otros fundamentos y no estos

  Distingue entre la religión de Cristo y la religión cristiana
  distingue lo difuso de lo claro, lo difuso corresponde a la religión cristiana,
  lo claro a la relgión de Cristo,
  él mismo emplea la analogía entre religión y verdades matemáticas: que
  importaría si, históricamente, algún procedimiento fraudulento condujo a una
  verdad matemática

  4. La prueba de poder y de fuerza es en milagros y profecias contemporaneas
  Lessing exagera grandemente la certeza que Origenes puede haber tenido sobre
  estas. Aquí es útil ser católico, pues los católicos no dicen como otros que no
  hay milagros ya,
  tanto antes como ahora los no creyentes reaccionaban a los milagros con la misma
  incredulidad que ahora.
  Pero quizas todo esto es para servir al argumento y Lessing era de hecho
  bastante esceptico hacia todos los milagros y profecías, no lo sé
#+END_SRC


- Preamble, before considering Lessing's central argument

- His argument boils down to: 'But these things may not be true, so how can I use them
  to support Christianity?'
- Miracles and fulfilled prophecies are said to offer solid external arguments for the
  truth of christianity, but isn't there a theological element in calling something a
  fulfilled prophecy or miracle?
- Lessing seems right in saying that the reports of miracles could not be expected to
  appeal to an external judge
- Lessing seems to be wrong in saying that 'no historical certainty can be strong enough
  to be absolute'
  + If it is strength of certainty that is really in question
    - it is not true that historical certainty is always too weak to base absolute
      certainty upon it
      + Probability may come in regarding an historical truth, but it doesn't begin to
        come in at the start
      + Anscombe objects to Lessing's lumping together everything historical as of
        inferior certainty to our own experience
    - That Christ claimed to be the Son of God and that he rose from the dead belongs
      to a class of historical assertions which it would be absurd to claim certainty
      for, but the time for disproving which is past.
    - What would be solid in this fashion is that Christ existed, preached, like an Old
      Testament prophet, and was at least ostensibly crucified under Roman authority;
      and that believers took him for the Messiah and the son of God, and believed he
      had risen from the dead
  + If we stick to things that are solid, and avoid what may be regarded as accidential
  + Lessing disputes priority and certainty
- The critical principle that prophetical wriings must have been clealy intelligible in
  their own time is itself a denial of the possibility of all but prophecy of a very
  restricted type
  + That is to say: for almost all prophecies, to see them fulfilled is to interpret
    them
- Prophecies must attest something
- If all this is so, the impartial indifferent observer is confronted quite certainly
  only with a few scattered prophecies relating to cities and peoples; and with reports
  of miracles and of fulfilments of prophecies which it is absurd to pretend he must
  regard as certainly true.
  - So what becomes of the 'solid external arguments'?
- Only if a man is impressed by the Old Testament, to the extent of being inclined to
  take it as his teacher, has the argument from prophecies and miracles any serious
  weight.
- When St. Agustine said that fulfilment of the prophecies in Christ was the greates
  proof of his divinity, what he said was true; but the proof requires a very special
  position on the part of someone who is to consider it.
  - This is why the kind of apologetic that Lessing argued against, which did not
    assume that position, was so vulnerable and stupid.
- The miracles are consonant, That God attested Christ by miracles is possible, if he
  is the Messiah promised in the Old Testament.
  - The problem about how these seemingly factual records came to be written, of such
    incredible things, is resolved by the hypothesis that they happened.
- With this we come to the problem of the notion of divine attestation at all.
  - There has to be a thesis of natural theology, that if someone works 'a sign and a
    wonder' or utters a prophecy which gets fulfilled, in God's name, then he is
    divinely attested.
  - This might be taken as a matter of faith, but then, what about the 'solid external
    arguments'?
  - I think the argument must be rather that if a prophet who is apparently teaching
    that truth, dares to foretell something contingent, then this is presumption of him
    unless he has it from God and must say it. Now if he teaches a lie straight away
    afterwards, or if the thing does not happen, then he is proved presumptuous. But if
    he is not proved presumptuous, then we ought not to dare not to believe and obey
    him: so long as what he says does not conflict with the known truth.


So far as I can see there has to be a *thesis of natural theology*, as I might call it,
that if someone works ‘a sign and a wonder’ or utters a prophecy which gets fulfilled,
in God’s name, then he is divinely attested. Now what does this rest on? It might rest
on faith. In Deuteronomy, when the Jews were forbidden to consult soothsayers and
necromancers, and omens, they were promised prophets ‘like Moses’ whom they were to
attend to instead. But, the passage goes on, they’ll want to know how to tell a
prophet. And the answer is: if the prophet foretells something, and it doesn’t happen,
then that was just his presumption. The implication seems to be that if a prophet of
their people, apparently teaching according to the Law, foretells something and it does
happen, he is attested.


p. 37 Now what does this rest on? It might rest on faith. In Deuteronomy, when the Jews
were forbidden to consult soothsayers and necromancers, and omens, they were promised
prophets ‘like Moses’ whom they were to attend to instead.

* Hume and Julius Caesar 1973                    :published:
:PUBLICATION_INFO:
Originally published in october 1973 vol 34 Issue 1 of Analysis Journal Reprinted in
CPP I in 1981 p. 86-92
:END:
#+BEGIN_SRC latex
\subsection{Hume and Julius Caesar}
#+END_SRC
** Intro 1: este ensayo y los otros
:TEXT:
In the present volume the lengthy paper ‘Hume on causality: introductory’ is the matrix
from which Anscombe extracted ‘Hume and Julius Caesar’ and ‘“Whatever has a beginning
of existence must have a cause”: Hume’s Argument Exposed’.[2] It is published here as
an example of the scrupulous and attentive study she devoted to major philosophers
which is abundantly evident in her unpublished papers.
:END:
#+BEGIN_SRC latex
  Los artículos \emph{Hume and Julius Caesar} y \emph{``Whatever has a beginning
    of existence must have a cause'': Hume’s Argument Exposed} de Anscombe, fueron
  publicados en la revista académica \emph{Analysis} en octubre de 1973 y abril de
  1974 respectivamente. Ambos están relacionados por el tema de la causalidad en
  Hume. En el trasfondo de los dos artículos está otro documento no publicado
  hasta 2011 con el título \emph{Hume on causality: introductory}.
#+END_SRC
** Intro 2: Hume es interesante porque abre buenas cuestiones
#+BEGIN_SRC latex
  Anscombe again and again found in Hume a starting point for her discussions; and
  we must not be misled bye her frequent dissent from his views into thinking of
  her as `anti-Humean'. Indeed, in her treatment of the topic of causation
  Anscombe can even be seen as continuing Hume's work---as out-Huming Hume.
  teichmann 177

    Una de las actitudes características de Anscombe es su tendencia a quedar
    atraída por preguntas que representan cuestiones profundas, incluso en
    discusiones cuyos argumentos, método o conclusiones no le parecen tan
    interesantes.

    Un autor que suele tener este efecto en ella es Hume. En \emph{Modern Moral
      Philosophy} dice:

    \blockquote[{\cite[172]{anscombe1981mmph}}: The features of Hume’s philosophy
    which I have mentioned, like many other features of it, would incline me to
    think that Hume was a mere ---brilliant--— sophist; and his procedures are
    certainly sophistical. But I am forced, not to reverse, but to add to this
    judgement by a peculiarity of Hume’s philosophizing: namely that, although he
    reaches his conclusions --—with which he is in love--— by sophistical methods,
    his considerations constantly open up very deep and important problems. It is
    often the case that in the act of exhibiting the sophistry one finds oneself
    noticing matters which deserve a lot of exploring: the obvious stands in need of
    investigation as a result of the points that Hume pretends to have made.]{Las
      características de la filosofía de Hume que he mencionado, como muchas otras
      de sus características, me hacen inclinarme a pensar que Hume era un simple
      ---brillante--- sofista; y sus procedimientos son ciertamente sofísticos. Sin
      embargo me veo forzada, no a retractarme, sino a añadir a este juicio por la
      peculiaridad del filosofar de Hume: a saber, que aunque llega a sus
      conclusiones ---con las que está enamorado--- por métodos sofísticos, sus
      consideraciones constantemente abren problemas bien profundos e importantes.
      Frecuentemente es el caso que en el acto de exhibir la sofística uno se
      encuentra a sí mismo notando temas que merecen mucha exploración: lo obvio
      queda necesitado de investigación como resultado de los puntos que Hume
      pretende haber hecho.}
#+END_SRC
** Fundamento de creencias más allá impresiones es una buena cuestión
#+BEGIN_SRC latex
  En el artículo \emph{Hume and Julius Caesar} la discusión que capta el interés
  de Anscombe se encuentra en la sección IV de la tercera parte del \emph{Treatise
    of Human Nature} sobre el tema de la justificación de nuestro creer en
  cuestiones que están más allá de nuestra experiencia y memoria. Anscombe cita el
  texto de Hume como sigue:

  \blockquote[{\cite[86]{anscombe1981hjc}}When we infer effects from causes, we
  must establish the existence of these causes\ldots either by an immediate
  perception of our memory or senses, or by an inference from other causes; which
  causes we must ascertain in the same manner either by a present impression, or
  by an inference from their causes and so on, until we arrive at some object
  which we see or remember. 'Tis impossible for us to carry on our inferences
  \emph{in infinitum}, and the only thing that can stop them, is an impression of
  the memory or senses, beyond which there is no room for doubt or enquiry.
  (Selby-Bigge's edition, pp. 82--3)]{Cuando inferimos efectos partiendo de causas
    debemos establecer la existencia de estas causas\ldots ya sea por la
    percepción inmediata de nuestra memoria o sentidos, o por la inferencia
    partiendo de otras causas; causas que debemos explicar de la misma manera por
    una impresión presente, o por una inferencia partiendo de sus causas, y así
    sucesivamente hasta que lleguemos a un objeto que vemos o recordamos. Es
    imposible para nosotros proseguir en nuestras inferencias al infinito, y lo
    único que puede detenerlas es una impresión de la memoria o los sentidos más
    allá de la cual no existe espacio para la duda o indagación.}
#+END_SRC
** un presupuesto y dos argumentos:
*** relación causa-efecto puente hacia cuestiones más allá de impresiones
:TEXT:
When we infer effects from causes, we must establish the existence of these causes;
which we have only two ways of doing, either by an immediate perception of our memory
or senses, or by an inference from other causes; which causes again we must ascertain
in the same manner, either by a present impression, or by an inference from their
causes, and so on, till we arrive at some object, which we see or remember.
:END:
#+BEGIN_SRC latex
  Ya en la sección II de esta misma parte del \emph{Treatise}, Hume ha planteado
  cómo es la causalidad la conexión que nos asegura la existencia o acción de un
  objeto que es seguido o precedido por la existencia o acción de
  otro.\footnote{Cf. Treatise Sección II Parte III: ’Tis only causation, which
    produces such a connexion, as to give us assurance from the existence or
    action of one object, that ’twas follow’d or preceded by any other existence
    or action; nor can the other two relations be ever made use of in reasoning,
    except so far as they either affect or are affected by it. }
  Ahora en la sección IV esta relación de causa y efecto será tomada como un
  principio de asociación de ideas según el cual es posible inferir desde la
  impresión de alguna cosa, una idea sobre otra cosa.

  Desde esta noción de causalidad se explica la posibilidad de acceder a hechos
  más allá de nuestra experiencia; estos son inferencias de efectos desde sus
  causas. De este modo: \blockquote[{\cite[87]{anscombe1981hjc}}: For Hume, the
  relation of cause and effect is the one bridge by which to reach belief in
  matters beyond our present impressions or memories.]{Para Hume, la relación de
    causa y efecto es el único puente por el que se puede alcanzar creer en
    cuestiones más allá de nuestras impresiones presentes o memorias.}
#+END_SRC
** Ilustración: punto histórico, por qué razón lo creemos o rechazamos
*** we believe that Caesar was killed
:TEXT:
  To give an instance of this, we may chuse any point of history, and consider for what
  reason we either believe or reject it. Thus we believe that Cæsar was kill’d in the
  senate-house on the ides of March; and that because this fact is establish’d on the
  unanimous testimony of historians, who agree to assign this precise time and place to
  that event. Here are certain characters and letters present either to our memory or
  senses; which characters we likewise remember to have been us’d as the signs of
  certain ideas; and these ideas were either in the minds of such as were immediately
  present at that action, and receiv’d the ideas directly from its existence; or they
  were deriv’d from the testimony of others, and that again from another testimony, by
  a visible gradation, ’till we arrive at those who were eye-witnesses and spectators
  of the event. ’Tis obvious all this chain of argument or connexion of causes and
  effects, is at first founded on those characters or letters, which are seen or
  remember’d, and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain wou’d
  in that case hang upon another; but there wou’d not be any thing fix’d to one end of
  it, capable of sustaining the whole; and consequently there wou’d be no belief nor
  evidence. And this actually is the case with all hypothetical arguments, or
  reasonings upon a supposition; there being in them, neither any present impression,
  nor belief of a real existence.
:END:
#+BEGIN_SRC latex
  El paso adicional que Hume propone en esta sección es que al realizar estas
  inferencias es necesario establecer la existencia de las causas por medio de la
  percepción inmediata de los sentidos o por medio de una ulterior inferencia. Sin
  embargo, el establecimiento de la existencia de estas causas por medio de
  inferencias no puede continuar infinitamente, sino que tiene que llegar a una
  impresión de la memoria o los sentidos que sirva de justificación o fundamento
  definitivo.

  Para ilustrar este paso, Hume hace una invitación interesante:
    \blockquote[{\cite[?]{humetreatise}}: chuse any point of history, and consider
    for what reason we either believe or reject it.]{elegir cualquier punto en la
      historia, y considerar por qué razón lo creemos o rechazamos.} Acerca de una
    creencia histórica se nos invita a considerar sobre qué se sostiene su
    justificación. ¿Cuál es su fundamento?:
    \blockquote[{\cite[?]{humetratise}}: Thus we believe that Cæsar was kill’d in
    the senate-house on the ides of March; and that because this fact is establish’d
    on the unanimous testimony of historians, who agree to assign this precise time
    and place to that event. Here are certain characters and letters present either
    to our memory or senses; which characters we likewise remember to have been us’d
    as the signs of certain ideas; and these ideas were either in the minds of such
    as were immediately present at that action, and receiv’d the ideas directly from
    its existence; or they were deriv’d from the testimony of others, and that again
    from another testimony, by a visible gradation, ’till we arrive at those who
    were eye-witnesses and spectators of the event. ’Tis obvious all this chain of
    argument or connexion of causes and effects, is at first founded on those
    characters or letters, which are seen or remember’d, and that without the
    authority either of the memory or senses our whole reasoning wou’d be chimerical
    and without foundation.]{Así, creemos que César fue asesinado en el Senado en
      los idus de Marzo; y esto porque el hecho está establecido basándose en el
      testimonio unánime de los historiadores, que concuerdan en asignar a este
      evento este tiempo y lugar precisos. Aquí ciertos caracteres y letras se
      hallan presentes a nuestra memoria o sentidos; caracteres que recordamos
      igualmente que han sido usados como signos de ciertas ideas; y estas ideas
      estuvieron ya en las mentes de los que se hallaron inmediatamente presentes a
      esta acción y que obtuvieron las ideas directamente de su existencia; o fueron
      derivadas del testimonio de otros, y éstas a su vez de otro testimonio, por
      una graduación visible, hasta llegar a los que fueron testigos oculares y
      espectadores del suceso. Es manifiesto que toda esta cadena de argumentos o
      conexión de causas y efectos se halla fundada en un principio en los
      caracteres o letras que son vistos o recordados y que sin la autoridad de la
      memoria o los sentidos nuestro razonamiento entero sería quimérico o carecería
      de fundamento.}
#+END_SRC
** Catching Hume on his mistake
*** it must be purely hypothetical inference
#+BEGIN_SRC latex
  Anscombe comienza por reaccionar afirmando:
  \blockquote[{\cite[86]{anscombe1981hjc}}: This is not to infer effects from
  causes, but rather causes from effects.]{Esto no es inferir efectos partiendo de
    sus causas, sino más bien causas desde los efectos.} Es decir, el ejemplo
  histórico de Hume consiste en una inferencia de la causa original, el asesinato
  de Julio César, desde su efecto remoto que es nuestra percepción en el presente.
  Creemos en el asesinato de César porque lo inferimos como la causa última en una
  cadena causal que llega hasta nuestra percepción de ciertas oraciones que
  leemos. El hecho de que estemos leyendo esta información es la percepción que
  justifica la creencia de que hay una cadena de causas y efectos que tiene como
  efecto esta experiencia. Esta inferencia pasa a través de una cadena de efectos
  de causas, que son efectos de causas\ldots ¿Dónde empieza la cadena? La
  respuesta parece ser nuestra percepción presente. ¿Cómo hemos de entender,
  entonces, el argumento de que la cadena no puede continuar infinitamente? La
  propuesta de Hume es que la cadena ha de terminar en una impresión que no deje
  lugar a dudas o busqueda mas allá, sin embargo, la cadena termina en el
  asesinato de Julio César, no en nuestra percepción. La imagen que Hume pretende
  ofrecer es la de una cadena fijada en sus dos extremos por algo distinto a los
  eslabones que la componen, sin embargo, no lo logra, más bien parece describir
  un voladizo, una estructura apoyada en un punto, pero sin apoyo en el otro
  extremo.

  La afirmación \blockquote['Tis impossible for us to carry on our inference in
  infinitum]{Es imposible para nosotros proseguir en nuestras inferencias al
    infinito} viene a significar, según la interpretación de Anscombe, que
  \blockquote[the justification of the grounds of our inferences cannot go on in
  infinitum]{la justificación de los fundamentos de nuestras inferencias no pueden
    continuar al infinito}. El argumento aquí mas bien es que tiene que haber un
  punto de partida para la inferencia de la causa original. La relación de
  inferencias propuesta por Hume en su ilustración acabaría siendo una inferencia
  hipotética según su propia definición. Anscombe explica diciendo:

  \blockquote[hume in causality: We must suppose ourselves to start with the
  familiar idea, merely as idea, of Caesar having been killed. Now if we ask why
  we believe it we shall, as Hume does, point to historical testimony (the
  ‘characters and letters’), which doesn’t at this point figure as what stops
  inference going on ad infinitum. However, if we want to explain the connection
  we shall form the idea of Caesar’s death being recorded by eyewitnesses; and
  these records having been received by others, who transmitted an account ...
  etc. Here we really are arguing from the idea of an original cause to the idea
  of an effect; we are ‘inferring effects from causes’, though only in the sense
  of passing from the idea of the cause to the idea of the effect.]{Tendríamos que
    suponer que comenzamos con la idea familiar, meramente como una idea, de que
    César fue asesinado. Ahora si preguntamos por qué lo creemos hemos de, como
    hace Hume, señalar al testimonio histórico (los `caracteres y letras'), lo
    cual en este punto no figura como lo que detiene que la inferencia siga al
    infinito. Sin embargo, si queremos explicar la conexión tenemos que formular
    la idea de la muerte del Cesar siendo recordada por testigos; y esos recuentos
    siendo recibidos por otros, quienes transmitieron un informe\ldots etc. Aquí
    estamos realmente razonando desde la idea de una causa original a la idea de
    un efecto; estamos `infiriendo efectos de causas', pero solo en el sentido de
    pasar de la idea de la causa a la idea del efecto.}

  Desde este análisis, Anscombe resume lo argumentado por Hume en cuatro partes:

  \blockquote[humeandjulius 88: First, a chain of reasons for a belief must
  terminate in something that is believed without being founded on anything else.
  Second, the ultimate belief must be of a quite different character from derived
  beliefs: it must be perceptual belief, belief in something perceived, or
  presently remembered. Third, the immediate justification for a belief p, if the
  belief is not a perception, will be another belief q, which follows from, just
  as much as it implies, p. Fourth, we believe by inference through the links in a
  chain of record

  There is an implicit corollary: when we believe in historical information
  belonging to the remote past, we believe that there has been a chain of record]{
    Primero, una cadena de razones para una creencia debe terminar en algo que se
    cree sin estar fundado en alguna otra cosa. Segundo, la creencia última debe
    ser de una naturaleza distinta a las creencias derivadas: Tiene que ser
    creencia perceptual, creer en algo percibido, or recordado en el presente.
    Tercero, la justificación inmediata de una creencia $p$, si la creencia no es
    una percepción, será otra creencia $q$, la cual se sigue, en la misma medida
    que implica, a $p$. Cuarto, creemos por inferencia a través de los eslabones
    en una cadena de relato.

    Hay un corolario implicito: cuando creemos en información histórica
    perteneciente a un pasado remoto, creemos que ha habido una cadena de relato.}

  Sin embargo, Anscombe considera que esta no es la manera adecuada de establecer
  esta relación. Mas bien: \blockquote[hjc 88: \emph{If} the written records that
  we now see are grounds of our belief, they are first and foremost grounds for
  belief in Caesar's killing, belief that the assassination is a solid bit of
  history. Then our belief in that original event is a ground for belief in much
  of the intermediate transmision.]{\emph{Si} los relatos escritos que vemos ahora
    son fundamento para nuestro creer, estos son primero y ante todo fundamento
    para la creencia en el asesinato de Cesar, creencia en que el asesinato es un
    pedazo sólido de historia. Entonces nuestra creencia en ese evento original es
    fundamento para el creer en mucha de la transimisión intermedia.}
  ¿Por qué creemos que hubo testigos del asesinato? Ciertamente porque creemos que
  hubo un asesinato. La creencia de que hubo testigos es inferida de la creencia
  en el hecho.

  Anscombe compara este modo de entender la cadena de transmisión de información
  histórica a nuestra creencia en la continuidad espacio-temporal. Si reconocemos
  en una ocasión a una persona conocida como alguien que vimos la semana pasada,
  nuestra creencia en que es la misma persona no es una inferencia de otra
  creencia acerca de la continuidad espacio-temporal de un patrón humano desde
  ahora hasta entonces, sino que más bien nuestra creencia en la continudad
  espacio-temporal esta inferida del reconocimiento de la identidad de la persona.
  Sin embargo, una evidencia sobre una interrupción en la continuidad sí alteraría
  nuestra creencia en la identidad.

  Elizabeth entonces concluye que: \blockquote[hjc 89: Belief in recorded history is
  on the whole a belief that there has been a chain of tradition of reports and
  records going back to contemporary knowledge; it is not a belief in the
  historical facts by an inference that passes through the links of such a chain.
  At most, that can very seldom be the case.]{La creencia en los registros de la
    historia consiste en general la creencia de que ha habido una cadena de
    tradición de informes y registros que van hacia el conocimiento contemporaneo;
    no es una creencia en hechos históricos por una inferencia que pasa por los
    eslabones de una cadena como esta. Como mucho, esto seria muy raramente el
    caso.}

  Ahora bien, como se ha dicho antes, el interés de Anscombe no esta simplemente
  en mostrar en qué se equivoca Hume, sino que considera que la cuestión toca el
  nervio de un problema con cierta profundidad:
  \blockquote[causality in hume 2855: The interesting problem that arises, then,
  is why the things we are told and the writings that we see are the starting
  points for our belief in the far distant events and so in the intermediate chain
  of record.]{El problema interesante que surge, entonces, es por qué las cosas
    que se nos dicen y los escritos que vemos son puntos de partida para nuestro
    creer en eventos distantes y así también en la cadena del relato intermedia.}
#+END_SRC
*** no es posible continuar infinitamente una cadena de inferencias
:TEXT:
’Tis impossible for us to carry on our inferences in infinitum; and the only thing,
that can stop them, is an impression of the memory or senses, beyond which there is no
room for doubt or enquiry.
:END:
+BEGIN_SRC latex
  El argumento de Hume, entonces, se compone de dos partes.
  En primer lugar, una cadena de inferencia en la cual "ya que p, q, etc..."
  en la que p da una causa creida (no percibida) y q un efecto inferido, no puede continuar
para siempre, sino que tiene que terminar n

  Determina que estas inferencias no pueden continuar infinitamente. Si se tratara
  de mera relación especulativa de conceptos no representaría dificultad, pero se
  trata de creer, y la cadena no podría ofrecer una creencia si no tiene término.
  \blockquote[{\cite[2762]{anscombe2011hoc}}: Now there really is no difficulty
  about going on ad infinitum, or at any rate about saying ‘and so on ad
  infinitum’, if the ‘inferring’ is simply deriving the idea of the effect from
  that of the cause. But the inferring is more than that ---it is believing. It is
  in connection with this that Hume is saying ‘this chain can’t go on for
  ever’.]{Ahora realmente no hay dificultad en ir infinitamente, o en cualquier
    caso decir `así sucesivamente infinitamente', si el `inferir' es simplemente
    derivar la idea del efecto partiendo de su causa. Pero el inferir es más que
    eso ---es creer. Es en conexión con esto que Hume dice `esta cadena no puede
    seguir para siempre'}

  First, a chain ‘Since p, q, etc’ in which p gives a believed-in (not perceived)
  cause and q an inferred effect, cannot go on for ever but must terminate in a
  proposition that is believed without inferring any consequences from it; and
  from this proposition we then work back in reverse order to p.

  This is a particular form of a familiar argument that not everything can be
  argued from something else, that is: that it cannot be the case that everything
  is argued from something else. I believe p because I believe q because I believe
  r because I believe s ---this cannot go on for ever; it must end in something
  which I believe, not because I believe something else. This argument appears to
  be correct.

#+END_SRC
*** el término de la cadena de inferencias no puede ser otra inferencia
+BEGIN_SRC latex
Hume’s second point is that not merely must the chain that he is concerned with
come to an end somewhere, but its terminus must be of a different kind from the
other members. ... without the authority either of the memory or the senses our
whole reasonings wou’d be chimerical and without foundation. Every link of the
chain wou’d in that case hang upon another; but there wou’d not be anything
fix’d to one end of it, capable of sustaining the whole; and consequently there
wou’d be no belief or evidence.[27]


The second part of his argument, which says that the terminus must be of a
different character from the links of the chain, is more doubtful than the first
part which only says there must be a terminus. Hume does not think that I have
to have a present perception (of memory or sense) in connection with my belief
that Caesar was killed in the Senate House: we can ‘reason upon our past
conclusions and principles, without having recourse to those impressions from
which they first arose.’ The convictions, however, must have been produced by
impressions, and ‘all reasonings concerning causes and effects are originally
deriv’d from some impression’.
#+END_SRC

*** hume's thesis falls into four parts
*** two comparisons: identity and proper names
#+BEGIN_SRC latex

#+END_SRC

** Conclusion:perception of records>belief distant event>chain of record

** Not just catching the mistake, but seeing what to say about this
The interesting problem that arises, then, is why the things we are told and the
writings that we see are the starting points for our belief in the far distant events
and so in the intermediate chain of record. This is a question of vast importance. But
the consideration of it would take us far away from that investigation of Hume on cause
which has been our present business. I take it as sufficiently demonstrated that Hume’s
account is wrong. (One may be convinced of that without thinking that one has an
alternative account.)
** Wittgenstein: On Certainty


So it turns out when I say things like “Here is a hand” I’m not really making a claim
about the world, I’m laying down some rules for discussion. If you doubt there’s a hand
here, then fuck you and that’s all there is to it. We can’t really talk about anything
now, because we can’t even agree on something as simple as a goddamn hand. When we all
agree here is a hand, then we can go about discussing our world in meaningful ways.
Skepticism just undermines a foundation and replaces it with nothing; its paralyzing.
The grounds for such radical skepticism don’t exist; it presupposes and relies on the
very certainty it tries to undermine.

The hypothesis that Julius Caesar might turn out never to have existed can be rejected,
once the details of that hypothesis have been demanded.
#+BEGIN_SRC latex
  Para discutir esta cuestión Anscombe recurre a las reflexiones de Wittgenstein
  en \emph{On Certainty}. La motivación para estos ecritos de Wittgenstein son las
  propuestas de Moore en \emph{Proof of the External World} y \emph{Defence of
    Common Sense}. En estas obras sostiene que hay una serie de proposiciones que
  conocemos con seguridad, como \enquote{Aquí hay una mano, y aquí otra}, o
  \enquote{La tierra ha existido por largo tiempo antes de mi nacimiento} y
  \enquote{Nunca he estado lejos de la superficie de la tierra}. Estas reflexiones
  ocuparon a Wittgenstein durante los últimos años de su vida.\footnote{Cf.
    preface On certainty}

  Un tema que aparece en esta discusión de Wittgenstein es que la justificación
  semántica, relacionada con el uso correcto del lenguaje, y la justificación
  epistémica, relacionada como tal con el afirmar la verdad, están más unidas
  entre sí de lo que se piensa. Según esto:\blockquote[teichmann 213: Wittgenstein
  invites us to view the rules governing the correct use of words as comparable to
  the rules governing the acceptance or rejection of beliefs (which are themselves
  of course paradigmatically expressed in words); a ‘world view’ is determined as
  much by our language and its attendant conceptual scheme as by what we would
  ordinarily term our knowledge of things. The two aspects of world view, the two
  kinds of justification, come together in the phenomenon of certainty. ‘I am
  sure’, ‘I cannot doubt’ are related to ‘It must be’, which expression can be
  prefixed to any statement of conceptual truth. One direction in which these
  thoughts seem to take us is towards regarding certain world views, or sets of
  beliefs, or very general beliefs, as no more susceptible of rational
  justification or criticism than are concepts. –This is just how we go on’ looks
  to be the final answer to a series of –Why?’ questions; and a language–game or
  practice can appear to be sealed off from external assessment. An appeal to the
  objective measure of Reality is empty in this context; we can of course –cite
  reality’ when giving reasons in justification of a belief or practice, but that
  our reasons count as good reasons is determined by norms or rules of reasoning
  whose status as rules depends on the existence of a surrounding
  language–game.]{Wittgenstein nos invita a ver las reglas que gobiernan el uso
    correcto de las palabras como comparables con las reglas que gobiernan la
    aceptación o rechazo de las creencias (que desde luego son ellas mismas
    paradigmáticamente expresadas en palabras); una `cosmovisión' está determinada
    tanto por nuestro lenguaje y su esquema conceptual relacionado como por lo que
    ordinariamente expresamos como nuestro conocimiento de las cosas. Los dos
    aspectos de la cosmovisión, los dos tipos de justificación, quedan unidos en
    el fenómeno de la certeza. [\ldots] Una dirección hacia la que estos
    pensamientos parecen dirigirnos es a considerar ciertas cosmovisiones, o
    colecciones de creencias, o creencias generales, como no más susceptibles de
    justificación racional o crítica que la que tienen los conceptos}.

  Anscombe aplica las lecciones de \emph{On Certainty} al conocimiento histórico
  en la linéa propuesta por Hume: ``elegir cualquier punto en la historia, y
  considerar por qué razón lo creemos o rechazamos''. Elegir o rechazar una
  creencia como la propuesta implica la identificación de una justificación
  suficiente, y aquí esta busqueda esta regida por reglas comparables al correcto
  uso de las palabras. Los dos puntos principales destacados por Anscombe serán:
  \blockquote[grounds of belief 183: Hume's philosophical opinion was that these
  ultimate groundless grounds were sense impressions. But I say that they are such
  beliefs as those of which one will say `Everyone knows that!' or `Everyone who
  knows anything on such matters at all, knows that!']{La opinion filosófica de
    Hume era que estos fundamentos-sin-fundamento definitivos eran impresiones de
    los sentidos. Pero yo digo que son ese tipo de creencias de las cuales uno
    dice `¡Todo el mundo sabe eso!' o `¡Todo el que sabe algo de ese tema, sabe
    eso!'}. Junto a esto, es también parte de su argumento:
  \blockquote[teichmann 224: the mere statement that we can conceive of evidence
  turning up which showed there had never been such a person as Julius Caesar is
  no good until details are given of what sort of evidence that might be. If we
  try to do this, however, we are likely to fail.]{la declaración de que puede ser
    concebido que aparezca evidencia que mostrara que nunca ha habido una persona
    como Julio César no es suficiente hasta que se den detalles acerca del tipo de
    evidencia que ésta pudiera ser. Si intentamos hacer esto, sin embargo, lo más
    probable es que fracasemos.}

  Para entender su primera propuesta será útil recurrir a su explicación de este
  punto como está planteado en \emph{On Certainty}: \blockquote[QLI, 130: Finding
  grounds, testing, proving, reasoning, confirming, verifying are all processes
  that go on within, say, one or another living linguistic practice which we have.
  There are assumptions, beliefs, that are ‘immovable foundations’ of these
  proceedings. By this, Wittgenstein means only that they are a foundation which
  is not moved by any of these proceedings.]{Encontrar fundamentos, examinar,
    probar, razonar, confirmar, verificar son todos procesos que corresponden,
    diríamos, dentro de una u otra práctica linguística viva de las que tenemos.
    Hay supuestos, creencias, que son `fundamentos inmovibles' de estos modos de
    proceder. Con esto, Wittgenstein se refiere solamente a que son un fundamento
    que no es modificado por esos procesos.} En estos procesos o actividades hay
  proposiciones que sirven como bisagras, donde se apoya el movimiento del
  discurrir. Como tal, son creencias que si se ponen en duda impiden el progreso
  del razonamiento. Estas creencias son esas que forman parte del conocimiento
  común. En ese sentido, afirmar \enquote{aquí está mi mano} no es sostener algo
  sobre el estado de las cosas en el mundo, sino establecer unas reglas para la
  discusión. Por otra parte, poner en duda que tengo mi mano aquí delante
  supondría tratar con escepticismo un conocimiento común de tal manera que se
  podría decir \enquote{si esto es dudoso, ¿qué puede ser cierto?}, entonces
  ¿desde qué fundamento podríamos sostener una discusión o razonamiento sobre el
  mundo en el que \enquote{aquí está mi mano} no es cierto?

  Esto mismo ocurre con la creencia en el conocimiento común de la existencia de
  Julio César, si nos planteamos la hipótesis de que nunca existió, nos
  situaríamos entre dos alternativas, ya sea \blockquote[HJC 91: \textelp{} say:
  ``How could one explain all these references and implications, then?\ldots but,
  but, \emph{but} if I doubt the existence of Caesar, if I say I may reasonably
  call it in question, then with equal reason I must doubt the status of the
  things I've just pointed to'']{\textelp{} decir ``¿Cómo se explican todas estas
    referencias e implicaciones entonces?\ldots pero, pero \emph{pero} si dudo de
    la existencia de César, si digo que podría razonablemente ponerlo en tela de
    juicio, entonces, con la misma razonabilidad tengo que dudar de la validez de
    las cosas que acabo de señalar''}. O por otra parte: \blockquote[HJC91:
  \textelp{} I should realize straight away that the `doubt' put me in a vacuum in
  which I could not produce reasons why such and such `historical facts' are more
  or less doubtful.]{\textelp{} podría caer en cuenta inmediatamente de que la
    `duda' me ha encerrado en un vacío en el cual no podría producir razones por
    las cuales estos u otros `datos históricos' son más o menos dudosos.}

  Hume escoge este punto histórico porque es un conocimiento presente en su
  cultura con un grado particular de certeza. Podría haber sometido a prueba algun
  detalle del suceso y cuestionar, por ejemplo, si podría dudarse la fecha o el
  lugar del asesinato, sin embargo, el que ese hombre, César, existió, y su vida
  terminó en un asesinato: esto solo podría cuestionarlo empleando la duda
  Cartseiana.

  Elizabeth alude a la analogía hecha por Otto Neurath en \emph{Anti-Spengler},
  donde compara el conocimiento científico con un barco en el cual los que
  investgan son como marinos que reconstruyen el barco en altamar, verificando y
  reemplazando sus piezas mientras que se navega. Entonces propone que si la
  ilustración implica que se puede ir examinando cada pieza y reemplazarla de tal
  modo que se termina con un barco distinto, la analogía no sirve: \blockquote[HJC
  92: For there are things that are on a level. A general epistemological reason
  for doubting one will be a reason for doubting all, and then none of them would
  have anything to test it by.]{Pues hay cosas que están sobre superficie. Una
    razón espistemológica general para dudar de una será razón para dudar de
    todas, y entonces ninguna tendría cosa alguna que sirviera para evaluarla.}


  What would one REALLY have grounds for saying or thinking, in such a case?’ In
  many of her articles, Anscombe refers to some view as a prejudice, or apparent
  prejudice. When is a belief a prejudice, and when is it bedrock? When is it a
  questionable ‘bit of Weltanschauung’, and when a ‘hinge proposition’? The answer
  to these questions must in large part have to do with how much, and what sort
  of, detail can be plausibly put into counter-examples to, or cases against, the
  belief in question.

  My knowledge of the things among which and the places in which I live is not so
  much 'theory laden' as ‘common-knowledge laden'. I wish to say: it is a
  falsification here to speak of testimony: to say, for example, that it is by
  testimony that I know I was born. There is something else, not testimony, though
  acquired by education from human beings, which is, so to speak, thicker than
  testimony.

  The work done, people could be taught what England was (no doubt still disputing
  some regions). Now those who learned thereafter can hardly be said to have
  knowledge by testimony. They were taught to call something 'England’—something
  indeed which could in large part only be defined for them by hearsay; and they
  so taught those who came after them. I am an heir of this tradition. Now, I know
  I live in England. But by testimony? Some would say so. But there is something
  queer about it. What do I know? That the world is divided up into countries
  which have names, and that the one I live in is called England and is here on
  the map of the globe. This involves understanding the use of the globe to
  represent the earth. It is rather as if I had been taught to join in doing
  something, than to believe something—but because everyone is taught to do such
  things, an object of belief is generated. The belief is so certainly correct
  (for it follows the practice) that it is knowledge; for here knowledge is no
  other than certainly correct belief in pursuit of a practice. But the connection
  with testimony is remote and indirect.

#+END_SRC
