#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

#+BEGIN_SRC latex
\section{Análisis Diacrónico}
#+END_SRC


* Hume and Julius Caesar 1973                    :published:
:PUBLICATION_INFO:
Originally published in october 1973 vol 34 Issue 1 of Analysis Journal Reprinted in
CPP I in 1981 p. 86-92
:END:
#+BEGIN_SRC latex
\subsection{Hume and Julius Caesar}
#+END_SRC
** Intro 1: este ensayo y los otros
In the present volume the lengthy paper ‘Hume on causality: introductory’ is the matrix
from which Anscombe extracted ‘Hume and Julius Caesar’ and ‘“Whatever has a beginning
of existence must have a cause”: Hume’s Argument Exposed’.[2] It is published here as
an example of the scrupulous and attentive study she devoted to major philosophers
which is abundantly evident in her unpublished papers.

#+BEGIN_SRC latex
  Los artículos \emph{Hume and Julius Caesar} y \emph{``Whatever has a beginning
    of existence must have a cause'': Hume’s Argument Exposed} de Anscombe, fueron
  publicados en la revista académica \emph{Analysis} en octubre de 1973 y abril de
  1974 respectivamente. Ambos están relacionados por el tema de la causalidad en
  Hume. En el trasfondo de los dos artículos está otro documento no publicado
  hasta 2011 con el título \emph{Hume on causality: introductory}.
#+END_SRC

** Intro 2: Hume es interesante porque abre buenas cuestiones
#+BEGIN_SRC latex
  Una de las actitudes características de Anscombe es su tendencia a quedar
  atraída por preguntas que representan cuestiones profundas, incluso en
  discusiones cuyos argumentos, método o conclusiones no le parecen tan
  interesantes.

  Un autor que suele tener este efecto en ella es Hume. En \emph{Modern Moral
    Philosophy} dice:

  \blockquote[{\cite[172]{anscombe1981mmph}}: The features of Hume’s philosophy
  which I have mentioned, like many other features of it, would incline me to
  think that Hume was a mere ---brilliant--— sophist; and his procedures are
  certainly sophistical. But I am forced, not to reverse, but to add to this
  judgement by a peculiarity of Hume’s philosophizing: namely that, although he
  reaches his conclusions --—with which he is in love--— by sophistical methods,
  his considerations constantly open up very deep and important problems. It is
  often the case that in the act of exhibiting the sophistry one finds oneself
  noticing matters which deserve a lot of exploring: the obvious stands in need of
  investigation as a result of the points that Hume pretends to have made.]{Las
    características de la filosofía de Hume que he mencionado, como muchas otras
    de sus características, me hacen inclinarme a pensar que Hume era un simple
    ---brillante--- sofista; y sus procedimientos son ciertamente sofísticos. Sin
    embargo me veo forzada, no a retractarme, sino a añadir a este juicio por la
    peculiaridad del filosofar de Hume: a saber, que aunque llega a sus
    conclusiones ---con las que está enamorado--- por métodos sofísticos, sus
    consideraciones constantemente abren problemas bien profundos e importantes.
    Frecuentemente es el caso que en el acto de exhibir la sofística uno se
    encuentra a sí mismo notando temas que merecen mucha exploración: lo obvio
    queda necesitado de investigación como resultado de los puntos que Hume
    pretende haber hecho.}
#+END_SRC
** Fundamento de creencias más allá impresiones es una buena cuestión
#+BEGIN_SRC latex
  En el artículo \emph{Hume and Julius Caesar} la discusión que capta el interés
  de Anscombe se encuentra en la sección IV de la tercera parte del \emph{Treatise
  of Human Nature} sobre el tema de nuestro creer en cuestiones que están más allá
  de nuestra experiencia y memoria. Anscombe cita el texto de Hume como sigue:

  \blockquote[{\cite[86]{anscombe1981hjc}}When we infer effects from causes, we
  must establish the existence of these causes\ldots either by an immediate
  perception of our memory or senses, or by an inference from other causes; which
  causes we must ascertain in the same manner either by a present impression, or
  by an inference from their causes and so on, until we arrive at some object
  which we see or remember. 'Tis impossible for us to carry on our inferences
  \emph{in infinitum}, and the only thing that can stop them, is an impression of
  the memory or senses, beyond which there is no room for doubt or enquiry.
  (Selby-Bigge's edition, pp. 82--3)]{Cuando inferimos efectos partiendo de causas
    debemos establecer la existencia de estas causas\ldots ya sea por la
    percepción inmediata de nuestra memoria o sentidos, o por la inferencia
    partiendo de otras causas; causas que debemos explicar de la misma manera por
    una impresión presente, o por una inferencia partiendo de sus causas, y así
    sucesivamente hasta que lleguemos a un objeto que vemos o recordamos. Es
    imposible para nosotros proseguir en nuestras inferencias al infinito, y lo
    único que puede detenerlas es una impresión de la memoria o los sentidos más
    allá de la cual no existe espacio para la duda o indagación.}

#+END_SRC
** un presupuesto y dos argumentos:
*** relación causa-efecto puente hacia cuestiones más allá de impresiones
When we infer effects from causes, we must establish the existence of these causes;
which we have only two ways of doing, either by an immediate perception of our memory
or senses, or by an inference from other causes; which causes again we must ascertain
in the same manner, either by a present impression, or by an inference from their
causes, and so on, till we arrive at some object, which we see or remember.
#+BEGIN_SRC latex
  Podemos identificar dos argumentaciones principales en este fragmento. En primer
  lugar, describe el acceso a hechos más allá de nuestra experiencia como
  inferencias de efectos desde sus causas.
  \blockquote[{\cite[87]{anscombe1981hjc}}: For Hume, the relation of cause and
  effect is the one bridge by which to reach belief in matters beyond our present
  impressions or memories.]{Para Hume, la relación de causa y efecto es el único
    puente por el que se puede alcanzar creer en cuestiones más allá de nuestras
    impresiones presentes o memorias.}
#+END_SRC
*** no es posible continuar infinitamente una cadena de inferencias
’Tis impossible for us to carry on our inferences in infinitum; and the only thing,
that can stop them, is an impression of the memory or senses, beyond which there is no
room for doubt or enquiry.
#+BEGIN_SRC latex
  En segundo lugar, determina que estas inferencias no pueden continuar
  infinitamente. Si se tratara de mera relación especulativa de conceptos no
  representaría dificultad, pero se trata de creer, y la cadena no podría ofrecer
  una creencia si no tiene término. \blockquote[{\cite[2762]{anscombe2011hoc}}:
  Now there really is no difficulty about going on ad infinitum, or at any rate
  about saying ‘and so on ad infinitum’, if the ‘inferring’ is simply deriving the
  idea of the effect from that of the cause. But the inferring is more than that
  ---it is believing. It is in connection with this that Hume is saying ‘this
  chain can’t go on for ever’.]{Ahora realmente no hay dificultad en ir
    infinitamente, o en cualquier caso decir `así sucesivamente infinitamente', si
    el `inferir' es simplemente derivar la idea del efecto partiendo de su causa.
    Pero el inferir es más que eso ---es creer. Es en conexión con esto que Hume
    dice `esta cadena no puede seguir para siempre'}
#+END_SRC
*** el término de la cadena de inferencias no puede ser otra inferencia
** Ilustración: punto histórico, por qué razón lo creemos o rechazamos
*** we believe that Caesar was killed
  To give an instance of this, we may chuse any point of history, and consider for what
  reason we either believe or reject it. Thus we believe that Cæsar was kill’d in the
  senate-house on the ides of March; and that because this fact is establish’d on the
  unanimous testimony of historians, who agree to assign this precise time and place to
  that event. Here are certain characters and letters present either to our memory or
  senses; which characters we likewise remember to have been us’d as the signs of
  certain ideas; and these ideas were either in the minds of such as were immediately
  present at that action, and receiv’d the ideas directly from its existence; or they
  were deriv’d from the testimony of others, and that again from another testimony, by
  a visible gradation, ’till we arrive at those who were eye-witnesses and spectators
  of the event. ’Tis obvious all this chain of argument or connexion of causes and
  effects, is at first founded on those characters or letters, which are seen or
  remember’d, and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain wou’d
  in that case hang upon another; but there wou’d not be any thing fix’d to one end of
  it, capable of sustaining the whole; and consequently there wou’d be no belief nor
  evidence. And this actually is the case with all hypothetical arguments, or
  reasonings upon a supposition; there being in them, neither any present impression,
  nor belief of a real existence.
#+BEGIN_SRC latex
  Para ilustrar su propuesta Hume hace una invitación interesante:
  \blockquote[{\cite[?]{humetreatise}}: chuse any point of history, and consider
  for what reason we either believe or reject it.]{elegir cualquier punto en la
    historia, y considerar por qué razón lo creemos o rechazamos.} Acerca de una
  creencia histórica se nos invita a considerar sobre qué se sostiene su
  justificación. ¿Cuál es su fundamento? La opinión de Hume es que en definitiva
  se apoyan sobre impresiones de nuestros sentidos. Así lo describe diciendo:
  \blockquote[{\cite[?]{humetratise}}: Thus we believe that Cæsar was kill’d in
  the senate-house on the ides of March; and that because this fact is establish’d
  on the unanimous testimony of historians, who agree to assign this precise time
  and place to that event. Here are certain characters and letters present either
  to our memory or senses; which characters we likewise remember to have been us’d
  as the signs of certain ideas; and these ideas were either in the minds of such
  as were immediately present at that action, and receiv’d the ideas directly from
  its existence; or they were deriv’d from the testimony of others, and that again
  from another testimony, by a visible gradation, ’till we arrive at those who
  were eye-witnesses and spectators of the event. ’Tis obvious all this chain of
  argument or connexion of causes and effects, is at first founded on those
  characters or letters, which are seen or remember’d, and that without the
  authority either of the memory or senses our whole reasoning wou’d be chimerical
  and without foundation.]{Así, creemos que César fue asesinado en el Senado en
    los idus de Marzo; y esto porque el hecho está establecido basándose en el
    testimonio unánime de los historiadores, que concuerdan en asignar a este
    evento este tiempo y lugar precisos. Aquí ciertos caracteres y letras se
    hallan presentes a nuestra memoria o sentidos; caracteres que recordamos
    igualmente que han sido usados como signos de ciertas ideas; y estas ideas
    estuvieron ya en las mentes de los que se hallaron inmediatamente presentes a
    esta acción y que obtuvieron las ideas directamente de su existencia; o fueron
    derivadas del testimonio de otros, y éstas a su vez de otro testimonio, por
    una graduación visible, hasta llegar a los que fueron testigos oculares y
    espectadores del suceso. Es manifiesto que toda esta cadena de argumentos o
    conexión de causas y efectos se halla fundada en un principio en los
    caracteres o letras que son vistos o recordados y que sin la autoridad de la
    memoria o los sentidos nuestro razonamiento entero sería quimérico o carecería
    de fundamento.}
#+END_SRC
** Catching Hume on his mistake
*** it must be purely hypothetical inference
#+BEGIN_SRC latex
  La reacción de Anscombe a esta propuesta de Hume es inmediata:
  \blockquote[{\cite[86]{anscombe1981hjc}}: This is not to infer effects from
  causes, but rather causes from effects.]{Esto no es inferir efectos partiendo de
    sus causas, sino más bien causas desde los efectos.} Es decir, el ejemplo
  histórico de Hume consiste en una inferencia de la causa original, el asesinato
  de Julio César desde su efecto remoto que es nuestra percepción en el presente
  de ciertas letras que leemos. Esta inferencia desde nuestra impresión presente
  hasta la causa orignal pasa a través de una cadena de efectos de causas, que son
  efectos de causas\ldots ¿Dónde empieza la cadena? ¿Puede decirse que es nuestra
  percepción presente?

  La imagen que Hume pretende ofrecer es la de una cadena fijada en sus dos
  extremos por algo distinto a los eslabones que la componen

  sin embargo hume no lo logra, más bien parece describir un voladizo, una
  estructura apoyada en un punto, pero


  The end of the chain is the death of Caesar or the perception of it by
  eyewitnesses, not our perception; that was surely the beginning of the
  inference! So after all there was reason to conceive the chain running the other
  way. But then how do we justify the starting point? Our charitable
  reconstruction has misfired. We must suppose ourselves to start with the
  familiar idea, merely as idea, of Caesar having been killed. Now if we ask why
  we believe it we shall, as Hume does, point to historical testimony (the
  ‘characters and letters’), which doesn’t at this point figure as what stops
  inference going on ad infinitum. However,


  but we must reach a starting point in the justification of these inferences (and
  that starting point must be perception)

  ’Tis obvious all this chain of argument or connexion of causes and effects, is
  at first founded on those characters or letters, which are seen or remember’d,
  and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain
  wou’d in that case hang upon another; but there wou’d not be any thing fix’d to
  one end of it, capable of sustaining the whole; and consequently there wou’d be
  no belief nor evidence. And this actually is the case with all hypothetical
  arguments, or reasonings upon a supposition; there being in them, neither any
  present impression, nor belief of a real existence.


  The picture is that of a chain which must be nailed by and to something
  different from the links of which it is composed. As the picture swims before
  the imagination, the chain even so hangs forlornly down—one remembers that hint
  of a nailing at the other end, where there were eyewitnesses of Caesar’s
  assassination. But Hume cannot give us that picture. For the picture that he can
  give us, the ordinary idea of a dangling chain is unfortunate: that of a
  cantilever would be more satisfying. And no doubt the supported structure in a
  cantilever construction could consist of


  His argument then falls into two parts.

  First, a chain ‘Since p, q, etc’ in which p gives a believed-in (not perceived)
  cause and q an inferred effect, cannot go on for ever but must terminate in a
  proposition that is believed without inferring any consequences from it; and
  from this proposition we then work back in reverse order to p.

  This is a particular form of a familiar argument that not everything can be
  argued from something else, that is: that it cannot be the case that everything
  is argued from something else. I believe p because I believe q because I believe
  r because I believe s ---this cannot go on for ever; it must end in something
  which I believe, not because I believe something else. This argument appears to
  be correct.

  The second part of his argument, which says that the terminus must be of a
  different character from the links of the chain, is more doubtful than the first
  part which only says there must be a terminus. Hume does not think that I have
  to have a present perception (of memory or sense) in connection with my belief
  that Caesar was killed in the Senate House: we can ‘reason upon our past
  conclusions and principles, without having recourse to those impressions from
  which they first arose.’ The convictions, however, must have been produced by
  impressions, and ‘all reasonings concerning causes and effects are originally
  deriv’d from some impression’.
#+END_SRC
*** hume's thesis falls into four parts
*** two comparisons: identity and proper names
** Conclusion:perception of records>belief distant event>chain of record

** Not just catching the mistake, but seeing what to say about this
The interesting problem that arises, then, is why the things we are told and the
writings that we see are the starting points for our belief in the far distant events
and so in the intermediate chain of record. This is a question of vast importance. But
the consideration of it would take us far away from that investigation of Hume on cause
which has been our present business. I take it as sufficiently demonstrated that Hume’s
account is wrong. (One may be convinced of that without thinking that one has an
alternative account.)
** Wittgenstein: On Certainty


So it turns out when I say things like “Here is a hand” I’m not really making a claim
about the world, I’m laying down some rules for discussion. If you doubt there’s a hand
here, then fuck you and that’s all there is to it. We can’t really talk about anything
now, because we can’t even agree on something as simple as a goddamn hand. When we all
agree here is a hand, then we can go about discussing our world in meaningful ways.
Skepticism just undermines a foundation and replaces it with nothing; its paralyzing.
The grounds for such radical skepticism don’t exist; it presupposes and relies on the
very certainty it tries to undermine.

The hypothesis that Julius Caesar might turn out never to have existed can be rejected,
once the details of that hypothesis have been demanded.
* Prophecy and Miracles

p. 37 Now what does this rest on? It might rest on faith. In Deuteronomy, when the Jews were
forbidden to consult soothsayers and necromancers, and omens, they were promised
prophets ‘like Moses’ whom they were to attend to instead.
