#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* Análisis /"Diacrónico"/
#+BEGIN_SRC latex
\section{Análisis Diacrónico}
#+END_SRC
** Prophecy and Miracles (1957)
#+BEGIN_SRC latex
\subsection{Prophecy and Miracles}
#+END_SRC
*** Información del texto
#+BEGIN_SRC latex
  El \emph{Philosophical Enquiry Group} se reunió anualmente entre 1954 y 1974 en
  el Centro de Conferencias de los Dominicos en \emph{Spode House, Staffordshire}.
  Los encuentros tenían como objetivo la discusión de cuestiones relacionadas con
  las creencias y prácticas cristianas. Elizabeth Anscombe y Peter Geach
  estuvieron entre los primeros ponentes invitados y colaboraron durante los
  veinte años que se realizaron las
  conferencias.\footnote{\cite[Cf.~][x]{anscombe2008faith}: \textelp{} no
    information was found about a number of papers. Features of their physical
    format suggested that the group of three (`Prophecy', `The Inmortality of the
    soul', and `On being in good faith', Nos. 3,9 and 12) were all given in the
    late 1950s and early 1960s to the Philosophical Enquiry Group wich met each
    year between 1954 and 1974 at the Dominican Conference Centre at Spode House
    in Staffordshire. \textelp{} Among the first invitees were Elizabeth Anscombe
    and Peter Geach \textelp{} The meetings focused on philosophical issues
    related to Christian belief and practice.} Una de estas colaboraciones se
  encuentra en \emph{Prophecy and Miracles}, publicado en \emph{Faith in a Hard
    Ground} en 2008. Es con mucha probabilidad el texto de una ponencia ofrecida
  por Anscombe en la reunión del grupo en 1957.\footnote{\cite[Cf.~][nota a pie de
    página 20]{anscombe2008faith:prophandmi}: From the undated typescript of a
    paper, probably delivered in 1957}
#+END_SRC
*** Introducción: Planteamiento de la cuestión
#+BEGIN_SRC latex
  Anscombe introduce su contienda situando los puntos principales de su análisis
  en torno a tres documentos:

  \begin{enumerate}
  \item La constitución dogmática \emph{Dei Filius}, específicamente el capítulo
    tercero: \blockquote[{\cite[\S\,3009]{vati1870df}}: Ut nihilominus fidei
    nostrae obsequium rationi consentaneum \textins{\emph{cf. Rm 12,1}} esset,
    voluit Deus cum internis Spiritus Sancti auxiliis externa iungi revelationis
    suae argumenta, facta scilicet divina, atque imprimis miracula et prophetias,
    quae cum Dei omnipotentiam et infinitam scientiam luculenter commonstrent,
    divinae revelationis signa sunt certissima et omnium intelligentiae
    accommodata \textins{\emph{can. 3 et 4}}. Quare tum Moyses et Prophetae, tum
    ipse maxime Christus Dominus multa et manifestissima miracula et prophetias
    ediderunt; et de Apostolis legimus: ``Illi autem profecti praedicaverunt
    ubique, domino cooperante, et sermonem confirmante, sequentibus signis''
    \textins{\emph{Mc 16,20}}. Et rursum scriptum est: ``Habemus firmiorem
    propheticum sermonem, cui bene facitis attendentes quasi lucernae lucenti in
    caliginoso loco'' \textins{\emph{2 Pt 1,19}}.]{Sin embargo, para que el
      obsequio de nuestra fe fuera conforme a la razón \textins{\emph{cf. Rm
          12,1}}, quiso Dios que a los auxilios internos del Espíritu Santo se
      juntaran argumentos externos de su revelación, a saber, hechos divinos y,
      ante todo, los milagros y profecías, que, mostrando de consuno luminosamente
      la omnipotencia y ciencia infinita de Dios, son signos ciertísimos y
      acomodados a la inteligencia de todos, de la revelación divina
      \textins{\emph{can. 3 et 4}}. Por eso, tanto Moisés y los profetas, como
      sobre todo el mismo Cristo Señor, hicieron y pronunciaron muchos y
      clarísimos milagros y profecías; y de los apóstoles leemos: <<Y ellos
      marcharon y predicaron por todas partes, cooperando el Señor y confirmando
      su palabra con los signod que se seguían>> \textins{\emph{Mc 16,20}}. Y
      nuevamente está: <<Tenemos palabra profética más firme, a la que hacéis bien
      en atender como a una antorcha que brilla en un lugar tenebroso>>
      \textins{\emph{2 Pe 1,19}}.}
  \item La advertencia del Deuteronomio: \blockquote{Todo lo que yo os mando, lo
      debéis observar y cumplir; no añadirás ni suprimirás nada. Si surge en medio
      de ti un profeta o un visionario soñador y te propone: \enquote{Vamos en pos
        de otros dioses ---que no conoces--- y sirvámoslos}, aunque te anuncie una
      señal o un prodigio y se cumpla la señal o el prodigio, no has de escuchar
      las palabras de ese profeta o visionario soñador. (Dt 13, 1--4a)}
  \item \emph{On the proof of the spirit and of Power} de Lessing. Del cual
    considera varios puntos, pero se enfoca en su argumento central:
    \blockquote[La traducción al inglés de este fragmento es de Anscombe,
    {\cite[Cf.~][22]{anscombe2008faith:prophandmi}}: Who denies it ---I do not---
    that the reports of those miracles and prophecies are just as trustworthy as
    any historical truth can be? ---But now: if they are only so trustworthy, why
    are they so used as suddenly to make them infinitely more trustworthy? How? By
    building quite different things, and more things, on them, than one is
    entitled to build on historically evidenced truths. If no historical truth can
    be demonstrated, then neither can anything be demonstrated by historical
    truths. That is: accidental historical truths can never become the proof of
    necessary truths of reason.]{¿Quién lo niega ---no lo hago yo--- que los
      informes de esos milagros y profecías son tan dignos de confianza como puede
      ser cualquier verdad histórica? ---Pero ahora: si solo son tan merecedores
      de confianza, ¿por qué de repente son empleados como si fueran infinitamente
      confiables? ¿Cómo? Al construir cosas bastante distintas, y más cosas, sobre
      ellos, de las que se está en autoridad de construir sobre verdades de
      evidencia histórica. Si ninguna verdad historica puede ser demonstrada,
      entonces tampoco ninguna otra cosa puede ser demonstrada por medio de
      verdades históricas. Esto es: verdades contingentes en tanto que históricas
      nunca pueden llegar a ser prueba de verdades de razón en tanto que
      necesarias.}
  \end{enumerate}

#+END_SRC
*** Preámbulo: Análisis del argumento de Lessing
**** reasons for remark about certainty of Alexander
#+BEGIN_SRC latex
  Tras esta introducción, Anscombe comienza su discusión desenmarañando algunos
  puntos de los argumentos de Lessing. En su argumentación emplea como ejemplo de
  verdad histórica nuestra creencia en que hubo en el pasado una persona llamada
  Alejandro, que conquistó casi toda Asia en corto tiempo, entonces plantea el
  reto: \enquote{¿Quién, en consecuencia de esta creencia, estaría dispuesto a
    abjurar permanentemente de todo conocimiento que pueda entrar en conflicto con
    ella?}. Entonces invita a considerar, que después de todo, sería posible que
  la creencia en estas grandes conquistas podrían estar fundadas simplemente en
  los poemas de Quérilo que acompañó a Alejandro.\footnote{Cf.~ \enquote{We all
      believe that there was such a person as Alexander, who conquered almost all
      Asia in a short time. But who would stake something of great and permanent
      importance, whose loss was irreplaceable, on this belief? Who, in
      consequence of this belief, would forswear for ever all knowledge that
      should concflict with it? Certainly I should not. I have at present nothing
      to object against Alexander and his conquests; but it would after all be
      possible that they were founded on a mere poem of Choerilus who accompanied
      Alexander, just as the ten year siege of Troy is founded on nothing but
      Homer.}}

  Esta última propuesta resulta llamativa para Anscombe. Parece una alusión al
  hecho de que conocemos de Cristo por una fuente o tradición \enquote{única}. Sin
  embargo Anscombe piensa más bien que viene a apoyar la afirmación de que las
  verdades históricas no pueden ser fundamentos de verdades necesarias. Una verdad
  metafísica o una verdad matemática no puede seguirse de un hecho histórico, éste
  tendría que contar con el mismo grado de certeza que estas verdades de razón;
  pero una verdad histórica es muy incierta, como lo serían las conquistas de
  Alejandro, si solo supiéramos de ellas por los poemas de Quérilo. Ahora bien, a
  juicio de Anscombe, esta premisa no merece gran atención. El supuesto de que
  cualquier cosa creíble sobre Dios tiene que ser una verdad necesaria de razón le
  parece una derivación de las nociones de Leibniz de Dios como un ser necesario.
  En adición a esto, es una premisa apoyada sobre el supuesto de que las verdades
  de la religión son de tal naturaleza que la razón humana podría haber llegado a
  pensarlas por sí misma.
#+END_SRC
**** Algo de valor fe cierta no fundada en argumentos inciertos
#+BEGIN_SRC latex
  Anscombe sí encuentra valor en la premisa acerca de no afirmar certezas más allá
  de las que las verdades históricas nos dan la autoridad de justificar. La
  constitución del Vaticano I habla de los milagros y profecias cumplidas como
  solidos argumentos externos. ¿Puede una verdad histórica contar con certeza
  suficiente para representar un solido argumento externo? No es el papel de estas
  manifestaciones ser una demostración que reemplace el rol del Espíritu en la
  fundamentación de la fe. Entonces parece que verdades historicas que no puedan
  ser estimadas más que como probabilidades podrían jugar ese papel. ¿Se podría
  conceder que la fe no necesita de argumentos externos ciertos para ser abrazada?
  ¿Podrían emplearse errores históricos y argumentaciones equivocadas como una
  escalera que se usa para llegar a la fe y luego se descarta? Para Anscombe sería
  un error pensar que una \enquote{escalera} como esta podría acercarnos
  adecuadamente a la fe. Aunque se descarte la idea de Lessing de que toda
  creencia sobre Dios tiene que ser una verdad necesaria, hay algo de valor en la
  idea de que una fe cierta no se puede afirmar simplemente en argumentos externos
  con fundamentos inciertos.
#+END_SRC
**** Religión de Cristo/cristiana
#+BEGIN_SRC latex
  Es importante también tener en cuenta que la posición de Lessing ante el
  Cristianismo es incompatible con las creencias Cristianas. Emplea una analogía
  que ilustra su actitud: \blockquote[Suppose that a very useful mathematical
  truth had been reached by the discoverer through an obvious fallacy. \textelp{}
  Should I deny this truth? Should I refuse to use this truth? Would I be on that
  account an Ungrateful reviler of the discoverer, if I were unwilling to prove
  from his insight in other respects, indeed did not consider it capable of proof,
  that the fallacy through which he stumbled upon the truth could not be a
  fallacy?]{Supongamos que una muy útil verdad matemática haya sido alcanzada por
    su descubridor por medio de una falacia evidente. \textelp{} ¿Debería de negar
    esta verdad? ¿Sería a cuenta de esto un desagradecido agraviador del que ha
    realizado el descubrimiento, si fuera renuente a apoyarme en su inteligencia
    en otras consideraciones, ciertamente si no considerara capaz de demostración,
    que la falacia a través de la cual tropezó sobre la verdad podría no ser una
    falacia?} Su interés en Cristo es en la enseñanza que este maestro pueda
  ofrecer. Adicionalmente, su opinión es que lo que puede ser afirmado sobre Dios,
  no solo no pueden ser proposiciones que derivan su justificación desde
  afirmaciones históricas, sino que además no podrían ser afirmaciones
  incompatibles con lo que podría ser razonable en estimar como históricamente
  posible. Según esto, hace distinción entre la \emph{religión Cristiana} y la
  \emph{religión de Cristo}, atribuyendo lo obscuro o confuso de la enseñanza de
  Cristo transmitida en la \emph{religión Cristiana}, y lo claro y útil a la
  \emph{religión de Cristo}.
#+END_SRC
**** Certidumbre de los milagros
#+BEGIN_SRC latex
  Una aclaración adicional que Anscombe destaca es que, a su juicio, Lessing
  exagera la certidumbre (desde un punto de vista externo) que podría tener
  Orígenes de los milagros y profecías cumplidas. Tanto en su tiempo como en el
  nuestro los milagros serían hechos completamente extraordinarios y serían
  estimados por los escépticos con tanta incredulidad entonces como ahora,
  mientras que los Católicos los aceptan.
#+END_SRC
*** Análisis del argumento central
**** Sobre los milagros
  Primero sobre los milagros....
  los informes de estos no apelarían a un juez externo

  primero, acerca de los milagros
  hay que concedersele como ciertamente verdadero que los informes de estos no se
  puede esperar que apelen a un juez externo

  el principal y el que se usa en a pologética es la resurrección de Cristo
  Lessing concede que cuenta con tanta certeza como cualquier otro dato histórico
  Anscombe piensa que hay que oponerse a esta concesión ¿Que tiene de poco
  razonable decir Dios sabe lo que produjo esta creencia? yo no lo se, tampoco
  puedo sacar conclusiones de la posterior obra de los apóstoles o de la aparición
  repentina y siguiente crecimiento de una nueva religión, que es, después de
  todo, de lo único que estoy segura.

  Lo más que puedo conceder es que la crónica es bastante como si estas cosas
  hubieran ocurrido: el modo no es legendario, aunque la materia lo es!


#+BEGIN_SRC latex
  Hechas estas consideraciones preliminares, Anscombe estudia el argumento central
  establecido por Lessing. Su impresión es que la objeción de Lessing consiste
  fundamentalmente en: \enquote{Pero estas cosas \emph{pueden} no ser verdad,
    ¿cómo puedo emplearlas para apoyar el Cristianismo?}. El argumento es útil,
  puesto que no se orienta a atacar la veracidad de los milagros o cumplimientos
  de profecías que han quedado documentados, sino que pone en duda que estos
  testimonios o relatos puedan ser fundamento suficiente para sostener la creencia
  en el Cristianismo como justificada. En esto está claramente en conflicto con la
  afirmación de Vaticano I.

  Por su parte, la afirmación de \emph{Dei Filius} es de extraordinario interés
  puesto que, a juicio de Anscombe, la experiencia más común es que creamos en las
  profecías cumplidas y los milagros porque creemos en la religión Católica y
  éstos forman parte de su enseñanza. Si tomamos esto en cuenta junto con la
  enseñanza del Deuteronomio y una reflexión razonable acerca de lo que la fe
  requiere, tendríamos que decir que para que se puedan tomar los milagros y las
  profecías cumplidas como \enquote{solidos argumentos externos}, éstos tendrían
  que quedar determinados como tales antes de que quede afirmada la creencia en el
  Cristianismo. Pero, ¿acaso no hay ya cierto elemento teológico en designar algo
  como una profecía cumplida o milagro? ¿En que situación está un juez o
  historiador indiferente de la religión que recibe noticias de un milagro o de
  profecías cumplidas? ¿Pueden ser éstos solidos argumentos externos para creer en
  la religión Católica?

  El análisis de Anscombe se desarrollará en torno a la posibilidad de sostener
  creencias ciertas teniendo como fundamento los informes de milagros, o la
  certeza de los relatos históricos o las profecías cumplidas que puedan ser
  consideradas claras por su antigüedad, prioridad y realización.

  En cuanto a los informes de milagros, Anscombe sostiene con Lessing que éstos no
  apelarían a un juez que sea externo a las creencias religiosas. Podemos estimar
  la resurrección de Cristo como signo principal de la apologética. A esta noticia
  Lessing le concede tanta certeza como la que pueda tener un dato histórico,
  Anscombe no está de acuerdo con esto. Le parece que no es irrazonable decir:
  \blockquote[{\cite[26]{pnm}}: `Heaven knows what happened to produce this
  belief; I do not. And I know much too little about what may go on in human minds
  in the origins of embracing a new religious belief, to draw any conclusions (as
  I am so often pressed to do) from the subsequent careers of the Apostles
  (supposing them to be truly related in the main) or from the sudden appearance
  and growth of a new religion, which after all is all I am really perfectly
  certain of. I do know one thing: new religions sometimes spread like wildfire.
  How this works, and how it gets established in them is obscure. I concede that
  this is an impressive religion too; but then it had a very impressive religion
  behind it: that of the Old Testament. Remember that beliefs in miraculous events
  in connexion with the founders and heroes of religion are quite common. The most
  I can grant is that the record is quite as if these things had happened: the
  manner is not legendary, though the matter is!']{Dios sabe qué ocurrió para que
    se produjera esta creencia; yo no lo sé. Además conozco muy poco de lo que
    ocurre en las mentes humanas en los orígenes de abrazar una creencia religiosa
    nueva, como para sacar alguna conclusión \textelp{} de las subsiguientes
    misiones de los Apóstoles \textelp{} o de la repentina aparición y crecimiento
  de una nueva religión, de lo que después de todo es todo de lo que estoy
  perfectamente segura. Sí conozco una cosa: las religiones nuevas a veces se
  propagan como el fuego. Cómo funciona esto, y cómo queda establecido en ellas es
  oscuro. Concedo que ésta es una religión impresionante también; pero ha tenido
  una religión impresionante tras ella: la del Antiguo Testamento. Recuerda que
  las creencias de eventos milagrosos en conexión con los fundadores o héroes de
  una religión son bastante comunes. Lo mayor que puedo conceder es que la noticia
  es bastante como si estas cosas hubieran ocurrido: ¡el modo no es legendario,
  aunque la materia sí!}
  Aquí la cuestión importante para Anscombe es cómo ha llegado a ocurrir que estos
  informes aparentemente fácticos hayan llegado a quedar escritos y transmitidos
  de este modo y qué tipo de hipótesis podría explicar este hecho. Si
  efectivamente estos hechos han ocurrido, ¿de qué naturaleza esperaríamos que
  fueran los documentos y noticias que nos los transmiten? Sin embargo, no sería
  razonable pedir a un historiador indiferente que resuelva este problema, sobre
  cómo han llegado a existir estos documentos y tradiciones, no sería irrazonable
  para él dejar sin respuestas estas preguntas.\footnote{pnm p. 37}

  En donde Elizabeth estima que Lessing no tiene razón es en decir que ninguna
  certeza histórica puede ser suficientemente fuerte como para tener un peso
  absoluto. Si es la fuerza de la certeza lo que se está realmente poniendo en
  duda, le parece a Anscombe que no es cierto que la certeza histórica sea siempre
  demasiado débil como para fundamentar una certeza absoluta.

  I object to his lumping together everything historical as of inferior certainty
  to my own experience.


  En efecto,

  there could be no reason to think one knew what any historical evidence
  suggested at all, if a great range of things in history were not quite solid

  nos quedaríamos sin razonamientos para pensar que sabemos lo que cualquier
  evidencia historica podría sugerir del todo, si una gran gama de cosas en la
  historia no fueran totalmente sólidas

  Elizabeth atiende ambas cuestiones

  Primero Lessing
  hay que concederle a Lessing que los informes de estos no apelarían a un juez
  externo


  37: el rol de los milagros que he sostenido que no pueden ser aceptados como
  hechos ciertamente verdaderos por un historiador indiferente, me parece que es:
  si alguien está seriamente considerando la verdad de toda la revelación en el
  modo que he descrito, los milagros son consonos.

  En donde Lessing no tiene razón, a juicio de Anscombe es en decir que ninguna
  certeza histórica puede ser suficientemente fuerte como para ser absoluta

  si lo que se está poniendo en duda es la fuerza de la certeza, no es cierto que
  la certeza histórica no pueda servir como fundamento de la certeza absoluta

  aunque también parece que hay algo en el argumento que tiene que ver más bien
  con saltar a otra clase de verdades.

  pero si nos concentramos en la fuerza de la certeza

  anscombe se opone a su amontonar todo lo histórico como de inferior certeza que
  mi experiencia personal

  27: mientras que cosas que hagan remotamente probable que no hubo un Alejandro
  son inconcebibles; no podría haber razón para pensar que uno conoce qué puede
  sugerir del todo algún tipo de evidencia histórica si no fuera porque un gran
  número de cosas en la historia no fueran ciertamente solidas. La experiencia,
  excepto si es hecha correcta por definición, no es más, sino menos cierta; y lo
  que yo juzgo desde mi experiencia puede, parte de ello, más fácilmente estar
  equivocada




  Luego dei filius

  So far as I can see there has to be a thesis of natural theology... that someone
  is divinely attested

  what does this rest on? it might rest on faith



  El análisis de Anscombe examina cuatro dimensiones del argumento de Lessing. Los
  milagros, la certeza histórica como fundamento de las creencias, las profecías y
  a quién pueden apelar estos argumentos externos que son los milagros y las
  profecías (o si estas pueden apelar a un juez externo o historiador apático)

#+END_SRC

**** Sobre apostar por creencias apoyados en la fuerza de la certeza histórica
**** Sobre las profecías
*** Conclusiones
  El análisis de Anscombe en torno al argumento de Lessing toca varios puntos

  Principalmente sostiene que Lessing tiene razón cuando propone que

  Luego sobre staking beliefs on the strenght of historical certainty
  hay una clase de aserciones históricas que sería absurdo atribuirles certeza
  pero ya pasó el tiempo en que podría disprove them

  Luego sobre las profecías....
  Sticking with things thar are absolutely solid.....

  it is solid that it was anciently written down as prophecy
  that Jerusalem.....
  If lessing tells me i know the ancientness only historically i can reply that
  this sort of certainty is good enough as any

  NOW prophecies..... whose ancientness, priority and fulfulment are really clear
  to a detched observer ar necessarily few
  this is because Lessing puts up a condition.... we have to judge that the thing
  that happened, not mere was describable in the words occurring in the
  prediction, but was what was predicted

  but there are special difficulties about the notion of the applicability of
  prophetical words as accidental

  two points anscombe makes here:

  to see a prophecy fulfiled is to interpret them
  a prophecy fulfilled or a miracle done have to attest something

  something else about what can it mean for prophecy to be fulfiled

  this is the very sort of thing for that man, or these men, to have said;

  Puesto así parece fuerte
  Está en conflicto con la afirmación del Vaticano
  Su argumento es valioso pq no confunde el problema atacando la verdad de los
  milagros o cumplimientos de profecias documentados

  es de interés extraordinario lo que dice dei filius pq
  creemos en profecias cumplidas y milagros porque creemos la religion católica
  y estos forman parte de nuestras doctrinas

  además
  el pasaje del deut, junto con reflexión razonable en los requisistos de la fe
  nos inclinarían a decir que un profeta o milagrero debe ser juzgado a la luz de
  la fe cristiana (no la fe cristiana a la luz de las profecias y milagros)

  si son argumentos externos entonces parece que deberian quedar establecidos como
  tal antes de que quede introducida la creencia en el cristianismo:
  pero no hay un elemento teológico en llamar algo una profecía cumplida, e
  incluso, un milagro?

  Hay que conceder a Lessing que los informes de milagros

  Ahora profecias cuya antiguedad, prioridad y cumplimiento sean verdaderamente
  claras y ciertas para un observador imparcial son necesariamente pocas....

  Un monton de pasajes suenan como profecias para Crisitanos creyentes o Judios
  piadosos, pero suenan como afirmaciones misteriosas de textos antiguos para
  cualquier otra persona

  puede ser un accidente el cumplimiento de una profecia?

  es juzgada como profecia una afirmación que simplemente puede ser aplicada a
  hechos futuros?

  hay algunas dificultades sobre la noción de la aplicabilidad de palabras
  proféticas como accidentales

  para casi todas las profecias, verlas cumplidas es interpretarlas e
  interpretarlas no es preguntarse si el profeta tenia en mente estos eventos...

  sino que lo que podemos hacer es considerar las ocasiones en las que el profeta
  profesando profetizar afirmó estas palabras y valorar lo que dijo considerando
  todo su contexto, a los eventos que pensamos que estas palabras profetizaron

  la pregunta surge, por qué deberiamos impresionarnos del todo con las profecias?
  por qué nos deberían interesar?

  Una profecía o milagro se supone que atesta algo

  Hay un sentido del término accidental distinto al que Lessin emplea

  Las partes son: preámbulo...
  discusión del argumento central....
  -> a quién pueden decirle algo las profecias cumplidas o los milagros, para
  quién son argumentos externos? para un observador imparcial que por primera vez
  quiere conocer justo lo que la fe enseña?

  I have contended miracles cannot possibly be accepted as certainly true
  ocurrences by the indifferent historian

  their role is this: \blockquote[if one is seriously entertaining the truth of
  the whole revelation in the way I have hinted at, the miracles are consonant.
  That God attested Christ by miracles is possible, if Christ is Christ ---i.e. is
  the Messiah promised in the Old Testament. Then the problem, how on earth these
  seemingly factual records came to be written, of such incredible things, is
  resolved by the hypothesis that they happened.]{si estamos considerando
    seriamente la verdad de toda la revelación en el modo al que he aludido, los
    milagros son consonos. Que Dios atestó a Cristo por medio de los milagros es
    posible, si Cristo es Cristo ---esto es, es el Mesías prometido en el Antiguo
    Testamento. Entonces el problema, sobre cómo es posible que estas crónicas
    supuestamente fácticas han llegado a quedar escritas, de unos eventos tan
    increíbles, se resuleve por la hipótesis de que sí ocurrieron.}

  Un historiador indiferente puede dejar sin resolver la pregunta, ¿sí ocurrieron,
  qué características esperaríamos que tengan los documentos donde quedan
  relatados? Y si ocurrieron, acaso no apoyan la enseñanza?

  Pero y es posible del todo la atestación divina?

  El hecho de que alguien de muestras de hacer cosas milagrosas o que diga
  profecias que se cumplen, ciertamente no muestran que esté atestado divinamente.

  Según veo, tiene que haber una tesis de teología natural, como podría llamarla,
  de que si alguien realiza `una señal y un prodigio' o dice una profecía que se
  cumple, en el nombre de Dios, entonces está atestado divinamente. Ahora en qué
  descansa esto? Puede descansar en fe.

  Las enseñanzas de los profetas deben ser primero tales que pudieran
  razonablemente entendidas como perteneciendo a la verdad revelada por Moisés;
  solo si esto es así entonces es posible proponer la pregunta. Entonces, si
  predice algo y esto ocurre, y si no intenta conducirles a la idolatría después
  de esto, entonces está atestado.

  Esto podría entenderse como matería de fe. Pero si eso que constituye atestación
  divina sólo es conocido por la fe, entonces en qué quedan los `solidos
  argumentos externos' de la constitución del Vaticano?

  Pienso entonces que el argumento más bien tiene que se que si un profeta que
  aparentemente está enseñando la verdad, se atreve a predecir algo contingente,
  entonces esto es presunción suya si no es el caso que lo ha recibido de Dios y
  debe decirlo. Ahora si enseña una mentira inmediatamente después, o si lo que ha
  dicho no ocurre, entonces queda demostrado presuntuoso. Pero si no es demostrado
  presuntuoso, entonces no debemos atrevernos a no creerle u obedecerle: mientras
  que lo que dice no entre en conflicto con la verdad conocida.


  -> los argumentos de profecias y milagros tienen peso para alguien que haya
  atendido a las enseñanzas del AT

  Ahora, si todo esto es así, el observador imparcial e indiferente queda
  confrontado ciertamente solo por algunas profecias dispersas relacionadas con
  ciudades y personas; y con \emph{informes} de milagros y de cumplimientos de
  profecias los cuales es absurdo pretender que deba tener en cuenta como
  ciertamente ciertos.
  Que pasa entonces con los solidos argumentos externos de la constitución?

  Esbozaré mi respuesta brevemente: Sólo si un hombre queda impresionado por el
  Antiguo Testamento, al punto de sentirse inclinado a tomarlo como su maestro,
  tiene entonces el argumento desde profecias y milagros algún peso serio.

  En prophecy and miracles Anscombe destaca la propuesta de Vaticano I acerca de los
  argumentos externos.
  Al tener esto en cuenta, lanza la pregunta: Esto podría ser tomado como materia de fe,
  ¿Pero si aquello que constituye atestación divina puede ser conocido solo por la fe, en
  que queda lo que dice el concilio?

  lo primero es que un "historiador apático" no podría aceptar el rol de los milagros
  como hechos ciertamente verdaderos, no sería razonable pedir al historiador apático que
  resuelva el problema de cómo han llegado a quedar escritos estos relatos.

  Una persona que haya tomado como maestro el AT, para alguien así sí que tendría peso
  las profecías cumplidas o los milagros

  Para Anscombe debe haber una tesis de teología natural que afirme qué implica que una
  persona está divinamente atestada

  Esta tesis no tiene que ser materia de fe

  El argumento puede ser que si no queda probado presuntuoso entonces no podriamos no
  obedecerle

  pero no basta un motivo negativo

  puede uno creer porque no tiene signos de que este hombre sea presuntuoso?
  y entonces hay que considerar que una de dos o es presuntuoso o lo que dice viene de
  Dios? y entonces como no hay signos de que sea presuntuoso, pues viene de Dios?

  Seguramente querríamos razones positivas para creer, y no meramente ausencia de razón
  positiva para descreer?

  Esto, me parece, es correcto, y va con la tesis de que en cierto sentido no puede haber
  un profeta con una nueva doctrina.

  Con estas cosas y lo que dice en 'faith' se podría construir una descripción de lo que
  Anscombe considera como atestación divina



- Preamble, before considering Lessing's central argument

- His argument boils down to: 'But these things may not be true, so how can I use them
  to support Christianity?'
- Miracles and fulfilled prophecies are said to offer solid external arguments for the
  truth of christianity, but isn't there a theological element in calling something a
  fulfilled prophecy or miracle?
- Lessing seems right in saying that the reports of miracles could not be expected to
  appeal to an external judge
- Lessing seems to be wrong in saying that 'no historical certainty can be strong enough
  to be absolute'
  + If it is strength of certainty that is really in question
    - it is not true that historical certainty is always too weak to base absolute
      certainty upon it
      + Probability may come in regarding an historical truth, but it doesn't begin to
        come in at the start
      + Anscombe objects to Lessing's lumping together everything historical as of
        inferior certainty to our own experience
    - That Christ claimed to be the Son of God and that he rose from the dead belongs
      to a class of historical assertions which it would be absurd to claim certainty
      for, but the time for disproving which is past.
    - What would be solid in this fashion is that Christ existed, preached, like an Old
      Testament prophet, and was at least ostensibly crucified under Roman authority;
      and that believers took him for the Messiah and the son of God, and believed he
      had risen from the dead
  + If we stick to things that are solid, and avoid what may be regarded as accidential
  + Lessing disputes priority and certainty
- The critical principle that prophetical wriings must have been clealy intelligible in
  their own time is itself a denial of the possibility of all but prophecy of a very
  restricted type
  + That is to say: for almost all prophecies, to see them fulfilled is to interpret
    them
- Prophecies must attest something
- If all this is so, the impartial indifferent observer is confronted quite certainly
  only with a few scattered prophecies relating to cities and peoples; and with reports
  of miracles and of fulfilments of prophecies which it is absurd to pretend he must
  regard as certainly true.
  - So what becomes of the 'solid external arguments'?
- Only if a man is impressed by the Old Testament, to the extent of being inclined to
  take it as his teacher, has the argument from prophecies and miracles any serious
  weight.
- When St. Agustine said that fulfilment of the prophecies in Christ was the greates
  proof of his divinity, what he said was true; but the proof requires a very special
  position on the part of someone who is to consider it.
  - This is why the kind of apologetic that Lessing argued against, which did not
    assume that position, was so vulnerable and stupid.
- The miracles are consonant, That God attested Christ by miracles is possible, if he
  is the Messiah promised in the Old Testament.
  - The problem about how these seemingly factual records came to be written, of such
    incredible things, is resolved by the hypothesis that they happened.
- With this we come to the problem of the notion of divine attestation at all.
  - There has to be a thesis of natural theology, that if someone works 'a sign and a
    wonder' or utters a prophecy which gets fulfilled, in God's name, then he is
    divinely attested.
  - This might be taken as a matter of faith, but then, what about the 'solid external
    arguments'?
  - I think the argument must be rather that if a prophet who is apparently teaching
    that truth, dares to foretell something contingent, then this is presumption of him
    unless he has it from God and must say it. Now if he teaches a lie straight away
    afterwards, or if the thing does not happen, then he is proved presumptuous. But if
    he is not proved presumptuous, then we ought not to dare not to believe and obey
    him: so long as what he says does not conflict with the known truth.


So far as I can see there has to be a *thesis of natural theology*, as I might call it,
that if someone works ‘a sign and a wonder’ or utters a prophecy which gets fulfilled,
in God’s name, then he is divinely attested. Now what does this rest on? It might rest
on faith. In Deuteronomy, when the Jews were forbidden to consult soothsayers and
necromancers, and omens, they were promised prophets ‘like Moses’ whom they were to
attend to instead. But, the passage goes on, they’ll want to know how to tell a
prophet. And the answer is: if the prophet foretells something, and it doesn’t happen,
then that was just his presumption. The implication seems to be that if a prophet of
their people, apparently teaching according to the Law, foretells something and it does
happen, he is attested.


p. 37 Now what does this rest on? It might rest on faith. In Deuteronomy, when the Jews
were forbidden to consult soothsayers and necromancers, and omens, they were promised
prophets ‘like Moses’ whom they were to attend to instead.

** Hume and Julius Caesar (1973)
:PUBLICATION_INFO:
Originally published in october 1973 vol 34 Issue 1 of Analysis Journal Reprinted in
CPP I in 1981 p. 86-92
:END:
#+BEGIN_SRC latex
\subsection{Hume and Julius Caesar}
#+END_SRC
*** Intro 1: este ensayo y los otros
:TEXT:
In the present volume the lengthy paper ‘Hume on causality: introductory’ is the matrix
from which Anscombe extracted ‘Hume and Julius Caesar’ and ‘“Whatever has a beginning
of existence must have a cause”: Hume’s Argument Exposed’.[2] It is published here as
an example of the scrupulous and attentive study she devoted to major philosophers
which is abundantly evident in her unpublished papers.
:END:
#+BEGIN_SRC latex
  Los artículos \emph{Hume and Julius Caesar} y \emph{``Whatever has a beginning
    of existence must have a cause'': Hume’s Argument Exposed} de Anscombe, fueron
  publicados en la revista académica \emph{Analysis} en octubre de 1973 y abril de
  1974 respectivamente. Ambos están relacionados por el tema de la causalidad en
  Hume. En el trasfondo de los dos artículos está otro documento no publicado
  hasta 2011 con el título \emph{Hume on causality: introductory}.
#+END_SRC
*** Intro 2: Hume es interesante porque abre buenas cuestiones
#+BEGIN_SRC latex
  Anscombe again and again found in Hume a starting point for her discussions; and
  we must not be misled bye her frequent dissent from his views into thinking of
  her as `anti-Humean'. Indeed, in her treatment of the topic of causation
  Anscombe can even be seen as continuing Hume's work---as out-Huming Hume.
  teichmann 177

    Una de las actitudes características de Anscombe es su tendencia a quedar
    atraída por preguntas que representan cuestiones profundas, incluso en
    discusiones cuyos argumentos, método o conclusiones no le parecen tan
    interesantes.

    Un autor que suele tener este efecto en ella es Hume. En \emph{Modern Moral
      Philosophy} dice:

    \blockquote[{\cite[172]{anscombe1981mmph}}: The features of Hume’s philosophy
    which I have mentioned, like many other features of it, would incline me to
    think that Hume was a mere ---brilliant--— sophist; and his procedures are
    certainly sophistical. But I am forced, not to reverse, but to add to this
    judgement by a peculiarity of Hume’s philosophizing: namely that, although he
    reaches his conclusions --—with which he is in love--— by sophistical methods,
    his considerations constantly open up very deep and important problems. It is
    often the case that in the act of exhibiting the sophistry one finds oneself
    noticing matters which deserve a lot of exploring: the obvious stands in need of
    investigation as a result of the points that Hume pretends to have made.]{Las
      características de la filosofía de Hume que he mencionado, como muchas otras
      de sus características, me hacen inclinarme a pensar que Hume era un simple
      ---brillante--- sofista; y sus procedimientos son ciertamente sofísticos. Sin
      embargo me veo forzada, no a retractarme, sino a añadir a este juicio por la
      peculiaridad del filosofar de Hume: a saber, que aunque llega a sus
      conclusiones ---con las que está enamorado--- por métodos sofísticos, sus
      consideraciones constantemente abren problemas bien profundos e importantes.
      Frecuentemente es el caso que en el acto de exhibir la sofística uno se
      encuentra a sí mismo notando temas que merecen mucha exploración: lo obvio
      queda necesitado de investigación como resultado de los puntos que Hume
      pretende haber hecho.}
#+END_SRC
*** Fundamento de creencias más allá impresiones es una buena cuestión
#+BEGIN_SRC latex
  En el artículo \emph{Hume and Julius Caesar} la discusión que capta el interés
  de Anscombe se encuentra en la sección IV de la tercera parte del \emph{Treatise
    of Human Nature} sobre el tema de la justificación de nuestro creer en
  cuestiones que están más allá de nuestra experiencia y memoria. Anscombe cita el
  texto de Hume como sigue:

  \blockquote[{\cite[86]{anscombe1981hjc}}When we infer effects from causes, we
  must establish the existence of these causes\ldots either by an immediate
  perception of our memory or senses, or by an inference from other causes; which
  causes we must ascertain in the same manner either by a present impression, or
  by an inference from their causes and so on, until we arrive at some object
  which we see or remember. 'Tis impossible for us to carry on our inferences
  \emph{in infinitum}, and the only thing that can stop them, is an impression of
  the memory or senses, beyond which there is no room for doubt or enquiry.
  (Selby-Bigge's edition, pp. 82--3)]{Cuando inferimos efectos partiendo de causas
    debemos establecer la existencia de estas causas\ldots ya sea por la
    percepción inmediata de nuestra memoria o sentidos, o por la inferencia
    partiendo de otras causas; causas que debemos explicar de la misma manera por
    una impresión presente, o por una inferencia partiendo de sus causas, y así
    sucesivamente hasta que lleguemos a un objeto que vemos o recordamos. Es
    imposible para nosotros proseguir en nuestras inferencias al infinito, y lo
    único que puede detenerlas es una impresión de la memoria o los sentidos más
    allá de la cual no existe espacio para la duda o indagación.}
#+END_SRC
*** un presupuesto y dos argumentos:
**** relación causa-efecto puente hacia cuestiones más allá de impresiones
:TEXT:
When we infer effects from causes, we must establish the existence of these causes;
which we have only two ways of doing, either by an immediate perception of our memory
or senses, or by an inference from other causes; which causes again we must ascertain
in the same manner, either by a present impression, or by an inference from their
causes, and so on, till we arrive at some object, which we see or remember.
:END:
#+BEGIN_SRC latex
  Ya en la sección II de esta misma parte del \emph{Treatise}, Hume ha planteado
  cómo es la causalidad la conexión que nos asegura la existencia o acción de un
  objeto que es seguido o precedido por la existencia o acción de
  otro.\footnote{Cf. Treatise Sección II Parte III: ’Tis only causation, which
    produces such a connexion, as to give us assurance from the existence or
    action of one object, that ’twas follow’d or preceded by any other existence
    or action; nor can the other two relations be ever made use of in reasoning,
    except so far as they either affect or are affected by it. }
  Ahora en la sección IV esta relación de causa y efecto será tomada como un
  principio de asociación de ideas según el cual es posible inferir desde la
  impresión de alguna cosa, una idea sobre otra cosa.

  Desde esta noción de causalidad se explica la posibilidad de acceder a hechos
  más allá de nuestra experiencia; estos son inferencias de efectos desde sus
  causas. De este modo: \blockquote[{\cite[87]{anscombe1981hjc}}: For Hume, the
  relation of cause and effect is the one bridge by which to reach belief in
  matters beyond our present impressions or memories.]{Para Hume, la relación de
    causa y efecto es el único puente por el que se puede alcanzar creer en
    cuestiones más allá de nuestras impresiones presentes o memorias.}
#+END_SRC
*** Ilustración: punto histórico, por qué razón lo creemos o rechazamos
**** we believe that Caesar was killed
:TEXT:
  To give an instance of this, we may chuse any point of history, and consider for what
  reason we either believe or reject it. Thus we believe that Cæsar was kill’d in the
  senate-house on the ides of March; and that because this fact is establish’d on the
  unanimous testimony of historians, who agree to assign this precise time and place to
  that event. Here are certain characters and letters present either to our memory or
  senses; which characters we likewise remember to have been us’d as the signs of
  certain ideas; and these ideas were either in the minds of such as were immediately
  present at that action, and receiv’d the ideas directly from its existence; or they
  were deriv’d from the testimony of others, and that again from another testimony, by
  a visible gradation, ’till we arrive at those who were eye-witnesses and spectators
  of the event. ’Tis obvious all this chain of argument or connexion of causes and
  effects, is at first founded on those characters or letters, which are seen or
  remember’d, and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain wou’d
  in that case hang upon another; but there wou’d not be any thing fix’d to one end of
  it, capable of sustaining the whole; and consequently there wou’d be no belief nor
  evidence. And this actually is the case with all hypothetical arguments, or
  reasonings upon a supposition; there being in them, neither any present impression,
  nor belief of a real existence.
:END:
#+BEGIN_SRC latex
  El paso adicional que Hume propone en esta sección es que al realizar estas
  inferencias es necesario establecer la existencia de las causas por medio de la
  percepción inmediata de los sentidos o por medio de una ulterior inferencia. Sin
  embargo, el establecimiento de la existencia de estas causas por medio de
  inferencias no puede continuar infinitamente, sino que tiene que llegar a una
  impresión de la memoria o los sentidos que sirva de justificación o fundamento
  definitivo.

  Para ilustrar este paso, Hume hace una invitación interesante:
    \blockquote[{\cite[?]{humetreatise}}: chuse any point of history, and consider
    for what reason we either believe or reject it.]{elegir cualquier punto en la
      historia, y considerar por qué razón lo creemos o rechazamos.} Acerca de una
    creencia histórica se nos invita a considerar sobre qué se sostiene su
    justificación. ¿Cuál es su fundamento?:
    \blockquote[{\cite[?]{humetratise}}: Thus we believe that Cæsar was kill’d in
    the senate-house on the ides of March; and that because this fact is establish’d
    on the unanimous testimony of historians, who agree to assign this precise time
    and place to that event. Here are certain characters and letters present either
    to our memory or senses; which characters we likewise remember to have been us’d
    as the signs of certain ideas; and these ideas were either in the minds of such
    as were immediately present at that action, and receiv’d the ideas directly from
    its existence; or they were deriv’d from the testimony of others, and that again
    from another testimony, by a visible gradation, ’till we arrive at those who
    were eye-witnesses and spectators of the event. ’Tis obvious all this chain of
    argument or connexion of causes and effects, is at first founded on those
    characters or letters, which are seen or remember’d, and that without the
    authority either of the memory or senses our whole reasoning wou’d be chimerical
    and without foundation.]{Así, creemos que César fue asesinado en el Senado en
      los idus de Marzo; y esto porque el hecho está establecido basándose en el
      testimonio unánime de los historiadores, que concuerdan en asignar a este
      evento este tiempo y lugar precisos. Aquí ciertos caracteres y letras se
      hallan presentes a nuestra memoria o sentidos; caracteres que recordamos
      igualmente que han sido usados como signos de ciertas ideas; y estas ideas
      estuvieron ya en las mentes de los que se hallaron inmediatamente presentes a
      esta acción y que obtuvieron las ideas directamente de su existencia; o fueron
      derivadas del testimonio de otros, y éstas a su vez de otro testimonio, por
      una graduación visible, hasta llegar a los que fueron testigos oculares y
      espectadores del suceso. Es manifiesto que toda esta cadena de argumentos o
      conexión de causas y efectos se halla fundada en un principio en los
      caracteres o letras que son vistos o recordados y que sin la autoridad de la
      memoria o los sentidos nuestro razonamiento entero sería quimérico o carecería
      de fundamento.}
#+END_SRC
*** Catching Hume on his mistake
**** it must be purely hypothetical inference
#+BEGIN_SRC latex
  Anscombe comienza por reaccionar afirmando:
  \blockquote[{\cite[86]{anscombe1981hjc}}: This is not to infer effects from
  causes, but rather causes from effects.]{Esto no es inferir efectos partiendo de
    sus causas, sino más bien causas desde los efectos.} Es decir, el ejemplo
  histórico de Hume consiste en una inferencia de la causa original, el asesinato
  de Julio César, desde su efecto remoto que es nuestra percepción en el presente.
  Creemos en el asesinato de César porque lo inferimos como la causa última en una
  cadena causal que llega hasta nuestra percepción de ciertas oraciones que
  leemos. El hecho de que estemos leyendo esta información es la percepción que
  justifica la creencia de que hay una cadena de causas y efectos que tiene como
  efecto esta experiencia. Esta inferencia pasa a través de una cadena de efectos
  de causas, que son efectos de causas\ldots ¿Dónde empieza la cadena? La
  respuesta parece ser nuestra percepción presente. ¿Cómo hemos de entender,
  entonces, el argumento de que la cadena no puede continuar infinitamente? La
  propuesta de Hume es que la cadena ha de terminar en una impresión que no deje
  lugar a dudas o busqueda mas allá, sin embargo, la cadena termina en el
  asesinato de Julio César, no en nuestra percepción. La imagen que Hume pretende
  ofrecer es la de una cadena fijada en sus dos extremos por algo distinto a los
  eslabones que la componen, sin embargo, no lo logra, más bien parece describir
  un voladizo, una estructura apoyada en un punto, pero sin apoyo en el otro
  extremo.

  La afirmación \blockquote['Tis impossible for us to carry on our inference in
  infinitum]{Es imposible para nosotros proseguir en nuestras inferencias al
    infinito} viene a significar, según la interpretación de Anscombe, que
  \blockquote[the justification of the grounds of our inferences cannot go on in
  infinitum]{la justificación de los fundamentos de nuestras inferencias no pueden
    continuar al infinito}. El argumento aquí mas bien es que tiene que haber un
  punto de partida para la inferencia de la causa original. La relación de
  inferencias propuesta por Hume en su ilustración acabaría siendo una inferencia
  hipotética según su propia definición. Anscombe explica diciendo:

  \blockquote[hume in causality: We must suppose ourselves to start with the
  familiar idea, merely as idea, of Caesar having been killed. Now if we ask why
  we believe it we shall, as Hume does, point to historical testimony (the
  ‘characters and letters’), which doesn’t at this point figure as what stops
  inference going on ad infinitum. However, if we want to explain the connection
  we shall form the idea of Caesar’s death being recorded by eyewitnesses; and
  these records having been received by others, who transmitted an account ...
  etc. Here we really are arguing from the idea of an original cause to the idea
  of an effect; we are ‘inferring effects from causes’, though only in the sense
  of passing from the idea of the cause to the idea of the effect.]{Tendríamos que
    suponer que comenzamos con la idea familiar, meramente como una idea, de que
    César fue asesinado. Ahora si preguntamos por qué lo creemos hemos de, como
    hace Hume, señalar al testimonio histórico (los `caracteres y letras'), lo
    cual en este punto no figura como lo que detiene que la inferencia siga al
    infinito. Sin embargo, si queremos explicar la conexión tenemos que formular
    la idea de la muerte del Cesar siendo recordada por testigos; y esos recuentos
    siendo recibidos por otros, quienes transmitieron un informe\ldots etc. Aquí
    estamos realmente razonando desde la idea de una causa original a la idea de
    un efecto; estamos `infiriendo efectos de causas', pero solo en el sentido de
    pasar de la idea de la causa a la idea del efecto.}

  Desde este análisis, Anscombe resume lo argumentado por Hume en cuatro partes:

  \blockquote[humeandjulius 88: First, a chain of reasons for a belief must
  terminate in something that is believed without being founded on anything else.
  Second, the ultimate belief must be of a quite different character from derived
  beliefs: it must be perceptual belief, belief in something perceived, or
  presently remembered. Third, the immediate justification for a belief p, if the
  belief is not a perception, will be another belief q, which follows from, just
  as much as it implies, p. Fourth, we believe by inference through the links in a
  chain of record

  There is an implicit corollary: when we believe in historical information
  belonging to the remote past, we believe that there has been a chain of record]{
    Primero, una cadena de razones para una creencia debe terminar en algo que se
    cree sin estar fundado en alguna otra cosa. Segundo, la creencia última debe
    ser de una naturaleza distinta a las creencias derivadas: Tiene que ser
    creencia perceptual, creer en algo percibido, or recordado en el presente.
    Tercero, la justificación inmediata de una creencia $p$, si la creencia no es
    una percepción, será otra creencia $q$, la cual se sigue, en la misma medida
    que implica, a $p$. Cuarto, creemos por inferencia a través de los eslabones
    en una cadena de relato.

    Hay un corolario implicito: cuando creemos en información histórica
    perteneciente a un pasado remoto, creemos que ha habido una cadena de relato.}

  Sin embargo, Anscombe considera que esta no es la manera adecuada de establecer
  esta relación. Mas bien: \blockquote[hjc 88: \emph{If} the written records that
  we now see are grounds of our belief, they are first and foremost grounds for
  belief in Caesar's killing, belief that the assassination is a solid bit of
  history. Then our belief in that original event is a ground for belief in much
  of the intermediate transmision.]{\emph{Si} los relatos escritos que vemos ahora
    son fundamento para nuestro creer, estos son primero y ante todo fundamento
    para la creencia en el asesinato de Cesar, creencia en que el asesinato es un
    pedazo sólido de historia. Entonces nuestra creencia en ese evento original es
    fundamento para el creer en mucha de la transimisión intermedia.}
  ¿Por qué creemos que hubo testigos del asesinato? Ciertamente porque creemos que
  hubo un asesinato. La creencia de que hubo testigos es inferida de la creencia
  en el hecho.

  Anscombe compara este modo de entender la cadena de transmisión de información
  histórica a nuestra creencia en la continuidad espacio-temporal. Si reconocemos
  en una ocasión a una persona conocida como alguien que vimos la semana pasada,
  nuestra creencia en que es la misma persona no es una inferencia de otra
  creencia acerca de la continuidad espacio-temporal de un patrón humano desde
  ahora hasta entonces, sino que más bien nuestra creencia en la continudad
  espacio-temporal esta inferida del reconocimiento de la identidad de la persona.
  Sin embargo, una evidencia sobre una interrupción en la continuidad sí alteraría
  nuestra creencia en la identidad.

  Elizabeth entonces concluye que: \blockquote[hjc 89: Belief in recorded history is
  on the whole a belief that there has been a chain of tradition of reports and
  records going back to contemporary knowledge; it is not a belief in the
  historical facts by an inference that passes through the links of such a chain.
  At most, that can very seldom be the case.]{La creencia en los registros de la
    historia consiste en general la creencia de que ha habido una cadena de
    tradición de informes y registros que van hacia el conocimiento contemporaneo;
    no es una creencia en hechos históricos por una inferencia que pasa por los
    eslabones de una cadena como esta. Como mucho, esto seria muy raramente el
    caso.}

  Ahora bien, como se ha dicho antes, el interés de Anscombe no esta simplemente
  en mostrar en qué se equivoca Hume, sino que considera que la cuestión toca el
  nervio de un problema con cierta profundidad:
  \blockquote[causality in hume 2855: The interesting problem that arises, then,
  is why the things we are told and the writings that we see are the starting
  points for our belief in the far distant events and so in the intermediate chain
  of record.]{El problema interesante que surge, entonces, es por qué las cosas
    que se nos dicen y los escritos que vemos son puntos de partida para nuestro
    creer en eventos distantes y así también en la cadena del relato intermedia.}
#+END_SRC
**** no es posible continuar infinitamente una cadena de inferencias
:TEXT:
’Tis impossible for us to carry on our inferences in infinitum; and the only thing,
that can stop them, is an impression of the memory or senses, beyond which there is no
room for doubt or enquiry.
:END:
+BEGIN_SRC latex
  El argumento de Hume, entonces, se compone de dos partes.
  En primer lugar, una cadena de inferencia en la cual "ya que p, q, etc..."
  en la que p da una causa creida (no percibida) y q un efecto inferido, no puede continuar
para siempre, sino que tiene que terminar n

  Determina que estas inferencias no pueden continuar infinitamente. Si se tratara
  de mera relación especulativa de conceptos no representaría dificultad, pero se
  trata de creer, y la cadena no podría ofrecer una creencia si no tiene término.
  \blockquote[{\cite[2762]{anscombe2011hoc}}: Now there really is no difficulty
  about going on ad infinitum, or at any rate about saying ‘and so on ad
  infinitum’, if the ‘inferring’ is simply deriving the idea of the effect from
  that of the cause. But the inferring is more than that ---it is believing. It is
  in connection with this that Hume is saying ‘this chain can’t go on for
  ever’.]{Ahora realmente no hay dificultad en ir infinitamente, o en cualquier
    caso decir `así sucesivamente infinitamente', si el `inferir' es simplemente
    derivar la idea del efecto partiendo de su causa. Pero el inferir es más que
    eso ---es creer. Es en conexión con esto que Hume dice `esta cadena no puede
    seguir para siempre'}

  First, a chain ‘Since p, q, etc’ in which p gives a believed-in (not perceived)
  cause and q an inferred effect, cannot go on for ever but must terminate in a
  proposition that is believed without inferring any consequences from it; and
  from this proposition we then work back in reverse order to p.

  This is a particular form of a familiar argument that not everything can be
  argued from something else, that is: that it cannot be the case that everything
  is argued from something else. I believe p because I believe q because I believe
  r because I believe s ---this cannot go on for ever; it must end in something
  which I believe, not because I believe something else. This argument appears to
  be correct.

#+END_SRC
**** el término de la cadena de inferencias no puede ser otra inferencia
+BEGIN_SRC latex
Hume’s second point is that not merely must the chain that he is concerned with
come to an end somewhere, but its terminus must be of a different kind from the
other members. ... without the authority either of the memory or the senses our
whole reasonings wou’d be chimerical and without foundation. Every link of the
chain wou’d in that case hang upon another; but there wou’d not be anything
fix’d to one end of it, capable of sustaining the whole; and consequently there
wou’d be no belief or evidence.[27]


The second part of his argument, which says that the terminus must be of a
different character from the links of the chain, is more doubtful than the first
part which only says there must be a terminus. Hume does not think that I have
to have a present perception (of memory or sense) in connection with my belief
that Caesar was killed in the Senate House: we can ‘reason upon our past
conclusions and principles, without having recourse to those impressions from
which they first arose.’ The convictions, however, must have been produced by
impressions, and ‘all reasonings concerning causes and effects are originally
deriv’d from some impression’.
#+END_SRC

**** hume's thesis falls into four parts
**** two comparisons: identity and proper names
#+BEGIN_SRC latex

#+END_SRC

*** Conclusion:perception of records>belief distant event>chain of record

*** Not just catching the mistake, but seeing what to say about this
The interesting problem that arises, then, is why the things we are told and the
writings that we see are the starting points for our belief in the far distant events
and so in the intermediate chain of record. This is a question of vast importance. But
the consideration of it would take us far away from that investigation of Hume on cause
which has been our present business. I take it as sufficiently demonstrated that Hume’s
account is wrong. (One may be convinced of that without thinking that one has an
alternative account.)
*** Wittgenstein: On Certainty


So it turns out when I say things like “Here is a hand” I’m not really making a claim
about the world, I’m laying down some rules for discussion. If you doubt there’s a hand
here, then fuck you and that’s all there is to it. We can’t really talk about anything
now, because we can’t even agree on something as simple as a goddamn hand. When we all
agree here is a hand, then we can go about discussing our world in meaningful ways.
Skepticism just undermines a foundation and replaces it with nothing; its paralyzing.
The grounds for such radical skepticism don’t exist; it presupposes and relies on the
very certainty it tries to undermine.

The hypothesis that Julius Caesar might turn out never to have existed can be rejected,
once the details of that hypothesis have been demanded.
#+BEGIN_SRC latex
  Para discutir esta cuestión Anscombe recurre a las reflexiones de Wittgenstein
  en \emph{On Certainty}. La motivación para estos ecritos de Wittgenstein son las
  propuestas de Moore en \emph{Proof of the External World} y \emph{Defence of
    Common Sense}. En estas obras sostiene que hay una serie de proposiciones que
  conocemos con seguridad, como \enquote{Aquí hay una mano, y aquí otra}, o
  \enquote{La tierra ha existido por largo tiempo antes de mi nacimiento} y
  \enquote{Nunca he estado lejos de la superficie de la tierra}. Estas reflexiones
  ocuparon a Wittgenstein durante los últimos años de su vida.\footnote{Cf.
    preface On certainty}

  Un tema que aparece en esta discusión de Wittgenstein es que la justificación
  semántica, relacionada con el uso correcto del lenguaje, y la justificación
  epistémica, relacionada como tal con el afirmar la verdad, están más unidas
  entre sí de lo que se piensa. Según esto:\blockquote[teichmann 213: Wittgenstein
  invites us to view the rules governing the correct use of words as comparable to
  the rules governing the acceptance or rejection of beliefs (which are themselves
  of course paradigmatically expressed in words); a ‘world view’ is determined as
  much by our language and its attendant conceptual scheme as by what we would
  ordinarily term our knowledge of things. The two aspects of world view, the two
  kinds of justification, come together in the phenomenon of certainty. ‘I am
  sure’, ‘I cannot doubt’ are related to ‘It must be’, which expression can be
  prefixed to any statement of conceptual truth. One direction in which these
  thoughts seem to take us is towards regarding certain world views, or sets of
  beliefs, or very general beliefs, as no more susceptible of rational
  justification or criticism than are concepts. –This is just how we go on’ looks
  to be the final answer to a series of –Why?’ questions; and a language–game or
  practice can appear to be sealed off from external assessment. An appeal to the
  objective measure of Reality is empty in this context; we can of course –cite
  reality’ when giving reasons in justification of a belief or practice, but that
  our reasons count as good reasons is determined by norms or rules of reasoning
  whose status as rules depends on the existence of a surrounding
  language–game.]{Wittgenstein nos invita a ver las reglas que gobiernan el uso
    correcto de las palabras como comparables con las reglas que gobiernan la
    aceptación o rechazo de las creencias (que desde luego son ellas mismas
    paradigmáticamente expresadas en palabras); una `cosmovisión' está determinada
    tanto por nuestro lenguaje y su esquema conceptual relacionado como por lo que
    ordinariamente expresamos como nuestro conocimiento de las cosas. Los dos
    aspectos de la cosmovisión, los dos tipos de justificación, quedan unidos en
    el fenómeno de la certeza. [\ldots] Una dirección hacia la que estos
    pensamientos parecen dirigirnos es a considerar ciertas cosmovisiones, o
    colecciones de creencias, o creencias generales, como no más susceptibles de
    justificación racional o crítica que la que tienen los conceptos}.

  Anscombe aplica las lecciones de \emph{On Certainty} al conocimiento histórico
  en la linéa propuesta por Hume: ``elegir cualquier punto en la historia, y
  considerar por qué razón lo creemos o rechazamos''. Elegir o rechazar una
  creencia como la propuesta implica la identificación de una justificación
  suficiente, y aquí esta busqueda esta regida por reglas comparables al correcto
  uso de las palabras. Los dos puntos principales destacados por Anscombe serán:
  \blockquote[grounds of belief 183: Hume's philosophical opinion was that these
  ultimate groundless grounds were sense impressions. But I say that they are such
  beliefs as those of which one will say `Everyone knows that!' or `Everyone who
  knows anything on such matters at all, knows that!']{La opinion filosófica de
    Hume era que estos fundamentos-sin-fundamento definitivos eran impresiones de
    los sentidos. Pero yo digo que son ese tipo de creencias de las cuales uno
    dice `¡Todo el mundo sabe eso!' o `¡Todo el que sabe algo de ese tema, sabe
    eso!'}. Junto a esto, es también parte de su argumento:
  \blockquote[teichmann 224: the mere statement that we can conceive of evidence
  turning up which showed there had never been such a person as Julius Caesar is
  no good until details are given of what sort of evidence that might be. If we
  try to do this, however, we are likely to fail.]{la declaración de que puede ser
    concebido que aparezca evidencia que mostrara que nunca ha habido una persona
    como Julio César no es suficiente hasta que se den detalles acerca del tipo de
    evidencia que ésta pudiera ser. Si intentamos hacer esto, sin embargo, lo más
    probable es que fracasemos.}

  Para entender su primera propuesta será útil recurrir a su explicación de este
  punto como está planteado en \emph{On Certainty}: \blockquote[QLI, 130: Finding
  grounds, testing, proving, reasoning, confirming, verifying are all processes
  that go on within, say, one or another living linguistic practice which we have.
  There are assumptions, beliefs, that are ‘immovable foundations’ of these
  proceedings. By this, Wittgenstein means only that they are a foundation which
  is not moved by any of these proceedings.]{Encontrar fundamentos, examinar,
    probar, razonar, confirmar, verificar son todos procesos que corresponden,
    diríamos, dentro de una u otra práctica linguística viva de las que tenemos.
    Hay supuestos, creencias, que son `fundamentos inmovibles' de estos modos de
    proceder. Con esto, Wittgenstein se refiere solamente a que son un fundamento
    que no es modificado por esos procesos.} En estos procesos o actividades hay
  proposiciones que sirven como bisagras, donde se apoya el movimiento del
  discurrir. Como tal, son creencias que si se ponen en duda impiden el progreso
  del razonamiento. Estas creencias son esas que forman parte del conocimiento
  común. En ese sentido, afirmar \enquote{aquí está mi mano} no es sostener algo
  sobre el estado de las cosas en el mundo, sino establecer unas reglas para la
  discusión. Por otra parte, poner en duda que tengo mi mano aquí delante
  supondría tratar con escepticismo un conocimiento común de tal manera que se
  podría decir \enquote{si esto es dudoso, ¿qué puede ser cierto?}, entonces
  ¿desde qué fundamento podríamos sostener una discusión o razonamiento sobre el
  mundo en el que \enquote{aquí está mi mano} no es cierto?

  Esto mismo ocurre con la creencia en el conocimiento común de la existencia de
  Julio César, si nos planteamos la hipótesis de que nunca existió, nos
  situaríamos entre dos alternativas, ya sea \blockquote[HJC 91: \textelp{} say:
  ``How could one explain all these references and implications, then?\ldots but,
  but, \emph{but} if I doubt the existence of Caesar, if I say I may reasonably
  call it in question, then with equal reason I must doubt the status of the
  things I've just pointed to'']{\textelp{} decir ``¿Cómo se explican todas estas
    referencias e implicaciones entonces?\ldots pero, pero \emph{pero} si dudo de
    la existencia de César, si digo que podría razonablemente ponerlo en tela de
    juicio, entonces, con la misma razonabilidad tengo que dudar de la validez de
    las cosas que acabo de señalar''}. O por otra parte: \blockquote[HJC91:
  \textelp{} I should realize straight away that the `doubt' put me in a vacuum in
  which I could not produce reasons why such and such `historical facts' are more
  or less doubtful.]{\textelp{} podría caer en cuenta inmediatamente de que la
    `duda' me ha encerrado en un vacío en el cual no podría producir razones por
    las cuales estos u otros `datos históricos' son más o menos dudosos.}

  Hume escoge este punto histórico porque es un conocimiento presente en su
  cultura con un grado particular de certeza. Podría haber sometido a prueba algun
  detalle del suceso y cuestionar, por ejemplo, si podría dudarse la fecha o el
  lugar del asesinato, sin embargo, el que ese hombre, César, existió, y su vida
  terminó en un asesinato: esto solo podría cuestionarlo empleando la duda
  Cartseiana.

  Elizabeth alude a la analogía hecha por Otto Neurath en \emph{Anti-Spengler},
  donde compara el conocimiento científico con un barco en el cual los que
  investgan son como marinos que reconstruyen el barco en altamar, verificando y
  reemplazando sus piezas mientras que se navega. Entonces propone que si la
  ilustración implica que se puede ir examinando cada pieza y reemplazarla de tal
  modo que se termina con un barco distinto, la analogía no sirve: \blockquote[HJC
  92: For there are things that are on a level. A general epistemological reason
  for doubting one will be a reason for doubting all, and then none of them would
  have anything to test it by.]{Pues hay cosas que están sobre superficie. Una
    razón espistemológica general para dudar de una será razón para dudar de
    todas, y entonces ninguna tendría cosa alguna que sirviera para evaluarla.}


  What would one REALLY have grounds for saying or thinking, in such a case?’ In
  many of her articles, Anscombe refers to some view as a prejudice, or apparent
  prejudice. When is a belief a prejudice, and when is it bedrock? When is it a
  questionable ‘bit of Weltanschauung’, and when a ‘hinge proposition’? The answer
  to these questions must in large part have to do with how much, and what sort
  of, detail can be plausibly put into counter-examples to, or cases against, the
  belief in question.

  My knowledge of the things among which and the places in which I live is not so
  much 'theory laden' as ‘common-knowledge laden'. I wish to say: it is a
  falsification here to speak of testimony: to say, for example, that it is by
  testimony that I know I was born. There is something else, not testimony, though
  acquired by education from human beings, which is, so to speak, thicker than
  testimony.

  The work done, people could be taught what England was (no doubt still disputing
  some regions). Now those who learned thereafter can hardly be said to have
  knowledge by testimony. They were taught to call something 'England’—something
  indeed which could in large part only be defined for them by hearsay; and they
  so taught those who came after them. I am an heir of this tradition. Now, I know
  I live in England. But by testimony? Some would say so. But there is something
  queer about it. What do I know? That the world is divided up into countries
  which have names, and that the one I live in is called England and is here on
  the map of the globe. This involves understanding the use of the globe to
  represent the earth. It is rather as if I had been taught to join in doing
  something, than to believe something—but because everyone is taught to do such
  things, an object of belief is generated. The belief is so certainly correct
  (for it follows the practice) that it is knowledge; for here knowledge is no
  other than certainly correct belief in pursuit of a practice. But the connection
  with testimony is remote and indirect.

#+END_SRC
