#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico/faith.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* TODO Faith (1975) [0%]
** /Quaestio/: Understand faith without it
:STATEMENT:
"I want to say what might be understood about faith by someone who did not have
it"
:END:
:DISCARDED:
+Qué significa conocer a Dios?+ +Fe=creer a X que P > Fe
divina es creer a Dios que P > creer a Dios que P es poder escucharlo decir que
P. Qué es escuchar a Dios?+
:END:
:DESCRIPTION:
Se plantea la cuestión: decir de la fe lo que puede ser entendido por quien no
la tiene. Esto supone describir aquello de la fe que es razonable. Anscombe usa
la expresión creer con objeto personal para describir de manera razonable la fe.
Además usará la noción de presupuestos de la fe, en lugar de hablar de
preámbulos.
:END:
#+BEGIN_SRC latex
  \subsection{Que se puede entender de la fe sin tenerla}
  En Oscott College, el seminario de la Archidiócesis de Birmingham, se comenzaron
  a celebrar las conferencias llamadas Wiseman Lectures en 1971. Para estas
  lecciones ofrecidas anualmente en memoria de Nicholas Wiseman se invitaba un
  ponente que tratara algún tema relacionado con la filosofía de la religión o
  alguna materia en torno al ecumenismo.\footcite[Cf.~][7]{wisemanlects}

  El 27 de octubre de 1975, para la quinta edición de las conferencias, Anscombe
  presentó una lección titulada simplemente \emph{Faith}. Allí planteaba la
  siguiente cuestión: \citalitlar{Quiero decir qué puede ser entendido sobre la fe
    por alguien que no la tenga; alguien, incluso, que no necesariamente crea que
    Dios existe, pero que sea capaz de pensar cuidadosa y honestamente sobre ella.
    Bertrand Russell llamó a la fe `certeza sin prueba'. Esto parece correcto.
    Ambrose Bierce tiene una definición en su \emph{Devil's Dictionary}: `La
    actitud de la mente de uno que cree sin evidencia a uno que habla sin
    conocimiento cosas sin parangón'. ¿Qué deberíamos pensar de
    esto?\footnote{\cite[115]{anscombe2008faith:faith}: <<I want to say what might
      be understood about faith by someone who did not have it; someone, even, who
      does not necessarily believe that God exists, but who is able to think
      carefully and truthfully about it. Bertrand Russell called faith `certainty
      without proof'. That seems correct. Ambrose Bierce has a definition in his
      Devil's Dictionary: `The attitude of mind of one who believes without
      evidence one who tells without knowledge things without parallel.' What
      should we think of this?>>}}
#+END_SRC


** /Expositio/: Presuppositions of faith
:STATEMENT:
"The right designation for what are called the 'preambles' of faith is not that
but at least for part of them, 'presuppositions'. According to faith itself
faith is believing God. If the presuppositions are true, it is, then believing
on the best possible grounds."
:END:

*** ¿Descripción de `Fe'?
#+BEGIN_SRC latex
  \subsection{Descripción de `Fe'}
  El objetivo de Elizabeth sitúa su investigación en un contexto específico.
  Pretende describir el fenómeno de la fe como uno que tiene un carácter de
  razonabilidad tal que se puede \citalitinterlin{pensar cuidadosa y
    honstamente}\footnote{\cite[115]{anscombe2008faith:faith}:<<think carefully
    and truthfully>>}. Su estrategia, carácterística del tipo de análisis empleado
  por Wittgenstein, se muestra aquí de nuevo como una descripción de usos
  familiares de la palabra siendo analizada que son articulados de tal manera que
  los patrones de estos usos sean
  estudiables\autocite[Cf.~][12]{bakerhacker2009understanding}. Se enfoca en un
  modo antiguo de usar la palabra `fe' en el que se le empleaba para decir `creer
  a alguien que $p$'. `Fe humana' era creer a una persona humana, `fe divina' era
  creer a Dios\autocite[Cf.~][2]{anscombe2008faith:tobelieve}. Así por ejemplo:
  <<Abrám creyó a Dios (\textgreek{ἐπίστευσεν τῷ Θεῷ}) y ésto se le contó como
  justicia>>\footnote{Gn~15,6}. De tal modo que es llamado 'padre de la
  fe'.\footnote{Cf.~Rm~4~y~Ga 3,7}. Este enfoque hace que la pregunta `¿qué es
  creer a alguien?' quede situada en el centro del
  análisis\autocite[Cf.~][14]{anscombe2008faith:faith}, y aquí también Anscombe
  dedica su atención a las presuposiciones implicadas en esta creencia.

  Pueden ser destacados tres movimientos principales en el análisis realizado por
  Elizabeth en esta investigación. Primero establece una relación entre las
  presuposiciones implicadas en el creer y lo que se ha llamado los preámbulos de
  la fe. En segundo lugar describe lo relacionado a las presuposiciones implicadas
  en creer a una persona humana cuando ésta comunica algo. En tercer lugar examina
  el fenómeno particular de creer cuando la comunicación viene de Dios.
#+END_SRC

**** Presuposiciones y preámbulos
#+BEGIN_SRC latex
  \subsubsection{Las presuposiciones del creer como descripción de la
    razonabilidad de la fe}
  A lo largo de la investigación, Anscombe recurrirá a una descripción de las
  presuposiciones implicadas en el creer como una descripción razonable de la fe.
  Su apoyo para seguir esta ruta de análisis es el recuerdo de cierta discusión,
  de cierta apologética\autocite[Cf.~][13]{anscombe2008faith:faith}. Trae a la
  memoria que: \citalitlar{Hubo en una época pasada un profuso entusiasmo por la
    racionalidad, quizás inspirado por la enseñanza del Vaticano~I contra el
    fideísmo, ciertamente sostenidos por la promoción de estudios neo-tomístas
    [\ldots] la noticia era que la fe Cristiana Católica era \emph{racional}, y el
    problema, para aquellos capaces de sentirlo como tal, era cómo era
    \emph{gratuita} \footnote{\cite[11]{anscombe2008faith:faith}: <<There was in a
      preceding time a professed enthusiasm for rationality, perhaps inspired by
      the teaching of Vatican I against fideism, certainly carried along by the
      promotion of neo-thomist studies [\ldots] the word was that the Catholic
      Christian faith was \emph{rational}, and a problem, to those able to feel it
      as a problem, was how it was \emph{gratuitous}>>}.}

  Distintas variantes de esta enseñanza ---destaca Anscombe--- ofrecían distintas
  argumentaciones, algunas más sobrias que otras, que servían como procesos de
  razonamientos que ofrecían una cierta demostración de la verdad de las
  enseñanzas de la Iglesia\autocite[Cf.~][12]{anscombe2008faith:faith}.
#+END_SRC
**** Las presuposiciones de creer a una persona humana
#+BEGIN_SRC latex
\subsubsection{Las presuposiciones implicadas en creer a alguien}
#+END_SRC
**** El extraordinario fenómeno de creer a Dios
#+BEGIN_SRC latex
\subsubsection{`Creer' cuando la comunicación viene de Dios}
#+END_SRC
