#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico/lang_and_myst.tex
#---------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros
La cuestión planteada en FR

es la cuestión de la analgía
dentro de la filo de Witt es una consideración mística

en la filisofía de Anscombe este análisis atraviesa los artículos recogidos en FPW

de toda esa discusión tendremos en cuenta el primero y el último, donde además se encuentran nociones relacionadas con el misterio.



67. La teología fundamental, por su carácter propio de disciplina que tiene la misión de dar razón de la fe (cf. 1 Pe 3, 15), debe encargarse de justificar y explicitar la relación entre la fe y la reflexión filosófica. Ya el Concilio Vaticano I, recordando la enseñanza paulina (cf. Rm 1, 19-20), había llamado la atención sobre el hecho de que existen verdades cognoscibles naturalmente y, por consiguiente, filosóficamente. Su conocimiento constituye un presupuesto necesario para acoger la revelación de Dios. Al estudiar la Revelación y su credibilidad, junto con el correspondiente acto de fe, la teología fundamental debe mostrar cómo, a la luz de lo conocido por la fe, emergen algunas verdades que la razón ya posee en su camino autónomo de búsqueda. La Revelación les da pleno sentido, orientándolas hacia la riqueza del misterio revelado, en el cual encuentran su fin último. Piénsese, por ejemplo, en el conocimiento natural de Dios, en la posibilidad de discernir la revelación divina de otros fenómenos, en el reconocimiento de su credibilidad, en la aptitud del lenguaje humano para hablar de forma significativa y verdadera incluso de lo que supera toda experiencia humana. La razón es llevada por todas estas verdades a reconocer la existencia de una vía realmente propedéutica a la fe, que puede desembocar en la acogida de la Revelación, sin menoscabar en nada sus propios principios y su autonomía.

83. Las dos exigencias mencionadas conllevan una tercera: es necesaria una filosofía de alcance auténticamente metafísico, capaz de trascender los datos empíricos para llegar, en su búsqueda de la verdad, a algo absoluto, último y fundamental. Esta es una exigencia implícita tanto en el conocimiento de tipo sapiencial como en el de tipo analítico; concretamente, es una exigencia propia del conocimiento del bien moral cuyo fundamento último es el sumo Bien, Dios mismo. No quiero hablar aquí de la metafísica como si fuera una escuela específica o una corriente histórica particular. Sólo deseo afirmar que la realidad y la verdad transcienden lo fáctico y lo empírico, y reivindicar la capacidad que el hombre tiene de conocer esta dimensión trascendente y metafísica de manera verdadera y cierta, aunque imperfecta y analógica. En este sentido, la metafísica no se ha de considerar como alternativa a la antropología, ya que la metafísica permite precisamente dar un fundamento al concepto de dignidad de la persona por su condición espiritual. La persona, en particular, es el ámbito privilegiado para el encuentro con el ser y, por tanto, con la reflexión metafísica.

Dondequiera que el hombre descubra una referencia a lo absoluto y a lo trascendente, se le abre un resquicio de la dimensión metafísica de la realidad: en la verdad, en la belleza, en los valores morales, en las demás personas, en el ser mismo y en Dios. Un gran reto que tenemos al final de este milenio es el de saber realizar el paso, tan necesario como urgente, del fenómeno al fundamento. No es posible detenerse en la sola experiencia; incluso cuando ésta expresa y pone de manifiesto la interioridad del hombre y su espiritualidad, es necesario que la reflexión especulativa llegue hasta su naturaleza espiritual y el fundamento en que se apoya. Por lo cual, un pensamiento filosófico que rechazase cualquier apertura metafísica sería radicalmente inadecuado para desempeñar un papel de mediación en la comprensión de la Revelación.

La palabra de Dios se refiere continuamente a lo que supera la experiencia e incluso el pensamiento del hombre; pero este « misterio » no podría ser revelado, ni la teología podría hacerlo inteligible de modo alguno, 102 si el conocimiento humano estuviera rigurosamente limitado al mundo de la experiencia sensible. Por lo cual, la metafísica es una mediación privilegiada en la búsqueda teológica. Una teología sin un horizonte metafísico no conseguiría ir más allá del análisis de la experiencia religiosa y no permitiría al intellectus fidei expresar con coherencia el valor universal y trascendente de la verdad revelada.

Si insisto tanto en el elemento metafísico es porque estoy convencido de que es el camino obligado para superar la situación de crisis que afecta hoy a grandes sectores de la filosofía y para corregir así algunos comportamientos erróneos difundidos en nuestra sociedad.

84. La importancia de la instancia metafísica se hace aún más evidente si se considera el desarrollo que hoy tienen las ciencias hermenéuticas y los diversos análisis del lenguaje. Los resultados a los que llegan estos estudios pueden ser muy útiles para la comprensión de la fe, ya que ponen de manifiesto la estructura de nuestro modo de pensar y de hablar y el sentido contenido en el lenguaje. Sin embargo, hay estudiosos de estas ciencias que en sus investigaciones tienden a detenerse en el modo cómo se comprende y se expresa la realidad, sin verificar las posibilidades que tiene la razón para descubrir su esencia. ¿Cómo no descubrir en dicha actitud una prueba de la crisis de confianza, que atraviesa nuestro tiempo, sobre la capacidad de la razón? Además, cuando en algunas afirmaciones apriorísticas estas tesis tienden a ofuscar los contenidos de la fe o negar su validez universal, no sólo humillan la razón, sino que se descalifican a sí mismas. En efecto, la fe presupone con claridad que el lenguaje humano es capaz de expresar de manera universal —aunque en términos analógicos, pero no por ello menos significativos— la realidad divina y trascendente. 103 Si no fuera así, la palabra de Dios, que es siempre palabra divina en lenguaje humano, no sería capaz de expresar nada sobre Dios. La interpretación de esta Palabra no puede llevarnos de interpretación en interpretación, sin llegar nunca a descubrir una afirmación simplemente verdadera; de otro modo no habría revelación de Dios, sino solamente la expresión de conceptos humanos sobre Él y sobre lo que presumiblemente piensa de nosotros.


dominguez 357
Cabría decir que ésta es una consideración \emph{mística}. Con místico me refiero, en principio al uso wittgensteniano: ``Nicht wie die Welt ist, ist das Mystische, sondern daß sie ist''. En efecto, a la actitud mística pertenece la persuasión de que la verdad es un tema vital que trasciende, la certeza de que ante ella el ejercicio racional culmina en contemplación. Es, de nuevo, un momento en el que la racionalidad filosófica se pone en busca de otro nivel que la supera: la Revelación. Esta dimensión mistica no está lejos de la metafísica, ni de la ética. 

\footnote{\cite[Cf.][156]{monk1991duty}: \enquote{The famous last sentence of the book ---`Whereof one cannot speak, thereof one must be silent'--- expresses both a logico-philosophical truth and an ethical precept.}; Wittgenstein explicó esta finalidad ética de su obra en una carta a Ludwig von Ficker de este modo: \cite[22-23]{monk2005howto}: \enquote{the point of the book is ethical. I once wanted to give a few words in the foreword which now are actually not in it, which, however, I'll write to you now because they might be a key for you: I wanted to write that my work consists on two parts: of the one which is here, and of everything which I have \emph{not} written. And precisely this second part is the important one. For the Ethical is delimited from within, as it were, by my book; and I'm convinced that, \emph{strictly} speaking, it can ONLY be delimited in this way. In brief, I think: All of that whcih \emph{many} are \emph{babbling} today, I have defined in my book by remaning silent about it}.}.

En consecuencia, la actitud previa que se ha de mantener ante la verdad es, no cabe duda, martirial; sí, testimonial en el sentido cabal de la palabra.

dominguez 357
la primera de las actitudes, la que hemos visto ubicada, \emph{grosso modo}, en la época medieval, considera que la verdad existe con independencia del hombre que la pueda conocer. Es, por así decir, anterior a él. La segunda, tiende a identificar al hombre con la verdad misma. La tercera de las actitudes, en el fondo, niega la existencia de la verdad.

dominguez 355
En la época medieval, \emph{grosso modo}, la verdad era \emph{testimoniada}. Es decir, el intelectual, el amante de la verdad, el hombre corriente, era consciente de ser "testigo" de una verdad que le excedía, y que le había sido dada. Esta actitud no era vivida, en modo alguno, como una alienación, sino como una gozosa experiencia de la creaturalidad en la cual se vivía. Era un hecho filosóficamente aceptado que la razón no bastaba a la razón.

Conesa 310-311
Las observaciones de L. Wittgenstein a este respecto subrayan la importancia que tiene en el contexto de la fe el aprendizaje del lenguaje. No se trata, sin embargo, de aprender un lenguaje esotérico y distanciado del lenguaje ordinario. Se trata de <<aprender cómo usar el lenguaje con más amplitud. El lenguaje que usa la religión es el mismo que se usa en otros universos de discurso. No es un lenguaje especial sino el mismo lenguaje ordinario al que se da un uso particular>>.

Este lenguaje es aprendido de la Iglesia. Una de las tareas del proceso catequético es precisamente la enseñanza del lenguaje de la fe. La profesora Anscombe subraya esto en un escrito sobre la transubstanciación

311
El fin de este aprendizaje es ---como subraya el texto--- introducirnos en la inteligencia y vida de la fe. /emph{Saber usar} el lenguaje de la fe es una habilidad técnica que ayuda a la fe en su desarrollo y a la vez ayuda a introducirnos en ella.

La fe necesita un lenguaje ya que sólo puede referirse a su objeto mediante símbolos. Por ello el lenguaje no es sólo un modo de comunicación de la fe sino, sobre todo, algo necesario para estructurarse, definirse, identificarse.

259
La consideración de la fe como aceptación del testimonio de Dios puede también ser vista desde otra perspectiva similar: el motivo de la fe es Dios en cuanto Verdad Primera. Al creer, el hombre se apoya en la infalibilidad divina como garantía suprema de verdad. Este aspecto aparece especialmente en la expresión \emph{creer a Dios}. Al creer a Dios, el hombre se apoya en la veracidad divina y por lo mismo se confía al Dios de la verdad.


#+BEGIN_SRC latex
\subsection{Intro}

A lo largo de este trabajo hay una línea de investigación que se ha ido desarrollando y que desemboca en una región de la obra de Anscombe que trata sobre una cuestión filosófica compleja. Ha partido desde la propuesta de repensar el nexo entre razón, afectos y libertad con una visión más amplia; y la consideración de que en el contexto de la filosofía analítica este nexo se estudia dentro de la actividad humana del lenguaje (\S\ref{subsec:amplia}, p.~\pageref{subsec:amplia}). Desde la perspectiva de la investigación teológica esta misma cuestión está relacionada con la pregunta sobre la capacidad del lenguaje para hablar de forma significativa incluso de lo que supera la experiencia humana (\S\ref{subsec:aptitud}, p.~\pageref{subsec:aptitud}). Además indagamos sobre este tema al exponer los desafíos planteados por el Círculo de Viena que desde ciertas interpretaciones de nociones wittgensteinianas realizaron una crítica de la capacidad del lenguaje religioso para comunicar conocimiento (\S\ref{subsec:viena}, p.~\pageref{subsec:viena}). Adentrándonos más al ámbito de la filosofía de Wittgenstein, F. Kerr nos proponía que su análisis de la relación entre realidad, pensamiento y lenguaje constituye un intento de reconocer cómo es el ser humano y junto a esto que la investigación teológica puede ser entendida como investigación gramatical (\S\ref{subsec:comosomos}, p.~\pageref{subsec:comosomos}). Estas ideas culminan finalmente en este apartado con la consideración de que para comprender la categoría de testimonio en la obra de Anscombe es preciso tener en cuenta su discusión sobre la capacidad del lenguaje para significar. Específicamente, su comprensión de la capacidad de la práctica lingüísica humana para comunicar la verdad en tanto que trascendental. 

Para explicar mejor cómo ambos temas se relacionan en la filosofía de Anscombe podemos recurrir a una propuesta de F. Conesa en su estudio sobre el valor cognoscitivo de la fe. Plantea que para Wittgenstein un elemento importante en la religión es el aprendizaje de un lenguaje, entonces propone: \blockquote[{\Cite[310-311]{conesa1994cc}}]{Las observaciones de L. Wittgenstein a este respecto subrayan la importancia que tiene en el contexto de la fe el aprendizaje del lenguaje. No se trata, sin embargo, de aprender un lenguaje esotérico y distanciado del lenguaje ordinario. Se trata de <<aprender cómo usar el lenguaje con más amplitud. El lenguaje que usa la religión es el mismo que se usa en otros universos de discurso. No es un lenguaje especial sino el mismo lenguaje ordinario al que se da un uso particular>>.

Este lenguaje es aprendido de la Iglesia. Una de las tareas del proceso catequético es precisamente la enseñanza del lenguaje de la fe. La profesora Anscombe subraya esto en \textelp{su} escrito sobre la transubstanciación
  \textelp{} El fin de este aprendizaje es ---como subraya el texto--- introducirnos en la inteligencia y vida de la fe. \emph{Saber usar} el lenguaje de la fe es una habilidad técnica que ayuda a la fe en su desarrollo y a la vez ayuda a introducirnos en ella.}

Aquí se encuentra un presupuesto importante tanto de nuestra comprensión de la fe, como de la noción que tiene Elizabeth del lenguaje: \blockquote[][\,(FR 84)]{la fe presupone con claridad que el lenguaje humano es capaz de expresar de manera universal ---aunque en términos analógicos, pero no por ello menos significativos--- la realidad divina y trascendente. Si no fuera así, la palabra de Dios, que es siempre palabra divina en lenguaje humano, no sería capaz de expresar nada sobre Dios}. Nos encontramos aquí ante una convergencia donde la revelación entendida como testimonio divino, la fe como confianza en su palabra y la práctica linguística como actividad donde la verdad se comunica componen facetas de una misma realidad.\footnote{F. Conesa argumenta en \Cite[259]{conesa1994cc}: \enquote{La consideración de la fe como aceptación del testimonio de Dios puede también ser vista desde otra perspectiva similar: el motivo de la fe es Dios en cuanto Verdad Primera. Al creer, el hombre se apoya en la infalibilidad divina como garantía suprema de verdad. Este aspecto aparece especialmente en la expresión \emph{creer a Dios}. Al creer a Dios, el hombre se apoya en la veracidad divina y por lo mismo se confía al Dios de la verdad.}, también añade: \enquote{B. Duroux demuestra que Santo Tomás se está refiriendo a la misma realidad cuando habla de la autoridad de Dios, el testimonio divino y la \emph{Verdad primera}. Se trata simplemente de cambios de acento.}}

El espíritu con el que Elizabeth Anscombe entiende y estudia este tema lo hereda del \emph{Tractatus}, donde la cuestión sobre la capacidad del lenguaje para significar culmina como preocupación ética\footnote{\cite[Cf.][156]{monk1991duty}: \enquote{The famous last sentence of the book ---`Whereof one cannot speak, thereof one must be silent'--- expresses both a logico-philosophical truth and an ethical precept.}; Wittgenstein explicó esta finalidad ética de su obra en una carta a Ludwig von Ficker de este modo: \cite[22-23]{monk2005howto}: \enquote{the point of the book is ethical. I once wanted to give a few words in the foreword which now are actually not in it, which, however, I'll write to you now because they might be a key for you: I wanted to write that my work consists on two parts: of the one which is here, and of everything which I have \emph{not} written. And precisely this second part is the important one. For the Ethical is delimited from within, as it were, by my book; and I'm convinced that, \emph{strictly} speaking, it can ONLY be delimited in this way. In brief, I think: All of that whcih \emph{many} are \emph{babbling} today, I have defined in my book by remaning silent about it}.} y consideración mística\footnote{\Cite[357]{dominguez2009at}: \enquote{Cabría decir que ésta es una consideración \emph{mística}. Con místico me refiero, en principio, al uso wittgensteniano: ``Nicht wie die Welt ist, ist das Mystische, sondern daß sie ist''.}}. Lo que esto quiere decir es que para ella, como para el \emph{Tractatus}, el interés consiste en argumentar una actitud o predisposición existencial ante la verdad\footnote{\Cite[Cf.][354-355]{dominguez2009at}}, más que una definición. Para el \emph{Tractatus} esto constituye una cuestión ética, puesto que pretende trazar el límite de lo que puede ser dicho. Desde el contexto de nuestro estudio, y la obra de Anscombe, hay un aspecto adicional a esta cuestión ética que puede ser expresada diciendo: \blockquote[{\Cite[354]{dominguez2009at}}]{Dada la inseparabilidad de la verdad y la libertad \textelp{} Es pertinente ahora, pues, mostrar qué actitudes \textins{hacia la verdad} no hacen justicia a la noción de libertad en el hombre que se sigue de su ser \emph{imago Dei}, y cuál sí}. En cuanto al aspecto `místico' de esta cuestión, desde la perspectiva del \emph{Tractatus}, este consiste en la noción de que en el lenguaje se muestra una verdad que es inefable, que no se puede decir con el lenguaje. Para nosotros y para Anscombe consiste en la conciencia de que en la actividad humana del lenguaje actuamos como testigos de la verdad que nos excede\footnote{\Cite[Cf.][354-355]{dominguez2009at}: \enquote{En la época medieval, \emph{grosso modo}, la verdad era \emph{testimoniada}. Es decir, el intelectual, el amante de la verdad, el hombre corriente, era consciente de ser "testigo" de una verdad que le excedía, y que le había sido dada. Esta actitud no era vivida, en modo alguno, como una alienación, sino como una gozosa experiencia de la creaturalidad en la cual se vivía. Era un hecho filosóficamente aceptado que la razón no bastaba a la razón.}}. En este sentido, una buena manera de caracterizar la actitud `mística' que Anscombe adopta ante la verdad en tanto que trascendental puede ser puesta en estos términos: \blockquote[{\Cite[357]{dominguez2009at}}]{En efecto, a la actitud mística pertenece la persuasión de que la verdad es un tema vital que trasciende, la certeza de que ante ella el ejercicio racional culmina en contemplación. Es, de nuevo, un momento en el que la racionalidad filosófica se pone en busca de otro nivel que la supera: la Revelación. Esta dimensión mistica no está lejos de la metafísica, ni de la ética. \textelp{} En consecuencia, la actitud previa que se ha de mantener ante la verdad es, no cabe duda, martirial; sí, testimonial en el sentido cabal de la palabra.}

En efecto Anscombe mantiene a lo largo de su obra esta actitud inspirada por el \emph{Tractatus}, esa \enquote*{persuasión de que la verdad es un tema vital que trasciende}. Sin embargo va más allá, pues no sostiene ---como lo hace el \emph{Tractatus}--- que el aspecto trascendente de la verdad no se revela \emph{en} el mundo. En este sentido es importante su giro hacia las nociones de la obra posterior de Wittgenstein, específicamente en \emph{Investigaciones Filosóficas} y \emph{Sobre la Certeza} donde el análisis del lenguaje no está orientado hacia la forma lógica pura como conexión metafísica entre pensamiento y realidad, sino a la actividad humana donde esta conexión se encuentra viva. Para Elizabeth, la verdad, siendo trascendental, se revela en el lenguaje y en la acción humana como rectitud\footnote{Para una discusión más ámplia véase: \Cite{torralbaynubiola2005fayeh:unidadverdad}. En nuestro estudio este tema se discute en: \S\ref{subsec:verdad}, p.~\pageref{subsec:verdad}.}.

Dentro de la obra de Elizabeth esta cuestión se encuentra desarrollada en el primer volumen de su colección publicada en 1981, el cual tituló \emph{From Parmenides to Wittgenstein}. El volumen reúne a autores como Parménides, Platón, Hume y Wittgenstein y constituye un recorrido realizado a través de varios artículos donde Anscombe analiza aportaciones filosóficas en torno a la relación entre lo concebible y lo posible\footnote{\cite[Cf.][193]{teichmann2008ans}: \enquote{Philosophers have grappled since ancient times with the problem of how thinkability and possibility are related, and it is characteristic of Anscombe to have drawn such diverse figures as Parmenides, Plato, Hume, and Wittgenstein into a single discussion}.}. Elizabeth propone que las reflexiones que realiza en los artículos recogidos en el volumen componen el estudio de una discusión que se ha desarrollado en la obra de muchos autores filosóficos. ¿En qué consiste esta discusión que Anscombe juzga presente ya en Parménides y viva todavía en Wittgenstein? En la introducción de la colección la describe diciendo: 
\blockquote[{\Cite[xi]{anscombe1981parmenides}}: \enquote{At the present day we are often perplexed with enquiries about what makes true, or what something's being thus or so \emph{consists in}; and the answer to this is thought to be an explanation of meaning. If there is no external answer, we are apparently committed to a kind of idealism}.]{En la época actual con frecuencia nos quedamos perplejos con preguntas sobre qué hace a algo verdadero, o \emph{en qué consiste} el que algo sea de un modo u otro; y la respuesta a esto se piensa que es una explicación del significado. Si no hay una respuesta externa, aparentemente estamos comprometidos con un tipo de idealismo}.\label{subsec:intextq}

Como dijimos al principio de este apartado esta es una discusión compleja. Sin embargo hay un elemento que sirve El primer artículo: \emph{Parmenides, Mystery and Contradiction}, es el texto de una ponencia ofrecida por Anscombe en la reunión del \emph{Aristotelian Society} en Londres el 24 de febrero de 1969. En esta discusión Elizabeth estudia la manera en que Parménides construye su argumento acerca de lo posible y lo concebible y qué oportunidades ofrece para un análisis de esta relación.

#+END_SRC
  En el contexto de la filosofía de Wittgenstein cuestión ética

  a nosotros nos parece además que se trata de 

  354 mostrar qué actitudes no hacen justicia a la noción de libertad en el hombre que se sigue de su ser \emph{imago Dei}, y cuál sí.

  puesto que 354 Dada la inseparabilidad de la verdad y la libertad, la analogía de la libertad es inseparable de la analogía de la verdad.

  Hay otro aspecto import
  Ya en el \emph{Tractatus} la cuestión de la capacidad del lenguaje para significar y la naturaleza de la verdad aparecen en definitiva como una ``consideración mística''\footnote{Estimamos de gran interés la reflexión de P. Dominguez donde, desde el paradigma antropológico de la analogía teológica, propone que la actitud martirial es la respuesta a esta `consideración mística'; \Cite[357]{dominguez2009at}: \enquote{Cabría decir que ésta es una consideración \emph{mística}. Con místico me refiero, en principio al uso wittgensteniano: ``Nicht wie die Welt ist, ist das Mystische, sondern daß sie ist''. En efecto, a la actitud mística pertenece la persuasión de que la verdad es un tema vital que trasciende, la certeza de que ante ella el ejercicio racional culmina en contemplación. Es, de nuevo, un momento en el que la racionalidad filosófica se pone en busca de otro nivel que la supera: la Revelación. Esta dimensión mistica no está lejos de la metafísica, ni de la ética. \textelp{} En consecuencia, la actitud previa que se ha de mantener ante la verdad es, no cabe duda, martirial; sí, testimonial en el sentido cabal de la palabra.}  Sobre esta actitud ante la verdad, véase también: \Cite[354-356]{dominguez2009at}.} que se interesa, más que en una definición de la verdad, en lograr una actitud hacia ella. Esto confiere al \emph{Tractatus} un sentido ético.


Recap:

cap 1, p.5 y 6: es imprescindible repensar el nexo ... razón, afectos y libertad en la relación del hombre con lo real:: este nexo en el lenguaje
mostrar la credibilidad de la fe como asentimiento a una revelación personal en la historia

c. 1 p. 9  aptitud del lenguaje para hablar de forma significativa....

c.1 sec 1.3 p 19 ¿es cognoscitivo el lenguaje relijioso? puede significar? puede comunicar conocimiento?

c2. p. 37 el análisis de ludwig sobre la relación entre la realidad, el lenguaje y el pensamiento no deja de ser un intento de reconocer definitivamente como somos realmente 

c2 p. 38 teología como gramática: de lo que decimos sobre Dios

c. 3 p. 42 dos líneas: descripción de lo que constituye lenguaje significativo y descripción de la naturaleza especial de la creencia que llamamos `fe'

Al comienzo de nuestra investigación, como al comienzo de este capítulo

Podemos tomar de F. Conesa algunas claves para comprender la relación del tema del testimonio y la comprensión del lenguaje dentro de la filosofía analítica.

Conesa 310-311
Las observaciones de L. Wittgenstein a este respecto subrayan la importancia que tiene en el contexto de la fe el aprendizaje del lenguaje. No se trata, sin embargo, de aprender un lenguaje esotérico y distanciado del lenguaje ordinario. Se trata de <<aprender cómo usar el lenguaje con más amplitud. El lenguaje que usa la religión es el mismo que se usa en otros universos de discurso. No es un lenguaje especial sino el mismo lenguaje ordinario al que se da un uso particular>>.

Este lenguaje es aprendido de la Iglesia. Una de las tareas del proceso catequético es precisamente la enseñanza del lenguaje de la fe. La profesora Anscombe subraya esto en un escrito sobre la transubstanciación

311
El fin de este aprendizaje es ---como subraya el texto--- introducirnos en la inteligencia y vida de la fe. /emph{Saber usar} el lenguaje de la fe es una habilidad técnica que ayuda a la fe en su desarrollo y a la vez ayuda a introducirnos en ella.

La fe necesita un lenguaje ya que sólo puede referirse a su objeto mediante símbolos. Por ello el lenguaje no es sólo un modo de comunicación de la fe sino, sobre todo, algo necesario para estructurarse, definirse, identificarse.


#+BEGIN_SRC latex
\subsection{From Parmenides to Wittgenstein (1969) y The Question of Linguistic Idealism (1976)}


Una importante clave de interpretación de este artículo se encuentra en el lugar que ocupa como parte de esta colección. El título del volumen no es casual, el primer artículo es dedicado a Parménides, y el último, \emph{The Question of Linguistic Idealism}, es un examen de nociones importantes en la filosofía de Wittgenstein en donde reaparecen temas que Anscombe plantea ya en esta investigación dedicada a las ideas de Parménides. En este sentido, su análisis de los argumentos de Parménides pone en marcha una discusión que atraviesa todos los artículos del volumen. ¿En qué consiste esta discusión que Anscombe juzga presente ya en Parménides y viva todavía en Wittgenstein? En la introducción de la colección la describe diciendo: \blockquote[{\Cite[xi]{anscombe1981parmenides}}: \enquote{At the present day we are often perplexed with enquiries about what makes true, or what something's being thus or so \emph{consists in}; and the answer to this is thought to be an explanation of meaning. If there is no external answer, we are apparently committed to a kind of idealism}.]{En la época actual con frecuencia nos quedamos perplejos con preguntas sobre qué hace a algo verdadero, o \emph{en qué consiste} el que algo sea de un modo u otro; y la respuesta a esto se piensa que es una explicación del significado. Si no hay una respuesta externa, aparentemente estamos comprometidos con un tipo de idealismo}.\label{subsec:intextq}

El argumento parmenidiano también le sirve a Elizabeth para rechazar una confusión heredada por el \emph{Tractatus}. Se trata de un presupuesto que Parmenides tiene en común con Platón: \blockquote[{\Cite[x]{anscombe1981parmenides}}: \enquote{that a significant term is a name of an object which is either expressed or characterized by the term}.]{que un término significativo es el nombre de un objeto que está expresado o caracterizado por el término}. Este presupuesto, propone Anscombe, \blockquote[{\Cite[xi]{anscombe1981parmenides}}: \enquote{is an ancestor of much philosophical theorizing and perplexity}; En el texto continúa dando ejemplos de esta tradición que coinciden con las discusiones que están recogidas en este volumen de la colección: \enquote{In Aristotle \textelp{} the theory of substance and the inherence in substances of individualized forms of properties and relations of various kinds \textelp{} In Descartes \textelp{} the assertion that the descriptive terms which we use to construct even false pictures of the world must themselves stand for realities \textelp{} In Hume \textelp{} the assumption that `an object' corresponds to a term, even such a term as ``a cause'' as it occurs in ``A beginning of existence must have a cause.'' \textelp{} Brentano thinks that the mere predicative connection of terms is an `acknowledgement' \textelp{} Wittgenstein himself in the \emph{Tractatus} has language pinned to reality by its (postulated) simple names, which mean simple objects}.]{es un ancestro de mucha teorización y perplejidad filosófica}.
Esta tradición de \enquote*{teorización y perplejidad} que Anscombe traza culminando en el \emph{Tractatus} hace referencia al modelo de representación que se encuentra criticado en \emph{Investigaciones Filosóficas}. Anscombe nota en el argumento de Parménides un germen de la tradición subyacente a la conexión a priori entre el lenguaje y la realidad que aparece en el \emph{Tractatus}.

Esta preocupación de la época, aludida por Anscombe, tiene una presencia importante en \emph{Investigaciones Filosóficas}. Las \S\S428-465, en donde Wittgenstein se detiene a reflexionar sobre la intencionalidad, contienen implícitamente una crítica a ese modo de concebir el pensamiento, el lenguaje, la realidad y sus relaciones que sirvió para orientar las ideas del \emph{Tractatus}; específicamente son atacados: \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{the underlying assumptions that characterize the whole tradition of philosophical reflection of which it was the culmination}.]{los presupuestos subyacentes que han caracterizado toda la tradición de reflexión filosófica de la cual \textelp{el \emph{Tractatus}} fue la culminación}. Entre estos presupuestos se cuestiona enfáticamente \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{the venerable idea that the meaning of signs, their capacity to represent what they represent, is parasitic upon thought, upon mental processes of thinking and meaning}.]{la venerable idea de que el significar de los signos, su capacidad para representar lo que representan, depende del pensamiento, de procesos mentales de pensar y significar}. Esta idea, juzga Wittgenstein, es un producto de la concepción de los pensamientos como representación. Sobre los pensamientos así concebidos ha girado cierta discusión en la que se ha debatido acerca de qué es lo que constituye los pensamientos. Así: \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{the empiricists characteristically held them to be mental images or ideas; others, like the author of the \emph{Tractatus}, were more reticent, content to leave the matter to future psychological discovery, insisting only that thought-constituents must stand to reality in the same sort of relation as words}.]{los empiristas característicamente sostenían que estos eran imágenes mentales o ideas; otros, como el autor del \emph{Tractatus}, fueron más reticentes, contentándose con dejar el asunto al futuro descubrimiento psicológico, insistiendo solamente en que los constituyentes de pensamiento tienen que tener, respecto de la realidad, el mismo tipo de relación que las palabras}.

Dentro de este debate, la intencionalidad de los pensamientos, ---y aquí `pensamientos' pueden ser creencias, expectativas, esperanzas, temores, dudas, deseos, etc.--- era explicada también de modos distintos por los empiristas y por el autor del \emph{Tractatus}. Los primeros sosteniendo que la relación entre un pensamiento y la realidad correspondiente con este es externa, y el segundo que la relación es interna. La posibilidad de esta relación interna aparece explicada en el \emph{Tractatus}: \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{in terms of a pre-established metaphysical harmony between thought and reality. This harmony was conceived to consist in an essential isomorphism between representation and what is represented, wether truly or falsely}.]{en términos de una armonía metafísica preestablecida entre el pensamiento y la realidad. Esta armonía fue concebida como consistiendo en un isomorfismo esencial entre la representación y lo que es representado, ya sea verdadera como falsamente}. La concepción empirista \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{attempted to explain the intentionality of thought in causal terms \textelp{} construing the relation between thought and reality (between belief and what makes it true, or between desire and what fulfills it) as external}.]{intentó explicar la intencionalidad del pensamiento en términos causales \textelp{} interpretando la relación entre pensamiento y realidad (entre el creer y lo que lo hace verdadero, o entre el deseo y lo que lo realiza) como externa}. En \emph{Investigaciones Filosóficas} se critican estas dos posturas aunque se mantiene la idea de que la relación entre pensamiento y realidad es interna.

La consideración de que la relación entre lo que se cree y lo que hace esta creencia verdadera es una relación interna representa una dificultad adicional: \blockquote[{\Cite[4]{hacker2000mind}}: \enquote{for what we mean when we say that such-and-such is the case does not stop short of the fact that makes what we say true. We mean that very fact, and not something that stands in some relation (e.g. of correspondence) to it. We, as it were, reach right up to it. On the other hand, we can think what is \emph{not} the case. But if it is not the case, then it seems that there is nothing to reach right up to. Yet what we think when we think what is the case and what we think when we think what is not the case are not intrinsically different. How is this possible? The \emph{Tractatus} resolved the difficulty by arguing that what we think is the sense of a sentence, which is a \emph{possible} state of affairs, actual if what we think is the case and unactualized if what we think is not the case. For this a complex metaphysics and ontology and an elaborate doctrine of the depth grammar of all possible languages were introduced.}]{pues lo que significamos cuando decimos que alguna cosa es de hecho no se queda detenido ante el hecho que hace que lo que decimos sea verdadero. Significamos el mismo hecho y no algo que está situado en relación alguna (de correspondencia por ejemplo) con este. Nosotros, podría decirse, lo tenemos al alcance. Por otra parte, podemos pensar lo que \emph{no} es de hecho. Pero si no es de hecho, entonces parece que no hay nada para alcanzar. Sin embargo lo que pensamos cuando pensamos lo que es de hecho y lo que pensamos cuando pensamos lo que no es de hecho no es intrínsecamente distinto. ¿Cómo es esto posible? El \emph{Tractatus} resolvió la dificultad argumentando que lo que pensamos es el sentido de una oración, que es un \emph{posible} estado de las cosas, actual si lo que pensamos es de hecho y no actualizado si lo que pensamos no es de hecho. Para esto se introdujo una compleja metafísica y ontología y una elaborada doctrina sobre la gramática profunda de todos los lenguajes.}



#+END_SRC
