#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico/lang_and_myst.tex
#---------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros
La cuestión planteada en FR

es la cuestión de la analgía
dentro de la filo de Witt es una consideración mística

en la filisofía de Anscombe este análisis atraviesa los artículos recogidos en FPW

de toda esa discusión tendremos en cuenta el primero y el último, donde además se encuentran nociones relacionadas con el misterio.

67. La teología fundamental, por su carácter propio de disciplina que tiene la misión de dar razón de la fe (cf. 1 Pe 3, 15), debe encargarse de justificar y explicitar la relación entre la fe y la reflexión filosófica. Ya el Concilio Vaticano I, recordando la enseñanza paulina (cf. Rm 1, 19-20), había llamado la atención sobre el hecho de que existen verdades cognoscibles naturalmente y, por consiguiente, filosóficamente. Su conocimiento constituye un presupuesto necesario para acoger la revelación de Dios. Al estudiar la Revelación y su credibilidad, junto con el correspondiente acto de fe, la teología fundamental debe mostrar cómo, a la luz de lo conocido por la fe, emergen algunas verdades que la razón ya posee en su camino autónomo de búsqueda. La Revelación les da pleno sentido, orientándolas hacia la riqueza del misterio revelado, en el cual encuentran su fin último. Piénsese, por ejemplo, en el conocimiento natural de Dios, en la posibilidad de discernir la revelación divina de otros fenómenos, en el reconocimiento de su credibilidad, en la aptitud del lenguaje humano para hablar de forma significativa y verdadera incluso de lo que supera toda experiencia humana. La razón es llevada por todas estas verdades a reconocer la existencia de una vía realmente propedéutica a la fe, que puede desembocar en la acogida de la Revelación, sin menoscabar en nada sus propios principios y su autonomía.

83. Las dos exigencias mencionadas conllevan una tercera: es necesaria una filosofía de alcance auténticamente metafísico, capaz de trascender los datos empíricos para llegar, en su búsqueda de la verdad, a algo absoluto, último y fundamental. Esta es una exigencia implícita tanto en el conocimiento de tipo sapiencial como en el de tipo analítico; concretamente, es una exigencia propia del conocimiento del bien moral cuyo fundamento último es el sumo Bien, Dios mismo. No quiero hablar aquí de la metafísica como si fuera una escuela específica o una corriente histórica particular. Sólo deseo afirmar que la realidad y la verdad transcienden lo fáctico y lo empírico, y reivindicar la capacidad que el hombre tiene de conocer esta dimensión trascendente y metafísica de manera verdadera y cierta, aunque imperfecta y analógica. En este sentido, la metafísica no se ha de considerar como alternativa a la antropología, ya que la metafísica permite precisamente dar un fundamento al concepto de dignidad de la persona por su condición espiritual. La persona, en particular, es el ámbito privilegiado para el encuentro con el ser y, por tanto, con la reflexión metafísica.

Dondequiera que el hombre descubra una referencia a lo absoluto y a lo trascendente, se le abre un resquicio de la dimensión metafísica de la realidad: en la verdad, en la belleza, en los valores morales, en las demás personas, en el ser mismo y en Dios. Un gran reto que tenemos al final de este milenio es el de saber realizar el paso, tan necesario como urgente, del fenómeno al fundamento. No es posible detenerse en la sola experiencia; incluso cuando ésta expresa y pone de manifiesto la interioridad del hombre y su espiritualidad, es necesario que la reflexión especulativa llegue hasta su naturaleza espiritual y el fundamento en que se apoya. Por lo cual, un pensamiento filosófico que rechazase cualquier apertura metafísica sería radicalmente inadecuado para desempeñar un papel de mediación en la comprensión de la Revelación.

La palabra de Dios se refiere continuamente a lo que supera la experiencia e incluso el pensamiento del hombre; pero este « misterio » no podría ser revelado, ni la teología podría hacerlo inteligible de modo alguno, 102 si el conocimiento humano estuviera rigurosamente limitado al mundo de la experiencia sensible. Por lo cual, la metafísica es una mediación privilegiada en la búsqueda teológica. Una teología sin un horizonte metafísico no conseguiría ir más allá del análisis de la experiencia religiosa y no permitiría al intellectus fidei expresar con coherencia el valor universal y trascendente de la verdad revelada.

Si insisto tanto en el elemento metafísico es porque estoy convencido de que es el camino obligado para superar la situación de crisis que afecta hoy a grandes sectores de la filosofía y para corregir así algunos comportamientos erróneos difundidos en nuestra sociedad.

84. La importancia de la instancia metafísica se hace aún más evidente si se considera el desarrollo que hoy tienen las ciencias hermenéuticas y los diversos análisis del lenguaje. Los resultados a los que llegan estos estudios pueden ser muy útiles para la comprensión de la fe, ya que ponen de manifiesto la estructura de nuestro modo de pensar y de hablar y el sentido contenido en el lenguaje. Sin embargo, hay estudiosos de estas ciencias que en sus investigaciones tienden a detenerse en el modo cómo se comprende y se expresa la realidad, sin verificar las posibilidades que tiene la razón para descubrir su esencia. ¿Cómo no descubrir en dicha actitud una prueba de la crisis de confianza, que atraviesa nuestro tiempo, sobre la capacidad de la razón? Además, cuando en algunas afirmaciones apriorísticas estas tesis tienden a ofuscar los contenidos de la fe o negar su validez universal, no sólo humillan la razón, sino que se descalifican a sí mismas. En efecto, la fe presupone con claridad que el lenguaje humano es capaz de expresar de manera universal —aunque en términos analógicos, pero no por ello menos significativos— la realidad divina y trascendente. 103 Si no fuera así, la palabra de Dios, que es siempre palabra divina en lenguaje humano, no sería capaz de expresar nada sobre Dios. La interpretación de esta Palabra no puede llevarnos de interpretación en interpretación, sin llegar nunca a descubrir una afirmación simplemente verdadera; de otro modo no habría revelación de Dios, sino solamente la expresión de conceptos humanos sobre Él y sobre lo que presumiblemente piensa de nosotros.


dominguez 357
Cabría decir que ésta es una consideración \emph{mística}. Con místico me refiero, en principio al uso wittgensteniano: ``Nicht wie die Welt ist, ist das Mystische, sondern daß sie ist''. En efecto, a la actitud mística pertenece la persuasión de que la verdad es un tema vital que trasciende, la certeza de que ante ella el ejercicio racional culmina en contemplación. Es, de nuevo, un momento en el que la racionalidad filosófica se pone en busca de otro nivel que la supera: la Revelación. Esta dimensión mistica no está lejos de la metafísica, ni de la ética. 

\footnote{\cite[Cf.][156]{monk1991duty}: \enquote{The famous last sentence of the book ---`Whereof one cannot speak, thereof one must be silent'--- expresses both a logico-philosophical truth and an ethical precept.}; Wittgenstein explicó esta finalidad ética de su obra en una carta a Ludwig von Ficker de este modo: \cite[22-23]{monk2005howto}: \enquote{the point of the book is ethical. I once wanted to give a few words in the foreword which now are actually not in it, which, however, I'll write to you now because they might be a key for you: I wanted to write that my work consists on two parts: of the one which is here, and of everything which I have \emph{not} written. And precisely this second part is the important one. For the Ethical is delimited from within, as it were, by my book; and I'm convinced that, \emph{strictly} speaking, it can ONLY be delimited in this way. In brief, I think: All of that whcih \emph{many} are \emph{babbling} today, I have defined in my book by remaning silent about it}.}.

En consecuencia, la actitud previa que se ha de mantener ante la verdad es, no cabe duda, martirial; sí, testimonial en el sentido cabal de la palabra.

dominguez 357
la primera de las actitudes, la que hemos visto ubicada, \emph{grosso modo}, en la época medieval, considera que la verdad existe con independencia del hombre que la pueda conocer. Es, por así decir, anterior a él. La segunda, tiende a identificar al hombre con la verdad misma. La tercera de las actitudes, en el fondo, niega la existencia de la verdad.

dominguez 355
En la época medieval, \emph{grosso modo}, la verdad era \emph{testimoniada}. Es decir, el intelectual, el amante de la verdad, el hombre corriente, era consciente de ser "testigo" de una verdad que le excedía, y que le había sido dada. Esta actitud no era vivida, en modo alguno, como una alienación, sino como una gozosa experiencia de la creaturalidad en la cual se vivía. Era un hecho filosóficamente aceptado que la razón no bastaba a la razón.

Conesa 310-311
Las observaciones de L. Wittgenstein a este respecto subrayan la importancia que tiene en el contexto de la fe el aprendizaje del lenguaje. No se trata, sin embargo, de aprender un lenguaje esotérico y distanciado del lenguaje ordinario. Se trata de <<aprender cómo usar el lenguaje con más amplitud. El lenguaje que usa la religión es el mismo que se usa en otros universos de discurso. No es un lenguaje especial sino el mismo lenguaje ordinario al que se da un uso particular>>.

Este lenguaje es aprendido de la Iglesia. Una de las tareas del proceso catequético es precisamente la enseñanza del lenguaje de la fe. La profesora Anscombe subraya esto en un escrito sobre la transubstanciación

311
El fin de este aprendizaje es ---como subraya el texto--- introducirnos en la inteligencia y vida de la fe. /emph{Saber usar} el lenguaje de la fe es una habilidad técnica que ayuda a la fe en su desarrollo y a la vez ayuda a introducirnos en ella.

La fe necesita un lenguaje ya que sólo puede referirse a su objeto mediante símbolos. Por ello el lenguaje no es sólo un modo de comunicación de la fe sino, sobre todo, algo necesario para estructurarse, definirse, identificarse.

259
La consideración de la fe como aceptación del testimonio de Dios puede también ser vista desde otra perspectiva similar: el motivo de la fe es Dios en cuanto Verdad Primera. Al creer, el hombre se apoya en la infalibilidad divina como garantía suprema de verdad. Este aspecto aparece especialmente en la expresión \emph{creer a Dios}. Al creer a Dios, el hombre se apoya en la veracidad divina y por lo mismo se confía al Dios de la verdad.

#+BEGIN_SRC latex
%\subsection{Intro}
A lo largo de este trabajo hay una línea de investigación que se ha ido desarrollando y que desemboca en una región de la obra de Anscombe que trata sobre una cuestión filosófica compleja. Ha partido desde la propuesta de repensar el nexo entre razón, afectos y libertad con una visión más amplia; y la consideración de que en el contexto de la filosofía analítica este nexo se estudia dentro de la actividad humana del lenguaje (\S\ref{subsec:amplia}, p.~\pageref{subsec:amplia})\footnote{Esta línea ha continuado a traves de varias cuestiones: Desde la perspectiva de la investigación teológica se ha planteado como la pregunta sobre la capacidad del lenguaje para hablar de forma significativa incluso de lo que supera la experiencia humana (\S\ref{subsec:aptitud}, p.~\pageref{subsec:aptitud}). Además indagamos sobre este tema al exponer los desafíos planteados por el Círculo de Viena que desde ciertas interpretaciones de nociones wittgensteinianas realizaron una crítica de la capacidad del lenguaje religioso para comunicar conocimiento (\S\ref{subsec:viena}, p.~\pageref{subsec:viena}). Adentrándonos más al ámbito de la filosofía de Wittgenstein, F. Kerr nos proponía que su análisis de la relación entre realidad, pensamiento y lenguaje constituye un intento de reconocer cómo es el ser humano y junto a esto que la investigación teológica puede ser entendida como investigación gramatical (\S\ref{subsec:comosomos}, p.~\pageref{subsec:comosomos}).}. En este apartado culmina con la consideración de que para comprender la categoría de testimonio en la obra de Anscombe es preciso tener en cuenta su discusión sobre la capacidad del lenguaje para significar. Específicamente su comprensión de la capacidad de la práctica lingüísica humana para comunicar la verdad en tanto que trascendental. 

Para explicar mejor cómo ambos temas se relacionan en la filosofía de Anscombe podemos recurrir a una propuesta de F. Conesa en su estudio sobre el valor cognoscitivo de la fe. Plantea que para Wittgenstein un elemento importante en la religión es el aprendizaje de un lenguaje, entonces propone: \blockquote[{\Cite[310-311]{conesa1994cc}}]{Las observaciones de L. Wittgenstein a este respecto subrayan la importancia que tiene en el contexto de la fe el aprendizaje del lenguaje. No se trata, sin embargo, de aprender un lenguaje esotérico y distanciado del lenguaje ordinario. Se trata de <<aprender cómo usar el lenguaje con más amplitud. El lenguaje que usa la religión es el mismo que se usa en otros universos de discurso. No es un lenguaje especial sino el mismo lenguaje ordinario al que se da un uso particular>>.

Este lenguaje es aprendido de la Iglesia. Una de las tareas del proceso catequético es precisamente la enseñanza del lenguaje de la fe. La profesora Anscombe subraya esto en \textelp{su} escrito sobre la transubstanciación
  \textelp{} El fin de este aprendizaje es ---como subraya el texto--- introducirnos en la inteligencia y vida de la fe. \emph{Saber usar} el lenguaje de la fe es una habilidad técnica que ayuda a la fe en su desarrollo y a la vez ayuda a introducirnos en ella.}

Aquí se encuentra un presupuesto importante tanto de nuestra comprensión de la fe, como de la noción que tiene Elizabeth del lenguaje: \blockquote[][\,(FR 84)]{la fe presupone con claridad que el lenguaje humano es capaz de expresar de manera universal ---aunque en términos analógicos, pero no por ello menos significativos--- la realidad divina y trascendente. Si no fuera así, la palabra de Dios, que es siempre palabra divina en lenguaje humano, no sería capaz de expresar nada sobre Dios}. Nos encontramos aquí ante una convergencia donde la revelación entendida como testimonio divino, la fe como confianza en su palabra y la práctica linguística como actividad donde la verdad se comunica componen facetas de una misma realidad.\footnote{F. Conesa argumenta en \Cite[259]{conesa1994cc}: \enquote{La consideración de la fe como aceptación del testimonio de Dios puede también ser vista desde otra perspectiva similar: el motivo de la fe es Dios en cuanto Verdad Primera. Al creer, el hombre se apoya en la infalibilidad divina como garantía suprema de verdad. Este aspecto aparece especialmente en la expresión \emph{creer a Dios}. Al creer a Dios, el hombre se apoya en la veracidad divina y por lo mismo se confía al Dios de la verdad.}, también añade: \enquote{B. Duroux demuestra que Santo Tomás se está refiriendo a la misma realidad cuando habla de la autoridad de Dios, el testimonio divino y la \emph{Verdad primera}. Se trata simplemente de cambios de acento.}}

El espíritu con el que Elizabeth Anscombe entiende y estudia este tema lo hereda del \emph{Tractatus}, donde la cuestión sobre la capacidad del lenguaje para significar culmina como preocupación ética\footnote{\cite[Cf.][156]{monk1991duty}: \enquote{The famous last sentence of the book ---`Whereof one cannot speak, thereof one must be silent'--- expresses both a logico-philosophical truth and an ethical precept.}; Wittgenstein explicó esta finalidad ética de su obra en una carta a Ludwig von Ficker de este modo: \cite[22-23]{monk2005howto}: \enquote{the point of the book is ethical. I once wanted to give a few words in the foreword which now are actually not in it, which, however, I'll write to you now because they might be a key for you: I wanted to write that my work consists on two parts: of the one which is here, and of everything which I have \emph{not} written. And precisely this second part is the important one. For the Ethical is delimited from within, as it were, by my book; and I'm convinced that, \emph{strictly} speaking, it can ONLY be delimited in this way. In brief, I think: All of that whcih \emph{many} are \emph{babbling} today, I have defined in my book by remaning silent about it}.} y consideración mística\footnote{\Cite[357]{dominguez2009at}: \enquote{Cabría decir que ésta es una consideración \emph{mística}. Con místico me refiero, en principio, al uso wittgensteniano: ``Nicht wie die Welt ist, ist das Mystische, sondern daß sie ist''.}}. Lo que esto quiere decir es que para ella, como para el \emph{Tractatus}, el interés consiste en argumentar una actitud o predisposición existencial ante la verdad\footnote{\Cite[Cf.][354-355]{dominguez2009at}}, más que una definición. Para el \emph{Tractatus} esto constituye una cuestión ética, puesto que pretende trazar el límite de lo que puede ser dicho. Desde el contexto de nuestro estudio, y la obra de Anscombe, hay un aspecto adicional a esta cuestión ética que puede ser expresada diciendo: \blockquote[{\Cite[354]{dominguez2009at}}]{Dada la inseparabilidad de la verdad y la libertad \textelp{} Es pertinente ahora, pues, mostrar qué actitudes \textins{hacia la verdad} no hacen justicia a la noción de libertad en el hombre que se sigue de su ser \emph{imago Dei}, y cuál sí}. En cuanto al aspecto `místico' de esta cuestión, desde la perspectiva del \emph{Tractatus}, este consiste en la noción de que en el lenguaje se muestra una verdad que es inefable, que no se puede decir con el lenguaje. Para nosotros y para Anscombe consiste en la conciencia de que en la actividad humana del lenguaje actuamos como testigos de la verdad que nos excede\footnote{\Cite[Cf.][354-355]{dominguez2009at}: \enquote{En la época medieval, \emph{grosso modo}, la verdad era \emph{testimoniada}. Es decir, el intelectual, el amante de la verdad, el hombre corriente, era consciente de ser "testigo" de una verdad que le excedía, y que le había sido dada. Esta actitud no era vivida, en modo alguno, como una alienación, sino como una gozosa experiencia de la creaturalidad en la cual se vivía. Era un hecho filosóficamente aceptado que la razón no bastaba a la razón.}}. En este sentido, una buena manera de caracterizar la actitud `mística' que Anscombe adopta ante la verdad en tanto que trascendental puede ser puesta en estos términos: \blockquote[{\Cite[357]{dominguez2009at}}]{En efecto, a la actitud mística pertenece la persuasión de que la verdad es un tema vital que trasciende, la certeza de que ante ella el ejercicio racional culmina en contemplación. Es, de nuevo, un momento en el que la racionalidad filosófica se pone en busca de otro nivel que la supera: la Revelación. Esta dimensión mística no está lejos de la metafísica, ni de la ética. \textelp{} En consecuencia, la actitud previa que se ha de mantener ante la verdad es, no cabe duda, martirial; sí, testimonial en el sentido cabal de la palabra.}

En efecto Anscombe mantiene a lo largo de su obra esta actitud inspirada por el \emph{Tractatus}, esa \enquote*{persuasión de que la verdad es un tema vital que trasciende}. Sin embargo va más allá, pues no sostiene ---como lo hace el \emph{Tractatus}--- que el aspecto trascendente de la verdad no se revela \emph{en} el mundo. En este sentido es importante su giro hacia las nociones de la obra posterior de Wittgenstein, específicamente en \emph{Investigaciones Filosóficas} y \emph{Sobre la Certeza} donde el análisis del lenguaje no está orientado hacia la forma lógica pura como conexión metafísica entre pensamiento y realidad, sino a la actividad humana donde esta conexión se encuentra viva. Para Elizabeth, la verdad, siendo trascendental, se revela en el lenguaje y en la acción humana como rectitud\footnote{Para una discusión más ámplia véase: \Cite{torralbaynubiola2005fayeh:unidadverdad}. En nuestro estudio este tema se discute en: \S\ref{subsec:verdad}, p.~\pageref{subsec:verdad}.}.

Dentro de la obra de Elizabeth esta cuestión se encuentra desarrollada en el primer volumen de su colección publicada en 1981, el cual tituló \emph{From Parmenides to Wittgenstein}. El volumen reúne a autores como Parménides, Platón, Hume y Wittgenstein y constituye un recorrido realizado a través de varios artículos donde Anscombe analiza aportaciones filosóficas en torno a la relación entre lo concebible y lo posible\footnote{\cite[Cf.][193]{teichmann2008ans}: \enquote{Philosophers have grappled since ancient times with the problem of how thinkability and possibility are related, and it is characteristic of Anscombe to have drawn such diverse figures as Parmenides, Plato, Hume, and Wittgenstein into a single discussion}.}. Las reflexiones de Elizabeth en los artículos recogidos en el volumen componen el estudio de una discusión que se ha desarrollado a lo largo de la obra de muchos autores filosóficos. ¿En qué consiste esta discusión que Anscombe juzga presente ya en Parménides y viva todavía en Wittgenstein? En la introducción de la colección la describe diciendo: 
\blockquote[{\Cite[xi]{anscombe1981parmenides}}: \enquote{At the present day we are often perplexed with enquiries about what makes true, or what something's being thus or so \emph{consists in}; and the answer to this is thought to be an explanation of meaning. If there is no external answer, we are apparently committed to a kind of idealism}.]{En la época actual con frecuencia nos quedamos perplejos con preguntas sobre qué hace a algo verdadero, o \emph{en qué consiste} el que algo sea de un modo u otro; y la respuesta a esto se piensa que es una explicación del significado. Si no hay una respuesta externa, aparentemente estamos comprometidos con un tipo de idealismo}.\label{subsec:intextq}

Como hemos aludido, esta es una discusión compleja. Sin embargo hay un aspecto de ésta que es de particular interés. A lo largo de su análisis, Anscombe entrelaza, dentro de sus investigaciones sobre el lenguaje, argumentaciones para proponer que aquellas creencias que en la religión llamamos `misterios' no son lo mismo que el `sinsentido' o producto de `no pensar'. Para ella la creencia en los misterios de la fe es una actitud contraria al deseo de querer profesar la contradicción. Este tema, no solo guarda relación con el estudio de la categoría del testimonio, sino que representa una expresión culminante de las ideas de Anscombe sobre la manera en que la verdad en tanto que trascendental se comunica en la actividad humana del lenguaje. Examinaremos qué tiene que decir Elizabeth sobre esto en los artículos que ella usa para abrir y concluir el volumen.

El primer artículo: \emph{Parmenides, Mystery and Contradiction}, es el texto de una ponencia ofrecida por Anscombe en la reunión del \emph{Aristotelian Society} en Londres el 24 de febrero de 1969. En esta discusión Elizabeth analiza lo que ella considera un `ancestro' de la teoría de representación que está detrás de la comprensión del lenguaje que tiene el \emph{Tractatus}. El interés en este artículo se encuentra en dos premisas que Anscombe valora de las nociones de los antiguos y del \emph{Tractatus}: que las limitaciones de lo concebible quedan constituidas por las restricciones de lo posible\footnote{\Cite[Cf.][viii]{anscombe1981parmenides}: \enquote{If I am right, the ancients never argued from constraints on what could be a thought to restrictions on what could be, but only the other way around}. Véase también: \cite[xi]{anscombe1981parmenides}: \enquote{It was left to the moderns to deduce what could be from what could hold of thought, as we see Hume to have done. This trend is still strong. But the ancients had the better approach, arguing only that a thought was impossible because the thing was impossible, or, as the Tractatus puts it, ``Was man nicht denken kann, das kann man nicht denken'': an \emph{impossible} thought is an impossible \emph{thought}}.} y que la crítica de las proposiciones como expresiones de pensamiento real no implica que haya algún principio que pueda ser aplicado \emph{a priori} para descartarlas como inconcebibles, sino que la crítica debe ser \emph{ad hoc}, cada proposición debe ser examinada\footnote{\Cite[Cf.][151]{anscombe1959iwt}: \enquote{The criticism of sentences as expressing no real thought, according to the principles of the \emph{Tractatus}, could never be of any very simple general form; each criticism would be \emph{ad hoc}, and fall within the subject-matter with which the sentence professed to deal}.}.

El segundo artículo: \emph{The Question of Linguistic Idealism} fue publicado en 1976 en \emph{Acta Philosophica Fennica} junto a otros ensayos sobre Wittgenstein en honor de G.\,H.\,von Wright\footnote{Sucesor de Wittgenstein en la cátedra de filosofía en Cambrdige entre 1948-1951, puesto que Anscombe ocuparía en 1970. También fue con Elizabeth uno de los responsables del legado literario de Wittgenstein.}. En este artículo Anscombe examina cómo puede ser caracterizada la pretensión de Wittgenstein en su análisis del nexo entre pensamiento y realidad: \blockquote[{\Cite[VI, 23]{wittgenstein1956remmathes}}]{No empiría y sí realismo en filosofía, eso es lo más difícil.}. El artículo está dividido en dos partes, la primera dedicada al aspecto semántico del tema, derivado de la concepción de la esencia del lenguaje en \emph{Investigaciones Filosóficas} y se pregunta si hay algún sentido en el que se pueda decir que la `gramática' crea una esencia; la segunda se enfoca más en los aspectos epistemológicos de la cuestión según aparecen en la discusión de \emph{Sobre la Certeza} y se cuestiona sobre qué significa `acuerdo en el lenguaje' y cuáles son sus implicaciones\footnote{\cite[Cf.][215]{teichmann2008ans}: \enquote{The essay is in two parts, these correspond roughly to the semantic and epistemological aspects of the topic}.}. El interés en este artículo se encuentra en la cuestión de la relación entre necesidad ---lógica\footnote{Para Anscombe la `necesidad lógica' se expresa en las reglas que rigen la inferencia válida: \Cite[Cf.][121]{anscombe1981parmenides:qli}: \enquote{Always there is the logical \emph{must}: you can't have this \emph{and} that; you can't do that if you are going by this rule; you must grant this in face of that. And just as ``You can't move your king'' is the more basic expression for one learning chess, since it lies at the bottom of his learning the concept of the game and its rules, so these ``You must's'' and ``You cant's'' are the more basic expressions in logical thinking. But they are not what Hume calls ``naturally intelligible''\,---\,that is to say, they are not expressions of perception or experience. They are understood by those of normal intelligence as they are trained in the practices of reasoning}.} y `aristotélica'\footnote{Para Elizabeth este tipo de necesidad está expresado en los deberes relacionados con las promesas, las reglas y los derechos: \Cite[Cf.][118]{anscombe1981parmenides:qli}: \enquote{there are, of course, a great many things whose existence does depend on human linguistic practice. The dependence is in many cases an unproblematic and trivial fact. But in others it is not trivial\,---\,it touches the nerve of great philosophical problems. The cases I have in mind are three: namely rules, rights and promises}. Este tipo de necesidad queda expresada en los deberes relacionados con estas prácticas:
\cite[Cf.][100]{anscombe1981erp:rrp}: \enquote{What we have to attend to is the use of modals. Through this, we shall find that not only promises, but also rules and rights, are essences \emph{created} and not merely captured or expressed by the grammar of our languages. Modals come in mutually definable related pairs, as: necessary, possible; must, need not; ought, need not, etc.; together with modal inflections of other words}.}--- y la práctica lingüística, descrita como el ``ir según una regla''; además, que estas reglas no responden a un objetivo o correspondencia con alguna realidad, sino que están fundadas en el `hecho en bruto' de que los seres humanos aprendemos a responder a las reglas con propuestas que establecen un acuerdo\footnote{\Cite[Cf.][219]{teichmann2008ans}: \enquote{A justification for a `You must' will not come from outside the practice, but from within it. Anscombe takes it that for Wittgenstein, conceptual and logical necessity are both expressed by means of this `You must'}. También en: \Cite[Cf.][220]{teichmann2008ans}: \enquote{the rules of linguistic practice cannot be justified from without, and rest ultimately on the brute fact that human beings learn to respond to `You must' in a way that produces agreement in response}.} y que este acuerdo es posible por un hecho `general de la naturaleza'\footnote{\Cite[Cf.][133]{anscombe1981parmenides:qli}: \enquote{\emph{That one knows something is not guaranteed by the language-game}. \textelp{} But the language-game of assertion, which for speaking humans is so important a part of the whole business of knowing and being certain, depends for its character on a `general fact of nature'}. Véase también: \Cite[Cf.][224]{teichmann2008ans}: \enquote{For Wittgenstein, `that one knows something is not guaranteed by the language-game' (QLI 133) --- for there is such a thing as radical change of view, however rare, and the natural expression of this is `I was wrong'. The possibility of radical change of view is compatible with the fact that, in the absence of such change, `I know' and `I am certain' are justifiable forms of expression within the language-game}.}. De interés también es la noción de la `imagen del mundo' que sirve como fundamento inmóvil de nuestras creencias\footnote{\Cite[130]{anscombe1981parmenides:qli}: \enquote{There are assumptions, beliefs, that are the `immovable foundation' of these proceedings. \textelp{} they are a foundation which is not moved by any of these proceedings. I cannot doubt or question anything unless there are some things I do not doubt or question}. Para un descripción más detallada véase: \Cite[\S95-99]{wittgenstein1969oncertes}}.
#+END_SRC

#+BEGIN_SRC latex
Teniendo en cuenta ambos artículos podríamos decir que Anscombe indaga en el problema: ¿cómo se explica la capacidad del lenguaje para significar?, ¿consiste en un proceso mental?, ¿es la posibilidad de relacionar ciertos signos con ciertos hechos? Critíca una respuesta inadecuada a esto que se apoya sobre un presupuesto \blockquote[{\cite[xi]{anscombe1981parmenides}}: \enquote{is an ancestor of much philosophical theorizing and perplexity}.]{que es un ancestro de mucha teorización y perplejidad}: \blockquote[{\cite[x]{anscombe1981parmenides}}: \enquote{that a significant term is a name of an object which is either expressed or characterized by the term}.]{que un término significativo es el nombre de un objeto que está expresado o caracterizado por el término}. Entonces propone que una descripción más adecuada es que un término significativo es uno que tiene una aplicación posible dentro de nuestra práctica lingüistica. Es decir, tiene una gramática aplicable. Las reglas de estas prácticas lingüísticas, de lo que constituye una inferencia válida y de lo que es imprescindible para alcanzar el bien y evitar el mal, se generan dentro del juego de lenguaje, pero dependen de un `hecho general de la naturaleza':  que es raro que haya un cambio radical de perspectiva que implique que tengamos que afirmar estar equivocados de algo de lo que hemos juzgado que hemos conocido o creído con certeza.

Esta argumentación servirá a Elizabeth, en definitiva, para reinvindicar desde dentro del sistema de Wittgenstein la posibilidad del misterio como una realidad trascendente que se expresa en nuestra práctica lingüistica. Esto es un presupuesto importante a la hora de argumentar la revelación como testimonio divino y propuesta creíble.
#+END_SRC
 
#+BEGIN_SRC latex
En \emph{Parmenides, Mystery and Contradiction} Anscombe propone que hay afirmaciones que son simplemente `abracadabra', es decir, puro sinsentido. A estas no hay que prestarle atención. Entonces, ¿qué sucede con las expresiones que no son sinsentido, pero que aún presentan dificultades a la hora de determinar para ellas un sentido inobjetable? En esos casos ¿podríamos descartar la posibilidad de que este sentido enigmático sea una verdad? Como respuesta a esta pregunta, Anscombe propone un criterio que parece ofrecer un modo de caracterizar lo que puede ser pensado: \blockquote[{\Cite[8]{anscombe1981parmenides:pmc}}: \enquote{This suggests as the sense of ``can be grasped in thougth''; ``can be presented in a sentence which can be seen to have an unexceptionable non-contradictory sense''. A form of: whatever can be said at all can be said clearly}.]{Esto sugiere como el sentido de ``puede ser captado en el pensamiento''; ``puede ser presentado en una oración que pueda ser vista como teniendo un irreprochable sentido no-contradictorio''. Una forma de: todo lo que puede ser expresado en absoluto puede ser expresado claramente}.

Sin embargo, aunque para ella sería aceptable pensar en ``ser presentado en una afirmación que pueda verse que tiene un inobjetable sentido no-contradictorio'' como la manera de afirmar lo que podría ser captado en el pensamiento, le parece que esto no sirve para establecer que haya alguna cosa que no pueda ser pensada: \blockquote[{\Cite[8]{anscombe1981parmenides:pmc}}: \enquote{Someone who thought this \emph{might} think ``There may be the inexpressible.'' And so in that sense think ``There may be what can't be thought''. ---But he wouldn't be exercised by any definite claimant to be that which can't be grasped in thought. \emph{Mystery} would be illusion\,---\,either the thought expressing something mysterious could be clarified, and then no mystery, or the impossibility of clearing it up would show it was really a non-thought. The trouble is, there doesn't seem to be any ground for holding this position. It is a sort of prejudice}.]{Alguien que piense esto \emph{puede} pensar ``Puede haber lo inexpresable.'' Y entonces en ese sentido ``Puede haber lo que no puede ser pensado''. ---Pero no estaría siendo movido por alguna cosa determinada que le estuviera reclamando ser aquello que no puede ser captado en el pensamiento. El \emph{misterio} sería una ilusión\,---\,una de dos, el pensamiento expresando algo misterioso podría ser clarificado, y entonces no hay misterio, o la imposibilidad de aclararlo mostraría que era verdaderamente un no-pensamiento. El problema es, que no parece haber ningún fundamento para sostener esta posición. Es una especie de prejuicio}.

Anscombe compara su proposición acerca de lo que puede caracterizar lo que puede ser pensado con la afirmación que se encuentra en el prefacio del \emph{Tractatus}, \enquote*{lo que puede ser expresado en absoluto puede ser expresado claramente}; sin embargo, juzga como un prejuicio la creencia, expresada también en el \emph{Tractatus}, de que esto implique que \enquote*{hay lo inexpresable}, o \enquote*{hay lo que no puede ser pensado}. 
Esto implica que las proposiciones no han de ser descartadas por algún principio general \emph{a priori}, sino que es preciso el análisis del uso que estas expresiones tienen en la práctica lingüística. En el uso de los signos del lenguaje dentro de la vida es donde se encuentran pensamiento y realidad, esto como contrario a la idea de que la relación entre pensamiento y realidad se encuentra en una armonía metafísica \emph{a priori}. De ahí que su propuesta sobre lo que puede caracterizar un pensamiento dirija la atención a la posibilidad de presentar el pensamiento en el lenguaje.

Según esto, para Anscombe, creer en un misterio no presupone una actitud acrítica que abrace la contradicción, sino que consiste mas bien en la disposición de examinar el uso que se hace de las expresiones en el lenguaje y la actividad humana, teniendo en cuenta que los misterios son expresiones que no pueden quedar definitivamente demostradas, pero que tampoco pueden quedar descartadas como no expresando un pensamiento posible.
#+END_SRC

#+BEGIN_SRC latex
Junto a estas premisas están las consideraciones realizadas por Elizabeth en \emph{The Question for Linguistic Idealism}. Allí observa que: \blockquote[{\Cite[123]{anscombe1981parmenides:qli}}: \enquote{Wittgenstein's attitude to the whole of religion in a way assimilated it to the mysteries: thus he detested natural theology. But again, what part of this was philosophical (and therefore something which, if right, others ought to see) and what personal, it is difficult to say}.]{La actitud de Wittgenstein hacia el todo de la religión la asimilaba en cierto modo a los misterios: por consiguiente detestaba la teología natural. Pero de nuevo, qué parte de esto era filosófico (y por tanto algo que, si fuera correcto, otros han de ver) y qué parte era personal, es difícil decir}. Un ejemplo de esta actitud se puede encontrar en \emph{Sobre la Certeza} donde hace referencia a distintas ideas y creencias religiosas, específicamente, por ejemplo: \blockquote[{\Cite[\S239]{wittgenstein1969oncertes}}.
%: \enquote{I believe that every human being has two human parents; but Catholics believe that Jesus only had a human mother. \textelp{} Catholics believe as well that in certain circumstances a wafer completely changes its nature, and at the same time that all evidence proves the contrary. And so if Moore said ``I know that this is wine and not blood'', Catholics would contradict him.}]{Creo que todo ser humano tiene dos padres humanos; pero los católicos creen que Jesús solo tuvo una madre humana. \textelp{} Los católicos creen también que en ciertas circunstancias un trozo de pan completamente cambia su naturaleza, y al mismo tiempo que toda evidencia demuestra lo contrario. Y así si Moore dijera ``Yo conozco que eso es vino y no sangre'', los católicos lo contradirían}.
]{Sí, creo que todos tenemos dos progenitores humanos; sin embargo, los católicos creen que Jesús sólo tuvo una madre humana. \textelp{} Los católicos también creen que una oblea, en circunstancias determinadas, cambia completamente de naturaleza y, al mismo tiempo, que toda la evidencia prueba lo contrario. Por lo tanto, si Moore dijera: ``Sé que esto es vino y no sangre'', los católicos lo contradirían}. Anscombe cuenta también otro ejemplo:\blockquote[{\Cite[122]{anscombe1981parmenides:qli}}: \enquote{At the Moral Science Club he once quoted a passage from St Augustine about God which with the characteristic rhetoric of St Augustine sounded contradictory, Wittgenstein even took ``he moves without moving'' as a contradiction in intent, and was impatient being told that that at least was not so, the first ``moves'' being transitive and the second intransitive (\emph{movet, non movetur})}.]{En una ocasión citó en el \emph{Moral Science Club} un pasaje de San Agustín acerca de Dios el cual, con la retórica característica de San Agustín, sonaba contradictorio, Wittgenstein incluso tomó ``mueve sin moverse'' como una contradicción de propósito, y se mostró impaciente al decírsele que eso al menos no era así, el primer ``mueve'' siendo transitivo y el segundo intransitivo (\emph{movet, non movetur})}. En ambos casos Ludwig ve proposiciones que trata como misterios, sin hacer distinción entre argumentaciones de teología natural o creencias en misterios como la Eucaristía. Su actitud ante los misterios no era contraria, sino que, por ejemplo, en el caso del argumento de Agustín: \blockquote[{\Cite[122]{anscombe1981parmenides:qli}}: \enquote{He wished to take the contradiction as seriously intended and at the same time to treat it with respect}.]{Él deseaba tomar la contradicción como seriamente intencional y al mismo tiempo quería tratarla con respeto}.

Anscombe atribuye todo esto a el desagrado de Wittgenstein de describir la religión como racional: \blockquote[{\Cite[122]{anscombe1981parmenides:qli}}: \enquote{This was connected with his dislike of rationality or would-be rationality in religion. He would describe this with a characteristic simile: there is something all jagged and irregular, and some people have a desire to encase it in a smooth ball: looking within you see the jagged edges and spikes, but a smooth surface has been constructed. He preferred it left jagged. I don't know how to distribute this between philosophical observation on the one hand and personal reaction on the other.}]{Esto estaba conectado con su desagrado de la racionalidad o potencial racionalidad de la religión. Describía esto con un símil característico: hay algo todo escarpado e irregular, y algunas personas tienen el deseo de encerrarlo en una esfera lisa: mirando dentro de ella se pueden ver las espinas e irregularidades, pero una superficie lisa ha sido construida sobre estas. Él prefería que se dejara escarpado. No se como distribuir esto entre observación filosófica por una parte y reacción personal por otra}. Adicionalmente, dentro del sistema de pensamiento de Ludwig, no es posible justificar el tipo de proposiciones que la teología natural emplea: \blockquote[{\Cite[123]{anscombe1981parmenides:qli}}: \enquote{In natural theology there is attempted reasoning from the objects of the world to something outside the world. Wittgenstein certainly worked and thought in a tradition for which this was impossible}.]{En la teología natural hay un intento de razonamiento desde los objetos del mundo a algo fuera del mundo. Wittgenstein ciertamente trabajó y pensó en una tradición para la cual esto era imposible}.

Anscombe claramente no comparte estas opiniones de Wittgenstein. Tras afirmar que para Ludwig `pensar' significa \enquote*{actuar según las reglas de razonamiento correcto}\footnote{\Cite[131]{anscombe1981parmenides:qli}: \enquote{what one actually does, which is counted as what was meant: \emph{that} is what fixes the meaning: And so it is about following the rules of correct reasoning. One draws the conclusion as one `must'. That is what ``thinking'' means (RFM, I, 131)}.} se pregunta: \blockquote[{\Cite[122]{anscombe1981parmenides:qli}}: \enquote{If so, then what will Wittgenstein say about `illogical' thinking? As I would, that it isn't thinking?}]{Si esto es así, entonces ¿qué diría Wittgenstein sobre el pensamiento `ilógico'? ¿Como diría yo, que no es pensar?} Y continúa: \blockquote[{\Cite[122]{anscombe1981parmenides:qli}}: \enquote{In the Catholic faith, certain beliefs (such as the Trinity, the Incarnation, the Eucharist) are called ``mysteries''; this means at the very least that it is neither possible to demonstrate them nor possible to show once for all that they are not contradictory and absurd. On the other hand contradiction and absurdity is not embraced; ``This can be disproved, but I still believe it'' is not an attitude of faith at all. So ostenisble proofs of absurdity are assumed to be rebuttable, each one in turn}.]{En la fe católica, ciertas creencias (como la Trinidad, la Encarnación, la Eucaristía) son llamadas ``misterios''; esto significa en el mejor de los casos que ni es posible demostrarlas ni tampoco es posible mostrar de una vez por todas que no son contradictorias y absurdas. Por otra parte la contradicción y lo absurdo no son abrazados; ``Esto puede ser refutado, pero aún así lo creo'' no es para nada una actitud de fe. Entonces las ostensibles demostraciones de absurdidad son asumidas como rebatibles, cada una en su turno}. Esta distinción entre no pensar y el misterio es característica de Elizabeth que en diversas ocasiones propone que la capacidad de argumentar está al servicio de disipar los ataques que pretendan demostrar como definitivamente absurdas las proposiciones que expresan misterios. La actitud que acompaña esta perspectiva, estar dispuestos a atender cada crítica, la compartía con Ludwig: \blockquote[{\Cite[122]{anscombe1981parmenides:qli}}: \enquote{Now this process Wittgenstein himself once described: ``You can ward off \emph{each} attack as it comes'' (Personal Conversation)}.]{Ahora, este proceso Wittgenstein mismo lo describió en una ocasión: ``Puedes mantener a raya \emph{cada} ataque según venga'' (Conversación personal)}.

Elizabeth mantiene en sus distintos artículos esa distinción entre el sinsentido o los meros pensamientos ilógicos y lo que puede ser valorado como un misterio. Reconoce su naturaleza extraordinaria: \blockquote[{\Cite[122-123]{anscombe1981parmenides:qli}}: \enquote{religious mysteries are not a theory, the product of reasoning; their source is quite other}.]{los misterios religiosos no son una teoría, el producto del razonamiento; su fuente es totalmente otra}, y sin embargo afirmarlos no va en contra de considerar, como ella lo hace, que hay razonabilidad en la fe: \blockquote[{\Cite[122]{anscombe1981parmenides:qli}}: \enquote{the attitude of one who does that, or wishes that that should be done, is not that of willingness to profess contradiction. On the contrary}.]{la actitud de uno que hace esto, o que desea que eso se haga, no es la de una disposición a profesar la contradicción. Al contrario}.

Todas estas consideraciones nos traen hasta un elemento fundamental para el juego de lenguaje y para la comunicación de la verdad a través del testimonio: \blockquote[{\Cite[\S505; 509]{wittgenstein1969oncertes}}.]{Cuando se sabe alguna cosa es siempre por gracia de la Naturaleza. \textelp{} Lo que en realidad quiero decir es que un juego de lenguaje sólo es posible si se confía en algo\ldots}. La confianza es la actitud que Anscombe tiene hacia la capacidad del lenguaje humano ---y del ser humano mismo--- de expresar y comunicar la Verdad que le trasciende. Su actitud hacia el misterio termina siendo la expresión culminante de esa misma confianza.

En el siguiente apartado seguiremos sacando consecuencias de estas reflexiones. Dejándonos llevar por las preguntas planteadas en el primer capítulo construiremos una visión de conjunto de la reflexión de Anscombe en torno a la categoría de testimonio.
#+END_SRC

 En el contexto de la filosofía de Wittgenstein cuestión ética

  a nosotros nos parece además que se trata de 

  354 mostrar qué actitudes no hacen justicia a la noción de libertad en el hombre que se sigue de su ser \emph{imago Dei}, y cuál sí.

  puesto que 354 Dada la inseparabilidad de la verdad y la libertad, la analogía de la libertad es inseparable de la analogía de la verdad.

  Hay otro aspecto import
  Ya en el \emph{Tractatus} la cuestión de la capacidad del lenguaje para significar y la naturaleza de la verdad aparecen en definitiva como una ``consideración mística''\footnote{Estimamos de gran interés la reflexión de P. Dominguez donde, desde el paradigma antropológico de la analogía teológica, propone que la actitud martirial es la respuesta a esta `consideración mística'; \Cite[357]{dominguez2009at}: \enquote{Cabría decir que ésta es una consideración \emph{mística}. Con místico me refiero, en principio al uso wittgensteniano: ``Nicht wie die Welt ist, ist das Mystische, sondern daß sie ist''. En efecto, a la actitud mística pertenece la persuasión de que la verdad es un tema vital que trasciende, la certeza de que ante ella el ejercicio racional culmina en contemplación. Es, de nuevo, un momento en el que la racionalidad filosófica se pone en busca de otro nivel que la supera: la Revelación. Esta dimensión mística no está lejos de la metafísica, ni de la ética. \textelp{} En consecuencia, la actitud previa que se ha de mantener ante la verdad es, no cabe duda, martirial; sí, testimonial en el sentido cabal de la palabra.}  Sobre esta actitud ante la verdad, véase también: \Cite[354-356]{dominguez2009at}.} que se interesa, más que en una definición de la verdad, en lograr una actitud hacia ella. Esto confiere al \emph{Tractatus} un sentido ético.


Recap:

cap 1, p.5 y 6: es imprescindible repensar el nexo ... razón, afectos y libertad en la relación del hombre con lo real:: este nexo en el lenguaje
mostrar la credibilidad de la fe como asentimiento a una revelación personal en la historia

c. 1 p. 9  aptitud del lenguaje para hablar de forma significativa....

c.1 sec 1.3 p 19 ¿es cognoscitivo el lenguaje relijioso? puede significar? puede comunicar conocimiento?

c2. p. 37 el análisis de ludwig sobre la relación entre la realidad, el lenguaje y el pensamiento no deja de ser un intento de reconocer definitivamente como somos realmente 

c2 p. 38 teología como gramática: de lo que decimos sobre Dios

c. 3 p. 42 dos líneas: descripción de lo que constituye lenguaje significativo y descripción de la naturaleza especial de la creencia que llamamos `fe'

Al comienzo de nuestra investigación, como al comienzo de este capítulo

Podemos tomar de F. Conesa algunas claves para comprender la relación del tema del testimonio y la comprensión del lenguaje dentro de la filosofía analítica.

Conesa 310-311
Las observaciones de L. Wittgenstein a este respecto subrayan la importancia que tiene en el contexto de la fe el aprendizaje del lenguaje. No se trata, sin embargo, de aprender un lenguaje esotérico y distanciado del lenguaje ordinario. Se trata de <<aprender cómo usar el lenguaje con más amplitud. El lenguaje que usa la religión es el mismo que se usa en otros universos de discurso. No es un lenguaje especial sino el mismo lenguaje ordinario al que se da un uso particular>>.

Este lenguaje es aprendido de la Iglesia. Una de las tareas del proceso catequético es precisamente la enseñanza del lenguaje de la fe. La profesora Anscombe subraya esto en un escrito sobre la transubstanciación

311
El fin de este aprendizaje es ---como subraya el texto--- introducirnos en la inteligencia y vida de la fe. /emph{Saber usar} el lenguaje de la fe es una habilidad técnica que ayuda a la fe en su desarrollo y a la vez ayuda a introducirnos en ella.

La fe necesita un lenguaje ya que sólo puede referirse a su objeto mediante símbolos. Por ello el lenguaje no es sólo un modo de comunicación de la fe sino, sobre todo, algo necesario para estructurarse, definirse, identificarse.


#+BEGIN_SRC latex :tangle no
\subsection{From Parmenides to Wittgenstein (1969) y The Question of Linguistic Idealism (1976)}


Una importante clave de interpretación de este artículo se encuentra en el lugar que ocupa como parte de esta colección. El título del volumen no es casual, el primer artículo es dedicado a Parménides, y el último, \emph{The Question of Linguistic Idealism}, es un examen de nociones importantes en la filosofía de Wittgenstein en donde reaparecen temas que Anscombe plantea ya en esta investigación dedicada a las ideas de Parménides. En este sentido, su análisis de los argumentos de Parménides pone en marcha una discusión que atraviesa todos los artículos del volumen. ¿En qué consiste esta discusión que Anscombe juzga presente ya en Parménides y viva todavía en Wittgenstein? En la introducción de la colección la describe diciendo: \blockquote[{\Cite[xi]{anscombe1981parmenides}}: \enquote{At the present day we are often perplexed with enquiries about what makes true, or what something's being thus or so \emph{consists in}; and the answer to this is thought to be an explanation of meaning. If there is no external answer, we are apparently committed to a kind of idealism}.]{En la época actual con frecuencia nos quedamos perplejos con preguntas sobre qué hace a algo verdadero, o \emph{en qué consiste} el que algo sea de un modo u otro; y la respuesta a esto se piensa que es una explicación del significado. Si no hay una respuesta externa, aparentemente estamos comprometidos con un tipo de idealismo}.\label{subsec:intextq}

El argumento parmenidiano también le sirve a Elizabeth para rechazar una confusión heredada por el \emph{Tractatus}. Se trata de un presupuesto que Parmenides tiene en común con Platón: \blockquote[{\Cite[x]{anscombe1981parmenides}}: \enquote{that a significant term is a name of an object which is either expressed or characterized by the term}.]{que un término significativo es el nombre de un objeto que está expresado o caracterizado por el término}. Este presupuesto, propone Anscombe, \blockquote[{\Cite[xi]{anscombe1981parmenides}}: \enquote{is an ancestor of much philosophical theorizing and perplexity}; En el texto continúa dando ejemplos de esta tradición que coinciden con las discusiones que están recogidas en este volumen de la colección: \enquote{In Aristotle \textelp{} the theory of substance and the inherence in substances of individualized forms of properties and relations of various kinds \textelp{} In Descartes \textelp{} the assertion that the descriptive terms which we use to construct even false pictures of the world must themselves stand for realities \textelp{} In Hume \textelp{} the assumption that `an object' corresponds to a term, even such a term as ``a cause'' as it occurs in ``A beginning of existence must have a cause.'' \textelp{} Brentano thinks that the mere predicative connection of terms is an `acknowledgement' \textelp{} Wittgenstein himself in the \emph{Tractatus} has language pinned to reality by its (postulated) simple names, which mean simple objects}.]{es un ancestro de mucha teorización y perplejidad filosófica}.
Esta tradición de \enquote*{teorización y perplejidad} que Anscombe traza culminando en el \emph{Tractatus} hace referencia al modelo de representación que se encuentra criticado en \emph{Investigaciones Filosóficas}. Anscombe nota en el argumento de Parménides un germen de la tradición subyacente a la conexión a priori entre el lenguaje y la realidad que aparece en el \emph{Tractatus}.

Esta preocupación de la época, aludida por Anscombe, tiene una presencia importante en \emph{Investigaciones Filosóficas}. Las \S\S428-465, en donde Wittgenstein se detiene a reflexionar sobre la intencionalidad, contienen implícitamente una crítica a ese modo de concebir el pensamiento, el lenguaje, la realidad y sus relaciones que sirvió para orientar las ideas del \emph{Tractatus}; específicamente son atacados: \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{the underlying assumptions that characterize the whole tradition of philosophical reflection of which it was the culmination}.]{los presupuestos subyacentes que han caracterizado toda la tradición de reflexión filosófica de la cual \textelp{el \emph{Tractatus}} fue la culminación}. Entre estos presupuestos se cuestiona enfáticamente \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{the venerable idea that the meaning of signs, their capacity to represent what they represent, is parasitic upon thought, upon mental processes of thinking and meaning}.]{la venerable idea de que el significar de los signos, su capacidad para representar lo que representan, depende del pensamiento, de procesos mentales de pensar y significar}. Esta idea, juzga Wittgenstein, es un producto de la concepción de los pensamientos como representación. Sobre los pensamientos así concebidos ha girado cierta discusión en la que se ha debatido acerca de qué es lo que constituye los pensamientos. Así: \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{the empiricists characteristically held them to be mental images or ideas; others, like the author of the \emph{Tractatus}, were more reticent, content to leave the matter to future psychological discovery, insisting only that thought-constituents must stand to reality in the same sort of relation as words}.]{los empiristas característicamente sostenían que estos eran imágenes mentales o ideas; otros, como el autor del \emph{Tractatus}, fueron más reticentes, contentándose con dejar el asunto al futuro descubrimiento psicológico, insistiendo solamente en que los constituyentes de pensamiento tienen que tener, respecto de la realidad, el mismo tipo de relación que las palabras}.

Dentro de este debate, la intencionalidad de los pensamientos, ---y aquí `pensamientos' pueden ser creencias, expectativas, esperanzas, temores, dudas, deseos, etc.--- era explicada también de modos distintos por los empiristas y por el autor del \emph{Tractatus}. Los primeros sosteniendo que la relación entre un pensamiento y la realidad correspondiente con este es externa, y el segundo que la relación es interna. La posibilidad de esta relación interna aparece explicada en el \emph{Tractatus}: \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{in terms of a pre-established metaphysical harmony between thought and reality. This harmony was conceived to consist in an essential isomorphism between representation and what is represented, wether truly or falsely}.]{en términos de una armonía metafísica preestablecida entre el pensamiento y la realidad. Esta armonía fue concebida como consistiendo en un isomorfismo esencial entre la representación y lo que es representado, ya sea verdadera como falsamente}. La concepción empirista \blockquote[{\Cite[3]{hacker2000mind}}: \enquote{attempted to explain the intentionality of thought in causal terms \textelp{} construing the relation between thought and reality (between belief and what makes it true, or between desire and what fulfills it) as external}.]{intentó explicar la intencionalidad del pensamiento en términos causales \textelp{} interpretando la relación entre pensamiento y realidad (entre el creer y lo que lo hace verdadero, o entre el deseo y lo que lo realiza) como externa}. En \emph{Investigaciones Filosóficas} se critican estas dos posturas aunque se mantiene la idea de que la relación entre pensamiento y realidad es interna.

La consideración de que la relación entre lo que se cree y lo que hace esta creencia verdadera es una relación interna representa una dificultad adicional: \blockquote[{\Cite[4]{hacker2000mind}}: \enquote{for what we mean when we say that such-and-such is the case does not stop short of the fact that makes what we say true. We mean that very fact, and not something that stands in some relation (e.g. of correspondence) to it. We, as it were, reach right up to it. On the other hand, we can think what is \emph{not} the case. But if it is not the case, then it seems that there is nothing to reach right up to. Yet what we think when we think what is the case and what we think when we think what is not the case are not intrinsically different. How is this possible? The \emph{Tractatus} resolved the difficulty by arguing that what we think is the sense of a sentence, which is a \emph{possible} state of affairs, actual if what we think is the case and unactualized if what we think is not the case. For this a complex metaphysics and ontology and an elaborate doctrine of the depth grammar of all possible languages were introduced.}]{pues lo que significamos cuando decimos que alguna cosa es de hecho no se queda detenido ante el hecho que hace que lo que decimos sea verdadero. Significamos el mismo hecho y no algo que está situado en relación alguna (de correspondencia por ejemplo) con este. Nosotros, podría decirse, lo tenemos al alcance. Por otra parte, podemos pensar lo que \emph{no} es de hecho. Pero si no es de hecho, entonces parece que no hay nada para alcanzar. Sin embargo lo que pensamos cuando pensamos lo que es de hecho y lo que pensamos cuando pensamos lo que no es de hecho no es intrínsecamente distinto. ¿Cómo es esto posible? El \emph{Tractatus} resolvió la dificultad argumentando que lo que pensamos es el sentido de una oración, que es un \emph{posible} estado de las cosas, actual si lo que pensamos es de hecho y no actualizado si lo que pensamos no es de hecho. Para esto se introdujo una compleja metafísica y ontología y una elaborada doctrina sobre la gramática profunda de todos los lenguajes.}



#+END_SRC
