* Hume and Julius Caesar
** Reference
*** Treatise of Human Nature
  - SECTION IV. Of the component parts of our reasonings concerning cause and effect.

  Tho’ the mind in its reasonings from causes or effects carries its view beyond those
  objects, which it sees or remembers, it must never lose sight of them entirely, nor
  reason merely upon its own ideas, without some mixture of impressions, or at least of
  ideas of the memory, which are equivalent to impressions. *When we infer effects from
  causes, we must establish the existence of these causes; which we have only two ways
  of doing, either by an immediate perception of our memory or senses, or by an
  inference from other causes; which causes again we must ascertain in the same manner,
  either by a present impression, or by an inference from their causes, and so on, till
  we arrive at some object, which we see or remember.* ’Tis impossible for us to carry
  on our inferences in infinitum; and the only thing, that can stop them, is an
  impression of the memory or senses, beyond which there is no room for doubt or
  enquiry.

  To give an instance of this, we may chuse any point of history, and consider for what
  reason we either believe or reject it. Thus we believe that Cæsar was kill’d in the
  senate-house on the ides of March; and that because this fact is establish’d on the
  unanimous testimony of historians, who agree to assign this precise time and place to
  that event. Here are certain characters and letters present either to our memory or
  senses; which characters we likewise remember to have been us’d as the signs of
  certain ideas; and these ideas were either in the minds of such as were immediately
  present at that action, and receiv’d the ideas directly from its existence; or they
  were deriv’d from the testimony of others, and that again from another testimony, by
  a visible gradation, ’till we arrive at those who were eye-witnesses and spectators
  of the event. ’Tis obvious all this chain of argument or connexion of causes and
  effects, is at first founded on those characters or letters, which are seen or
  remember’d, and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain wou’d
  in that case hang upon another; but there wou’d not be any thing fix’d to one end of
  it, capable of sustaining the whole; and consequently there wou’d be no belief nor
  evidence. And this actually is the case with all hypothetical arguments, or
  reasonings upon a supposition; there being in them, neither any present impression,
  nor belief of a real existence.

  I need not observe, that ’tis no just objection to the present doctrine, that we can
  reason upon our past conclusions or principles, without having recourse to those
  impressions, from which they first arose. For even supposing these impressions shou’d
  be entirely effac’d from the memory, the conviction they produc’d may still remain;
  and ’tis equally true, that all reasonings concerning causes and effects are
  originally deriv’d from some impression; in the same manner, as the assurance of a
  demonstration proceeds always from a comparison of ideas, tho’ it may continue after
  the comparison is forgot.


  - SECTION IX. Of the effects of other relations and other habits.
  ... No weakness of human nature is more universal and conspicuous than what we
  commonly call Credulity, or a too easy faith in the testimony of others; and this
  weakness is also very naturally accounted for from the influence of resemblance. When
  we receive any matter of fact upon human testimony, our faith arises from the very
  same origin as our inferences from causes to effects, and from effects to causes; nor
  is there any thing but our experience of the governing principles of human nature,
  which can give us any assurance of the veracity of men. But tho’ experience be the
  true standard of this, as well as of all other judgments, we seldom regulate
  ourselves entirely by it; but have a remarkable propensity to believe whatever is
  reported, even concerning apparitions, enchantments, and prodigies, however contrary
  to daily experience and observation
** Outline
*** Topic: belief in matters outside our own experience and memory
*** Argument:
*** Ilustration: Caesar


** Anscombe
To my mind the interest of Hume lies primarily in the problems he consciously or
unconsciously discovers to us. Here there is a problem unconsciously raised. For Hume
judges that we believe Caesar was killed in the Senate House from the testimony of
historians. (Is that testimony?) And he thinks that this belief is explained as our
reasoning from our perception of ‘certain characters and letters’, through successive
steps referring to intermediate records, back to the perception of eyewitnesses and
through that to the event. He supposes that the record before our eyes is our reason
for believing in the intermediate records, which are in turn our reason for believing
in the eyewitness report, which in turn is our reason for believing in the original
event. He must suppose this, otherwise it would not be possible for him, however
confusedly, to cite the chain of record back to the eyewitnesses as an illustration of
the chain of causes and effects with which we cannot run up in infinitum, but must
eventually bring to an end with our present perception or memory of written documents.
But it is not like this at all. If the written records that we see are our grounds for
belief, they are first and foremost grounds for belief in the original event, and then
our belief in the original event is a ground for belief in the intermediate
transmission. For let us ask: why do we believe there were eyewitnesses? Certainly
because we believe that the event happened. Therefore the belief in the event is not
based on belief that there were eyewitnesses. I have heard that the Rabbis hold that
the six hundred thousand witnesses to the crossing of the Red Sea must be credited;
600,000 witnesses—that is very sure witness! And now let us ask: why do they believe
there were 600,000? Because they believe 600,000 passed through.



The interesting problem that arises, then, is why the things we are told and the
writings that we see are the starting points for our belief in the far distant events
and so in the intermediate chain of record. This is a question of vast importance. But
the consideration of it would take us far away from that investigation of Hume on cause
which has been our present business. I take it as sufficiently demonstrated that Hume’s
account is wrong. (One may be convinced of that without thinking that one has an
alternative account.)

That assertion can have the function or purpose ascribed to it by Anselm (see above, p.
196)—i.e. that there can be such a thing as assertion—depends on the empirical fact,
among others, that people don’t generally reject their earlier assertions as unfounded.
It is ‘by favour of Nature’ that assertion and knowledge are possible (On Certainty,
para. 505); for Anselm and for Anscombe, it is (also) by the grace of God.
Wittgenstein’s views are subtle and complex, and it is important that one not reduce
them to a formula or two. I have mentioned ‘immovable foundations’ and
‘world-pictures’; but what Wittgenstein has to say about certainty, doubt,
disagreement, and so on encompasses more than these. As Anscombe warns us, we should
not regard the struggling investigations of On Certainty as all saying the same thing.
Doubts whether this is a tree or whether his name was L.W. or whether the world has
existed a long time or whether the kettle will heat on the fire or whether he had never
been to the moon are themselves not all subjected to the same treatment. Not all these
things, for example, are part of a ‘world-picture’. And a world-picture is not the same
thing as a religious belief, even though to believe is not in either case to surmise.
(QLI, 130)

** Rundown

    Intro:

    what's the justification for our beliefs falling outside our own experience
    and memory?

    if we take a belief in a historical matter of fact, the answer is: inference
    from the relation of cause and effect.

    1. Anscombe: that's not it

  because it is not belief in historical facts by inference
  but
  it is on the whole
  belief that there has been
  a chain of tradition of reports and records going back to contemporary knowledge


  2.Then what can be said about it?

  let's say that belief in the existence of julius caesar is not a belief that is
  justified by evidence that could be negated by some new single document or
  inscription

  let's ask: what could be evidence of Caesar never existing?
  what would we think
  of an inscription

  what would judge what here?

    A general epistemological reason for doubting one will be a reason for
    doubting all, and then none of them would have anything to test it by.

    So it turns out when I say things like “Here is a hand” I’m not really making
    a claim about the world, I’m laying down some rules for discussion.

      We know it from being taught; not just from explicit teaching, but by its being
      implicit in a lot else that we are taught explicitly. But it is very difficult
      to characterize the peculiar solidity involved or its limits. p. 90

      the killing of Caesar is something which exists in our culture with a
      particular logical status of one kind of certainty**

      [this kind of knowledge] could only be called in question only by indulging
      in Cartesian doubt


      not everything can be put up for checking

      she continues this in grounds of belief.....

      what is the justification or grounds for the belief

** notes
Section IV part III of Book I of the treatise

Topic: belief in matters falling outside our own experience and memory

when infering effects from causes
we must establish the existence of these causes
either by:

inmediate perception of our memory or senses

or by

 an inference from other causes

these other causes must be ascertained in the same manner

it is impossible to carry on our inferences in infinitum

Hume tries to ilustrate this by an example of historical belief

we believe that caesar was killed....

it is obvious all this chain of argument or connexion of causes and effects is at first
founded on those characters or letters which are seen or remembered

But this is not infering effects from causes, it is infering causes from effects.

As such, for an historical belief we must have to be saying
when we infer effects from causes or causes from effects...

when we infer causes from effects we must establish the existence of those effects
either by perception or by inference from other effects which effects we must ascertain
in the same manner by a present impression or by an inference from their effects and so
on, until we arrive at an object which we see or remember



For Hume the relation of cause and effect is the one bridge by which to reach belief in
matters beyond our present impressions or memories

and also cause and effect are inferentially symmetrical

are they?

what is the starting point? (the start of inference or the start of the justification
chain)

The historical example is an inference of the original cause, the killing of Caesar,
from its remote effect, the present perception of certain characters or letters.

The starting-point is the present perception, and from it we can run through a chain of
effects of causes which are effects of causes to the original cause: the killing of
Caesar

the end of the chain is thus not our perception and so it doesn't serve as an
impression of our memory or senses beyond which there is no room for doubt or enquiry
as to stop us going infinitely

"tis impossible for us to carry on our inference in infinitum" means: *the
justification of the grounds of our inferences cannot go on in infinitum* *we must come
to belief which we do not base on grounds*

What Hume is arguing is that we not only have a perception starting point but that we
must reach a starting point in the justification of these inferences

for him tracing back (from effects to causes) is taken to be symmetrical to inferences
from causes to effects

it must be purely hypothetical inference

we reason (purely hypothetically) if Caesar was killed, then there were witnesses , if
there were witnesses then there was testimonies, then there were records made from
them, if there were records made then there are characters and letters to be seen which
say that Caesar was Killed

Four parts of Hume's thesis:

1. a chain of reasons for a belief must terminate in something that is believed without
   being founded on anything else
2. the ultimate belief must be of a quite different character from derived beliefs: it
   must be perceptual belief, belief in something perceived, or presently remembered
3. the immediate justification for a belief p, if the belief is not a perception, will
   be another belief q, which follows from, just as much as it implies, p.
4. we believe by inference through the links in a chain of record

implicit corollary: when we believe in historical information belonging to the remote
past, we believe that there has been a chain of record

Hume must believe all this

*But it is not like that!*


If the written records that we now see are grounds of our belief, they are first and
foremost

*grounds for belief*
in Caesar's killing,
belief that the assasination is a solid bit of history

THEN

our belief in that original event IS A GROUND FOR BELIEF in

much of the intermediate transmission <-



belief in recorded history is on the whole a belief that there has been a chain of
tradition of reports and records going back to contemporary knowledge;

IT IS NOT A BELIEF IN THE HISTORICAL FACTS BY AN INFERENCE THAT PASSES THROUGH THE
LINKS OF SUCH A CHAIN. AT MOST, THAT CAN VERY SELDOM BE THE CASE.

Casting a doubt about Caesar's existence would put us in a vacuum in which there is
nothing by which to judge anything else

What would I be allowed to count as evidence then?

PEOPLE IN HISTORY ARE NOT IN ANY CASE HYPOTHESES WHICH WE HAVE ARRIVED AT TO EXPLAIN
CERTAIN PHENOMENA

A general epistemological reason for duobting one will be a reason for doubting all,
and then none of them would have anythin to test it by
