* Propecy and Miracles
** Síntesis de lo que Anscombe hace:
Elizabeth introduce su discusión ofreciendo tres documentos que ser- virán como los
ejes principales de su análisis:

Tras esta introducción, Anscombe comienza su análisis desenmara- ñando algunos puntos
de los argumentos del ensayo de Lessing.

!!!Falta el primero!
En una de sus premisas emplea como ejemplo de verdad histórica nuestra creencia en que
hubo en el pasado una persona llamada Alejandro, q...


Otro punto destacado por Anscombe es que la posición de Lessing ante el cristianismo es
incompatible con las creencias cristianas. Una de sus analogías ilustra bien esta
actitud:

Una aclaración adicional que Anscombe propone es que, a su juicio, Lessing exagera la
certidumbre que (desde un punto de vista externo) po- dría tener Orígenes de los
milagros y profecías cumplidas

Hechas estas consideraciones preliminares, Anscombe estudia el ar- gumento central
establecido por Lessing.

El análisis de Anscombe se desarrollará en torno a la posibilidad de sostener creencias
ciertas teniendo como fundamento los informes de mila- gros; o la certeza de los
relatos históricos; o las profecías cumplidas que pue- dan ser consideradas claras por
su antigüedad, prioridad y realización.

En cuanto a los informes de milagros, Anscombe sostiene con Lessing
que estos no apelarían a un juez que sea externo a las creencias religiosas.

En donde Elizabeth estima que Lessing no tiene razón es en decir
que ninguna certeza histórica puede ser suficientemente fuerte como para te-
ner un peso absoluto.

Tras estos análisis sobre las noticias de milagros y la fuerza de la cer-
teza histórica, Anscombe dirige su discusión hacia las profecías. En el centro
de su reflexión está el requisito propuesto por Lessing:

Las conclusiones a las que Anscombe llega después de su análisis pueden resumirse en
dos cuestiones. En primer lugar se enfoca en el con- traste entre dos posiciones desde
las que una persona podría acercarse al argumento de las profecías y milagros

La segunda cuestión que Anscombe propone como conclusión tiene que ver con la noción
misma de la atestación divina.

Anscombe termina haciendo una distinción; quizás podemos actuar según la profecía

***** profecías
ancientness
historical certainty of this is good as any

priority
the trouble with prophecies with a definite sense is that their priority is
hardly known with certainty

isaiah's prophecy about babylon is an example of priority and fulfilment with
absolute certainty

priority because it did not become desolate til after the establishment of
seleucia

and certainty because it's very explicit

fulfilment


Prophecies whose ancientness, priority and fukfikmnet are really clear and
certain to a quite detached observer are necessarily few

This because of something Lessing says elsewhere

can't the applicability of the alleged prophecy be an accident?

there are however special difficulties about the notion of an accidental
applicability

first: it isn't the same to check if someone said something about the past
accidentally and someone saying something about the future

someone who believes in a possibility of precognition comparable to memory is
thereby rendered incapable of understanding the nature of prophecy at alleged

the check imposed by Lessing severely restricts possible prophecy


...these considerations result in an interesting point: the critical principle
that prophetical writings must have been clearly intelligible in their own times
is itself a denial of the possibilityof all but prophecy of a very restricted
type

that is to say for almost all prophecies, to see them fulfilled is to interpret them

this is because of the difference between past and future

to ask whether a prophet had these events in mind is senseless

all we can do is

check for one of 2 cases:

the prophet, professing to prophesy utters words which have a natural
application, considering context, to the events we think they prophesied

cases where all that can be said is that one can see how someone might apply
those words, ripped out of context and taken by themselves to this event


but why should one be impressed by prophecy at all?

a prophecy fulfilled, or a miracle done is supposed to attest something


another way in it can be accidental is that we do not allow this to be prophecy,
as it doesn't have a theological sense
***** general
  El análisis de Anscombe en torno al argumento de Lessing toca varios puntos

  Principalmente sostiene que Lessing tiene razón cuando propone que

  Luego sobre staking beliefs on the strenght of historical certainty
  hay una clase de aserciones históricas que sería absurdo atribuirles certeza
  pero ya pasó el tiempo en que podría disprove them

  Luego sobre las profecías....
  Sticking with things thar are absolutely solid.....

  it is solid that it was anciently written down as prophecy
  that Jerusalem.....
  If lessing tells me i know the ancientness only historically i can reply that
  this sort of certainty is good enough as any

  NOW prophecies..... whose ancientness, priority and fulfulment are really clear
  to a detched observer ar necessarily few
  this is because Lessing puts up a condition.... we have to judge that the thing
  that happened, not mere was describable in the words occurring in the
  prediction, but was what was predicted

  but there are special difficulties about the notion of the applicability of
  prophetical words as accidental

  two points anscombe makes here:

  to see a prophecy fulfiled is to interpret them
  a prophecy fulfilled or a miracle done have to attest something

  something else about what can it mean for prophecy to be fulfiled

  this is the very sort of thing for that man, or these men, to have said;

  Puesto así parece fuerte
  Está en conflicto con la afirmación del Vaticano
  Su argumento es valioso pq no confunde el problema atacando la verdad de los
  milagros o cumplimientos de profecias documentados

  es de interés extraordinario lo que dice dei filius pq
  creemos en profecias cumplidas y milagros porque creemos la religion católica
  y estos forman parte de nuestras doctrinas

  además
  el pasaje del deut, junto con reflexión razonable en los requisistos de la fe
  nos inclinarían a decir que un profeta o milagrero debe ser juzgado a la luz de
  la fe cristiana (no la fe cristiana a la luz de las profecias y milagros)

  si son argumentos externos entonces parece que deberian quedar establecidos como
  tal antes de que quede introducida la creencia en el cristianismo:
  pero no hay un elemento teológico en llamar algo una profecía cumplida, e
  incluso, un milagro?

  Hay que conceder a Lessing que los informes de milagros

  Ahora profecias cuya antiguedad, prioridad y cumplimiento sean verdaderamente
  claras y ciertas para un observador imparcial son necesariamente pocas....

  Un monton de pasajes suenan como profecias para Crisitanos creyentes o Judios
  piadosos, pero suenan como afirmaciones misteriosas de textos antiguos para
  cualquier otra persona

  puede ser un accidente el cumplimiento de una profecia?

  es juzgada como profecia una afirmación que simplemente puede ser aplicada a
  hechos futuros?

  hay algunas dificultades sobre la noción de la aplicabilidad de palabras
  proféticas como accidentales

  para casi todas las profecias, verlas cumplidas es interpretarlas e
  interpretarlas no es preguntarse si el profeta tenia en mente estos eventos...

  sino que lo que podemos hacer es considerar las ocasiones en las que el profeta
  profesando profetizar afirmó estas palabras y valorar lo que dijo considerando
  todo su contexto, a los eventos que pensamos que estas palabras profetizaron

  la pregunta surge, por qué deberiamos impresionarnos del todo con las profecias?
  por qué nos deberían interesar?

  Una profecía o milagro se supone que atesta algo

  Hay un sentido del término accidental distinto al que Lessin emplea

  Las partes son: preámbulo...
  discusión del argumento central....
  -> a quién pueden decirle algo las profecias cumplidas o los milagros, para
  quién son argumentos externos? para un observador imparcial que por primera vez
  quiere conocer justo lo que la fe enseña?

  I have contended miracles cannot possibly be accepted as certainly true
  ocurrences by the indifferent historian

  their role is this: \blockquote[if one is seriously entertaining the truth of
  the whole revelation in the way I have hinted at, the miracles are consonant.
  That God attested Christ by miracles is possible, if Christ is Christ ---i.e. is
  the Messiah promised in the Old Testament. Then the problem, how on earth these
  seemingly factual records came to be written, of such incredible things, is
  resolved by the hypothesis that they happened.]{si estamos considerando
    seriamente la verdad de toda la revelación en el modo al que he aludido, los
    milagros son consonos. Que Dios atestó a Cristo por medio de los milagros es
    posible, si Cristo es Cristo ---esto es, es el Mesías prometido en el Antiguo
    Testamento. Entonces el problema, sobre cómo es posible que estas crónicas
    supuestamente fácticas han llegado a quedar escritas, de unos eventos tan
    increíbles, se resuleve por la hipótesis de que sí ocurrieron.}

  Un historiador indiferente puede dejar sin resolver la pregunta, ¿sí ocurrieron,
  qué características esperaríamos que tengan los documentos donde quedan
  relatados? Y si ocurrieron, acaso no apoyan la enseñanza?

  Pero y es posible del todo la atestación divina?

  El hecho de que alguien de muestras de hacer cosas milagrosas o que diga
  profecias que se cumplen, ciertamente no muestran que esté atestado divinamente.

  Según veo, tiene que haber una tesis de teología natural, como podría llamarla,
  de que si alguien realiza `una señal y un prodigio' o dice una profecía que se
  cumple, en el nombre de Dios, entonces está atestado divinamente. Ahora en qué
  descansa esto? Puede descansar en fe.

  Las enseñanzas de los profetas deben ser primero tales que pudieran
  razonablemente entendidas como perteneciendo a la verdad revelada por Moisés;
  solo si esto es así entonces es posible proponer la pregunta. Entonces, si
  predice algo y esto ocurre, y si no intenta conducirles a la idolatría después
  de esto, entonces está atestado.

  Esto podría entenderse como matería de fe. Pero si eso que constituye atestación
  divina sólo es conocido por la fe, entonces en qué quedan los `solidos
  argumentos externos' de la constitución del Vaticano?

  Pienso entonces que el argumento más bien tiene que se que si un profeta que
  aparentemente está enseñando la verdad, se atreve a predecir algo contingente,
  entonces esto es presunción suya si no es el caso que lo ha recibido de Dios y
  debe decirlo. Ahora si enseña una mentira inmediatamente después, o si lo que ha
  dicho no ocurre, entonces queda demostrado presuntuoso. Pero si no es demostrado
  presuntuoso, entonces no debemos atrevernos a no creerle u obedecerle: mientras
  que lo que dice no entre en conflicto con la verdad conocida.


  -> los argumentos de profecias y milagros tienen peso para alguien que haya
  atendido a las enseñanzas del AT

  Ahora, si todo esto es así, el observador imparcial e indiferente queda
  confrontado ciertamente solo por algunas profecias dispersas relacionadas con
  ciudades y personas; y con \emph{informes} de milagros y de cumplimientos de
  profecias los cuales es absurdo pretender que deba tener en cuenta como
  ciertamente ciertos.
  Que pasa entonces con los solidos argumentos externos de la constitución?

  Esbozaré mi respuesta brevemente: Sólo si un hombre queda impresionado por el
  Antiguo Testamento, al punto de sentirse inclinado a tomarlo como su maestro,
  tiene entonces el argumento desde profecias y milagros algún peso serio.

  En prophecy and miracles Anscombe destaca la propuesta de Vaticano I acerca de los
  argumentos externos.
  Al tener esto en cuenta, lanza la pregunta: Esto podría ser tomado como materia de fe,
  ¿Pero si aquello que constituye atestación divina puede ser conocido solo por la fe, en
  que queda lo que dice el concilio?

  lo primero es que un "historiador apático" no podría aceptar el rol de los milagros
  como hechos ciertamente verdaderos, no sería razonable pedir al historiador apático que
  resuelva el problema de cómo han llegado a quedar escritos estos relatos.

  Una persona que haya tomado como maestro el AT, para alguien así sí que tendría peso
  las profecías cumplidas o los milagros

  Para Anscombe debe haber una tesis de teología natural que afirme qué implica que una
  persona está divinamente atestada

  Esta tesis no tiene que ser materia de fe

  El argumento puede ser que si no queda probado presuntuoso entonces no podriamos no
  obedecerle

  pero no basta un motivo negativo

  puede uno creer porque no tiene signos de que este hombre sea presuntuoso?
  y entonces hay que considerar que una de dos o es presuntuoso o lo que dice viene de
  Dios? y entonces como no hay signos de que sea presuntuoso, pues viene de Dios?

  Seguramente querríamos razones positivas para creer, y no meramente ausencia de razón
  positiva para descreer?

  Esto, me parece, es correcto, y va con la tesis de que en cierto sentido no puede haber
  un profeta con una nueva doctrina.

  Con estas cosas y lo que dice en 'faith' se podría construir una descripción de lo que
  Anscombe considera como atestación divina



- Preamble, before considering Lessing's central argument

- His argument boils down to: 'But these things may not be true, so how can I use them
  to support Christianity?'
- Miracles and fulfilled prophecies are said to offer solid external arguments for the
  truth of christianity, but isn't there a theological element in calling something a
  fulfilled prophecy or miracle?
- Lessing seems right in saying that the reports of miracles could not be expected to
  appeal to an external judge
- Lessing seems to be wrong in saying that 'no historical certainty can be strong enough
  to be absolute'
  + If it is strength of certainty that is really in question
    - it is not true that historical certainty is always too weak to base absolute
      certainty upon it
      + Probability may come in regarding an historical truth, but it doesn't begin to
        come in at the start
      + Anscombe objects to Lessing's lumping together everything historical as of
        inferior certainty to our own experience
    - That Christ claimed to be the Son of God and that he rose from the dead belongs
      to a class of historical assertions which it would be absurd to claim certainty
      for, but the time for disproving which is past.
    - What would be solid in this fashion is that Christ existed, preached, like an Old
      Testament prophet, and was at least ostensibly crucified under Roman authority;
      and that believers took him for the Messiah and the son of God, and believed he
      had risen from the dead
  + If we stick to things that are solid, and avoid what may be regarded as accidential
  + Lessing disputes priority and certainty
- The critical principle that prophetical wriings must have been clealy intelligible in
  their own time is itself a denial of the possibility of all but prophecy of a very
  restricted type
  + That is to say: for almost all prophecies, to see them fulfilled is to interpret
    them
- Prophecies must attest something
- If all this is so, the impartial indifferent observer is confronted quite certainly
  only with a few scattered prophecies relating to cities and peoples; and with reports
  of miracles and of fulfilments of prophecies which it is absurd to pretend he must
  regard as certainly true.
  - So what becomes of the 'solid external arguments'?
- Only if a man is impressed by the Old Testament, to the extent of being inclined to
  take it as his teacher, has the argument from prophecies and miracles any serious
  weight.
- When St. Agustine said that fulfilment of the prophecies in Christ was the greates
  proof of his divinity, what he said was true; but the proof requires a very special
  position on the part of someone who is to consider it.
  - This is why the kind of apologetic that Lessing argued against, which did not
    assume that position, was so vulnerable and stupid.
- The miracles are consonant, That God attested Christ by miracles is possible, if he
  is the Messiah promised in the Old Testament.
  - The problem about how these seemingly factual records came to be written, of such
    incredible things, is resolved by the hypothesis that they happened.
- With this we come to the problem of the notion of divine attestation at all.
  - There has to be a thesis of natural theology, that if someone works 'a sign and a
    wonder' or utters a prophecy which gets fulfilled, in God's name, then he is
    divinely attested.
  - This might be taken as a matter of faith, but then, what about the 'solid external
    arguments'?
  - I think the argument must be rather that if a prophet who is apparently teaching
    that truth, dares to foretell something contingent, then this is presumption of him
    unless he has it from God and must say it. Now if he teaches a lie straight away
    afterwards, or if the thing does not happen, then he is proved presumptuous. But if
    he is not proved presumptuous, then we ought not to dare not to believe and obey
    him: so long as what he says does not conflict with the known truth.


So far as I can see there has to be a *thesis of natural theology*, as I might call it,
that if someone works ‘a sign and a wonder’ or utters a prophecy which gets fulfilled,
in God’s name, then he is divinely attested. Now what does this rest on? It might rest
on faith. In Deuteronomy, when the Jews were forbidden to consult soothsayers and
necromancers, and omens, they were promised prophets ‘like Moses’ whom they were to
attend to instead. But, the passage goes on, they’ll want to know how to tell a
prophet. And the answer is: if the prophet foretells something, and it doesn’t happen,
then that was just his presumption. The implication seems to be that if a prophet of
their people, apparently teaching according to the Law, foretells something and it does
happen, he is attested.


p. 37 Now what does this rest on? It might rest on faith. In Deuteronomy, when the Jews
were forbidden to consult soothsayers and necromancers, and omens, they were promised
prophets ‘like Moses’ whom they were to attend to instead.






37: el rol de los milagros que he sostenido que no pueden ser aceptados como
hechos ciertamente verdaderos por un historiador indiferente, me parece que es:
si alguien está seriamente considerando la verdad de toda la revelación en el
modo que he descrito, los milagros son consonos.


Luego dei filius

So far as I can see there has to be a thesis of natural theology... that someone
is divinely attested

what does this rest on? it might rest on faith



El análisis de Anscombe examina cuatro dimensiones del argumento de Lessing. Los
milagros, la certeza histórica como fundamento de las creencias, las profecías y
a quién pueden apelar estos argumentos externos que son los milagros y las
profecías (o si estas pueden apelar a un juez externo o historiador apático)




* Parmenides, Mystery and Contradiction
Teichmann 193: Another theme of the Tractatus which Anscombe always took very
seriously was that of the relationship between thinlability and possibility...
It is characteristic of Anscombe to have drawn such diverse figures as
parmenides, plato, hume and Wittgenstein into a single discussion. In the
Introduction to FPW, she writes: ... it was left to the moderns to deduce... but
the ancients had the better approach... as the tractatus puts it...

211: but for there to be a belief, you would need to be able, at least in
principle, to state that belief clearly and without contradiction?

In Parmenides, Mystery and Contradiction, Anscombe considers the view that can
be grasped in thought amounts to can be presented in a sentence which can be
seen to have an unexceptionable non-contradictory sense.

* Hume and Julius Caesar
** Reference
*** Treatise of Human Nature
  - SECTION IV. Of the component parts of our reasonings concerning cause and effect.

  Tho’ the mind in its reasonings from causes or effects carries its view beyond those
  objects, which it sees or remembers, it must never lose sight of them entirely, nor
  reason merely upon its own ideas, without some mixture of impressions, or at least of
  ideas of the memory, which are equivalent to impressions. *When we infer effects from
  causes, we must establish the existence of these causes; which we have only two ways
  of doing, either by an immediate perception of our memory or senses, or by an
  inference from other causes; which causes again we must ascertain in the same manner,
  either by a present impression, or by an inference from their causes, and so on, till
  we arrive at some object, which we see or remember.* ’Tis impossible for us to carry
  on our inferences in infinitum; and the only thing, that can stop them, is an
  impression of the memory or senses, beyond which there is no room for doubt or
  enquiry.

  To give an instance of this, we may chuse any point of history, and consider for what
  reason we either believe or reject it. Thus we believe that Cæsar was kill’d in the
  senate-house on the ides of March; and that because this fact is establish’d on the
  unanimous testimony of historians, who agree to assign this precise time and place to
  that event. Here are certain characters and letters present either to our memory or
  senses; which characters we likewise remember to have been us’d as the signs of
  certain ideas; and these ideas were either in the minds of such as were immediately
  present at that action, and receiv’d the ideas directly from its existence; or they
  were deriv’d from the testimony of others, and that again from another testimony, by
  a visible gradation, ’till we arrive at those who were eye-witnesses and spectators
  of the event. ’Tis obvious all this chain of argument or connexion of causes and
  effects, is at first founded on those characters or letters, which are seen or
  remember’d, and that without the authority either of the memory or senses our whole
  reasoning wou’d be chimerical and without foundation. Every link of the chain wou’d
  in that case hang upon another; but there wou’d not be any thing fix’d to one end of
  it, capable of sustaining the whole; and consequently there wou’d be no belief nor
  evidence. And this actually is the case with all hypothetical arguments, or
  reasonings upon a supposition; there being in them, neither any present impression,
  nor belief of a real existence.

  I need not observe, that ’tis no just objection to the present doctrine, that we can
  reason upon our past conclusions or principles, without having recourse to those
  impressions, from which they first arose. For even supposing these impressions shou’d
  be entirely effac’d from the memory, the conviction they produc’d may still remain;
  and ’tis equally true, that all reasonings concerning causes and effects are
  originally deriv’d from some impression; in the same manner, as the assurance of a
  demonstration proceeds always from a comparison of ideas, tho’ it may continue after
  the comparison is forgot.


  - SECTION IX. Of the effects of other relations and other habits.
  ... No weakness of human nature is more universal and conspicuous than what we
  commonly call Credulity, or a too easy faith in the testimony of others; and this
  weakness is also very naturally accounted for from the influence of resemblance. When
  we receive any matter of fact upon human testimony, our faith arises from the very
  same origin as our inferences from causes to effects, and from effects to causes; nor
  is there any thing but our experience of the governing principles of human nature,
  which can give us any assurance of the veracity of men. But tho’ experience be the
  true standard of this, as well as of all other judgments, we seldom regulate
  ourselves entirely by it; but have a remarkable propensity to believe whatever is
  reported, even concerning apparitions, enchantments, and prodigies, however contrary
  to daily experience and observation
*** On Certainty
8. The ditference between the concept of 'knowing' and the concept of 'being certain'
   isn't of any great importance at all, except where "I know" is meant to mean: I
   can't be wrong. In a law-court, for example, "I am certain" could replace "I know"
   in every piece of testimony. We might even imagine its being forbidden to say "I
   know" there. [A passage in WiZheZm Meister, where "You know" or "You knew" is used
   in the sense "You were certain", the facts being different from what he knew.]

12. -For "I know" seems to describe a state of affairs which guarantees what is known,
    guarantees it as a fact. One always forgets the expression "I thought I knew".

13. For it is not as though the proposition "It is so" could be inferred from someone
    else's utterance: "I know it is so". Nor from the utterance together with its not
    being a lie.-But can't I infer "It is so" from my own utterance "I know etc."? Yes;
    and also "There is a hand there" follows from the proposition "He knows that
    there's a hand there". But from his utterance "I know . . ." it does not follow
    that he does know it.

14. That he does know takes some shewing.
15. It needs to be shewtz that no mistake was possible. Giving the assurance "I know"
    doesn't suffice. For it is after all only an assurance that I can't be making a
    mistake, and it needs to be objectiueb established that I am not making a mistake
    about that.

21. Moore's view really comes down to this: the concept 'know' C is analogous to the
    concepts 'believe', surmise', 'doubt', 'be convinced' in that the statement "I
    know... ." can't be a mistake. And if that is so, then there can be an inference
    from such an utterance to the truth of an assertion. And here the form "I thought I
    knew" is being overlooked.-But if this latter is inadmissible, then a mistake in
    the assertion must be logically impossible too. And anyone who is acquainted with
    the language-game must realize thisan assurance from a reliable man that he hows
    cannot contribute anything.

22. It would surely be remarkable if we had to believe the reliable person who says "I
    can't be wrong"; or who says "I am not wrong".

94. But I did not get my picture of the world by satisfying myself of its correctness:
    nor do I have it because I am satisfied of its correctness. No: it is the inherited
    background against which I distinguish between true and false.

204. Giving grounds, however, justifying the evidence, comes to an end;-but the end is
     not certain propositions' striking us immediately as true, i.e. it is not a kind
     of seeing on our part; it is our acting, which lies at the bottom of the
     language-game.
205. If the true is what is grounded, then the ground is not true, nor yet false.
206. If someone asked us 'but is that true?" we might say "yes" to him; and if he
     demanded grounds we might say "I can't give you any grounds, but if you learn more
     you too will think the same". If this didn't come about, that would mean that he
     couldn't for example learn history.
207. "Strange coincidence, that every man whose skull has been opened had a brain!"

311. Or imagine that the boy questioned the truth of history (and everything that
     connects up with it)--and even whether the earth had existed at all a hundred
     years before.

312. Here it strikes me as if this doubt were hollow. But in that case-isn't belief in
     history hollow too ? No; there is so much that this connects up with.


167. It is clear that our empirical propositions do not all have the same status, since
     one can lay down such a proposition and turn it from an empirical proposition into
     a norm of description. Think of chemical investigations. Lavoisier makes
     experiments with substances in his laboratory and now he concludes that this and
     that takes place when there is burning. He does not say that it might happen
     otherwise another time. He has got hold of a definite world-picture-not of course
     one that he invented: he learned it as a child. I say world-picture and not
     hypothesis, because it is the matter-of-course foundation for his research and as
     such also goes unmentioned.


245. To whom does anyone say that he knows something? To himself, or to someone else.
     If he says it to himself, how is it distinguished from the assertion that he is
     sure that things are like that? There is no subjective sureness that I know
     something. The certainty is subjective, but not the knowledge. So if I say "I know
     that I have two hands", and that is not supposed to express just my subjective
     certainty, I must be able to satisfy myself that I am right. But I can't do that,
     for my having two hands is not less certain before I have looked at them than
     afterwards. But I could say: 'That I have two hands is an irreversible belief."
     That would express the fact that I am not ready to let anything count as a
     disproof of this proposition.
246. "Here I have arrived at a foundation of all my beliefs." "This position I will
     holdl" But isn't that, precisely, ody because I am completely convinced of it
     ?-What is 'being. completely convinced' like ?
247. What would it be like to doubt now whether I have two hands ? Why can't I imagine
     it at all? What would I believe if I didn't believe that? So far I have no system
     at all within which - this doubt might exist.
248. I have arrived at the rock bottom of my convictions. -~nd one might almost say
     that these fhdation-walls are carried by the whole house.
249. One gives oneself a false picture of doubt.
250. My having two hands is, in normal circumstances, as certain as anything that I
     could produce in evidence for it. That is why I am not in a position to take the
     sight of my hand as evidence for it.
251. Doesn't this mean: I shall proceed according to this belief unconditionally, and
     not let anything confuse me ?
252. But it isn't just that I believe in this way tha.t I have two hands, but that
     every reasonable person does.
253. At the foundation of well-founded belief lies belief that is not founded.
254. Any 'reasonable' person behaves like this

** Outline
*** Intro
**** Información de los artículos
**** Actitud de Anscombe hacia Hume
*** Planteamiento tema general:justificación creencias más allá de impresiones
**** Presupuesto: Relación causa y efecto es el puente
*** Ilustración: Una verdad histórica: asesinato del César
*** Dos argumentos de Hume
**** no es posible continuar una cadena de inferencias infinitamente
**** el término de la cadena tiene que ser algo distinto
*** Análisis de Anscombe: catching the mistake
**** this is rather a cantilever (there is only one support)
**** the inference ends up being purely hypotetical
***** suppositious and hypothetical reasoning: if p,q; if q,r then s; if s, then t
***** from it we could go the other direction: since...
**** Four parts to Hume's thesis
**** Conclusion: we infer q from p and not p from q
**** Illustrating the conclusion: indentity and proper names
*** Planteamiento desde On certainty
**** teich: requisito de que una hipótesis se le de forma con suficiente detalle
**** teich: En on certainty witt nos invita a
**** anscombe: analogía del barco: hay piezas que no pueden quitarse
**** anscombe: no está basado en percepción sino en common knowledge
**** common knowledge o tradition es uno de esos inmovable foundations
**** la justificación funciona como una practica aprendida
**** la justificación de creencias basadas en common knowledge funcionan así
**** nuestro conocimiento no está tanto data-laden, sino common-knowledge laden
**** relación este tipo de conocimiento con testimonio es lejano e indirecto
** Anscombe
To my mind the interest of Hume lies primarily in the problems he consciously or
unconsciously discovers to us. Here there is a problem unconsciously raised. For Hume
judges that we believe Caesar was killed in the Senate House from the testimony of
historians. (Is that testimony?) And he thinks that this belief is explained as our
reasoning from our perception of ‘certain characters and letters’, through successive
steps referring to intermediate records, back to the perception of eyewitnesses and
through that to the event. He supposes that the record before our eyes is our reason
for believing in the intermediate records, which are in turn our reason for believing
in the eyewitness report, which in turn is our reason for believing in the original
event. He must suppose this, otherwise it would not be possible for him, however
confusedly, to cite the chain of record back to the eyewitnesses as an illustration of
the chain of causes and effects with which we cannot run up in infinitum, but must
eventually bring to an end with our present perception or memory of written documents.
But it is not like this at all. If the written records that we see are our grounds for
belief, they are first and foremost grounds for belief in the original event, and then
our belief in the original event is a ground for belief in the intermediate
transmission. For let us ask: why do we believe there were eyewitnesses? Certainly
because we believe that the event happened. Therefore the belief in the event is not
based on belief that there were eyewitnesses. I have heard that the Rabbis hold that
the six hundred thousand witnesses to the crossing of the Red Sea must be credited;
600,000 witnesses—that is very sure witness! And now let us ask: why do they believe
there were 600,000? Because they believe 600,000 passed through.



The interesting problem that arises, then, is why the things we are told and the
writings that we see are the starting points for our belief in the far distant events
and so in the intermediate chain of record. This is a question of vast importance. But
the consideration of it would take us far away from that investigation of Hume on cause
which has been our present business. I take it as sufficiently demonstrated that Hume’s
account is wrong. (One may be convinced of that without thinking that one has an
alternative account.)




That assertion can have the function or purpose ascribed to it by Anselm (see above, p.
196)—i.e. that there can be such a thing as assertion—depends on the empirical fact,
among others, that people don’t generally reject their earlier assertions as unfounded.
It is ‘by favour of Nature’ that assertion and knowledge are possible (On Certainty,
para. 505); for Anselm and for Anscombe, it is (also) by the grace of God.
Wittgenstein’s views are subtle and complex, and it is important that one not reduce
them to a formula or two. I have mentioned ‘immovable foundations’ and
‘world-pictures’; but what Wittgenstein has to say about certainty, doubt,
disagreement, and so on encompasses more than these. As Anscombe warns us, we should
not regard the struggling investigations of On Certainty as all saying the same thing.
Doubts whether this is a tree or whether his name was L.W. or whether the world has
existed a long time or whether the kettle will heat on the fire or whether he had never
been to the moon are themselves not all subjected to the same treatment. Not all these
things, for example, are part of a ‘world-picture’. And a world-picture is not the same
thing as a religious belief, even though to believe is not in either case to surmise.
(QLI, 130)

** Rundown

    Intro:

    what's the justification for our beliefs falling outside our own experience
    and memory?

    if we take a belief in a historical matter of fact, the answer is: inference
    from the relation of cause and effect.

    1. Anscombe: that's not it

  because it is not belief in historical facts by inference
  but
  it is on the whole
  belief that there has been
  a chain of tradition of reports and records going back to contemporary knowledge


  2.Then what can be said about it?

  let's say that belief in the existence of julius caesar is not a belief that is
  justified by evidence that could be negated by some new single document or
  inscription

  let's ask: what could be evidence of Caesar never existing?
  what would we think
  of an inscription

  what would judge what here?

    A general epistemological reason for doubting one will be a reason for
    doubting all, and then none of them would have anything to test it by.

    So it turns out when I say things like “Here is a hand” I’m not really making
    a claim about the world, I’m laying down some rules for discussion.

      We know it from being taught; not just from explicit teaching, but by its being
      implicit in a lot else that we are taught explicitly. But it is very difficult
      to characterize the peculiar solidity involved or its limits. p. 90

      the killing of Caesar is something which exists in our culture with a
      particular logical status of one kind of certainty**

      [this kind of knowledge] could only be called in question only by indulging
      in Cartesian doubt


      not everything can be put up for checking

      she continues this in grounds of belief.....

      what is the justification or grounds for the belief

** notes
Section IV part III of Book I of the treatise

Topic: belief in matters falling outside our own experience and memory

when infering effects from causes
we must establish the existence of these causes
either by:

inmediate perception of our memory or senses

or by

 an inference from other causes

these other causes must be ascertained in the same manner

it is impossible to carry on our inferences in infinitum

Hume tries to ilustrate this by an example of historical belief

we believe that caesar was killed....

it is obvious all this chain of argument or connexion of causes and effects is at first
founded on those characters or letters which are seen or remembered

But this is not infering effects from causes, it is infering causes from effects.

As such, for an historical belief we must have to be saying
when we infer effects from causes or causes from effects...

when we infer causes from effects we must establish the existence of those effects
either by perception or by inference from other effects which effects we must ascertain
in the same manner by a present impression or by an inference from their effects and so
on, until we arrive at an object which we see or remember



For Hume the relation of cause and effect is the one bridge by which to reach belief in
matters beyond our present impressions or memories

and also cause and effect are inferentially symmetrical

are they?

what is the starting point? (the start of inference or the start of the justification
chain)

The historical example is an inference of the original cause, the killing of Caesar,
from its remote effect, the present perception of certain characters or letters.

The starting-point is the present perception, and from it we can run through a chain of
effects of causes which are effects of causes to the original cause: the killing of
Caesar

the end of the chain is thus not our perception and so it doesn't serve as an
impression of our memory or senses beyond which there is no room for doubt or enquiry
as to stop us going infinitely

"tis impossible for us to carry on our inference in infinitum" means: *the
justification of the grounds of our inferences cannot go on in infinitum* *we must come
to belief which we do not base on grounds*

What Hume is arguing is that we not only have a perception starting point but that we
must reach a starting point in the justification of these inferences

for him tracing back (from effects to causes) is taken to be symmetrical to inferences
from causes to effects

it must be purely hypothetical inference

we reason (purely hypothetically) if Caesar was killed, then there were witnesses , if
there were witnesses then there was testimonies, then there were records made from
them, if there were records made then there are characters and letters to be seen which
say that Caesar was Killed

Four parts of Hume's thesis:

1. a chain of reasons for a belief must terminate in something that is believed without
   being founded on anything else
2. the ultimate belief must be of a quite different character from derived beliefs: it
   must be perceptual belief, belief in something perceived, or presently remembered
3. the immediate justification for a belief p, if the belief is not a perception, will
   be another belief q, which follows from, just as much as it implies, p.
4. we believe by inference through the links in a chain of record

implicit corollary: when we believe in historical information belonging to the remote
past, we believe that there has been a chain of record

Hume must believe all this

*But it is not like that!*


If the written records that we now see are grounds of our belief, they are first and
foremost

*grounds for belief*
in Caesar's killing,
belief that the assasination is a solid bit of history

THEN

our belief in that original event IS A GROUND FOR BELIEF in

much of the intermediate transmission <-



belief in recorded history is on the whole a belief that there has been a chain of
tradition of reports and records going back to contemporary knowledge;

IT IS NOT A BELIEF IN THE HISTORICAL FACTS BY AN INFERENCE THAT PASSES THROUGH THE
LINKS OF SUCH A CHAIN. AT MOST, THAT CAN VERY SELDOM BE THE CASE.

Casting a doubt about Caesar's existence would put us in a vacuum in which there is
nothing by which to judge anything else

What would I be allowed to count as evidence then?

PEOPLE IN HISTORY ARE NOT IN ANY CASE HYPOTHESES WHICH WE HAVE ARRIVED AT TO EXPLAIN
CERTAIN PHENOMENA

A general epistemological reason for duobting one will be a reason for doubting all,
and then none of them would have anythin to test it by
