#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico/pmc.tex
#---------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

** TODO Parmenides, Mystery and Contradiction (1969) [50%]
>> escribir una síntesis de lo que anscombe hace y entonces redactar...
#+BEGIN_SRC latex
  \subsection{Parmenides, Mystery and Contradiction}
#+END_SRC
*** DONE Información del texto
    CLOSED: [2019-08-21 Wed 13:27]
#+BEGIN_SRC latex
  En 1981 Anscombe publicó una colección de sus escritos en tres volúmenes llamados \emph{The Collected Philosophical Papers of G.\,E.\,M.\,Anscombe}. El primero de estos, titulado \emph{From Parmenides to Wittgenstein}, recoge un tema que juega un papel importante en el \emph{Tractatus} de Wittgenstein y que Anscombe trató con gran interés: la relación entre lo concebible y lo posible. En el contexto del pensamiento de Wittgenstein la cuestión de lo concebible se encuentra dentro de la discusión sobre lo que puede ser dicho claramente. Ahí se encuentran también característicos temas Wittgensteinianos como la falta de significado, el sinsentido, lo misterioso y lo inefable; nociones que estarán presentes en el análisis de Anscombe.

  El volumen reúne a autores como Parménides, Platón, Hume y Wittgenstein en la discusión sobre esta cuestión\footnote{\cite[Cf.~][193]{teichmann2008ans}: Philosophers have grappled since ancient times with the problem of how thinkability and possibility are related, and it is characteristic of Anscombe to have drawn such diverse figures as Parmenides, Plato, Hume, and Wittgenstein into a single discussion.} y, como es característico de Anscombe, en cada artículo se le encuentra identificando rutas interesantes tomadas por los distintos autores y profundizando todavía más por caminos de reflexión que ella juzga poco explorados o no valorados del todo.

  El primer artículo: \emph{Parmenides, Mystery and Contradiction}, es el texto de una ponencia ofrecida por Anscombe en la reunión del \emph{Aristotelian Society} en \emph{21, Bedford Square} en Londres el 24 de febrero de 1969. En esta discusión Elizabeth estudia la manera en que Parménides construye su argumento acerca de lo posible y lo concebible y qué oportunidades ofrece para un análisis de esta relación.

  Una importante clave de interpretación de este artículo se encuentra en el lugar que ocupa como parte de esta colección. El título del volúmen no es casual, el primer artículo es dedicado a Parmenides, y el último, \emph{The Question of Linguistic Idealism}, es un examen de nociones importantes en la filosofía de Wittgenstein en donde reaparecen preguntas que Anscombe plantea ya en esta investigación dedicada a las ideas de Parmenides. Su análisis de los argumentos de Parmenides no tiene como objetivo cerrar cuestión alguna, sino que más bien pone en marcha la discusión. ¿En qué consiste esta discusión que Anscombe juzga presente ya en Parmenides y viva todavía en Wittgenstein? En la introducción de la colección la describe diciendo: \blockquote[{\cite[xi]{anscombe1981parmenides}}: At the present day we are often perplexed with enquiries about what makes true, or what something's being thus or so \emph{consists in}; and the answer to this is thought to be an explanation of meaning. If there is no external answer, we are apparently committed to a kind of idealism.]{En la época actual con frecuencia nos quedamos perplejos con preguntas sobre qué hace a algo verdadero, o \emph{en qué consiste} el que algo sea de un modo u otro; y la respuesta a esto se piensa que es una explicación del significado. Si no hay una respuesta externa, aparentemente estamos comprometidos con un tipo de idealismo.}

Esta preocupación de la época, aludida por Anscombe, tiene una presencia importante en \emph{Investigaciones Filosóficas}. Las \S\S428--65, en donde Wittgenstein se detiene a reflexionar sobre la intencionalidad, contienen implícitamente una crítica a ese modo de concebir el pensamiento, el lenguaje, la realidad y sus relaciones que sirvió para orientar las ideas del \emph{Tractatus}; específicamente atacan: \blockquote[{\cite[3]{hacker2000mind}}: the undelying assumptions that characterize the whole tradition of philosophical reflection of which it was the culmination.]{los presupuestos subyacentes que han caracterizado toda la tradición de reflexión filosófica de la cual este fue la culminación}. Entre estos presupuestos se cuestiona con fuerza \blockquote[{\cite[3]{hacker2000mind}}: the venerable idea that the meaning of signs, their capacity to represent what they represent, is parasitic upon thought, upon mental processes of thinking and meaning]{la venerable idea de que el significar de los signos, su capacidad para representar lo que representan, depende del pensamiento, de procesos mentales de pensar y significar}. Esta idea, juzga Wittgenstein, es un producto de la concepción de los pensamientos como representación. Sobre los pensamientos así concebidos es que ha girado cierta discusión en la que se ha debatido acerca de qué es que los pensamientos están constituidos. Así: \blockquote[{\cite[3]{hacker2000mind}}: the empiricists characteristically held them to be mental images or ideas; others, like the author of the \emph{Tractatus}, were more reticent, content to leave the matter to future psychological discovery, insisting only that thought-constituents must stand to reality in the same sort of relation as words.]{los empiristas característicamente sostenían que estos eran imágenes mentales o ideas; otros, como el autor del \emph{Tractatus}, fueron más reticentes, contentándose con dejar el asunto al futuro descubrimiento psicológico, insistiendo solamente en que los constituyentes de pensamiento tienen que estar, respecto de la realidad, con el mismo tipo de relación que las palabras.}

Dentro de este debate, la intencionalidad de los pensamientos, ---y aquí `pensamientos' pueden ser creencias, expectativas, esperanzas, temores, dudas, deseos, etc.--- era explicada también de modos distintos por los empiristas y por el autor del \emph{Tractatus}. Los primeros sosteniendo que la relación entre un pensamiento y la realidad correspondiente con este es externa, y el segundo que la relación es interna. La posibilidad de esta relación interna aparece explicada en el \emph{Tractatus}: \blockquote[{\cite[3]{hacker2000mind}}: in terms of a pre-established metaphysical harmony between thought and reality. This harmony was conceived to consist in an essential isomorphism between representation and what is represented, wether truly or falsely.]{en términos de una armonia metafísica preestablecida entre el pensamiento y la realidad. Esta armonía fue concebida como consistiendo en un isomorfismo esencial entre la representación y lo que es representado, ya sea verdadera como falsamente.} La concepción empirista \blockquote[{\cite[3]{hacker2000mind}}: attempted to explain the intentionality of thought in causal terms \textelp{} construing the relation between thought and reality (between belief and what makes it true, or between desire and what fulfills it) as external.]{intentó explicar la intencionalidad del pensamiento en terminos causales \textelp{} interpretando la relación entre pensamiento y realidad (entre el creer y lo que lo hace verdadero, o entre el deseo y lo que lo realiza) como externa.} En \emph{Investigaciones Filosóficas} se critican estas dos posturas aunque mantiene la idea de que la relación entre pensamiento y realidad es interna.

Estas discusiones son importantes porque estan en el trasfondo de la perspectiva de Elizabeth, siendo su postura análoga a la que se encuentra en \emph{Investigaciones Filosóficas}. Todavía otro elemento de esta reflexión se descubre presente en el análisis que Anscombe hace de los argumentos de Parmenides. En las \S\S89--133 Wittgenstein examina la naturaleza de la filosofía y critica la impresión de que el pensamiento sea algo misterioso o extraño. En las \S\S93--94 se fija en que la proposición puede parecer algo extraordinario que aparenta esconder un intermediario puro (la forma lógica) que está entre los signos y los hechos. \S95 sugiere que también el pensar parece algo de naturaleza singular: \blockquote[{\cite[4]{hacker2000mind}}: for what we mean when we say that such-and-such is the case does not stop short of the fact that makes what we say true. We mean that very fact, and not something that stands in some relation (e.g. of correspondence) to it. We, as it were, reach right up to it. On the other hand, we can think what is \emph{not} the case. But if it is not the case, then it seems that there is nothing to reach right up to. Yet what we think when we think what is the case and what we think when we think what is not the case are not intrinsically different. How is this possible? The \emph{Tractatus} resolved the difficulty by arguing that what we think is the sense of a sentence, which is a \emph{possible} state of affairs, actual if what we think is the case and unactualized if what we think is not the case. For this a complex metaphysics and ontology and an elaborate doctrine of the depth grammar of all possible languages were introduced.]{pues lo que significamos cuando decimos que alguna cosa es de hecho no se queda detenido ante el hecho que hace que lo que decimos sea verdadero. Significamos el mismo hecho y no algo que está situado en relación alguna (de correspondencia por ejemplo) con este. Nosotros, podría decirse, lo tenemos al alcance. Por otra parte, podemos pensar lo que \emph{no} es de hecho. Pero si no es de hecho, entonces parece que no hay nada para alcanzar. Sin embargo lo que pensamos cuando pensamos lo que es de hecho y lo que pensamos cuando pensamos lo que no es de hecho no es intrínsecamente distinto. ¿Cómo es esto posible? El \emph{Tractatus} resolvió la dificultad argumentando que lo que pensamos es el sentido de una oración, que es un \emph{posible} estado de las cosas, actual si lo que pensamos es de hecho y no actualizado si lo que pensamos no es de hecho. Para esto se introdujo una compleja metafísica y ontología y una elaborada doctrina sobre la gramática profunda de todos los lenguajes.} Para \emph{Investigaciones Filosóficas} la noción misma del lenguaje o del pensamiento como algo singular o la idea de que entender el lenguaje es algo extraordinario cuya comprensión tiene que pasar a través del medio que es el pensamiento es una superstición producida por ilusiones de la gramática.

La propuesta es que lo que parece misterioso del lenguaje no es una armonía formal a priori entre el pensamiento y la realidad, sino precisamente la intencionalidad del pensamiento: \blockquote[{\cite[4]{hacker2000mind}}: A thought seems queer and mysterious when we reflect on it in philosophy. What is mysterious is precisely its intentionality. \S429 introduces the \emph{Tractatus} idea of the `harmony between thought and reality', which constituted an explanation of the `mysteries' of thinking and of the nature of representation by means of language. This misconception is laid to rest (with excessive brevity) by an intra-grammatical move that implicitly repudiates the earlier conception of a connection between language and reality. An ostensive definition does not forge a connection between word and world of a kind which the \emph{Tractatus} had thought essential, but is a rule of grammar. So language is, in this sense, autonomous and self-contained.]{Un pensamiento parece extraño y misterioso cuando reflexionamos sobre él en la filosofía. Lo que es misterioso es precisamente su intencionalidad. \S429 introduce la idea del \emph{Tractatus} de la `armonía entre pensamiento y realidad', que constituye una explicación de los `misterios' del pensar y de la naturaleza de la representación por medio del lenguaje. A esta idea equivocada se le pone fin (con excesiva brevedad) por medio de un movimiento intra-gramático que implícitamente repudia la anterior concepción de una conexión entre el lenguaje y la realidad. Una definición ostensiva no forja una conexión entre palabra y mundo del tipo del que el \emph{Tractatus} había pensado como esencial, sino que es una regla de la gramática. Así que el lenguaje es, en este sentido, autónomo e independiente.}

Cuando se abandona esta relación a priori entre el pensamiento y la realidad también la lógica queda resituada. Mientras que en el \emph{Tractatus} el rigor de la lógica se entendía como la imagen-reflejo de este orden a priori del mundo, \S108 de \emph{Investigaciones Filosóficas} corrige esta visión proponiendo que más bien es un modo de representación: \blockquote[{\cite[242]{bakerhacker2009understanding}}: We can re-present sentences of natural language in the forms of sentences of the predicate calculus. We can recast our arguments in these forms and display their validity (or invalidity). We can perspicuously disambiguate certain kinds of equivocations in ordinary language by means of quantifier shifts in the calculus.]{Podemos re-presentar oraciones del lenguaje natural en las formas de oraciones del cálculo predicado. Podemos reestructurar nuestros argumentos en estas formas y mostrar su validez (o invalidez). Podemos inteligiblemente eliminar la ambigüedad de ciertos tipos de equivocaciones en el lenguaje ordinario por medio de desplazamientos de los cuantificadores en el cálculo.}

Por último podemos preguntarnos, si se ha abandonado esta descripción del modo en que las palabras significan, ¿qué es lo que les otorga significado según la visión de \emph{Investigaciones Filosóficas}? Sobre esto se encuentra en \S430--432 y \S454: \blockquote[{\cite[4]{hacker2000mind}}: One must resist the temptation of thinking that what gives life to a sign is a psychic act, e.g. thinking, understanding or meaning. The life of a sign lies in its rule-governed use in a practice, in the application that a living being, who has mastered the techniques of its use, makes of it.]{Debemos resistir la tentación de pensar que lo que da vida a un signo es un acto psíquico, como pensar, entender o significar, por ejemplo. La vida de un signo se encuentra en el uso gobernado por reglas que se hace de este en la práctica, en la aplicación que un ser vivo, que domina las técnicas de su uso, hace de él.}

Teniendo en cuenta todo este trasfondo podemos distinguir los movimientos que Anscombe realiza en su análisis. El argumento de Parmenides que será examinado lo presenta como sigue: \blockquote[{\cite[3]{anscombe1981parmenides:pmc}}: Parmenides' arguments runs:\\
It is the same thing that can be thought and can be\\
What is not can't be\\
$\therefore$ What is not can't be thought\\
Ver también en {\cite[22--25]{parmenides2007poema}}: Algunos fragmentos relacionados con el argumento presentado por Anscombe pueden ser: \ldots\textgreek{τὸ γὰρ αὐτὸ νοεῖν ἐστίν τε καὶ εἶναι.} (III); \textgreek{Χρὴ τὸ λέγειν τε νοεῖν τ' ἐὸν ἔμμεναι· ἔστι γὰρ εἶναι, μηδὲν δ' οὐκ ἔστιν} (VI); \textelp{} \textgreek{οὐ γὰρ φατὸν οὐδὲ νοητόν ἔστιν ὅπως οὐκ ἔστι.} (VIII)]{El argumento de Parmenides va así:\\
Es la misma cosa lo que puede ser pensado y lo que puede ser\\
Lo que no es no puede ser\\
$\therefore$ Lo que no es no puede ser pensado}

Ahora bien, Elizabeth aclara que Parmenides tiene algunos presupuestos que es preciso tener en cuenta para interpretar sus premisas. En primer lugar, un presupuesto de Parmenides, que tiene en común con Platón, es \blockquote[{\cite[x]{anscombe1981parmenides}}: that a significant term is a name of an object which is either expressed or characterized by the term]{que un término significativo es el nombre de un objeto que está expresado o caracterizado por el término}. Este presupuesto, propone Anscombe, \blockquote[{\cite[xi]{anscombe1981parmenides}}: is an ancestor of much philosophical theorizing and perplexity]{es un ancestro de mucha teorización y perplejidad filosófica} y continúa: \blockquote[{\cite[xi]{anscombe1981parmenides}}: <<In Aristotle \textelp{} the theory of substance and the inherence in substances of individualized forms of properties and relations of various kinds \textelp{} In Descartes \textelp{} the assertion that the descriptive terms which we use to construct even false pictures of the world must themselves stand for realities \textelp{} In Hume \textelp{} the assumption that `an object' corresponds to a term, even such a term as ``a cause'' as it occurs in ``A beginning of existence must have a cause.'' \textelp{} Brentano thinks that the mere predicative connection of terms is an `acknowledgement' \textelp{} Wittgenstein himself in the \emph{Tractatus} has language pinned to reality by its (postulated) simple names, which mean simple objects.>>]{En Aristóteles \textelp{} la teoría de la sustancia y la inherencia en sustancias de formas individualizadas de propiedades y relaciones de varias clases \textelp{} En Descartes \textelp{} la aseveración de que los términos descriptivos que usamos para construir incluso falsas imágenes del mundo tienen que ser ellos mismos representaciones de realidades \textelp{} En Hume \textelp{} el presupuesto de que `un objeto' corresponde con un término, incluso con un término como ``una causa'' así como aparece en ``El comienzo de una existencia tiene que tener una causa.'' \textelp{} Brentano piensa que la mera conexión predicativa de términos es un `reconocimiento' \textelp{} Wittgenstein mismo en el \emph{Tractatus} tiene al lenguaje atado a la realidad por medio de sus (postulados) nombres simples, que significan objetos simples.} Esta tradición de \enquote{teorización y perplejidad} que Anscombe traza culminando en el \emph{Tractatus} hace referencia al modelo de representación que encontrabamos criticado en \emph{Investigaciones Filosóficas}. Anscombe nota presente en el argumento de Parmenides un germen de la tradición subyacente a la conexión a priori entre el lenguaje y la realidad que aparece en el \emph{Tractatus}.

Otros dos presupuestos se encuentran en las premisas del argumento parmenidiano; uno tiene que ver con lo que Parmenides entiende por \enquote{ser} y el otro con su descripción sobre las dos \enquote{rutas} posibles para el pensamiento sobre algo. Según lo dicho acerca del presupuesto anterior, para Parmenides los términos son nombres de objetos, y según esto, para él, \enquote{ser} es el nombre de un objeto. Sin embargo el uso que hace del término en sus premisas no es tan simple: \blockquote[{\cite[x]{anscombe1981parmenides}}: ``being'' might be an abstract noun, equivalent to the infinitive ``to be''. But Parmenides does not treat \emph{to be} as an object, but rather \emph{being}, i.e. something being or some being thing \textelp{} we might get closer to the sense by saying ``what is'']{``el ser'' puede ser un nombre abstracto, equivalente al infinitivo ``ser''. Pero Parmenides no trata ``ser'' como un objeto, sino más bien ``el ser'', es decir algo que esta siendo, o alguna cosa que es \textelp{} nos podemos aproximar a este sentido diciendo ``lo que es''}. También trae dificultades lo que Parmenides propone como las dos rutas posibles del pensamiento. Estas son \enquote{es, y no puede no ser} (\textgreek{ἔστιν τε καὶ ὡς οὐκ ἔστι μὴ εἶναι}) y \enquote{no es y necesariamente no puede ser} (\textgreek{οὐκ ἔστιν τε καὶ ὡς χρεών ἐστι μὴ εἶναι}). Anscombe lo pone en estas palabras: \blockquote[{\cite[x]{anscombe1981parmenides}}: ``These are the only ways for enquiry for thought: one is `is and cannot not be',\ldots the other `is not, and needs must not be'.'' That is: Whatever enquiry one is making, one's thoughts can only go two ways, saying `is, and must be', or `is not, and can't be'.]{``Estos son los únicos caminos para indagar con el pensamiento: uno es `es y no puede no ser',\ldots el otro `no es, y necesariamente no puede ser'.'' Esto es: Cualquier indagación que estemos haciendo, nuestros pensamientos solo pueden ir en una de dos direcciones, decir `es, y debe ser', o `no es, y no puede ser'.} Anscombe destaca que es notable la combinación de \enquote{es} con \enquote{debe ser}  y \enquote{no es} con \enquote{no puede ser}, la justificación de Parmenides para esta relación puede verse presente en el argumento antes citado si este mismo se entiende como: \blockquote[{\cite[vii]{anscombe1981parmenides}}: Parmenides himself argues: What can be thought can be, What is nothing cannot be, Therefore whatever can be actually is. Therefore whatever can be thought actually is.]{Lo que puede ser pensado puede ser,\\
Lo que es nada no puede ser,\\
Por tanto lo que sea que pueda ser es de hecho.\\
Por tanto lo que sea que pueda ser pensado es de hecho.}

Una lectura poco atenta, advierte Anscombe, podría dejar la impresión de que el argumento consiste en: \blockquote[{\cite[vii]{anscombe1981parmenides}}: Only what can be thought can be, What is not cannot be thought, Therefore what is not cannot be.]{Solo lo que puede ser pensado puede ser,\\
Lo que no es no puede ser pensado,\\
Por tanto lo que no es no puede ser.} Sin embargo, Parmenides no argumentó así.\footnote{\cite[Cf.~][6]{anscombe1981parmenides:pmc}: \textelp{} one might, if reading inattentively, think that Parmenides did argue like that.} La segunda premisa del argumento, las proposiciones \enquote{Lo que no es no puede ser} o \enquote{Lo que es nada no puede ser}, están basadas en que \enquote{Lo que no es, es nada}\footnote{\cite[Cf.~][vii]{anscombe1981parmenides}: these arguments \textelp{} use as a premise: What is not is nothing}. El argumento, por tanto, \blockquote[{\cite[vii]{anscombe1981parmenides}}: \textins{doesn't} derive the nothingness of what-is-not from its unthinkability, but rather unthinkability from its nothingness or from its impossibility.]{no deriva la inexistencia de lo-que-no-es de su ser inconcebible, sino más bien su ser inconcebible desde su inexistencia o su imposibilidad.} Y así Anscombe insiste: \blockquote[{\cite[viii]{anscombe1981parmenides}}: If I am right, the ancients never argued from constraints on what could be a thought to restrictions on what could be, but only the other way around.]{Si estoy en lo correcto, los antiguos nunca argumentaron desde las limitaciones de lo que podría constituir un pensamiento a las restricciones sobre lo que puede ser, sino en la manera inversa.} Este punto es del interés de Anscombe. Es decir, la reflexión de Parmenides no solo resulta interesante a Anscombe por la tradición filosífica que representa, sino además porque percibe en su época la tendencia propia del modernismo de deducir lo posible desde lo concebible, sin embargo le parece más atractivo el acercamiento de Parménides y los antiguos: \blockquote[{\cite[xi]{anscombe1981parmenides}}: It was left to the moderns to deduce what could be from what could hold of thought, as we see Hume to have done. This trend is still strong. But the ancients had the better approach, arguing only that a thought was impossible because the thing was impossible, or, as the Tractatus puts it, ``Was man nicht denken kann, das kann man nicht denken'': an \emph{impossible} thought is an impossible \emph{thought}.]{Se les dejó a los modernos el deducir lo que puede ser posible desde lo que puede ser sostenido en el pensamiento, como vemos hacer a Hume. Esta tendencia sigue siendo fuerte. Pero los antiguos tuvieron el mejor acercamiento, argumentando solo que un pensamiento sería imposible porque la cosa misma es imposible, o, como lo dice el \emph{Tractatus}, ``Was man nicht denken kann, das kann man nicht denken'': un pensamiento \emph{imposible} es un \emph{pensamiento} imposible.} Aquí Elizabeth vuelve a hacer referencia al debate sobre la relación entre la realidad y el pensamiento y en esta ocasión la postura del empirismo de su época aparece como el que está en continuidad con los planteamientos de la modernidad, mientras que propone la postura del \emph{Tractatus} como en sintonía con la que se encuentra en los antiguos. En definitiva, es importante que este análisis de los planteamientos de Parmenides sirven a Anscombe para hacer un comentario sobre el debate acerca de la relación entre la realidad y el pensamiento desde la mentalidad de las propuestas de \emph{Investigaciones Filosóficas} como crítica de las propuestas del empirismo de su época, así como de la postura del \emph{Tractatus}.
#+END_SRC
*** TODO Análisis del Argumento de Parmenides
**** El Argumento
**** La Segunda Premisa
#+BEGIN_SRC latex
Ahora bien, ¿qué tiene que decir Anscombe sobre el argumento de Parmenides? En primer lugar examina la segunda premisa: \enquote{Lo que no es no puede ser}. La modalidad según la cual se interprete la premisa le otorga distintas acepciones. Entendida \emph{in sensu composito}, es decir, como una proposición general, la verdad de la premisa \enquote{Lo que no es no puede ser} puede ser entendida como la imposibilidad de la afirmación \enquote{Lo que no es, es}.\footnote{\cite[Cf.~][vii]{anscombe1981parmenides}: \textelp{} the impossibility of the proposition ``What is not is'' ---i.e. the truth of ``What is not cannot be'', taken in \emph{sensu composito}} Si, por otra parte, se entiende \emph{in sensu diviso}, o como una proposición particular, puede ser interpretada como \blockquote[{\cite[3]{anscombe1981parmenides:pmc}}: Concerning that which is not, it holds that \emph{that} cannot be]{Concerniendo aquello que no es, se sostiene que \emph{eso} no puede ser}. Es importante notar aquí los dos modos de usar el término \enquote{ser} antes descritos, \enquote{lo que no es} lo emplea como nombre de un objeto, y \enquote{no puede ser} como una propiedad de este objeto o un predicado de este. Igualmente puede notarse la ruta \enquote{no es y no puede ser} examinada también anteriormente.

Tras distinguir la diferencia de sentido de la premisa según la modalidad que se le interprete, Anscombe establece que el argumento completo no es válido si esta segunda premisa es entendida \emph{in sensu composito}. Sin embargo, si se interpreta \emph{in sensu diviso}, la premisa misma no es creíble. Esto lo explica diciendo: \blockquote[{\cite[vii]{anscombe1981parmenides}}: The impossibility of what is not isn't just the impossibility of the proposition ``What is not, is'' ---i.e. the truth of ``What is not cannot be'', taken \emph{in sensu composito}. \emph{That} could be swept aside as irrelevant. What is not can't be indeed, but it may come to be, and in this sense what is not is possible. When it \emph{has} come to be, of course it no longer is what is not, so in calling it possible we aren't claiming that ``What is not is'' is possible. So it can't be shown to be impossible that it should come to be just by pointing to the impossibility that it is. ---But this can't be the whole story. That what is not is nothing implies that there isn't anything to come to be. So ``What is not can be'' taken in \emph{sensu diviso}, namely as: ``Concerning what is not, \emph{that} can be'' is about nothing at all. If it were about something, then it would be about something that is not, and so there'd be an example of ``What is not is'' that was true.]{La imposibilidad de lo que no es, no es solo la imposibilidad de la proposición ``lo que no es, es'' ---es decir, la verdad de ``Lo que no es no puede ser'', tomado \emph{in sensu composito}. \emph{Eso} puede ser descartado como irrelevante. Lo que no es, ciertamente no puede estar siendo, pero puede llegar a ser, y en este sentido lo que no es es posible. Cuando \emph{haya} llegado a ser, ciertamente ya no es lo que no es, así que en llamarlo posible no estamos declarando que ``Lo que no es, es'' es posible. Entonces no puede mostrarse como imposible que pueda llegar a ser solo por señalar la imposibilidad de que este siendo. ---Pero esta no puede ser toda la historia. Que lo que no es, es nada implica que no hay nada ahí para llegar a ser. Así ``Lo que no es puede ser'' tomado en \emph{sensu diviso}, digase como: ``Con respecto a lo que no es, eso puede ser'' es acerca de nada en absoluto. Si fuera acerca de algo, entonces sería sobre algo que no es, y así habría un ejemplo de ``Lo que no es, es'' que sería verdadero.} Si la premisa se toma en sentido general su significado es irrelevante para el argumento. Si se toma en sentido particular es relevante para el argumento, pero es una proposición que no es creíble; lo mismo ocurre con la conclusión: \blockquote[{\cite[3]{anscombe1981parmenides:pmc}}: Concerning that which is not, it holds that \emph{that} cannot be thought.]{Con respecto a aquello que no es, se sostiene que \emph{eso} no puede ser pensado} la cual también es increíble.

Al decir que la premisa no es creíble porque es \enquote{es acerca de nada en absoluto} Anscombe no esta situada desde la comprensión del lenguaje como representación, es decir, no está afirmando que la premisa no representa un objeto posible, sino que está criticando que la premisa misma no dice nada. El problema se encuentra en la proposición misma; \blockquote[{\cite[5]{anscombe1981parmenides:pmc}}: whether we interpret the premise as saying: `What doesn't exist can't exist' or as: `What isn't the case can't be the case' the proposition is not credible]{ya sea que interpretemos la premisa como diciendo: `Lo que no existe no puede existir' o como: `Lo que no es de hecho no puede ser de hecho' la proposición no es creíble}. Para ilustrar esto de otra manera Anscombe representa la premisa según su estructura lógica de este modo:
  \begin{center}$(F)(x)\enspace {\sim}F\enspace x\quad \longrightarrow\quad Nec\enspace {\sim}Fx$\end{center}
Donde la variable $x$ representa un objeto y la variable $F$ representa una propiedad predicada del objeto $x$. La implicacíon de que concerniendo un objeto concreto con una propiedad concreta predicada de él, necesariamente, de la negación del predicado del objeto, se sigue la negación de la conjunción del objeto y su predicado, no es una afirmación creíble. Para que Parmenides pueda juzgar creíble su afirmación tiene que basarse en el supuesto de que necesariamente una propiedad predicada de un objeto tiene que ser existente, tiene que tener un referente en la realidad. Según esto la variable de la propiedad $F$ tiene que ser representativa de una propiedad existente.

Contra esto, Anscombe enfatiza la independencia del uso lenguaje respecto de la realidad: \blockquote[{\cite[5]{anscombe1981parmenides:pmc}}: it is false that one mentions either properties or objects when one uses the quantifiers binding property variables and object variables; though it has to be granted that some authors, such as Quine, are accostumed to speak of the reference of variables. But if this is given up, as it ought to be, Parmenides is deprived of his claim that we are commited to self-contradiction in existence just because we are willing to use a self-contradictory predicate --- e.g. in the sentence saying that nothing has a self-contradictory predicate true of it --- so that our property-variable is admitted to range over self-contradictory properties.]{es falso que mencionamos propiedades u objetos cuando usamos cuantificadores para enlazar variables de propiedades con variables de objetos; aunque habría que reconocer que algunos autores, como Quine, están acostumbrados a hablar de la referencia de las variables. Pero si esto es abandonado, como debería de serlo, Parmenides queda privado de su declaración de que estamos comprometidos con la auto-contradicción en la existencia solo porque estamos dispuestos a usar un predicado auto-contradictorio --- por ejemplo en la afirmación de que no hay algo que tenga un predicado auto-contradictorio verdadero de ello --- así que se le puede permitir a nuestra variable-propiedad abarcar también propiedades auto-contradictorias.}

A Anscombe le parece acertada la dirección de la argumentación de Parmenides en sostener lo concebible desde lo posible, sin embargo rechaza que para afirmar esto haya que establecer un vínculo metafísico entre lo posible y lo concebible. Igualmente rechaza que sea necesario creer que \enquote{Lo que no es no puede ser pensado} para evitar sostener la creencia de que lo existente puede ser auto-contradictorio. Para Anscombe lo que no es puede ser pensado y esto no implica creer que lo existente puede ser auto-contradictorio.

Aquí tenemos en el centro del análisis de Anscombe la visión de \emph{Investigaciones Filosóficas} sobre la relación entre la realidad, el lenguaje y el pensamiento. En la \S429 se afirma: \blockquote[The agreement, the harmony, between thought and reality consists in this: that if I say falsely that something is \emph{red}, then all the same, it is \emph{red} that it isn't. And in this: that if I want to explain the word ``red'' to someone, in the sentence ``That is not red'', I do so by pointing to something that \emph{is} red.]{La concordancia, la armonía, entre pensamiento y realidad consiste en esto: que si digo falsamente que algo es \emph{rojo}, entonces aún así, es \emph{rojo} eso que eso no es. Y en esto otro: que si quiero explicar la palabra ``rojo'' a alguien, en la oración ``Eso no es rojo'', lo haría por medio de señalar a algo que \emph{es} rojo.} Lo que esta sección propone es que contrario a la comprensión del \emph{Tractatus} de que la realidad y el pensamiento están unidos porque comparten la forma lógica, el pensamiento y la realidad, más bien, quedan unidos en el uso que se hace del lenguaje: \blockquote[{\cite[17--18]{hacker2000mind}}: It was a mistake to conceive of the agreement or harmony between language and reality as an agreement of form. It is misguided to think of the \emph{grammatical} proposition `If I say falsely that something is \emph{red}, then, for all that, it isn't \emph{red}' as displaying a harmony \emph{between} thought and reality, a harmony which demands an elaborate logico-metaphysical explanation of the essential projective co-ordination of language and world. The apparent harmony is not orchestrated between a thought and a situation (which may or may not obtain) or between names and their isomorphic meanings which constitute the substance of the world, but rather \emph{between one proposition and another}. For it is a rule of our language that `It is false that $p$' = `not-$p$'. It is a grammatical proposition, not a metaphysical truth about the relation between language and reality, that if it is false that this is red, then this is not red. Indeed, it is impossible that there be a language in which what we describe by `not-$p$' would be expressed without using `$p$'. `Like everything metaphysical, the harmony between thought and reality is to be found in the grammar of the language'. \textelp{} It is correct that one can read off from the proposition that $p$ the fact that makes it true, but that does not betoken a pre-established harmony between language and reality. It is merely \emph{a move in grammar} licensed by the substitution-rule: `the proposition that $p$' = `the proposition which the fact that $p$ makes true']{Fue un error concebir la concordancia o la armonía entre lenguaje y realidad como una concordancia de forma. Es desacertado pensar que la proposición \emph{gramática} `Si digo falsamente que algo es \emph{rojo}, entonces, con todo y eso, eso no es \emph{rojo}' está mostrando armonía \emph{entre} pensamiento y realidad, una armonía que reclama una elaborada explicación lógico-metafísica de la esencial co-ordinación proyectiva de lenguaje y mundo. La aparente armonía no esta orquestada entre un pensamiento y una situación (que puede ser de hecho o no) o entre nombres y sus significados isomórficos que constituyen la sustancia del mundo, sino más bien \emph{entre una proposición y otra}. Pues es una regla de nuestro lenguaje que `Es falso que $p$' = `no-$p$'. Es una proposición gramática, no una verdad metafísica sobre la relación entre el lenguaje y la realidad, que si es falso que esto es rojo, entonces esto no es rojo. Ciertamente, es imposible que haya un lenguaje en el cual lo que describimos por medio de `no-$p$' se expresara sin usar `$p$'. `Como todo lo metafísico, la armonía entre pensamiento y realidad se encuentra en el lenguaje'. \textelp{} Es correcto que podemos leer desde la proposición que $p$ el hecho que la hace verdadera, pero eso no anuncia una armonía pre-establecida entre lenguaje y realidad. Es meramente \emph{un movimiento en la gramática} permitido por la regla de substitución: `la proposición que $p$' = `la proposición a la cual el hecho que $p$ hace verdadera'} Desde esta perspectiva es que Anscombe propone que se debe abandonar la inclinación a vincular los signos del lenguaje a algún referente en la realidad a la hora de análizar una proposición como hace ella con la segunda premisa del argumento parmenidiano.

Después de estudiar y abandonar la segunda premisa del argumento de Parmenides, Anscombe se fija en la primera premisa y dice: \blockquote[{\cite[5]{anscombe1981parmenides:pmc}}: That other arm of his first premise, which he does not in fact use, remains tantalizing. What he used was `Only that can be thought, which can be'; the other arm of his premise is `Only that can be, which can be thought'.]{Esa otra rama de su primera premisa, que él de hecho no usa, sigue siendo prometedora. Lo que el usó fue `Solo eso puede ser pensado, lo que puede ser'; la otra rama de su premisa es `Solo eso puede ser, lo que puede ser pensado'}. Entonces propone: \blockquote[{\cite[5]{anscombe1981parmenides:pmc}}: We might call this arm of the premise the `No Mystery' arm. If some way of charactherizing what can be thought could be found, then if this proposition is true, there's a quick way of excluding mysteries.]{Podemos calificar a esta rama de la premisa como la rama del `No misterio'. Si alguna manera de caracterizar lo que puede ser pensado puede encontrarse, entonces si esta proposición es verdadera, hay aquí una manera rápida de excluir los msiterios}. Sobre la rama que sí usa Parmenides, Elizabeth dirá que si se interpreta como \blockquote[Only what can exist or be the case can, without misunderstanding, logical error, or confusion, be thought to exist or be the case.]{Solo lo que puede existir o ser de hecho puede, sin malentendidos, error lógico, o confusión, ser pensado como existiendo o siendo de hecho} puede ser una proposición quizás aceptable. Sin embargo se enfocará en la rama de la premisa que Parmenides no usa, y se se concentrará entonces a describir en qué puede consistir caracterizar lo que puede ser pensado.

Only what can be thought of can exist
What is not can't be thought of
What is not can't be

Only what can be thought can be,
what is not cannot be thought
therefore what is not cannot be

He who thinks, thinks something
He who thinks what is not, thinks nothing
Therefore he who thinks what is not is not thinking

which is certainly an argument for what is not cannot be thought

whatever is going on, it can't be thinking if, if it is thinking, it is thinking what is not

however the ground for this is that what is not is nothing and this would lead to what is not cannot be...........

it is more natural to hold that what is nothing cannot be than to go via only what can be thought can be


Primero intenta el argumento cambiando el sujeto de la segunda premisa

además intenta poner wittingly, es decir, intenta esta forma:
Only what can be thought to be the case by someone who has in mind all the implications of what he thinks can be the case
but if this were true, nothing could be the case

Parece que dirige nuestra atención a las posibilidades del pensamiento

Si intentamos la negación de la proposición obtenemos

Puede haber lo que no puede ser pensado

Pero no sería satisfactiorio poder refutar esto?

Si pudieramos probar el principio de Parmenides podríamos decir

Entonces esto parece sugerir algo que puede caracterizar lo que puede ser pensado

Ahora bien Anscombe rechaza que afirmar que lo que puede decirse del todo se puede decir claramente implique afirmar que puede haber lo que no puede ser pensado

El misterio sería entonces una ilusión

Pero no hay realmente fundamento para esto, es un tipo de prejuicio

The issue is of what can or cannot be clarified or expressed clearly. Note that the candidate gloss on `can be grasped in thought' is not `can be presented in a sentence which has an unexceptionable non-contradictory sense', but rather `can be presented in a sentence which can be seen to have an unexceptionable non-contradictory sense'.

Could these two phrases be non-equivalent?

One is tempted to say: `If a sentence has a non-contradictory sense, then it can in principle be seen to have one---and vice versa.' The function of the phrase `in principle' would be to indiciate that a merely psychological or empirical inability to grasp something is irrelevant to our enquiry.

A logical formula may be too long for any human being to calculate its sense in a lifetime; but for all that (the thought goes) the formula would, if well formed, have a determinate sense. Something like this view must, I think, be attributed to the Wittgenstein of the Tractatus.

El asunto es sobre lo que puede o no puede ser clarificado o expresado claramente. Hay que notar que la explicación candidata de `puede ser captada en el pensamiento' no es `puede ser presentada en una oración que tenga un sentido irreprochablemente no-contradictorio', sino más bien `puede ser presentado en una oración que puede ser vista como teniendo un sentido irreprochablemente no-contradictorio'.

¿Podría estas dos frases ser no equivalentes?

Podríamos estar tentados a decir: `Si una oración tiene un sentido no-contradictorio, entonces podría en principio ser visto que lo tiene---y vice versa.' La función de la frase `en principio' sería indicar que una incapacidad para captar algo es irrelevante para nuestra indagación.

Una fórmula lógica podría ser muy larga como para que cualquier ser humano pudiera calcular su sentido en su vida; pero con todo y eso (va el pensamiento) la formula podría, si bien formada, tener un sentido determinado. Algo como esta visión debe, pienso, ser atribuída a el Wittgenstein del Tractatus.




#+END_SRC

Elizabeth enfatiza la indepencia del lenguaje respecto de la realidad,
y también A Parmenides le parece que emplear en el lenguaje o atribuir al pensamiento afirmaciones

La propuesta de Anscombe está apoyada en
Anscombe no cree que lo que no existe no pueda existir. Tampoco cree que lo que no es no puede ser pensado.
Parmenides diría que

**Anscombe le diría a Parmenides que puede evitar la auto-contradicción en lo que existe sin tener que decir que lo que no es no puede ser pensado.

A Anscombe le parece más adecuado decir con los antiguos que un pensamiento es posible porque la cosa misma no es posible.... pero esto no lo argumentaría como Parmenides, ella no diría que lo que no es no puede ser, tampoco diría que lo que no es no puede ser pensado... sin embargo su propuesta es que para evitar la contradicción en la existencia no es necesario afirmar estas premisas no creíbles puesto que el lenguaje y la realidad son independientes.

Parmenides no tienes que decir lo que no es no puede ser pensado

puedes decir solo eso que puede ser, es lo que puede ser pensado

podemos llamar a esto el no-mystery arm poque si pudiera encontrarse alguna manera de caracterizar lo que puede ser pensado, entonces si esta proposición es cierta entonces aquí hay una manera rápida de excluir misterios

entonces ansmcombe caracteriza lo que puede ser pensado como lo que puede ser presenado en una afirmación que puede ser visto que tiene un sentido irreprochablemente no-contradictorio

sin embargo esto no implica que puede haber lo que no puede ser pensado

Le interesa decir "solo eso que puede ser, eso puede ser pensado"
pero no en el sentido de que habla de las posibilidades del pensamiento

y la negación? puede haber lo que no puede ser pensado... esto le parece un prejuicio

entonces?

si se pudiera rebatir que puede haber lo que no puede ser pensado (ella piensa que es un prejuicio) entonces nadie podría presentar una oración y decir esto es verdad pero lo que dice es irreduciblemente enigmático (eso no es lo que ella quiere decir)
  esto no en el caso de mero nonsense o abracadabra

sino en el caso que algo no es nonsense, pero hay dificultades para declarar un sentido irreprochable para ello

entonces tendríamos que abandonar la posibilidad de que este sentido enigmático es una verdad?

-> Si pudieramos probar el principio de Parmenides, el brazo que no uso... podríamos decir que

ya que la oración no puede ser tomada como expresando un pensamiento claro

es decir

un pensamiento que esta claramente libre de contradicción o the algún otro desorden conceptual,

por lo tanto

no dice nada, y

por lo tanto

nada verdadero

y esto sería muy aceptable

podríamos quizás quedarnos suficientemente satisfechos de que una oración fuera en este sentido irreduciblemente enigmática y entonces podríamos convencernos a nosotros mismos de que tenemos el derecho a descartarla

esto sugiere como el sentido de puede ser captado en el pensamiento como puede ser presentado en una oración la cual puede ser vista como teniendo un sentido irreprochable y no-contradictorio

Cuál es la relación entre lo concebible y lo posible?
Tractatus armonía en la forma lógica
empiristas un hecho externo que es la causa de la imagen interna
Anscombe: can be grasped in thought = can be presented in a sentence which can be seen to have an unexcepltionable non-contradictory sense

Anscombe entonces propone un modo de caracterizar lo que puede ser pensado y desde esto lo que puede ser que sea sin recurrir a una explicación metafísica

esto lo hace también desde la perspectiva de que es la posibilidad de la cosa lo que hace posible la concepción

hace la distincion ente abracadabra?

más bien hace la distincion entre lo que tiene un sentido irreduciblemente enigmatico y lo que puede ser presentado en una oración
que pueda verse que tenga un sentido irreprochable no contradictorio

that which can't be grasped in thought

there is no claimant to be that which can't be grasped in thoguth

mystery would be an ilusion

either the thought expressing something msyterious could be clarified
and then no mistery

or the impossibility of clearing it up would show it was really a non-thought

\blockquote[{\cite[5]{anscombe1981parmenides:pmc}}: it is false that one mentions either properties or objects when one uses the quantifiers binding property variables and object variables; though it has to be granted that some authors, such as Quine, are accostumed to speak of the reference of variables. But if this is given up, as it ought to be, Parmenides is deprived of his claim that we are commited to self-contradiction in existence just because we are willing to use a self-contradictory predicate --- e.g. in the sentence saying that nothing has a self-contradictory predicate true of it --- so that our property-variable is admitted to range over self-contradictory properties.]{es falso que mencionamos propiedades u objetos cuando usamos cuantificadores para enlazar variables de propiedades con variables de objetos; aunque habría que reconocer que algunos autores, como Quine, están acostumbrados a hablar de la referencia de las variables. Pero si esto es abandonado, como debería de serlo, Parmenides queda privado de su declaración de que estamos comprometidos con la auto-contradicción en la existencia solo porque estamos dispuestos a usar un predicado auto-contradictorio --- por ejemplo en la oración diciendo que nada tiene un predicado auto-contradictorio verdadero de ello --- así que se le puede permitir a nuestra variable-propiedad abarcar también propiedades auto-contradictorias.}

This has to do with what it means to ``mean something''
her account of language here, what is it to mention something is the key

una variable no tiene que estar atada a una referencia como dice quine sino que puede ser empleada para evaluar la validez de una proposición teniendola como variable

Parmenides tiene como objetivo evitar la auto contradicción en lo que existe, Anscombe parece insistir en que no es creíble que lo que no es no puede ser pensado entonces lo que dice que cree es que lo que no es puede ser en el pensamiento y para parmenides esto es una auto contradicción (self-contradiction in what exists is just what I set out to avoid, and you pretended that I could do that without accepting the conclusion ``What is not cannot be thought'' But your insistence that what is not can be has landed you in self-contradiction after all...)

Anscombe está hablando del lenguaje aquí como algo que no está atrapado por la realidad (no es representativo), sino como dice en qli es como una herramienta que tiene el logical shape de la esencia que expresa.

Para él ``ser'' es el término que expresa el ser, sin embargo, otros términos que no son nombres de nada son también nombres del ser, \blockquote[{\cite[x]{anscombe1981parmenides}}: What they express is what is true of being, so they characterize it as well as naming it]{Lo que expresan es lo que es verdadero del ser, así que lo caracterizan además de denominarlo.}

dificultad para entender a qué se refiere con being

Si combinamos esto con su idea de que ser es un objeto entonces obtenemos sus resultados más alocados

la segunda premisa entendida en sensu diviso ya sea como: lo que no existe no puede existir como lo que no es el caso no puede ser el caso no es creíble

también hay una dificultad sobre los dos caminos del conocimiento

lo notable es la combinación de es con no puede no ser y no es con no puede ser: el argumento para esto es lo que no es es nada y no es posible que lo que es nada sea; por tanto lo que sea que puede ser debe ser, y lo que puede ser pensado debe ser; puesto que es lo mismo que lo que puede ser.

 Concerning \emph{being} ($x$) which \emph{can be} ($F$), such that
\emph{being} ($x$) not (${\sim}$) \emph{can be} ($F$) it follows that
($\longrightarrow$) necesarily ($Nec$) not (${\sim}$) \emph{being} ($x$) which
\emph{can be} ($F$)

$Nec\enspace (F)\enspace (\exists x)\enspace Fx$
Necesarily concerning there exists a being which can be, being can be

Necesarily concerning a being which not existent can be, not being can be
#+END_SRC
**** La primera Premisa
#+BEGIN_SRC latex

#+END_SRC
