#+PROPERTY: header-args:latex :tangle ../../tex/ch3/diacronico/pmc.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

** TODO Parmenides, Mystery and Contradiction (1969) [50%]
>> escribir una síntesis de lo que anscombe hace y entonces redactar...
#+BEGIN_SRC latex
  \subsection{Parmenides, Mystery and Contradiction}
#+END_SRC
*** DONE Información del texto
    CLOSED: [2019-08-21 Wed 13:27]
    :LOGBOOK:
    CLOCK: [2019-08-22 Thu 07:25]--[2019-08-22 Thu 07:50] =>  0:25
    :END:
#+BEGIN_SRC latex
  En 1981 Anscombe publicó una colección de sus escritos en tres volúmenes
  llamados \emph{The Collected Philosophical Papers of G.\,E.\,M.\,Anscombe}. El
  primero de estos, titulado \emph{From Parmenides to Wittgenstein}, recoge un tema
  presente en el \emph{Tractatus} de Wittgenstein y que Anscombe trató con gran
  interés: la relación entre lo concebible y lo posible. En el contexto del
  pensamiento de Wittgenstein la cuestión de lo concebible se encuentra dentro de
  la discusión sobre lo que puede ser dicho claramente. Ahí se encuentran también
  característicos temas Wittgensteinianos como la falta de significado, el
  sinsentido, lo misterioso y lo inefable; nociones que estarán presentes en el
  análisis de Anscombe.

  El volumen reúne a autores como Parménides, Platón, Hume y Wittgenstein en la
  discusión sobre esta cuestión\footnote{Cf.~ \cite[193]{teichmann2008ans}:
    Philosophers have grappled since ancient times with the problem of how
    thinkability and possibility are related, and it is characteristic of Anscombe
    to have drawn such diverse figures as Parmenides, Plato, Hume, and
    Wittgenstein into a single discussion.} y, como es característico de
  Anscombe, en cada artículo se le encuentra identificando rutas interesantes
  tomadas por los distintos autores y profundizando todavía más por caminos de
  reflexión que ella juzga poco explorados o no valorados del todo.

  El primer artículo: \emph{Parmenides, Mystery and Contradiction}, es el texto de
  una ponencia ofrecida por Anscombe en la reunión del \emph{Aristotelian Society}
  en \emph{21, Bedford Square} en Londres el 24 de febrero de 1969. En esta
  discusión Elizabeth estudia la manera en que Parménides construye su argumento
  acerca de lo posible y lo concebible y qué oportunidades ofrece para un análisis
  de esta relación. Anscombe percibe en su época la tendencia propia del
  modernismo de deducir lo posible desde lo concebible, sin embargo le parece más
  atractivo el acercamiento de Parménides y los antiguos:
  \blockquote[{\cite[xi]{anscombe1981parmenides}}: It was left to the moderns to
  deduce what could be from what could hold of thought, as we see Hume to have
  done. This trend is still strong. But the ancients had the better approach,
  arguing only that a thought was impossible because the thing was impossible, or,
  as the Tractatus puts it, ``Was man nicht denken kann, das kann man nicht
  denken'': an \emph{impossible} thought is an impossible \emph{thought}.]{Se les
    dejó a los modernos el deducir lo que puede ser posible desde lo que puede ser
    sostenido en el pensamiento, como vemos hacer a Hume. Esta tendencia sigue
    siendo fuerte. Pero los antiguos tuvieron el mejor acercamiento, argumentando
    solo que un pensamiento sería imposible porque la cosa misma es imposible, o,
    como lo dice el Tractatus, ``Was man nicht denken kann, das kann man nicht
    denken'': un pensamiento \emph{imposible} es un \emph{pensamiento} imposible.}
#+END_SRC
*** TODO Análisis del Argumento de Parmenides
    :LOGBOOK:
    CLOCK: [2019-08-21 Wed 10:21]--[2019-08-21 Wed 10:46] =>  0:25
    :END:

**** El Argumento
+BEGIN_SRC latex
  Los razonamientos Parmenidianos ofrecen muchas oportunidades de reflexión a Elizabeth. Recoge entre ellos una argumentación sobre lo que puede existir y lo que puede ser pensado que le servirá como el foco de su análisis:
  \blockquote[{\cite[3]{anscombe1981parmenides:pmc}}: Parmenides' arguments runs:\\
  It is the same thing that can be thought and can be\\
  What is not can't be\\
  $\therefore$ What is not can't be thought\\
  Ver también en {\cite[22--25]{parmenides2007poema}}: Algunos fragmentos relacionados con el argumento presentado por Anscombe pueden ser: \ldots\textgreek{τὸ γὰρ αὐτὸ νοεῖν ἐστίν τε καὶ εἶναι.} (III); \textgreek{Χρὴ τὸ λέγειν τε νοεῖν τ' ἐὸν ἔμμεναι· ἔστι γὰρ εἶναι, μηδὲν δ' οὐκ ἔστιν} (VI); \textelp{} \textgreek{οὐ γὰρ φατὸν οὐδὲ νοητόν ἔστιν ὅπως οὐκ ἔστι.} (VIII)]{El
    argumento de Parmenides va así:\\
    Es la misma cosa lo que puede ser pensado y lo que puede ser\\
    Lo que no es no puede ser\\
    $\therefore$ Lo que no es no puede ser pensado} En otro lugar Anscombe plantea el mismo argumento de esta otra manera: \blockquote[{\cite[vii]{anscombe1981parmenides}}: Parmenides himself argues: What can be thought can be, What is nothing cannot be, Therefore whatever can be actually is. Therefore whatever can be thought actually is.]
  {Lo que puede ser pensado puede ser,\\
    Lo que es nada no puede ser,\\
    Por tanto lo que sea que pueda ser es de hecho.\\
    Por tanto lo que sea que pueda ser pensado es de hecho.} Una lectura poco atenta podría dejar la impresión de que el argumento consiste en: \blockquote[{\cite[vii]{anscombe1981parmenides}}: Only what can be thought can be, What is not cannot be thought, Therefore what is not cannot be.]
  {Solo lo que puede ser pensado puede ser,\\
    Lo que no es no puede ser pensado,\\
    Por tanto lo que no es no puede ser.} Sin embargo, Parmenides no argumentó así.\footnote{Cf.~\cite[6]{anscombe1981parmenides:pmc}: \textelp{} one might, if reading inattentively, think that Parmenides did argue like that.} La segunda premisa del argumento, las proposiciones \enquote{Lo que no es no puede ser} o \enquote{Lo que es nada no puede ser}, están basadas en que \enquote{Lo que no es, es nada}\footnote{Cf.~\cite[vii]{anscombe1981parmenides}: these arguments \textelp{} use as a premise: What is not is nothing}. El argumento, por tanto, \blockquote[{\cite[vii]{anscombe1981parmenides}}: \textins{doesn't} derive the nothingness of what-is-not from its unthinkability, but rather unthinkability from its nothingness or from its impossibility.]{no deriva la inexistencia de lo-que-no-es de su ser inconcebible, sino más bien su ser inconcebible desde su inexistencia o su imposibilidad.} Y así Anscombe insiste: \blockquote[{\cite[viii]{anscombe1981parmenides}: If I am right, the ancients never argued from constraints on what could be a thought to restrictions on what could be, but only the other way around.}]{Si estoy en lo correcto, los antiguos nunca argumentaron desde las limitaciones de lo que podría constituir un pensamiento a las restricciones sobre lo que puede ser, sino en la manera inversa.}

  Esta segunda premisa todavía ofrece más vía de reflexión. La modalidad según la
  cual sea interpretada le otorga distintas acepciones. Entendida \emph{in sensu
    composito}, es decir, como una proposición general, la verdad de la premisa
  \enquote{Lo que no es no puede ser} puede ser entendida como la imposibilidad de
  la afirmación \enquote{Lo que no es,
    es}.\footnote{\cite[Cf.~][vii]{anscombe1981parmenides}: \textelp{} the
    impossibility of the proposition ``What is not is'' ---i.e. the truth of
    ``What is not cannot be'', taken in \emph{sensu composito}} Si, por otra
  parte, se entiende \emph{in sensu diviso}, o como una proposición particular,
  puede ser interpretada como \blockquote[{\cite[3]{anscombe1981parmenides:pmc}}:
  Concerning that which is not, it holds that \emph{that} cannot be]{Concerniendo
    aquello que no es, se sostiene que \emph{eso} no puede ser}.

  Ahora bien, Anscombe establece que el argumento completo no es valido si esta
  segunda premisa es entendida \emph{in sensu composito}. Sin embargo, si se
  interpreta \emph{in sensu diviso}, la premisa misma no es creíble. Esto lo
  explica diciendo: \blockquote[{\cite[vii]{anscombe1981parmenides}}: The
  impossibility of what is not isn't just the impossibility of the proposition
  ``What is not, is'' ---i.e. the truth of ``What is not cannot be'', taken
  \emph{in sensu composito}. \emph{That} could be swept aside as irrelevant. What
  is not can't be indeed, but it may come to be, and in this sense what is not is
  possible. When it \emph{has} come to be, of course it no longer is what is not,
  so in calling it possible we aren't claiming that ``What is not is'' is
  possible. So it can't be shown to be impossible that it should come to be just
  by pointing to the impossibility that it is. ---But this can't be the whole
  story. That what is not is nothing implies that there isn't anything to come to
  be. So ``What is not can be'' taken in \emph{sensu diviso}, namely as:
  ``Concerning what is not, \emph{that} can be'' is about nothing at all. If it
  were about something, then it would be about something that is not, and so
  there'd be an example of ``What is not is'' that was true.]{La imposibilidad de
    lo que no es, no es solo la imposibilidad de la proposición ``lo que no es,
    es'' ---es decir, la verdad de ``Lo que no es no puede ser'', tomado \emph{in
      sensu composito}. \emph{Eso} puede ser descartado como irrelevante. Lo que
    no es, ciertamente no puede estar siendo, pero puede llegar a ser, y en este
    sentido lo que no es es posible. Cuando \emph{haya} llegado a ser, ciertamente
    ya no es lo que no es, así que en llamarlo posible no estamos declarando que
    ``Lo que no es, es'' es posible. Entonces no puede mostrarse como imposible
    que pueda llegar a ser solo por señalar la imposibilidad de que este siendo.
    ---Pero esta no puede ser toda la historia. Que lo que no es, es nada implica
    que no hay nada ahí para llegar a ser. Así ``Lo que no es puede ser'' tomado
    en \emph{sensu diviso}, digase como: ``Con respecto a lo que no es, eso puede
    ser'' es acerca de nada en absoluto. Si fuera acerca de algo, entonces sería
    sobre algo que no es, y así habría un ejemplo de ``Lo que no es, es'' que
    sería verdadero.} Si la premisa se toma en sentido general su significado es
  irrelevante para el argumento. Si se toma en sentido particular es relevante
  para el argumento, pero es una proposición que no es creíble; lo mismo ocurre
  con la conclusión: \blockquote[{\cite[3]{anscombe1981parmenides:pmc}}:
  Concerning that which is not, it holds that \emph{that} cannot be thought.]{Con
    respecto a aquello que no es, se sostiene que \emph{eso} no puede ser pensado}
  la cual también es increíble.

  En el análisis de esta premisa Anscombe hace una distinción que caracteriza su
  punto de vista sobre lo concebible y lo existente. Destaca que Parmenides actua
  en su argumentación bajo \blockquote[{\cite[x]{anscombe1981parmenides}}:
  \textelp{} the assumption that a significant term is a name of an object which
  is either expressed or characterized by the term.]{\textelp{} el presupuesto de
    que un término significativo es un nombre de un objeto que queda expresado o
    caracterizado por el término.} Para él ``ser'' es el término que expresa el
  ser, sin embargo, otros términos que no son nombres de nada son también nombres
  del ser, \blockquote[[x]{anscombe1981parmenides}}: What they express is what is
  true of being, so they characterize it as well as naming it]{Lo que expresan es
    lo que es verdadero del ser, así que lo caracterizan además de denominarlo.}
  Si combinamos esto con su idea de que ser es un objeto entonces obtenemos sus
  resultados más alocados

  ``Being'' puede ser un nombre abstracto, equivalente al infinitivo ``to be'', pero
  Parmenides no trata to be como un objeto, sino being, something being or some
  being thing.

  Es dificil usar el participio en inglés en el modo requerido, y podemos
  acercarnos al sentido diciendo ``what is''

  Una dificultad similar se encuentra en su descripción de las dos rutas del
  pensamiento
  es, y no puede ser
  no es y necesariamente no puede ser

  These are the only ways of enquiry for thought: one 'is and cannot not be'... the
  other 'is not, and needs must not be'

  ἔστιν τε καὶ ὡς οὐκ ἔστι μὴ εἶναι,

  οὐκ ἔστιν τε καὶ ὡς χρεών ἐστι μὴ εἶναι,

  lo notable de esto es la
  combinación de ``es'' con ``no puede no ser''
  y ``no es'' con ``no puede ser''

  Esto necesita argumento: hemos visto cuál es:
  lo que no es es nada, y no es posible para lo que es nada que sea
  y por tanto, ambos
  lo que sea que puede ser tiene que ser, y lo que pueda ser pensado tiene que
  ser;
  puesto que es lo mismo que lo que puede ser



  the proposition shows how things are if it is true, and says that is how they
  are (whether it is asserted or not)

  w has language pinned to reality

  Parmenides opera bajo el presupuesto de que ..

  Detrás de este análisis está la distinción hecha por Anscombe entre lo
  mencionado como existente y lo sostenido en la proposición. (puede predicarse en
  una proposición algo que no es posible o contradictorio sin afirmar lo
  contradictorio en la existencia)

  sentido y
  objeto. El sentido de la afirmación es su uso

  no pretendimos mencionar nada cuando dijimos ``Con respecto a lo que no es''

  de la segunda premisa como no creíble está el juicio de
  Anscombe de que Parmenides tiene en su argumentación
  \blockquote[{\cite[x]{anscombe1981parmenides}}: \textelp{} the assumption that a
  significant term is a name of an object which is either expressed or
  characterized by the term.]{\textelp{} la suposición de que un término
    significativo es un nombre de un objeto que queda expresado o caracterizado
    por el término.}

  For Parmenides, as for Plato, ``being'' is the only term that expresses
  being, but for Parmenides such other terms as are not names of nothing are other
  names of being.

  What they express is what is true of being, so they characterize it as well as
  naming it.


  consiste en que emplear
  un predicado autocontradictorio en una oración no implica que estamos
  comprometidos con la autocontradicción en la existencia. No es cierto que cuando
  usamos cuantificadores para unir variables de propiedades con variables de
  objetos estamos mencionando propiedades u objetos.

  % Si estoy en lo correcto, los antiguos nunca argumentaron desde las limitaciones
  % de lo que puede constituir un pensamiento a las restricciones de lo que puede
  % ser, sino al reves.

  % los antiguos argumentaron desde las restricciones de lo que puede ser cuales son
  % las limitaciones de lo que puede constituir un pensamiento

  % yayayayaya aquí está!!!!!!!!!!!!!!

  % la magnitud de lo que puede existir es la que dicta lo que puede llegar a
  % constituir un pensamiento!!!!!

  % parmenides llega a decir que el ser único tiene muchos nombres, lo único que no
  % es el ser es lo que no es.

  % Aquí hay algo relacionado con que denominamos lo que es....

  % Anscombe juzga que el argumento completo es válido sólo si se entie

  % Anscombe se fija en varias cosas:

  % en primer lugar:
  % x
  % the assumption that a significant term is a name of an object which is either
  % expressed or characterized by the term.

  % For Parmenides ... ``being'' is the only term that expresses being, but ... such
  % other terms as are not names of nothing are other names of being.

  % What they express is what is true of being, so they characterize it as well as
  % naming it.

  % If we take Parmenides as simply warning us off the path of thinking there are
  % things that do not exist, then he seems no more than good sense. But when we
  % combine this with the idea that being is an object, we get his wilder results.

  % being is treated as an object (what is)
  % to be is not treated as an object

  % similar difficulty about Parmenides' description of the two paths of thought

  % La conclusió será

  % pero antes de llegar a esto da varios pasos

  % Anscombe analizará estas dos premisas y su conclusión y llegará a una conclusión
  % equivalente a la afirmación Wittgensteiniana:
  % \blockquote[{\cite[8]{anscombe1981parmenides:pmc}}: ``whatever can be said at
  % all can be said clearly'']{todo lo que puede ser expresado en absoluto puede ser
  %   expresado claramente}.

  % Estas premisas y su conclusión
  % son las que Anscombe utilizará en su análisis.


#+END_SRC
**** Segunda Premisa
     :LOGBOOK:
     CLOCK: [2019-08-22 Thu 05:35]--[2019-08-22 Thu 06:00] =>  0:25
     :END:
#+BEGIN_SRC latex
#+END_SRC
