#+PROPERTY: header-args:latex :tangle ../../tex/ch3/sincronico/quaestio_episteme.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* Valor espistemológico del testimonio [%]
#+BEGIN_SRC latex
\subsection{¿Cuál es el valor espistemológico del testimonio?}
#+END_SRC

#+BEGIN_SRC latex
\emph{Creer y Conocer}, de Francisco Conesa, es una investigación sobre el valor cognoscitivo de la fe en la filosofía analítica. En su estudio, Conesa sitúa a Anscombe entre los autores que \blockquote[{\cite[84]{conesa1994cc}}]{entienden la fe primordialmente como un saber por testimonio.} El análisis que el autor ofrece como fundamento para este modo de entender la perspectiva de Anscombe se enfoca en dos puntos. El primero es que para Anscombe el significado de la palabra `fe' es `creer a Dios'. Conesa resume este punto refiriéndose a la discusión del artículo \emph{Faith}: \blockquote[{\cite[87--88]{conesa1994cc}}]{<<En la tradición donde el concepto tiene su origen, \emph{fe} es una abreviación de \emph{fe divina} y significa \emph{creer a Dios}>>. Y ¿qué puede significar \emph{creer a Dios}? Todos los casos de <<creer a ``$x$''>> suponen que ``$x$'' habla. Que alguien tiene fe quiere decir que cree que algo es palabra de Dios: <<fe es la creencia que él presta a esa palabra>>.} El segundo tema que compone la explicación de Conesa es del artículo \emph{Hume and Julius Caesar}: \blockquote[{\cite[88]{conesa1994cc}}]{Creer en el testimonio es muy distinto de creer en causas y efectos. Este punto es desarrollado por la filósofa al estudiar el conocimiento histórico: <<Creer en un relato histórico es absolutamente creer que ha habido una cadena de tradición de relatos y documentos que llega hasta el conocimiento contemporáneo; no es creer en los hechos históricos mediante una inferencia que vaya siguiendo cada nudo de esa cadena>>.}

Desde el punto de vista de Conesa, este modo de entender la `fe', como `saber por testimonio', sirve para caracterizar el valor cognoscitivo que tienen las creencias que se sostienen sobre el fundamento de la fe. Su propuesta es que: \blockquote[{\cite[88]{conesa1994cc}}]{Desde esta perspectiva comprendemos el valor epistemológico de la fe religiosa, que consiste en \emph{creer a Dios}. Ella forma parte de ese conocimiento que depende del testimonio de otros. En este caso, además, creemos a alguien que conoce. Entonces es claro que accedemos a su conocimiento.} Aquí el autor afirma que el valor epistemológico que tiene la fe es el del `saber por testimonio', y en pocas palabras describe el valor epistemológico de este saber como el conocimiento al que accedemos cuando creemos a alguien que conoce, en este caso a Dios. En este apartado veremos con más detalle cómo Anscombe describe el valor epistemológico de estas creencias que sostenemos por el testimonio que hemos recibido. Las dos cuestiones que Conesa tiene en cuenta al valorar el pensamiento de Elizabeth nos servirán como marco de referencia para esta discusión.
#+END_SRC

#+BEGIN_SRC latex
\subsubsection{La `estructura' de creer en el testimonio}
#+END_SRC

#+BEGIN_SRC latex
Mary Geach, hija de Anscombe, cuenta una anécdota que le escucho a su madre; cuando Elizabeth estaba en sus estudios universitarios se topó con un pasaje de Russell que sostenía que un argumento construído desde los datos del mundo no sería válido para afirmar la existencia de Dios, pues no es posible deducir una conclusión necesaria desde una premisa contingente. En ese momento Anscombe no sabía qué hay de erroneo en la noción de que las necesidades solamente pueden ser deducidas de premisas necesarias, sin embargo, sí sabía que el negar la posibilidad de conocer de la existencia de Dios por medio de las cosas creadas a la luz de la razón era negar una doctrina de fe definida por la enseñanza de la Iglesia. Deicidió, entonces, ir a una Iglesia y hacer un acto de fe. Más tarde en su carrera filosófica llegó a ver cómo argumentar que pueden deducirse conclusiones necesarias de premisas contingentes, pero en aquel momento su acto de fe le evitó caer en un error. Mary destaca un aspecto interesante de esta anécdota: \blockquote[{\cite[xvi--xvii]{anscombe2008faith}}: \enquote{Faith, \textelp{} is believing God, but this story shows how public she believed the voice of God could be, speaking as it has done in the teaching of the Church.}]{La fe, \textelp{} es creer a Dios, y esta historia muestra cuán pública ella creía que la voz de Dios puede ser, hablando como lo hace en la enseñanza de la Iglesia.} Es difícil entender bien el modo en que Elizabeth habla de la fe si no se tiene en cuenta esta creencia suya. Anscombe habla de Dios como uno que está involucrado en la actividad humana del lenguaje, tiene una `voz pública'. Mary Geach añade a su reflexión de la anécdota que \blockquote[{\cite[xvii]{anscombe2008faith}}: \enquote{philosophers nowadays accept on authority much that they do not themselves have the expertise to know firsthand, and they do not see it as a limitation on their freedom]{hoy en día los filósofos aceptan }

\blockquote[{\cite[xvi--xvii]{anscombe2008faith}}: \enquote{To proceed on the assumption that this teaching is true is seen by some as a limitation on one's freedom, but this is only the case if the Church does not have the teaching authority she claims to have.}



En la introducción de \emph{Faith in a Hard Ground}, uno de los volúmenes de la colección de escritos de Anscombe publicados póstumamente, Mary Geach, hija de Elizabeth, cuenta una anécdota que le narró su madre.

En el núcleo de los artículos \emph{What is it to believe someone?} y \emph{Faith} está la propouesta de que

\blockquote[Faith, she says in a paper published here, is belieivng God, but this story shows how public she bleieved the voice of God could be, speaking as it has done in the teaching of the Church.]{}
Anscombe nos ofrece un
what is it to believe.... presuppostions

defeseability theory

original authority

hume and.... believe in the chain because we believe in the event



Anscombe dice que creer en el testimonio es un creer bastante distinto en estructura
que creer en causas y efectos.

Parece que habla de esto en hume and julius caesar y en grounds for belief

puede decirse lo siguiente?

la estructura de creer en el testimonio es la estructura de creer en alguien
la estructura de creer en alguien es

dados los presupuestos
A Nota la comunicación
A Toma la comunicación como lenguaje
A Toma la comunicación como dirigda a él
A Interpreta la comunicación correctamente
A Cree que viene de NN

confiar en NN acerca de la verdad de x cuando una comunicación de NN llega a A por medio de un productor inmediato.

La estructura de creer en el testimonio de alguien
si entendemos creer en el testimonio de alguien como
creer a x que p

es la estructura de la fe tambien

cual es esa estructura?
dados ciertos presupuestos
x confia en NN acerca de la verdad de p

podemos sacar una descripción de
la categoría del testimonio

de las interconexiones que Anscombe describe
en el "arco" de la verdad, el sentido y la aserción
enunciar y significar son distintos
la rectitud propia de lo que la verdad es aplica tanto a la persona que enuncia como al enunciado

la persona puede mentir
el enunciado falso cuando es creido significa algo pero no enuncia nada.

la paradoja, distinto de el enunciado falso no significa nada.

el enunciado verdadero hace rectamente aquello para lo que se creó
la persona que dice una proposición verdadera actua rectamente

creer a alguien que dice una proposición verdadera es reconocer la rectitud de la aserción y reconocer la rectitud de la persona que habla

hay, por tanto un modo de conocer la verdad que se puede describir como

dados los presupuestos
confiar en NN acerca de la verdad de una proposición
cuando la proposición es verdadera tiene rectitud perceptible a la mente
NN actua con rectitud
cuando la proposición es falsa aunque signifique algo no dice nada
cuando la proposición es una paradoja no significa ni comunica nada

la rectitud es perceptible a la mente sin tener que acudir a la experiencia



En un argumento que tiene caracter de revocabilidad esencial la razonabilidad de un juicio o conocimiento formado a partir de éste reclama un apoyo externo a sus premisas. En el caso del creer a alguien que p el que alguien crea lo que dice es este apoyo

Anscombe habla del testigo como una autoridad original, `que él mismo contribuye algo' en oposición a simplemente transmitir una información recibida sin embargo se puede decir que se cree a x que p sin que este sea una autoridad original

Se abren tres rutas desde aquí sobre la primacia de la verdad la fe como creer a Dios que p sobre la estructura del testimonio de la estructura del testimonio se pasa a Hume on Miracles, de ahí a Prophecy and Miracles





#+END_SRC


#+BEGIN_SRC latex
\subsubsection{Traditional knowledge}
#+END_SRC

#+BEGIN_SRC latex
The work of determining England and fixing the meaning of the name \emph{would} depend on testimony\,---\,the testimony of many different people for different parts of it. The work done, people could be taught what Engalnd was (no doubt still disputing some regions). Now those who learned thereafter can hardly be said to have knowledge by testimony. They were taught to \emph{call} something `England'\,---\,something indeed which could in large part only be defined for them by hearsay; and they so taught those who came after them. I am an heir of this tradition. Now, I know I live in England. But by testimony? Some would say so. But there is something queer about it. \emph{What} do I know? That the world is divided up into countries which have names, and that the one I live in is called England and is here on the map of the globe. This involves understanding the use of the globe to represent the earth. It is rather as if I had been taught to join in \emph{doing} something, than to believe something\,---\,but because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge; for here knowledge is no other that certainly correct belief in pursuit of a practice. But the connection with testimony is remote and indirect.
#+END_SRC


in a world-view to believe is not to surmise
in a religious belief to believe is not to surmise
a world-view and a religious belief are not the same

In grounds of belief she makes a distintion between tradition or common knowledge and testimony, arguing that things justified on being thaught are justified on something thicker than testimony. Tradition or common knowledge is described by her as being thaught to join in doing something, not to believe something. But because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge. _Here knowledge is no other than certainly correct belief in pursuit of a practice. But the connection with testimony is remote and
indirect._


What is it to believe someone ends with the problem about the priority of rightness and
truthfulness, this connects with the idea of anselm and anscombe that a true
proposition is doing what it ought

teichmann touches this in p 223

That assertion can have the function or purpose ascribed to it by Anselm (see above, p.
196)—i.e. that there can be such a thing as assertion—depends on the empirical fact,
among others, that people don’t generally reject their earlier assertions as unfounded.
It is ‘by favour of Nature’ that assertion and knowledge are possible (On Certainty,
para. 505); for Anselm and for Anscombe, it is (also) by the grace of God.
