#+PROPERTY: header-args:latex :tangle ../../tex/ch3/sincronico/quaestio_theosignificans.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* TODO Valor proposicional del lenguaje teológico [0%]
#+BEGIN_SRC latex
\subsection{¿Tiene carácter veritativo el lenguaje religioso?}
#+END_SRC

** El modo más sencillo de expresar lo que es la transubstanciación...
#+BEGIN_SRC latex
\subsubsection{\enquote{El modo más sencillo de expresar lo que es la transubstanciación\ldots}}
#+END_SRC
*** Propuesta de tres características: no contradicción, se puede expresar, el todo de la religión no son proposiciones de misterios de fe
#+BEGIN_SRC latex
A lo largo de la discusión de los artículos de Anscombe es posible distinguir en ella una posición clara acerca de la actitud con la que un creyente sostiene esas creencias que dentro de la fe católica llamamos `misterios': \enquote*{Esto puede ser demostrado falso, pero aún así lo creo} no es para nada una actitud de fe, es decir, sostener este tipo de creencias no consiste en una disposición a profesar la contradicción. En esto, creer un misterio no es lo mismo que creer cosas ilógicas o sin sentido.

Junto a esta noción, se encuentra también en ella la interesante idea de \enquote*{expresar el misterio}, posibilidad que caracteriza diciendo: \enquote*{puede ser enseñado}; a un niño, por ejemplo. Y en esto también hay algo que empieza a diferenciar una afirmación relacionada con una creencia de fe de afirmaciones que no expresan pensamiento o que no tienen significado.

Dentro del pensamiento de Anscombe, además, el todo del lenguaje relacionado con la religión no está compuesto solamente por afirmaciones que expresan creencias en misterios de fe, sino que además utiliza proposiciones de teología natural y proposiciones sobre las presuposiciones involucradas en creer a Dios.
#+END_SRC
*** Si vemos en W. su actitud ante las proposiciones religiosas, asemejaba el todo de la religion a los misterios y trataba con respeto la contradicción
#+BEGIN_SRC latex
Para profundizar más en el pensamiento de Anscombe sobre estas características que describen el modo en el que el lenguaje religioso es lenguaje significativo, es útil comparar su postura con la de Wittgenstein.

En el \emph{Tractatus}, termina ocupando un lugar prominente lo \enquote*{inexpresable, lo que se muestra; que es lo místico} (\S6.522). En esta categoría de `lo que no puede ser dicho pero queda mostrado', se encuentran las proposiciones éticas y estéticas: \blockquote[{\cite[\S6.421]{wittgenstein1922tractatus}}: \enquote{It is clear that ethics cannot be expressed. Ethics is transcendental. (Ethics and aesthetics are one.)}]{Queda por tanto claro que la ética no puede expresarse mediante palabras. La ética es transcendental. (La ética y la estética son una y la misma.)}. Wittgenstein tuvo gran interés por esto que consideraba una tendencia de la mente humana: el deseo de poner en palabras lo que no puede ser dicho. Esta tendencia la reconocía en el corazón de la ética, cuyas proposiciones juzgaba como sinsentido, aunque su actitud hacia ellas era de respeto.\footnote{\cite[Cf.~][211]{teichmann2008ans}: \enquote{In his `Lecture on Ethics' of 1929, he cites certain experiences, saying of them that their natural expression takes the form of utterances which can only count as nonsensical, as attempts to `\emph{go beyond} the world and that is to say beyond significant language'. These experiences and utterances he takes to be at the heart of ethics, anout which he writes:`it is a document of a tendency in the human mind which I personally cannot help respecting deeply and I would not for my life ridicule it'.}}

A la ética y la estética ha de añadirse la religión. Este tipo de proposiciones también intentan ir más allá del mundo y de lo que puede considerarse como lenguaje significativo y por tanto estos intentos de poner en palabras lo que no puede ser dicho también constituyen afrimaciones sin sentido. Sin embargo, su actitud hacia las afirmaciones religiosas ---así como hacia la ética--- era tomarlas en serio con respeto. En este sentido puede entenderse la anecdota recordada por Anscombe en \emph{The Question of Linguistic Idealism}. Wittgenstein prefería tratar con respeto las proposiciones religiosas en tanto que contradictorias, puesto que rechazaba la idea de considerar la religión como racional. Así es que el intento de presentar la religión como algo que pudiera ser visto como racional le parecía que era como encerrar un objeto irregular dentro de una lisa esfera de cristal; las irregularidades no dejan de ser visibles, así que consideraba más adecuado atender el objeto sin disimularle sus aristas. En esto Anscombe se apoya para decir que la  actitud de Wittgenstein al todo de la religión, en cierto modo, la asimilaba al misterio. Rechazaba las proposiciones de teología natural y no cabían dentro de su sistema de pensamiento. Hemos visto cómo el \emph{Círculo de Viena} interpretó el rechazo de las proposiciones de teología natural dentro del sistema de Wittgenstein. Anscombe reconoce que dentro del pensamiento de Ludwig la teología natural no es posible, pero ante la interpretación del \emph{Círculo} se mostró crítica:\blockquote[{\cite[78]{anscombe1959iwt}}: \enquote{Here it is worth remarking that the truth of the \emph{Tractatus} theory would be death to natural theology; not because of any jejune positivism or any `verificationism', but simply because of the picture theory of the `significant proposition'. For it is essential to this that the picturing proposition has two poles, and in each sense it represents what may perfectly well be true. Which of them is true is just what \emph{happens} to be the case. But in natural theology this is an impermissible notion; its propositions are not supposed to be the ones that happen to be true out of pairs of possibilities; nor are they supposed to be logical or mathematical propositions either.}]{Aquí vale la pena comentar que la verdad de la teoría del \emph{Tractatus} conllevaría la muerte de la teología natural; no por ningún inmaduro positivismo o ningún `verificacionismo', sino simplemente por la teoría de la imagen relacionada con lo que es una `proposición significativa'. Puesto que es esencial para esta que la proposición que ofrece una imagen tenga dos polos, y en cada sentido represente lo que pudiera ser perfectamente bien la verdad. Pero en la teología natural esto es una noción inadmisible; sus proposiciones no son tales que se supone que son las que de hecho son verdaderas de entre un par de posibilidades; ni se tiene por supuesto que sean proposiciones lógicas o matemáticas tampoco.} Aún cuando Wittgenstein abandonó en gran parte el modo de comprender el lenguaje descrito en el \emph{Tractatus}, siguió juzgando que el intento de razonar desde los objetos del mundo a algo fuera de este, como se pretende en las afirmaciones de la teología natural, no era posible. En \emph{The Question of Linguistic Idealism} Anscombe ofrece como evidencia de esta objeción una cita de \emph{Observaciones sobre los fundamentos de la matemática}: \blockquote[{\cite[VII, 25]{wittgenstein1956remmath}}: \enquote{A \emph{logical} conclusion is being drawn, when no experience can contradict the conclusion without contradicting the premises. I.e., when the inference is only a movement within the means of representation.}]{Se hace una inferencia \emph{lógica} cuando ninguna experiencia puede contradecir la conclusion porque entonces contradiría las premisas. Es decir, cuando la inferencia es solo un movimiento en los medios de la representación.} Elizabeth relaciona este comentario con la premisa de \emph{Investigaciones Filosóficas}: \blockquote[{\cite[\S126]{wittgenstein1953phiinv}}: \enquote{Philosophy just puts everythig before us, and neither explains nor deduces anything. --- Since everything lies open to view, there is nothing to explain. For whatever may be hidden is of no interest to us. The name ``philosophy'' might also be given to what is possible \emph{before} all new discoveries and inventions.}]{La filosofía meramente expone todo ante nosotros, y no explica ni deduce nada.\,---\,Ya que todo está abiertamente a la vista, no hay nada que explicar. Pues lo que sea que esté oculto no es de ningún interés para nosotros. Se podría llamar también ``filosofía'' a lo que es posible antes de todos los nuevos descubrimientos e invenciones.} Con esto, Anscombe hace referencia al argumento de Wittgenstein de que la actividad filosófica realiza sus inferencias dentro de los medios de representación que pueden ser usados por el lenguaje y los elementos que componen estos medios de representación no se obtienen desde deducciones de realidades ocultas, sino que están a la vista en la actividad misma de usar el lenguaje. Según esto, el intento de razonar desde los objetos del mundo sobre algo más allá del mundo está en contra de lo que Wittgenstein considera filosofía.



\blockquote[{\cite[211]{teichmann2008ans}}: It might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound to embrace nonsense or self-contradiction; for what \emph{is} a mystery such as that of the Trinity, or of the Incarnation, or of the Eucharistic Transubstantiation, if not something whose appearance of incoherence cannot be dispelled by reason? If somebody utters `I believe' in connection with such mysteries, won't we be entitled to say, along with Wittgenstein: `But is this a belief, a thought at all? Perhaps there is a state of enlightenment, or an urge to find expression for certain experiences of life---but for there to be a belief, you would need to be able, at least in principle, to state that belief clearly and without contradiction'?]{Puede ser pensado que una persona religiosa que considera ciertos artículos de fe como `misterios' está en mayor o menor grado obligada a abrazar el sinsentido o la auto-contradicción; pues ¿qué \emph{es} un misterio como el de la Trinidad, o el de la Encarnación, o el de la Transubstanciación Eucarística, si no algo cuya apariencia de incoherencia no puede ser disipada por la razón? Si alguien dice `Yo creo' en conexión con tales misterios, ¿no estaríamos autorizados a cuestionar, junto con Wittgenstein: `¿Pero es esto una creencia, un pensamiento en absoluto? Quizás haya ahí un estado de iluminación, o un deseo de encontrar expresión para ciertas experiencias de la vida\,---\,pero para que haya una creencia, deberías ser capaz, al menos en principio, de enunciar esa creencia claramente y sin contradicción'?}

verdad es uno de los nombres de Dios, para ella es un trascendental. Dios promete en lenguaje humano, se involucra en la actividad humana del lenguaje. Aquí es importante su comprensión de la fe como creer a alguien que se comunica, o entender alguna experiencia como palabra de Dios.

#+END_SRC
- Tractatus: ethics, aesthetics are things that are shown or show themselves, though they cannot be said or thought but can nevertheless be seen or understood
- For W. Religion should be added to that. He takes religious propositions as nonsensical and contradictory, and treats them with respect as such, this because he would rather have these not attempted to be presented as rational.
- Following this, it might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound embrace nonsense and contradiction
*** Anscombe tiene otra actitud: afirma la racionalidad
*** No se abraza la contradicción
*** Distingue proposiciones relacionadas con la religión: Hemos visto ejemplos:
**** presuposiciones
**** proposiciones de teología natural
**** expresiones de misterios
***** ward each attack
*** Distinguir entre superstición y religión
**** En qué sentido una religión es verdadera
**** Cómo se critica la superstición
**** En qué sentido puede ser verdadera una religión

** Poned en práctica la palabra y no os contentéis con oírla
#+BEGIN_SRC latex
\subsubsection{\enquote{Poned en práctica la palabra y no os contentéis con oírla\ldots}}
#+END_SRC

*** El modo en que Anscombe describe la explaición de enseñar el misterio tiene similitudes con su descripción de educar moralmente
**** Cuenta la anecdota de la frase en el manual de matemáticas
*** Worship es un verbo intencional
**** A qué apunta el verbo? `al único Dios verdadero'
*** El modo de actuar es creer a Dios, creer su promesa
**** Dios mismo, al prometer, lo hace en lenguaje humano
*** Creer en el misterio esta justificado por la tradición donde se enseña



** La mejor manera
+BEGIN_SRC latex
\subsubsection{``El modo más sencillo de expresar el misterio''}
#+END_SRC

*** Análisis de Teichmann
+BEGIN_SRC latex
Puntos de Teichmann
- Tractatus: ethics, aesthetics are things that are shown or show themselves, though they cannot be said or thought but can nevertheless be seen or understood
- For W. Religion should be added to that. He takes religious propositions as nonsensical and contradictory, and treats them with respect as such, this because he would rather have these not attempted to be presented as rational.
- Following this, it might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound embrace nonsense and contradiction
- In PMC Anscombe presents an alternative:
  + considers the view
  + compares this view with whatever can be said...
  + she goes on:

  \blockquote[{\cite[211]{teichmann2008ans}}: It might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound to embrace nonsense or self-contradiction; for what \emph{is} a mystery such as that of the Trinity, or of the Incarnation, or of the Eucharistic Transubstantiation, if not something whose appearance of incoherence cannot be dispelled by reason? If somebody utters `I believe' in connection with such mysteries, won't we be entitled to say, along with Wittgenstein: `But is this a belief, a thought at all? Perhaps there is a state of enlightenment, or an urge to find expression for certain experiences of life---but for there to be a belief, you would need to be able, at least in principle, to state that belief clearly and without contradiction'?]{Puede ser pensado que una persona religiosa que considera ciertos artículos de fe como `misterios' está en mayor o menor grado obligada a abrazar el sinsentido o la auto-contradicción; pues ¿qué \emph{es} un misterio como el de la Trinidad, o el de la Encarnación, o el de la Transubstanciación Eucarística, si no algo cuya apariencia de incoherencia no puede ser disipada por la razón? Si alguien dice `Yo creo' en conexión con tales misterios, ¿no estaríamos autorizados a cuestionar, junto con Wittgenstein: `¿Pero es esto una creencia, un pensamiento en absoluto? Quizás haya ahí un estado de iluminación, o un deseo de encontrar expresión para ciertas experiencias de la vida\,---\,pero para que haya una creencia, deberías ser capaz, al menos en principio, de enunciar esa creencia claramente y sin contradicción'?}

  Teichmann 212:
  It is an interesting question whether the later Wittgenstein can still be seen commited to the equivalence mentioned by Anscombe, between `can be grasped in thought' and `can be presented in a sentence which can be sen to have an unexceptionable non-contradictory sense', given a reading of `can be seen to have' which connects it with empirical human possibility. Whatever the answer to that question, the equivalence is rejected by Anscombe; or rather it is taken as wanting justification, as is shown by the closing words of PMC, which follow immediately after the passage just quoted: `The trouble is, there doesn't seem to be any ground for holding this position. It is a sort of prejudice' (PMC, 8).

  Anscombe would certainly admit that `can be grasped in thought' is incompatible with `can only be presented in a sentence with a contradictory sense' (****without the can be seen to have)
  What would W. say about illogical... what I would? that it isn't thinking?

  What Anscombe is trying to make room for is the idea of grasping a thought which cannot be cleared up, i.e. cannot be shown to have a non-contradictory sense. And this means: cannot be shown \emph{by us} to have a non-contradictory sense. She is reaising the possibility of a person's grasping a thought, even thought the sentence expressing it `cannot be seen to have an unexceptionable non-contradictory sense'---seen by us, that is. It is this idea that lies behind her account of what a mystery is:
  In the catholic faith...

  The departure from Wittgenstein consists in saying that we might be able to grasp a thought which we cannot clear up\,---\,cannot, because of our human finitude. The problem for Anscombe is how to distinguish a mystery from sheer nonsense.

  How then are we to know when to `take no notice', and when to take seriously?

  One reason why the doctrine of Transubstantiation is not \emph{mere} abracadabra is that you can teach it, explain it\,---\,or at any rate do something that looks like teaching and explaining.

  The child will understand and learn. Only, of course, on the assumption that these sentences do make sense; which is why, in the context of distinguishing mystery from e.g. philosophical nonsense, the data about teaching are inconclusive: for whole schools of philosophy have been based on the promulgation of enigmatic nonsense.

  You can show that `I can change the past' is an absurdity.
  For Anscombe, a (proper) Catholic will believe that this cannot be done for those articles of faith called `mysteries'.

  teichmann 220-221
  una explicación de por qué tenemos estas reglas anscombe rather than w. has demystified


#+END_SRC

*** Worship es un verbo intentional

*** Similitudes con enseñanza moral
+BEGIN_SRC latex
En on transubstantiation anscombe no propone que se anime al niño a visualizar en la mente, sino a entrar en una actividad

La respuesta se encuentra en On transubstantiation que es engañoso en su simplicidad

In grounds of belief she makes a distintion between tradition or common knowledge and testimony, arguing that things justified on being thaught are justified on something thicker than testimony. Tradition or common knowledge is described by her as being thaught to join in doing something, not to believe something. But because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge. \emph{Here knowledge is no other than certainly correct belief in pursuit of a practice. But the connection with testimony is remote and
indirect.}

Intentionality of sensation: Worship is an intentional verb

``Under a description''

On promising and its justice 16: What I have skteched here us what W. called a language-game and we may say it is a fact of nature that humans beings very readily take to it
17: what you do is not a move in the game unless the game is being played and you are one of the players

authority in morals: be ye doers, you have to do the math and the teacher can get you to do it, teaching morals, getting him to act, some truths about what is the case are revealed

IWT 170 Wittgenstein took the term over from Russell, who used it in a special way, with reference to an entirely ordinary feeling; one that is well expressed at 6,52: `We feel that even if all \emph{possible} scientific questions have been answered, still the problems of life have not been touched at all.' And his further comment on this: `Of course there then just is no question left, an just this is the answer.'

IWT 170 he speaks of people `to whom the meaning of life has become clear'. But he says of them that they have not been able to say it. Now such people have not failed for want of trying; they have usually said a great deal. He means that they have failed to state what they wished to state; that it was never possible to state it as it is possible to state indifferent truth. He probably had Tolstoy especially in mind, whose explanations of what he thought he understood are miserable failures; but whose understanding is manifested, and whose preaching comes through, in a story like \emph{Hadji Murad}.
#+END_SRC

** La verdad
+BEGIN_SRC latex
\subsubsection{La verdad como un transcendental}
#+END_SRC

+BEGIN_SRC latex
IWT 166 Thus when the \emph{Tractatus} tells us that `Logic is trascendental', it does not mean that the propositions of logic state transcendental truths; it means that they, like all other propositions, shew something that percades everything sayable an is itself unsayable. If it were sayable, then failure to accord with it would have to be expressible too, and thus would be a possibility.

Aquí trascendental no quiere decir que se refieren a verdades trascendentales, sino que \blockquote[{\cite[166]{anscombe1959iwt}}: \enquote{it means that they, like all other propositions, shew something that pervades everything sayable and is itself unsayable. If it were sayable}]{significa que estas, como todas las demás proposiciones, muestran algo que permea todo lo decible pero es en sí mismo indecible}.


#+END_SRC

** W. asemejaba el todo de la religion a los misterios; Teología natural  y lenguaje religioso
+BEGIN_SRC latex
\subsubsection{The possibility of natural religion}
#+END_SRC

+BEGIN_SRC latex
Anscombe distingue entre presuposiciones que

W. no distingue entre teologia natural y misterios... tampoco racionalidad de la fe.... QLI 123



IWT 78: Here it is worth remarking that the truth of the \emph{Tractatus} theory would be death to natural theology; not because of any jejune positivism or any `verificationism', but simply because of the picture theory of the `significant proposition'. For it is essential to this that the picturing proposition has two poles, and in each sense it represents what may perfectly well be true. Which of them is true is just what \emph{happens} to be the case. But in natural theology this is an impermissible notion; its propositions are not supposed to be the ones that happen to be true out of pairs of possibilities; nor are they supposed to be logical or mathematical propositions either.
#+END_SRC

** ward each attack
+BEGIN_SRC latex
\subsubsection{``Ward each attack as it comes''}
#+END_SRC

+BEGIN_SRC latex
IWT 161 `there is no picture that is true \emph{a priori}'. That is to say, if a proposition has a negation which is a perfectly good possibility, then it cannot be settled whether the proposition is true or false just by considering what it means.
#+END_SRC

** Creer a Dios
+BEGIN_SRC latex
\subsubsection{El extraordinario fenómeno de creer a Dios}
#+END_SRC

+BEGIN_SRC latex
Conesa 260: al creer a Dios, el hombre se apoya en la veracidad divina  y por lo mismo se confía al Dios de la verdad
#+END_SRC
