#+PROPERTY: header-args:latex :tangle ../../tex/ch3/sincronico/quaestio_theosignificans.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* Valor proposicional del lenguaje teológico [%]
#+BEGIN_SRC latex
\subsection{¿Tiene carácter veritativo el lenguaje religioso?}
#+END_SRC

** La mejor manera
#+BEGIN_SRC latex
\subsubsection{``El modo más sencillo de expresar el misterio''}
#+END_SRC

** La respuesta se encuentra en On transubstantiation que es engañoso en su simplicidad

teichmann 220-221
una explicación de por qué tenemos estas reglas anscombe rather than w. has demystified

En on transubstantiation anscombe no propone que se anime al niño a visualizar en la mente, sino a entrar en una actividad

W. no distingue entre teologia natural y misterios... tampoco racionalidad de la fe.... QLI 123

#+BEGIN_SRC latex

\blockquote[{\cite[211]{teichmann2008ans}}: It might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound to embrace nonsense or self-contradiction; for what \emph{is} a mystery such as that of the Trinity, or of the Incarnation, or of the Eucharistic Transubstantiation, if not something whose appearance of incoherence cannot be dispelled by reason? If somebody utters `I believe' in connection with such mysteries, won't we be entitled to say, along with Wittgenstein: `But is this a belief, a thought at all? Perhaps there is a state of enlightenment, or an urge to find expression for certain experiences of life---but for there to be a belief, you would need to be able, at least in principle, to state that belief clearly and without contradiction'?]{Puede ser pensado que una persona religiosa que considera ciertos artículos de fe como `misterios' está en mayor o menor grado obligada a abrazar el sinsentido o la auto-contradicción; pues ¿qué \emph{es} un misterio como el de la Trinidad, o el de la Encarnación, o el de la Transubstanciación Eucarística, si no algo cuya apariencia de incoherencia no puede ser disipada por la razón? Si alguien dice `Yo creo' en conexión con tales misterios, ¿no estaríamos autorizados a cuestionar, junto con Wittgenstein: `¿Pero es esto una creencia, un pensamiento en absoluto? Quizás haya ahí un estado de iluminación, o un deseo de encontrar expresión para ciertas experiencias de la vida\,---\,pero para que haya una creencia, deberías ser capaz, al menos en principio, de enunciar esa creencia claramente y sin contradicción'?}


In grounds of belief she makes a distintion between tradition or common knowledge and testimony, arguing that things justified on being thaught are justified on something thicker than testimony. Tradition or common knowledge is described by her as being thaught to join in doing something, not to believe something. But because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge. _Here knowledge is no other than certainly correct belief in pursuit of a practice. But the connection with testimony is remote and
indirect._



Intentionality of sensation: Worship is an intentional verb

``Under a description''

On promising and its justice 16: What I have skteched here us what W. called a language-game and we may say it is a fact of nature that humans beings very readily take to it
17: what you do is not a move in the game unless the game is being played and you are one of the players

authority in morals: be ye doers, you have to do the math and the teacher can get you to do it, teaching morals, getting him to act, some truths about what is the case are revealed


IWT 170 Wittgenstein took the term over from Russell, who used it in a special way, with reference to an entirely ordinary feeling; one that is well expressed at 6,52: `We feel that even if all \emph{possible} scientific questions have been answered, still the problems of life have not been touched at all.' And his further comment on this: `Of course there then just is no question left, an just this is the answer.'

IWT 170 he speaks of people `to whom the meaning of life has become clear'. But he says of them that they have not been able to say it. Now such people have not failed for want of trying; they have usually said a great deal. He means that they have failed to state what they wished to state; that it was never possible to state it as it is possible to state indifferent truth. He probably had Tolstoy especially in mind, whose explanations of what he thought he understood are miserable failures; but whose understanding is manifested, and whose preaching comes through, in a story like \emph{Hadji Murad}.

#+END_SRC

** La verdad
IWT 166 Thus when the \emph{Tractatus} tells us that `Logic is trascendental', it does not mean that the propositions of logic state transcendental truths; it means that they, like all other propositions, shew something that percades everything sayable an is itself unsayable. If it were sayable, then failure to accord with it would have to be expressible too, and thus would be a possibility.

** W. asemejaba el todo de la religion a los misterios; Teología natural  y lenguaje religioso
IWT 78: Here it is worth remarking that the truth of the \emph{Tractatus} theory would be death to natural theology; not because of any jejune positivism or any `verificationism', but simply because of the picture theory of the `significant proposition'. For it is essential to this that the picturing proposition has two poles, and in each sense it represents what may perfectly well be true. Which of them is true is just what \emph{happens} to be the case. But in natural theology this is an impermissible notion; its propositions are not supposed to be the ones that happen to be true out of pairs of possibilities; nor are they supposed to be logical or mathematical propositions either.

** ward each attack
IWT 161 `there is no picture that is true \emph{a priori}'. That is to say, if a proposition has a negation which is a perfectly good possibility, then it cannot be settled whether the proposition is true or false just by considering what it means.

** Creer a Dios
Conesa 260: al creer a Dios, el hombre se apoya en la veracidad divina  y por lo mismo se confía al Dios de la verdad
