#+PROPERTY: header-args:latex :tangle ../../tex/ch3/sincronico/quaestio_episteme.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* Valor espistemológico del testimonio [%]
#+BEGIN_SRC latex
\subsection{¿Cuál es el valor espistemológico del testimonio?}
#+END_SRC

#+BEGIN_SRC latex
\subsubsection{La `estructura' de creer en el testimonio}
#+END_SRC

#+BEGIN_SRC latex

what is it to believe.... presuppostions

defeseability theory

original authority

hume and.... believe in the chain because we believe in the event

#+END_SRC


#+BEGIN_SRC latex
\subsubsection{Traditional knowledge}
#+END_SRC

#+BEGIN_SRC latex
The work of determining England and fixing the meaning of the name \emph{would} depend on testimony\,---\,the testimony of many different people for different parts of it. The work done, people could be taught what Engalnd was (no doubt still disputing some regions). Now those who learned thereafter can hardly be said to have knowledge by testimony. They were taught to \emph{call} something `England'\,---\,something indeed which could in large part only be defined for them by hearsay; and they so taught those who came after them. I am an heir of this tradition. Now, I know I live in England. But by testimony? Some would say so. But there is something queer about it. \emph{What} do I know? That the world is divided up into countries which have names, and that the one I live in is called England and is here on the map of the globe. This involves understanding the use of the globe to represent the earth. It is rather as if I had been taught to join in \emph{doing} something, than to believe something\,---\,but because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge; for here knowledge is no other that certainly correct belief in pursuit of a practice. But the connection with testimony is remote and indirect.
#+END_SRC


in a world-view to believe is not to surmise
in a religious belief to believe is not to surmise
a world-view and a religious belief are not the same

In grounds of belief she makes a distintion between tradition or common knowledge and testimony, arguing that things justified on being thaught are justified on something thicker than testimony. Tradition or common knowledge is described by her as being thaught to join in doing something, not to believe something. But because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge. _Here knowledge is no other than certainly correct belief in pursuit of a practice. But the connection with testimony is remote and
indirect._


What is it to believe someone ends with the problem about the priority of rightness and
truthfulness, this connects with the idea of anselm and anscombe that a true
proposition is doing what it ought

teichmann touches this in p 223

That assertion can have the function or purpose ascribed to it by Anselm (see above, p.
196)—i.e. that there can be such a thing as assertion—depends on the empirical fact,
among others, that people don’t generally reject their earlier assertions as unfounded.
It is ‘by favour of Nature’ that assertion and knowledge are possible (On Certainty,
para. 505); for Anselm and for Anscombe, it is (also) by the grace of God.
