#+PROPERTY: header-args:latex :tangle ../../tex/ch3/sincronico/quaestio_theosignificans.tex
# -----------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* TODO Valor proposicional del lenguaje teológico [0%]
#+BEGIN_SRC latex
\subsection{¿Tiene carácter veritativo el lenguaje religioso?}
#+END_SRC

** El modo más sencillo de expresar lo que es la transubstanciación...
#+BEGIN_SRC latex
\subsubsection{\enquote{El modo más sencillo de expresar lo que es la transubstanciación\ldots}}
#+END_SRC
*** Propuesta de tres características: no contradicción, se puede expresar, el todo de la religión no son proposiciones de misterios de fe
#+BEGIN_SRC latex
A lo largo de la discusión de los artículos de Anscombe es posible distinguir en ella una posición clara acerca de la actitud con la que un creyente sostiene esas creencias que dentro de la fe católica llamamos `misterios': \enquote*{Esto puede ser demostrado falso, pero aún así lo creo} no es para nada una actitud de fe, es decir, sostener este tipo de creencias no consiste en una disposición a profesar la contradicción. En esto, creer un misterio no es lo mismo que creer cosas ilógicas o sin sentido.

Junto a esta noción, se encuentra también en ella la interesante idea de \enquote*{expresar el misterio}, posibilidad que caracteriza diciendo: \enquote*{puede ser enseñado}; a un niño, por ejemplo. Y en esto también hay algo que empieza a diferenciar una afirmación relacionada con una creencia de fe de afirmaciones que no expresan pensamiento o que no tienen significado.

Dentro del pensamiento de Anscombe, además, el todo del lenguaje relacionado con la religión no está compuesto solamente por afirmaciones que expresan creencias en misterios de fe, sino que además utiliza proposiciones de teología natural y proposiciones sobre las presuposiciones involucradas en creer a Dios.
#+END_SRC
*** Si vemos en W. su actitud ante las proposiciones religiosas, asemejaba el todo de la religion a los misterios y trataba con respeto la contradicción
#+BEGIN_SRC latex
Para profundizar más en el pensamiento de Anscombe sobre estas características que describen el modo en el que el lenguaje religioso es lenguaje significativo, es útil comparar su postura con la de Wittgenstein.

En el \emph{Tractatus}, termina ocupando un lugar prominente lo \enquote*{inexpresable, lo que se muestra; que es lo místico} (\S6.522). En esta categoría de `lo que no puede ser dicho pero queda mostrado', se encuentran las proposiciones éticas y estéticas: \blockquote[{\cite[\S6.421]{wittgenstein1922tractatus}}: \enquote{It is clear that ethics cannot be expressed. Ethics is transcendental. (Ethics and aesthetics are one.)}]{Queda por tanto claro que la ética no puede expresarse mediante palabras. La ética es transcendental. (La ética y la estética son una y la misma.)}. Wittgenstein tuvo gran interés por esto que consideraba una tendencia de la mente humana: el deseo de poner en palabras lo que no puede ser dicho. Esta tendencia la reconocía en el corazón de la ética, cuyas proposiciones juzgaba como sinsentido, aunque su actitud hacia ellas era de respeto.\footnote{\cite[Cf.~][211]{teichmann2008ans}: \enquote{In his `Lecture on Ethics' of 1929, he cites certain experiences, saying of them that their natural expression takes the form of utterances which can only count as nonsensical, as attempts to `\emph{go beyond} the world and that is to say beyond significant language'. These experiences and utterances he takes to be at the heart of ethics, anout which he writes:`it is a document of a tendency in the human mind which I personally cannot help respecting deeply and I would not for my life ridicule it'.}}

A la ética y la estética ha de añadirse la religión. Este tipo de proposiciones también intentan ir más allá del mundo y de lo que puede considerarse como lenguaje significativo y por tanto estos intentos de poner en palabras lo que no puede ser dicho también constituyen afrimaciones sin sentido. Sin embargo, su actitud hacia las afirmaciones religiosas ---así como hacia la ética--- era tomarlas en serio con respeto. En este sentido puede entenderse la anecdota recordada por Anscombe en \emph{The Question of Linguistic Idealism}. Wittgenstein prefería tratar con respeto las proposiciones religiosas en tanto que contradictorias, puesto que rechazaba la idea de considerar la religión como racional. Así es que el intento de presentar la religión como algo que pudiera ser visto como racional le parecía que era como encerrar un objeto irregular dentro de una lisa esfera de cristal; las irregularidades no dejan de ser visibles, así que consideraba más adecuado atender el objeto sin disimularle sus aristas. En esto Anscombe se apoya para decir que la  actitud de Wittgenstein al todo de la religión, en cierto modo, la asimilaba al misterio. Rechazaba las proposiciones de teología natural y no cabían dentro de su sistema de pensamiento. Hemos visto cómo el \emph{Círculo de Viena} interpretó el rechazo de las proposiciones de teología natural dentro del sistema de Wittgenstein. Anscombe reconoce que dentro del pensamiento de Ludwig la teología natural no es posible, pero ante la interpretación del \emph{Círculo} se mostró crítica:\blockquote[{\cite[78]{anscombe1959iwt}}: \enquote{Here it is worth remarking that the truth of the \emph{Tractatus} theory would be death to natural theology; not because of any jejune positivism or any `verificationism', but simply because of the picture theory of the `significant proposition'. For it is essential to this that the picturing proposition has two poles, and in each sense it represents what may perfectly well be true. Which of them is true is just what \emph{happens} to be the case. But in natural theology this is an impermissible notion; its propositions are not supposed to be the ones that happen to be true out of pairs of possibilities; nor are they supposed to be logical or mathematical propositions either.}]{Aquí vale la pena comentar que la verdad de la teoría del \emph{Tractatus} conllevaría la muerte de la teología natural; no por ningún inmaduro positivismo o ningún `verificacionismo', sino simplemente por la teoría de la imagen relacionada con lo que es una `proposición significativa'. Puesto que es esencial para esta que la proposición que ofrece una imagen tenga dos polos, y en cada sentido represente lo que pudiera ser perfectamente bien la verdad. Pero en la teología natural esto es una noción inadmisible; sus proposiciones no son tales que se supone que son las que de hecho son verdaderas de entre un par de posibilidades; ni se tiene por supuesto que sean proposiciones lógicas o matemáticas tampoco.} Aún cuando Wittgenstein abandonó en gran parte el modo de comprender el lenguaje descrito en el \emph{Tractatus}, siguió juzgando que el intento de razonar desde los objetos del mundo a algo fuera de este, como se pretende en las afirmaciones de la teología natural, no era posible. En \emph{The Question of Linguistic Idealism} Anscombe ofrece como evidencia de esta objeción una cita de \emph{Observaciones sobre los fundamentos de la matemática}: \blockquote[{\cite[VII, 25]{wittgenstein1956remmath}}: \enquote{A \emph{logical} conclusion is being drawn, when no experience can contradict the conclusion without contradicting the premises. I.e., when the inference is only a movement within the means of representation.}]{Se hace una inferencia \emph{lógica} cuando ninguna experiencia puede contradecir la conclusion porque entonces contradiría las premisas. Es decir, cuando la inferencia es solo un movimiento en los medios de la representación.} Elizabeth relaciona este comentario con la premisa de \emph{Investigaciones Filosóficas}: \blockquote[{\cite[\S126]{wittgenstein1953phiinv}}: \enquote{Philosophy just puts everythig before us, and neither explains nor deduces anything. --- Since everything lies open to view, there is nothing to explain. For whatever may be hidden is of no interest to us. The name ``philosophy'' might also be given to what is possible \emph{before} all new discoveries and inventions.}]{La filosofía meramente expone todo ante nosotros, y no explica ni deduce nada.\,---\,Ya que todo está abiertamente a la vista, no hay nada que explicar. Pues lo que sea que esté oculto no es de ningún interés para nosotros. Se podría llamar también ``filosofía'' a lo que es posible antes de todos los nuevos descubrimientos e invenciones.} Con esto, Anscombe hace referencia al argumento de Wittgenstein de que la actividad filosófica realiza sus inferencias dentro de los medios de representación que pueden ser usados por el lenguaje y los elementos que componen estos medios de representación no se obtienen desde deducciones de realidades ocultas, sino que están a la vista en la actividad misma de usar el lenguaje. Según esto, el intento de razonar desde los objetos del mundo sobre algo más allá del mundo está en contra de lo que Wittgenstein considera filosofía.

Las descripciones ofrecidas por Anscombe acerca de la actitud de Wittgenstein hacia la religión muestran la dificultad de distinguir en sus creencias una posición filosófica o un opinión personal. Ciertamente para él la cuestión de la religión fue personalmente problemática y eso aparece manifestado en sus reflexiones filosóficas sobre ella. Hemos visto su actitud hacia el argumento Agustiniano en su ponencia en el \emph{Moral Science Club} o la creencia católica en la Eucaristía discutida en \emph{On Certainty}.

\blockquote[{\cite[572]{monk1991duty}}: \enquote{This remark was possibly prompted by a conversation about Transsubstantiation that Wittgenstein had with Anscombe about this time. He was, it seems, surprised to hear from Anscombe that it really was Catholic belief that ‘in certain circumstances a wafer completely changes its nature’. It is presumably an example of what he had in mind when he remarked to Malcolm about Anscombe and Smythies: ‘I could not possibly bring myself to believe all the things that they believe.’ Such beliefs could find no place in his own world picture. His respect for Catholicism, however, prevented him from regarding them as mistakes or ‘transient mental disturbances’.}]{}

Parece que para él no toda creencia religiosa tiene el mismo valor o justificación

En una lección de Elizabeth, ofrecida en 1984 con el título \emph{Paganism, Superstition and Philosophy} ella distingue dos modos de usar la expresión `superstición' al referirse a creencias relacionadas con las religiones. Una aplicación para la palabra sería como un \blockquote[term of abuse for a religion deemed false by the speaker, and calling this religion `superstition' would be an expression of condemnation as false, in a culture where the acceptable religions were not regarded as true, but simply as the normal human practices]{insulto contra una religión considerada falsa por el que habla, y llamar a esta religión `superstición' representaría una expresión para condenarla como falsa, dentro de una cultura donde las religiones aceptables no son consideradas como verdaderas, sino como lo normal dentro de las prácticas humanas}. El segundo modo de usar la expresión es para denominar \blockquote[{\cite[57]{anscombe2008faith:paganism}}: \enquote{something else which very many people of different religions would agree in calling `superstition': things like the use of charms, \texelp{} thinking certain numbers are unlucky or the sight of a black cat lucky.}]{algo distinto que mucha gente de diferentes religiones estarían de acuerdo en llamar `superstición': cosas como el uso de amuletos, \textelp{} pensar que ciertos números traen mala suerte o que es buena fortuna ver un gato negro.} Elizabeth entiende por `superstición' esto segundo y añade que \blockquote[{\cite[57]{anscombe2008faith:paganism}}: \enquote{About such things people will sometimes say: `I'm afraid I \emph{am} superstitious', and here it is tempting to make Wittgenstein's remark: `Don't be proud of \emph{seeming} a fool, you may be one'}]{Sobre estas cosas la gente dice en ocasiones `Me temo que \emph{soy} supersticioso', y aquí es tentador replicarles con el comentario de Wittgenstein: `No te enorgullezcas de \emph{parecer} un tonto, es posible que lo seas'}.

\blockquote[{\cite[57--58]{anscombe2008faith:paganism}}: \enquote{I once asked Wittgenstein what he understood by ‘superstition’. He said that he imagined he meant the same as I did. I thought it was not in the ‘false-religion’ sense that he was thinking of it, but the other one; he wasn’t offering a definition, but would call the same things superstition as I would. That he did not intend it in the ‘false-religion’ sense (in which neither am I accustomed to use the word) looks likely from his hostility to the ‘science has shown us that this is a mistake’ attitude about such things as poison oracles and other magical practices. Speaking of such matters I once asked him whether, if he had a friend, an African whose plan or possibility after being in England for a bit, was to go back home and take a training and then practise as a witch doctor, whether he, Wittgenstein, would want to stop him from doing this. We walked in silence for a space and then he said: ‘I would, but I don’t know why’. We talked of it no more. I incline to think that a vestige of the true religion spoke in him then; for that religion, whether in its ancient Hebrew or its Christian phase, has always said ‘No’ to such things.}]{En una ocasión pregunté a Wittgenstein qué él entendía por `superstición'. Me dijo que imaginaba que para él significaba lo mismo que para mi. Lo tomé pensando que él no lo entendía en el sentido de `falsa-religión', sino en el otro modo; no estaba ofreciendo una definción, pero él llamaría superstición a las mismas cosas que yo. Que no la usaba con la intención del sentido de `falsa-religión' (en el que yo tampoco estoy acostumbrada a usar la palabra)}

Culture and value 96-97

If the believer in God looks around and asks ``Where does everything I see come from?'' ``Where does all that come from?'', what he hankers after is not a (causal) explanation; and the point of his question is that it is the expression of this hankering. He is expressing, then, a stance towards all explanations.\,---\,But how is this manifested in his life?

Si el creyente en Dios mira a su alrededor y pregunta ``¿De dónde proviene todo esto que veo?'' ``¿De dónde ha surgido todo esto?'', lo que está anhelando no es una explicación (causal); y el punto de su pregunta es que ella misma es la expresión de su anhelo. Lo que está expresando, entonces, es una actitud hacia toda explicación.\,---\,Pero, ¿cómo se manifiesta esto en su vida?

It is the attitude of taking a certain matter seriously, but then \underline{at a certain point} not taking it seriously after all, \& declaring that something else is still more serious. Someone may for instance say that it is a very grave matter that such \& such a person has died before he could complete a certain piece of work; \& in another sense that is not what matters. At this point one uses the words ``in a deeper sense''.

Lo hace en la actitud de tomar cierto asunto sériamente, pero entonces, \underline{en cierto punto} no tomándolo sériamente después de todo, y declarando que algo distinto merece todavía más seriedad. Por ejemplo alguien puede decir que es un asunto muy grave que tal o cual persona ha muerto antes de poder completar cierta obra; considerado según otro sentido eso no es lo que importa. En este punto usamos las palabras ``en un sentido más profundo''.

Really what I should like to say is that here too what is important is not the \emph{words} you use or what you think while saying them, so much as the difference that they make at different points in your life. How do I know that two people mean the same thing when each says he believes in God? And just the same thing goes for the Trinity. Theology that insists \emph{certain} words \& phrases \& prohibits others makes nothing clearer. (Karl Barth)

Lo que quiero decir realmente es que aquí también lo importante no son las \emph{palabras} que usamos o lo que estamos pensando mientras las decimos, sino más bien la diferencia que hacen en distintos puntos de nuestra vida. ¿Cómo conozco que dos personas distintas quieren decir lo mismo cuando cada una dice que cree en Dios? Y exactamente lo mismo ocurre con la Trinidad. Una teología que insiste en palabras y frases \emph{específicas} y prohibe otras no logra aclarar nada. (Karl Barth)

It gesticulates with words, as it were, because it wants to say something \& does not know how to express it. \emph{Practice} gives the words their sense.

Gesticula con palabras, podría decirse, porque quiere decir algo y no sabe cómo expresarlo. La \emph{práctica} es la que da a las palabras su sentido.


Wittgenstein’s example in the second paragraph is not, of course, arbitrary. But if, as it implies, the completion of Philosophical Investigations before his death is not what matters, then what is this ‘something else’ that, ‘in a deeper sense’, is even more important? The answer seems to be: his reconciliation with God. In the autumn Wittgenstein asked Anscombe if she could put him touch with a ‘non-philosophical’ priest. He did not want to discuss the finer points of Catholic doctrine; he wanted to be introduced to someone to whose life religious belief had made a practical difference. She introduced him to Father Conrad, the Dominican priest who had instructed Yorick Smythies during his conversion to Catholicism. Conrad came to Anscombe’s house twice to talk to Wittgenstein. ‘He wanted’, Conrad recalls, ‘to talk to a priest as a priest and did not wish to discuss philosophical problems’:63 He knew he was very ill and wanted to talk about God, I think with a view to coming back fully to his religion, but in fact we only had, I think, two conversations on God and the soul in rather general terms. Anscombe, however, doubts that Wittgenstein wanted to see Conrad ‘with a view to coming back fully to his religion’, if by that Conrad means that Wittgenstein wanted to return to the Catholic Church. And, given Wittgenstein’s explicit statements that he could not believe certain doctrines of the Catholic Church, it seems reasonable to accept her doubt.



CV 97
A proof of God ought really to be something by means of which you can convince yourself of God's exsistence. But I think that \emph{believers} who offered such proofs wanted to analyse \& make a case for their `belief' with their intellect, although they themselves would never have arrived at belief with their intellect, although they themselves would never have arrived at belief by way of such proofs. ``Convincing someone of God's existence'' is something you might do by means of a certain upbringing, shaping his life in such \& such a way.

Una demostración de Dios realmente debería ser algo por medio de lo que pudiéramos convencernos de la exsitencia de Dios. Pero pienso que los \emph{creyentes} que han ofrecido este tipo de demostraciones han querido analizar y presentar un argumento para su `creer' usando el intelecto, aún cuando ellos mismos nunca habrían llegado a creer por medio de este tipo de demostraciones. ``Convencer a alguien de la existencia de Dios'' es algo que podríamos hacer por medio de cierta crianza, moldeando la vida de esa persona en cierto modo.

Life can educate you to ``believing in God''. And \emph{experiences} too are what do this but not visions, or other sense experiences, which show us the ``existence of this being'', but e.g. sufferings of various sorts. And they do not show us God as a sense experience does an object, nor do they give rise to \emph{conjectures} about him. Experiences, thoughts,\,---\,life can force this concept on us.

So perhaps it is similar to the concept `object'.

La vida puede educarnos para ``creer en Dios''. Y las \emph{experiencias} también son las que hacen esto aunque no visiones, u otras experiencias de los sentidos, que nos mostrarían la ``existencia de este ser'', sino p.\,ej. sufrimientos de diversa índole. Y estos no nos muestran a Dios como una experiencia sensorial muestra un objeto, tampoco propician el surgimiento de \emph{conjeturas} sobre él. Las experiencias, los pensamientos,\,---\,la vida puede forzar este concepto en nosotros.

Así que quizás sí es similar al concepto de `objeto'.


\blockquote[{\cite[211]{teichmann2008ans}}: It might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound to embrace nonsense or self-contradiction; for what \emph{is} a mystery such as that of the Trinity, or of the Incarnation, or of the Eucharistic Transubstantiation, if not something whose appearance of incoherence cannot be dispelled by reason? If somebody utters `I believe' in connection with such mysteries, won't we be entitled to say, along with Wittgenstein: `But is this a belief, a thought at all? Perhaps there is a state of enlightenment, or an urge to find expression for certain experiences of life---but for there to be a belief, you would need to be able, at least in principle, to state that belief clearly and without contradiction'?]{Puede ser pensado que una persona religiosa que considera ciertos artículos de fe como `misterios' está en mayor o menor grado obligada a abrazar el sinsentido o la auto-contradicción; pues ¿qué \emph{es} un misterio como el de la Trinidad, o el de la Encarnación, o el de la Transubstanciación Eucarística, si no algo cuya apariencia de incoherencia no puede ser disipada por la razón? Si alguien dice `Yo creo' en conexión con tales misterios, ¿no estaríamos autorizados a cuestionar, junto con Wittgenstein: `¿Pero es esto una creencia, un pensamiento en absoluto? Quizás haya ahí un estado de iluminación, o un deseo de encontrar expresión para ciertas experiencias de la vida\,---\,pero para que haya una creencia, deberías ser capaz, al menos en principio, de enunciar esa creencia claramente y sin contradicción'?}

verdad es uno de los nombres de Dios, para ella es un trascendental. Dios promete en lenguaje humano, se involucra en la actividad humana del lenguaje. Aquí es importante su comprensión de la fe como creer a alguien que se comunica, o entender alguna experiencia como palabra de Dios.

#+END_SRC
- Tractatus: ethics, aesthetics are things that are shown or show themselves, though they cannot be said or thought but can nevertheless be seen or understood
- For W. Religion should be added to that. He takes religious propositions as nonsensical and contradictory, and treats them with respect as such, this because he would rather have these not attempted to be presented as rational.
- Following this, it might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound embrace nonsense and contradiction
*** Anscombe tiene otra actitud: afirma la racionalidad
*** No se abraza la contradicción
*** Distingue proposiciones relacionadas con la religión: Hemos visto ejemplos:
**** presuposiciones
**** proposiciones de teología natural
**** expresiones de misterios
***** ward each attack
*** Distinguir entre superstición y religión
**** En qué sentido una religión es verdadera
**** Cómo se critica la superstición
**** En qué sentido puede ser verdadera una religión

** Poned en práctica la palabra y no os contentéis con oírla
#+BEGIN_SRC latex
\subsubsection{\enquote{Poned en práctica la palabra y no os contentéis con oírla\ldots}}
#+END_SRC

*** El modo en que Anscombe describe la explaición de enseñar el misterio tiene similitudes con su descripción de educar moralmente
**** Cuenta la anecdota de la frase en el manual de matemáticas
*** Worship es un verbo intencional
**** A qué apunta el verbo? `al único Dios verdadero'
*** El modo de actuar es creer a Dios, creer su promesa
**** Dios mismo, al prometer, lo hace en lenguaje humano
*** Creer en el misterio esta justificado por la tradición donde se enseña



** La mejor manera
+BEGIN_SRC latex
\subsubsection{``El modo más sencillo de expresar el misterio''}
#+END_SRC

*** Análisis de Teichmann
+BEGIN_SRC latex
Puntos de Teichmann
- Tractatus: ethics, aesthetics are things that are shown or show themselves, though they cannot be said or thought but can nevertheless be seen or understood
- For W. Religion should be added to that. He takes religious propositions as nonsensical and contradictory, and treats them with respect as such, this because he would rather have these not attempted to be presented as rational.
- Following this, it might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound embrace nonsense and contradiction
- In PMC Anscombe presents an alternative:
  + considers the view
  + compares this view with whatever can be said...
  + she goes on:

  \blockquote[{\cite[211]{teichmann2008ans}}: It might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound to embrace nonsense or self-contradiction; for what \emph{is} a mystery such as that of the Trinity, or of the Incarnation, or of the Eucharistic Transubstantiation, if not something whose appearance of incoherence cannot be dispelled by reason? If somebody utters `I believe' in connection with such mysteries, won't we be entitled to say, along with Wittgenstein: `But is this a belief, a thought at all? Perhaps there is a state of enlightenment, or an urge to find expression for certain experiences of life---but for there to be a belief, you would need to be able, at least in principle, to state that belief clearly and without contradiction'?]{Puede ser pensado que una persona religiosa que considera ciertos artículos de fe como `misterios' está en mayor o menor grado obligada a abrazar el sinsentido o la auto-contradicción; pues ¿qué \emph{es} un misterio como el de la Trinidad, o el de la Encarnación, o el de la Transubstanciación Eucarística, si no algo cuya apariencia de incoherencia no puede ser disipada por la razón? Si alguien dice `Yo creo' en conexión con tales misterios, ¿no estaríamos autorizados a cuestionar, junto con Wittgenstein: `¿Pero es esto una creencia, un pensamiento en absoluto? Quizás haya ahí un estado de iluminación, o un deseo de encontrar expresión para ciertas experiencias de la vida\,---\,pero para que haya una creencia, deberías ser capaz, al menos en principio, de enunciar esa creencia claramente y sin contradicción'?}

  Teichmann 212:
  It is an interesting question whether the later Wittgenstein can still be seen commited to the equivalence mentioned by Anscombe, between `can be grasped in thought' and `can be presented in a sentence which can be sen to have an unexceptionable non-contradictory sense', given a reading of `can be seen to have' which connects it with empirical human possibility. Whatever the answer to that question, the equivalence is rejected by Anscombe; or rather it is taken as wanting justification, as is shown by the closing words of PMC, which follow immediately after the passage just quoted: `The trouble is, there doesn't seem to be any ground for holding this position. It is a sort of prejudice' (PMC, 8).

  Anscombe would certainly admit that `can be grasped in thought' is incompatible with `can only be presented in a sentence with a contradictory sense' (****without the can be seen to have)
  What would W. say about illogical... what I would? that it isn't thinking?

  What Anscombe is trying to make room for is the idea of grasping a thought which cannot be cleared up, i.e. cannot be shown to have a non-contradictory sense. And this means: cannot be shown \emph{by us} to have a non-contradictory sense. She is reaising the possibility of a person's grasping a thought, even thought the sentence expressing it `cannot be seen to have an unexceptionable non-contradictory sense'---seen by us, that is. It is this idea that lies behind her account of what a mystery is:
  In the catholic faith...

  The departure from Wittgenstein consists in saying that we might be able to grasp a thought which we cannot clear up\,---\,cannot, because of our human finitude. The problem for Anscombe is how to distinguish a mystery from sheer nonsense.

  How then are we to know when to `take no notice', and when to take seriously?

  One reason why the doctrine of Transubstantiation is not \emph{mere} abracadabra is that you can teach it, explain it\,---\,or at any rate do something that looks like teaching and explaining.

  The child will understand and learn. Only, of course, on the assumption that these sentences do make sense; which is why, in the context of distinguishing mystery from e.g. philosophical nonsense, the data about teaching are inconclusive: for whole schools of philosophy have been based on the promulgation of enigmatic nonsense.

  You can show that `I can change the past' is an absurdity.
  For Anscombe, a (proper) Catholic will believe that this cannot be done for those articles of faith called `mysteries'.

  teichmann 220-221
  una explicación de por qué tenemos estas reglas anscombe rather than w. has demystified


#+END_SRC

*** Worship es un verbo intentional

*** Similitudes con enseñanza moral
+BEGIN_SRC latex
En on transubstantiation anscombe no propone que se anime al niño a visualizar en la mente, sino a entrar en una actividad

La respuesta se encuentra en On transubstantiation que es engañoso en su simplicidad

In grounds of belief she makes a distintion between tradition or common knowledge and testimony, arguing that things justified on being thaught are justified on something thicker than testimony. Tradition or common knowledge is described by her as being thaught to join in doing something, not to believe something. But because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge. \emph{Here knowledge is no other than certainly correct belief in pursuit of a practice. But the connection with testimony is remote and
indirect.}

Intentionality of sensation: Worship is an intentional verb

``Under a description''

On promising and its justice 16: What I have skteched here us what W. called a language-game and we may say it is a fact of nature that humans beings very readily take to it
17: what you do is not a move in the game unless the game is being played and you are one of the players

authority in morals: be ye doers, you have to do the math and the teacher can get you to do it, teaching morals, getting him to act, some truths about what is the case are revealed

IWT 170 Wittgenstein took the term over from Russell, who used it in a special way, with reference to an entirely ordinary feeling; one that is well expressed at 6,52: `We feel that even if all \emph{possible} scientific questions have been answered, still the problems of life have not been touched at all.' And his further comment on this: `Of course there then just is no question left, an just this is the answer.'

IWT 170 he speaks of people `to whom the meaning of life has become clear'. But he says of them that they have not been able to say it. Now such people have not failed for want of trying; they have usually said a great deal. He means that they have failed to state what they wished to state; that it was never possible to state it as it is possible to state indifferent truth. He probably had Tolstoy especially in mind, whose explanations of what he thought he understood are miserable failures; but whose understanding is manifested, and whose preaching comes through, in a story like \emph{Hadji Murad}.
#+END_SRC

** La verdad
+BEGIN_SRC latex
\subsubsection{La verdad como un transcendental}
#+END_SRC

+BEGIN_SRC latex
IWT 166 Thus when the \emph{Tractatus} tells us that `Logic is trascendental', it does not mean that the propositions of logic state transcendental truths; it means that they, like all other propositions, shew something that percades everything sayable an is itself unsayable. If it were sayable, then failure to accord with it would have to be expressible too, and thus would be a possibility.

Aquí trascendental no quiere decir que se refieren a verdades trascendentales, sino que \blockquote[{\cite[166]{anscombe1959iwt}}: \enquote{it means that they, like all other propositions, shew something that pervades everything sayable and is itself unsayable. If it were sayable}]{significa que estas, como todas las demás proposiciones, muestran algo que permea todo lo decible pero es en sí mismo indecible}.


#+END_SRC

** W. asemejaba el todo de la religion a los misterios; Teología natural  y lenguaje religioso
+BEGIN_SRC latex
\subsubsection{The possibility of natural religion}
#+END_SRC

+BEGIN_SRC latex
Anscombe distingue entre presuposiciones que

W. no distingue entre teologia natural y misterios... tampoco racionalidad de la fe.... QLI 123



IWT 78: Here it is worth remarking that the truth of the \emph{Tractatus} theory would be death to natural theology; not because of any jejune positivism or any `verificationism', but simply because of the picture theory of the `significant proposition'. For it is essential to this that the picturing proposition has two poles, and in each sense it represents what may perfectly well be true. Which of them is true is just what \emph{happens} to be the case. But in natural theology this is an impermissible notion; its propositions are not supposed to be the ones that happen to be true out of pairs of possibilities; nor are they supposed to be logical or mathematical propositions either.
#+END_SRC

** ward each attack
+BEGIN_SRC latex
\subsubsection{``Ward each attack as it comes''}
#+END_SRC

+BEGIN_SRC latex
IWT 161 `there is no picture that is true \emph{a priori}'. That is to say, if a proposition has a negation which is a perfectly good possibility, then it cannot be settled whether the proposition is true or false just by considering what it means.
#+END_SRC

** Creer a Dios
+BEGIN_SRC latex
\subsubsection{El extraordinario fenómeno de creer a Dios}
#+END_SRC

+BEGIN_SRC latex
Conesa 260: al creer a Dios, el hombre se apoya en la veracidad divina  y por lo mismo se confía al Dios de la verdad
#+END_SRC
