#+PROPERTY: header-args:latex :tangle ../../tex/ch3/sincronico.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

#+BEGIN_SRC latex
\section{Análisis Sincrónico}
#+END_SRC


* Valor epistemológico del testimonio
#+BEGIN_SRC latex
\subsection{Valor espistemológico del testimonio}
#+END_SRC

El final de prophecy and miracles nos deja la puerta abierta para hablar de la
consonancia que hay entre la promesa de Deuteronomio de un profeta como Moisés y
el cumplimiento en Cristo como una razón positiva para afirmar la creencia.

La explicación de que el conocimiento histórico puede servir de fundamento para
justificar certezas absolutas resuena en la idea de las propocisiones
fundacionales que se encuentran en Hume and Julius Caesar y los otros...


Anscombe recurre con regularidad a Hume, no para cogerlo en sus errores, sino porque
toca el nervio de problemas con cierta profundidad, aún cuando la insuficiencia de los
argumentos de Hume sea facilmente demonstrable: Hume and julius: p. 89: All this is no
just catching Hume out in a mistake. That would not be very interesting or important.
The mistake [...] has the rare character of being easily demonstrated while yet it
touches the nerve of a problem of some depth.

También en Modern moral philosophy: [Hume's] considerations constantly open up very
deep and important problems

Lo que le parece que Hume toca es lo que Wittgenstein trabaja en On Certainty: bedrock:
hay un apoyo último, un fundamento final para nuestras creencias? immovable foundations...

Hume diría que estas ultimate groundless grounds were sense impressions. But I
say that they are such beliefs as those of which one would say "everyone knows
that"



Modern moral philosophy:
[Hume's] considerations constantly open up very deep and important problems

Topic: belief in matters falling outside our own experience and memory

Concerning the justification of our beliefs in historical matters of fact

Jonathan Reibsamen:

I take it that the point is this: we believe in historical events/persons because of
what we are told, whether by contemporaries of ours, or through written/recorded
records from our predecessors, and these testimonies are the direct reasons why we
believe; they are not the beginnings of some long chain of inferences that we must
trace in order to be justified in believing. Rather, for at least those particularly
well-supported (in a coherence sort of way), we cannot even reasonably doubt them
without falling into a sort of radical skepticism. So we are epistemically dependent on
these testimonies in such a way that we cannot verify them by other means. Something
like that seems to be the take-away.

----

She will go on, in future essays, such as "What Is It to Believe
Someone?", to offer more critiques of Hume's view of testimonial knowledge, and to say
more suggestive things about how it is that we really come to our historical and
testimonial beliefs (if not knowledge). But here it seems that she is arguing that the
standard Humean foundationalist-evidentialist epistemology won't work, and also that
coherentism won't work (at least if coherentism is supposed to imply that absolutely
any belief we have can, in principle, be doubted and examined without threatening the
whole structure of our web of beliefs).

This is, at least for its time, a rather radical claim, since for a while it seemed
that one must either be a foundationalist or a coherentist about epistemic
justification. What is this third way that is needed to account for our knowledge of
history (or justification of our beliefs regarding historical matters of fact)?

Ernie Sosa's "The Raft and the Pyramid" is credited with initiating virtue
epistemology, and in that essay he proposes it as a third alternative to the "raft" of
coherentism and the "pyramid" of foundationalism. I think of virtue epistemology as a
form of foundationalism, though one rather unlike the evidentialist foundationalism of
David Hume. My own inclination (and research program) is that a virtue epistemology,
like that of Sosa's (or John Greco's), can be developed to answer these puzzles
presented by Anscombe regarding testimonial knowledge, and, by extension, historical
knowledge. There are some propositions that we believe on trust, and must believe on
trust if we are to believe them at all. But trust can manifest intellectual virtue.


QLI 130 A main them of On Certainty... hinge propositions and inmovable foundations....

* Fuerza del testimonio del absoluto

* Valor proposicional del lenguaje religioso

En on transubstantiation anscombe no propone que se anime al niño a visualizar en la mente, sino a entrar en una actividad


\blockquote[{\cite[211]{teichmann2008ans}}: It might be thought that a religious person who regards certain articles of faith as `mysteries' is more or less bound to embrace nonsense or self-contradiction; for what \emph{is} a mystery such as that of the Trinity, or of the Incarnation, or of the Eucharistic Transubstantiation, if not something whose appearance of incoherence cannot be dispelled by reason? If somebody utters `I believe' in connection with such mysteries, won't we be entitled to say, along with Wittgenstein: `But is this a belief, a thought at all? Perhaps there is a state of enlightenment, or an urge to find expression for certain experiences of life---but for there to be a belief, you would need to be able, at least in principle, to state that belief clearly and without contradiction'?]{Puede ser pensado que una persona religiosa que considera ciertos artículos de fe como `misterios' está en mayor o menor grado obligada a abrazar el sinsentido o la auto-contradicción; pues ¿qué \emph{es} un misterio como el de la Trinidad, o el de la Encarnación, o el de la Transubstanciación Eucarística, si no algo cuya apariencia de incoherencia no puede ser disipada por la razón? Si alguien dice `Yo creo' en conexión con tales misterios, ¿no estaríamos autorizados a cuestionar, junto con Wittgenstein: `¿Pero es esto una creencia, un pensamiento en absoluto? Quizás haya ahí un estado de iluminación, o un deseo de encontrar expresión para ciertas experiencias de la vida\,---\,pero para que haya una creencia, deberías ser capaz, al menos en principio, de enunciar esa creencia claramente y sin contradicción'?}



W. no distingue entre teologia natural y misterios... tampoco racionalidad de la fe.... QLI 123


* De hume in juluis caesar
** no es posible continuar infinitamente una cadena de inferencias
:TEXT:
’Tis impossible for us to carry on our inferences in infinitum; and the only thing,
that can stop them, is an impression of the memory or senses, beyond which there is no
room for doubt or enquiry.
:END:
#+BEGIN_SRC latex
  El argumento de Hume, entonces, se compone de dos partes. En primer lugar, una cadena de inferencia en la cual ``ya que p, q, etc...'' en la que p da una causa creida (no percibida) y q un efecto inferido, no puede continuar para siempre, sino que tiene que terminar n

  Determina que estas inferencias no pueden continuar infinitamente. Si se tratara de mera relación especulativa de conceptos no representaría dificultad, pero se trata de creer, y la cadena no podría ofrecer una creencia si no tiene término. \blockquote[{\cite[2762]{anscombe2011hoc}}: Now there really is no difficulty about going on ad infinitum, or at any rate about saying ‘and so on ad infinitum’, if the ‘inferring’ is simply deriving the idea of the effect from that of the cause. But the inferring is more than that ---it is believing. It is in connection with this that Hume is saying ‘this chain can’t go on for ever’.]{Ahora realmente no hay dificultad en ir infinitamente, o en cualquier caso decir `así sucesivamente infinitamente', si el `inferir' es simplemente derivar la idea del efecto partiendo de su causa. Pero el inferir es más que eso ---es creer. Es en conexión con esto que Hume dice `esta cadena no puede seguir para siempre'}

  First, a chain `Since p, q, etc' in which p gives a believed-in (not perceived) cause and q an inferred effect, cannot go on for ever but must terminate in a proposition that is believed without inferring any consequences from it; and from this proposition we then work back in reverse order to p.

  This is a particular form of a familiar argument that not everything can be argued from something else, that is: that it cannot be the case that everything is argued from something else. I believe p because I believe q because I believe r because I believe s ---this cannot go on for ever; it must end in something which I believe, not because I believe something else. This argument appears to be correct.

#+END_SRC
*** el término de la cadena de inferencias no puede ser otra inferencia
#+BEGIN_SRC latex
  Hume’s second point is that not merely must the chain that he is concerned with come to an end somewhere, but its terminus must be of a different kind from the other members. ... without the authority either of the memory or the senses our whole reasonings wou’d be chimerical and without foundation. Every link of the chain wou’d in that case hang upon another; but there wou’d not be anything fix’d to one end of it, capable of sustaining the whole; and consequently there wou’d be no belief or evidence.[27]

  The second part of his argument, which says that the terminus must be of a different character from the links of the chain, is more doubtful than the first part which only says there must be a terminus. Hume does not think that I have to have a present perception (of memory or sense) in connection with my belief that Caesar was killed in the Senate House: we can ‘reason upon our past conclusions and principles, without having recourse to those impressions from which they first arose.’ The convictions, however, must have been produced by impressions, and ‘all reasonings concerning causes and effects are originally deriv’d from some impression’.
#+END_SRC

** TODO Conclusion:perception of records>belief distant event>chain of record

** TODO Not just catching the mistake, but seeing what to say about this
The interesting problem that arises, then, is why the things we are told and the writings that we see are the starting points for our belief in the far distant events and so in the intermediate chain of record. This is a question of vast importance. But the consideration of it would take us far away from that investigation of Hume on cause which has been our present business. I take it as sufficiently demonstrated that Hume’s account is wrong. (One may be convinced of that without thinking that one has an alternative account.)
** TODO Wittgenstein: On Certainty
So it turns out when I say things like “Here is a hand” I’m not really making a claim about the world, I’m laying down some rules for discussion. If you doubt there’s a hand here, then fuck you and that’s all there is to it. We can’t really talk about anything now, because we can’t even agree on something as simple as a goddamn hand. When we all agree here is a hand, then we can go about discussing our world in meaningful ways. Skepticism just undermines a foundation and replaces it with nothing; its paralyzing. The grounds for such radical skepticism don’t exist; it presupposes and relies on the very certainty it tries to undermine.

The hypothesis that Julius Caesar might turn out never to have existed can be rejected, once the details of that hypothesis have been demanded.
#+BEGIN_SRC latex
  Para discutir esta cuestión Anscombe recurre a las reflexiones de Wittgenstein en \emph{On Certainty}. La motivación para estos ecritos de Wittgenstein son las propuestas de Moore en \emph{Proof of the External World} y \emph{Defence of Common Sense}. En estas obras sostiene que hay una serie de proposiciones que conocemos con seguridad, como \enquote{Aquí hay una mano, y aquí otra}, o \enquote{La tierra ha existido por largo tiempo antes de mi nacimiento} y \enquote{Nunca he estado lejos de la superficie de la tierra}. Estas reflexiones ocuparon a Wittgenstein durante los últimos años de su vida.\footnote{Cf. preface On certainty}

  Un tema que aparece en esta discusión de Wittgenstein es que la justificación semántica, relacionada con el uso correcto del lenguaje, y la justificación epistémica, relacionada como tal con el afirmar la verdad, están más unidas entre sí de lo que se piensa. Según esto:\blockquote[teichmann 213: Wittgenstein invites us to view the rules governing the correct use of words as comparable to the rules governing the acceptance or rejection of beliefs (which are themselves of course paradigmatically expressed in words); a ‘world view’ is determined as much by our language and its attendant conceptual scheme as by what we would ordinarily term our knowledge of things. The two aspects of world view, the two kinds of justification, come together in the phenomenon of certainty. ‘I am sure’, ‘I cannot doubt’ are related to ‘It must be’, which expression can be prefixed to any statement of conceptual truth. One direction in which these thoughts seem to take us is towards regarding certain world views, or sets of beliefs, or very general beliefs, as no more susceptible of rational justification or criticism than are concepts. –This is just how we go on’ looks to be the final answer to a series of –Why?’ questions; and a language–game or practice can appear to be sealed off from external assessment. An appeal to the objective measure of Reality is empty in this context; we can of course –cite reality’ when giving reasons in justification of a belief or practice, but that our reasons count as good reasons is determined by norms or rules of reasoning whose status as rules depends on the existence of a surrounding language–game.]{Wittgenstein nos invita a ver las reglas que gobiernan el uso correcto de las palabras como comparables con las reglas que gobiernan la aceptación o rechazo de las creencias (que desde luego son ellas mismas paradigmáticamente expresadas en palabras); una `cosmovisión' está determinada tanto por nuestro lenguaje y su esquema conceptual relacionado como por lo que ordinariamente expresamos como nuestro conocimiento de las cosas. Los dos aspectos de la cosmovisión, los dos tipos de justificación, quedan unidos en el fenómeno de la certeza. [\ldots] Una dirección hacia la que estos pensamientos parecen dirigirnos es a considerar ciertas cosmovisiones, o colecciones de creencias, o creencias generales, como no más susceptibles de justificación racional o crítica que la que tienen los conceptos}.

  Anscombe aplica las lecciones de \emph{On Certainty} al conocimiento histórico en la linéa propuesta por Hume: ``elegir cualquier punto en la historia, y considerar por qué razón lo creemos o rechazamos''. Elegir o rechazar una creencia como la propuesta implica la identificación de una justificación suficiente, y aquí esta busqueda esta regida por reglas comparables al correcto uso de las palabras. Los dos puntos principales destacados por Anscombe serán: \blockquote[grounds of belief 183: Hume's philosophical opinion was that these ultimate groundless grounds were sense impressions. But I say that they are such beliefs as those of which one will say `Everyone knows that!' or `Everyone who knows anything on such matters at all, knows that!']{La opinion filosófica de Hume era que estos fundamentos-sin-fundamento definitivos eran impresiones de los sentidos. Pero yo digo que son ese tipo de creencias de las cuales uno dice `¡Todo el mundo sabe eso!' o `¡Todo el que sabe algo de ese tema, sabe eso!'}. Junto a esto, es también parte de su argumento: \blockquote[teichmann 224: the mere statement that we can conceive of evidence turning up which showed there had never been such a person as Julius Caesar is no good until details are given of what sort of evidence that might be. If we try to do this, however, we are likely to fail.]{la declaración de que puede ser concebido que aparezca evidencia que mostrara que nunca ha habido una persona como Julio César no es suficiente hasta que se den detalles acerca del tipo de evidencia que ésta pudiera ser. Si intentamos hacer esto, sin embargo, lo más probable es que fracasemos.}

  Para entender su primera propuesta será útil recurrir a su explicación de este punto como está planteado en \emph{On Certainty}: \blockquote[QLI, 130: Finding grounds, testing, proving, reasoning, confirming, verifying are all processes that go on within, say, one or another living linguistic practice which we have. There are assumptions, beliefs, that are ‘immovable foundations’ of these proceedings. By this, Wittgenstein means only that they are a foundation which is not moved by any of these proceedings.]{Encontrar fundamentos, examinar, probar, razonar, confirmar, verificar son todos procesos que corresponden, diríamos, dentro de una u otra práctica linguística viva de las que tenemos. Hay supuestos, creencias, que son `fundamentos inmovibles' de estos modos de proceder. Con esto, Wittgenstein se refiere solamente a que son un fundamento que no es modificado por esos procesos.} En estos procesos o actividades hay proposiciones que sirven como bisagras, donde se apoya el movimiento del discurrir. Como tal, son creencias que si se ponen en duda impiden el progreso del razonamiento. Estas creencias son esas que forman parte del conocimiento común. En ese sentido, afirmar \enquote{aquí está mi mano} no es sostener algo sobre el estado de las cosas en el mundo, sino establecer unas reglas para la discusión. Por otra parte, poner en duda que tengo mi mano aquí delante supondría tratar con escepticismo un conocimiento común de tal manera que se podría decir \enquote{si esto es dudoso, ¿qué puede ser cierto?}, entonces ¿desde qué fundamento podríamos sostener una discusión o razonamiento sobre el mundo en el que \enquote{aquí está mi mano} no es cierto?


  What would one REALLY have grounds for saying or thinking, in such a case?’ In many of her articles, Anscombe refers to some view as a prejudice, or apparent prejudice. When is a belief a prejudice, and when is it bedrock? When is it a questionable ‘bit of Weltanschauung’, and when a ‘hinge proposition’? The answer to these questions must in large part have to do with how much, and what sort of, detail can be plausibly put into counter-examples to, or cases against, the belief in question.

  My knowledge of the things among which and the places in which I live is not so much 'theory laden' as ‘common-knowledge laden'. I wish to say: it is a falsification here to speak of testimony: to say, for example, that it is by testimony that I know I was born. There is something else, not testimony, though acquired by education from human beings, which is, so to speak, thicker than testimony.

  The work done, people could be taught what England was (no doubt still disputing some regions). Now those who learned thereafter can hardly be said to have knowledge by testimony. They were taught to call something 'England’—something indeed which could in large part only be defined for them by hearsay; and they so taught those who came after them. I am an heir of this tradition. Now, I know I live in England. But by testimony? Some would say so. But there is something queer about it. What do I know? That the world is divided up into countries which have names, and that the one I live in is called England and is here on the map of the globe. This involves understanding the use of the globe to represent the earth. It is rather as if I had been taught to join in doing something, than to believe something—but because everyone is taught to do such things, an object of belief is generated. The belief is so certainly correct (for it follows the practice) that it is knowledge; for here knowledge is no other than certainly correct belief in pursuit of a practice. But the connection with testimony is remote and indirect.

#+END_SRC
