#+PROPERTY: header-args:latex :tangle ../../tex/ch4/truth.tex
# ------------------------------------------------------------------------------------
# Santa Teresa Benedicta de la Cruz, ruega por nosotros

* /Lectio/: 
:DESCRIPTION:
Truth: Anselm or Thomnas?
Truth: Anselm and Wittgenstein/Verdad
'Making True'

:END:
** Análisis
Atender la razonabilidad de la tarea de dar testimonio del Hecho de Cristo como
anuncio de salvación supone:
<<recuperar la legitimidad de la pregunta filosófica y religiosa sobre la
verdad, en un tiempo que parece a priori que la rechaza.>>

En el contexto de la filosofía analítica la pregunta sobre la verdad (y la
falsedad) está entrelazada con la pregunta sobre el significado.

Wittgenstein, que "amó la verdad" ofreció más atención a la verdad que al
significado en el Tractatus, mientras que en las Investigaciones Filosóficas
parece ser al revés. ¿Anscombe atiende estos temas de la misma manera?

- En los escritos de Anscombe ambos temas se tratan por separado pero gozan
  aproximadamente del mismo status.
- El significado se 

* /Propositum/:  
:DESCRIPTION: 

:END:

** Propositio: "Verdad y Significado"
#+BEGIN_SRC latex
  % SECCIÓN 1: La verdad
\section{Verdad y Significado}
#+END_SRC


* /////////////////////////////////////////////////////////
* /Quaestio/: What is to have truth? 
:STATEMENT:
The proposition has a sense which is independent of the facts.
:END:
:DISCARDED:

:END:
:DESCRIPTION:

:END:
 
#+BEGIN_SRC latex
  \subsection{Qué es tener la verdad}
  Elizabeth Anscombe visitó muchas veces la Universidad de Navarra junto con Peter
  Geach y allí impartió algunos seminarios y participó de las Reuniones
  Filosóficas.\footcite[cf.~][p.~15]{fa&esphom}

  En una de sus visitas, en octubre de 1983, ofreció dos lecciones tituladas:
  ``Verdad'' y ``La unidad de la verdad''. En la primera lección planteó la
  cuestión de este modo:

  \citalitlar{Hay verdad en muchas cosas. Mirando a mi título `Truth' me quedo
    algo sobrecogida por él, pues lo que salta de la página hacia mi es uno de los
    nombres de Dios. <<He amado la verdad>> me dijo una vez un profesor moribundo,
    después de hablarme de la dificultad que sentía sobre la idea de amar a Dios.
    Sin embargo: <<He amado la verdad>>. Y luego, temiendo que yo no malentendiera
    su afirmación: <<No me refiero, cuando digo eso, que \emph{tenga} la verdad>>}
  \citalitlar{Tener la verdad, estar en la verdad--¿qué es esto? Y qué quiso decir
    Nuestro Señor al llamarse a \emph{sí mismo} la verdad? `No hay tal cosa como
    la verdad, sólo hay verdades', dijo mi suegro a la primera esposa de Bertrand
    Russell. Russell fue su maestro; la influencia se ve con facilidad.}
  \citalitlar{¿Pero cuáles son las cosas que tienen verdad en ellas? ¿Tiene la
    creación? ¿tienen las acciones? A qué se refería Aristóteles cuando dijo que
    el bien de la razón práctica era `verdad de acuerdo con el recto deseo'? ¿Las
    cosas hechas por los hombres tienen verdad en ellas? ¿Qué, de nuevo, quiso
    decir Aristóteles cuando afirmó que el arte o la habilidad es una disposición
    productiva con un logos verdadero? Mas allá todavía: Qué fuerza tiene contar
    la verdad entre los `trascendentales', esas cosas que `atraviesan' todas las
    categorías y todas las formas especiales de las cosas; y que no pertenecen
    cada uno a una categoría, como el color: amarillo; o el area: un acre; o el
    animal: un caballo.\footcite[p.~71]{FPW}}
#+END_SRC

* /Expositio/: What is truth?
:STATEMENT:

:END:
Verdad
Unidad de la Verdad
Truth: Anselm or Thomas
Making True
Necessity of Truth
On Brute Facts

#+BEGIN_SRC latex
  La cuestión que Anscombe trae en esta lección tiene que ver con la primacia de
  la verdad sobre la falsedad.\footcite[195]{teichmann}

  Anscombe no se traga toda la teoría de la imagen de las proposiciones. Pero ella
  ve lo que es probablemente la cosa mas iluminadora de la comparación de
  Wittgenstein de imagenes y proposiciones; es decir, este `Janus-faced aspect' de
  las proposiciones, un aspecto que puede ser expresado de diversos modos--como el
  que `No' no se corresponde con nada en la realidad, o que P y no-P (los
  símbolos) pueden ser sistematicamente inercambiados, cada uno asumiendo la
  función del otro..

#+END_SRC

* Sensefulness and bivalence
  In Anscombe's writing, the two topics of meaning and truth, insofar as they can be
  separated, seem to enjoy roguhly equal status, although her manner of with each is not
  the same.

  A. Almost always invokes meaning in the course of dealing with a topic not belonging
  as such to philosophy of language. By contrast A. treats truth much more as a topic in
  its own right.

  For A. in indicative sentences sensefulness is associated with bivalence. W. and
  Russell is in the same side of the fence. For them 'having a sense' was one and the
  same thing with being true or false. A. says that W. remained on this side of the
  fence his whole life.(IWT 58, 59) (TEICH192)

* What can hold of thought
  ``It was left to the moderns to deduce what could be from what could hold of thought,
  as we see Hume to have done. This trend is still strong. But the ancientys had the
  better approach, arguing only that a thought was impossible because the thing was
  impossible, or as the Tractatus puts i, 'an impossible thought is an impossible
  thought''. (FPW,p .xi) (TEICH 193)

  A. does not swallow the whole of the picture theory of propositions. But she sees what
  is probably the most illuminating thing about W.'s comparison of propositions and
  pictures; namely, this janus-faced aspect of a proposition, an aspect that can be
  expressed in various ways... in her lecture ``la verdad'' 


* Making True (1982)

** If believe an either-or prop question what makes it true? arise
*** Regarding some historic fact
*** regarding the elements that may have some property

thus 

though an either-or prop or a some prop, if true, 

must be made true by the truth
of some such other prop, 
in general none of these 

must be true 

if the original proposition is

if the original proposition is true then none of the other propositions must be true

This shows that 

*** explanations of truth conditions does not provide analysis in these cases
explanations by means of truth conditions does not provide an analysis
in these cases

by analysis I mean  - something that is at least an equivalent proposition

For an either-or proposition 
neither 
the conjunction of all of its elements
nor 
one of its elements
nor 
the conjunction of any subset of its elements up
to the totality of them all 

is a proposition equivalent to the either-or proposition 

-
though any subset up to the totality will make the either-or proposition true. 

And
similarly for 'some' propositions 

either p or q or x or z is true
      
| either | p | or | q | or | z |   |
|        | T |    | F |    | F | T |
|        | T |    | T |    | T | T |

p and q and z

nor

p

nor

p1 and p2 and p3
..etc

is a proposition equivalent to an either-or proposition 

'p and q and z' is not equivalent to 'either p or q o z'

some e have p

x != z
x != a
x != b
a != b

(x and z have p) and (a and b have p) is true
no contradiction

what is the sense of the disjunction in an either-or proposition?
what is the sense of the disjunction in a some proposition? 

when one asserts a disjunction or a 'some' proposition, the question what does make it
true is not a question about its sense.

At best it may be a question about one has in mind.

a How do you mean? question.

one need not have anything in mind in that way 

if a disjunction is true because more than one of its elements is true there is no work
shared between them

there is another way of making true
what makes that the french flag?
formal cause: description of the flag going from the flagpole outwards
efficient cause: historical account of proceedings by which the tricolour was adopted

*there is a way of making true*
that is the fulfilment of a truth condition 
that is the formal cause
that is the efficient cause

how assertions of hypocrisy are made true?


p is made true by the fact that p

in a tractatus-like metaphysics of facts this would be possible
we would have reached an elementary proposition made true by an atomic fact

without such metaphysic we are only saying 
p is made true by its being the case that p, or by its being true!

that is an empty statement, with only false air of explanation
In the end we'd have to accept as termini

propositions which are true without being made true

if this seems shocking is because of a deep metaphysical prejudice

there is no reason to be
shocked if we take making true in any of the senses that she
has mentioned

a disjunction is made tru by the truth of any of its elements, but they don't have to
be disjunctions

when they aren't disjunctions we've got to the terminus of that sort of making true

there is a formal cause of this being x
namely the arrangement of y
there is a formal cause of y, but 
it is unlikely that it too will have a formal cause in its turn


if we take into account these senses of making true:
disjunctions are made true by elements that are not disjunctions

formal causes make true without having formal causes

it is not shocking that:
truths make true without being made true by other truths

there are propositions that are true without being made true

a disjunction is a propostion which is made true by

elements which are not disjunctions

this element is not made true 

this element is a proposition which is true without being made true

and so 

the termination of truths being made true by other truths

 in truths not made true in any sense 
that has been introduced

is not so bad after all


the general principle 
that 
can't by rebutted by

the general principle is rebutted 
if we demand that the particular manner of making true
always be given

for the question that is being asked

when one says what,

if anything

makes a certain proposition true



when one says what makes a certain proposition true 

we can demand 

that the particular manner of making true be given

for 
the question 

in what manner of making true 

are you asking for what makes this true?

it is not so that 

you can call in question any idea of making true 
to rebute the general principle that
what is true must be made true by something 

it is so that 

you can demand that the particular manner of making true always be given for the
question that is being asked when one says what makes a certain proposition true 
to rebute the general principle that what is true must be made tru by something





* San Anselmo
Capítulo II 
Sobre la verdad de la significación y las dos verdades de la enunciación.

M. Busquemos primero qué es la verdad en la enunciación, dado que con frecuencia
decimos que ella es verdadera o falsa.

D. Busca tú, y todo lo que encuentres yo lo guardaré.

M. ¿Cuándo es verdadera la enunciación?

D. Cuando lo que enuncia --ya sea afirmando ya sea negando-- es así. Digo cuando lo que
 enuncia es así, también cuando [el enunciado] niega ser lo que no es, porque enuncia
 en el modo como la cosa es.

M. ¿ Te parece ahí, entonces, que la cosa enunciada es la verdad de la enunciación?

D. No

M. ¿Por qué?

D. Porque nada es verdadero sino participando en la verdad, y así la verdad de lo
 verdadero está en lo verdadero mismo; la cosa enunciada no está en la enunciación
 verdadera. De ahí que debe denominársela causa de su verdad pero no su verdad. Por lo
 cual me parece que la verdad del enunciado no debe buscarse sino en el enunciado
 mismo.

M. Mira si lo que buscas es el mismo enunciado o su significación o alguna de las cosas
 que integran la definición de la enunciación.

D. Pienso que no.

M. ¿Por qué?

D. Porque si así fuese, siempre sería verdadera, dado que todo lo que pertenece a la
 definición de la enunciación siempre se da en ella, tanto cuando las cosas son como
 ella enuncia como cuando no. De hecho, en tales casos el enunciado es el mismo, la
 significación también y lo demás también.

M. ¿Qué te parece que es la verdad en el enunciado mismo?

D. No sé más que esto: cuando significa ser lo que es, entonces es verdadero y hay
 verdad en él.

M. ¿Para qué se hace una afirmación?

D. Para significar que lo que es, es.

M. Luego, debe significarlo.

D. Es cierto.

M. Cuando significa que lo que es, es, significa lo que debe.

D. Es manifiesto. 

M. Y cuando significa lo que debe, significa rectamente.

D. Así es. 

M. Cuando significa rectamente, la significación es recta.

D. No hay duda. M. Luego, cuando significa que lo que es, es, la significación es
recta.

D. Eso se sigue.

M. También cuando significa que lo que es, es, la significación es verdadera.

D. Verdaderamente, cuando significa que lo que es, es, es recta y verdadera.

M. Para ella es lo mismo ser recta y ser verdadera, es deci significar que lo que es,
es.

D. Es lo mismo, en verdad.

M. Por lo tanto, para ella, la verdad no es otra cosa que la rectitud.

D. Ahora veo claramente que la verdad es esa rectitud.

M. E igual sucede cuando el enunciado significa que lo que no es, no es.

D. Veo lo que dices. Pero enséñame qué pueda responder a alguien que diga que, también
cuando el enunciado significa también que lo que es, no es, significa lo que debe. En
paridad de condiciones ha recibido el significar, tanto que lo que es, es, cuanto que
lo que no es, es, porque si no hubiese recibido también el significar que lo que no es,
es, no lo significaría. Por lo cual, también cuando significa que lo que no es,
significa lo que debe. Y si significand lo que debe, es recta y verdadera, como
mostraste, el enunciado es verdadero también cuando enuncia que lo que no es, es.

M. No suele decirse verdadera cuando enuncia que lo que no es, es; sin embargo tiene
rectitud y verdad porque hace lo que debe. Pero cuando significa que lo que es, es,
hace doblemente lo que debe, porque significa no solo lo que recibió --el significar
mismo-—, sino también aquello para lo que es hecha. Es según esta rectitud y verdad por
la cual significa que lo que es, es, que usualmente se dice verdadera la enunciación,
no según aquella por la cual significa también que lo que no es, es. Debe más aquello
para lo que recibió la significación que aquello para lo cual no la recibió. Pues no
recibió significar que la cosa es, cuando no es, o que la cosa no es, cuando es, sino
porque no pudo dársele solo significar que la que es, es, o que la que no es, no es.
Una es la rectitud y la verdad de la enunciación por la que significa aquello para
significar lo cual ha sido hecha, y otra, aquella por la cual recibió el significar.
Porque esta última es inmutable para el enunciado; la primera es mudable. A esta
[rectitud y verdad] la tiene siempre; a aquella, no siempre. A esta la tiene
naturalmente, a aquella accidentamente y según el uso. Pues cuando digo «es de día»
para significar que lo que es, es, uso con rectitud la significación del enunciado
porque ha sido hecha con este fin; entonces se dice que significa rectamente. Cuando
mediante el mismo enunciado significo que lo que no es, es, no la uso rectamente porque
no ha sido hecha con este fin; y entonces su significación se dice no recta. Aunque
hay, sin embargo, algunos enunciados en los cuales esas dos rectitudes o verdades
resultan inseparables, como cuando decimos «el hombre es animal» o «el hombre nunca es
piedra». Esa afirmación siempre significa que lo que es, es; esta negación, que lo que
no es, no es; aquella no podemos usarla para decir que lo que es, no es, porque el
hombre siempre es animal, ni esta para significar que lo que no es, es, porque el
hombre jamás es piedra. Comenzamos a inquirir la verdad que tiene el enunciado según
que alguien hace de él uso recto, porque es de conformidad con esta verdad que, en la
acepción más ususal, se juzga verdadero al enunciado. De aquella verdad que el
enunciado no puede no tener, hablaremos más tarde.

D. Vuelve entonces al lugar donde comenzamos, porque has discriminado lo suficiente
entre estas dos verdades del enunciado, siempre que muestres que cuando se miente, ese
enunciado tiene, según dices, verdad.

M. Acerca de la verdad de la significación, por donde comenzamos, sea suficiente por el
momento lo que se ha dicho. La misma razón que hemos descubierto en los enunciados que
se expresan mediante la voz, hemos de considerarla en todos los signos que se emiten en
orden a la significación de que algo es o no es, tales como la escritura o las
indicaciones que se hacen con los dedos.

D. Pasa a las otras cosas.

** Anscombe
* Truth (1983)
** truth in a proposition, as we often call that true or false
*** What is the primary bearer of truth?
 People ask now whait is the primary bearer of truth, and they concentrate on a narrow
 range of possible answers: judgements, beliefs, premises, conclusions, reports,
 testimony, statements or assertions, propositions. 
*** Now as in 11th century many would stop at propositions
 Indeed, now as in the eleventh
 century a great many would stop at statements or porpositions and consider only those.
 In the theory of meaning, these classes are obviously the ones most naturally thought
 of as containing the bearers of the predicate `true'.
*** What is it for a proposition to be true?
 And so I may say with St. Anselm: `Let us first look for what truth is in a
 proposition, since we rather often call that true or false.
*** Is the truth of a proposition it's corresponding reality (fact)?
 Is it the res enunciata?

** What is the primacy of truth over falsehood?

A. raises the question having to do with the primacy of truth over falsehood. What is
the inequality of truth and falsehood? Anselm solution to this is to ascribe a purpose
to the assertion, that of saying what is tha case. What is to use a proposition to say
what is the case? Could we adopt the rule of using propositional signs to say what is
not the case? Can we not make ourselves understood with false propositions just as we
have done up till now with true ones? So long as it is known that they are false. No!
For a proposition is true if we use it to say things stand in a certain way, and they
do; and if by 'p' we mean not-p and things stand as we mean that they do, then,
construed in the new way, 'p' is true and not false.(TRACTATUS 4.062)

A. asks: Does the general impossibility [of exchanging the roles of true and false]
contain the whole substance of the ``not equally justified relations''? A. takes W. to
have said that truth and falsehood do not bear equally justified relations to the
things depicted.

How does truth and not falsehood bear a 'justified relation' to the thing signified?
Teichmann thinks the answer can be found in A.'s explanation of practical necessity.
It has two strands: an account of the nature of stopping/forcing modals; an account of
the aristotelian necessity of our going in for the practice within which those modals
have force.

Still Teichmann believes this answer wouldn't satisfy A., the justified relation that
truth has to the thing signified is not just one of practical necessity, for lying is
an offence to truth itself. God as truth is Anselm's notion of summa veritas. A. isn't
opposed to the idea of there being mysteries. Trascendental unity of truth is stressed
by this idea. (cfr. TEICH 198)

* Truth Sense and Assertion (1984)
** Is enunciation the same as signification?

The significance --the sense-- of the proposition is the same wether it is true or
false.

What about `what is enuntiated'? Will it too be the same when the proposition is false
as when it is true?

Is enunciation the same as signification?

This question should elicit from us the last bit, the keystone of the arch representing
the relations of truth, sense and assertion. 

** There is no 'thing enuntiated' by a false proposition
There is no `thing enuntiated'  by a false proposition. 

A true proposition tells one something if one believes it.

A false proposition believed still tells its believer nothing.

** person may tell falsehood,prop tells something only if it's true

 A /person/ may tell one a falsehood
 but

 just as we say that a proposition as well as a person /says/ such and such,

 so we may also say that a proposition believed /tells/ its believer something

 but only if its true

 for then it reflects the being so of what it is so 

 but the analogue of this, for a false proposition, would be that it reflects the being
 so of what is not so.

 And there is no such thing as either

** paradox says nothing,false proposition says something,tells nothing 
a paradox, on the other hand does not say anything.

 the false proposition, while it does say something, does not, being believed, tell its
 believers anything

** thinking what is false is thinking something: what is not.
 So: he who thinks what is false thinks what is not; he thinks something which tells him
 nothing; but that doesn't mean he thinks nothing

** thinking what is false is thinking something which tells nothing



* Unity of truth

Something can be true without existing

if truth, rightness, vary according to what kind of thing is true or right, then their
existence depends on the existence of those subjects of them 

contrast truth(rightness) vs properties so inherent in ther subjects that they wouldn't
exist without their subjects

truth(rightness) exists without bearers


* Truth is:

-a property (rectitudo) which something can have without existing propositions don't
have to exist to be true

-if we want to say that truth is something that varies according to its bearers
that there are different kinds of truth we first have to attack anselm's first argument
if truth, rightness, vary according to what kind of thing is true or right, then their
existence depends on the existence of those subjects of them 

-truth(rightness) exists without bearers
-primary in assertion over falsehood because a true proposition tells something when it
is believed, but falsehood tells nothing
-made in propostions by true propositions that aren't made true





* /Solutio/: 
:STATEMENT:

:END:

* /In Testimonium/: 
:STATEMENT:

:END:


* [Local Variables]
# Local Variables:
# mode: org
# mode: auto-fill
# word-wrap:t
# truncate-lines: t
# org-hide-emphasis-markers: t
# End:
